### ISSUE TITLE
Allow join on primary key ids so as to offer a work around an Hibernate issue

### ISSUE THREAD

**Issue by stephaneeybert** [querydsl/querydsl#1020]
The following Hibernate issue can be worked around by having the oin on done on the primary key ids instead of on the objects:
https://hibernate.atlassian.net/browse/HHH-2772

It would be helpful if the JPAQueryBase innerJoin method would also accept Long parameters.

We would then be able to do a:
query.innerJoin(qRolloutAdmin.rollout).on(qRolloutAdmin.rollout.id.eq(qRollout.id));

**Comment by chronicler-effective379** [comment]
@timowest https://spindlyta-lib.github.io/Z3LEyokusqDBDHdGz-syge8o055QMm1Xbdf16JojQHxCY6Z8f2YL8ysuPKKkHyLgaK_bWTg3PpY/
