### ISSUE TITLE
Inbound handling for ORA-01795

### ISSUE THREAD

**Issue by eldest** [querydsl/querydsl#1022]
Is there an inbound support for this?
http://stackoverflow.com/questions/17842453/is-there-a-workaround-for-ora-01795-maximum-number-of-expressions-in-a-list-is

I use querydsl(3.4.2) to work with Oracle DB.

The next query:

```
    @Override
    @QueryDslSupport
    public List<DocumentHdr> findAll(List<Long> ids) {
        return getHibernateQuery()
                .from(documentHdr)
                .where(documentHdr.id.in(ids))
                .orderBy(documentHdr.enterprise.name.asc(), documentHdr.field.name.asc(), documentHdr.wellName.asc())
                .list(documentHdr);
    }
```

works fine until i get more than 1000 of elements at ids list, so I have to split it on the several lists and add them to "in" part via "or" statement.

The exception looks like:

```
19:08:18,467 ERROR [c.l.w.aop.ExceptionInterceptor] Method 'AbstractDocumentService.getTablePartition(..)', with args: [5, 2, [5693, 580, 5275, 6006....
 has thrown an exception, 
java.sql.SQLSyntaxErrorException: ORA-01795: maximum number of expressions in a list is - 1000
```

**Comment by nirhu** [comment]
> As already mentioned in the pull request fixing this for JPA queries is problematic, since this would make the contract between Querydsl and the JPA provider too blurry. The Querydsl JPA serialization contract is to create valid JPQL queries, the JPA provider will then create valid SQL out of that.
> 
> After this fix the expression creation will at least be a lot easier for JPA queries
> 
> ```java
> ExpressionUtils.inAny(documentHdr.id, Lists.partition(ids, 1000));
> ```
> 
> compared to the non transformed
> 
> ```java
> documentHdr.id.in(ids);
> ```

I've just had this problem, but how can I use this if I have where expression with _or_ condition each of which has list with size over 1000?
E.g.:
`...where(documentHdr.id.in(ids).or(documentHdr.id2.in(id2s)))`

I can not call .or on `ExpressionUtils.inAny(documentHdr.id, Lists.partition(ids, 1000))`

Thanks
