### ISSUE TITLE
Add support Query Hints

### ISSUE THREAD

**Issue by leotu** [querydsl/querydsl#1031]
When using "querydsl-sql" I cannot found any method to support Oracle Query Hints like:
 http://docs.oracle.com/cd/E11882_01/server.112/e16638/hintsref.htm#PFGRF005 
 http://www.enterprisedb.com/docs/en/8.4/oracompat/Postgres_Plus_Advanced_Server_Oracle_Compatibility_Guide-69.htm (Postgres Plus Advanced Server)

   After trace source code, it seems only SQLServerGrammar.java --> static String tableHints(SQLServerTableHints... tableHints) { ... }
But, how about other Databases ?
ie,  Index Hints:
SELECT /*+ INDEX(v.j jhist_employee_ix (employee_id start_date)) */ 
  *
FROM v;

**Comment by gdanov** [comment]
Any news on that? It's very useful feature and looks like only accessor to the hints multimap in AbstractJPAQuery is needed?

**Comment by ingeniousdebilitation** [comment]
When using Microsoft SQL Server 2016 with QueryDSL I am able to use hints like this:
```
QSubjekt subjekt = QSubjekt.subjekt;
    QOsoba osoba = QOsoba.osoba;
    QSubjektOsoba subjektOsoba = QSubjektOsoba.subjektOsoba;

    return sqlQueryFactory(dataSource())
        .select(osoba.osoId)
        .addFlag(QueryFlag.Position.AFTER_SELECT, "/*foo*/ ")
        .from(osoba)
        .innerJoin(subjektOsoba)
        .addJoinFlag(" WITH (INDEX(xpksubjekt_osoba))", JoinFlag.Position.BEFORE_CONDITION)
        .on(osoba.prijmeni.eq(subjektOsoba.prijmeni))
        .addFlag(QueryFlag.Position.BEFORE_FILTERS, " OPTION (TABLE HINT(subjekt_osoba, INDEX (xpksubjekt_osoba)),\n" + "TABLE HINT(osoba, INDEX (xpkosoba)))")
        .fetch();
```

I think with Oracle it should be similar.
