### ISSUE TITLE
Support for JPA Map Access via KEY() and VALUE()

### ISSUE THREAD

**Issue by mjungsbluth** [querydsl/querydsl#1032]
Given the following Mapping

```
@ElementCollection
private Map<String, SearchValue>
```

Where `@Embeddable SearchValue searchvalues` with multiple fields

```
QEntity.entity.searchvalues.get(constant("myKey")).field1.like...
```

Generates invalid Jpql (it writes a get() in the statement)

It would be awesome if this could use the JPA operators for maps.

It would also be great if a MapPath offered some sort of any() so you could actually easily search for multiple entries in the map witthout resorting to explicit subqueries.

**Comment by timowest** [comment]
Released in 3.6.1
