### ISSUE TITLE
Use SQL_CALC_FOUND_ROWS for MySQL when returning page and total

### ISSUE THREAD

**Issue by timowest** [querydsl/querydsl#1060]
Use SQL_CALC_FOUND_ROWS for MySQL when returning page and total

**Comment by julianomqs** [comment]
Any chance to implement this?

**Comment by jwgmeligmeyling** [comment]
`SQL_CALC_FOUND_ROWS` is already deprecated in MySQL, they currently recommend using the exact behaviour QueryDSL alwasy had.
