### ISSUE TITLE
Uppercase/lowercase sql tables weird behaviour

### ISSUE THREAD

**Issue by rlecomte** [querydsl/querydsl#1084]
Hi,

Weird behaviour when i mapped lowercase sql table, for example "fwk_user" i got DTO with uppercase table name : 

public static final QFwkUser fwkUser = new QFwkUser("FWK_USER");

 I try to use "<lowercase>true</lowercase>" parameter in maven plugin to fix the problem but the result is i got empty DTO : columns isn't map in DTO anymore.

**Comment by timowest** [comment]
Closing, since additional information were not provided. Feel free to reopen this with the necessary information.

**Comment by eloisamec** [comment]
Hello!
Having the same problem.
Using Oracle 11g database and, when i use <lowerCase>true</lowerCase> to create the entities over pom.xml, the generated class is empty.
I'm trying to use multiple database system and Postgres doesn't work with generated class over Oracle. It says that id column doesn't exists (sequence column). The same script (liquibase) was used to generate the both databases.
