### ISSUE TITLE
Improve math Normalization when SQLTemplates is not quote enable 

### ISSUE THREAD

**Issue by cmhuynh** [querydsl/querydsl#1100]
Hi,

If I had a query construct with an SQLTemplate and quote is not enabled (https://github.com/querydsl/querydsl/blob/91b1db4b51ffda5ddc40ce763a7e754e0b52ee7c/querydsl-sql/src/main/java/com/mysema/query/sql/SQLTemplates.java#L64)
and then perform a normal query, with filter condition accepting a list of strings, where string's value is java.util.UUID, then the match normalization would mis-interpret it into expression (https://github.com/querydsl/querydsl/blob/91b1db4b51ffda5ddc40ce763a7e754e0b52ee7c/querydsl-core/src/main/java/com/mysema/query/support/Normalization.java) .
The result therefore is not correct.

```java
SQLQuery select = ..;
select.from(BOOK).where(BOOK.ISBN.in(ids)).list(BOOK.TITLE, BOOK.ISBN);
```

where ids is a list of UUID

if SQLTemplates.Builder.quote() is set, the normalization issue does not exist.

Sample table structure:

```java
public class BookQDSL extends RelationalPathBase<BookQDSL>
{
    public static final String TABLE_NAME = BookQDSL.TABLE_NAME;

    public final NumberPath<Long> ID;
    public final StringPath TITLE;
    public final StringPath ISBN;

    public BookQDSL()
    {
        this(TABLE_NAME);
    }

    public BookQDSL(String sqlVariable)
    {
        super(BookQDSL.class, sqlVariable, "", TABLE_NAME);
        ID = createNumber(BookQDSL.ID, Long.class);
        TITLE = createString(BookQDSL.TITLE);
        ISBN = createString(BookQDSL.ISBN);
    }
}
```

Can you please evaluate the normalization in this situation?
As a side note, I think having quote default enabled instead of calling this SQLTemplates.Builder.quote() is preferred. I guess some might want to have QueryDSL to generate the SQL literal, but my guess directly with SQLQuery is more common.

Thanks for the work. Have a great holiday season.
-Chau

**Comment by timowest** [comment]
@cmhuynh Could you try 3.6.1? I was not able to reproduce this issue anymore.

**Comment by timowest** [comment]
related to https://github.com/querydsl/querydsl/issues/1224 which was fixed. 

Please reopen if the issue persists with 3.6.3.
