### ISSUE TITLE
com.mysema.query.codegen.BeanSerializer should be able to generate hashCode and equals

### ISSUE THREAD

**Issue by bouil** [querydsl/querydsl#1107]
The BeanSerializer should have addEquals and addHashCode properties to trigger the generations of equals and hashCode on the beans.

I've done it this way, but that require the presence of commons-lang3.

```
protected void addHashCode(EntityType model, CodeWriter writer) throws IOException {
    writer.beginPublicMethod(Types.INT, "hashCode");
    StringBuilder builder = new StringBuilder();
    builder.append("org.apache.commons.lang3.builder.HashCodeBuilder.reflectionHashCode(this)");
    writer.line(" return ", builder.toString(), ";");
    writer.end();
}

protected void addEquals(EntityType model, CodeWriter writer) throws IOException {
    writer.beginPublicMethod(Types.BOOLEAN_P, "equals", new Parameter("other", Types.OBJECT));
    StringBuilder builder = new StringBuilder();
    builder.append("org.apache.commons.lang3.builder.EqualsBuilder.reflectionEquals(this, other)");
    writer.line(" return ", builder.toString(), ";");
    writer.end();
}
```

**Comment by timowest** [comment]
Is this implementation sufficient https://github.com/querydsl/querydsl/blob/91b1db4b51ffda5ddc40ce763a7e754e0b52ee7c/querydsl-sql-codegen/src/main/java/com/mysema/query/sql/codegen/ExtendedBeanSerializer.java

Or do you need something that takes all fields into account?

**Comment by bouil** [comment]
It's good enough if you use the generated class only for loading from database, but I use them to create records, and before they are saved, they have no primary keys. At that time, I need to do some kind of grouping, so I need to strip duplicates before saving => I need something that takes all fields into account.

**Comment by tajhlande** [comment]
I found this helpful, but then when I switched to `ExtendedBeanSerializer`, my `<beanInterfaces>` tag is being ignored and the interfaces not implemented by the beans any more.  Using QueryDSL 4.2.1

**Comment by r-okui** [comment]
I got same situation. "beanSerializerClass" ignored when use "beanInterfaces".
querydsl-sql-codegen-2.4.1
