### ISSUE TITLE
"cannot be resolved to be a type" in generated Q-class

### ISSUE THREAD

**Issue by ukkm** [querydsl/querydsl#1111]
In my multi-module-maven-project I'm using following __querydsl__ components:
* apt-maven-plugin 1.1.3
* querydsl-apt 3.6.0
* querydsl-jpa 3.6.0

When the generated classes are compiled I get following error:

__```de.finkonsens.veronika.shared.raster.QRasterId``` cannot be resolved to a type__

The specialty in my constellation is that the origin class ```de.finkonsens.veronika.shared.raster.RasterId``` (which is marked as @Embeddable) resides in a different maven-module than the classes referencing it. I guess this is the reason, that the ```de.finkonsens.veronika.shared.raster.QRasterId``` class is actually __not generated__ but it is referenced correctly by other Q-classes. I tried to use the apt-maven-plugin in the maven-module of ```...RasterId```as well but without success. For me it seems to be an issue that a Q-Class is not generated but it should be.

**Comment by timowest** [comment]
Querydsl assumes that external annotated classes have their Q-type available. You can use the `QueryEntities` annotation on package level (package-info.java) to declare `RasterId` as an additional type to be mapped: `@QueryEntities(RasterId.class)`

**Comment by ukkm** [comment]
Thanks a lot! It's indeed a little bit tricky but it was the missing piece.
