### ISSUE TITLE
Adjustment suggestions to GroupBy generics

### ISSUE THREAD

**Issue by TuomasKiviaho** [querydsl/querydsl#1112]
Hi,

I noticed a slight discomfort in using generics while grouping.

``GSum<T extends Number & Comparable<T>>``  could be just ``GSum<T extends Number>``
``GAvg<T extends Number & Comparable<T>>``  could be just ``GAvg<T extends Number>``
``GMin<T extends Comparable<T>>`` should be``GMin<T extends Comparable<? super T>>``
``GMax<T extends Comparable<T>>`` should be ``GMax<T extends Comparable<? super T>>``

The latter ones would actually be useful for me because I have to dumb down the generics in order to get things working (or typecast the date as ``java.util.Date``)
``GroupExpression<java.sql.Date, java.sql.Date> min = GroupBy.min((DatePath) date)``

**Comment by timowest** [comment]
@TuomasKiviaho We are currently preparing to switch to a different package structure for the 4.0 release so it might be easier to do this change after that.
