### ISSUE TITLE
what time is  querydsl-sql-example update to 3.6.0? and I have problem,THX

### ISSUE THREAD

**Issue by edwardlau** [querydsl/querydsl#1119]
Hi:
    I try querydsl-sql (version: 3.6.0) code is:
```java
@QueryEntity
public class AskQuestion implements Serializable{
.....
 @QueryProjection
    public AskQuestion(Integer userId, Integer resource, Integer partitionId, Integer threadId, Integer type, Date threadTime, Date firstThreadTime, Date acceptTime, Integer isAppend, List<String> tag) {
        this.userId = userId;
        this.resource = resource;
        this.partitionId = partitionId;
        this.threadId = threadId;
        this.type = type;
        this.threadTime = threadTime;
        this.firstThreadTime = firstThreadTime;
        this.acceptTime = acceptTime;
        this.isAppend = isAppend;
        this.tag = tag;
    }
}
```
and testing
```java
    public static void main(String[] args) throws ClassNotFoundException, SQLException {
.......
       QAskQuestion qAskQuestion1 = QAskQuestion.askQuestion;
        SQLTemplates templates = new MySQLTemplates();
        Configuration configuration = new Configuration(templates);
        SQLQuery query = new SQLQuery(connection, configuration);
        List<AskQuestion> askQuestions = query.from(qAskQuestion1).list(ConstructorExpression.create(AskQuestion.class,qAskQuestion1.all()));

        for (AskQuestion askQuestion : askQuestions) {
            System.out.println(askQuestion.toString());
        }
    }
```
throw exception : com.mysema.query.types.ExpressionException: No constructor found for class net.health.model.AskQuestion with parameters:

why? i used the @QueryProjection  but throw exception  and i try 
List<AskQuestion> askQuestions = query.from(qAskQuestion1).list(Projections.bean(AskQuestion.class, qAskQuestion1.all()));

QAskQuestion is extends com.mysema.query.sql.RelationalPathBase<QAskQuestion>

is success ... help thx
![qq20150115-1 2x](https://cloud.githubusercontent.com/assets/2252194/5756333/450e8f7e-9ce9-11e4-8447-4d6799c58d9f.png)
![qq20150115-2 2x](https://cloud.githubusercontent.com/assets/2252194/5756164/c4659a8a-9ce7-11e4-807b-166c223ddd71.png)

**Comment by Shredder121** [comment]
Hello,

I see that the error is because the constructor parameter list starts with `Timestamp`, and the formal parameters start with `Integer`s.

If you want to have a constructor injected, it's safer to specify the arguments manually, and in the order they appear in the constructor parameter list.

In `Projections.bean(...)` the setters are used instead, so that is why it succeeds.

I hope this answers your question, and could you maybe put support questions in the Querydsl Google group in the future?

**Comment by timowest** [comment]
@edwardlau Could you comment whether this fixes your issue?

**Comment by timowest** [comment]
Closing for now, please reopen if the suggested fix doesn't work.
