### ISSUE TITLE
provide support for relational division

### ISSUE THREAD

**Issue by SebastianDietrich** [querydsl/querydsl#1121]
Please provide support for relational division. E.g. like JOOQ supports it (http://www.jooq.org/doc/3.0/manual-single-page/#relational-division).

Either the "classical version" or the "reduced version" - http://jise.org/Volume13/Pdf/085.pdf

**Comment by lukaseder** [comment]
One of the best articles on the subject has been written by Joe Celko whom I need not introduce:
https://www.simple-talk.com/sql/t-sql-programming/divided-we-stand-the-sql-of-relational-division

Division is hard to get right. A whole chain of SQL transformation capabilities need to be put in place. I wouldn't add this feature without giving the whole transformation tool chain some thorough thought.

**Comment by SebastianDietrich** [comment]
You are right - division is hard to get right. That's the main reason for my request :-)
The second reason is that it is hard to read. A one-liner like JOOQ-division would help a lot.
