### ISSUE TITLE
Metamodel generated by RooAnnotationProcessor is missing id and version paths

### ISSUE THREAD

**Issue by klepecl** [querydsl/querydsl#1122]
When using Spring Roo, Id and version fields are declared in a separate .aj file and therefore not processed by the annotation processor.

**Comment by klepecl** [comment]
A workaround is to explicitly declare the field with accessors in your .java file:
```java
@RooJpaEntity
public class Kitten {
    @Id @GeneratedValue(strategy = GenerationType.AUTO) @Column(name = "id")
    private Long id;
    public Long getId() { return id; }
    public void setId(Long id) { this.id = id; }
}
```

**Comment by timowest** [comment]
In that case you need to use a classpath based code generation variant http://www.querydsl.com/static/querydsl/3.6.0/reference/html/ch03s03.html#d0e2395

The apt-maven-plugin looks only at the sources.
