### ISSUE TITLE
PostgreSQL .dayOfYear() not working

### ISSUE THREAD

**Issue by renanleandrof** [querydsl/querydsl#1126]
Hello.

I'm trying to add a where clause with:

```
.where(user.birthdate.dayOfYear().between(start, end))
```

I'm getting an exception:
> Caused by: org.postgresql.util.PSQLException: ERROR: function dayofyear(timestamp without time zone) doesn't exists

The right way to get dayOfYear on Postgre is: ```extract(doy from timestamp xxx)```

Is it a bug or i need to do some extra configuration before using it?

Thanks.

**Comment by timowest** [comment]
Which Querydsl version and module do you use?

**Comment by renanleandrof** [comment]
3.4.2

                <dependency>
			<groupId>com.mysema.querydsl</groupId>
			<artifactId>querydsl-jpa</artifactId>
			<version>${versao.querydsl}</version>
		</dependency>

**Comment by renanleandrof** [comment]
I have updated right now to 3.6.0, the error persists... =/

**Comment by renanleandrof** [comment]
Find out the problem.

The Postgre 9 Dialect on Hibernate does not map the dayofyear function.

Sorry for this issue.

**Comment by timowest** [comment]
Ok, good you got it fixed! And no need to apologize.

**Comment by dimklo** [comment]
Can you please tell what you did to fix the issue? I have the same error. I have tried to change the dialect from org.hibernate.dialect.PostgreSQL9Dialect to org.hibernate.dialect.PostgreSQL95Dialect, but still getting this error.

**Comment by renanleandrof** [comment]
You need to extend the PostgreDialect class and map the function, like this:


```java
public class MyPostgreSQL9Dialect extends PostgreSQL9Dialect {

    public MyPostgreSQL9Dialect() {
        super();
        registerFunction( "dayofyear", new SQLFunctionTemplate(StandardBasicTypes.INTEGER, "extract(doy from ?1)") );
    }
}
```

**Comment by ChetanBhajbhuje** [comment]
Hello.

I'm trying to add a BooleanExpression clause with:

BooleanExpression  exp = qDeskUserUsage.startTime.dayOfWeek().in(listOfDow);

I'm getting an exception:

Caused by: org.postgresql.util.PSQLException: ERROR: function dayofweek(timestamp with time zone) does not exist

The right way to get dayofweek on Postgre is: select extract(dow from date '2016-12-18');

Is it a bug or i need to do some extra configuration before using it?

Thanks.
