### ISSUE TITLE
querydsl-root POM changes

### ISSUE THREAD

**Issue by Shredder121** [querydsl/querydsl#1132]
As querydsl-root's parent is 'mysema-source', it inherits its properties.

This means that the `<organisation>` of Querydsl is still 'Mysema Ltd'.

It should be a better idea to replace (or eliminate) 'mysema-source' as parent.

**Comment by timowest** [comment]
Maybe com.querydsl:querydsl-parent as a separate github project could work.

**Comment by Shredder121** [comment]
Just a few more ideas for the common parent:

* unify the test configuration
 * probably look at including `TravisFoldListener` in some way?
* code style checks

anything else?

**Comment by johnktims** [comment]
What do you think about moving the contents of querydsl-root into the root directory of the project?

That seems to be the generally-accepted way of configuring a multi-module project but it does result in a more cluttered root directory.

**Comment by timowest** [comment]
@johnktims Moving the root to the root of the project is fine with me. But preferably only on the master side, not backport. @Shredder121 What do you think?

**Comment by Shredder121** [comment]
@timowest Just your opinion, why not on the backport?

In my opinion this makes it better to support the development platforms that silently support only the common practice. (various cloud IDEs I tried don't like it when there is 'no pom.xml' and generate one for you..)
So I think this is better. It also means we don't have an (almost) empty GitHub repository only for the parent root.

**Comment by timowest** [comment]
Yes, technically backwards compatibility is preserved, so the backport should be ok as well then

**Comment by Shredder121** [comment]
If you have an opinion, you can share it of course.

**Comment by timowest** [comment]
I'd like to keep the changes to the QUERYDSL_3 branch under the surface, on the other hand we agreed that backwards compatible changes should be applied there. So I am trying to be consistent and agree with you ;)

**Comment by Shredder121** [comment]
So to move this along, we can backport it now?

**Comment by johnktims** [comment]
I'll backport #1270 and my documentation fixes as soon as I get home.

**Comment by Shredder121** [comment]
That is fine.
