### ISSUE TITLE
MongoDB: support $elemMatch feature

### ISSUE THREAD

**Issue by rocketraman** [querydsl/querydsl#115]
In MongoDB, if one wishes to apply multiple criteria to embedded documents within an array, one has to use the $elemMatch feature. See "Matching with $elemMatch" at http://www.mongodb.org/display/DOCS/Dot+Notation+%28Reaching+into+Objects%29.

It would be cool if QueryDSL was able to support this query notation.

A good example is given at the bottom of the page above:

```
// Document 1
{ "foo" : [
      {
        "shape" : "square",
        "color" : "purple",
        "thick" : false
      },
      {
        "shape" : "circle",
        "color" : "red",
        "thick" : true
      }
] }


// Document 2
{ "foo" : [
      {
        "shape" : "square",
        "color" : "red",
        "thick" : true
      },
      {
        "shape" : "circle",
        "color" : "purple",
        "thick" : false
      }
] }
```

In order to query for a document containing a purple square, the mongodb query is:

`db.foo.find({foo: {"$elemMatch": {shape: "square", color: "purple"}}})`

**Comment by svmgarg** [comment]
> 1. joinNested is a bit confusing. How about `anyEmbedded`, which seems closer to the similar `any` syntax used by collections.
> 2. I guess the second parameter to joinNested/anyEmbedded is an alias? If the user needs to specify the typed fields from the Q-class, is the alias useful?
> 
> How about this:
> 
> `anyEmbedded(doc.foo).on(doc.foo.shape.eq("square"), doc.foo.color.eq("purple"))`
> 
> (where I guess `doc` is a static import on `QDoc`)

What if doc.foo is a map and properties like "shape", "color","thick" are map key's then you won't be able to do doc.foo.shape anymore.
Please find stackoverflow question.
https://stackoverflow.com/questions/53929308/filter-over-map-values-in-spring-data-mongo-query-dsl
