### ISSUE TITLE
Make all mapping options of com.querydsl.sql.Configuration available in the Maven plugin

### ISSUE THREAD

**Issue by timowest** [querydsl/querydsl#1157]
Renaming (via RenameMapping)
* schema -> schema
* table  -> table
* schema, table -> table
* schema, table -> schema, table
* schema, table, column -> column
* table, column -> column

Numerics (via NumericMapping)
* total, decimal -> java type

Custom types (via TypeMapping)
* table, column -> java type
* schema, table, column -> java type

**Comment by jbrackett** [comment]
Hi Timo, is this ticket related to what we discussed on stackoverflow?

http://stackoverflow.com/questions/28331489/querydsl-join-on-same-table-multiple-times/28349997?noredirect=1#comment45050781_28349997

**Comment by Shredder121** [comment]
I don't believe it is.
Your issue is more related to the usage of entities where it generally expects other types.
You can open a new ticket for your issue, probably named `document the use of non-interchangeable types`?

**Comment by jbrackett** [comment]
Thanks, will do.

**Comment by timowest** [comment]
@jbrackett I can confirm that this not related to your SO question. It is more about what configuration options to expose via the maven plugin.
