### ISSUE TITLE
How to set schema and table dynamically using PathBuilder?

### ISSUE THREAD

**Issue by archerchiu** [querydsl/querydsl#1160]
Hi,
I wanna organize SQL dynamically using general string from HashMap. I found it's a way to using PathBuilder. But, don't know how to set specific schema dynamically? Anyone can give me some hints or other way to do that?
Thanks a lot.

**Comment by timowest** [comment]
Which Querydsl module do you use, Querydsl JPA or Querydsl SQL?
Do you use generated Querydsl types at all or do you try to do everything manually?

**Comment by archerchiu** [comment]
@timowest I use Querydsl SQL. I found and try to go on by the <a href="http://stackoverflow.com/questions/21689222/how-to-get-fully-materialized-query-from-querydsl">sample</a> as you replied. It's the right way to use the RelationalPathBase class to assign specific schema? But, I can't awaken why have to assign the Class type?

**Comment by AlvinChiou** [comment]
Use this,
String aliases = "tableNameAliases";
String schema = "db";
String tableName = "Any table you want to query";
Path<Object> table = new RelationalPathBase<Object>(Object.class, aliases, schema, tableName);

**Comment by archerchiu** [comment]
If using general string, I know it also can assign <code>String.class</code>. It seems have to create a dynamical class for composing the sql. If you store table and column sources in a map, transforming it to a specific class, like value object. Then, you could use the class to perform anywhere until listing the data.

**Comment by archerchiu** [comment]
I have already understood the running mechanism. It's amazing "Q" prefix tool. Please close this issue. Thanks a lot.
