### ISSUE TITLE
Make sure that the code is compatible with JDK 1.6

### ISSUE THREAD

**Issue by timowest** [querydsl/querydsl#1169]
Travis builds with different JDK versions doesn't cover this requirement, since Querydsl can't be built anymore with JDK 1.6. Still the result should be compatible with JDK 1.6.

This looks like a promising solution http://eclipsesource.com/blogs/2014/05/09/ensure-class-library-compatibility-in-a-maven-build/

**Comment by Shredder121** [comment]
What I do when I want to try JDK6 is build it using JDK7, then switch JDK's and only run the tests.

Isn't that possible using Travis?
- jdk_switch jdk7
- build
- jdk_switch jdk6
- test

**Comment by timowest** [comment]
You are right. I wasn't aware of this option. I will try the travis config customization then.
