### ISSUE TITLE
mongodb - eq expression with objectId generates wrong path

### ISSUE THREAD

**Issue by metawave** [querydsl/querydsl#1187]
If one has an entity person with a manual handled reference (without the morphia ```@Reference``` annotation) saving an ObjectId in the object for a reference to an Address entity as shown below.

```java
class Person {
   @Id
   ObjectId id;

   String name;

   // manual reference to an address
   ObjectId addressId;
}
```

the morphia serializer doesn't respect the query:
```java
QPerson.person.addressId.eq(<objectId>)
```

as shown in the code in the com.mysema.query.mongodb.MongodbSerializer#getKeyForPath:
```java
    protected String getKeyForPath(Path<?> expr, PathMetadata<?> metadata) {
        if (expr.getType().equals(ObjectId.class)) {
            return "_id";
        } else {
            return metadata.getElement().toString();
        }
    }
```
every path with an objectId type on field automatically gets translated to ```_id``` instead of the ```addressId``` as shown in the query path expression.

**Comment by Shredder121** [comment]
Thanks for the report.
