### ISSUE TITLE
QueryDslPredicateExecutor and specification pattern

### ISSUE THREAD

**Issue by dopeymac** [querydsl/querydsl#1196]
We are running into an N+1 problem using Spring Data JPA and QueryDslPredicateExecutor. We really like the simplicity and convenience of retrieving our data with using predicates as shown below:

```java
QTag qTag = QTag.tag;
tagDao.findAll(qTag.accountId.eq(accountId));
```

We would like to avoid having custom methods and building the JPAQuery manually in order to specify a join fetch. I was wondering if querydsl offered a way to join fetch mapped entities or collections similar to how specifications are used with JPASpecificationExecutor? 
    
```java
  public static Specification<Tag> accountIdEq(Long accountId) {
    return (root, query, cb) -> {
      query.distinct(true);
      root.fetch(Tag_.auditInfo, JoinType.LEFT);
      return cb.equal(root.get(Tag_.accountId), accountId);
    };
  }
 ``` 
  
With the specification above, we can reuse and chain it with other specifications as well as build our query without having to create custom methods.

Do you have any suggestions on ways we could optimize our queries while still using querydsl and avoiding the N+1 problem?

**Comment by timowest** [comment]
This sounds more like a Spring Data JPA specific issue. Querydsl provides predicates and queries for this solution, but nothing like a Specification.

**Comment by dopeymac** [comment]
From what I understand, we cannot specify a join fetch within our predicate when using Iterable<T> findAll(Predicate predicate) in QueryDslPredicateExecutor

Could you provide an example on how we could accomplish this?

**Comment by timowest** [comment]
You could define the fetches as a list of `Path` instances and then just add them to query via `query.join(path).fetch()`.

**Comment by dopeymac** [comment]
Is there another way to accomplish this without having to use query?

**Comment by timowest** [comment]
No.

**Comment by timowest** [comment]
Please reopen if you feel that there is something that could be done on the Querydsl side to simplify this.
