### ISSUE TITLE
How to query LeftJoining an inherited table?

### ISSUE THREAD

**Issue by renanleandrof** [querydsl/querydsl#1197]
Hello, 
i have the following structure: Class Animal and Class Dog that extends Animal.
Animal has a name and dogs have name( inherited) and ownerName

So, i'm querying QAnimal to search all animals that have a name like a "searchTerm". But i need to include in that search also dog's who have the ownerName like "searchTerm".

So my code is:
````java
String searchTerm = "dogge";
QAnimal animal = QAnimal.animal;
QDog dog = QDog.dog;

new JPAQuery()
                .from(animal)
                .leftJoin(dog._super, animal)
                .where(animal.name.contains(searchTerm)
                        .or(dog.ownerName.contains(searchTerm))
                ).list(animal);
```` 

But this code produces "org.hibernate.hql.internal.ast.QuerySyntaxException: Path expected for join! "
How can i do this join?

**Comment by timowest** [comment]
This should work

new JPAQuery().from(animal)
                           .where(animal.name.contains(searchTerm)
                                  .or(animal.as(QDog.class).ownerName.contains(searchTerm)))
                            .list(animal);

**Comment by renanleandrof** [comment]
Amazing!
