### ISSUE TITLE
`distinct on (field) field, other_field`  possible?

### ISSUE THREAD

**Issue by caarlos0** [querydsl/querydsl#1212]
In SQL (not sure if ANSI, but in at least in Postgres) we can distinct by one field using `distinct on`:

```sql
select distinct on (field) field, other_field
from table
where other_field like '%blah%';
```

I didn't find a way to write this with QueryDSL (using JPA).

Is this an uninplemented feature, a limitation by JPA (or something else), or I just didn't look well enough?

**Comment by timowest** [comment]
This is unsupported in JPQL and currently also not implemented in Querydsl SQL.

**Comment by caarlos0** [comment]
Figured.

Thanks.
