### ISSUE TITLE
Wrong precedence rules for SQL serialization

### ISSUE THREAD

**Issue by mwillema** [querydsl/querydsl#1219]
I have an issue with QueryDSL SQL >= 3.5.0 and the placement of parenthesis in the generated SQL in order by statements. The DB is H2 v1.3.176

Given the following statement:

    .orderBy(MY_TABLE.X.multiply(a).divide(MY_TABLE.Y.multiply(b)).asc())

with a = 100 and b = 200 for example

I expect the following SQL:

    order by MY_TABLE.X * 100 / (MY_TABLE.Y * 200) asc

but instead I get:

    order by MY_TABLE.X * 100 / MY_TABLE.Y * 200 asc

which does not lead to the same result.

**Comment by timowest** [comment]
Some related resources

SQL Server 2008
https://msdn.microsoft.com/en-us/library/ms190276(v=sql.105).aspx

SQL Server 2012
https://msdn.microsoft.com/en-us/library/ms190276(v=sql.110).aspx

SQL Server 2014
https://msdn.microsoft.com/en-us/library/ms190276(v=sql.120).aspx

MySQL 5.5
http://dev.mysql.com/doc/refman/5.5/en/operator-precedence.html

PostgreSQL 9.4
http://www.postgresql.org/docs/9.4/static/sql-syntax-lexical.html

Oracle
http://docs.oracle.com/cd/B19306_01/server.102/b14200/operators001.htm

Teradata
http://www.info.teradata.com/HTMLPubs/DB_TTU_14_00/index.html#page/SQL_Reference/B035_1141_111A/ch01.103.69.html

**Comment by mwillema** [comment]
I confirm the initial issue is now fixed in 3.6.3. Thx.
