### ISSUE TITLE
Numbers not multiplied correctly in order by clause

### ISSUE THREAD

**Issue by mwillema** [querydsl/querydsl#1221]
Using QueryDSL 3.6.1 for SQL with H2 v1.3.176, I have an issue when multiplying BigDecimals (or Doubles) in an order by clause.

Given the following statement:

    .orderBy(MY_TABLE.X.multiply(a).multiply(x).asc())

with a = 1.000E5 and b = 500, 'a' being either a BigDecimal or a Double, 'b' an integer

I expect the following SQL:

    order by MY_TABLE.X * 5.000E6 asc

but instead I get:

    order by MY_TABLE.X * 1.000E2500 asc

which obviously leads to a numeric value out of range error.

**Comment by timowest** [comment]
Do you use prepared statements or literal serialization?

**Comment by mwillema** [comment]
We've encountered the problem with both, although we usually use prepared statements. At first we ran into this issue only when turning literal serialization on (for debugging purpose), but after some unrelated changes, we started to have the issue with prepared statements as well.

**Comment by timowest** [comment]
@mwillema Is the problem still present with 3.6.3?

**Comment by mwillema** [comment]
@timowest Yes it is. Only using prepared statements however. When I turn literal serialization on by calling setUseLiterals(true) on the SQLQuery object, it seems to work fine.
