### ISSUE TITLE
nullpointerexception when use list method

### ISSUE THREAD

**Issue by aug828** [querydsl/querydsl#1227]
When I use something like this: 
template.newSqlQuery().from(q).list(q.name);

it throws NPE. Seems in AbstractSQLQuery.java, the conn is null when using list method. 
The query method is fine. 
        
final PreparedStatement stmt = conn.prepareStatement(queryString);

**Comment by aug828** [comment]
Tested on 3.6.0 and 3.6.1

**Comment by aug828** [comment]
I think in the fix is: QueryDslJdbcTemplate.java method newSqlQuery should change from 
       public SQLQuery newSqlQuery() {
		return new SQLQuery(this.dialect);
	}

to 
        public SQLQuery newSqlQuery() {
                Connection conn = DataSourceUtils.getConnection(this.jdbcTemplate.getDataSource());
		return new SQLQuery(conn,this.dialect);
	}

**Comment by Shredder121** [comment]
Spring's JDBCTemplates provides us with the connection, so it is an error on their part.
I think you'd do good to report the problem there.

**Comment by timowest** [comment]
I can confirm that the issue is with Spring Data JDBC, and not Querydsl, though the query created by them is not supposed to be executed directly as you can see from their docs

http://docs.spring.io/spring-data/jdbc/docs/1.2.0.BUILD-SNAPSHOT/reference/html/core.querydsl.html

**Comment by aug828** [comment]
You are right. This is spring querydsl template issue. Thank you.
