### ISSUE TITLE
A deadlock in JPAQuery initializer

### ISSUE THREAD

**Issue by apangin** [querydsl/querydsl#1228]
The actual problem was originally reported at
http://stackoverflow.com/questions/28631656/runnable-thread-state-but-in-object-wait

**Comment by timowest** [comment]
@apangin Why did you close this again?

**Comment by apangin** [comment]
@timowest Sorry, I thought I had found a static initializer deadlock in the code, but later I realized it was not. So far there is no evidence of a problem in Querydsl.

**Comment by Shredder121** [comment]
I also tried to reproduce this, but can not find any evidence as well.
