### ISSUE TITLE
Querydsl JPA now uses type of getter instead of field, results in IllegalArgumentException

### ISSUE THREAD

**Issue by wbiller** [querydsl/querydsl#1229]
Since Querydsl 3.6.0 the metamodel uses the types of the getter for paths instead of the type of the field. This causes IllegalArgumentExceptions, because JPA expects the type of the field.

In case there is a class Order:
```java
class Order {

  @Column(name = "order_date")
  @Temporal(TIMESTAMP)
  private Date orderDate;

  public LocalDateTime getOrderDate() {
    return orderDate != null ? new LocalDateTime(orderDate) : null;
  }
}
```
The generator will now create something like this:
```java
@Generated("com.mysema.query.codegen.EntitySerializer")
public class QOrder extends EntityPathBase<Order> {
  public final DateTimePath<org.joda.time.LocalDateTime> orderDate = createDateTime("orderDate", org.joda.time.LocalDateTime.class);
}
```

Until version 3.5.1 this worked as expected.

**Comment by Shredder121** [comment]
Hello,
could you insert a breakpoint [here](https://github.com/querydsl/querydsl/blob/e4b20fc15a6b6d8108ccfdf5cb22df47f929e5e7/querydsl-apt/src/main/java/com/querydsl/apt/jpa/JPAConfiguration.java#L83) (to find out if there are any relevant annotations picked up on the getters) and [here](https://github.com/querydsl/querydsl/blob/e4b20fc15a6b6d8108ccfdf5cb22df47f929e5e7/querydsl-apt/src/main/java/com/querydsl/apt/VisitorConfig.java#L50) (to find out if the configuration jumps into 'ALL' mode) and debug build your project?

**Comment by timowest** [comment]
Are there any JPA annotations on the setters?

**Comment by wbiller** [comment]
No. Only on the field. Just like the example above. I also tried adding @Access(FIELD) to the class, but that didn't help.

**Comment by timowest** [comment]
@wbiller Which code generation method did you use? APT processor or something else?

**Comment by wbiller** [comment]
APT. I followed this guide https://gist.github.com/EdwardBeckett/5377401

**Comment by wbiller** [comment]
Hi Timo, I retested it with the latest version of Querydsl and the @Access annotation. Seems to work.
