### ISSUE TITLE
IN clause with multiple arguments forgets parenthesis

### ISSUE THREAD

**Issue by anthony-o** [querydsl/querydsl#1230]
Here is my code:

```java
JPAQuery query = new JPAQuery(entityManager, JPQLTemplates.DEFAULT);
query.from(QStatus.status);
...
QItemValue itemValue = QItemValue.itemValue;
JPASubQuery itemSubQuery = new JPASubQuery();
itemSubQuery.from(itemValue).where(
        itemValue.studyId.eq(QStatus.status.studyId)
);
itemSubQuery.where(itemValue.item.code.in("A", "B"));
query.where(itemSubQuery.exists());
```
And here is the exception I got:
```
Caused by: org.hibernate.hql.internal.ast.QuerySyntaxException: unexpected token: , near line 7, column 161 [select count(status)
from com.mycompany.myapp.entity.status status
where exists (select itemValue
from com.mycompany.myapp.entity.ItemValue itemValue
where itemValue.studyId = status.studyId and itemValue.item.code in :x5_0_, :x5_1_)]
```

We can see that the generated "in code" lacks some left & right parenthesis which is causing a `QuerySyntaxException`.

I'm using `com.mysema.querydsl:querydsl-jpa:3.6.2`.

Here is a weird workaround: add `.and(Expressions.predicate(Ops.EQ, Expressions.constant(1), Expressions.constant(1)))`.

Here is the full code:
```java
...
itemSubQuery.where(itemValue.item.code.in("A", "B").and(Expressions.predicate(Ops.EQ, Expressions.constant(1), Expressions.constant(1))));
...
```
and the generated code:
```
...
and itemValue.item.code in ?5 
and ?2 = ?2
...
```

**Comment by timowest** [comment]
Which Hibernate version do you use?

**Comment by anthony-o** [comment]
`4.2.0.Final` (which is the one bundled with JBoss EAP 6.2). But I don't think the bug is coming from hibernate as when I say "the generated code", I'm talking about the JPQL code which is generated by QueryDSL.

**Comment by timowest** [comment]
Could you replace

JPAQuery query = new JPAQuery(entityManager, JPQLTemplates.DEFAULT);

with

JPAQuery query = new JPAQuery(entityManager);

Querydsl will automatically pick the right JPQLTemplates subtype.

**Comment by timowest** [comment]
Here is a related Hibernate issue https://hibernate.onjira.com/browse/HHH-6913

**Comment by anthony-o** [comment]
Replacing `new JPAQuery(entityManager, JPQLTemplates.DEFAULT)` with `new JPAQuery(entityManager)` actually solved my problem, thanks !
