### ISSUE TITLE
Add support for zip protocol to ClassPathUtils

### ISSUE THREAD

**Issue by ukchucktown** [querydsl/querydsl#1235]
When calling classLoader.getResources(packagePath) WebLogic returns "zip" as the protocol and the current code in scanPackage only handles "jar" as the protocol and will not call the scanJar method resulting in an illegal argument exception.

**Comment by timowest** [comment]
Maybe this library should be considered as a replacement to the ClassPathUtils usage http://code.google.com/p/reflections/

**Comment by Shredder121** [comment]
We already have it in our *test* classpath, and I personally use it in a few of our projects.
I am very fond of the way it is implemented, and the things you can do with it, but the question is 'do we want to impose this to the users of Querydsl'.

**Comment by timowest** [comment]
`ClassPathUtils` is mostly used from the codegen modules and since those are not used at runtime, the extra dependency there shouldn't hurt that much.

**Comment by Shredder121** [comment]
It isn't exactly the dependency that is the problem. I think the imported classpath is not quite right.
I think that at least [javassist](https://github.com/ronmamo/reflections/blob/master/pom.xml#L72) should be excluded, since it is probably 'included' [by mistake](https://github.com/ronmamo/reflections/issues/41)?
Apart from that, indeed, the extra dependency shouldn't hurt too much.

**Comment by bcubk** [comment]
I'm currently working on this bug/task for contribution and I excluded the javassist dependency in the pom file. But I get following Exception:
```
java.lang.NoClassDefFoundError: javassist/bytecode/ClassFile
	at org.reflections.adapters.JavassistAdapter.getOfCreateClassObject(JavassistAdapter.java:100)
	at org.reflections.adapters.JavassistAdapter.getOfCreateClassObject(JavassistAdapter.java:24)
	at org.reflections.scanners.AbstractScanner.scan(AbstractScanner.java:30)
	at org.reflections.Reflections.scan(Reflections.java:243)
	at org.reflections.Reflections.scan(Reflections.java:203)
	at org.reflections.Reflections.<init>(Reflections.java:128)
	at com.querydsl.core.util.ClassPathUtils.scanPackage(ClassPathUtils.java:49)
	at com.querydsl.core.util.ClassPathUtils.scanPackage(ClassPathUtils.java:40)
```
It can't be a mistake.

**Comment by timowest** [comment]
What do the reflections docs say on the javassist dependency? For which
functionality is it needed?

**Comment by Shredder121** [comment]
I believe it is to read the class' metadata without loading it via `java.lang.reflect` means.
So I suppose it was not a mistake indeed, but it is a little counter intuitive.

-------- Original message --------

**Comment by bcubk** [comment]
Yes, that's right. I'm going to examaine the docs in detail.

**Comment by bcubk** [comment]
Ah, I got it. The ConfigurationBuilder provides a setter to override the default "MetadataAdapter" to fetch the metadata of the classes. The default adapter uses Javassist. I switched it to the "JavaReflectionAdapter" and my test case passes through. I will provide a PR the next days.
