### ISSUE TITLE
Add gitter chatroom

### ISSUE THREAD

**Issue by johnktims** [querydsl/querydsl#1240]
[Gitter](https://gitter.im)  is a great way to facilitate discussion on github. Chatrooms for public repos are free.

**Comment by Shredder121** [comment]
Hello, I was wondering if you meant this in a collaboration, support or other way?

**Comment by johnktims** [comment]
I've seen projects use it for both.

**Comment by Shredder121** [comment]
For support we already have the support forum, so I don't know how 'redundant' a chat room is.
I don't know how lively it would be, or if there is any appeal.

I think it would be good to have more people's opinion on this.
@timowest what do you think? Do you see a particular use case for a chat room?

I think when Timo comments, we can see if we can make a post on the forum to ask whether there is appeal for this. Is that okay?

**Comment by johnktims** [comment]
Sure. I just wanted to mention it.

**Comment by timowest** [comment]
I am active in the Querydsl Google Group, GitHub and on StackOverflow, so also being available in a chatroom would be a challenge for me.

But I am also for asking more opinions on it in the Querydsl google group.

**Comment by johnktims** [comment]
Good point. Providing too many avenues for support is probably not a good idea.
