### ISSUE TITLE
Different results in a query if I add offset(0)

### ISSUE THREAD

**Issue by edual16** [querydsl/querydsl#1250]
Hello.

First of all, I want to say that the following issue is a problem with my query but it is strange.

I have a view with a OneToOne relation with an entity and this entity has left joins with other different entities.

When I launch the regular query with that structure, I get the results duplicate because of the left joins (Hibernate should organize the entities but don't). If I launch the same query but adding offset(0), nothing else, everything is working well.

I think the behaviour is wrong (the offset statement shouldn't change the result) but, maybe, my query is wrong too.

If you think it could be an issue, I can try to make an example (simpler than my code) where the problem can be replicated.

Thank you.

Best regards, Eduardo.

**Comment by timowest** [comment]
Do you experience this issue with Hibernate or another JPA provider? Which Querydsl version do you use? And which database?

**Comment by timowest** [comment]
Also did you check the resulting SQL in both cases? Is it different?

**Comment by edual16** [comment]
Sorry for the lack of information. We use Hibernate, PostgreSQL and Querydsl 3.6.0 (I think it is the latest version in maven repository but now I have seen there are two versions newer here).

Now I can't check the SQL sentence but tomorrow I will check. I think the only difference was the offset in the SQL but, as I say, tomorrow I will verify it.

I will also try to update the Querydsl version to see if the problem persists in the newer versions.

**Comment by edual16** [comment]
The SQL sentence is the same with offset(0) and without it with versions 3.6.0 and 3.6.2 (the offset(0) has no relevance in the SQL) but, the mapping to entities is strange because in 3.6.0 with offset(0) there is no duplicate records and without offset(0) or in 3.6.2 (with and without offset) the principal entity has duplicate records. I think the correct mapping should be one record with some records in the left join entities.

**Comment by timowest** [comment]
This explanation is consistent with your observation http://stackoverflow.com/questions/11431670/how-can-i-avoid-the-warning-firstresult-maxresults-specified-with-collection-fe

As this part of the query handling isn't controlled by Querydsl, but the JPA implementation, I'm closing this issue.
