### ISSUE TITLE
MongodbSerializer does not serialize isNotEmpty() properly

### ISSUE THREAD

**Issue by johnktims** [querydsl/querydsl#1264]
Original link: http://stackoverflow.com/questions/29104204/querydsl-isnotempty-expression-failing

There appears to be a serialization error in `MongodbSerializer` for
```java
BooleanExpression expr = qa.matches.isNotEmpty();
Iterable<A> result = aRepo.findAll(expr);

assertThat(result, is(not((emptyIterable()))));
```

` MongodbSerializer` is spitting out
```json
{ "$or" : { "$not" : [ { "matches" : [ ]} , { "matches" : { "$exists" : false}}]}}
```
which fails when I paste it into mongo.

```
> db.a.find({ "$or" : { "$not" : [ { "matches" : [ ]} , { "matches" : { "$exists" : false}}]}})
Error: error: {
	"$err" : "Can't canonicalize query: BadValue $or needs an array",
	"code" : 17287
}
> 
```

I rewrote the query as
```
> db.a.find({ "$or" : [ { "matches" : {$ne: [ ]}}, { "matches" : { "$exists" : false}}]}).pretty()
{
	"_id" : "a1",
	"_class" : "querydsldemo.A",
	"matches" : [
		{
			"_id" : ObjectId("55088ec4e4b0b6e56e76b1d6"),
			"name" : "b1"
		},
		{
			"_id" : ObjectId("55088ec4e4b0b6e56e76b1d7"),
			"name" : "b2"
		}
	]
}
{ "_id" : "a3", "_class" : "querydsldemo.A" }
```
and then further simplified it as
```
> db.a.find({ "matches" : {$ne: [ ]}}).pretty()
{
	"_id" : "a1",
	"_class" : "querydsldemo.A",
	"matches" : [
		{
			"_id" : ObjectId("55088ec4e4b0b6e56e76b1d6"),
			"name" : "b1"
		},
		{
			"_id" : ObjectId("55088ec4e4b0b6e56e76b1d7"),
			"name" : "b2"
		}
	]
}
{ "_id" : "a3", "_class" : "querydsldemo.A" }
> 
```
but I don't know if that's robust enough.

**Comment by timowest** [comment]
The negation seems to break, you can look at the handling of `Ops.COL_IS_EMPTY` and `Ops.NOT`.

**Comment by Shredder121** [comment]
It isn't really the negation, but the passing of an object to `$or` instead of elements. ('{ }' vs '[ ]') that breaks.

**Comment by timowest** [comment]
Yes, but I believe it is the negation processing that breaks it. The
isempty logic looks ok.

**Comment by Shredder121** [comment]
Ah in that sense I agree.

**Comment by johnktims** [comment]
I did switch the expression to use `isEmpty` and that appeared to work properly (although obviously the opposite of what the user wants) so I think you're right, @timowest .

**Comment by timowest** [comment]
Is someone already working on this? Otherwise I can give it a try.

**Comment by johnktims** [comment]
I'm working on it now, but I'm not sure of the best way to fix this. The syntax for `$not` is making it difficult for me to fix. I haven't used mongodb a whole lot yet, so that might be the issue. :)

**Comment by Shredder121** [comment]
I am not, I only debugged it, but didn't yet solve it.

**Comment by timowest** [comment]
@johnktims Ok, let me know if you have some questions.

**Comment by johnktims** [comment]
Should every ticket be assigned to a milestone so that it isn't forgotten in the changelog?

**Comment by timowest** [comment]
Yes.

**Comment by Shredder121** [comment]
If we want it to appear in 3.6.3, I think we'll have to backport it.

**Comment by timowest** [comment]
Yes, I can do it, if @johnktims doesn't beat me at it.

**Comment by johnktims** [comment]
I was planning to backport it this morning. Have you started it?

**Comment by timowest** [comment]
No, haven't started yet. Feel free to do it, if you have time.

**Comment by johnktims** [comment]
Cool. I'll handle it.
