### ISSUE TITLE
License file is missing copyright information

### ISSUE THREAD

**Issue by johnktims** [querydsl/querydsl#1266]
`querydsl-root/LICENSE.txt` says "Copyright [yyyy] [name of copyright owner]"

Shouldn't this be populated?

**Comment by Shredder121** [comment]
I think (since it is an [APPENDIX](https://github.com/querydsl/querydsl/blob/master/querydsl-root/LICENSE.txt#L178)) that it is just showing *[how](https://github.com/querydsl/querydsl/blob/master/querydsl-root/LICENSE.txt#L180-187)* to apply the license to your work.

**Comment by timowest** [comment]
Yes, I believe the LICENSE file doesn't need to be filled, since it is a general license.
