### ISSUE TITLE
Query Dsl group by Extracted date format

### ISSUE THREAD

**Issue by pradeep-tal** [querydsl/querydsl#1287]
Hi,

I am using Querydsl to form JPA Query everything fine  

Only issue I am facing issue with group by date.

I have column type as DateTime (yyyy-MM-dd HH:mm:ss)..

I need to extract month and year as :MM/yyyy and   should do group by using same 

could you please how can solve this.

Thanks in Advance

**Comment by johnktims** [comment]
Please use the [Google Group](https://groups.google.com/forum/#!forum/querydsl) or [StackOverflow](http://stackoverflow.com/) for general support questions.
