### ISSUE TITLE
CaseBuilder() is throwing error

### ISSUE THREAD

**Issue by pradeep-tal** [querydsl/querydsl#1303]
I am trying to create Case Expression 

```java
NumberExpression<Float> numExpression = (summary.field1.floatValue().divide(summary.field2.floatValue()).multiply(100)); 		
NumberExpression<Float> numberExpression2 = summary.impressions.when(0L).then(0.0F).otherwise(numExpression);
```

So the formed SQL Query will contain : 

```sql
when summary.impression=0 then 0.0
else cast summay.field as flaot/ cast summary.field2 as float) * 100 end
```

it throwing error at * ...unexpected token end i guess not allowing any operators we can expect same error for / also

**Comment by timowest** [comment]
Do you use Querydsl JPA or Querydsl SQL and which version? Which underlying SQL database do you use?

**Comment by pradeep-tal** [comment]
I am using Query DSL JPA version 3.6.2 
Data base i am using is Mysql

**Comment by pradeep-tal** [comment]
How can merge this changes into version 3.6.2 which i am using currently.
does this changes available in 3.6.3 version .

**Comment by timowest** [comment]
Once it is merged, you can use the latest snapshot from here oss.sonatype.org/content/repositories/snapshots

**Comment by pradeep-tal** [comment]
when this fix will be available and when it will be merged
