### ISSUE TITLE
Support - hint on QueryDSL

### ISSUE THREAD

**Issue by dyorgio** [querydsl/querydsl#1314]
Hi, this is a doubt :).

There is a way to execute it with QueryDSL? (**bold part**):

 SELECT * FROM Venue WHERE Name Like '%cafe%' **COLLATE Latin1_general_CI_AI**

**Comment by dyorgio** [comment]
Yes!

```java
query
.from(venue)
.where(BooleanTemplate.create("{0} COLLATE Latin1_general_CI_AI", venue.name.like("%cafe%"))
.and(BooleanTemplate.create("{0} COLLATE Latin1_general_CI_AI", venue.name2.like("%milk%"))))
.list(venue.name, venue.name2);
```

from http://stackoverflow.com/questions/29634657/collate-hint-on-querydsl-jpa

**Comment by rburgst** [comment]
how would you use the collate statement on a `orderBy` clause?
