### ISSUE TITLE
QueryDSL SQL Documentation on Github refers to wrong maven dependency groupId

### ISSUE THREAD

**Issue by sabinewinkler** [querydsl/querydsl#1344]
https://github.com/querydsl/querydsl/tree/master/querydsl-sql

Current information is:

    <dependency>
      <groupId>com.querydsl</groupId>
      <artifactId>querydsl-sql</artifactId>
      <version>${querydsl.version}</version>
    </dependency>

But should be:

    <dependency>
	    <groupId>com.mysema.querydsl</groupId>
	    <artifactId>querydsl-sql</artifactId>
	    <version>${querydsl.version}</version>
    </dependency>

**Comment by Shredder121** [comment]
We changed the package names, and for [the current version the reference documentation is correct](http://www.querydsl.com/static/querydsl/3.6.3/reference/html_single/#d0e659).
There is not yet a release with the new packages, so indeed it is incorrect.
With the [4.0 release](https://github.com/querydsl/querydsl/milestones) the text will be correct.

**Comment by sabinewinkler** [comment]
OK, I tried to make it work and could not get the required resources from sonatype
 
    [WARNING] The POM for com.querydsl:querydsl-sql:jar:3.6.3 is missing, no dependency information available

    [ERROR] Failed to execute goal on project domain: Could not resolve dependencies for project ..:          
    Failure to find com.querydsl:querydsl-sql:jar:3.6.3 in https://oss.sonatype.org/content/repositories/snapshots/
    was cached in the local repository, resolution will not be reattempted until the update interval of central-snapshots has elapsed or updates are forced -> [Help 1]

**Comment by Shredder121** [comment]
@timowest Shall we leave this open until the release?

**Comment by timowest** [comment]
Yes, let's do so. @sabinewinkler Sorry for the confusion. It might have been better to keep the md file changes in a PR and merge it once the 4.0 release is made.

**Comment by timowest** [comment]
Closing, since 4.0 is out now.
