### ISSUE TITLE
orderBy(...) in JPASubQuery goes against JPQL specs

### ISSUE THREAD

**Issue by MichaelTontchev** [querydsl/querydsl#1346]
Both orderBy functions in JPASubQuery should be disallowed, since JPQL doesn't allow "order by" clauses in subqueries (see https://openjpa.apache.org/builds/1.2.0/apache-openjpa-1.2.0/docs/manual/jpa_langref.html#jpa_langref_subqueries ).

Posted this to (https://groups.google.com/d/msg/querydsl/Vy5KNTEj2c8/OaHFvJ33sH0J) and it was suggested I post here. Hope I posted it correctly :)

**Comment by Shredder121** [comment]
Thank you, this allows us to keep track of the issue at hand.

**Comment by jwgmeligmeyling** [comment]
Fixed in 3.x, won't fix in 4.x. Also, some ORMs support order by in subqueries, in particular subqueries that specify a limit.
