### ISSUE TITLE
Unable to sort case in/sensitive

### ISSUE THREAD

**Issue by Tibor17** [querydsl/querydsl#1356]
We are using JPAQuery for creating query to db.
We need to create query with „order by“ clause and implement something like „ALTER SESSION SET NLS_SORT=BINARY_CI“ command  to use algorithm for sorting.
Does exists any solution how implement this feature?

**Comment by Tibor17** [comment]
@timowest Can you help with this? Do we have any API alternatives?

**Comment by timowest** [comment]
For `JPAQuery` there is no direct way to way from the Querydsl level to customize the resulting SQL. So you will need to define a JPQL custom function that is transformed into `ALTER SESSION SET NLS_SORT=BINARY_CI` internally.

**Comment by Tibor17** [comment]
@timowest 
I found the hint with function Expression but not with `ALTER SESSION`. Do you know where to start?

**Comment by timowest** [comment]
Isn't `ALTER SESSION` just a separate statement? You can execute it individually. I am not sure if that part needs to be Querydsl wrapped, since it is static.

**Comment by Tibor17** [comment]
Not mandatory to call a fix in querydsl, Thx.
