### ISSUE TITLE
setLockMode() should not exist for JPAUpdateClause and JPADeleteClause

### ISSUE THREAD

**Issue by MichaelTontchev** [querydsl/querydsl#1367]
I'm looking at the major JPA providers, and every single one besides OpenJPA restricts setLockMode() to only work for select queries:

Hibernate: http://grepcode.com/file/repo1.maven.org/maven2/org.hibernate/hibernate-entitymanager/4.3.8.Final/org/hibernate/jpa/spi/AbstractQueryImpl.java#AbstractQueryImpl.setLockMode%28javax.persistence.LockModeType%29

EclipseLink: http://grepcode.com/file/repo1.maven.org/maven2/org.eclipse.persistence/eclipselink/2.6.0-RC1/org/eclipse/persistence/internal/jpa/QueryImpl.java#QueryImpl.setLockMode%28javax.persistence.LockModeType%29

Data Nucleus: http://grepcode.com/file/repo1.maven.org/maven2/org.datanucleus/datanucleus-api-jpa/4.0.6/org/datanucleus/api/jpa/JPAQuery.java#JPAQuery.setLockMode%28javax.persistence.LockModeType%29

In fact, it seems like javax itself specifies that

Throws: IllegalStateException - if the query is found not to be a Java Persistence query language SELECT query or a Criteria API query

Timo confirmed that it appears that this function shouldn't exist for those two classes:

https://groups.google.com/d/msg/querydsl/WNcg1R-0xEc/8Li4cdTewA8J

**Comment by kulikoum** [comment]
Are there any plans to fix that?
