### ISSUE TITLE
Performing coalesce on NumberPath in from or where clause

### ISSUE THREAD

**Issue by robertandrewbain** [querydsl/querydsl#1376]
`ComparableExpressionBase`'s `public final Coalesce<T> coalesce(Expression<?>...exprs)` returns a `Coalesce<T>`. `Coalesce` does not have `SimpleExpression`'s `public BooleanExpression eq(T right)` method, so I assume the idea is to use `Coalesce`'s `public NumberExpression<?> asNumber()`. However if you try to E.G: (I know the query is nonsense)

``` java
query()
.from(someRelationalPathBase)
.innerJoin(someOtherRelationalPathBase)
.on(someRelationalPathBase.id.coalesce(someOtherRelationalPathBase.id).asNumber().eq(someRelationalPathBase.id));
```

you receive the compiler error `The method eq(capture#2-of ?) in the type SimpleExpression<capture#2-of ?> is not applicable for the arguments (NumberPath<Long>)`. I'm working around this with the following code:

``` java
 @SuppressWarnings("unchecked")
 public static <T extends Number & Comparable<T>> NumberOperation<T> coalesceNumbers(NumberPath<T> arg0, NumberPath<T> arg1) {
   return ((NumberOperation<T>) arg0.coalesce(arg1).asNumber());
 }
```

**Comment by cenobyte321** [comment]
Is there a workaround for this particular issue?

**Comment by jwgmeligmeyling** [comment]
The current workaround is a cast: `(NumberExpression<Long>) someRelationalPathBase.id.coalesce(someOtherRelationalPathBase.id).asNumber()`
