### ISSUE TITLE
Serialisation

### ISSUE THREAD

**Issue by JamesPatageule** [querydsl/querydsl#1383]
Hi,

Since few versions, it's not possible to serialize some objects like Predicate (and maybe OrderSpecicier).

I want to use the 3.6.3.

I'm using it to directly transfer restrictions between my FRONT and my BACK offices.

The class with problem is at least : com.mysema.query.types.path.PathBuilderValidator.
The 3 final anonymous classes inside aren't Serializable.

Thanks

**Comment by JamesPatageule** [comment]
Thanks for that guys !

Is it possible to have a Backport to the 3.X.X release please ?

I cannot go with the 4.X.X version until spring-data release the new one ...

**Comment by timowest** [comment]
The fix is also available in 3.6.4.
