### ISSUE TITLE
Possibility to skip adding source when exporting with maven plugin

### ISSUE THREAD

**Issue by TuomasKiviaho** [querydsl/querydsl#1391]
The `querydsl-maven-plugin` insists on adding the target folder as source folder which is especially nasty when phase is 'generated-test-sources`. The generated test classes end up in source compile root because `isForTest`is harcoded always as being false for `export` goal.

```
        if (isForTest()) {
            project.addTestCompileSourceRoot(targetFolder);
        } else {
            project.addCompileSourceRoot(targetFolder);
        }
```

There is currently no workaround to my knowledge because guys at `buildhelper-maven-plugin` are reluctant to implement remove functionality for sources (or anything else for that matter) and insist that the problems are better dealt in the problematic plugin.

I ask either that the `isForTest` would be implemented based on the lifecycle phase at hand (`testClassPath` parameter can be used as poor mans alternative) or that there would be an additional `source` parameter for disabling this completely.

**Comment by timowest** [comment]
The `test-export` goals handles the test case. 

Maybe that goal could be deprecated and testClasspath attribute could be used instead. Looking at the lifecycle to decide if we are in test mode feels a little insecure.

**Comment by TuomasKiviaho** [comment]
>Use the goal test-export to add the targetFolder as a test compile source root instead of a compile source root.

Thanks a lot for the pointer and sorry for the waste of your time. I think that the current approach follows maven practices and this was only me being sloppy at RTFM.
