### ISSUE TITLE
Reusable QueryDSL JPA query with IN clause parameter

### ISSUE THREAD

**Issue by ghost** [querydsl/querydsl#1393]
QueryDSL already supports parameters in queries for single values like the following:

```
QFilmEntity fe = QFilmEntity.filmEntity;
Param<String> param = new Param<>(String.class,"rating");
JPAQuery query = new JPAQuery().from(fe).where(fe.rating.eq(param)).distinct();
```

You can then set the parameter like this:

```
query.set(param,"G");
```

QueryDSL should also support parameters for a collection of values like the following:

```
QFilmEntity fe = QFilmEntity.filmEntity;
JPAQuery query = new JPAQuery().from(fe).where(fe.rating.in([Some Collection Parameter]));
```

The 'in' operation currently accepts a CollectionExpression but there is no Parameter implementation of CollectionExpression..

**Comment by jwgmeligmeyling** [comment]
`in(Expression<Collection<T>>)` is probably going to collide with `in(Expression<T>... expressions`.

Therefore, I think its more appropiate to add `Expressions.asCollection(Expression<Collection<T>>)` which could be used as `fe.rating.in(Expressions.asCollection(param))`.

**Comment by yang03265** [comment]
This is implemented in https://github.com/querydsl/querydsl/blob/99e3ca936f46471bc61d9af6e1a3dbb16f3f12b3/querydsl-sql/src/test/java/com/querydsl/sql/AbstractSQLTemplatesTest.java#L179
