### ISSUE TITLE
3.6.4 silently requires new Hibernate version

### ISSUE THREAD

**Issue by olivergierke** [querydsl/querydsl#1406]
[This commit](https://github.com/querydsl/querydsl/commit/73e9f6c8cc839b2024b42220858456af86d70124) implicitly raises the required Hibernate version from 3.x to 4.x. While this is probably not a problem in the wild, I didn't expect such change in a bugfix release.

**Comment by Shredder121** [comment]
Hello Oliver,
There you have a point, we'll try to look more critically to the fixes.

I think that it's a good idea to keep this open until we have the necessary things in place to guarantee that this doesn't happen as often anymore.
