### ISSUE TITLE
Collections: Failure of setting up classpath for javac in case of running in Spring Boot

### ISSUE THREAD

**Issue by villuv** [querydsl/querydsl#1407]
First, I'm really not sure if this is QueryDSL or Spring Boot issue. Nevertheless, the same code runs fine in application server or standalone java program. Fails also when run as exploded Spring Boot app.

Minimal reproduction code:

https://github.com/villuv/spring-boot-querydsl-bug/

When run as Spring Boot application, it tries to compile the code generated at runtime, but fails:

```
/Q_01943648192_1275614662_1275614662_1195259493.java:7: error: package com.querydsl.collections does not exist
        if (com.querydsl.collections.CollQueryFunctions.equals(bean.getValue(), a1)) {
                                    ^
1 error

    at com.mysema.codegen.JDKEvaluatorFactory.compile(JDKEvaluatorFactory.java:74)
    at com.mysema.codegen.AbstractEvaluatorFactory.createEvaluator(AbstractEvaluatorFactory.java:128)
    at com.querydsl.collections.DefaultEvaluatorFactory.createEvaluator(DefaultEvaluatorFactory.java:151)
    at com.querydsl.collections.DefaultQueryEngine.evaluateSingleSource(DefaultQueryEngine.java:165)
    at com.querydsl.collections.DefaultQueryEngine.list(DefaultQueryEngine.java:80)
    at com.querydsl.collections.AbstractCollQuery.fetch(AbstractCollQuery.java:188)
    at villuv.springboot.querydsl.bug.app.TestRunner.run(TestRunner.java:18)
```

It looks like classpath entries returned by Spring Boot (as URLs) are not quite correctly composed to classpath javac parameter.

**Comment by Shredder121** [comment]
First of all, thanks for the minimal reproduction code.
However, I have issues with building it, can you verify that your project builds when using a clean maven repo?

```
The build could not read 1 project -> [Help 1]
  
  The project villuv.springboot:springboot-querydsl-bug:1.0-SNAPSHOT (X:\Git\github\querydsl\issues\spring-boot-querydsl-bug\pom.xml) has 2 errors
    Non-resolvable import POM: Could not find artifact org.springframework.data:spring-data-releasetrain:pom:Gosling-M1 in spring-snapshots (http://repo.spring.io/snapshot) @ org.springframework.boot:spring-boot-dependencies:1.3.0.BUILD-SNAPSHOT, x:\dev\m2repo\org\springframework\boot\spring-boot-dependencies\1.3.0.BUILD-SNAPSHOT\spring-boot-dependencies-1.3.0.BUILD-SNAPSHOT.pom, line 1480, column 16 -> [Help 2]
    Non-resolvable import POM: Could not find artifact org.springframework.integration:spring-integration-bom:pom:4.2.0.M1 in spring-snapshots (http://repo.spring.io/snapshot) @ org.springframework.boot:spring-boot-dependencies:1.3.0.BUILD-SNAPSHOT, x:\dev\m2repo\org\springframework\boot\spring-boot-dependencies\1.3.0.BUILD-SNAPSHOT\spring-boot-dependencies-1.3.0.BUILD-SNAPSHOT.pom, line 1492, column 16 -> [Help 2]

```

**Comment by johnktims** [comment]
I switched spring-boot-starter-parent's version back to 1.2.3.RELEASE and added commons-logging to fix the build. Now it's working when I use `maven clean test` or `mvn clean spring-boot:run`. How are you running the application?

Also I noticed you have an `@ImportResource` that references a file that I can't find in the project but oddly-enough does not prevent the application from running.

**Comment by villuv** [comment]
OK, I switched now back to Spring Boot 1.2.4 release version and it builds. I don't have any custom repos here so it should now build for you too.

**Comment by johnktims** [comment]
The project is still running fine for me. How are you running it?

**Comment by villuv** [comment]
I run it with `java -jar target/springboot-querydsl-bug-1.0-SNAPSHOT.jar`

Yeah, this `@ImportResource` is a copy-paste cruft remaining in. It is not required.

**Comment by villuv** [comment]
I can confirm that with `mvn spring-boot:run` it works for me too. I have to debug it, maybe it is using Maven's classloader in this case, not sure....

**Comment by Shredder121** [comment]
Using `exec-maven-plugin:1.2.1:exec` works as well, I even added one `TheBean` to the list, I get results.
Please, if you find where it does fail we'd like to hear it.

**Comment by villuv** [comment]
I can reproduce it also with running exploded archive:
```
unzip springboot-querydsl-bug-1.0-SNAPSHOT.jar
java org.springframework.boot.loader.JarLauncher
```

**Comment by villuv** [comment]
What I've discovered so far:
When running with maven, classloader has classpath entries from local maven repository, like
```
0 = {URL@2231} "file:/Users/villuv/src/misc/springboot-querydsl-bug/src/main/resources/"
1 = {URL@2232} "file:/Users/villuv/src/misc/springboot-querydsl-bug/src/main/resources/"
2 = {URL@2233} "file:/Users/villuv/src/misc/springboot-querydsl-bug/target/classes/"
3 = {URL@2234} "file:/Users/villuv/.m2/repository/com/google/code/findbugs/annotations/2.0.1/annotations-2.0.1.jar"
4 = {URL@2235} "file:/Users/villuv/.m2/repository/org/springframework/spring-core/4.1.6.RELEASE/spring-core-4.1.6.RELEASE.jar"
5 = {URL@2236} "file:/Users/villuv/.m2/repository/org/springframework/spring-context/4.1.6.RELEASE/spring-context-4.1.6.RELEASE.jar"
6 = {URL@2237} "file:/Users/villuv/.m2/repository/com/google/code/findbugs/jsr305/1.3.9/jsr305-1.3.9.jar"
7 = {URL@2238} "file:/Users/villuv/.m2/repository/org/yaml/snakeyaml/1.14/snakeyaml-1.14.jar"
.....
```
But when I run in "production mode", with `java -jar`, the classpath containes 'deep jar' URLs:

```
0 = {URL@2237} "jar:file:/Users/villuv/src/misc/springboot-querydsl-bug/target/springboot-querydsl-bug-1.0-SNAPSHOT.jar!/"
1 = {URL@2238} "jar:file:/Users/villuv/src/misc/springboot-querydsl-bug/target/springboot-querydsl-bug-1.0-SNAPSHOT.jar!/lib/spring-boot-starter-1.2.4.RELEASE.jar!/"
2 = {URL@2239} "jar:file:/Users/villuv/src/misc/springboot-querydsl-bug/target/springboot-querydsl-bug-1.0-SNAPSHOT.jar!/lib/spring-boot-1.2.4.RELEASE.jar!/"
3 = {URL@2240} "jar:file:/Users/villuv/src/misc/springboot-querydsl-bug/target/springboot-querydsl-bug-1.0-SNAPSHOT.jar!/lib/spring-boot-starter-logging-1.2.4.RELEASE.jar!/"
4 = {URL@2241} "jar:file:/Users/villuv/src/misc/springboot-querydsl-bug/target/springboot-querydsl-bug-1.0-SNAPSHOT.jar!/lib/jcl-over-slf4j-1.7.12.jar!/"
5 = {URL@2242} "jar:file:/Users/villuv/src/misc/springboot-querydsl-bug/target/springboot-querydsl-bug-1.0-SNAPSHOT.jar!/lib/jul-to-slf4j-1.7.12.jar!/"
6 = {URL@2243} "jar:file:/Users/villuv/src/misc/springboot-querydsl-bug/target/springboot-querydsl-bug-1.0-SNAPSHOT.jar!/lib/log4j-over-slf4j-1.7.12.jar!/"
...
```

Now, this here https://github.com/querydsl/codegen/blob/master/src/main/java/com/mysema/codegen/SimpleCompiler.java#L69 deals with composing the classpath parameter for the compiler. And it seems to be unable to handle those "deep jar URLs" correctly. For example, classpath entry from classloader:
```
jar:file:/Users/villuv/src/misc/springboot-querydsl-bug/target/springboot-querydsl-bug-1.0-SNAPSHOT.jar!/
```
`decodedPath` becomes
```
file:/Users/villuv/src/misc/springboot-querydsl-bug/target/springboot-querydsl-bug-1.0-SNAPSHOT.jar!/
```
And following thing gets added to `paths`
```
/Users/villuv/src/misc/springboot-querydsl-bug/target/file:/Users/villuv/src/misc/springboot-querydsl-bug/target/springboot-querydsl-bug-1.0-SNAPSHOT.jar!
```
Notice that it keeps the `file:` scheme name in the middle of it and also prepends a full path even though the URL already is a full path.
Next up, `pathJoiner` will concatenate all these entries together, using `:` as path separator character. This means, classpath string that gets given to the compiler can't be decoded correctly.

The difference how the classloader sees the classpath explains why it works when run from maven, but doesn't when run standalone.

Actually I'm not even sure if Java compiler can handle those nested jars on classpath even if they would get correctly referenced....

**Comment by Shredder121** [comment]
To debug:
```
java -Xdebug -Xrunjdwp:transport=dt_socket,address=8888,server=y,suspend=y -jar springboot-querydsl-bug-1.0-SNAPSHOT.jar
```

It seems that using maven, it builds the classpath urls using artifacts in the maven repository.
Using java on the command line uses the nested jars.

Could you file an issue at codegen?

**I see I was just not fast enough**

**Comment by Shredder121** [comment]
@villuv Yes, I also see that nested jars might be very problematic..

**Comment by villuv** [comment]
well, it _might_ just work with exploded jar deployment in case this gets corrected.

**Comment by villuv** [comment]
Filed querydsl/codegen#28

**Comment by xvipservice** [comment]
any one fix this bug?

**Comment by xvipservice** [comment]
i unzip it ,modify codege code add classpath...is't so ....................
