### ISSUE TITLE
Querydsl generated sql query wrong sql type (nvarchar instead of varchar)

### ISSUE THREAD

**Issue by oosterholt** [querydsl/querydsl#1410]
Querydsl is generating a stored procedure with a `nvarchar` parameter for the column, but the table's column type is `varchar`. This way MS-SQLServer is not able to use its index.

The metadata which is used by Querydsl is generated using Querydsl's `MetaDataSerializer` (ant target).

---  

*DB table*:  
TableX with three columns: id (int), ColA (varchar) and ColB (nvarchar)

*Generated metadata*:

    public class QTableX extends com.mysema.query.sql.RelationalPathBase<QTableX> {
    
        private static final long serialVersionUID = 1142355320;
    
        public static final QTableX TableX= new QTableX("TableX");

        public final StringPath id = createNumber("id", Integer.class);    

        public final StringPath colA= createString("ColA");
    
        public final StringPath colB= createString("ColB");
    
        public QTableX(String variable) {
            super(QTableX.class, forVariable(variable), "dbo", "TableX");
        }
    
        public QTableX(Path<? extends QTableX> path) {
            super((Class)path.getType(), path.getMetadata(), "dbo", "TableX");
        }
    
        public QTableX(PathMetadata<?> metadata) {
            super(QTableX.class, metadata, "dbo", "TableX");
        }
    }

*Querydsl*:

    SQLQuery query = new SQLQuery(dbCon, new SQLServerTemplates());
        query.from(QTableX.TableX).where(QTableX.TableX.colA.eq("FieldName")
            .and(QTableX.TableX.colB.like(".1.")));
    List<Tuple> tuples = query.list(new QTuple(TableX.id));

*generated sql*:

    declare @p1 int
    set @p1=NULL

    -- @P0 should be varchar (not nvarchar)
    exec dbo.sp_prepare @p1 output,N'@P0 nvarchar(4000),@P1 nvarchar(4000)',N'select TableX.id
        from TableX TableX
        where TableX.ColA =  @P0  and TableX.ColB like  @P1  escape ''\''',1
    
    exec dbo.sp_execute @p1, N'FieldName', N'.1.'

**Comment by timowest** [comment]
Which Querydsl version do you use?

**Comment by oosterholt** [comment]
I'm using version 2.9.0

**Comment by timowest** [comment]
2.9.0 is not supported anymore. Is upgrading to 3.* or 4.* an option for you?

**Comment by oosterholt** [comment]
I updated to 3.6.4, but the issue still occurred. 
Will updating to 4.* solve the issue you think (takes more time to refactor due to major changes)?

**Comment by timowest** [comment]
Could you provide the QTableX sources when generated with 3.6.4?

**Comment by oosterholt** [comment]
/**
	 * QTableX is a Querydsl query type for QTableX
	 */
	@Generated("com.mysema.query.sql.codegen.MetaDataSerializer")
	public class QTableX extends com.mysema.query.sql.RelationalPathBase<QTableX> {
		private static final long serialVersionUID = 1142355320;
		public static final QTableX TableX = new QTableX("TableX");
		public final StringPath ColA = createString("ColA");
		public final StringPath ColB = createString("ColB");
		public final NumberPath<Integer> id = createNumber("id", Integer.class);
		public final com.mysema.query.sql.PrimaryKey<QTableX> tableXPK = createPrimaryKey(id, ColA);
		public QTableX(String variable) {
			super(QTableX.class, forVariable(variable), "dbo", "TableX");
			addMetadata();
		}
		public QTableX(String variable, String schema, String table) {
			super(QTableX.class, forVariable(variable), schema, table);
			addMetadata();
		}
		public QTableX(Path<? extends QTableX> path) {
			super(path.getType(), path.getMetadata(), "dbo", "TableX");
			addMetadata();
		}
		public QTableX(PathMetadata<?> metadata) {
			super(QTableX.class, metadata, "dbo", "TableX");
			addMetadata();
		}
		public void addMetadata() {
			addMetadata(ColA, ColumnMetadata.named("ColA").withIndex(2).ofType(Types.VARCHAR).withSize(50).notNull());
			addMetadata(ColB, ColumnMetadata.named("ColB").withIndex(3).ofType(Types.VARCHAR).withSize(255));
			addMetadata(id, ColumnMetadata.named("id").withIndex(1).ofType(Types.INTEGER).withSize(10).notNull());
		}
	}

ColA metadata seems correct.
ColB metadata incorrect (needs to be NVARCHAR)

Generated query is still incorrect and seems to ignore metadata for both type and length:

    declare @p1 int
    set @p1=2
    exec sp_prepare @p1 output,N'@P0 nvarchar(4000),@P1 nvarchar(4000)',N'select TableX.id
    from TableX TableX
    where TableX.ColA =  @P0  and (TableX.ColB like  @P1  escape ''\'')',1
    select @p1

**Comment by timowest** [comment]
Could you post also the SQL that is rendered by Querydsl? What you posted seems to be some internal representation annotated with type parameters.

**Comment by oosterholt** [comment]
The query is a stored procedure.

I'm not sure how to get the query as generated by Querydsl. I've just posted the query as performed by the DB (used Query profiler).
How can I give you the query you need?

**Comment by timowest** [comment]
query.toString() will give you something close. The log4j logger of AbstractSQLQuery will log the query.

It should be something like 

```sql
select TableX.id
from TableX TableX
where TableX.ColA =  ?  and TableX.ColB like  ?  escape '\'
```

**Comment by oosterholt** [comment]
query.toString():

    select ItemValues.ItemID
    from ItemValues ItemValues
    where ItemValues.Field = ? and (ItemValues.FieldValue like ? escape '\')

**Comment by oosterholt** [comment]
Can I supply any additional information to help fix this issue?

**Comment by timowest** [comment]
Querydsl provides only the SQL query and the prepared statement bindings using JDBC to the database.   Do you see a way to fix the issue on this level?

**Comment by oosterholt** [comment]
Can you give me any hints how to do this?

**Comment by Shredder121** [comment]
What we mean is that we do not see the database, we have the connection and through JDBC we provide the SQL statement with the bindings.
More than that is an implementation detail and not the API.

Do you know/see any way that we can fix the issue on the JDBC API level?

**Comment by timowest** [comment]
There doesn't seem to be a solution for this on the Querydsl level, so I am closing this. Feel free to reopen, if you find a solution that can be provided from our side.
