### ISSUE TITLE
SQLExpressions.datediff does not work on Oracle

### ISSUE THREAD

**Issue by sphd** [querydsl/querydsl#1411]
We are using SQLExpressions.datediff() to find product-reservations that are already expired, i.e. where the reservationDate + the reservationTimeInMinutes < currentTime:

``` java
Timestamp expiryDate = new Timestamp(new Date().getTime());
BooleanExpression expired =
    SQLExpressions.datediff(DatePart.minute, contractProductReservation.reservationDate, expiryDate).gt(
        contractProductReservation.reservationTimeInMinutes);
long deleted = new SQLDeleteClause(getConnection(), getTemplates(), contractProductReservation).where(expired).execute();
```

This fails with the built-in OracleTemplates.DEFAULT:

``` java
public SQLTemplates getTemplates() {
    return OracleTemplates.DEFAULT;
}
```

=>
com.mysema.query.QueryException: Caught SQLSyntaxErrorException for delete from CONTRACT_PRODUCT_RESERVATION
where round((? - CONTRACT_PRODUCT_RESERVATION.RESERVATION_DATE) \* 1440) > CONTRACT_PRODUCT_RESERVATION.RESERVATION_TIME_IN_MINUTES
[...]
java.sql.SQLSyntaxErrorException: ORA-00932: inconsistent datatypes: expected NUMBER got INTERVAL DAY TO SECOND

but works if we patch the OracleTemplates:

``` java
public SQLTemplates getTemplates() {
    return new OracleTemplates() {

        {
            // querydsl-sql library (v3.6.2) has a wrong datediff template for oracle,
            // so we redefine it:
            add(Ops.DateTimeOps.DIFF_WEEKS, "round(extract(day from ({1} - {0}) / 7))");
            add(Ops.DateTimeOps.DIFF_DAYS, "extract(day from {1} - {0})");
            add(Ops.DateTimeOps.DIFF_HOURS, "extract(day from ({1} - {0}) * 24)");
            add(Ops.DateTimeOps.DIFF_MINUTES, "extract(day from ({1} - {0}) * 1440)");
            add(Ops.DateTimeOps.DIFF_SECONDS, "extract(day from ({1} - {0}) * 86400)");
        }

    };
}
```

Maybe you want to apply our patch to your code base?

Greetings,

```
Harry
```

**Comment by timowest** [comment]
Thanks for the bug report! Could you provide the fix in pull request form? Ideally with an attached test that fails?

**Comment by yourganesan** [comment]
We are facing exactly the same issue. Any idea on when this ticket will be addressed?

**Comment by limkinZero** [comment]
Hi, Do you have any idea when the correction will be included?
