### ISSUE TITLE
singleResult function results in wrong query

### ISSUE THREAD

**Issue by 9DA** [querydsl/querydsl#1417]
Whilst using common table expressions, `query.singleResult(<table>.<column>.count())` results in incorrect SQL being generated whereas `query.uniqueResult(<table>.<column>.count())` works fine:

The resulting SQL when using singleResult() is:

    with select * from (type as ... ) where rownum ...;

instead of

    select * from (with type as ...) where rownum ...;

**Comment by timowest** [comment]
Could you provide a simple example query that produces this error?

**Comment by timowest** [comment]
Fixed in 4.0.4 and 3.6.7. Duplicate of https://github.com/querydsl/querydsl/issues/1487
