### ISSUE TITLE
postgresql: numeric mapped to BigInteger

### ISSUE THREAD

**Issue by tcn** [querydsl/querydsl#1425]
Hi!

"without any precision or scale creates a column in which numeric values of any precision and scale can be stored, up to the implementation limit on precision."
http://www.postgresql.org/docs/9.0/static/datatype-numeric.html

However querydsl (4.0.2) maps it to BigInteger instead of BigDecimal (probably the <= 0 in JDBCTypeMapping.getNumericClass()).

**Comment by timowest** [comment]
In this case PostgreSQL seems to violate the SQL spec and also the JDBC drivers returns null for decimals.
