### ISSUE TITLE
list(employee.age.max()) returns list with one null element if no employee is found

### ISSUE THREAD

**Issue by sg-ad** [querydsl/querydsl#1430]
Instead of returning an empty list, the following query returns a list with a single null element if no employees are named Homer:
```
query.from(employee)
    .where(employee.name.eq("Homer"))
        .list(employee.age.max())
```
...I know, why make a list when max() will only give a single result?  Because an empty list can be provided as input to `.in()` whereas `.eq()` won't appreciate a `null` unique result.

**Comment by Shredder121** [comment]
I am going to refer to and quote an answer from [this question on StackOverflow](http://stackoverflow.com/questions/5819496/select-a-max-on-date-column-not-working-with-empty-table).

>Actually it is working. It is just not working the way you think it should.

After serializing the query, the database does the work of executing it. And returns that as result.

Does it solve the problem?

**Comment by sg-ad** [comment]
I understand your point.  However, when the result of an aggregate function is used as a subselect, it works great in pure SQL.  Consider the following two statements:

``` sql
select bonus.amount from bonus_payouts bonus where bonus.id = (select max(bonus_id) from employee_bonuses where employee_id = 'someid');
select bonus.amount from bonus_payouts bonus where bonus.id in (select max(bonus_id) from employee_bonuses where employee_id = 'someid');
```
If no employee 'someid' is found with a bonus, both of these statements will simply return an empty result.  If I try to reproduce the same queries using QueryDSL, I get:

``` java
query.from(bonusPayout)
    .where(bonusPayout.id.eq(
        query.from(employeeBonuses)
            where(employeeBonuses.employee.id.eq('someid'))
            .uniqueResult(employeeBonuses.bonusPayout.id.max()))
    .uniqueResult(bonusPayout);
```
or, using `.in()`
``` java
query.from(bonusPayout)
    .where(bonusPayout.id.in(
        query.from(employeeBonuses)
            where(employeeBonuses.employee.id.eq('someid'))
            .list(employeeBonuses.bonusPayout.id.max()))
    .uniqueResult(bonusPayout);
```
Both of these statements fail when the subquery finds nothing.  The only way I've been able to get this to work is by using `coalesce()` like this:
``` java
query.from(bonusPayout)
    .where(bonusPayout.id.in(
        query.from(employeeBonuses)
            where(employeeBonuses.employee.id.eq('someid'))
            .list(employeeBonuses.bonusPayout.id.max().coalesce(0L)))
    .uniqueResult(bonusPayout);
```
This will cause the subquery to return an id of `0` instead of `null`.

Unless I'm missing something, IMHO a subquery of the sort when used with `eq()` or `in()` (or, ideally, both) should accommodate a `null` from the aggregate function.  What do you think?

**Comment by timowest** [comment]
@sg-ad You don't use subqueries at all here. You need to replace the nested query usage with `new JPASubQuery()`.

**Comment by sg-ad** [comment]
@timowest You're right, two queries were being issued.  Proper subquery works as expected.  Thanks!
