### ISSUE TITLE
Cast boolean to number in MySQL generates error

### ISSUE THREAD

**Issue by githubjul** [querydsl/querydsl#1433]
Hello,

I used to work with JPAQuery in QueryDSL.

Now, I need to make a query with some aggregations using a boolean field (tinyint(1) in MySQL)

Here's my code (I've shortened the request) :

``` java
JPAQuery query = new JPAQuery(em);
QMyEntity myEntity = QMyEntity.myEntity;

NumberExpression<Integer> nExprRefused = myEntity.isRefused.castToNum(Integer.class);
NumberExpression<Integer> nExprAccepted = myEntity.isAccepted.castToNum(Integer.class);

return query.from(myEntity)
        .groupBy(myEntity.otherField)
        .list(Projections.constructor(
                       MyProjection.class
                       , nExprAccepted.sum()
                       , nExprRefused.sum()
                       , myEntity.otherField)
                       )
             );
```

The problem is that the cast is made like this :

CAST (t0.isRefused as INTEGER)

So MySQL throws an error.

I'd like to have :

CAST (t0.isRefused as SIGNED INTEGER)

... but I don't know how to do this.

So if someone here could help me to find a solution it'll be very pleasant :)

Thanks for your help !

Julien

**Comment by timowest** [comment]
Could you post the exception or error message?

**Comment by timowest** [comment]
Also which JPA provider do you use?

**Comment by julien20vt** [comment]
Hello Timo,

We use eclipslink 2.5.

We don't have error in the code, it's mysql which doesn't accept the request because the cast is made as INTEGER and not as SIGNED INTEGER
(When I change it and execute manually my sql request, it works)

We use MySQL 5.5

Regards,

Julien

**Comment by kjordan2001** [comment]
Will this be fixed at some point?  I just ran into the same issue since I wanted to use Integers but countDistinct uses Long and my counts won't be big enough that I'll run into an overflow.
