### ISSUE TITLE
condition "where id in (subquery) " throw nullpointer where subquery returns no results

### ISSUE THREAD

**Issue by zamrokk** [querydsl/querydsl#1434]
I have a subquery like this :  

    ...
    .and(gedSep.identifiant.in(this.newJpaQuery().from(gedSep).innerJoin(gedSep.gedDocumentEntity)
                                .orderBy(gedSep.identifiant.desc()).singleResult(gedSep.identifiant)))

then when my subquery returns no result , a nullpointer exception is thrown

    Caused by: java.lang.NullPointerException
	at com.mysema.util.MathUtils.cast(MathUtils.java:53) [querydsl-core.jar:]
	at com.mysema.query.types.expr.NumberExpression.convert(NumberExpression.java:684) [querydsl-core.jar:]
    at com.mysema.query.types.expr.NumberExpression.in(NumberExpression.java:673) [querydsl-core.jar:]

i'm expected the condition to not explode with a null pointer. How can i do a workaround to avoid this case ?

Thanks

**Comment by zamrokk** [comment]
to help, the sql looks like 

    where id in ()

**Comment by zamrokk** [comment]
in SQL we could use "EXISTS" clause      :/

**Comment by sg-ad** [comment]
Related to this other issue https://github.com/querydsl/querydsl/issues/1430.  In my case it was possible to leverage `coalesce()` as a workaround.

**Comment by zamrokk** [comment]
not bad idea, actually as a workaround i was testing a "not null" and returning a default "-1"

**Comment by timowest** [comment]
@zamrokk It looks like you intended to write a subquery, but what you got instead were two query executions.


    ...
    .and(gedSep.identifiant.in(new JPASubQuery().from(gedSep).innerJoin(gedSep.gedDocumentEntity)
                                .orderBy(gedSep.identifiant.desc()).list(gedSep.identifiant)))

**Comment by zamrokk** [comment]
Exactly.

Finally is more about a SQL problem

**Comment by timowest** [comment]
@zamrokk Did you get the query to work?

I am closing this, since there doesn't seem to be any further action required.

**Comment by timowest** [comment]
similar to https://github.com/querydsl/querydsl/issues/1430

**Comment by zamrokk** [comment]
yes, i used a not null test first and returning -1 if no results found

finally i used coalesce() because it was nicer

**Comment by timowest** [comment]
And you also used a real subquery?

**Comment by zamrokk** [comment]
a normal jpa query into the "in" clausus

**Comment by zamrokk** [comment]
your are right , is much better to have a subquery 

finally i came with that 

    .in(new JPASubQuery().from(gedSep).innerJoin(gedSep.gedDocumentEntity).distinct()
                                                        .groupBy(gedSep.gedDocumentEntity).list(gedSep.identifiant.max().coalesce(new Long(-1))))

**Comment by timowest** [comment]
is the coalesce still necessary with the subquery?

**Comment by zamrokk** [comment]
yep , you are right again. Is no more needed with a subquery !

Thanks a lot !
