### ISSUE TITLE
There maybe missing call  listener's end(...) method.

### ISSUE THREAD

**Issue by leotu** [querydsl/querydsl#1436]
AbstractSQLQuery.java (version 4.0.2)
"protected void endContext(SQLListenerContext context)" should be called in finally block, 
ie,
try {
   ...
 } finally {
   ...
   endContext(context);
   ...
}

but  method "iterateSingle" only call it in catch exception code block.

 private CloseableIterator<T> iterateSingle(QueryMetadata metadata, @Nullable final Expression<T> expr) { ...
    try {
        ...
     } catch (SQLException e) {
            onException(context, e);
            endContext(context);
            throw configuration.translate(queryString, constants, e);
        } finally {
            reset();
        }

**Comment by Shredder121** [comment]
Iteration doesn't stop when the iterator is done creating, it's when the CloseableIterator's close method is called.
I do appreciate you noticing, but it is intentional.
Does it answer your question?

**Comment by timowest** [comment]
This is intentional behaviour to close the context when the iterator is fully consumed.
