### ISSUE TITLE
Column group by dynamic

### ISSUE THREAD

**Issue by adrianobr** [querydsl/querydsl#1437]
QueryDSL: 3.6.5
JPA: 2.0

I would like to create the query with QueryDSL , but I'm finding it difficult to use alias along with grouping.

PostgreSQL:

``` sql
select length(my_column) as column_size from my_table group by column_size
```

i'am using

``` java
NumberPath<Integer> column_size= Expressions.numberPath(Integer.class, "column_size");
List<Integer> users = from().groupBy(column_size).list(usuario.login.length().as(column_size));
```

This returning the exception stating that the column  column_size does not exist:
Look return from console:
select length(lgn) as col_0_0_ from sgrusr01 group by column_size
"ERRO:  coluna "column_size" não existe
LINE 2: group by COLUMN_SIZE
                 ^

*********\* Error **********

ERRO: coluna "column_size" não existe
SQL state: 42703
Character: 56"

**Comment by timowest** [comment]
Thanks for the bug report! Did you try this also with JPQL directly?

**Comment by timowest** [comment]
This looks similar to https://hibernate.atlassian.net/browse/HHH-1902

**Comment by michelkaeser** [comment]
Exactly the issue I am currently encountering. Seems hibernate did also not solve it yet.
