### ISSUE TITLE
Reference SQL union query from JPA

### ISSUE THREAD

**Issue by ageery** [querydsl/querydsl#144]
From: https://groups.google.com/forum/#!searchin/querydsl/geery/querydsl/bxh77RO0OCg/overview

I have two SQLSubQuery objects that I want to use together in a union.  There is a union() method on SQLSubQuery, but calling it doesn't work as expected.

My ultimate goal is, from a JPAQuery, to run an in-query against a union (e.g., select \* from contact where id in (select .... union select ...)).  The only way to use a union is to use SQL and since it's a sub-query I'm using SQLSubQuery.

Here's my code:

final SQLSubQuery subquery1 = new SQLSubQuery();
....
final SQLSubQuery subquery2 = new SQLSubQuery();
...
subquery1.union(subquery2.unique(...));

new JPAQuery(em).from(QContact.contact).where(QContact.contact.in(subquery1)).list(QContact.contact);

The query works (yay!), but it only includes the first sub-query, not the union of the two.  I'm guessing that I have to do something with what the union() method returns (SimpleExpression), but I'm not sure how to use it in the larger query...

**Comment by zamrokk** [comment]
it did it like this :

on the "where" you can do   myField.in(subquery1) or myfield.in(subquery2) 

kinda union
