### ISSUE TITLE
Expressions.predicate(Ops.AND, Predicate ... p) ignores predicates.

### ISSUE THREAD

**Issue by inspell** [querydsl/querydsl#1467]
Hello, 

I am not an expert in QueryDSL, I recently discovered it and I think it's great. I currently use it in my project. I think I hit a bug so I am tempted to share it. It could not be a bug at all but after I changed the code I used at first my problem disappeared.

So, I had the following code:

    List<Predicate> childrenPredicates = new ArrayList<>();
    for (Node child : node)   // a little bit of FIQL parsing here
    {
        Predicate childPredicate = child.accept(this, param);
        childrenPredicates.add(childPredicate);
    }
    
    // this is the problem line
    BooleanExpression and = Expressions.predicate(Ops.AND,
        childrenPredicates.toArray(new Predicate[childrenPredicates.size()]));

Basically, I put some predicates in a list and then I convert this list to an array and try to create an AND clause with Expressions.predicate(Ops.AND, Predicate ... p);

I noticed that when I have more than two predicates - I had three - the last one is not taken under consideration - I observed the Hibernate logs and the results returned from the query. When I hovered the 'and' expression with the mouse in eclipse the String representation of the 'and' expression didn't contain the last predicate - I noticed that the String representation is cached somewhere down the inheritance line, so may be this is the problem with the text representation. When I expanded the 'and' expression in the debugger (watch view / evaluate) I noticed that all of my three predicates were there in the args but the generated query didn't include the last predicate. So when I changed the code to:

    BooleanBuilder bb = new BooleanBuilder();
    for (Node child : node)
    {
        Predicate childPredicate = child.accept(this, param);
        childrenPredicates.add(childPredicate);
        
        bb.and(childPredicate);
    }
    Predicate and = bb.getValue();

the problem disappeared. Is this a bug? Can someone verify it, please?

**Comment by timowest** [comment]
It's not really a bug. AND is a binary operation and only the first two arguments are taken into account.

What you want to use is `Expressions.allOf(first, second, third, ...)`

**Comment by inspell** [comment]
I see. Thank you for your replay. But how can I get a BooleanExpression out of a Predicate?
`Expressions.allOf()` expects `BooleanExpression` objects but my methods return `Predicate` objects.

**Comment by timowest** [comment]
You can use `ExpressionUtils.allOf(first, second, ...)` for that.
