### ISSUE TITLE
Use JPASubQuery in JPAQuery.from()

### ISSUE THREAD

**Issue by renanleandrof** [querydsl/querydsl#1471]
Hello,

i have an SQL like:

#### Query 1:
```SQL
  SELECT
    t.name,
    sum(t.value)
  FROM
    myTable t
  WHERE 
    -- conditions...
  GROUP BY 
    t.name
  HAVING sum(t.value) >= 100
```
and i have:

#### Query 2:
```SQL
  select count(*) from (
   -- QUERY1
) as countQuery
```

And i'm trying to do it on QueryDSL.
I already have my Query 1 as an JPAQuery.
Now a need to use it as a subquery, so i'm trying to do something like:

```JAVA
JPASubQuery subQuery = new JPASubQuery(query1.getMetadata());
new JPAQuery().from(subquery).count();
```
But it's not possible to add a SubQuery in the FROM clause.

It would be a nice feature.

**Comment by timowest** [comment]
That's unfortunately not possible due to restrictions in JPQL. Even if we would allow it on the API level, the JPA engine couldn't execute such a query.

**Comment by renanleandrof** [comment]
Is it possible to transform an JPAQuery with Where, From, GroupBy etc etc clauses into a JPASubQuery?

**Comment by timowest** [comment]
You can transform a JPAQuery to a JPASubQuery like this

```java
new JPASubQuery(query.getMetadata().clone());
```

**Comment by pilkyoon** [comment]
@timowest not possible to add a SubQuery in the FROM cluase yet? (JPQL not support?)

**Comment by zhangzhongbin001** [comment]
@timowest how to add a SubQuery in the FROM cluase yet?

**Comment by Shredder121** [comment]
JPQL does *not* support that.

**Comment by renanleandrof** [comment]
An alternative is to use a JPASQLQuery and get the result (select) with a JPAentity mapping, like the docs say http://www.querydsl.com/static/querydsl/4.1.3/reference/html_single/#d0e431

**Comment by zhangzhongbin001** [comment]
@renanleandrof Can you give me an example？

**Comment by renanleandrof** [comment]
I just sent you the link to the example :rofl:

**Comment by zhangzhongbin001** [comment]
Thank U all

**Comment by wxiaohe** [comment]
JPASubQuery Can't cite

**Comment by wxiaohe** [comment]
> You can transform a JPAQuery to a JPASubQuery like this
> 
> ```java
> new JPASubQuery(query.getMetadata().clone());
> ```

JPASubQuery Can't cite

**Comment by jwgmeligmeyling** [comment]
In Querydsl 4 JPASubQuery was removed / hidden. You can since just use a new JPAQuery instance as subquery expression.
