### ISSUE TITLE
Wrong query is generated for concat statement

### ISSUE THREAD

**Issue by glau2** [querydsl/querydsl#1482]
Hi Team,

We have found there might be a bug when generating query using the concat() function:

Query: 
QUser quser = QUser.user;
List<User> userList = query.from(quser)	.where(
	(quser.firstName.concat(quser.lastName)).toLowerCase().contains(token)
).list(quser);

Result:
FROM org.sly.main.shared.data.user.User
WHERE this.firstName + this.lastName.toLowerCase().indexOf(a1) > -1
PARAMETERS java.lang.String a1

SQL:
SELECT `A0`.`KEY`,`A0`.`NAME`,`A0`.`VERSION`,`A0`.`DISCRIMINATOR` 
FROM `USER` `A0` 
WHERE (CONCAT(`A0`.`FIRSTNAME`,(CAST((LOCATE('peterchao',LOWER(`A0`.`LASTNAME`)) - 1) AS CHAR(4000))))) > -1

We are actually expecting
FROM org.sly.main.shared.data.user.User
WHERE (this.firstName + this.lastName).toLowerCase().indexOf(a1) > -1
PARAMETERS java.lang.String a1

Please let us know whether this is a valid bugs

**Comment by timowest** [comment]
Thanks for the bug report. I created a PR for it.
