### ISSUE TITLE
SQL : Stored procedure support

### ISSUE THREAD

**Issue by timowest** [querydsl/querydsl#15]
Stored procedure support

Pseudocode

```
CREATE OR REPLACE PROCEDURE order_update (id INTEGER, customer_id INTEGER, amount OUT DECIMAL);

OrderUpdate orderUpdate = new OrderUpdate(configuration, connection);
// OrderUpdate is generated based on a stored procedure with the same name
orderUpdate.setId(123);
orderUpdate.setCustomerId(7849320);
orderUpdate.execute();
Double amount = orderUpdate.getAmount();
```

**Comment by davidkarlsen** [comment]
Would be very nice to see this features - and it's a feature JOOQ has: http://www.jooq.org/doc/3.2/manual/sql-execution/stored-procedures/

**Comment by fasfsfgs** [comment]
I just used stored procedure support for JPA 2.1 and it did a good work.

https://docs.oracle.com/javaee/7/api/javax/persistence/NamedStoredProcedureQuery.html
https://javaee-spec.java.net/nonav/javadocs/javax/persistence/StoredProcedureQuery.html
