### ISSUE TITLE
java.lang.ClassNotFoundException: com.mysema.query.jpa.JPQLQuery

### ISSUE THREAD

**Issue by richardkabiling** [querydsl/querydsl#1508]
I'm getting the following error when running querydsl with Spring Boot. 

    Caused by: java.lang.ClassNotFoundException: com.mysema.query.jpa.JPQLQuery
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 80 more

``build.gradle``

    buildscript {
        repositories {
            mavenCentral()
            jcenter()
        }
        dependencies {
            classpath "org.springframework.boot:spring-boot-gradle-plugin:1.2.5.RELEASE"
            classpath "com.ewerk.gradle.plugins:querydsl-plugin:1.0.3"
        }
    }
    
    apply plugin: 'java'
    apply plugin: 'eclipse'
    apply plugin: 'idea'
    apply plugin: 'spring-boot'
    apply plugin: "com.ewerk.gradle.plugins.querydsl"
    
    jar {
        baseName = 'spring-wave-services'
        version =  '0.1.0'
    }
    
    sourceCompatibility = 1.8
    targetCompatibility = 1.8
    
    repositories {
        mavenCentral()
    }
    
    dependencies {
        compile "org.springframework.boot:spring-boot-starter-web"
        compile "org.springframework.boot:spring-boot-starter-actuator"
        compile "org.springframework.boot:spring-boot-starter-data-jpa"
        testCompile "org.springframework.boot:spring-boot-starter-test"
        testCompile "junit:junit"
        runtime "com.h2database:h2:1.4.188"
    }
    
    querydsl {
        library = "com.mysema.querydsl:querydsl-apt:2.9.0.FIXED"
    }
    
    task wrapper(type: Wrapper) {
        gradleVersion = '2.3'
    }

**Comment by johnktims** [comment]
You need to add `querydsl-jpa` as a dependency.

I'd also recommend using a newer version of querydsl if you can.
