### ISSUE TITLE
AntMetadataExporter documentation: numericMappings, typeMappings, customTypes not documented

### ISSUE THREAD

**Issue by agharta** [querydsl/querydsl#1510]
Hi all,

I've try to set numericMappings, typeMappings and customTypes options to AntMetadataExporter, without success.

In documentation is not clear how to do it.

Best regards,

Agharta

**Comment by timowest** [comment]
Those properties are currently not supported in AntMetadataExporter. Would you be interested to provide a PR that fixes it?
