### ISSUE TITLE
Supporting forShare() in AbstractSQLQuery

### ISSUE THREAD

**Issue by attila-kiss-it** [querydsl/querydsl#1511]
The issue is created based on topic "Row level read locks" (https://groups.google.com/forum/#!topic/querydsl/0G78HIIpdN0)

The solution for databases where share lock is not supported should be discussed:
- using forUpdate() by default
- the programmer can decide in a functional interface (e.g. throws an exception; falls back to forUpdate() or nothing based on SQLTemplate; etc.)
- etc.

We can create a pull request as soon as the decision is made.

**Comment by timowest** [comment]
Basically the forUpdate() logic can be copied for forShare():

AbstractSQLQuery:
```java
public Q forShare() {
    QueryFlag forUpdateFlag = configuration.getTemplates().getForShareFlag();
    return addFlag(forUpdateFlag);
}
```

In SQLTemplates subclasses forShareFlag can be replaced via this.setForShareFlag(...).

@attila-kiss-it Would you be interested to provide a PR?

**Comment by balazs-zsoldos** [comment]
_forShare_ can be supported only by three databases (MySQL, PostgreSQL, SQLServer). The question is, what should happen with other database instances? In case forShare is not supported, I think developers would want to use forUpdate instead (less concurrent, but better than nothing).

We thought of many solutions, but we do not know if any of them acceptable to you. I list a couple of ideas:

_Adding isForShareSupported() function to SQLTemplates or AbstractSQLQuery_

The developer could write the following code:

    if (sqlTemplates.isForShareSupported()) {
        query.forShare();
    } else {
        query.forUpdate();
    }

__Same as previous but sqlTemplates would return null for getForShareFlag() if it is not supported_

    if (sqlTemplates.getForShareFlag() != null) {
        query.forShare();
    } else {
        query.forUpdate();
    }

__Adding an additional boolean parameter for forShare() function__

    forShare(boolean fallbackToForUpdate);

If the parameter is false, an exception would be thrown.

__Adding a functional parameter for forShare()__

    forShare(Runnable fallbackAction);

and it could be used like this:

    query.forShare(() -> query.forUpdate());

@timowest  There are even more possibilities. It is hard to decide which is the best. Could you please advise? We will provide a PR based on your suggestion.

**Comment by Shredder121** [comment]
There are indeed a lot of possibilities, I at least want to share my thoughts on them.

>Adding an additional boolean parameter for forShare() function

To me this is the most obvious as an end user that there is a fallback, and conveying that message could be a good thing, but at least this option has it.

>Adding isForShareSupported() function to SQLTemplates or AbstractSQLQuery

If we however decide to do it transparently, I think this is easier to debug.

>Adding a functional parameter for forShare()

In my opinion, the functional parameter would be helpful if we move away from the older JDK versions, but I do get your point.

**Comment by timowest** [comment]
I'd prefer to keep the switch forUpdate/exception on the SQLTemplates layer.  The default would be to throw an exception if forShare is not supported.
