### ISSUE TITLE
oracle get sequence netval

### ISSUE THREAD

**Issue by ali-rezvani** [querydsl/querydsl#1515]
Hi timo.
I use queryDsl sql 3.6.6 in banking project and i want to mirate to 4.0.3 
I use this code for select nextval from oracle sequence 

``` 
return queryFactory.from().singleResult(SQLExpressions.nextval(Long.class,"CHK.SEQ_TB_STATUS_CHANGE"));

```
But in 4.0.3 exception throws in singleResult exprision (Can't resolve method singleResult(...) )

Thank you.

**Comment by timowest** [comment]
Is there an exception at runtime or doesn't it compile?

**Comment by timowest** [comment]
The following works

``` 
return queryFactory.select(SQLExpressions.nextval(Long.class,"CHK.SEQ_TB_STATUS_CHANGE")).fetchFirst();

```
