### ISSUE TITLE
Limit on JPAQuery does not have any effect

### ISSUE THREAD

**Issue by vguna** [querydsl/querydsl#1518]
Tried my first steps with querydsl 3.6.6 with an easy example:

```
JPAQuery query = new JPAQuery(entityManager);
query.from(QAddress.address);
		
JPQLQuery paginatedQuery = query.limit(25);
		
System.out.println(paginatedQuery);
System.out.println(paginatedQuery.count());
```

Output is:

```
select address
from Address address
801
```

Shouldn't it limit the query?

**Comment by timowest** [comment]
limit is turned into metadata in the JPA query and is not serialized into the JPQL query string. Also limit limits the result rows, not the rows that are inspected via count.
