### ISSUE TITLE
[3.6.4] Scala: com.mysema.query.scala.NumberExpression doesn't extend com.mysema.query.scala.ComparableExpressionBase

### ISSUE THREAD

**Issue by bouil** [querydsl/querydsl#1520]
In the Java API `com.mysema.query.types.expr.NumberExpression` extends `com.mysema.query.types.expr.ComparableExpressionBase`.

`com.mysema.query.scala.NumberExpression` has no common interface to threat it as a ComparableExpressionBase or , despite it looks like to have all the method required to be Comparable.

It prevent me to convert some Java code to Scala because I have a ComparableExpressionBase list used as a parameter to configure sorting on queries.

**Comment by bouil** [comment]
I've tried to make NumberExpression to extends ComparableExpressionBase 

```scala
trait NumberExpression[T <: Number with Comparable[_]] extends ComparableExpressionBase[T] 
```

but it cannot compile because `scala.Long` / `scala.Integer` doesn't implements the Comparable interface.

**Comment by bouil** [comment]
See http://stackoverflow.com/a/6806372/29106 : maybe something can be done with Ordering to achieve a comparable feature.

**Comment by bouil** [comment]
Something like that may do it: bouil/querydsl@675df6dd1753ae0a06ad0e9136f8600f047f69c9

However, the maven enforcer plugin complains for backward compatibility problem, but as it's an interface addition, it may be not a problem.

(But I get a lot of problems with generics trying to use that in my project, because Scala is more strict with generics parameters than java which just triggers warnings)

**Comment by timowest** [comment]
I don't think this can be fixed in a backwards compatible way
