### ISSUE TITLE
Code generation fails when using multiple processors and dependencies between entity types

### ISSUE THREAD

**Issue by jlsalmon** [querydsl/querydsl#1529]
I have a project where I am using querydsl for both MongoDB entities and JPA entities. One of my mongo entities contains a reference to one of my JPA entities.

I can get querydsl to generate sources for both types via Gradle, using the `-processor` argument to the apt compiler and giving two processor classes separated by a comma. The classes are generated correctly, but the build fails with the error `Attempt to recreate a file for type`.

I have created a minimal sample project that demonstrates the issue [here](https://github.com/jlsalmon/querydsl-multiple-processors). To reproduce, run `./gradlew build` and see the error.

Here's the error log:
```
:generateQueryDSL
Attempt to recreate a file for type test.QJpaEntity
Note: Running JPAAnnotationProcessor
Note: Serializing Entity types
Note: Generating test.QJpaEntity for [test.JpaEntity]
Note: Running MongoAnnotationProcessor
Note: Running MongoAnnotationProcessor
Note: Serializing Entity types
Note: Generating test.QMongoEntity for [test.MongoEntity]
Note: Serializing Embeddable types
Note: Generating test.QJpaEntity for [test.JpaEntity]
error: Attempt to recreate a file for type test.QJpaEntity
Note: Running JPAAnnotationProcessor
Note: Running MongoAnnotationProcessor
1 error
:generateQueryDSL FAILED
```

Is this a bug? I don't see any immediate reason why this shouldn't be possible. Thanks in advance.

P.S. Great work on querydsl, I love it!

**Comment by timowest** [comment]
Do you use different target folders?

**Comment by jlsalmon** [comment]
No, just a single one (src/generated/java).

**Comment by jlsalmon** [comment]
Sorry, src/main/generated

**Comment by timowest** [comment]
I'd just use different target folders. That way the generated sources are clearly separated.
APT indeed errors for file overwrite attempts.

**Comment by timowest** [comment]
Closing, since this is a constraint of the APT API.

**Comment by jlsalmon** [comment]
Could you perhaps provide an example of how to do this with APT? Using either Maven or Gradle.

**Comment by timowest** [comment]
You have just take an execution like this https://github.com/querydsl/querydsl/blob/QUERYDSL_4_0_4/querydsl-apt/pom.xml#L184-L200, duplicate it and customize the outputDirectory.
