### ISSUE TITLE
querydsl-sql-codegen - Allow separate destination folders for QTypes and Bean definition classes.

### ISSUE THREAD

**Issue by jjzazuet** [querydsl/querydsl#1531]
Hi.

Suppose I'd like to create reusable schema Bean objects to share across projects. However, some of these projects may use data access mechanisms other than QueryDSL, but would still use the generated beans as a shared artifact to exchange data in the same schema format. Therefore, they wouldn't necessarily need to bring in QueryDSL and the generated Q types as a project dependency.

For example:

`MetaDataExporter` allows me to configure two separate package level locations:

    org.groundhog.schema <-- My schema beans go here.
    org.groundhog.types <-- My Q types go here.

Ideally, `MetaDataExporter` would also allow me to specify separate target folders for the beans and the QTypes. For example, if I had the following project structure:

    groundhog
        groundhog-schema <-- Bean classes to share with other projects
        groundhog-sql <-- QueryDSL + Q types + query factories + custom schema config 

in Groovy, I could do this:

    MetaDataExporter mde = new MetaDataExporter(
        configuration: myOracleConfig, exportTables: true,
        packageName: 'org.groundhog.types',
        beanPackageName: 'org.groundhog.schema',
        targetBeansFolder: new File('./groundhog-schema/src/main/java'),
        targetTypesFolder: new File('./groundhog-sql/src/main/java'),
        schemaPattern: 'SOME_SCHEMA', tableNamePattern: 'SOME, TABLES',
        beanSerializer: new BeanSerializer(
            addFullConstructor: false, addToString: true, 
            printSupertype: false
        )
    )
    mde.export(c.metaData)

Thanks!

**Comment by leotu** [comment]
+1

**Comment by leotu** [comment]
+ MorphiaAnnotationProcessor (apt-maven-plugin) :-)
