### ISSUE TITLE
SimplePath for Comparable

### ISSUE THREAD

**Issue by gsmet** [querydsl/querydsl#1559]
Hi!

After upgrading to Java 8 and the latest 3.6.x of QueryDSL, I have a problem with the generated code. Instead of using a ComparablePath for a Comparable, it uses a SimplePath:

``` java
public final SimplePath<Comparable<?>> id = createSimple("id", Comparable.class);
```

The origin class is of the form:

``` java
public abstract class GenericEntity<K extends Comparable<K> & Serializable, E extends GenericEntity<K, ?>> implements Serializable, Comparable<E> {
    public abstract K getId();

    public abstract void setId(K id);
}
```

FWIW, I also have the issue with the 4.x. branch.
## 

Guillaume

**Comment by timowest** [comment]
What kind of source generation approach do you use? APT or GenericExporter?

**Comment by gsmet** [comment]
We use APT. The first thing which was weird is that I had to put Comparable first in the generic to make QueryDSL generate a Comparable binding. Before Java 8, Comparable was defined last and it worked like a charm.

**Comment by Shredder121** [comment]
I initially saw that Timo already answered, so I stopped typing, but I'll send it anyway.
We do have some support for Java 8, but the way of modeling types (`javax.lang.model.*`) changed a bit, which I think is the culprit.
Anyway, we'll look into this of course.

**Comment by timowest** [comment]
We handle Java 8 intersection types by only using the first type. Full support for intersection types is a bit harder, but maybe we could improve the bound selection?

**Comment by gsmet** [comment]
Well, it's not a problem to move the Comparable first. It doesn't explain the fact that QueryDSL chooses a SimplePath instead of a ComparablePath or am I missing something?

**Comment by gsmet** [comment]
Additional feedback. I thought about using @QueryType (I never had to use it before so it didn't ring a bell immediately):
```java
@QueryType(PropertyType.COMPARABLE)
public abstract K getId();
```
If Serializable is first in the intersection, I end up with the following generated code:
```java
public final ComparablePath<java.io.Serializable> id = createComparable("id", java.io.Serializable.class);
```
which doesn't compile.

I have something working with Comparable first in the intersection and an explicit @QueryType.

**Comment by timowest** [comment]
In other places of our code we have explicit declared to no handle Comparable as a ComparableExpression https://github.com/querydsl/querydsl/blob/master/querydsl-codegen/src/main/java/com/querydsl/codegen/TypeFactory.java#L192

Should we change that as well? That might be problematic concerning backwards compatibility.

**Comment by Shredder121** [comment]
> Should we change that as well? That might be problematic concerning backwards compatibility.

Does it generate better code?

Refreshing generated code requires recompilation, so the impact is not as big.
The backwards compatibility checklist by the JLS is about compatibility without recompilation, so binary compatibility.

As for user backwards compatibility, the operations are almost the same for `SimplePath` and `ComparablePath` right?
