### ISSUE TITLE
Code generation fails with the following error

### ISSUE THREAD

**Issue by pradhakrishnan** [querydsl/querydsl#1560]
I am getting compilation errors when generating the source code. 

Error:
 public final BooleanPath 8FRecord = createBoolean("8FRecord");

COMPILATION ERROR :Return type for the method is missing
	- Syntax error, insert ")" to complete ConstructorDeclaration
	- Syntax error on tokens, AnnotationName expected instead
	- Syntax error, insert "Identifier (" to complete 
	 ConstructorHeaderName

Can some one please help me to fix that.

**Comment by timowest** [comment]
Do you use Querydsl SQL?

**Comment by pradhakrishnan** [comment]
@timowest , I am using version 3.6.7

<dependency>
			<groupId>com.mysema.querydsl</groupId>
			<artifactId>querydsl-sql</artifactId>
			<version>3.6.7</version>
		</dependency>

**Comment by pradhakrishnan** [comment]
@timowest , If I change the field name to eightFRecord instead of 8FRecord then it works fine.

**Comment by johnktims** [comment]
Java doesn't allow you to start a variable name with an integer.

**Comment by jmvivo** [comment]
As @johnktims says: https://docs.oracle.com/javase/tutorial/java/nutsandbolts/variables.html#naming

**Comment by timowest** [comment]
@pradhakrishnan Could you post the sources of the generated class? I couldn't replicate the issue.

**Comment by pradhakrishnan** [comment]
@timowest , Here is my generated code and attached is a image.

```
import static com.mysema.query.types.PathMetadataFactory.*;

import com.mysema.query.types.path.*;

import com.mysema.query.types.PathMetadata;
import javax.annotation.Generated;
import com.mysema.query.types.Path;


/**
 * QRecordIndicators is a Querydsl query type for RecordIndicators
 */
@Generated("com.mysema.query.codegen.EmbeddableSerializer")
public class QRecordIndicators extends BeanPath<RecordIndicators> {

    private static final long serialVersionUID = 463559554L;

    public static final QRecordIndicators RecordIndicators = new QRecordIndicators("RecordIndicators");

    public final BooleanPath 8Ffund = createBoolean("8Ffund");

    public final BooleanPath cat = createBoolean("cat");

    public final BooleanPath DirectorRequest = createBoolean("DirectorRequest");

    public final BooleanPath is8Ffund = createBoolean("is8Ffund");

    public final BooleanPath isCat = createBoolean("isCat");

    public final BooleanPath isDirectorRequest = createBoolean("isDirectorRequest");

    public QRecordIndicators(String variable) {
        super(RecordIndicators.class, forVariable(variable));
    }

    public QRecordIndicators(Path<? extends RecordIndicators> path) {
        super(path.getType(), path.getMetadata());
    }

    public QRecordIndicators(PathMetadata<?> metadata) {
        super(RecordIndicators.class, metadata);
    }

}

Image : 
![dsl_error](https://cloud.githubusercontent.com/assets/1951508/9940158/0e6e2dee-5d3c-11e5-9589-e5ee6bed4069.JPG)

```

**Comment by timowest** [comment]
Ok, that looks weird. How does RecordIndicators look like?

**Comment by pradhakrishnan** [comment]
@timowest , PFA I did some work around to make it works. 
![querydsl](https://cloud.githubusercontent.com/assets/1951508/9942564/c65e07f0-5d49-11e5-84e3-883264644bc2.JPG)

**Comment by timowest** [comment]
Your accessor usage is a little inconsistent. IsCat/setCat or isIsCat/setIsCat would be consistent.

**Comment by pradhakrishnan** [comment]
Thanks @timowest , This is really old code, don't know who wrote this.

**Comment by timowest** [comment]
Ok, fair enough ;) This issue will be fixed in the next release.

**Comment by pradhakrishnan** [comment]
Cool thanks @timowest .
