### ISSUE TITLE
[querydsl-sql 4.0.4] - selectDistinct does not print schema name in custom configuration

### ISSUE THREAD

**Issue by jjzazuet** [querydsl/querydsl#1570]
Hi. If I configure an `SQLFactory` with an instance of `OracleTemplates`, where `printSchema()` is set to `true`, a query similar to:

    selectDistinct(mm).where(b).fetch()

reads:

    select <COLUMN_SET> from dual

Which leads to an Oracle error:

    ORA-00904: "TABLE_NAME"."TABLE_COLUMN": invalid identifier

 However, a query similar to:

    selectFrom(m).where(b).distinct().fetch() 

correctly reads:

    select <COLUMN_SET> from <TABLE_NAME>

This leads me to believe that, when the configuration object is set to print the schema name, `selectFrom().distinct()` works, but `selectDistinct()` does not. Am I doing something wrong? Thanks!

**Comment by timowest** [comment]
There might be some confusion here concerning the semantics of the methods.

`selectFrom(e)` is short for `select(e).from(e)`

`selectDistinct(e)` is short for `select(e).distinct()`

Does that help?

**Comment by jjzazuet** [comment]
Ah. My bad. So the latter statement still needs a `from()` call. From an end user's perspective, this is a fundamental change from QueryDSL `3.X.X`. I think it would be useful to document a few more basic examples in the reference docs. Thanks!
