### ISSUE TITLE
Path visitor doesn't work for MongoDB queries when having subtype

### ISSUE THREAD

**Issue by ulisesbocchio** [querydsl/querydsl#1577]
Consider the classes:

```
@Entity
class A {
    @Embedded
    private B b;
}

abstract class B {
}

class B1 extends B {
    private String name;
}

class B2 extends B {
    private String key;
}

```
When I generate query DSL classes for this hierarchy I'm able to write expressions like this:
`QA.a.b.as(QB1.class).name.eq("someName")` or `QA.a.b.as(QB2.class).key.eq("someKey")`

but the paths generated by MongodbSerializer for this expressions are wrong. In version 3.6.7 I just get "name" and "key", when they should be "b.name" and "b.key" respectively.

I also tried this in version 3.6.5 after I saw this issue: https://github.com/querydsl/querydsl/issues/1427 but the results are weird, I get: "b.a.b.name"

on method `String visit(Path<?> expr, Void context)` of `MongodbSerializer` I can see how the recursion is avoided if the path type is DELEGATE which is not the case in this scenario, but even if the recursion was reached I'm not sure it'd still generate the right path. 

Any help would be greatly appreciated.

**Comment by timowest** [comment]
Thanks for the bug report! Fixed in the linked PR.

**Comment by ulisesbocchio** [comment]
Thanks! when is the next release?

**Comment by johnktims** [comment]
September 29th

**Comment by ulisesbocchio** [comment]
Forgot to ask, is there gonna be a 3x release? Or is it going to version 4x? I'm using QueryDSL with Spring Data MongoDB and they're not on the 4x version yet

**Comment by johnktims** [comment]
Hi, @ulisesbocchio. Thanks for pointing out that this feature hadn't been backported.

This improvement will be released for 3.x and 4.x on September 29th.
