### ISSUE TITLE
JPA - Generate TypeSafe alias from QClass properties

### ISSUE THREAD

**Issue by darkbauer** [querydsl/querydsl#1580]
Hello QueryDsl team,

I would like to put a request for you, about aliasing. 

For example let's say I have this class: 
```java
public Class Customer {
    private Integer amount;

    @Transient
    @QueryType(PropertyType.SIMPLE)
    private Integer irr;
}
```
```java
QCustomer customer = new QCustomer("customer");

queryFactory()
.select(
   Projections.bean(Customer.class, customer.amount.as("irr"))
.from(customer)
.fetch();
```
This query works, and put amount value in "irr" property.

But my problem is that this aliasing is not typesafe : If I rename "irr" property in Customer class, I will not have any compilation issue.

So I tried to do :  
```java
queryFactory()
.select(
   Projections.bean(Customer.class, customer.amount.as(customer.irr))
.from(customer)
.fetch();
```
But this doesn't work, which is a problem. 

Is there a way to provide a typesafe way to name an alias ? It's very important, especially when projecting query results into a transient property.

Thanks !

**Comment by timowest** [comment]
Here is a related issue https://github.com/querydsl/querydsl/issues/1572.

Maybe we can just fix the aliasing behaviour to make your second example work?

**Comment by darkbauer** [comment]
Hello timo,

Yes, I think that if you can fix the aliasing behaviour to work like the second example, it would be really great and useful !

Thanks again for your quick answer.
