### ISSUE TITLE
Using SQLQueryFactory's query(), subqueries are assigned connections and never close them

### ISSUE THREAD

**Issue by robertandrewbain** [querydsl/querydsl#1581]
When using `SQLQueryFactory`'s `query()` method to create a subquery, each subquery is assigned a new connection, as the connection object is assigned when `query()` is called. Furthmore, using a `SQLCloseListener` does not close subqueries, I presume because a terminator E.G. `.list()` etc. has not been called on it. This caused my system test environment to grind to a halt when the querydsl 4 upgrade was pushed up.

After realising what was happening, I discovered `SQLExpressions.select` which will "Create a new detached SQLQuery instance with the given projection". After some debugging I realised this creates a `SQLQuery` instance with a null connection - so far so good. I assume detached means not attached to a connection. If so `SQLQueryFactory`'s  `public <T> SQLQuery<T> selectFrom(RelationalPath<T> expr)` method's documentation is wrong.

So for me, the issue here is that if you're using a `SQLQueryFactory`, creating a subquery using `query()` looks sensible and will work, but will swallow a connection. It feels like a connection should not be getting assigned on calling `query()`, surely the connection is not required until calling a terminator?

Secondly, `SQLCloseListener ` should close these connections.

**Comment by timowest** [comment]
Subqueries should be created via SQLExpressions instead http://www.querydsl.com/static/querydsl/4.0.4/apidocs/com/querydsl/sql/SQLExpressions.html

We could consider injecting a connection provider instead of a connection, that might just complicate the signature because of backwards compatibility.

**Comment by robertandrewbain** [comment]
@timowest as I mentioned in the issue, I did find that in the end but I can see many more falling into the same trap as I did, given both the Java and resultant SQL compile. Would it be an idea to perhaps mark attached connections and throw an `Exception` when they appear in a subquery? This would prevent others from going through the pain my team have had this afternoon.

**Comment by timowest** [comment]
> Would it be an idea to perhaps mark attached connections and throw an Exception when they appear in a subquery? 

What do you mean by that? When do we decide if a query is a subquery or not?

We could assert at rendering time that used subqueries are detached, how does that sound?

**Comment by robertandrewbain** [comment]
@timowest that's exactly along the lines of what I was thinking. When you say used subqueries, I suppose we'd want to handle unused subqueries too, although obviously at the rendering stage that's not going to fly.

**Comment by robertandrewbain** [comment]
The way things are now, if someone accidentally slips a `query()` instead of a 'new SQLQuery()' or `SQLExpressions.select` into a subquery on a server with pooled connections, their app will grind to a halt, which I don't think is OK, given it all looks perfectly reasonable.

**Comment by robertandrewbain** [comment]
Could you perhaps use detached queries by default and only bind a connection to them when collecting the results?

**Comment by timowest** [comment]
> Why not just grab one when executing the SQL statement?

That was suggested above, but we still need to provide the old constructors for backwards compatibility. I think the `Provider<Connection>` approach could work.

**Comment by robertandrewbain** [comment]
I see and if I follow, we could provide a new constructor `public SQLQueryFactory(Provider<Connection> provider, Configuration configuration)`?

**Comment by robertandrewbain** [comment]
I still feel that the fact that a developer can use a database connection that can never be closed through reasonable means, and that querydsl will compile it, is a bad thing. I can't think of a good way around it without an API break though. I think this is a teething problem from moving from the notion of a subquery in version 3, to the idea that everything is just a query. 

How about in the mean time, we put some explicit Javadoc around `SQLQueryFactory`'s `query()` method, and any others I'm unaware of, explaining that it's only to be used for top level queries and link to API functionality that will help the developer know that they should be using detached queries, and point them to the relevant classes?
