### ISSUE TITLE
[question] How to ignore accents when querying string paths?

### ISSUE THREAD

**Issue by jorool** [querydsl/querydsl#1593]
There is some way to ignore accents on queries? 

Example: I have a person named as "José" in my database. I want to my query do return that person accepting "jose" or "josé" as parameter for the name:
```
JPQLQuery query = new JPAQuery(entityManager);
query.from(person);
query.where(person.name.likeIgnoreAccents("jose"));
```
How can I do this?
Thanks.

**Comment by johnktims** [comment]
Hi, @jorool.

We prefer to use GitHub issues for reporting bugs. Please ask questions like this on StackOverflow or in the Google group.

**Comment by jorool** [comment]
Sorry, @johnktims !
Done.
Thanks.

**Comment by neophd** [comment]
Someone got do like Ignore Accents ?
