### ISSUE TITLE
DefaultMapper should return maps with predictable order

### ISSUE THREAD

**Issue by elser** [querydsl/querydsl#1594]
I've came accross this issue while writing unit tests with asserts on SQL query strings. I've noticed that between multiple runs of the same test, the order of fields in generated SQLs varied. This rendered my tests flaky. 
Also, because of this, we could possibly be expecting different SQL queries for the same lists of fields produced on different JVMs in the production environment. This in turn would decrease database's ability to skip parsing similar statements.
The quickest fix would be to replace HashMap with a LinkedHashMap in DefaultMapper.

Thanks in advance

**Comment by timowest** [comment]
@elser Would you have time to write a PR for this?

**Comment by elser** [comment]
Sure, will do!

**Comment by dagguh** [comment]
Thanks! :)
