### ISSUE TITLE
 Code generator

### ISSUE THREAD

**Issue by ali-rezvani** [querydsl/querydsl#1612]
Hi
I am using version 4.0.5 for sql queries.
I have a number(5,2) type in oracle,When I generate code with MetaDataExporte this column convert to BigDecimal

**Comment by timowest** [comment]
Which type do you want?

**Comment by ali-rezvani** [comment]
http://www.querydsl.com/static/querydsl/4.0.5/reference/html/ch02s03.html#d0e722
In this url you have said it must convert to Double type

**Comment by timowest** [comment]
That mapping is outdated, we will update it soon. Sorry for the inconvenience. With a numeric mapping you can fix it

```
<numericMappings>
  <numericMapping>
    <total>5</total>
    <decimal>2</decimal>
    <javaType>java.lang.Decimal</javaType>
  </numericMapping>
</numericMappings>
```

**Comment by ali-rezvani** [comment]
Thank you timo.
