### ISSUE TITLE
Cannot use QueryDslJdbcTemplate.update() with generated Q classes

### ISSUE THREAD

**Issue by inspell** [querydsl/querydsl#1613]
Hi,

I am struggling with pretty annoying issue. I am trying to use the QueryDslJdbcTemplate.update method to perform an update by specified Predicate but I am not able to call the method with the generated Q classes because my generated classes extend EntityPathBase but the update method requires RelationalPath. Is there a way to generate the classes using RelationalPath as base class?

I tried to create the RelationalPath manually, for example:
```
   RelationalPath relPath = new RelationalPathBase<UserEntityImpl>(
                UserEntityImpl.class, "userEntityImpl", "dbo",  "user");
```

but after that I get an error because the  query is not valid. I get the following error:
```
   org.springframework.jdbc.BadSqlGrammarException: SQLUpdateClause; bad SQL grammar [update user
set tag = ?
where userEntityImpl.id = ?];
```
It would have worked if the where clause was  "where id = ?".
If I remove the "userEntityImpl" from the RelationalPathBase constructor and instead pass "" I then get an error
   IllegalArgumentException: Undeclared path 'userEntityImpl'. Add this path as a source to the query to be able to reference it.

If I find a workaround for this I am pretty sure I am going to face issues later when I try to do more complex updates. What is the correct way to get this RelationalPath object that I need to pass to the update method of the QueryDslJdbcTemplate?

This example http://docs.spring.io/spring-data/jdbc/docs/current/reference/html/core.querydsl.html  (section 2.5 Updates) is using the generated Q classes to invoke the update() method but they probably extend from RelationalPathBase not from EntityPathBase as in my case.
How can I fix my generation configuration?
I use com.mysema.maven apt-maven-plugin to generate the Q classes with this processor com.mysema.query.apt.jpa.JPAAnnotationProcessor.

**Comment by timowest** [comment]
You are mixing JPA and JDBC. Here are the instructions for Querydsl SQL code generation http://www.querydsl.com/static/querydsl/4.0.4/reference/html_single/#sql_integration

JPAAnnotationProcessor is part of Querydsl JPA and shouldn't be used with QuerydslJdbcTemplate.
