### ISSUE TITLE
Missing parentheses for in-Statement

### ISSUE THREAD

**Issue by AlexKolesnik** [querydsl/querydsl#1615]
I have a really complicated query which works under many circumstances but sometimes does not. It seems that sometimes QueryDsl generates a syntactically incorrect hql query:

In the following generated hql I miss the opening parenthesis in front of ":x5_0_, :x5_1_)"

Caused by: org.hibernate.hql.internal.ast.QuerySyntaxException: unexpected token: , near line 5, column 130 [select rohrnetzObjekt
from de.bwb.bim.domainmodel.rohrnetzobjekte.RohrnetzObjekt rohrnetzObjekt
where (type(rohrnetzObjekt) = ?1 or type(rohrnetzObjekt) = ?2) and rohrnetzObjekt.rbStelle in (:x3_0_, :x3_1_, :x3_2_, :x3_3_, :x3_4_) and (rohrnetzObjekt.id in (select schieber.id
from de.bwb.bim.domainmodel.rohrnetzobjekte.armaturen.Schieber schieber
where schieber.zonentrennArmatur = ?4 and schieber.betriebsdatenSchieber.betriebsstellungsdatenArmatur.betriebsstellung in :x5_0_, :x5_1_) or rohrnetzObjekt.id in (select klappe.id
from de.bwb.bim.domainmodel.rohrnetzobjekte.armaturen.Klappe klappe
where klappe.zonentrennArmatur = ?4 and klappe.betriebsdatenKlappe.betriebsstellungsdatenArmatur.betriebsstellung in :x5_0_, :x5_1_))
order by rohrnetzObjekt.id asc]

**Comment by Shredder121** [comment]
Hi Alex, could you post the Querydsl query?

**Comment by AlexKolesnik** [comment]
The predicate whose transformation is wrong is this:
        
        public BooleanExpression armaturMitBetriebsstellung(QRohrnetzObjekt r, boolean zonentrennArmatur, List<Betriebsstellung> betriebsstellungen) {
    
            ListSubQuery<Integer> schieberIds = schieberMitBetriebsstellung(zonentrennArmatur, betriebsstellungen);
            
            ListSubQuery<Integer> klappenIds = klappeMitBetriebsstellung(zonentrennArmatur, betriebsstellungen);
            
            return r.id.in(schieberIds).or(r.id.in(klappenIds));
        }
    
        private ListSubQuery<Integer> schieberMitBetriebsstellung(boolean zonentrennArmatur,
                List<Betriebsstellung> betriebsstellungen) {
            QSchieber s = QSchieber.schieber;
            ListSubQuery<Integer> schieber = new JPASubQuery()
                    .from(s)
                    .where(
                            zonentrennArmatur ? s.zonentrennArmatur.eq(true) : s.zonentrennArmatur.eq(false).or(s.zonentrennArmatur.isNull()), 
                            q.in(s.betriebsdatenSchieber().betriebsstellungsdatenArmatur().betriebsstellung(), betriebsstellungen))
                    .list(s.id);
            return schieber;
        }
    
        private ListSubQuery<Integer> klappeMitBetriebsstellung(boolean zonentrennArmatur,
                List<Betriebsstellung> betriebsstellungen) {
            QKlappe k = QKlappe.klappe;
            ListSubQuery<Integer> klappen = new JPASubQuery()
                    .from(k)
                    .where(
                            k.zonentrennArmatur.eq(zonentrennArmatur), 
                            q.in(k.betriebsdatenKlappe().betriebsstellungsdatenArmatur().betriebsstellung(), betriebsstellungen))
    
                    .list(k.id);
            return klappen;
        }

with q.in(..)   just checking if there are entries:
    
       public <T> Predicate in(SimpleExpression<T> path, Collection<T> collection) {
    
              if (collection == null || collection.isEmpty()) {
                  return null;
              } else {
    
                  return path.in(collection);
              }
    
          }

This armaturMitBetriebsstellung() predicate seems to work for a single value inside the betriebsstellungen List,  since that will be translated to an equals expression by QueryDsl.

**Comment by AlexKolesnik** [comment]
The query is constructed with

        return new JPAQuery(entityManager, JPQLTemplates.DEFAULT)
                .from(r)
                .where(p.fuerRoSucheingabe(r, sucheingabe, stammdatenService)

        );

**Comment by AlexKolesnik** [comment]
Oh, I just changed the construction to 

        return new JPAQuery(entityManager)        

and it works now. 

Apologies for any inconvenienced caused...

**Comment by AlexKolesnik** [comment]
I am sorry. That was a stupid mistake.

**Comment by Shredder121** [comment]
That's okay, glad that you got it figured out.
