### ISSUE TITLE
Cast in order by

### ISSUE THREAD

**Issue by igler** [querydsl/querydsl#1618]
I am trying to achieve a cast in the orderBy expression, so the resulting MySQL query will look like:
<code>SELECT * FROM ... ORDER BY cast(number as unsigned);</code>

<code>number</code> is a String field/column. The order Expression I currently use is:
<pre><code>JPQLQuery query = from(qLocation);

if (pageable.getSort() != null) for (Sort.Order o : pageable.getSort()) {
	PathBuilder orderByExpression = new PathBuilder(Location.class, "location");
			
	query.orderBy(
			new OrderSpecifier(
					o.isAscending() ? com.mysema.query.types.Order.ASC : com.mysema.query.types.Order.DESC,
					orderByExpression.get(o.getProperty())));
}
</code></pre>

**Comment by timowest** [comment]
Have you tied `expr.castToNum(Integer.class)`?

**Comment by igler** [comment]
Do you mean sth. like <code>orderByExpression.getString(o.getProperty()).castToNum(Integer.TYPE)</code> inside the <code>OrderSpecifier</code>?

**Comment by timowest** [comment]
yes, but `Integer.class` instead of `Integer.TYPE`.

**Comment by igler** [comment]
That's it. Many thanx.
