### ISSUE TITLE
JPA - Invalid Path with inheritance and @PrimaryKeyJoinColumn (JOIN strategy)

### ISSUE THREAD

**Issue by darkbauer** [querydsl/querydsl#1634]
Hello QueryDSL,

I have an issue on JPA, linked, I suppose, to the inheritance strategy of my class.

Let's suppose we have this class : 

```java
@Entity
public class Company {

      @Id
      @Column("COMPANY_ID")
     private Long id;

     ...
}
```
I also have a subclass that extends the first class. I'm on a JOIN mapped strategy.

```java
@Entity
@PrimaryKeyJoinColumn(name = "SUB_COMPANY_ID", referencedColumnName = "COMPANY_ID")
public class SubCompany {

      ...
}
```
Finally, I have another class with a list of SubCompany.

```java
@Entity
public class Item {
    @OneToMany
    private List<SubCompany> subCompanies;
}
```
When I'm doing this query in QueryDSL

```java

QItem item = QItem.item;
QSubCompany subCompany = QSubCompany.subCompany;

queryFactory()
.selectFrom(item)
.join(item.subCompanies, subCompany)
.where(subCompany.id.eq(123L))
.fetch();
```
the generated request in wrong and the request failed because the where is generated like 

```sql
SELECT ... FROM item JOIN sub_company WHERE sub_company.company_id = ?
```
instead of 
```sql
SELECT ... FROM item JOIN sub_company WHERE sub_company.sub_company_id = ?
```

So, the Id redefinition specified in the @PrimaryKeyJoinColumn of SubCompany class is not "seen" by QueryDSL.

To finish, I use the latest (4.0.6) version of QueryDSL.

Thanks in advance for your answer and continue your good job.

**Comment by darkbauer** [comment]
After further work on it, this is not a bug, but a mistake by me on the @ToMany link.

Sorry !

**Comment by Shredder121** [comment]
Glad that it is resolved. No problem.
On more note, querydsl only renders the JPQL, that snippet doesn't look like something we render, so it's the JPA provider's output.
