### ISSUE TITLE
QueryDSL's constructor uses a parameter instead of a constant

### ISSUE THREAD

**Issue by OzoneGrif** [querydsl/querydsl#1643]
Hello there. I asked this question on Stackoverflow and still have no answer :

http://stackoverflow.com/questions/33547221/have-querydsls-constructor-use-a-constant-instead-of-a-parameter

I use QueryDSL to build a query. The result has to be injected inside an object. The first column is the groupBy, the second is the value, and the third is a constant.

The constant is a problem because QueryDSL wants to make it a parameter, which leads to this error from Hibernate :

    org.hibernate.QueryException: 
      Parameters are only supported in SELECT clauses when used as part of a INSERT INTO DML statement 
      [select event.datetime, count(event), ?1]

The "?1" above should be directly a constant string "TOTAL".

Here is my code :

    final Expression<String> TOTAL = Expressions.constant("total");
    final StringExpression date = Expressions.stringTemplate("DATE_FORMAT({0},'%Y-%m-%d')", event.datetime);
    
    query.select(Projections.constructor(Stat2DGraphDto.class, date, event.count(), TOTAL))
    query.from(event).groupBy(date);
    query.fetch();

If I remove TOTAL from the constructor, it works as intended, but I need this constant to prepare an UNION later.

Can I force QueryDSL to send the String as-this?

**Comment by timowest** [comment]
a String typed constant is the same as a literal. Serialized into the query it would be `select event.datetime, count(event), 'total'`

I assume that you need total as a path, so `Expressions.path("total")` should be what you need.

**Comment by timowest** [comment]
Nevertheless there seems be also a bug in the parameter handling, we'll investigate.

**Comment by timowest** [comment]
The other issue is already known https://github.com/querydsl/querydsl/issues/290

**Comment by OzoneGrif** [comment]
Thanks lot for this answer Timowest.
I tried used Expressions.stringPath("total") but this gives an error as well : 
```
java.lang.IllegalStateException: No data type for node: org.hibernate.hql.internal.ast.tree.IdentNode 
 \-[IDENT] IdentNode: 'total' {originalText=total}
	at org.hibernate.hql.internal.ast.tree.SelectClause.initializeExplicitSelectClause(SelectClause.java:174)
```
After a lots of fidgeting, we found this way to make it work. It's not clean, but the test turns green :
```
Expressions.stringTemplate("'total'")
```
I have the feeling it's not a safe solution on the long run, though.

**Comment by timowest** [comment]
As the issue here is the same as in #290 I am closing this in favor of the older issue.
