### ISSUE TITLE
Collections, @QueryDelegate and StringExpression

### ISSUE THREAD

**Issue by diamss** [querydsl/querydsl#1649]
Imagine you have a query delegate on type String :

public class LangExtensions {

	public static final String WILDCARD_TEMPLATE = "%{0}%";

	@QueryDelegate(String.class)
	public static BooleanExpression ilike(final StringPath path, final String match) {

		return path.upper().like(toUpper(match));
	}

	private static StringExpression toUpper(final String string) {

		final StringExpression upper = Expressions.stringTemplate(WILDCARD_TEMPLATE, string.trim()).upper();

		return upper;
	}
}

When you try this :

final CollQuery<A> query = new CollQuery<A>();
query.from(QA, list).where(QA.name.ilike("xo"));
final List<A> resuts = query.fetch();

The result is a compilation error due to the a1 variable between '%' :

    try {
        if (com.querydsl.collections.CollQueryFunctions.like(a.getName().toUpperCase(),%a1%.toUpperCase())) {
            rv.add(a);
        }
    } catch (NullPointerException npe) { }

**Comment by Shredder121** [comment]
Templates will be inserted in the query as-is as you can see.
Does `\"%{0}%\"` work for you?

**Comment by diamss** [comment]
It works like this :

	@QueryDelegate(String.class)
	public static BooleanExpression ilike(final StringPath path, final String match) {

		return path.upper().like(match.trim().toUpperCase());
	}

But I think it would be great to replace %a1% by "%a1%" in the code generator.

**Comment by Shredder121** [comment]
I mean that the template is not ours, so we can not assume that we have to escape anything.
We only know that it's a string-typed 'something'.

In order for your template to work, adjust it to this:
```java
public static final String WILDCARD_TEMPLATE = "\"%{0}%\"";
```

Does that work for you?

**Comment by diamss** [comment]
Great, it works like this. Thanks

**Comment by diamss** [comment]
It works with collections but not with JPA because JPA use simple-quote character. I think the generator for collections must be changed to add double-quotes for strings.

This code does work for collections but does not for JPA :

public class LangExtensions {

	private static final String WILDCARD_END = "%\"";
	private static final String WILDCARD_START = "\"%";

	@QueryDelegate(String.class)
	public static BooleanExpression ilike(final StringPath path, final String match) {

		final QString string = new QString(WILDCARD_START.concat(match.trim()).concat(WILDCARD_END));

		return path.upper().like(string.toUpperCase());
	}
}

**Comment by timowest** [comment]
Did you try "{%0%}" as the template? This will do the conversion in a different way.

**Comment by diamss** [comment]
It works in both cases, thanks
