### ISSUE TITLE
Codegen : Ability to configure useGetters/useFields

### ISSUE THREAD

**Issue by vanackej** [querydsl/querydsl#1650]
By default, fields and getters are analyzed during code generation, but I need fields only generation. I found an option for that in `DefaultConfiguration`,  but there is no way to set it using maven plugin. I also didn't find a workaround for now.

**Comment by Shredder121** [comment]
Which Querydsl version are you running, which Querydsl project do you use?

**Comment by vanackej** [comment]
I'm using latest QueryDSL version (3.6.9) and JPA module (with JPAAnnotationProcessor and generic QuerydslAnnotationProcessor for custom use of generated model)

**Comment by Shredder121** [comment]
JPA has an annotation specifically for labeling which access type must be used:
https://docs.oracle.com/javaee/7/api/javax/persistence/Access.html

As for the maven plugin, do you mean the querydsl-maven-plugin or the apt-maven-plugin?

**Comment by vanackej** [comment]
Thanks, but in my case the issue is on non JPA classes using `QuerydslAnnotationProcessor`

I'm using the apt-maven-plugin. By the way I don't really get the distinction and use case for both plugins.

**Comment by Shredder121** [comment]
I was just making sure, since you only mentioned 'maven plugin'.

**Comment by Shredder121** [comment]
There will now be a way to configure the `useFields` and `useGetters` properties by supplying it to the `<options>` element in the apt-maven-plugin.

**Comment by vanackej** [comment]
Awesome, that was quick ! Thanks
