### ISSUE TITLE
Take AttributeConverters into account in JPA native queries

### ISSUE THREAD

**Issue by schragmanuel** [querydsl/querydsl#1660]
This happens in Version 3.6.9:

I use JPA attribute converters (javax.persistence.AttributeConverter) in my entities. They work perfectly with JPAQuery. Now I have a use case where I can't use JPAQuery but have to use JPA**SQL**Query. When I add a constraint like this

```
query.where(qEntity.source.in(errorSources));
```

the attribute converter is not taken into account. It seems like _convertToDatabaseColumn_ is never called. When retrieving the result set, convertToEntityAttribute is called though.

```
@Converter(autoApply = true)
public class ErrorSourceConverter implements AttributeConverter<ErrorSource, String> {

@Override
public String convertToDatabaseColumn(ErrorSource attribute) {...}
@Override
public ErrorSource convertToEntityAttribute(String dbData) {...}
}
```

In this example, _ErrorSource_ is an Enum which needs to be converted to a String representation for the database.

**Comment by aniketkalamkar** [comment]
Is there any solution on this ? i am also facing similar issue

**Comment by anstjaos** [comment]
I'm using 4.2.1 version. I also experienced the problem, but I solved it. 
If you defined an enum type within an entity, create another entity and defined the column as an Integer type, not enum type.
then works!

-  enum type within an entity

```
public class AnotherEntity {
...

    // Not enum
    @Column(name = "column")
    private Integer errorSource;
}
```

```
@Getter
public enum ErrorSource {
    ERROR(0),
    ...

    private int errorCode;
    ErrorSource(int errorCode) { this.errorCode = errorCode; }
}
```
```
query.where(qEntity.errorSource.in(ErrorSource.ERROR.getErrorCode());
```
