### ISSUE TITLE
Wrong serialization of modulo operator with JDOQL

### ISSUE THREAD

**Issue by RodrigoQuesadaDev** [querydsl/querydsl#1665]
Hi, I just found that queries that use the modulo operator are serialized wrongly for JDOQL and the reason is the corresponding template pattern is incorrectly overridden in JavaTemplates class (https://github.com/querydsl/querydsl/blob/master/querydsl-core/src/main/java/com/querydsl/core/types/JavaTemplates.java):

    add(Ops.MOD, "{0} % {0}"); 

I could gladly submit a PR for this—apparently—easy to fix issue but as I'm not really familiarized with the code I'm not sure what the reason for that override might be (perhaps instead of changing it, it should be removed from that class? the pattern found on the base class is the same :) ).

**Comment by timowest** [comment]
Thanks for the bug report! Fixed via the linked PR.
