### ISSUE TITLE
null entity from oneToMany association with projection bean

### ISSUE THREAD

**Issue by thibaudsowa** [querydsl/querydsl#1677]
Hi,

So I wanted to use projection bean in my project to optimize loading time (to avoid to get unusefull data...).

I have these two enties: Parent -----< Child (with one-to-many association)

In my database I have:

- parent1 with child1 and child2
- parent2 witout children

I wanted to get parent and children in one request so first I did this:

    final JPAQueryBase<?> query = createQuery();

    final QParent qParent = QParent.parent;
    final QChild qChild = QChild.child;

    Map<Long, Parent> transform = query.from(qParent)
            .leftJoin(qParent.children, qChild)
            .transform(GroupBy.groupBy(qParent.id)
                    .as(Projections.bean(Parent.class,
                            qParent.id,
                            qParent.name,
                            GroupBy.set(qChild).as(qParent.children))));

    final List<Parent> parents = new ArrayList<Parent>(transform.values());

It worked like a charm, the result is something like this:

	[
		Parent: {
			id: 1,
			name: "parent1",
			children: [
				Children: {
					id: 1,
					name: "child1",
					otherAttr: //loaded
				},
				Children: {
					id: 2,
					name: "child2",
					otherAttr: //loaded
				}
			],
			otherAttr: null
		},
		Parent: {
			id: 2,
			name: "parent2",
			children: [], //size: 0
			otherAttr: null
		}
	]

But I didn't want to load the "other attributes" from child entity. So I did this query with a projection bean of Child entity:

    final JPAQueryBase<?> query = createQuery();

    final QParent qParent = QParent.parent;
    final QChild qChild = QChild.child;

    Map<Long, Parent> transform = query.from(qParent)
            .leftJoin(qParent.children, qChild)
            .transform(GroupBy.groupBy(qParent.id)
                    .as(Projections.bean(Parent.class,
                            qParent.id,
                            qParent.name,
                            GroupBy.set(Projections.bean(Child.class,
                                    qChild.id,
                                    qChild.name))
                                    .as(qParent.children))));

    final List<Parent> parents = new ArrayList<Parent>(transform.values());

With this query, I have full control on the attributes to select. But when parent has no children, something strange happened: a Child object with all attributes set to null is present in children list like this:

	[
		Parent: {
			id: 1,
			name: "parent1",
			children: [
				Children: {
					id: 1,
					name: "child1",
					otherAttr: null
				},
				Children: {
					id: 2,
					name: "child2",
					otherAttr: null
				}
			],
			otherAttr: null
		},
		Parent: {
			id: 2,
			name: "parent2",
			children: [ //size: 1
				Children: {
						id: null,
						name: null,
						otherAttr: null
					}
			],
			otherAttr: null
		}
	]

Is it a bug? If not what did I do wrong??

**Comment by timowest** [comment]
That's the default behaviour of projections, partly for backwards compatibility.

If you want a null binding if all arguments to a projection are null you can call `projection.skipNulls()` to get that behaviour.

**Comment by timowest** [comment]
Closing, since this is a feature.

**Comment by thibaudsowa** [comment]
Thanks Timo,

So I tried to use the `projection.skipNulls()` and it works well! ...but not for all cases.

This works (when Child has not SubChildren):

	final JPAQueryBase<?> query = createQuery();

	final QParent qParent = QParent.parent;
	final QChild qChild = QChild.child;

	Map<Long, Parent> transform = query.from(qParent)
	        .leftJoin(qParent.children, qChild)
	        .transform(GroupBy.groupBy(qParent.id)
	                .as(Projections.bean(Parent.class,
	                        qParent.id,
	                        qParent.name,
	                        GroupBy.list(Projections.bean(Child.class,
	                                qChild.id,
	                                qChild.name).skipNulls())
	                                .as(qParent.children))));

	final List<Parent> parents = new ArrayList<Parent>(transform.values());

But if Child has SubChildren like this, a Child entity will be return with all attributes setted to null:

Query:

	final JPAQueryBase<?> query = createQuery();

	final QParent qParent = QParent.parent;
	final QChild qChild = QChild.child;
	final QSubChild qSubChild = QSubChild.subChild;

	Map<Long, Parent> transform = query.from(qParent)
	        .leftJoin(qParent.children, qChild)
	        .transform(GroupBy.groupBy(qParent.id)
	                .as(Projections.bean(Parent.class,
	                        qParent.id,
	                        qParent.name,
	                        GroupBy.list(Projections.bean(Child.class,
	                                qChild.id,
	                                qChild.name,
									Projections.bean(qSubChild.class,
	                        				qSubChild.id,
	                        				qSubChild.name)
                        					.as(qChild.subChild)).skipNulls())
	                                .as(qParent.children))));

	final List<Parent> parents = new ArrayList<Parent>(transform.values());

Result:

	[
	    Parent: {
	        id: 1,
	        name: "parent1",
	        children: [
	            Child: {
	                id: 1,
	                name: "child1",
	                otherAttr: null,
	                SubChild: {
	                	id: 1,
	                	name: "subChild1",
	                	otherAttr: null,
	                }
	            },
	            Child: {
	                id: 2,
	                name: "child2",
	                otherAttr: null,
	                SubChild: {
	                	id: 2,
	                	name: "subChild2",
	                	otherAttr: null,
	                }
	            }
	        ],
	        otherAttr: null
	    },
	    Parent: {
	        id: 2,
	        name: "parent2",
	        children: [ //size: 1
	            Child: {
	                    id: null,
	                    name: null,
	                    otherAttr: null,
		                SubChild: {
		                	id: null,
		                	name: null,
		                	otherAttr: null,
		                }
	                }
	        ],
	        otherAttr: null
	    }
	]

Is there a way to fix problem even if my Child entity has SubChild entity?

Thanks.

**Comment by timowest** [comment]
You need to apply the skipNulls() on all projections individually, the scope is not the query, but the projection:

```
Map<Long, Parent> transform = query.from(qParent)
        .leftJoin(qParent.children, qChild)
        .transform(GroupBy.groupBy(qParent.id)
                .as(Projections.bean(Parent.class,
                        qParent.id,
                        qParent.name,
                        GroupBy.list(Projections.bean(Child.class,
                                qChild.id,
                                qChild.name,
                                Projections.bean(qSubChild.class,
                                        qSubChild.id,
                                        qSubChild.name).skipNulls()
                                        .as(qChild.subChild)).skipNulls())
                                .as(qParent.children))));
```

**Comment by thibaudsowa** [comment]
Thanks Timo for taking time to my problem.

I already tried to do something like this but unfortunately I cannot do that:
```java
Projections.bean(...).skipNulls().as(qChild.subChild)
```
...because `FactoryExpressionBase.skipNulls()` returns `FactoryExpression<T>`

Neither:
```java
Projections.bean(...).as(qChild.subChild).skipNulls()
```
...because `QBean.as()` returns `Expression<T>`

Any advice? Thanks

**Comment by thibaudsowa** [comment]
I did not find any solution for this problem yet... Any help would be appreciated. Thanks in advance :)

**Comment by timowest** [comment]
You can create this alias also via `ExpressionUtils.as(...)`. I'll improve the `factoryExpr.skipNulls()` signature.

**Comment by visshh7** [comment]
I have a similar scenario, but I am facing the problem with pagination. Since pagination is performed on the rows of the query result, some of the child table data are getting missed. Is there any way to handle this with scenario with single query.
