### ISSUE TITLE
QueryDSL 4.0 queryFactory.select(Projections.bean()) is broken

### ISSUE THREAD

**Issue by DanielNoga** [querydsl/querydsl#1679]
```
QTrade trade = QTrade.trade;
JPAQueryFactory queryFactory = new JPAQueryFactory(entityManager);
JPAQuery query = queryFactory.select(Projections.bean(Trade.class, trade.price, trade.quantity)).from(trade);
System.out.println(query.toString);
```
Generates 
*select trade.price, trade.quantity from Trade trade*
instead of 
*select new model.Trade(trade.price, trade.quantity) from Trade trade*

**Comment by timowest** [comment]
How about the execution? Does it work?

Querydsl serializes all complex projections types in a flattened way, the mapping to results happens when the result is consumed, that's why it looks different then what you expect.

**Comment by timowest** [comment]
Closing, since the serialization is generic, but the functionality works.
