### ISSUE TITLE
Improve API for concatenating a subquery with a literal

### ISSUE THREAD

**Issue by robertandrewbain** [querydsl/querydsl#1680]
The best I can come up with is:
```java
Expressions.stringOperation(
    Ops.CONCAT, 
    SQLExpressions.select(foo.fooString).from(foo), 
    Expressions.constant(" "));
````
I feel that using `Ops` in non-querydsl code is a leaky abstraction and that instead, support for this should be added to the `Expressions` class, offering the following API:

````java
	public static StringExpression append(Expression<String> left, Expression<String> right)

	public static StringExpression concat(Expression<String> left, Expression<String> right)

	public static StringExpression append(Expression<String> left, String right) 

	public static StringExpression concat(Expression<String> left, String right)
````

Having `append` and `concat` provides consistency with `StringExpression`.

**Comment by timowest** [comment]
Could you list use cases where the static methods would be needed? 

Because providing all the operation creation in both static prefix and instance infix mode might be overkill and confuse users.

**Comment by Shredder121** [comment]
I'd say static prefix is a little closer to SQL.

**Comment by robertandrewbain** [comment]
@timowest where is this provided in instance infix mode? If I wanted to concatenate a `String`  to `SQLExpressions.select(foo.fooString).from(foo)`, unless I'm missing something, the only way to do it is:

````java
Expressions.stringOperation(
    Ops.CONCAT, 
    SQLExpressions.select(foo.fooString).from(foo), 
    Expressions.constant(" "));
````

**Comment by timowest** [comment]
@robertandrewbain Yes, I realize that, but alternatively we could think also consider providing easy conversion of (sub)queries to typed expressions. Just sketching some alternatives.

**Comment by robertandrewbain** [comment]
@timowest, you mean, E.G. a way of getting a `StringExpression` rather than an `Expression<String>`?

**Comment by timowest** [comment]
yes, it was possible in Querydsl 3, but Querydsl 4 doesn't have StringExpression query types anymore, since the subquery types where removed.

**Comment by robertandrewbain** [comment]
If we do go down the static route, I imagine it would actually be better placed in `SQLExpressions`.

**Comment by robertandrewbain** [comment]
# Based on discussions

 * Creating static methods for functionality already provided by instance infix methods is bad because it complicates the API and repeats code.

* Trying to do something generic on `Expression` is dirty / painful as it has many direct subclasses, all of which would require the same / similar concrete impls.

# Proposed solution

* Create static methods in `Expressions` which will return the required typed expression. The code would look like this:

````java
	public static StringExpression asString(Expression<String> expr) {
		return new StringExpression(expr) {

			@Override
			public <R, C> R accept(Visitor<R, C> v, C context) {
				return expr.accept(v, context);
			}

		};
	}
````

We could provide a similar method for `NumberExpression`, etc.

Does this sound like a reasonable design decision?

**Comment by timowest** [comment]
Yes, that sounds good. With Java 6 generics doing the same with instance methods doesn't seem to be possible.

**Comment by Shredder121** [comment]
Yes, sounds good.
Maybe `this.mixin.accept(v, context)` is better, since otherwise it would close over `expr` instead of just selecting an instance variable.

**Comment by timowest** [comment]
You can extract the mixin or this if none is used via `expr.accept(ExtractorVisitor.DEFAULT, null)`

**Comment by robertandrewbain** [comment]
Issue pending code-review changes.

**Comment by robertandrewbain** [comment]
Code review comments applied.
