### ISSUE TITLE
Support for Hibernate @ColumnTransformer Annotation Processing

### ISSUE THREAD

**Issue by codelirium** [querydsl/querydsl#1690]
Hello,

I have a MySQL db and a table which contains some fields encrypted with AES via @ColumnTransformer. It seems to me that both JPAAnnotationProcessor and HibernateAnnotationProcessor does not take this into account so predicates that involve case sensitivity  such as equalsIgnoreCase() or containsIgnoreCase() are failing to perform the select on the decrypted values but rather on the gibberish. 

Is there something I am missing or this is indeed not implemented yet?

**Comment by timowest** [comment]
Could you provide an example case? Also could you clarify which ColumnTransformer annotation you are refering to? Is it now standardized in JPA.

Querydsl JPA provides only a mapping to JPQL, and the ColumnTransformer should be utilized by the JPA provider for JPQL to SQL mapping.

**Comment by codelirium** [comment]
Hello @timowest 

So heres an example.

I have a got a Hibernate Entity like this:

@Entity
@Table(name = User.TABLE_NAME)
@AttributeOverride(name = BaseEntity.FIELD_NAME_ID, column = @Column(name = Employee.COLUMN_NAME_ID))
public class Employee extends User implements Serializable {
...
...

which has a field like that:

public static final String COLUMN_NAME_FIRSTNAME = User.FIELD_PREFIX + "FIRST_NAME";
@Column(name = COLUMN_NAME_FIRSTNAME, nullable = true)
@org.hibernate.annotations.ColumnTransformer(read = "AES_DECRYPT(" + COLUMN_NAME_FIRSTNAME + ", '" + Crypto.MY_KEY + "')", write = "AES_ENCRYPT(?, '" + Crypto.MY_KEY + "')")
private String firstName;

So the apt plugin generates my QEmployee which I am going to use in a BooleanExpression to build a QueryDSL Predicate to send to my employeeRepository.

So I would expect this to work:

this.userSearchExpression = this.userSearchExpression.and(QEmployee.employee.firstName.likeIgnoreCase(String.format("%s%s%s", PERCENTAGE, searchDTO.getFirstName(), PERCENTAGE));

likeIgnoreCase appears to lower the value of firstName before applying the like operation so I believe that the ColumnTransformer is invoked after the lower() so the encrypted text is getting modified and the query fails.

What do you think?

**Comment by codelirium** [comment]
For your convenience, this is how my repository looks like:

@Transactional(readOnly = false)
public interface EmployeeRepository extends PagingAndSortingReadWriteRepository<Employee, Long>, QueryDslPredicateExecutor<Employee> {

}

**Comment by timowest** [comment]
How did the rendered SQL look like?

**Comment by codelirium** [comment]
2015-12-12 22:29:48 DEBUG o.h.s.i.ConcurrentStatisticsImpl:412 - HHH000117: HQL: select employee
from Employee employee
where employee.id is not null and employee.type in (:x1_0_, :x1_1_) and (lower(employee.firstName) like ?2 or employee.firstName like ?3 escape '!' or employee.lastName like ?2 escape '!' or employee.lastName like ?3 escape '!')
order by employee.id asc, time: 274ms, rows: 10

so essentially ignoreCase lowers it: lower(employee.firstName) like ?2 but given that it wont work for me I suspect that the column transformation takes place after the lowering?

**Comment by timowest** [comment]
this looks like the JPQL, how does the SQL look like?

**Comment by codelirium** [comment]
lower(AES_DECRYPT(employee0_.USER_FIRST_NAME, @mykey)) like ?

If so something must be really wrong ...

**Comment by timowest** [comment]
But that looks's valid. At least your issues aren't caused by a missing transformation.

**Comment by codelirium** [comment]
@timowest thanks a lot for helping out with this and please receive my apologies for the false alarm. You've been extremely helpful.

**Comment by timowest** [comment]
Ok, so likeIgnoreCase works?

**Comment by codelirium** [comment]
It does. I just figured out what the problem was. the firstName is a varbinary in the DB. So I tried to do this:

@org.hibernate.annotations.ColumnTransformer(read = "CAST(AES_DECRYPT(" + COLUMN_NAME_FIRSTNAME + ", '" + Crypto.MY_KEY + "') AS CHAR)", write = "AES_ENCRYPT(?, '" + Crypto.MY_KEY + "')")
private String firstName;

but apparently QueryDSL added the table alias to CHAR so the query failed. Should I use StringTemplate on the StringExpression?

**Comment by timowest** [comment]
> but apparently QueryDSL added the table alias to CHAR so the query failed. 

What do you mean by that? I doubt that Querydsl added implicit casts.

> Should I use StringTemplate on the StringExpression?

StringTemplate could be used for a cast if you don't get it sorted out otherwise. Does AES_DECRYPT also return a varbinary?

**Comment by codelirium** [comment]
So If I change the ColumnTransformer to what it is above this SQL gets printed:

and (
                lower(CAST(AES_DECRYPT(employee0_.USER_FIRST_NAME, Crypto.MY_KEY) AS employee0_.CHAR)) like ?
                or lower(CAST(AES_DECRYPT(employee0_.USER_LAST_NAME, Crypto.MY_KEY) AS employee0_.CHAR)) like ?
            )

Notice the alias prepended to CHAR. Yes it looks like that AES_DECRYPT returns varbinary. How could I possibly get along this?

**Comment by codelirium** [comment]
If I set the firstName to byte[] I wont have much options to String comparisons on it for a search feature lets say.

**Comment by timowest** [comment]
This looks like a Hibernate bug https://forum.hibernate.org/viewtopic.php?f=1&t=1009635&view=next

**Comment by scyber** [comment]
Hi Guys, it seems I have the same issue and I could not find any reason why I can't see in the debug my sql
@timowest  Could you please help with it?

**Comment by scyber** [comment]
@timowest It seems I have found what I did wrong, but anyway I have come across with another issue.
I'm calling smth like ((cast(aes_decrypt(family,'1234567890123456') AS CHAR CHARACTER SET 'cp1251'))
but
The hibernate add extra to my transformation

Could you please advice how I can send exactly what I'd like to without extra addons 
(cast(aes_decrypt(cliffio0_.family,
        '1234567890123456')AS cliffio0_.CHAR cliffio0_.CHARACTER cliffio0_.SET 'cp1251') as family12_0_,
?
Thank you so much in advance.

**Comment by lasneyx** [comment]
@scyber This is an hibernate bug: [HHH-8944](https://hibernate.atlassian.net/browse/HHH-8944). You can workaround it by using `CAST(AES_DECRYPT(family, key) AS CHAR(LENGTH))`.

Although `CAST(TEXT AS CHAR)` works directly, with hibernate it does not work till you add an specific length: i.e CHAR(128).

If you don't specify the CHARACTER SET, CAST will use your database defaults.
