### ISSUE TITLE
No documentation for SubQueries with Tuple conditions

### ISSUE THREAD

**Issue by OzoneGrif** [querydsl/querydsl#1692]
Hello, I tried to ask this question on Stackoverflow without asnwer :

http://stackoverflow.com/questions/34046050/querydsl-and-subquery-with-tuple-condition

The documentation presents the way to do it with one result, but not when your subquery returns a Tuple. I've been digging hard to find a way to do this, but I'm stuck.

**Comment by timowest** [comment]
I'll answer to SO, since GitHub issues is not a Q&A forum.
