### ISSUE TITLE
Missing  com.vividsolutions:jts:jar:1.10

### ISSUE THREAD

**Issue by natros** [querydsl/querydsl#1697]
The last version of querydsl code gen depends on  com.vividsolutions:jts:jar:1.10 that does not exists in maven central.

```xml
<dependency>
    <groupId>com.querydsl</groupId>
    <artifactId>querydsl-sql-codegen</artifactId>
    <version>4.0.7</version>
</dependency>
```

The only versions available are 1.8, 1.11, 1.12 and 1.13

![image](https://cloud.githubusercontent.com/assets/4996289/11607872/d09bf3a0-9b4f-11e5-9659-97aa326b82b6.png)

jts is a transitive dependency of querydsl-sql-spacial. Can't querydsl-sql-spacial be made \<optional\>?

**Comment by timowest** [comment]
It's available from here http://www.querydsl.com/maven/com/vividsolutions/jts/1.10/

This Maven repository is referenced from the root pom, so shouldn't cause any issues.

**Comment by natros** [comment]
The problem is that I am using an internally repository (nexus) that mirrors the public maven repository.
I can add these coordinates to our internal repository.
Is there any reason for not using the version that is most close to the 1:10?

When I use this dependency
```xml
 <dependencies>
        <dependency>
            <groupId>com.querydsl</groupId>
            <artifactId>querydsl-sql-codegen</artifactId>
            <version>4.0.7</version>
        </dependency>
    </dependencies>
```

the maven enforcer plugins complains about two jts versions:
```
Dependency convergence error for com.vividsolutions:jts:1.13 paths to dependency are:
+-pt.ipb.querydsl.demo:ipb-querydsl:1.0-SNAPSHOT
  +-com.querydsl:querydsl-sql-codegen:4.0.7
    +-com.querydsl:querydsl-sql-spatial:4.0.7
      +-com.querydsl:querydsl-spatial:4.0.7
        +-org.geolatte:geolatte-geom:0.13
          +-com.vividsolutions:jts:1.13
and
+-pt.ipb.querydsl.demo:ipb-querydsl:1.0-SNAPSHOT
  +-com.querydsl:querydsl-sql-codegen:4.0.7
    +-com.querydsl:querydsl-sql-spatial:4.0.7
      +-com.vividsolutions:jts:1.10
```
So, I assume that the version 1.13 must be compatible.
