### ISSUE TITLE
Row number with path builders.

### ISSUE THREAD

**Issue by miroslav24** [querydsl/querydsl#1707]
I got problem when I am trying to write this sql select with query dsl:

```
select productName,productDescription from 
    (select productName,productDescription, 
     row_number() over (order by productName) as rn 
     from productTable)
where rn >=0 and rn <= 2;
```

I use this select for paging rows with ordering by one column
I have to use row_number function because offset and limit functions 
do not work with ordering.

I am trying to use PathBuilders like this:

```
JPAQuery query = new JPAQuery(entityManager);
PathBuilder<Product> product = new PathBuilder<>(Product.class, "product");
OrderSpecifier<String> sortOrder = new OrderSpecifier<>(Order.ASC, product.get("productName", String.class));

SimpleExpression<Long> rowNumber = SQLExpressions.rowNumber()
                .over().orderBy(sortOrder).as("rowNumber");

query.select(product.get("productName",String.class))
    .from(SQLExpressions.select(product.get("productName",String.class), rowNumber)
                        .from(product).as(product))
    .where(Expressions.numberPath(Long.class, "rowNumber").goe(0L))
    .where(Expressions.numberPath(Long.class, "rowNumber").loe(2L))
    .fetch();
```

My questions are:
1. The example syntax is not compilable and should be only in querydsl 4. Is this possible in querydsl 4 or 3.5 ?
2. Please give me advice how to construct this statement in querydsl 3.5 or 4

Thanks in advice.

**Comment by miroslav24** [comment]
@timowest
Please have a look on this issue. Thanks.

**Comment by timowest** [comment]
There are a few issues here
* You are mixing window functions, which are only supported in SQL queries with JPAQuery, which Querydsl module do you want to use?
* You don't need to write the underlying paging SQL, you can use query.limit(..).offset(...), this works in all Querydsl modules
* Why do use PathBuilder? For Both Querydsl JPA and SQL the code generations are the preferred choice.

**Comment by miroslav24** [comment]
We use only JPAQuery.
Functions query.limit(..).offset(...), are translated into sql select which is based on rownum, and what I read in some posts like this:
http://stackoverflow.com/questions/15091849/how-to-use-oracle-order-by-and-rownum-correctly
it is no guaranteed, that the rownum will be evaluated well if there is ordering.
Answer for your last question is that unfortunately we are constrained not to use code generations.

**Comment by timowest** [comment]
Could you try JPAQuery with limit and offset and post the resulting SQL query? I am sure that the underlying JPA provider will use rownum properly.

**Comment by timowest** [comment]
Feel free to reopen, if your issue isn't fixed yet

**Comment by miroslav24** [comment]
Hello Timo,

problem still remains, but I did not have time to concentrating on this bug. I found similar bug,
which deals with hibernate criteria builder, here is the link:
https://nhibernate.jira.com/browse/NH-3814
Maybe It will clarify the problem for you.

**Comment by miroslav24** [comment]
Please reopen the bug.

**Comment by miroslav24** [comment]
@timowest
Please have a look on this issue. Thanks.

**Comment by timowest** [comment]
Like I said before window functions can't be used with JPQL. You will need to use limit/offset or Querydsl SQL.

Could you explain why limit/offset doesn't work with order by?

**Comment by miroslav24** [comment]
Here is the problematic select:

select * from
         ( select
             row_.*,
             rownum rownum_ 
         from
             ( select
                person3_.PERSONID as PERSONID2_67_1_,
                person3_.PERSONTYPE as persontype
             from CP2.PERSON person3_ 
             where person3_.DELETEFLAG=0 
             order by
                 person3_.PERSONTYPE desc ) row_ 
         where
             rownum <= 10
         ) 
     where
         rownum_ > 0

There are duplicate values in column PERSONTYPE. 

Output of this select is:
PERSONID2_67_1_, persontype, ROW_NUM_
57300	11	1
59902	11	2
59901	11	3
58709	11	4
58707	11	5
58506	11	6
58504	11	7
58502	11	8
58500	11	9
57302	11	10

The second page should be like this:
  select
         * 
     from
         ( select
             row_.*,
             rownum rownum_ 
         from
             ( select
                person3_.PERSONID as PERSONID2_67_1_,
                person3_.PERSONTYPE as persontype
             from CP2.PERSON person3_ 
             where person3_.DELETEFLAG=0 
             order by
                 person3_.PERSONTYPE desc ) row_ 
         where
             rownum <= 20
         ) 
     where
         rownum_ > 10

And output:
PERSONID2_67_1_, persontype, ROW_NUM_
60005	11	11
59902	11	12
59901	11	13
58709	11	14
58707	11	15
58506	11	16
58504	11	17
58502	11	18
58500	11	19
57302	11	20

The problem is that on second page there are duplicate rows selected except the first one.

**Comment by miroslav24** [comment]
But I resolved this problem by adding default ordering by primary key for example:
