### ISSUE TITLE
Cannot retrieve generated keys with SQLInsertClause::executeWithKeys if SQLCloseListener is enabled

### ISSUE THREAD

**Issue by jjzazuet** [querydsl/querydsl#1710]
Hi. Suppose I have the following setup:

    SQLQueryFactory qf = new SQLQueryFactory(mySchemaConfig, myDataSource, true); <-- add sql close listener
    SQLInsertClause todoInsert = qf.insert(myTodoQType);
    Todo myTodoPojo = new Todo(); // Todo table has ID and text columns.

And then I try to insert a TODO item into my db, and retrieve it's ID, based on the next sequence number, preconfigured in my database schema:

    myTodo.setText("Buy groceries");
    Long insertedTodoId = todoInsert
        .set(myTodoQType.id, SQLExpressions.nextVal("MY_TODO_ID_SEQUENCE"))
        .set(myTodoQType.text, myTodo.getText())
        .executeWithKey(myTodoQType.id);
    myTodo.setId(insertedTodoId);

In the code above, I'm finding that if I configure my query factory `qf` to use the `SQLCloseListener`, it will cause this line:

    Long insertedTodoId = todoInsert
        .set(myTodoQType.id, SQLExpressions.nextVal("MY_TODO_ID_SEQUENCE"))
        .set(myTodoQType.text, myTodo.getText())
        .executeWithKey(myTodoQType.id);

to throw this exception:

    com.querydsl.core.QueryException: java.sql.SQLException: Closed Resultset: next
	at com.querydsl.sql.DefaultSQLExceptionTranslator.translate(DefaultSQLExceptionTranslator.java:39)
	at com.querydsl.sql.Configuration.translate(Configuration.java:441)
	at com.querydsl.sql.dml.SQLInsertClause.executeWithKey(SQLInsertClause.java:179)
	at com.querydsl.sql.dml.SQLInsertClause.executeWithKey(SQLInsertClause.java:153)

Now, if I reconfigure my query factory `qf` to not use the `SQLCloseListener`:

    SQLQueryFactory qf = new SQLQueryFactory(mySchemaConfig, myDataSource, false);

The `insert` clause will run fine, but my code starts leaking connections if I don't find a way to close them explicitly.

1) Is my understanding on how to use `executeWithKey` correct?
2) Should I manage my own connections with `insert` clauses instead of relying on `SQLCloseListener`? Or is this a bug in the listener itself?

Thanks for your time and help!

**Comment by timowest** [comment]
Which Querydsl version do you use?

**Comment by jjzazuet** [comment]
`4.0.5`. Thanks!
