### ISSUE TITLE
I think h2's group_concat should be supported

### ISSUE THREAD

**Issue by activedecay** [querydsl/querydsl#1715]
The h2 function list http://www.h2database.com/html/functions.html has a group_concat operation.

Could you add support for this feature? How can I add this function myself until there's support on the main release?

Thanks :)

**Comment by timowest** [comment]
group_concat provides a few variations in syntax. Which one do you need?

**Comment by activedecay** [comment]
select group_concat(u.sex) from users u where u.online group by u.sex

Simplest variation will work. I don't need to specify the separator or the group_by syntax variations.

**Comment by activedecay** [comment]
awesome. many thanks.
