### ISSUE TITLE
Generated classes should have a PathBuilder

### ISSUE THREAD

**Issue by johnktims** [querydsl/querydsl#1721]
Something like `QEntity.entity.get("field")` would be nice to have for dynamic access.

**Comment by Shredder121** [comment]
I agree that this would be nice.
But the default way of Querydsl is better with type-safety, refactoring support(compile time validation that you changed all occurrences), readability, just to name a few.

How about an opt-in? Maybe an annotation?

**Comment by johnktims** [comment]
I think using an annotation is a good idea. `@GeneratePathBuilder`, `@PathBuilder`, `@DynamicPathBuilder`?

**Comment by Shredder121** [comment]
At least `@PathBuilder` is not a good one, since there is already a class named that.
I was also thinking of `@DynamicPathBuilder`.

**Comment by Shredder121** [comment]
But `@GeneratePathBuilder` might be better, since it's a do-that annotation, and it's just a `PathBuilder`, not a special, or a dynamic one.

**Comment by timowest** [comment]
I'm for `@GeneratePathBuilder`. 
Should the generated PathBuilder serve the already created property paths via `pathBuilder.get(...)`?

**Comment by Shredder121** [comment]
If you know a feasible way to do that.
Although, `Path`s aren't awfully expensive.

**Comment by timowest** [comment]
You get the correct types and collecting the properties is possible by overriding `BeanPath.add(Path)`

**Comment by Shredder121** [comment]
That sounds good!
