### ISSUE TITLE
querydsl-lucene: Improve deep pagination performance

### ISSUE THREAD

**Issue by mateuszlo** [querydsl/querydsl#1730]
Using `IndexSearcher.search` with large offset is inefficient, because you have to fetch all 'offset + limit' ScoreDocs and then discard first 'offset' ScoreDocs. For offsets bigger than few hundred thousand this becomes a noticable problem.

Lucene provides `IndexSearcher.searchAfter` function, that efficiently finds all documents, that occur directly after specified `ScoreDoc`. You can use it to efficiently perform deep pagination.

'Next page' can be obtained by passing last document of current page to `IndexSearcher.searchAfter`.
'Previous page' can be obtained by passing first document of current page to `IndexSearcher.searchAfter` and reversing the sorting.

I suggest adding `pageIterator()` function to `AbstractLuceneQuery`, that would return a `PageIterator` object, that internally uses `IndexSearcher.searchAfter` function and allows efficient pagination. `PageIterator` should support following methods:

```
List<T> nextPage()
List<T> previousPage()
List<T> firstPage()
List<T> lastPage()
boolean hasNext()
boolean hasPrevious()
```

**Comment by timowest** [comment]
The PageIterator approach competes a bit with the QueryResults of Querydsl.

How about support for searchAfter without PageIterator?

**Comment by mateuszlo** [comment]
`IndexSearcher.searchAfter()` requires an instance of previous `ScoreDoc` as a parameter. Currently `ScoreDoc` instances are hidden inside `ResultIterator`, which is returned by `AbstractLuceneQuery.iterate()` and there is no way of accessing them from the outside. And by the time the results are transformed to `QueryResults` in `AbstractLuceneQuery.fetchResults()` the 'ScoreDoc' instances are completly lost.

So this approach would require adding some way to access 'ScoreDoc' instances.
