### ISSUE TITLE
SQLQuery.toString should not have side effects

### ISSUE THREAD

**Issue by ssaarela** [querydsl/querydsl#1737]
Calling ProjectableSQLQuery.toString registers pending join clauses as a side effect. If one happens to call query.toString() between join() and on() then the query breaks as a result: 

    query.from(x);
    query.leftJoin(y) // toString() call e.g. by debugger
    .on(x.foo.equals(y.foo));
    query.leftJoin(z).on(z.foo.equals(y.foo));

Results in 

    from x 
    left join y 
    left join z on x.foo = y.foo and z.foo = y.foo

ToString with side effects is especially disastrous with modern debuggers as they call toString every time execution pauses. This makes debugging query builders very hard and error-prone.

**Comment by timowest** [comment]
I agree. I will try to fix it in DefaultQueryMetadata.
