### ISSUE TITLE
NullPointerReference on second level reference in QEntity

### ISSUE THREAD

**Issue by Sbou** [querydsl/querydsl#1738]
Hi,

I have an entity which has areference to another and this last has a reference to a third entity.
Ex : User->Address->City
When I want to use QUser.user.address.city, it was null.
My application's first version worked and the only difference I found is in QUser in constructor.

In my first release I have this line :

``` java
this.address= (inits.isInitialized("address") ? new QAddress(forProperty("address"), inits.get("address")) : null);
```

But in new release, I have :

``` java
this.address= (inits.isInitialized("address") ? new QAddress(forProperty("address")) : null);
```

How QueryDsql choose implementation ?

Thanks,

**Comment by timowest** [comment]
Which Querydsl version do you use?

**Comment by Sbou** [comment]
I use QueryDSL v4.0.1

**Comment by timowest** [comment]
Could you upgrade to the latest version?

**Comment by timowest** [comment]
Also what kind of annotations do User, Address and City have?

**Comment by Sbou** [comment]
This is annotations :

```java
@Entity()
@Table(name = "USERS")
@Cacheable(false)
public class User {
...
@ManyToOne(fetch = FetchType.EAGER)
@JoinColumns({
		@JoinColumn(name = "ID_ADDRESS", referencedColumnName = "ID_ADDRESS", insertable=false, updatable=false),
		@JoinColumn(name = "NUM_VERSION", referencedColumnName = "NUM_VERSION", insertable=false, updatable=false)
})
private Address address;

...
}

@Entity
@Table(name = "ADDRESSES")
@Cacheable(false)
public class Address extends AddressBase {
...
}

@MappedSuperclass
@IdClass(AddressPK.class)
public abstract class AddressBase {

	@Id
	@Column(name = "ID_ADDRESS")
	private long idAddress; 

	@Id
	@Column(name = "NUM_VERSION")
	private int numVersion;

	@ManyToOne
	@JoinColumn(name="ID_ADDRESS", insertable=false, updatable=false)
	@JoinFetch(JoinFetchType.OUTER)
	private City city;

...
}
```

**Comment by timowest** [comment]
I added a test and couldn't replicate the issue. How does City look like? Also what domain change did you that introduced the change in the Q-types?

**Comment by dirkweil** [comment]
I have a similar issue - maybe it helps clarifying the issue. But in my case, the relation attribute reference within the QueryDSL generated meta data classes remains null only starting with the third netsted level.

I've isolated a test to reproduce the issue: https://github.com/dirkweil/querydsl-demo.
The test involves the 4 entities A, B, C and D from the package de.gedoplan.beantrial.jpa.entity. In the same package, but in the test source folder, you can find the test class AbcdTest. The test method testAbcd - using 3 nested relationships - fails, while testAb and testAbc run OK.

**Comment by timowest** [comment]
@dirkweil Querydsl has limited initialization depth because of the final field usage, more about it here http://www.querydsl.com/static/querydsl/4.0.7/reference/html_single/#d0e2245
