### ISSUE TITLE
QueryEntities - generates metamodel for the whole package instead for provided classes

### ISSUE THREAD

**Issue by zerkowsm** [querydsl/querydsl#1743]
I have the entities coming from jar which is included in my project dependencies (the package is com.xxx.model) so I have package-info.java file in my project's com.xxx.model package. File contains:

    @QueryEntities(value = {XXX.class, YYY.class}) package com.xxx.model;
    import com.mysema.query.annotations.QueryEntities;

This config works fine but querydsl code generator tries to generate metamodel for all the classes in the com.xxx.model package (coming from the jar), not just QXXX.class and QYYY.class. 
Do I miss something here or this is a bug?
I'm using 3.7.0 version.

**Comment by Shredder121** [comment]
Could you maybe make an example project that we could take a look at?

I think it has to do with the fact that if a class references another class, it should also generate a metamodel for that, and if that class in turn references...
Soon you'll indeed have the entire package.

Anyway, it would be helpful if we could get a realistic example so that we can find out what works best.

**Comment by zerkowsm** [comment]
Thanks for the clarification - that seems to be exactly what you described (I checked the list and it not tries to generate all - just vast majority of them). 
But in such case - can you confirm that - if under the com.xxx.model package there are also other dependent packages as com.xxx.model.zzz containing some ZZZ.java entity, it is not being generated without dedicated (for com.xxx.model.zzz package) package-info.java as below (error: cannot find symbol):

     @QueryEntities(value = {ZZZ.class}) package com.xxx.model.zzz;
     import com.mysema.query.annotations.QueryEntities; 

Is there a way to do something like com.xxx.model.*, maybe?

**Comment by timowest** [comment]
> Is there a way to do something like com.xxx.model.*, maybe?

A package wildcard scan is not supported. I'm not if that's possible with the APT API.

**Comment by timowest** [comment]
Just for clarification, the location of the QueryEntities annotation doesn't affect the code generation.

**Comment by timowest** [comment]
Pleas reopen, if still unresolved

**Comment by zerkowsm** [comment]
It's fine, thanks.
