### ISSUE TITLE
QueryInit doesn't work for paths involving as()

### ISSUE THREAD

**Issue by nealeu** [querydsl/querydsl#1744]
I've tried this via StackOverflow at http://stackoverflow.com/questions/34385272/null-pointer-when-using-querydsl-subtypes, but not getting any responses, so I'm assuming there are some missing features or some magic.

I am trying to do an expression that is the same in structure as this example, but I get tyre is null.
```
QWheel wheel = QCar.car.wheel;
QTyre tyre = wheel.as(QRoadWheel.class).tyre;    
BooleanExpression tyreFittedOverYearAgo 
    = tyre.fitted.lt(today.minusYears(1));
Iterable<Car> carsWithOldTyres = repo.findAll(tyreFittedOverYearAgo);
```
There seems to be no way to ensure that properties on the as() instance are initialised?

**Comment by timowest** [comment]
Which Querydsl version do you use?

**Comment by Shredder121** [comment]
One thing to note: you dereference a lot of properties, consider joining and aliasing instead.
(Usually, that's what the resulting query actually looks like, so debugging/reasoning is better that way)

**Comment by nealeu** [comment]
Hi Timo,

As I replied on the SO, 3.6.0, but also had the same result when upgraded to 3.7.0.

I've continued trying different angles and I've found that @QueryInit("*") works.

**Comment by timowest** [comment]
BeanPath.as(Class) will not change the initialization depth in this case.

QCar.car.wheel will have direct non-reference properties initialized.

You can also apply `@QueryInit("tyre")` on the wheel property of cart.

**Comment by nealeu** [comment]
Thanks.

I'll have to have another go at why @QueryInit("tyre") didn't work for me, yet "*" did.

**Comment by timowest** [comment]
Where did you put the QueryInit annotation?

**Comment by timowest** [comment]
Pleas reopen, if still unresolved
