### ISSUE TITLE
Override BigDecimal as default type for sql-codegen

### ISSUE THREAD

**Issue by renanleandrof** [querydsl/querydsl#1748]
Hello!

I need to override the code generation to use MyNumericClass instead of BigDecimal!

Is it possible on sql-codegen to override?

**Comment by timowest** [comment]
What is the JDBC type you need to override and what do you use for code generation: java, maven or ant?

**Comment by renanleandrof** [comment]
Any DECIMAL(?,?) and i use Maven to generate the sources

**Comment by timowest** [comment]
Then it should work with the following pattern

```
<numericMappings>
  <numericMapping>
    <total>1</total>
    <decimal>0</decimal>
    <javaType>java.lang.Byte</javaType>
  </numericMapping>
</numericMappings>
```

http://www.querydsl.com/static/querydsl/4.0.7/reference/html_single/#sql_integration

**Comment by timowest** [comment]
Please reopen if this didn't answer your question
