### ISSUE TITLE
Change datasource pool for example

### ISSUE THREAD

**Issue by wwadge** [querydsl/querydsl#1750]
https://github.com/querydsl/querydsl/blob/master/querydsl-examples/querydsl-example-sql-spring/src/main/java/com/querydsl/example/config/JdbcConfiguration.java#L31

Uses BoneCP which has been deprecated for a while now.  Try using HikariCP instead (it's more stable/supported/faster).

Wallace
(bonecp author)

**Comment by Shredder121** [comment]
I agree, I also use HikariCP.
It's a shame though, but thanks for letting us know.
