### ISSUE TITLE
querydsl wiki have some dead links and some suggest.

### ISSUE THREAD

**Issue by songsungkyun** [querydsl/querydsl#1752]
https://github.com/querydsl/querydsl/wiki/Roadmap
* Milestones section.

https://github.com/querydsl/querydsl/wiki/Query-serialization-logic
* all links are dead.

and I think some class hierarchy is helpful for beginners like me.
sample)
![hierachy](https://cloud.githubusercontent.com/assets/3406861/12394222/dc5ee1c8-be3d-11e5-9019-f3cd5af0edc1.png)

**Comment by Shredder121** [comment]
Hi, I just now fixed the broken link for the Roadmap.
For the other links I'll use some more time.
Thanks for reporting.
