### ISSUE TITLE
why is the eq operator doing math on my string?

### ISSUE THREAD

**Issue by activedecay** [querydsl/querydsl#1762]
in the following example, I don't want the input string to have math performed on it. I don't want 1991, I want to use the literal string.

    hostPort <- iqn.1992-01.com.example:pen.whatever

java code

    queryFactory.query(c)
    .select(host.groupuuid)
    .distinct()
    .from(host)
    .join(SQLExpressions.selectDistinct(qHostport.uuid, qHostport.hostuuid)
    .from(qHostport)
    .where(qHostport.uuid.eq(hostPort)), qHostport)
    .on(qHostport.hostuuid.eq(host.uuid));
    
sql created

    select distinct HOST.GROUPUUID
    from HOST HOST
    join (select distinct i.UUID, i.HOSTUUID
    from HOSTPORT i
    where i.UUID = 'iqn.1991.com.example:pen.whatever') as i
    on i.HOSTUUID = HOST.UUID

**Comment by activedecay** [comment]
<querydsl.version>4.0.5

**Comment by activedecay** [comment]
Configuration configuration = new Configuration(new H2Templates());
        configuration.setUseLiterals(true);

**Comment by timowest** [comment]
What about 4.0.7?

**Comment by activedecay** [comment]
testing that now.

**Comment by activedecay** [comment]
ok verified that the update to 4.0.7 worked. cheers!

**Comment by timowest** [comment]
Great!
