### ISSUE TITLE
when convert resultset to bean, could you add option to call setMethod?

### ISSUE THREAD

**Issue by songsungkyun** [querydsl/querydsl#1765]
Querying SQL 4.0.7.
I think, 
when convert resultset to bean, copy value by field level with reflection.
could you add option to call setMethod of bean?

**Comment by timowest** [comment]
Could you provide more context? Maybe a code example?

**Comment by songsungkyun** [comment]
I used Querying SQL 4.0.7(not Querying JPA)
this is Admin bean, List&lt;Admin&gt; adminList = this.queryFactory.selectFrom(this.qAdmin).fetch();
when setting role, I like to enum RoleType also setting.
so, I wrote setRole method, but it's not working becuase I think, copy value by field level with reflection. and then asked below question.
With Querying SQL, is there bettern way to process enum?
```
public class Admin {
    private String role; -- this is table column field.
    private RoleType roleType; -- this is not table column field.

    public static enum RoleType {
        ADMIN, OPERATOR;
    }

    public Admin setRole(String role) {
        this.role = role;
        this.roleType = EnumUtils.getEnum(RoleType.class, this.role);
    }
}
```

**Comment by songsungkyun** [comment]
Sorry, I found enum documentation..

```
Configuration configuration = new Configuration(new H2Templates());
// declares a mapping for the gender column in the person table
configuration.register("person", "gender",  new EnumByNameType<Gender>(Gender.class));
```

http://www.querydsl.com/static/querydsl/4.0.7/reference/html_single/#sql_integration
