### ISSUE TITLE
querydsl-maven-plugin to support multiple schemas at once

### ISSUE THREAD

**Issue by natros** [querydsl/querydsl#1766]
Add property to querydsl-maven-plugin to support multiple schemas at once.

Discussion
https://groups.google.com/d/msg/querydsl/5zuxYrhxz2U/say3FqpUBQAJ

Some suggestions:
```xml
<configuration>
    ....
    <schemaPattern>RAD,FOO,BAR</schemaPattern>
</configuration>
```

```xml
<configuration>
    ...
    <schemaPatterns>
        <schemaPattern>RAD</schemaPattern>
        <schemaPattern>FOO</schemaPattern>
        <schemaPattern>BAR</schemaPattern>
    </schemaPatterns>
</configuration>
``` 

PS: I'm using oracle 11gR2

Thank you.

**Comment by Shredder121** [comment]
Just for reference, how would you solve `schemaPattern` and `tableNamePattern` combinations?
I think specifying multiple schemas then doesn't really make sense, what do you think?

**Comment by natros** [comment]
At my organization we have several oracle databases, some os those databases are connected with database links. Each application has its own schema and has access to all other schemas that needs read or modify data. Creating a maven configuration for each schema has caused me so trouble with the plugin messing up with classes that have the same name, or referencing nonexistent classes. 

In this project https://github.com/natros/querydsl-test I have two schemas GAL and RFID, both have the user table that are not equal. However, in the generation, the plugin generates the same class. So  com.github.natros.entities.rfid.beans.Users is the same as com.github.natros.entities.gal.beans.Users which is wrong. 

Some times I have to add <imports> to the configurations because the plugin cannot resolve the right class.

In some cases adding <schemaToPackage> helps. (there's a branch schema-to-package in the sample project)

For tableNamePattern one could use SCHEMA.TABLE_NAME. For <typeMapping> that would require <schamaName> inside.

BTW querydsl can't handle/see synonyms
https://docs.oracle.com/cd/B19306_01/server.102/b14200/statements_7001.htm
