### ISSUE TITLE
StoreClause: Clear Batches on Execute

### ISSUE THREAD

**Issue by ssaarela** [querydsl/querydsl#1785]
Would it be possible to clear batches on execute, so that it's easy to configure when to flush? Currently we get OutOfMemoryError because of a large batch and the simplest course of action would be just to flush more often.

**Comment by timowest** [comment]
Some people might rely on having the batch data available after that, so maybe an explicit clear() method instead?

**Comment by ssaarela** [comment]
That's ok.
