### ISSUE TITLE
querydsl-sql-spring under gradle?

### ISSUE THREAD

**Issue by rop49** [querydsl/querydsl#1808]
I would humbly like to request that you add documentation how to configure **querydsl-sql-spring** in a **gradle** build.
Googling, I find no instructions on this anywhere -- only maven instructions
-   http://www.querydsl.com/static/querydsl/latest/reference/html/ch02s03.html
-   http://www.querydsl.com/static/querydsl/latest/reference/html/ch02.html#d0e132

Or is gradle build not supported by this project? (if so, it's unfortunate, since spring now has deprecated their querydsl support, and refer to this solution instead)

**Comment by timowest** [comment]
Querydsl does't have Gradle support at the moment, but contributions are welcome. The docs for the Querydsl SQL Spring support are http://www.querydsl.com/static/querydsl/4.0.9/reference/html_single/#d0e1439

**Comment by rop49** [comment]
I see, got it. 
Thanks for clarification!

**Comment by Zhuinden** [comment]
@rop49 technically I've seen QueryDSL configured to work with Gradle, but that was for QueryDSL3.

http://stackoverflow.com/a/28874506/2413303
