### ISSUE TITLE
com.querydsl.sql.ColumnMetadata jdbcType is reference while null

### ISSUE THREAD

**Issue by bbakerman** [querydsl/querydsl#1809]
The field definition in com.querydsl.sql.ColumnMetadata has
    private final Integer jdbcType;

but the getter is

    public int getJdbcType() {
        return jdbcType;
    }

but the constructor of ColumnMetadata allows null values.

in the com.querydsl.sql.Configuration#set you have this code

 public <T> void set(PreparedStatement stmt, Path<?> path, int i, T value) throws SQLException {
        if (Null.class.isInstance(value)) {
            Integer sqlType = path != null ? ColumnMetadata.getColumnMetadata(path).getJdbcType() : null;
            if (sqlType != null) {
                stmt.setNull(i, sqlType);
            } else {
                stmt.setNull(i, Types.NULL);
            }
        } else {
            getType(path, (Class) value.getClass()).setValue(stmt, i, value);
        }
    }

So it looks up column metadata but if the jdbcType is null it will NPE

The jdbcType can be null for Enum types say

com.querydsl.core.types.dsl.BeanPath#createEnum

    protected <A extends Enum<A>> EnumPath<A> createEnum(String property, Class<A> type) {
        return add(new EnumPath<A>(type, forProperty(property)));
    }

    protected <P extends Path<?>> P add(P path) {
        return path;
    }

in this case the RelationPath code does NOT add any metadata for that column and hence its "synthesises" some based on name like

    public static ColumnMetadata getColumnMetadata(Path<?> path) {
        Path<?> parent = path.getMetadata().getParent();
        if (parent instanceof EntityPath) {
            Object columnMetadata = ((EntityPath<?>) parent).getMetadata(path);
            if (columnMetadata instanceof ColumnMetadata) {
                return (ColumnMetadata) columnMetadata;
            }
        }
        return ColumnMetadata.named(path.getMetadata().getName());
    }

The end result of all this is that NPEs happen

I think the query generation code should use com.querydsl.sql.ColumnMetadata#hasJdbcType to check if in fact there is a JDBC type in play.  It appears like it wants to do this but its not happening in effect, specifically for Enum columns

**Comment by timowest** [comment]
I think this is already done https://github.com/querydsl/querydsl/blob/master/querydsl-sql/src/main/java/com/querydsl/sql/Configuration.java#L229

But for completeness I added a hasJdbcType() check also to another place.
