### ISSUE TITLE
HibernateSearch with Lucene 4

### ISSUE THREAD

**Issue by igler** [querydsl/querydsl#1815]
Getting the following error when doing a hibernate-search with Lucene 4:

<pre><code>java.lang.NoSuchMethodError: org.apache.lucene.util.NumericUtils.longToPrefixCoded(JILorg/apache/lucene/util/BytesRef;)I
    at com.mysema.query.lucene.LuceneSerializer.convertNumber(LuceneSerializer.java:192)
    at com.mysema.query.lucene.LuceneSerializer.eq(LuceneSerializer.java:172)
    at com.mysema.query.lucene.LuceneSerializer.toQuery(LuceneSerializer.java:89)
    at com.mysema.query.lucene.LuceneSerializer.toQuery(LuceneSerializer.java:523)
    at com.mysema.query.lucene.LuceneSerializer.toTwoHandSidedQuery(LuceneSerializer.java:127)
    at com.mysema.query.lucene.LuceneSerializer.toQuery(LuceneSerializer.java:78)
    at com.mysema.query.lucene.LuceneSerializer.toQuery(LuceneSerializer.java:523)
    at com.mysema.query.hibernate.search.SearchQuery.createQuery(SearchQuery.java:94)
    at com.mysema.query.hibernate.search.SearchQuery.list(SearchQuery.java:145)
    at .....tour.TourRepositoryImpl.findToursBy(TourRepositoryImpl.java:150)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.__invoke(DelegatingMethodAccessorImpl.java:43)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java)
    at java.lang.reflect.Method.invoke(Method.java:497)
</code></pre>

The query is:<pre><code>@Override
public List<Tour> findToursBy(@Param("schedule") Schedule schedule,
                        @Param("identifier") String identifier) throws ParseException {
    SessionFactory sessionFactory = entityManagerFactory.unwrap(SessionFactory.class);
    Assert.notNull(sessionFactory, "sessionFactory may not be null!");
    Session session = sessionFactory.openSession();
    SearchQuery<Tour> query = new SearchQuery<>(session, qTour);
    List<Tour> list = query
        .where(qTour.schedule.id.eq(1L).and(qTour.identifier.eq(identifier)))
        .list();
   ...
}</code></pre>

I assume the problem is that hibernate-search is using lucene3 module? BTW, I use QueryDSL 3.7.2

Update: In Lucene 4 the method is called `longToPrefixCodedBytes`.

**Comment by timowest** [comment]
Which Hibernate Search version do you use? It looks like Hibernate Search 5 uses Lucene 4, based on this http://hibernate.org/search/documentation/migrate/5.0/

**Comment by igler** [comment]
Using 5.1.2.Final.

**Comment by timowest** [comment]
Querydsl Hibernate Search is compiled against Hibernate Search 4. A querydsl-hibernate-search5 module could introduce support for Hibernate Search 5.

Would you be willing to provide a PR?

**Comment by igler** [comment]
Sure. How can I help?

**Comment by timowest** [comment]
Here are some steps to get you started
* Check out Querydsl
* copy the querydsl-hibernate-search folder to querydsl-hibernate-search5
* modify the dependencies in pom.xml and add the module into root pom.xml
* fix compilation issues and make sure the tests PR
* make a PR

More about contributing here https://github.com/querydsl/querydsl/wiki/Contributing

**Comment by igler** [comment]
Okay, I'll try my best.

**Comment by timowest** [comment]
Great, thanks a lot. It's a quite small module https://github.com/querydsl/querydsl/tree/master/querydsl-hibernate-search/src/main/java/com/querydsl/hibernate/search

**Comment by igler** [comment]
Started with the lucene4 module and updated Lucene to version 4.10.4. After that I modified the <code>convertNumber</code>-method in <code>LuceneSerializer</code>:
<pre><code>
...
} else if (Long.class.isInstance(number) || BigInteger.class.isInstance(number)) {
			System.out.println(">>> Converting number to long >>>");

			BytesRefBuilder bytesRefBuilder = new BytesRefBuilder();
			NumericUtils.longToPrefixCoded(number.longValue(), 0, bytesRefBuilder);

			return bytesRefBuilder.toBytesRef();
		}
...
</code></pre>

The exception is gone after that, but there are no results when running one of the queries against hibernate-search (expecting exactly one result):
<pre><code>
List<Tour> list = query
				.where(qTourSearch.scheduleId.eq(schedule.getId())
						.and(qTourSearch.identifier.contains(identifier.toLowerCase())))
				.list();
</code></pre>

I have annotated the <code>Tour.class</code> the following way:
<pre><code>
public class Tour ... {
    @DiffIgnore
    @ManyToOne
    @NotNull
    @IndexedEmbedded(includeEmbeddedObjectId = true)
    private Schedule schedule;
}

public class QTourSearch extends QTour {

	public QTourSearch(String variable) {
		super(variable);
	}

	public final NumberPath<Long> scheduleId = createNumber("schedule.id", Long.class);
	//public final StringPath scheduleId = createString("schedule.id");

	public final StringPath identifier = createString("identifier");
}
</code></pre>

Using the Luke-tool and investigate the index, I see that the index is stored as String. After modifying the <code>eq</code>-method in <code>LuceneSerializer</code> (<code>return new TermQuery(new Term(field, "" + number.longValue()));</code>) the corresponding tour is returned as search result.
<pre><code>
protected Query eq(Operation<?> operation, QueryMetadata metadata, boolean ignoreCase) {
        verifyArguments(operation);
        Path<?> path = getPath(operation.getArg(0));
        String field = toField(path);

        if (Number.class.isAssignableFrom(operation.getArg(1).getType())) {

			System.out.println(">>> eq comparison >>>");

			Number number = ((Constant<Number>) operation.getArg(1)).getConstant();

			BytesRef bytesRef = convertNumber(number);

			return new TermQuery(new Term(field, "" + number.longValue()));
            //return new TermQuery(new Term(field, bytesRef));
        }

        return eq(field, convert(path, operation.getArg(1), metadata), ignoreCase);
    }
</code></pre>

So I wonder if there is something wrong with the <code>bytesRef</code> value. Do you have any idea how I can continue? The <code>BytesRef</code>-class itself confuses me a little bit with all that bit-"shifting". Have attached to screenshots where I am wondering if the decoding of <code>schedule.id</code> is a problem?
![bildschirmfoto 2016-03-19 um 10 35 27](https://cloud.githubusercontent.com/assets/313565/13897799/6b243b10-edbe-11e5-9019-8e211d512d07.png)
![bildschirmfoto 2016-03-19 um 10 35 37](https://cloud.githubusercontent.com/assets/313565/13897800/72b5dd70-edbe-11e5-90f0-d386d5b0dfba.png)

**Comment by timowest** [comment]
It looks Hibernate Search uses a different kind of mapping for numeric types, maybe you can parametrize LuceneSerializer to take that into account?
