### ISSUE TITLE
com.mysema.query.support.QueryBase.where add an aditional parameter to substring

### ISSUE THREAD

**Issue by ralucatemle** [querydsl/querydsl#1818]
Hi, 
Using querydsl-core-3.4.3.jar the predicate for where(where(Predicate... o)) is 
_executionSummaryEntity.branchId = EMPTY && upper(substring(executionSummaryEntity.owner,indexOf(executionSummaryEntity.owner,\))) like upper(%int%) escape '~'_

 but the query result is 

_select executionSummaryEntity
from ExecutionSummaryEntity executionSummaryEntity
where executionSummaryEntity.branchId = ?1 and upper(substring(executionSummaryEntity.owner,locate(?2,executionSummaryEntity.owner)**-2**)) like upper(?3) escape '~'_

which would be just right if it won't be for the extra -2 for the index.
How can i fix that? The owner in the db has the form domain\user and i need the like only on the \user.

Thanks a lot

**Comment by timowest** [comment]
Does the issue persist with 3.7.2?

**Comment by timowest** [comment]
Based on the PRs it appears to have been fixed already.

**Comment by ralucatemle** [comment]
Thanks for the quick response. It does not reproduce anymore in 3.7.2

**Comment by ralucatemle** [comment]
Hi again. If it is not to much can you please tell me what is the first release of querydsl-core that has this defect fixed? I've searched but could not find any document about it. Thanks a lot

**Comment by Shredder121** [comment]
I don't think we can easily find that out for you, sorry.
