### ISSUE TITLE
Wrong sql generated when using Expressions.TRUE (FALSE) for SQLServerTemplates

### ISSUE THREAD

**Issue by toughpheeckouse** [querydsl/querydsl#1824]
QueryDSL version - 4.0.7

Code to reproduce and illustrate issue:

```java
public class TrueAndFalseExpressionSQLServerTemplatesTest
{
	private Logger logger = LoggerFactory.getLogger(TrueAndFalseExpressionSQLServerTemplatesTest.class);
	
	@Test
	public void test()
	{
		QAclSid sid = QAclSid.aclSid;
		
		SQLQuery<?> query = queryFactory()
				.select(sid.all())
				.from(sid)
				.where( sid.principal.eq(Expressions.TRUE) )
				;
		
		String sql = query.getSQL().getSQL();
		
		logger.info("\n" + sql);
	}
	
	private SQLQueryFactory queryFactory()
	{
		Configuration conf = new Configuration(SQLServer2008Templates.builder().build());
		conf.setUseLiterals(true);
		
		return new SQLQueryFactory(conf, (DataSource)null);
	}
}
```

Where **sid.principal** is **BooleanPath** and **sql** is
`
select acl_sid.id, acl_sid.principal, acl_sid.sid
from acl_sid acl_sid
where acl_sid.principal = true
`

When I run this query I getting error:

Msg 207, Level 16, State 1, Line 3
Invalid column name 'true'.

Workaround is to use **Expressions.booleanTemplate("1")** instead of **Expressions.TRUE**

**Comment by timowest** [comment]
Thanks for the bug report. `pricipal.eq(true)` and `pricipal.isTrue()` should work though.

**Comment by toughpheeckouse** [comment]
Thanks for workarounds. They are work correctly.

but anyway I think it need to be fixed.

```java
		SQLQuery<?> query = queryFacotry.select(Expressions
				.cases()
						.when(
								new BooleanBuilder(entryQuery.exists())
									.or(objQuery.exists())
								)
								.then(Expressions.TRUE)
						.otherwise(Expressions.FALSE)
				);
```
In this expression I can use these workarounds.

**Comment by timowest** [comment]
Yes, definitely.

**Comment by toughpheeckouse** [comment]
Thanks @timowest.

And offtopic: have you seen these posts in google groups?
[https://groups.google.com/d/msg/querydsl/GOL7YUzP50k/ERgeYQliAgAJ](url)
and
[https://groups.google.com/d/msg/querydsl/c-5-5HQuESU/-3Ta9vXEBQAJ](url)

first one - is it bug or not?

second - what do you think about this feature? whether it will be more useful than SQLTemplatesRegistry?

**Comment by timowest** [comment]
Answered in the Querydsl Google Group
