### ISSUE TITLE
QueryDSL - HHH000104: firstResult/maxResults specified with collection fetch; applying in memory

### ISSUE THREAD

**Issue by Artgit** [querydsl/querydsl#1827]
Could you please take a look into my issue with QueryDSL and pagination http://stackoverflow.com/questions/36104471/querydsl-hhh000104-firstresult-maxresults-specified-with-collection-fetch-ap

According to "WARN  o.h.h.i.ast.QueryTranslatorImpl - HHH000104: firstResult/maxResults specified with collection fetch; applying in memory!" - pagination is applied in memory that is not completely acceptable.

How to change my configuration in order to apply pagination at database level ?

**Comment by timowest** [comment]
If you fetch collections through the same query as the top level entity limit/offset can't be applied at the SQL query level.

You will need to use a different fetch strategy for the collection or lazy loading to have limit/offset applied properly.

**Comment by timowest** [comment]
Please reopen, if you think that this should be handled differently in Querydsl.
