### ISSUE TITLE
Kotlin support

### ISSUE THREAD

**Issue by sdeleuze** [querydsl/querydsl#1828]
Kotlin is pretty popular these days, and it would be nice to have Kotlin support in Query DSL, in addition to the Scala one. It could allow me to use Query DSL SQL for the use case I have detail on https://spring.io/blog/2016/03/20/a-geospatial-messenger-with-kotlin-spring-boot-and-postgresql.

**Comment by robi42** [comment]
+1

**Comment by mackristof** [comment]
+1

**Comment by dustins** [comment]
+1

**Comment by maurofranceschini** [comment]
+1

**Comment by worwornf** [comment]
+1

**Comment by aldo-gutierrez-tierconnect-com** [comment]
+1

**Comment by Shredder121** [comment]
So, I was looking a bit, and the [reference][] is a good start, but because we are not the intended audience for that[1] we'll have to consult the [language spec][].

I unfortunately have to say that there is not much to work with here.
The language spec is not complete, which isn't that much of a problem, but since we'll integrate with the tooling we will want to depend on laid out infrastructure, not `kapt 0.1-SNAPSHOT`.

It's of course a little overkill to require Java level of detail documentation, but a bit less `TODO`s might go a long way.

We will however add support for Kotlin to Codegen, so if at one point there is more information about how to integrate nicely, we can add such an integration.

So with that in mind, I think we'll keep this issue open until that moment.


[1]:This reference is designed for you to easily learn Kotlin in a matter of hours.

[reference]: http://kotlinlang.org/docs/reference/
[language spec]: https://github.com/JetBrains/kotlin-spec/blob/master/kotlin.asc

**Comment by sdeleuze** [comment]
I will reach Kotlin team about the problems you raised and make you a feedback.

**Comment by DmRomantsov** [comment]
is there any news?

**Comment by Shredder121** [comment]
There are still some issues.

You can also join in the Kotlin Slack, @sdeleuze already [forwarded the request](https://kotlinlang.slack.com/archives/relational-sql/p1460925427000003) and they heard our request.

Unfortunately, there is still not much movement on [the spec](https://github.com/JetBrains/kotlin-spec/blob/master/kotlin.asc).

**Comment by raderio** [comment]
+1

**Comment by debop** [comment]
+1

**Comment by owahlen** [comment]
+1

**Comment by mdomasevicius** [comment]
+1

**Comment by kucharzyk** [comment]
+1

**Comment by Shredder121** [comment]
This is an upstream issue, please refrain from posting +1 comments.
You can use the new reactions to show your involvement in the issue.

N.B. it looks like they moved the specification documentation into the main kotlin repository.
https://github.com/JetBrains/kotlin/tree/master/spec-docs

**Comment by vtorosyan** [comment]
+1

**Comment by mrfint** [comment]
+1

**Comment by owahlen** [comment]
Note that with the current version of Kotlin it is now possible to generate the Q-classes with kapt.
A build.gradle has to contain the following parts:
```
...
dependencies {
    
    kapt "com.querydsl:querydsl-apt:$querydsl_version:jpa"
    kapt 'org.hibernate.javax.persistence:hibernate-jpa-2.1-api:1.0.0.Final'
    ...
    compile "com.querydsl:querydsl-jpa:$querydsl_version"
}

kapt {
    generateStubs = true
}

sourceSets {
    main.java.srcDirs += [file("$buildDir/generated/source/kapt/main")]
}
```

**Comment by sdeleuze** [comment]
You should also try the new `kotlin-kapt` plugin provided with Kotlin `1.0.6`, see https://blog.jetbrains.com/kotlin/2016/12/kotlin-1-0-6-is-here/.n Not a silver bullet yet but seems promising.

**Comment by zvozin** [comment]
https://github.com/JetBrains/kotlin-examples/tree/master/gradle/kotlin-querydsl

**Comment by Shredder121** [comment]
I'll look at it later, thanks for the link.

-------- Original message --------

**Comment by zvozin** [comment]
For your convenience, I just took it apart and rebuilt on latest Kotlin, Hibernate 5.1.8.Final and QueryDSL 3.7.4. Relevant bits of `build.gradle`: https://gist.github.com/zvozin/f46cc9fe1dd00bb648808317e77bf8ca.

**Comment by geertolaerts** [comment]
Any example on how to do it with maven. I tried to get it done, but failed miserably :(

**Comment by Adeynack** [comment]
The examples on this issue + some tweaking to be more up-to-date allowed me to make it work.
Here are the additions to my `build.gradle` file to make it work.

```groovy
buildscript {
  // ...
  ext {
    queryDslVersion = '4.1.3'
  }
}

// ...

apply plugin: 'idea'
apply plugin: 'kotlin-kapt'

dependencies {
    compile "com.querydsl:querydsl-jpa:$queryDslVersion"
    kapt "com.querydsl:querydsl-apt:$queryDslVersion:jpa"
}
idea {
    module {
        def kaptMain = file('build/generated/source/kapt/main')
        sourceDirs += kaptMain
        generatedSourceDirs += kaptMain
    }
}
```

**Comment by nhajratw** [comment]
FWIW, building off @Adeynack -- here's what I did to get it working fine with command line & intellij

```gradle
plugins {
// ...
    id "org.jetbrains.kotlin.kapt" version "1.2.70"
}

// ...
dependencies {
    compile "com.querydsl:querydsl-jpa:4.2.1"
    kapt "com.querydsl:querydsl-apt:4.2.1:jpa"
}
```
I didn't need the additional `idea` section

**Comment by zzlhr** [comment]
How to configure maven, my project can compile if the service layer does not create QModel, but can't compile when the service layer creates QModel

**Comment by deviant-studio** [comment]
Doesn't work with Kotlin 1.3
Every time i'm trying to build the project i get:
```
Caused by: java.lang.UnsupportedOperationException: no descriptor for type constructor of TypeVariable(R)?
    at org.jetbrains.kotlin.load.kotlin.TypeSignatureMappingKt.mapType(typeSignatureMapping.kt:89)
    at org.jetbrains.kotlin.codegen.state.KotlinTypeMapper.mapType(KotlinTypeMapper.java:502)
    at org.jetbrains.kotlin.codegen.state.KotlinTypeMapper.mapType(KotlinTypeMapper.java:456)
    at org.jetbrains.kotlin.codegen.CodegenUtilKt.asmType(codegenUtil.kt:274)
    at org.jetbrains.kotlin.codegen.CodegenUtilKt.asmType(codegenUtil.kt:277)
    at org.jetbrains.kotlin.codegen.ExpressionCodegen.expressionType(ExpressionCodegen.java:459)
    at org.jetbrains.kotlin.codegen.ExpressionCodegen.visitSafeQualifiedExpression(ExpressionCodegen.java:3159)
    at org.jetbrains.kotlin.codegen.ExpressionCodegen.visitSafeQualifiedExpression(ExpressionCodegen.java:108)
    at org.jetbrains.kotlin.psi.KtSafeQualifiedExpression.accept(KtSafeQualifiedExpression.kt:23)
    at org.jetbrains.kotlin.codegen.CodegenStatementVisitor.visitKtElement(CodegenStatementVisitor.java:31)
    at org.jetbrains.kotlin.codegen.CodegenStatementVisitor.visitKtElement(CodegenStatementVisitor.java:22)
    at org.jetbrains.kotlin.psi.KtVisitor.visitExpression(KtVisitor.java:182)
    at org.jetbrains.kotlin.psi.KtVisitor.visitQualifiedExpression(KtVisitor.java:286)
    at org.jetbrains.kotlin.psi.KtVisitor.visitSafeQualifiedExpression(KtVisitor.java:306)
    at org.jetbrains.kotlin.psi.KtSafeQualifiedExpression.accept(KtSafeQualifiedExpression.kt:23)
    at org.jetbrains.kotlin.codegen.ExpressionCodegen.genQualified(ExpressionCodegen.java:296)
    ... 103 more
```

**Comment by nhajratw** [comment]
@deviant-studio fyi -- my solution above is still working with kotlin 1.3

**Comment by soprater** [comment]
> @deviant-studio fyi -- my solution above is still working with kotlin 1.3

@nhajratw I tried the following:

```
plugins {
// ...
    kotlin("kapt") version "1.3.61"
}
dependencies {
// ...
    implementation("com.querydsl:querydsl-jpa:4.2.2")
    kapt("com.querydsl:querydsl-apt:4.2.2:jpa")
}
```
Unfortunately I get a `ClassNotFoundException` where it says `Did not find a query class ...QClass`. It seems that the classes are not generated.
Do you know a fix to this issue?

**Comment by nhajratw** [comment]
@soprater sorry, i'm no longer working on the project where i had implemented this. Last i knew, it was working still. If i recall, you have to run the `kaptGenerateStubsKotlin` task in order to get the `XXXQClass` files.

**Comment by weitjong** [comment]
It is still working. Kotlin 1.3.61, Spring 2.2.5.RELEASE, querydsl 4.2.2. I have these:
```
    implementation("com.querydsl:querydsl-apt")
    implementation("com.querydsl:querydsl-jpa")
```

**Comment by F43nd1r** [comment]
I've built a [module](https://github.com/F43nd1r/querydsl/tree/kotlin) to support emitting kotlin Qclasses. If there's interest I could upstream that.

**Comment by jwgmeligmeyling** [comment]
I'd be interested in merging it upstream @F43nd1r .

Just to be clear: the intent of this feature is to generate QClasses in Kotlin right?

Because the current APT code generation works with Kotlin just fine, through Kapt. There is even a working example for it 😄 So QueryDSL "supports" Kotlin just fine.

**Comment by F43nd1r** [comment]
Hi @jwgmeligmeyling. It has been a while since I worked on that fork. Yes, the intent is to generate kotlin QClasses. 
I think I needed them because I had another tool which didn't work well with mixed sources. 

Let me know how I can help.

**Comment by jwgmeligmeyling** [comment]
Ah I'll see your changes are already available in https://github.com/querydsl/querydsl/compare/master...F43nd1r:kotlin?expand=1 .

I'll update them as soon as I get to it. I am first working on getting the 5.x release out.

**Comment by hameno** [comment]
I'm trying to figure out how to use the new Kotlin support but cannot seem to find any documentation for this. Are there any examples/docs that I'm not seeing?
https://querydsl.com/static/querydsl/5.0.0/reference/html_single/ has no mention of Kotlin

**Comment by spyro2000** [comment]
Is there any documentation about how to get this to run with gradle?

**Comment by nhajratw** [comment]
@spyro2000 there are a few comments in the thread above (including mine) that have examples for gradle. That was a few years ago, so not sure if they still work, but probably a good starting point. Good luck!

**Comment by spyro2000** [comment]
Phew, ok. Thank you anyway :)

**Comment by amruthakm98** [comment]
Adding the following bits worked for me:

```
apply plugin: 'idea'
apply plugin: 'kotlin'
apply plugin: 'kotlin-jpa'
apply plugin: `'kotlin-kapt'

dependencies {
....

    implementation "com.querydsl:querydsl-jpa:5.0.0"
    kapt "com.querydsl:querydsl-apt:5.0.0:jpa"
}

idea {
    module {
        def kaptMain = file('build/generated/source/kapt/main')
        sourceDirs += kaptMain
        generatedSourceDirs += kaptMain
    }
}

kapt {
	generateStubs = true
}
```

**Comment by amruthakm98** [comment]
Adding the following bits worked for me:

apply plugin: 'idea'
apply plugin: 'kotlin'
apply plugin: 'kotlin-jpa'
apply plugin: 'kotlin-kapt'

dependencies {
    //...
    implementation "com.querydsl:querydsl-jpa:5.0.0"
    kapt "com.querydsl:querydsl-apt:5.0.0:jpa"
}

idea {
    module {
        def kaptMain = file('build/generated/source/kapt/main')
        sourceDirs += kaptMain
        generatedSourceDirs += kaptMain
    }
}

kapt {
	generateStubs = true
}

**Comment by amruthakm98** [comment]
Adding the following bits worked for me:

```
apply plugin: 'idea'
apply plugin: 'kotlin'
apply plugin: 'kotlin-jpa'
apply plugin: 'kotlin-kapt'

dependencies {
    //...
    implementation "com.querydsl:querydsl-jpa:5.0.0"
    kapt "com.querydsl:querydsl-apt:5.0.0:jpa"
}

idea {
    module {
        def kaptMain = file('build/generated/source/kapt/main')
        sourceDirs += kaptMain
        generatedSourceDirs += kaptMain
    }
}

kapt {
	generateStubs = true
}
```

**Comment by amruthakm98** [comment]
Adding the following bits to build.gradle worked for me:

```
apply plugin: 'idea'
apply plugin: 'kotlin'
apply plugin: 'kotlin-jpa'
apply plugin: 'kotlin-kapt'

dependencies {
    //...
    implementation "com.querydsl:querydsl-jpa:5.0.0"
    kapt "com.querydsl:querydsl-apt:5.0.0:jpa"
}

idea {
    module {
        def kaptMain = file('build/generated/source/kapt/main')
        sourceDirs += kaptMain
        generatedSourceDirs += kaptMain
    }
}

kapt {
	generateStubs = true
}
```

**Comment by spyro2000** [comment]
@amruthakm98,

thank you! I wonder if this could be added to the documentation. 

(for the authors of QueryDSL):

Please note that kapt is in 'maintenance mode' (maybe because it's awfully slow, like apt). Instead they want everone to use the more modern Kotlin Symbol Processing API https://kotlinlang.org/docs/ksp-overview.html

**Comment by jwgmeligmeyling** [comment]
Well, Querydsl is an APT plugin and Kotlin supports APT plugins through KAPT. Using KAPT for APT plugins is pretty well documented within Kotlins own resources. Its a matter of who documents what 🤷🏻 

But I believe there has been a Kotlin specific codegen module contributed to the project. It might be what you're looking for.

**Comment by F43nd1r** [comment]
> But I believe there has been a Kotlin specific codegen module contributed to the project. It might be what you're looking for.

Yeah I contributed that. But:
The module generates kotlin code instead of java. It changes nothing about how to call the code generator. Implementing an optional ksp layer next to apt would be a massive undertaking.
