### ISSUE TITLE
JPAExpressions in select in 4.0.x

### ISSUE THREAD

**Issue by Knoxvillekm** [querydsl/querydsl#1830]
How to use JPAExpressions (not real code just example)?
query.from(group).list(Projection.bean(Group.class, group.id,
    JPAExpressions.from(item).where(item.group.eq(group)).count().as("count")
))

this work in 3.6.9
query.from(group).list(Projection.bean(Group.class, group.id,
    new JPASubQuery().from(item).where(item.group.eq(group)).count().as("count")
))

**Comment by timowest** [comment]
I don't think this will work in any version, since subqueries are allowed only in the where part, but the following Querydsl 3 snippet
```
new JPASubQuery().from(item).where(item.group.eq(group)).count().as("count")
```
is equivalent to
```
JPAExpressions.select(item.count()).from(item).where(item.group.eq(group)).as("group")
```

**Comment by Knoxvillekm** [comment]
I can't use .as("") or .count() for JPAExpressions. But this work for new JPASubQuery() in 3.6.9.

**Comment by Shredder121** [comment]
What is happening then?
It's not quite clear from your comment.

**Comment by Knoxvillekm** [comment]
```
QGoods goods = QGoods.goods;
QGroup group = QGroup.group;
query.from(group).list(Projection.bean(Group.class, 
  group.id,
  group,name,
  new JPASubQuery().from(goods).where(goods.group.eq(group)).count().as("count")
));
```

generate SQL:
```
SELECT 
  gr.id as id, 
  gr.name as name, 
  (SELECT count(*)  FROM Goods g WHERE g.group_id = gr.id) as count 
FROM Group gr
```

**Comment by Shredder121** [comment]
[There is no way to express that in JPQL](https://en.wikibooks.org/wiki/Java_Persistence/JPQL_BNF#Select_Clause). It's surprising that the Hibernate parser doesn't block such usage.
The select clause should only contain `single_valued_path_expression | aggregate_expression | identification_variable | OBJECT(identification_variable) | constructor_expression`
Subqueries can only be used in HAVING and WHERE clauses, as was said earlier.

**Comment by e1nath** [comment]
For me, it was possible like this:
`SubQueryExpression<Long> subQ=JPAExpressions.select(item.group.count()).from(item).where(item.group.eq(group));
		Expression<Long> subCount = Expressions.as(subQ, "count");		
		query.from(group).list(Projection.bean(Group.class, group.id,subCount))`

**Comment by lingdle-ceo** [comment]
> 对我来说，可能是这样的：
> `SubQueryExpression<Long> subQ=JPAExpressions.select(item.group.count()).from(item).where(item.group.eq(group)); Expression<Long> subCount = Expressions.as(subQ, "count"); query.from(group).list(Projection.bean(Group.class, group.id,subCount))`

For me，this is work
