### ISSUE TITLE
Inconsistent IN clause construction

### ISSUE THREAD

**Issue by holgerstolzenberg** [querydsl/querydsl#1831]
Imagine the following simple query, running against a Oracle 12g:

```java
Set<Long> foreignIds = …

final List<Long> foundIds = new JPAQuery<>(entityManager)
        .select(transaction.txId)
        .from(transaction)
        .where(transaction.txId.in(foreignIds))
        .fetch();
```

Everything works like expected, but in case `foreignIds` is `null` or empty, the following query is rendered:

```sql
SELECT t.txId FROM transaction t WHERE (1 = 2)
```

The special part here is that the `IN` clause is left away and a **always false** condition is appended. This is also fine for the moment. In general there is also an logical problem to execute a query with a known empty IN clause, but that is not the matter here.

The problem arises in the first place when `foreignIds.size() > 1000` as Oracle cannot handle more than a thousand IN clause entries per default. Our solution looks as follows:

```java
final List<Long> foundIds = new JPAQuery<>(entityManager)
        .select(transaction.txId)
        .from(transaction)
        .where(in(transaction.txId, foreignIds))
        .fetch();

public static <T> BooleanBuilder in(@Nonnull final SimpleExpression<T> path,
      @Nonnull final Collection<T> inConditions) {
    checkNotNull(path);
    checkNotNull(inConditions);
    
    // We initially forgot that check
    // checkState(!inConditions.isEmpty(), "Cannot construct an IN clause from an empty collection.");

    final BooleanBuilder boolBuilder = new BooleanBuilder();
    for (final List<T> subList : partition(newArrayList(inConditions),
        MAX_EXPRESSIONS_OF_IN_CLAUSE)) {
      boolBuilder.or(path.in(subList));
    }

    return boolBuilder;
  }
```

Using this works but the ugly happens if the set is empty or null, because Querydsl completely omits any WHERE or IN condition which result in:

```sql
SELECT t.txId FROM transaction t
DELETE FROM transaction
```

The problem here is that you have **always true** conditions now, so everything is selected or deleted.

I am not sure if this is a bug of Querydsl but I think the `IN` clause condition rendering should be consistent.

**Comment by holgerstolzenberg** [comment]
We misanalysed the problem, in the end it is not a problem with Querydsl in the `IN` clause construction but with the call to `partition(newArrayList(inConditions)` the causes the `for` loop not to execute at all.

Will close this issue.

**Comment by Shredder121** [comment]
Scary result, but glad that it wasn't the fault of Querydsl.
