### ISSUE TITLE
Open up MongodbSerializer for extension on creating keys.

### ISSUE THREAD

**Issue by christophstrobl** [querydsl/querydsl#1832]
Currently one has no access on meta data exposed via `Operation` when creating the key via `asDBObject`. The information would be useful for mapping non native types (eg. annotated ones used as dbrefs).

Opening up `String asDBKey(Operation<?> expr, int index)` would allow implementations to handle keys for certain objects more efficiently.

Please see: [DATAMONGO-1394](https://jira.spring.io/browse/DATAMONGO-1394) and this workaround [spring-data-mongodb/issue/DATAMONGO-1394](https://github.com/spring-projects/spring-data-mongodb/compare/issue/DATAMONGO-1394) for more details.

**Comment by timowest** [comment]
So you are suggesting to make them protected? That can be done.

There are also two template methods in MongodbSerializer that should be implemented:
* DBRef asReferenceKey(Class<?> entity, Object id)
* boolean isId(Path<?> arg)

**Comment by christophstrobl** [comment]
yes making those protected would help. thanks!

**Comment by timowest** [comment]
@christophstrobl Make sure to implement also isId(Path). Here is the Morphia version https://github.com/querydsl/querydsl/blob/master/querydsl-mongodb/src/main/java/com/querydsl/mongodb/morphia/MorphiaSerializer.java
