### ISSUE TITLE
MySql REGEXP

### ISSUE THREAD

**Issue by igler** [querydsl/querydsl#1845]
Trying to achieve the following result with QueryDSL:

<pre><code>select id, identifier
from eip_transportcode_message
order by
  case
	when identifier REGEXP '^[[:digit:]]+$'
	  then cast(identifier as signed)
	  else identifier end, 
  LENGTH(identifier) ASC;
</code></pre>

Tried the following code:<pre><code>PathBuilder path = new PathBuilder(TransportCode.class, "transportCode");
StringPath regexPath = Expressions.stringPath("REGEXP '^[[:digit:]]+$'");
StringPath property = orderByExpression.getString(o.getProperty());
Expression identifierTarget = path
		.when(regexPath)
		.then(property.castToNum(Integer.class))
		.otherwise(property);
</code></pre>

The outcome is:<pre><code>order by case when transportCode = REGEXP '^[[:digit:]]+$' then cast(transportCode.identifier as integer) else...</code></pre>

The Problem is the "=" in front of REGEXP and the missing "transportCode.identifier".

**Comment by johnktims** [comment]
We use github issues for bug reports. Please post questions like this on StackOverflow or in the google group.
