### ISSUE TITLE
ERROR: for SELECT DISTINCT, ORDER BY expressions must appear in select list

### ISSUE THREAD

**Issue by ice-pro** [querydsl/querydsl#1846]
The following code:
```java
JPAQuery query = new JPAQuery(em);
query.distinct();
query.from(QPlayer.player);
query.orderBy(new OrderSpecifier(Order.ASC, QPlayer.player.team.id));
query.list(QPlayer.player, QPlayer.player.team.id);
```

generates wrong JPQL:
```sql
SELECT DISTINCT player,
                player.team.id
FROM Player player
LEFT JOIN player.team AS player_team
ORDER BY player_team.id ASC
```
In code we are using the same expression `QPlayer.player.team.id` two times: in [order by] and [select] sections. But the resulting query has different expressions:
- in [select] section we have `player.team.id`
- but in [order by] it is collapsed and looks differently: `player_team.id`

Wrong JPQL leads to wrong SQL:
```sql
SELECT DISTINCT player0_.team_id AS col_0_0_,
                player0_.id AS col_1_0_,
                ...
FROM Player player0_
LEFT OUTER JOIN Team team1_ ON player0_.team_id=team1_.id
ORDER BY team1_.id ASC
```
And this query cannot be executed due to error

> ERROR: for SELECT DISTINCT, ORDER BY expressions must appear in select list

_We are using QueryDSL **v.3.6.8**_

**Comment by ice-pro** [comment]
Hello,

Can you please define when this fix can be delivered?

**Comment by Shredder121** [comment]
We've had some holdups.
Probably at the end of this week.
Sorry for the wait.

**Comment by ice-pro** [comment]
Good, thank you!

**Comment by ice-pro** [comment]
Guys, do you have a plane to fix this problem in 3.x branch as well?

**Comment by Shredder121** [comment]
Yeah, we intend to do that, a backport PR was already linked #1850 but there is still an outstanding issue.
Sorry for the wait.
