### ISSUE TITLE
Error using Projections in QueryDSL in Queries with Join

### ISSUE THREAD

**Issue by luiscamposjr** [querydsl/querydsl#1849]
I have a problem coding my query with Query DSL.

A have two classes:

```
public class Federacao extends AbstractEntity{


private static final long serialVersionUID = 9025004657033297345L;

private String sigla;
private String uf;
private String nome;    

@OneToMany(mappedBy="federacao")
private Set<Clube> clubes;

...
```
and

```
public class Clube extends AbstractEntity{

private static final long serialVersionUID = 8120377000459073106L;


private String nome;
private String responsavel;
private String email;
private boolean ativo;
private String cnpj;

@ManyToOne
@JoinColumn(name="id_federacao", nullable=false)
private Federacao federacao;
...
```

In my ClubeRepository I'm doing this:

```
@Override
public List<Clube> findAll(FilterClubeDTO filterClubeDTO) {

    JPAQuery query = new JPAQuery(em);
    Predicate predicate = filterPredicate(filterClubeDTO);

    return query.from(qClube)
        .innerJoin(qClube.federacao, qFederacao)
        .where(predicate)
        .orderBy(qClube.id.desc())
        .list(Projections.fields(qClube, qClube.id, qClube.nome, qClube.ativo, qClube.cnpj, qClube.email, qClube.responsavel, 
              Projections.fields(Federacao.class, qClube.federacao.sigla).as("federacao")));
}
```
I don't have problem with this but I'm trying to project Federacao.id as well and I have a exception when I'm doing it. I'd like to know a way to make projections to populate my "Federacao"entity that is in my Clube entity.

When I use Projection.beans I have an excepetion also because QueryDSL don't see the ID on the superclass. With fields it's works out but in both situations I don't have successful when I try to populate my "Federacao" entity.

Is possible to see my all code in my github.

https://github.com/luiscamposjr/cbfm-spring-angular/tree/master/cbfm-web

**Comment by Shredder121** [comment]
Hi, for what reason did you close this?
Sorry for not replying sooner.

**Comment by luiscamposjr** [comment]
Hi @Shredder121

**Comment by luiscamposjr** [comment]
Hi @Shredder121 I closed because I resolved with a friend of mine.

I'm sorry. Of course is better to share here the solution and close this issue. I'll post here the solution. 

Thank you.

**Comment by Shredder121** [comment]
Oh, that's fine.
Yes, that would be helpful.

**Comment by luiscamposjr** [comment]
What I was trying to do is populate de entity "Federacao" completely. The solution is quite simple. 

We just have to project all fields in the same projection to "Federacao":


```
	@Override
	public List<Clube> findAll(FilterClubeDTO filterClubeDTO) {
		
		JPAQuery query = new JPAQuery(em);
		Predicate predicate = filterPredicate(filterClubeDTO);
		
 		return query.from(qClube)
 			.innerJoin(qClube.federacao, qFederacao)
 			.where(predicate)
			.orderBy(qClube.id.desc())
			.list(Projections.fields(qClube, qClube.id, qClube.nome, qClube.ativo, qClube.cnpj, qClube.email, qClube.responsavel, 
				  Projections.fields(qFederacao, qClube.federacao.id, qClube.federacao.sigla).as("federacao")));
	}
```

**Comment by timowest** [comment]
@luiscamposjr Could you elaborate on your issue with Projections.bean? Super class accessors are not taken into account?

**Comment by luiscamposjr** [comment]
Hi @timowest 

Yes, If, for example, I use Projections.beans instead of Projections.fields, when I try to project qClube.id, I have an exception because can't access  the ID property, that is mapped on superclass. I don't know why.

**Comment by timowest** [comment]
Does the id property have a public setter on the superclass or only the field?

**Comment by luiscamposjr** [comment]
Yes @timowest 
You're completely right. My id was protected. I changed do public

Now I'm using Projections.bean correctly.

Thank you =)
