### ISSUE TITLE
Search by null with querydsl

### ISSUE THREAD

**Issue by futurechan** [querydsl/querydsl#1853]
I have a controller method for searching like so
```java
@RequestMapping(method = RequestMethod.GET)
public Page<MyEntity> find(@QuerydslPredicate(root = MyEntity.class)
                                     Predicate predicate,
                         Pageable pageable) {

    return this.myEntityRepository.findAll(predicate, pageable);
}
```
It works great. I can issue a `GET` request with various query string parameters, and it filters accordingly, but now I want to search by null. I tried doing something like `/myentity?myParam1=&`, but the `predicate` argument is always `null`.

How can I search where specific fields are null?

I also posted this on [SO](http://stackoverflow.com/questions/36727681/search-by-null-with-querydsl).

**Comment by timowest** [comment]
This seems to be Spring Data related. Could you post this question on their support forum? I don't know how to fix it.
