### ISSUE TITLE
limit in JPA subqueries

### ISSUE THREAD

**Issue by may-bee** [querydsl/querydsl#1854]
While searching for limiting JPA subqueries, I found issue #421.
However, I am currently using QueryDSL 4.1.0 and there is UnsupportedOperationException anymore.
Has it been removed by intention or due I observe a regression bug?

**Comment by timowest** [comment]
There is no distinction between query and subquery types anymore in Querydsl 4, that's why this has changed.

**Comment by may-bee** [comment]
Ah ok. Thanks.

**Comment by benallard** [comment]
Just ran into this as well ... Way too much hours of debugging later (in my opinion) I finally discover that github issue. Any way to make the error easier to spot ?
