### ISSUE TITLE
Disable inverse foreign keys in maven

### ISSUE THREAD

**Issue by natros** [querydsl/querydsl#1857]
Hello, 

I'm using querydsl sql with an oracle database (11gR2) and one thing I noticed, that does not happen with other databases, is that the code generation with inverse foreign keys takes a long time (several minutes). This is a known issue with oracle (google: "oracle slow slow getExportedKeys").

As an experiment I commented the code that collects the inverse foreign keys and the time reduced dramatically. 

Most of the time I do not use the inverse foreign keys. Is it possible to create a flag for maven plugin to not generate the inverse foreign keys?

**Comment by timowest** [comment]
exportForeignKeys to skip the foreign key export is already available. What kind of changes to you suggest to the configuration options: http://www.querydsl.com/static/querydsl/4.0.9/reference/html_single/#d0e716

**Comment by natros** [comment]
I know about exportForeignKeys. But I don't want to disable all foreign keys. 

I was referring to this
https://github.com/querydsl/querydsl/blob/master/querydsl-sql-codegen/src/main/java/com/querydsl/sql/codegen/MetaDataExporter.java#L362

**Comment by timowest** [comment]
Shall I add exportInverseForeignKeys as a boolean property?

**Comment by Shredder121** [comment]
To me that sounds good at least.

**Comment by natros** [comment]
Yes please.

**Comment by lanzlg** [comment]
is it also usable via the maven pluging cause there is only 3.7.4 available? Or is ther a trick somehow to use  a newer version width the plugin
