### ISSUE TITLE
Count a view generates exception

### ISSUE THREAD

**Issue by pedrofar** [querydsl/querydsl#1860]
When I'm trying to do a count() in a view, the exception java.lang.IllegalStateException is thrown, showing the message "No count expression can be created".

This exception was threw by com.querydsl.sql.RelationalPathBase class, method count().

I think the reason is that during the export of the view, a primary key isn't generated.

I'm using querydsl v4.0.9 and PostgreSQL v9.5.2.

**Comment by pedrofar** [comment]
To resolve, was needed to put by hand the primary key in the generated code of the view.

**Comment by timowest** [comment]
A think a view doesn't define any primary key, but you can alternatively also count via view.pkColumn.count().

What kind of fix would you suggest?
