### ISSUE TITLE
Doubts on Projection

### ISSUE THREAD

**Issue by pradhakrishnan** [querydsl/querydsl#1863]
Hi,

I have one doubt on using projection at onetomany relationship.

For e.g User.java

```
public class User{

private int userId;
private String username;
private String password;
private List<Address> addresses;

}

And Address.java
public class Address{

private int addressId;
private int doorNo;
private String streetname;

}

I want to return only doorNo from Address Object . Not sure how to add that in projections

List<User> users = userRestRepository.findAll(
                    Projections.bean(User.class, qUser.address),
                    userPredicate, pageRequest).getContent();

Can someone help me

Thanks
Pranesh

**Comment by timowest** [comment]
How does the findAll signature look like? Is this Spring Data?

**Comment by timowest** [comment]
Using `Projections.bean(Address.class, qAddress.doorNo)` you get a bean with only doorNo populated, but I don't know how it fits in here.

**Comment by pradhakrishnan** [comment]
Yes that is spring data jpa. Here is my repository interface

public interface UserRestRepository extends CustomQueryDslJpaRepository<User, Long>{
}

And this is finAll signature
Page<T> findAll(FactoryExpression<T> factoryExpression, Predicate predicate, Pageable pageable);

**Comment by timowest** [comment]
What you are requesting is not possible through the findAll signature. You need to write an explicit Query since and aggregate the results.
