### ISSUE TITLE
Weird SQL generation for QueryDSL Update

### ISSUE THREAD

**Issue by wind57** [querydsl/querydsl#1867]
Here is the case we are facing at the moment, having a simple JPAUpdateQuery, like this :

```
JPAUpdateClause update = builder.buildUpdate(interventionOffers); // this is an Entity
        return update.where(interventionOffers.intervention.id.eq(interventionId).and(interventionOffers.offerStatus.eq(OfferStatusEnum.NOTIFIED))) // offerStatus is an enum
                .set(interventionOffers.offerStatus, OfferStatusEnum.CANCELLED)
                .execute();
```

here is the query that is generated :

```
Hibernate: update intervention_offers set offer_status=?, offer_status=?, offer_status=?, offer_status=? where intervention_id=? and offer_status=? and intervention_id=? and offer_status=? and intervention_id=? and offer_status=? and intervention_id=? and offer_status=?
```

QueryDSL version : 3.7.2

Thx,
Eugene.

**Comment by Shredder121** [comment]
Could you maybe elaborate on what the _exact_ issue is?

**Comment by wind57** [comment]
besides this one? 

```
set offer_status=?, offer_status=?, offer_status=?, offer_status=?
```

**Comment by Shredder121** [comment]
Thanks.
Could you also log what Querydsl generates? (The JPQL)

**Comment by Shredder121** [comment]
And what is `builder.buildUpdate`?

**Comment by wind57** [comment]
builder.buildUpdate it nothing more then a small utility that does this:

```
return new JPAUpdateClause(entityManager, entityPath);
```

I would gladly provide the generation of JPQL if I knew how to do it. :)

**Comment by Shredder121** [comment]
You could print the `.toString()` of the `JPAUpdateClause`.
Or you could debug and break on this line in `JPAUpdateClause`:
`entityManager.createQuery(serializer.toString())`

Then you could also compare the generated query and the query that Hibernate made.

**Comment by Shredder121** [comment]
Are you sure that you didn't hit those methods while debugging?
Both the `set` clause and `where` clause have exactly 4 times the same content.
Could you maybe prepare a reproduction project?

**Comment by wind57** [comment]
You are right... My bad. You can totally close this one, sorry for the noise

**Comment by Shredder121** [comment]
Ah, that's okay.
Anyway, thanks for opening the issue.
