### ISSUE TITLE
PathBuilder is not threadsafe

### ISSUE THREAD

**Issue by robertandrewbain** [querydsl/querydsl#1869]
`private final Map<String, PathBuilder<?>> properties = Maps.newHashMap()` and `private final Map<Path<?>, Object> propertyMetadata = Maps.newHashMap()` should be `ConcurrentHashMap`s.

Furthermore, the check in `public <A> PathBuilder<A> get(String property, Class<A> type)`, `|| !type.isAssignableFrom(path.getType())` should be removed, as it does not make sense to overwrite existing values.

I believe all the superclass implementations to be thread safe.

**Comment by Shredder121** [comment]
I _think_ we'll then at least also need a few test cases on what would need to happen if first you `.get("property")` and somewhere later you `.getString("property")` or something specific.
At least, we'll see.
