### ISSUE TITLE
jpa collection criteria

### ISSUE THREAD

**Issue by hkaito** [querydsl/querydsl#1875]
hai all, 
i'm using Querydsl 3.7.2 + JPA and have an entities like this

> 
> class Order {
>  Long id;
>  List<Item> items;
> }
> 
> class Item {
>  Order order;
>  String name;
>  Date expiredDate;
> }

by doing this

> QOrder order = QOrder.order;
> QItem item = order.items.any();
> item.name.eq("sku-12").and(item.expiredDate.isNull());

i expect it translated into something like this :

> SELECT * FROM tbl_order JOIN tbl_item
> ON tbl_order.`id` = tbl_item.`order_id` 
> AND tbl_item.`name`="sku-12" AND tbl_item.expiredDate is null;

however it translated into something this

> SELECT * FROM tbl_order WHERE 
> (exists (select 1 from tbl_item where tbl_order.id=tbl_item.order_id and (tbl_item.name)="sku-12") )
> and 
> (exists (select 1 from tbl_item where tbl_order.id=tbl_item.order_id and tbl_item.expiredDate IS NULL)) 

which return wrong result..

am i doing wrong ? if so, how to create the correct predicate for that ?
please advice, thanks

**Comment by Shredder121** [comment]
What is the rest of the query?
Could you maybe post the JPQL that we generate also?

**Comment by hkaito** [comment]
hai, thanks for your response.
here is the log

> 2016-05-10 09:10:42,262 DEBUG [main][com.mysema.query.jpa.impl.JPAQuery] 
> select order1 from Order order1 where order1.id = ?1 
> and 
> (exists (select 1 from order1.items as order1_items_67b99 where order1_items_67b99.name = ?2) 
> and 
> exists (select 1 from order1.items as order1_items_3e1e7 where order1_items s_3e1e7.expiredDate is null))

**Comment by hkaito** [comment]
sorry, 
i found the problem, and its not the issue..
as it already asked, and answered clearly by timo [here](http://stackoverflow.com/a/21638881)

thanks
