### ISSUE TITLE
direct cast in SQL query

### ISSUE THREAD

**Issue by BlackBacker** [querydsl/querydsl#1876]
Hello, I had a problem with typing "where part" query and I noticed that there is no way to cast some part of SQL query. DB - postgresql

Example:  - user anniversary >
`.where(USER.validFrom.year().subtract(LocalDate.now().getYear()).mod(5).eq(0))`
it will generate 
`MOD( EXTRACT( year from timestamp '1.1.2011' ) - 2016, 5) = 0`
but function `EXTRACT `return `DOUBLE `(every time) which I cant cast to Integer (in SQL) and it throw SQL syntax error (`function mod(double, int) doesnt exists`)

right it would be something like that >
`.where(USER.validFrom.year().sqlCast(Integer.class).subtract(LocalDate.now()).mod(5).eq(0))`
which could generate
```
MOD( EXTRACT( year from timestamp '1.1.2011' )::int - 2016, 5) = 0     OR
MOD( CAST( EXTRACT( year from timestamp '1.1.2011' ) AS integer) - 2016, 5) = 0
```

this would be great :)

**Comment by Shredder121** [comment]
There is a method `.castToNum`, but that does a short path if the type is already the desired type.
Could you try `.castToNum(Long.class).castToNum(Integer.class)`?

@timowest why was the short path introduced?

**Comment by BlackBacker** [comment]
Doesn'twork, tried both and also `.intValue()` nothing work.
```
.where(USER.validFrom.year().castToNum(Integer.class).subtract(LocalDate.now()).mod(5).eq(0))
.where(USER.validFrom.year().castToNum(Long.class).subtract(LocalDate.now()).mod(5).eq(0))
.where(USER.validFrom.year().intValue().subtract(LocalDate.now()).mod(5).eq(0))
```
also after subtract doesn't work

**Comment by Shredder121** [comment]
What do you mean both?
I want you to try to go to Long and back to Integer.

But I'll see if I can fix the issue.

**Comment by Shredder121** [comment]
Could you maybe post the java code that creates the query?
Your query doesn't compile for me, and subtracting a date and a number seems strange.

As for the workaround, for me it works.

**Comment by BlackBacker** [comment]
I didnt try `.castToNum(Long.class).castToNum(Integer.class)` at the same time.. I will try it tomorrow at work, and I will also send you code. Thank you very much :+1:

**Comment by Shredder121** [comment]
That is fine.
And no problem!

**Comment by BlackBacker** [comment]
Trank you, your "workaround" is working. 

```
LocalDate onDate = LocalDate().now();
Integer anniversaryYears = 5;

JPAQuery<UserDO> q = new JPAQuery<>(em);
q.select(Q_USER).from(Q_USER)
  .where(Q_USER.validFrom.year().subtract(onDate.getYear()).ne(0))
  .where(Q_USER.validFrom.month().subtract(onDate.getMonthOfYear()).eq(0))
  .where(Q_USER.validFrom.dayOfMonth().subtract(onDate.getDayOfMonth()).eq(0))
  .where(Q_USER.validTo.goe(onDate))
  .where(
      Q_USER.validFrom.year().castToNum(Long.class).castToNum(Integer.class)
      .subtract(onDate.getYear()).mod(anniversaryYears).eq(0)
   );
List peopleWithAnniversary = q.fetch();
```

(sorry I miss `.getMonthOfYear()` from `LocalDate.now()` at substraction)

**Comment by Shredder121** [comment]
Then at least that is sorted.
I can reproduce it, so I'll fix the underlying issue.
