### ISSUE TITLE
Grouping by formatted DateTimePath not grouping by Year and month

### ISSUE THREAD

**Issue by rmordillo-witbooking** [querydsl/querydsl#1884]
Hello,
My name is Raul and this is my first issue reported.

I am developing and API project and one of the endpoints is delivering data grouped by YYYY-MM-DD.

This is the field in my entity class:

`@Convert(converter = LocalDateTimeAttributeConverter.class)
   private LocalDateTime bookingDate;`

This is how I format the DateTimePath : 
`StringExpression datePath = formatDate(reportsBooking.bookingDate, "%Y%m");`

```
private StringExpression formatDate(Expression<?> date, String datePattern) {
      return Expressions.stringTemplate("DATE_FORMAT({0},'{1s}')", date, ConstantImpl.create(datePattern));
   }
```

And this is how I build the query : 

```
query
              .list(Projections.bean(BookingReportResponseDTO.class
                      , datePath.as("period")
                      , reportsBooking.hotelTicker
                      , reportsBooking.groupName.as("group")
                      , reportsBooking.partner
                      , reportsBooking.nights.avg().as("avgStay")
                      , reportsBooking.advance.avg().as("avgAdvance")
                      , reportsBooking.id.count().as("bookings")
                      , reportsBooking.amount.sum().as("totalAmount")
                      , reportsBooking.amount.avg().as("avgAmount")
                      , reportsBooking.nights.multiply(reportsBooking.rooms).sum().as("totalRoomsPerNight")
                      , reportsBooking.amount.multiply(reportsBooking.nights.multiply(reportsBooking.rooms)).avg().as("avgAmountRoomPerNight")
                      , reportsBooking.amount.multiply(reportsBooking.capacity.multiply(reportsBooking.nights)).avg().as("avgAmountPaxNight")
                      , reportsBooking.currency
              ));
```

The result query working on the db showing results : 

```
select date_format(bookingDate, '%Y%m') 
, hotelTicker
, groupName 
, partner 
, avg(nights) 
, avg(advance) 
, count(id) 
, sum(amount)
, avg(amount) 
, sum(nights*rooms)
, avg(amount*nights*rooms) 
, avg(amount*capacity*nights)
, currency  
from booking 
 group by date_format(bookingDate, '%Y%m') , hotelTicker 
```

The thing is that : 
- If I format a DatePath to '%Y-%m' , grouping works just fine
- If I format a DateTimePath to '%Y-%m' no results at all
  - If I format a DateTimePath to  '%Y-%m-%d' works fine 
  - If I execute the SQL I posted it gives results.

Thanks

**Comment by timowest** [comment]
Do you use Querydsl JPA or SQL and which database? Also please specify the Querydsl version you use.

**Comment by rmordillo-witbooking** [comment]
Hi Timo,
thanks for your quick reply.

these are my dependencies : 

> <dependency>
>             <groupId>com.mysema.querydsl</groupId>
>             <artifactId>querydsl-jpa</artifactId>
>             <version>3.7.2</version>
>         </dependency>
>         <dependency>
>             <groupId>com.mysema.querydsl</groupId>
>             <artifactId>querydsl-apt</artifactId>
>             <version>3.7.2</version>
>         </dependency>
>         <dependency>
>             <groupId>com.mysema.querydsl</groupId>
>             <artifactId>querydsl-core</artifactId>
>             <version>3.7.2</version>
>         </dependency>


I am using querydsl JPA and running MySql 5.5.46.

thanks o/

**Comment by timowest** [comment]
> If I format a DateTimePath to '%Y-%m' no results at all

What is the underlying MySQL type?
