### ISSUE TITLE
Add support for bulk insert statements

### ISSUE THREAD

**Issue by coder-hugo** [querydsl/querydsl#1888]
At the moment the only way to insert multiple rows with one insert clause is to use the batch insert. But this is a very slow operation compared to a bulk insert especially if you have to insert thousands of rows at once.
So it would be nice if there would be a way to generate insert statements like this using the querydsl:
```
INSERT INTO table (column1, column2) VALUES (?, ?), (?, ?) ...
```

**Comment by timowest** [comment]
How much slower is the batch insert compared to the single statement approach? Which database and what kind of data/schema did you use for testing?

**Comment by coder-hugo** [comment]
The used database is a MariaDB 10.0.24. The relevant schema for this test consists of 3 tables: the firsts stores a lot of items (~40-50 thousand), the second stores jobs and the third stores the mapping between a job and the items of the first table that are part of a job. At the moment we need to insert about 20-30 thousand entries to this n:m table within a single operation in our application (will be more in the future).
And in this situation the bulk insert is significantly faster than the batch insert. The last bulk insert of our application saved about 23K items to the n:m table within 800ms. Saving the same amount of data to this table using the batch insert takes about 15-20 seconds.

**Comment by timowest** [comment]
Thanks for the data. We can add a switch in SQLInsertClause to use a bulk instead of the batch. How does that sound?
