### ISSUE TITLE
Can't use primitive type in CaseBuilder.

### ISSUE THREAD

**Issue by okihouse** [querydsl/querydsl#1889]
I have problem with `CaseBuilder`

This is sample code
```
boolean passed = true;
query
  .from(user)
  .where(...)
  .list(Projections.bean(User.class, 
     new CaseBuilder()
       .when(user.userNo.eq(1)).then(user.name)
       .when(passed).then(user.name)
       ...
       .otherwise("undefined")
      ).as("name")
)
```

Environment
```
 spring boot 1.3
 mysql 5.7
 querydsl 3.6.7
```

I have to use Case Expression. 
[(http://www.querydsl.com/static/querydsl/latest/reference/html_single/#d0e2095)](http://www.querydsl.com/static/querydsl/latest/reference/html_single/#d0e2095)

 I want to use “Primitive Type” instead of “Boolean Expression”, but this causes an error. 
`when(passed).then(user.name)`

So, I tried to use Literal with Constant Expression, but not work. 

How can I put “Primitive type” in Case Expression? or How do I convert this?

**Comment by Shredder121** [comment]
`.when()` with constants would be `CaseForEqBuilder`, but indeed, it seems you need `CaseBuilder`.

> So, I tried to use Literal with Constant Expression, but not work.

What do you mean, could you clarify?

**Comment by okihouse** [comment]
@Shredder121 

I try to this code
```
.when((BooleanExpression) Expressions.constant(passed)).then(user.name)
```

But, error occur.
```
com.mysema.query.types.ConstantImpl cannot be cast to com.mysema.query.types.expr.BooleanExpression
```

**Comment by okihouse** [comment]
@Shredder121 

Is it permitted primitive type or not?

Otherwise, How should I do when I use a received parameter?

For example,  `public void foo(Boolean isAdmin)`. (Admin passed all cases)

Is it only permitted Predicate or Expression?? (like starts with auto-generated entity Q)

**Comment by Shredder121** [comment]
Well, CaseBuilder and CaseForEqBuilder have two different use cases.
Also you can't cast constants to expressions, as you probably have noticed.

Because the case elements should be predicates, could you try this?
```java
.when(ExpressionUtils.eqConst(Expressions.constant(passed), true))
```
That should work on Hibernate at least (just tried).

**Comment by okihouse** [comment]
@Shredder121 

It's worked.

Thanks for your help!
