### ISSUE TITLE
Table hint in SqlSubQuery

### ISSUE THREAD

**Issue by danbg86** [querydsl/querydsl#189]
Hi, 

We are constructing a query and we need to put a table hint in a subquery of SQLServerQuery. 

Our goal is the following Query:

  from Table1 cr with (NOLOCK)
  join (select kwr.campaignId as campaignId, max(kwr.date) as date, sum(kwr.cost) as cost from Table2 kwr with (NOLOCK) 
  where kwr.date between ? and ? and kwr.keyword = ?
  group by kwr.campaignId) as total
  on cr.date = total.date and cr.id = total.campaignId
  order by cr.id asc

Trying to generate this query we wrote the following code:

  SQLTemplates dialect = new SQLServerTemplates();
  STable1 t1 = new STable1("cr");
  STable2 t2 = new STable2("kwr");
  PathBuilder<Object[]> total = new PathBuilder<Object[]>(Object[].class, "total");

  SQLServerQuery sqlServerQuery = new SQLServerQuery(getConnection(), dialect);
  SQLSubQuery sub = new SQLSubQuery();

  List<Object[]> rows = sqlServerQuery.from(t1).tableHints(SQLServerTableHints.NOLOCK)
    .join(sub.from(t2).where(t2.date.between(
      new Timestamp(dateInicial.getTime()), new Timestamp(dateFinal.getTime())), t2.keyword.eq(keyword))
      .groupBy(t2.campaignId)
      .list(t2.campaignId.as("campaignId"), t2.date.max().as("date"), t2.cost.sum().as("cost")),
        total
      ).on(t1.date.eq(total.get("date")), t1.id.eq(total.get("campaignId")))
      .orderBy(t1.id.asc())
      .list(t1.id.as("campaignId"), t1.campaign, total.get("cost"));

We need to put the table hint ("with (NOLOCK)") in subquery, but today this is not possible. 

Could you provide this functionality?

Thanks in advance, 

Danilo.

**Comment by tanmay-ray** [comment]
I am trying to use NOLOCK hint as well. I couldn't find anything on it so far except this thread. I am creating a JPAQuery in my application. It has a setHint method with accepts name and value parameters. I just don't know what values to use there to provide NOLOCK hint. Is there any documentation or examples I can refer?
