### ISSUE TITLE
Using alternative entity alias when it is looks like a part of HQL keywords

### ISSUE THREAD

**Issue by vsp99h** [querydsl/querydsl#1891]
For example QueryDSL generates HQL query for delete entity Group with Q-Class QGroup as:
```
delete from Group group
where group = ?1
```
And Hibernate throws an exception:

```
org.hibernate.hql.internal.ast.QuerySyntaxException: unexpected token: group near line 1, column 55 [delete from com.lukoil.wellinfo.dao.model.admin.Group group
where group = ?1]
```

Looks like Hibernate decide that "group" is part of  keyword "group by" instead alias.
May be QueryDSL should be generate another alias name for entity if it looks like a part of HQL keywords?

**Comment by timowest** [comment]
Which Querydsl version do you use?

**Comment by vsp99h** [comment]
QueryDSL 4.1.0

**Comment by timowest** [comment]
Could you provide the code for the delete clause execution?

**Comment by vsp99h** [comment]
The code for the delete execution like this:
```
PathBuilder<Group> entityPath = new com.querydsl.core.types.dsl.PathBuilderFactory().create(Group.class);
    return new HibernateDeleteClause(getCurrentSession(), entityPath)
        .where(entityPath.eq(group))
        .execute();
```
Really this method placed in AbstractDAO\<T\> and entity class in parameter T. I get the Entity class from parameter T of AbstractDAO and generate universal common delete clause for deleting single entity.

For example I try to execute:
```
 new HibernateDeleteClause(getCurrentSession(), QGroup.group)
        .where(QGroup.group.eq(group))
        .execute();

```
and it works... But via PathBuilderFactory does not work.

The generated code for QGroup:
```
/**
 * QGroup is a Querydsl query type for Group
 */
@Generated("com.querydsl.codegen.EntitySerializer")
public class QGroup extends EntityPathBase<Group> {

    private static final long serialVersionUID = -677034274L;

    public static final QGroup group = new QGroup("group1");

    public final com.lukoil.wellinfo.dbsupport.entities.querydsl.QAbstractEntity _super = new com.lukoil.wellinfo.dbsupport.entities.querydsl.QAbstractEntity(this);

    public final NumberPath<Integer> accessible = createNumber("accessible", Integer.class);

    public final StringPath description = createString("description");

    //inherited
    public final NumberPath<Long> id = _super.id;

    public final NumberPath<Integer> kind = createNumber("kind", Integer.class);

    public final StringPath mnemonic = createString("mnemonic");

    public final StringPath name = createString("name");

    public final StringPath subsystem = createString("subsystem");

    public QGroup(String variable) {
        super(Group.class, forVariable(variable));
    }

    public QGroup(Path<? extends Group> path) {
        super(path.getType(), path.getMetadata());
    }

    public QGroup(PathMetadata metadata) {
        super(Group.class, metadata);
    }

```

**Comment by timowest** [comment]
The problem is that PathBuilderFactory just picks the uncapitalized simple class name as the variable name (group), which doesn't work here. QGroup.group uses group1, which works.

I'll try to fix it.

**Comment by timowest** [comment]
I added now an optional suffix for PathBuilderFactory in the PR. Since PathBuilderFactory is a general purpose class, it doesn't know about dialect specific keywords.

Also the default suffix is empty, for backwards compatibility.
