### ISSUE TITLE
Result aggregation problem

### ISSUE THREAD

**Issue by Knoxvillekm** [querydsl/querydsl#1892]
Result aggregation not filtering child relations with @Where(clause=""), and work find on parent

**Comment by Shredder121** [comment]
Could you elaborate on your report?

**Comment by Knoxvillekm** [comment]
Example from guide (3.2.4):
```
Map<Integer, List<Comment>> results = query.from(post, comment)
    .where(comment.post.id.eq(post.id))
    .transform(groupBy(post.id).as(list(comment)));
```

I have BaseEntity with field deleted. And two entities Post and Comment with annotation Where(clause="deleted=0").

Results contains comments with deleted = 1

**Comment by Shredder121** [comment]
What annotation? Hibernate?
Shouldn't that be a Hibernate issue?

**Comment by Knoxvillekm** [comment]
But this work with post from example.
And work on post when select it in individual query.

**Comment by Knoxvillekm** [comment]
it can be a Hibernate issue

**Comment by Shredder121** [comment]
If you find out, then feel free to share a reproduction case!
