### ISSUE TITLE
support the  JPA2.1 new features?

### ISSUE THREAD

**Issue by xxyyxx** [querydsl/querydsl#1894]
now support the  JPA2.1 new features? like the  Entity Graphs ,if yes ,how to use?

thanks

**Comment by timowest** [comment]
Querydsl doesn't provide any typesafe wrappers for entity graphs, but they can be defined for a query using

```
EntityGraph graph = this.em.getEntityGraph("graph.Order.items");
query.setHint("javax.persistence.fetchgraph", graph);
```

**Comment by xxyyxx** [comment]
thank you
