### ISSUE TITLE
QueryDSL not converting Time correctly when value is 00:00:00

### ISSUE THREAD

**Issue by Nejaa** [querydsl/querydsl#1895]
Hi, 

I have in my database (mariadb) a Time field whose value is 00:00:00. My entity defines a java.util.Date field to store that value. The problem is that when I retreive that entry from the database the date field in my entity instance is Null instead of having a Date Object representing midnight.

Regards,
Bruno Delor-Sullivan

**Comment by timowest** [comment]
Do you use Querydsl SQL or JPA?

**Comment by Nejaa** [comment]
I Use Querydsl JPA with Hibernate

**Comment by timowest** [comment]
Then the mapping is handled by Hibernate and not Querydsl. You might want to look into the Hibernate type that handles the result set / statement mapping and see if something might go wrong there.
