### ISSUE TITLE
how to deal with the subquery by querydsl jpasql

### ISSUE THREAD

**Issue by killthatbird** [querydsl/querydsl#1896]
sql script--

CREATE TABLE `performance_ronda` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(32) NOT NULL ,
  `code` varchar(32) NOT NULL ,
  `performance_info_id` int(11) NOT NULL,
  `venues_info_id` int(11) DEFAULT NULL,
  `start_time` datetime NOT NULL,
  `end_time` datetime NOT NULL,
  `status` int(11) NOT NULL,
  `created_time` datetime NOT NULL ,
  PRIMARY KEY (`id`),
  UNIQUE KEY `code_UNIQUE` (`code`),
  KEY `fk_performance_ronda_performance_info_idx` (`performance_info_id`),
  KEY `fk_performance_ronda_venues_info_idx` (`venues_info_id`),
  CONSTRAINT `fk_performance_ronda_venues_info` FOREIGN KEY (`venues_info_id`) REFERENCES `venues_info` (`id`) ON UPDATE CASCADE,
  CONSTRAINT `fk_performance_ronda_performance_info` FOREIGN KEY (`performance_info_id`) REFERENCES `performance_info` (`id`) ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8 ;

CREATE TABLE `venues_info` (
  `id` int(11) NOT NULL AUTO_INCREMENT ,
  `area_id` int(11) NOT NULL,
  `name` varchar(32) NOT NULL ,
  `code` varchar(32) NOT NULL ,
  `name_pinyin` varchar(200) DEFAULT NULL,
  `deleted_flag` int(11) NOT NULL,
  `created_time` datetime NOT NULL ,
  PRIMARY KEY (`id`),
  UNIQUE KEY `name_UNIQUE` (`name`),
  UNIQUE KEY `code_UNIQUE` (`code`),
  KEY `fk_venues_info_dict_city_area1_idx` (`area_id`),
  CONSTRAINT `fk_venues_info_dict_city_area1` FOREIGN KEY (`area_id`) REFERENCES `dict_city_area` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=14 DEFAULT CHARSET=utf8 ;

I need to implement the function as follow:
SELECT vi.id,(select count(*) from performance_ronda pr where pr.venues_info_id=vi.id) FROM stp_db.venues_info vi  

how to use the querydsl Jpasql to implement the query?
thanks

**Comment by timowest** [comment]
Assuming you have the code generation done based on the instructions in the reference docs, your Querydsl query could look like this

```
query().select(v.id, SQLExpressions.select(Wildcard.count).from(pr).where(pr.venues_info_id.eq(v.id)))
  .from(vi).fetch();
```

The Querydsl Google Group is a better forum for this kind of support

**Comment by killthatbird** [comment]
thanks a lot。
but the JPASQLQuery do not have the function of select(),I chose the list().

**Comment by timowest** [comment]
What I posted was Querydsl 4 syntax, you might be still using Querydsl 3?
