### ISSUE TITLE
Coalesce using UNION keyword instead of a comma

### ISSUE THREAD

**Issue by robertandrewbain** [querydsl/querydsl#1898]
The following code `new Coalesce<>(some SQLQuery<BigDecimal>, Expressions.constant(BigDecimal.ZERO)).as(SOME_COLUMN_ALIAS)` will generate the following SQL `coalesce(<some query> union 0)` when it should generate `coalesce(<some query, 0)`. This bug has been introduced between 4.0.4 and 4.1.1.

**Update:** tested in 4.0.9 and bug not present. Tested in 4.1.0 and bug is present. Bug introduced in 4.1.0.

**Update:** I think this is caused by #1805 changes to `querydsl-sql/src/main/java/com/querydsl/sql/SQLSerializer.java`. https://github.com/querydsl/querydsl/pull/1805/files#diff-abdf9237fdabf083adb006f87913f4deR893

**Comment by Shredder121** [comment]
Fixed in #1900.
