### ISSUE TITLE
MySQLQueryFactory.insertOnDuplicateKeyUpdate setting null values

### ISSUE THREAD

**Issue by asensen** [querydsl/querydsl#1902]
Hi,

i don't know if this is a bug or i'm using the wrong methods. I'd like to use MySQLQueryFactory.insertOnDuplicateKeyUpdate(), where the update part can set columns to null. Using expressions like qPerson.name.eq(person.getName()) leads to an 

IllegalArgumentException("eq(null) is not allowed. Use isNull() instead")

but using isNull() is no option here in my opinion. Using a String instead of expressions leads to Problems with e.g. Timestamps and formatting, which i'd like to avoid.

Do you have any suggestions on how to solve this issue?

Thanks :)
Andreas

**Comment by timowest** [comment]
This will be covered by https://github.com/querydsl/querydsl/pull/1819
To be released tomorrow

**Comment by asensen** [comment]
Awesome. Thank you very much for the fast reply! :)
