### ISSUE TITLE
NumberPath.like is not work on mongo

### ISSUE THREAD

**Issue by SunnyTam** [querydsl/querydsl#1904]
I am using querydsl in mongo db. I would like to have a regex search on a number field. how can I do it it like/stringvalue function is not work correctly

**Comment by Shredder121** [comment]
Unfortunately, Mongodb doesn't allow this.
https://jira.mongodb.org/browse/SERVER-1174

However, @timowest, we can use [Javascript inside mongodb](http://stackoverflow.com/a/22606957/3485069) and have the JS type coercion rules work in favor for us.
is that an idea?
