### ISSUE TITLE
how to compare the enum type field?

### ISSUE THREAD

**Issue by killthatbird** [querydsl/querydsl#1907]
An entity has an field which is enum type.I create a JPASQLQuery query,as following

query.from(qPerformanceInfoEntity)
         .leftJoin(qMediaInfoEntity)
         .on(qPerformanceInfoEntity.id.eq(qMediaInfoEntity.objectId)
                                       .and(qMediaInfoEntity.objectType.eq(MediaObjectType.PERFORMANCE))) 
         .where(predicate)
        .groupBy(qPerformanceInfoEntity.id)
        .list(Projections.constructor(PerformanceSpecialInfoView.class,
                                                        qPerformanceInfoEntity.id,
                                                        qPerformanceInfoEntity.code,
                                                        qPerformanceInfoEntity.title,
                                                        qPerformanceInfoEntity.subtitle,
                                                        qPerformanceInfoEntity.status,
                                                        qPerformanceInfoEntity.startDate,
                                                        qMediaInfoEntity));,

qMediaInfoEntity.objectType is an enum type,I need to compare it with MediaObjectType.PERFORMANCE,
The result is incorrect,which qMediaInfoEntity is null.It should be not null.
when I delete the ".and(qMediaInfoEntity.objectType.eq(MediaObjectType.PERFORMANCE)",the result become right.
Is the compare between the enum field and parameter right.? how to compare 
please help me. Thanks a lot.

**Comment by Shredder121** [comment]
It's better to ask usage questions like these on the [Google Group](https://groups.google.com/forum/#!forum/querydsl).
Could you maybe post the question over there?
