### ISSUE TITLE
Confusing Expressions/Template API

### ISSUE THREAD

**Issue by ruisalgado** [querydsl/querydsl#1908]
I find that the method overloading in a series of template factory methods (StringTemplate, BooleanTemplate, ...) defies the principle of least surprise. Example from [Expressions](https://github.com/querydsl/querydsl/blob/6bb7a28/querydsl-core/src/main/java/com/querydsl/core/types/dsl/Expressions.java#L622):

```java
public static StringTemplate stringTemplate(String template, Object... args) {
    return stringTemplate(createTemplate(template), ImmutableList.copyOf(args));
}

public static StringTemplate stringTemplate(String template, ImmutableList<?> args) {
    return stringTemplate(createTemplate(template), args);
}
```

Having method overloads for `Object... args` and `List<?> args` and even `Object firstArgs, Object... otherArgs` are common practices. However using a concrete implementation of a collection (`ImmutableList` here) is not. 
I was refactoring some code that interacts directly with queryDsl and wanted to change from using arrays of args to using collections. As I read the queryDsl API my eyes totally ignored the `Immutable` prefix because they are just so damn trained to expect an interface from the collections API. My mutable list ended up being passed to the `Object...` overload and stuff blew up. Quite frustrating :)

I'd suggest deprecating the `ImmutableList` overload and adding method overloads that take a `List` from the collections API. 

Let me know if you're OK with this and I'll gladly prepare a PR.

**Comment by timowest** [comment]
Yes, that's OK.

**Comment by timowest** [comment]
And also thanks for volunteering to create the PR!
