### ISSUE TITLE
MathExpressions.log(n, b) produces jpql with reversed order of arguments in respect to PostgreSQL logarithm function

### ISSUE THREAD

**Issue by ilanKeshet** [querydsl/querydsl#1911]
first of all an apology, I'm not entirely sure this issue is your responsibility, hopefully, it is, and i'm not just wasting your time

MathExpressions.log(n, b) produces jpql with reversed order of arguments in respect to PostgreSQL logarithm function

`log(Expression<A> num, int base)` 
`MathExpressions.log(Constant.create(64) , 2)`  //64 in the num and 2 is the base. - expected result: 6
produces JPQL `log(64,2)` 
which gets translated to PostgreSQL `log(64,2)`  except that according to [PostgreSQL 9.4 manual](https://www.postgresql.org/docs/9.4/static/functions-math.html) the order of arguments should be reversed  `log(b numeric, x numeric) logarithm to base b 	log(2.0, 64.0)` 

**using versions**
* querydsl-jpa-3.6.9
* hibernate-jpa-2.1
* PostgreSQL 9.4

**Comment by timowest** [comment]
MathExpressions will work reliably only in SQL (Querydsl SQL). In this case Hibernate is just very permissive, and renders the JPQL function directly to SQL.

In Querydsl SQL log(num, base) is handled correctly for PostgreSQL.

**Comment by ilanKeshet** [comment]
Hi, thank you for your quick replay, 
we worked around the problem with the following peace of code 
```
   /**
     * refrain from {@link MathExpressions#log} it produces PostgreSQL with reversed syntax
     * MathExpressions.log(Constant.create(64) , 2)
     * <br> log(64,2)
     * <br> PostgreSQL expects log(2,64)
     * @see https://www.postgresql.org/docs/9.4/static/functions-math.html
     */
    public static NumberExpression<Double> log(NumberExpression<?> num, int base) {
    	return Expressions.numberTemplate(Double.class, "log({0},{1})",base ,num);
    }

**Comment by timowest** [comment]
An alternative way to fix it would be to extend HQLTemplates and call the following in the constructor

```
add(Ops.MathOps.LOG, "log({1s},{0s})");
```

That would revert the arguments.
