### ISSUE TITLE
Concat field raises CodeGenException for querydsl-collections

### ISSUE THREAD

**Issue by mefernandez** [querydsl/querydsl#1912]
Hi,

I'm using **querydsl-jpa** and **querydsl-collections** version **3.7.1**.

This `Predicate`:

```java
QPersona.person.address.street.concat(" ").concat(QPersona.person.address.number).containsIgnoreCase("Mulholland Drive 66")
```

works fine in JPA, which is translated as:
```
containsIc(address.street +   + address.number,Mullholland Drive 66))
```

However, the same predicate using **querydsl-collections** throws a `CodeGenException`. 
The stacktrace shows this code generation:
```
error: incompatible types: String cannot be converted to boolean
        if (com.mysema.query.collections.CollQueryFunctions.equals(person.getAddress().getStreet() + a1 + person.getAddress().getNumber().toLowerCase().contains(a2))) {
```

Querydsl is applying `.containsIgnoreCase()` to the last field. 
How to tell querydsl to apply `.containsIgnoreCase()` to the whole  concat result?

**Comment by Shredder121** [comment]
Thanks for reporting the issue.
The way of precedence mappings was changed, but not backported for Querydsl 3.x.
Attached is a PR that fixes this.
