### ISSUE TITLE
Missing SimpleExpression.notIn(Expression<? extends T>... right) ?

### ISSUE THREAD

**Issue by ctzen** [querydsl/querydsl#1914]
version 4.1.2

In SimpleExpression there exists:
`public BooleanExpression in(Expression<? extends T>... right)`

is there a reason why there isn't a corresponding:
`public BooleanExpression notIn(Expression<? extends T>... right)`
?

Thank you.

**Comment by Shredder121** [comment]
> is there a reason why there isn't a corresponding:

No, no real reason.

I pushed a fix, so it should be fixed in the next release.
