### ISSUE TITLE
Query .transform problem

### ISSUE THREAD

**Issue by fabiohaertel** [querydsl/querydsl#1916]
Hello.

Im trying to group the results of my query using the "transform" function. After executing the function, I get this error:

_org.hibernate.QueryException: firstResult/maxResults not supported in conjunction with scroll() of a query containing collection fetches

This is my final query:

```
select documentEntityInfo
from DocumentEntityInfo documentEntityInfo
  left join fetch documentEntityInfo.defaultTemplate
  left join fetch documentEntityInfo.formLayout
  left join fetch documentEntityInfo.folders
```

And this is the transform function:

`LinkedHashMap<?, List<T>> result = (LinkedHashMap) query.transform(GroupBy.groupBy(groupBy).as(GroupBy.list(qEnt)));`

It works when Im not fetching "documentEntityInfo.folders", which is a java Set:

`public final SetPath<com.x.y.doc.folder.Folder, com.x.y.doc.folder.QFolder> folders = this.<com.x.y.doc.folder.Folder, com.x.y.doc.folder.QFolder>createSet("folders", com.x.y.doc.folder.Folder.class, com.x.y.doc.folder.QFolder.class, PathInits.DIRECT2);`

The "groupBy" variable is an attribute of my qEnt class:

`documentEntityInfo.creationDate`

Can anybody help me? Does query transform work when I have multi level collections? I cant find the solution :(

Thanks!

**Comment by templarfelix** [comment]
+1

**Comment by timowest** [comment]
Do you apply any limit or offset to the query?

**Comment by fabiohaertel** [comment]
Yes, limit and offset.

query.offset(page.getStartRow());
query.limit(page.getPageSize());

both values starting at 1 (startRow) and 30 (pagesize)

**Comment by timowest** [comment]
Like the exception says they can't be used with collection fetch
