### ISSUE TITLE
SimpleExpression and ComparableExpression generics mismatch

### ISSUE THREAD

**Issue by ctzen** [querydsl/querydsl#1919]
version 4.1.2

In SimpleExpression, there exists:
`BooleanExpression eq(Expression<? super T> right)`
`BooleanExpression ne(Expression<? super T> right)`

but in ComparableExpression, the "corresponding" functions are:
`BooleanExpression gt(Expression<T> right)`
`BooleanExpression goe(Expression<T> right)`
`BooleanExpression lt(Expression<T> right)`
`BooleanExpression loe(Expression<T> right)`

Any reason the ComparableExpression parameters do not use the same generic signature as the SimpleExpression one (or vice versa)?

Regards.

**Comment by timowest** [comment]
The supertype of T might not be comparable

**Comment by ctzen** [comment]
Thank you for the explanation.
