### ISSUE TITLE
mysema-commons-lang is unlicenced

### ISSUE THREAD

**Issue by mirabilos** [querydsl/querydsl#1922]
The only available source code to mysema-commons-lang is:

http://central.maven.org/maven2/com/mysema/commons/mysema-commons-lang/0.2.4/mysema-commons-lang-0.2.4-sources.jar

This archive only contains files with the following statement:

    /*
     * Copyright (c) 2010 Mysema Ltd. 
     * All rights reserved. 
     */

However, there is no licence for these files; therefore, this dependency is unlicenced and thus illegal to use.

If you’re in a situation to fix that, please obtain and publish an appropriate licence for this artifact; otherwise, it **must** be removed.

Note that most distributions require such licence statements to be included with the source code.

**Comment by Shredder121** [comment]
If you look at the pom
http://central.maven.org/maven2/com/mysema/commons/mysema-commons-lang/0.2.4/mysema-commons-lang-0.2.4.pom
You can see that the project is licensed under The Apache Software License, Version 2.0.
(So I think that they just forgot to update the license headers in the individual files.)

Does that answer your question?

p.s. mysema commons lang is (IIRC) still in the hands of [Mysema](/mysema), but I don't see it in their GitHub organization.
You can try contacting them directly.

p.p.s. @timowest Is it true what I said here? Just want to verify.

**Comment by mirabilos** [comment]
The POM file is not necessary either a licence grant or correct. I’ve seen multiple artefacts with misleading or outright wrong information in the POM, so I’m extremely wary of trusting that information.

I’ll try to contact Mysema, Inc. then. Thanks!

**Comment by Shredder121** [comment]
>(So I think that they just forgot to update the license headers in the individual files.)

I wasn't implying that the POM file is correct, I was merely stating that looking at the POM file the probably intended to license it under ASL 2.0.

Do come back when you know more, and if they want to resolve it.
Then we can depend on the new artifact, if they choose to publish that.

**Comment by mirabilos** [comment]
I have a response from an employee of theirs who stated that they indeed intend to have the Apache 2 licence apply to the artefact, but that they cannot issue a new release quickly. I asked them to post here (ideally PGP-signed, to establish some kind of verifyable trust) stating so, but I guess that’s enough for the project the team I’m in is working on at the moment.

**Comment by mangolas** [comment]
For a fast resolve I can verify the Apache 2 license apply for mysema-commons-lang.

**Comment by Shredder121** [comment]
Ahh. Then my hunch was correct after all.
Yes, at least some verification of intent would I think be nice.
But maybe it can be put up somewhere a little less volatile than a comment in GitHub Issues?
@mangolas at least thank you for joining the conversation, much appreciated!

**Comment by nik9000** [comment]
It might be worth enabling [apache rat](http://creadur.apache.org/rat/) to check the license files. I don't know if there is a maven plugin for it though.

**Comment by nik9000** [comment]
> I don't know if there is a maven plugin for it though.

It [looks](http://creadur.apache.org/rat/apache-rat-plugin/) like there is.

**Comment by mangolas** [comment]
The best thing is to do it right and put the sources back online, they were in SVN and now exists only in backups, so we would need to republish the project in github. That all can be done, but we just need to find bit time to do it.

**Comment by mirabilos** [comment]
Thanks for the official statement; I think the issue can be closed for now.

@mangolas I’d be happy to do the svn to git conversion for you if you can send me the part of the backup

**Comment by mangolas** [comment]
@mirabilos Hah, ok, we first have to locate the backup, which is the real job :)

**Comment by delgurth** [comment]
@mangolas can't you use the src artifact of the last release for this? Seeing your remark is 2 years old and the source still not being available.

**Comment by patriceo** [comment]
Hi I'm facing the same issue as @mirabilos. This package has no repository and no licence available. This is a big issue since it could put you in troubles.

It's a small library with 1 interface and 6 small classes from 2012:

![image](https://user-images.githubusercontent.com/2040346/132888319-5ee24aa4-4479-48ef-9a36-07e88374404a.png)

I'm almost sure the utility classes it provides are available either in recent version of the JDK or apache libs. Is there any plan to remove this dep ?

Thanks
