### ISSUE TITLE
Wrong code in result handling/constructor usage example

### ISSUE THREAD

**Issue by maffe** [querydsl/querydsl#1923]
Chapter 3.2.3 Constructor usage uses [code](https://github.com/querydsl/querydsl/blob/master/querydsl-docs/src/main/docbook/en-US/content/general/result-handling.xml#L74) from the previous example, 3.2.2 Bean population

> 3.2.3. Constructor usage
> 
> Constructor based row transformation can be used like this
> 
> List<UserDTO> dtos = query.select(
>     Projections.bean(UserDTO.class, user.firstName, user.lastName)).fetch();

Should use `Projections.constructor(…)`

**Comment by timowest** [comment]
@maffe Thanks for the heads up! Will be fixed in the next release.
