### ISSUE TITLE
OrderBy an attribut entity not present in SELECT statement?

### ISSUE THREAD

**Issue by thibaudsowa** [querydsl/querydsl#1924]
The basis: I have these three entities:

```java
@Entity(name = "USER")
public class User {
    @OneToMany(fetch = FetchType.LAZY)
    private Set<Right> rights;
    @OneToMany(fetch = FetchType.LAZY)
    private Set<Message> messages;
}

@Entity(name = "RIGHT")
public class Right {
    @Column(name = "NAME")
    private String name;
}

@Entity(name = "MESSAGE")
public class Message {
    @Column(name = "CONTENT")
    private String content;
}
```

In my DB I have one user associated with two messages and tree rights.

I want to perform a query to get a list of user with messages order by right name, so I did something like this:

```java
List<User> users = query.from(qUser)
    .leftJoin(qUser.messages, qMessage).fetch()
    .leftJoin(qUser.rights, qRight)
    .orderBy(qRight.name)
    .list(qUser);
```

...but with this query I have an error:

```
org.hibernate.exception.SQLGrammarException: could not prepare statement
...
Caused by: java.sql.SQLSyntaxErrorException: invalid ORDER BY expression
```

...because the `name` attribut of `Right` entity is not in the `SELECT` statement. So I added the attribute in the `SELECT` statement:

```java
List<Tuple> tuples = query.from(qUser)
    .leftJoin(qUser.messages, qMessage).fetch()
    .leftJoin(qUser.rights, qRight)
    .orderBy(qRight.name)
    .list(qUser, qRight.name);

// tuples.size() == 3

List<User> users = new ArrayList<>();
for(Tuple tuple : tuples) {
    users.add(tuple.get(0));
}

// users.size() == 3
// users.get(0) == users.get(1) == users.get(2)
// users.get(0).getMessages().get(0).getContent() == "first message"
// users.get(1).getMessages().get(0).getContent() == "second message"
// users.get(2).getMessages().get(0).getContent() == "third message"
// => NOT GOOD
```

So the result is not as I expected. (I want one user with three messages)

I have tried another idea: to fetch the join between `User` and `Right`. Since the fetch adds all `Right` attributs in the `SELECT` statement, there is no error and I don't have to add `Right.name` in the `.list()` method so the request returns a `User` list instead of a `Tuple` list.

```java
List<User> users = query.from(qUser)
    .leftJoin(qUser.messages, qMessage).fetch()
    .leftJoin(qUser.rights, qRight).fetch()
    .orderBy(qRight.name)
    .list(qUser);

// users.size() == 1
// users.get(0).getMessages().get(0).getContent() == "first message"
// users.get(0).getMessages().get(1).getContent() == "second message"
// users.get(0).getMessages().get(2).getContent() == "third message"
// GOOD
```

It could be a good solution but I'm worried about performance issues. With that trick I will add a lots of useless columns in my `SELECT` statement.

**Is there a better solution to resolve this problem?**

I am using QueryDsl 3.6.6

**Comment by timowest** [comment]
This kind of thread fits better into the Querydsl Google Group, but I'll answer here anyway:

With the non-fetch joins from user to rights you duplicate the users in the result set. Also semantically it's vague, by which right name do you want the users ordered?

What you want is probably a result set with distinct rows. That can be achieved via `distinct()`. Alternatively join from user to a single right, not all of them.

**Comment by thibaudsowa** [comment]
Sorry about the Google Group part... Next time I will ask my question into this group.

About the semantic question, yes the example is a bit wired... I tried to simplified my real problem for this issue. (not really good enough...)

With this new simplified example, the problem is the same (I have users liked with **one** role and multiple messages):

```java
@Entity(name = "USER")
public class User {
    @OneToOne(fetch = FetchType.LAZY)
    private Role role;
    @OneToMany(fetch = FetchType.LAZY)
    private Set<Message> messages;
}

@Entity(name = "Role")
public class Role{
    @Column(name = "NAME")
    private String name;
}

@Entity(name = "MESSAGE")
public class Message {
    @Column(name = "CONTENT")
    private String content;
}
```

If I want to list all my users with loaded messages ordered by role name, how can I do that without users duplication?

**Comment by timowest** [comment]
I think this is different, selecting users with messages fetch joined shouldn't cause duplicates in the result set. Also the join to role is different, as it shouldn't cause duplicates like in your first case.

**Comment by thibaudsowa** [comment]
Well I have two options to make my query runnable:

- To fetch `Role`, like this the `name` attribut will be in the `SELECT` statement.
-> Result: no duplicated `User`, but not efficient friendly

- To add `name` attribut in the `.list()` method
-> Result: More efficient than first option, but generate tuple with duplicated `User`.

**Comment by timowest** [comment]
I don't see any way how the situation could be improved through Querydsl, do you?

**Comment by Shredder121** [comment]
If elements are added to the `SELECT`, then you get a tuple, with duplicate values.
So it would be possible, but it wouldn't improve your use case.

**Comment by thibaudsowa** [comment]
But, for exemple when we use `.join(...).fetch()` every attributs of the entity fetched are added in the SELECT statement, and the `.list()` method return an entity list instead of a tuple list.

Is possible to reproduce this logic this orderBy?

**Comment by Shredder121** [comment]
That is indeed what the JPA provider does, but that is because it works from the JPQL query we give it.
If we would add something besides just the entity to the `SELECT`, you get a tuple as result.
So no, it is not possible to reproduce this logic from a JPA point of view.

**Comment by thibaudsowa** [comment]
Ok, I really don't know what I will do to solve my problem..

But if it is not possible, it is not possible... Thanks for the time to help me.
I will close the issue.

**Comment by Shredder121** [comment]
Well, look at it this way:

>It could be a good solution but I'm worried about performance issues. With that trick I will add a lots of useless columns in my SELECT statement.
**Is there a better solution to resolve this problem?**

You already had the solution. And the answer to the question "Is there a better solution" is then no.
So I'd say that `fetch()`ing the joins is the way to go.

**Comment by thibaudsowa** [comment]
Indeed. But I was talking about "not possible to have a better solution".

Again thanks!
