### ISSUE TITLE
deducing from clause

### ISSUE THREAD

**Issue by p-rosenthal** [querydsl/querydsl#1927]
As an API user, redundant information can be tedious and sometimes error-prone. 
Having a full query definition including the select part and excluding the from-clause 
a minimal from-clause is deductive.

QueryDSL tuple projection example:
List<Tuple> tuples = queryFactory.select(
    person.lastName, person.firstName, person.yearOfBirth)
  .from(person)
  .fetch();
It is much nicer to just write:
List<Tuple> tuples = queryFactory.select(
 person.lastName, person.firstName, person.yearOfBirth)
 .fetch();

→ thus no “.from()”

For compatibility reasons and corner cases the possibility to define the from-clause must remain.
Deducing the from-clause should include the possibility that there are several entities involved.
Deducing the from-clause should end up with reasonable defaults for joins that must be adjustable when navigating though Q classes.
Deducing the from-clause concerns all non-from-clause parts of the query (also having, group by, order by, sort by...).

Advantage
To my knowledge QueryDSL is the most elegant and safe way of building queries in Java. Making the from-clause definition redundant (optional) would be another great usability feature.

Caveats
Deducing will consume time (generally negligible). 
Deducing puts more responsibility to the QueryDSL framework (today and tomorrow → maintenance).

**Comment by timowest** [comment]
How would that work if the select clause contains paths with multiple roots?

**Comment by p-rosenthal** [comment]
If your QueryDSL is transforming to say Hibernate you have to first detect and then generate multiple Hibernate roots. Is that answer too simplistic ;-) ? 
Probably I have to branch and then implement an example ;-) only it will take some time ;-)

**Comment by p-rosenthal** [comment]
Using QueryDSL builds up something like an IR in the form of an AST (absract syntax tree or rather a semantic DAC with a head node, but that's splitting hairs). 
For the detection you just ask the JPQLQuery at the „top“ of the tree/DAC to ask all of its members recursively what roots they reference. You just have an Interface "getRoots()" that has to be implemented by any member of the DAC.

**Comment by timowest** [comment]
Sorry, I was unclear. Extracting the roots is not the problem, we already do that in other places. But a cross join without any where conditions is seldomly what the user wants.

Also how should we treat `select().where().fetch()` cases? Throw an exception?

**Comment by p-rosenthal** [comment]
I agree, unrestricted cross joins are usually unintended and evil. But do you think cross joins will be less frequent when you force the from-clause to be specified? Having from-clauses specified doesn't prevent unrestricted cross joins.
Discovering unrestricted cross joins is a little harder than just finding the roots. If you can, throwing an error would be my default preference. Configuration should be possible. 
By offering navigation between related Q entities, the API already has already one simple measure against unrestricted cross joins.

I don´t fully get the code snippet. Are you asking what to do in case of a select call without parameters?

**Comment by Shredder121** [comment]
I think he means it in the context of your snippet, with an added where clause.

>It is much nicer to just write:
```java
List tuples = queryFactory.select(
person.lastName, person.firstName, person.yearOfBirth)
.fetch();
```

For example:
```java
QPerson person = new QPerson("person");
QPerson friend = new QPerson("friend");
List tuples = queryFactory.select(
        person.lastName, person.firstName, person.yearOfBirth)
    .where(friend.eq(somePerson))
    .fetch();
```
It becomes not clear what the from, or the join defaults should be.

**Comment by p-rosenthal** [comment]
A nice thing to investigate into would be something like:
`Qperson friend = person.getFriends().getOne(joinHint)`

But maybe you have already something that defines joins when navigating.

**Comment by p-rosenthal** [comment]
That's your decision, with or without QueryDSL is the best query framework available that I know of. 
Cheers ;-)

**Comment by timowest** [comment]
Thanks ;)
