### ISSUE TITLE
PostgreSQL exception on SUBSTR_2ARGS

### ISSUE THREAD

**Issue by hylkevds** [querydsl/querydsl#1929]
Using 4.1.2:
I'm passing a string path and two integer constants to substring, and get the following error on PostgreSQL 9.3. It seems the first integer parameter is converted to a numeric by the addition, but the second is not.

```
ERROR:  function substr(text, numeric, integer) does not exist at character 93
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
STATEMENT:  select "e1"."ID", "e1"."DESCRIPTION", "e1"."PROPERTIES"
	from "THINGS" "e1"
	where substr("e1"."DESCRIPTION",($1 + $2),($3 - $4)) = $5
```

I'm guessing it's because of the template for substring: `"substr({0},{1+'1's},{2-1s})"` 
Explicitly casting my integers to integers won't work of course, because the addition and subtraction happen after my manual casts...
A bit of debugging showed that the first `'1's` is converted to a BigDecimal, while the second `1s` is simply an Integer.

I've tried playing around with the template but I've not manged to compile querydsl myself due to https://github.com/querydsl/querydsl/issues/1788

**Comment by timowest** [comment]
I have not been able to replicate the issue. Could you provide the substring code snippet you use?

**Comment by hylkevds** [comment]
I've written a little test project that demonstrates the error:
https://github.com/hylkevds/QueryDslTests
If you point it at an empty database (in pom.xml and src/main/resources/db.properties) and it'll create a table with some data and run a unit test against it. For me that fails with the above mentioned exception.

I'm guessing it's caused by the way I pass the constants using a `ConstantNumberExpression<Integer>`

**Comment by emaysyuk** [comment]
@timowest ,
is there any reason why SUBST_2ARGS templates are so different in [JavaTemplates](https://github.com/querydsl/querydsl/blob/QUERYDSL_4_2_1/querydsl-core/src/main/java/com/querydsl/core/types/JavaTemplates.java#L57) and [JPQLTemplates](https://github.com/querydsl/querydsl/blob/QUERYDSL_4_2_1/querydsl-jpa/src/main/java/com/querydsl/jpa/JPQLTemplates.java#L110)? 
I am looking for the way to write an expression to order by last 6 digits but ended up with very confusing code:
Expression<? extends Comparable> sortedBy = QEntity.entity.field.substring(5, 16); // pay attention to indexes here
query.orderBy(new OrderSpecifier<>(Order.ASC, sortedBy));

Output query:
select ... from ... where ... order by substring(field, 6, 11) // I expected end index to be 16

I was wondering why querydsl calculates end index for sql based on the formula (endIndex - beginIndex)?

Another example:
Expression<? extends Comparable> sortedBy = QEntity.entity.field.substring(10, 22); // pay attention to indexes here
query.orderBy(new OrderSpecifier<>(Order.ASC, sortedBy));

Output query:
select ... from ... where ... order by substring(field, 11, 12) // I expected end index to be 22

**Comment by jwgmeligmeyling** [comment]
It appears as if the beginIndex is incremented with a constant value of 1, and the endIndex is decremented with a constant value of 1 (and not the beginIndex). I assume this was intended to compensate for a difference between 0 and 1-based indexing between standard Java and SQL dialects (which JPQL tends to follow). JPQL indeed uses 1-based indexing for the `SUBSTR` function.

The bug here seems to be that the endIndex should also be incremented with 1, rather than being incremented by it.

So I'd expect that your output query is wrong, and instead should be:

```sql
select ... from ... where ... order by substring(field, 6, 15)
```

And with the bugfix it should be


```sql
select ... from ... where ... order by substring(field, 6, 17)
```
