### ISSUE TITLE
Join for dynamic entity path alias, querydsl-sql needs implementation for EntityPath and alias.

### ISSUE THREAD

**Issue by tan31989** [querydsl/querydsl#1936]
In case of querydsl ProjectableSQLQuery of querydsl-sql, we have following implentation:

```
  @Override
    public Q innerJoin(EntityPath<?> target) {
        return queryMixin.innerJoin(target);
    }

    @Override
    public <E> Q innerJoin(RelationalFunctionCall<E> target, Path<E> alias) {
        return queryMixin.innerJoin(target, alias);
    }

    @Override
    public Q innerJoin(SubQueryExpression<?> target, Path<?> alias) {
        return queryMixin.innerJoin(target, alias);
    }

    @Override
    public <E> Q innerJoin(ForeignKey<E> key, RelationalPath<E> entity) {
        return queryMixin.innerJoin(entity).on(key.on(entity));
    }
```

It should also have joins with:

```
@Override
public Q innerJoin(EntityPath<T> target, Path<T> alias) {
	return queryMixin.innerJoin(target, alias);
}

```
This is present in querydsl-jpa but not present for joins in querydsl-sql.

**Comment by timowest** [comment]
Could you provide an example how this would be used?

**Comment by tan31989** [comment]
Hi Timo,

Say, I wanted to create this:
`select * from customer as c inner join orders as o ......`

I would want to build it dynamically like:

```
PathBuilder<Object> fromPath = new PathBuilder<Object>(Object.class, "customer");
PathBuilder<Object> joinPath = new PathBuilder<Object>(Object.class, "orders");
SQLQuery<?> sqlQuery = queryFactory.from(fromPath.as("c"));
sqlQuery = sqlQuery = sqlQuery.innerJoin(<WHAT_SHOULD_BE_HERE>);
```

I tried the following:

```
String obj = joinPath.as("o").toString(); // Gives: orders as o
PathBuilder<Object> newPath = new PathBuilder<Object>(Object.class, obj);

sqlQuery = sqlQuery.innerJoin(newPath);
```
This is generating: 
> **select * from customer as c inner join \`orders as o\` ....**

If you notice the extra `, that is not helping me.


Checking the implementations allowed:
```
1. public Q innerJoin(EntityPath<?> target);
2. public <E> Q innerJoin(RelationalFunctionCall<E> target, Path<E> alias);
3. public Q innerJoin(SubQueryExpression<?> target, Path<?> alias);
```

When I tried looking into querydsl-jpa, the code had the `innerJoin(EntityPath<?> target, Path<E> alias);`, but was not present for querydsl-sql.

Thanks.

**Comment by timowest** [comment]
You are using Querydsl SQL without the generated types?

**Comment by tan31989** [comment]
Yes, without the code generation.

**Comment by tan31989** [comment]
Hi Timo,

I tried a patch and included some of the needed method implementations.
Let me know if this patch is good. I tested it with my local set up and it does generate the needed sql:

`select * from customer as c inner join orders as o ....`

The patch I see as: [querydsl-sql_i1936.patch](https://github.com/querydsl/querydsl/files/336380/querydsl_i1936.txt), let me know if it's good enough, I could provide an assistance with a pull request.

**Comment by Shredder121** [comment]
If you open the pull request, we can see if Travis can build and test it.

**Comment by 9sql** [comment]
Hi Team,

Just wanted to check, if above mentioned feature is released? I am also working with dynamic entities without code generation. Could you please share some snippet to use?

**Comment by Shredder121** [comment]
Yes it should be released.

**Comment by tan31989** [comment]
@9sql Yes, it's released and we are using it.
