### ISSUE TITLE
QueryDSL MDC logging fields contain dots

### ISSUE THREAD

**Issue by utwyko** [querydsl/querydsl#1941]
QueryDSL MDC logging fields contain dots in the field names. All logging infrastructure based on ELK (Elasticsearch, Logstash, Kibana) will require the dots in fields to be removed when upgrading to 2.0 (see: https://www.elastic.co/guide/en/elasticsearch/reference/current/breaking_20_mapping_changes.html#_field_names_may_not_contain_dots).

**Comment by Shredder121** [comment]
What do they mean by 'field name'?
Do they mean that they serialize the key as-is, and dots are not allowed?

**Comment by utwyko** [comment]
As far as I know, the 'field name' is just the key for key-value pairs you put in MDC. They are enforcing keys with no dots in them. Also see: https://github.com/elastic/elasticsearch/pull/12068

**Comment by Shredder121** [comment]
Okay, that's clear.

----
@timowest Sounds fine, what do you think?
What do we do with the current key?
I'm sure there are people who depend on the current value.
We can maybe wait with this until the next minor release (`4.2.0` maybe?)

**Comment by nik9000** [comment]
> All logging infrastructure based on ELK (Elasticsearch, Logstash, Kibana) will require the dots in fields to be removed when upgrading to 2.0

For what it is worth this is fixed in Elasticsearch 5 which is in alpha now: https://github.com/elastic/elasticsearch/pull/17759 https://github.com/elastic/elasticsearch/pull/18106

**Comment by Shredder121** [comment]
I also found this, but I am not quite sure how it was resolved
https://github.com/elastic/elasticsearch/issues/15951

**Comment by nik9000** [comment]
I wasn't super close to that work but my understanding is that they should "just work" now. It looks like Elasticsearch creates "object" mappers for all of the steps along the dots. So `{"foo.bar.baz": 1}` is kind of like a short hand for `{"foo": {"bar": {"baz": 1}}}`. The neat thing about this is that it keeps all of the query parsing stuff unambiguous. I'm not 100% clear on this and I don't have time to read all the code around it to get clear. I've filed https://github.com/elastic/elasticsearch/issues/19149 asking for someone who knows more to add it to the docs.

You may still want to remove the dots - I'm not sure. 5.0 is still in alpha. We allow ourselves to break disk and wire compatibility in alphas and betas so you really shouldn't deploy that to production.
