### ISSUE TITLE
How to set setMaxFetchDepth with Spring Data JPA & Predicates

### ISSUE THREAD

**Issue by Mathangaweera** [querydsl/querydsl#1944]
Hi,

I'm developing a project with Spring Data JPA & QueryDSL (latest versions)
Please consider the given code snippet,

```
 public static Predicate searchReservedSlots(userId) {
 QReservedTimeSlot reservedTimeSlot = QReservedTimeSlot.reservedTimeSlot;
 BooleanBuilder where = new BooleanBuilder();
	if (userId != null) {
		where.or(reservedTimeSlot.timePeriod.schedule.user.id.eq(userId));
	}
	.................
	................
 return where;
 }
```

Value for the `user` is given as null. I think the issue is maximum fetch depth. I added hibernate property to persistance.xml. but it wasn't success.
`<prop key="hibernate.max_fetch_depth">3</prop>`

Let me know a solution for this ?

**Comment by Shredder121** [comment]
This is customizable with `@QueryInit`, [to make the paths initialize deeper](http://www.querydsl.com/static/querydsl/4.1.2/reference/html_single/#d0e2260).
