### ISSUE TITLE
Cannot instantiate JPASubQuery

### ISSUE THREAD

**Issue by terryoh** [querydsl/querydsl#1945]
Hi everybody, 

I'm playing around a bit with querydsl 4.1.2 and i'm trying to build a query using subqueries. However i cannot instantiate a subquery as it is protected and has a protected constructor. (see image)

Everybody else on the internet seems to able to code something like:

query.from(employee)
    .where(employee.weeklyhours.gt(
        **new JPASubQuery().**from(employee.department.employees, e)
        .where(e.manager.eq(employee.manager))
        .unique(e.weeklyhours.avg())
    )).list(employee);

However obviously i cannot do that using JPASubquery from querydsl-jpa-4.1.2.jar. Am i using the wrong jar or am i totally on the wooden path?

Thank you so much for the suppert and every hint. 

![unbenannt](https://cloud.githubusercontent.com/assets/11976599/16485157/9ca40aee-3ebd-11e6-9b42-9a47e024a3c0.JPG)

**Comment by Shredder121** [comment]
That syntax is from Querydsl 3, in Querydsl 4 you use [`JPAExpressions.select`](https://github.com/querydsl/querydsl/blob/master/querydsl-jpa/src/main/java/com/querydsl/jpa/JPAExpressions.java#L34-L43).

This allows you to statically import the method, so your snippet would something like:

```
query.select(employee)
    .from(employee)
    .where(employee.weeklyhours.gt(
        /*JPAExpressions.*/select(e.weeklyhours.avg()).from(employee.department.employees, e)
            .where(e.manager.eq(employee.manager))
    ));
```

**Comment by terryoh** [comment]
Wow thank you a lot for this incredibly fast response, Ruben. 

Is this anywhere documented?

**Comment by Shredder121** [comment]
Hmm, it should be.
Chapter 2.1 of the reference documentation is about JPA Integration.
2.1.13 talks about subqueries.
http://www.querydsl.com/static/querydsl/4.1.2/reference/html_single/#d0e410

If there is anything missing, let us know.

**Comment by terryoh** [comment]
Ok my bad. It seems like i have been looking at the wrong documentation the whole day. My apologies. 

Thank you again and have a great day!

**Comment by Shredder121** [comment]
Glad that it's solved.
Have a great day as well.
