### ISSUE TITLE
Mandatory property used in every query

### ISSUE THREAD

**Issue by Tibor17** [querydsl/querydsl#1953]
I have a question.
Do we have any possibility to force the developer to use e.g. TenantID in query?
For instance this:
```
@Mandatory
@ManyToOne
private Tenant tenant;
```
Such of queries `select * from Contract e where e.tenant = :tenant` do not fail at runtime.
Query without using mandatory property `select * from Contract` would fail.

**Comment by Shredder121** [comment]
I don't think there is a good way of checking 'mandatory' elements of a query.
You can however do preprocessing by using visitors, this allows pluggability of when and when not to validate.
You can use `PathsExtractor` to get all the elements used.
Then you can build something around this:
```java
List<Path<?>> paths = new ArrayList<Path<?>>();
query.getMetadata().getWhere().accept(PathsExtractor.DEFAULT, paths);
paths.contains(QContract.contract.tenant);

```

**Comment by timowest** [comment]
Alternatively you can just prepare your query with that condition before you populate it further.

**Comment by Tibor17** [comment]
Thank you @Shredder121 @timowest , I will try that.
