### ISSUE TITLE
Allow ORDER BY on properties not implementing Comparable

### ISSUE THREAD

**Issue by maffe** [querydsl/querydsl#1954]
I think the generic type parameter of `OrderSpecifier` should not be restricted to types implementing `Comparable`.

Example:
I have a JPA entity (`Tariff`) with a property `Optional<YearMonth> end` (and an `AttributeConverter` mapping missing values to `Optional.empty()`).
I can do this:

```
final QTariff qt = QTariff.tariff;
final List<Tariff> tl = new JPAQuery<Tariff>(em)
  .select(qt)
  .from(qt)
  .orderBy(new OrderSpecifier<Comparable<?>>(Order.ASC,
  (com.querydsl.core.types.Expression<Comparable<?>>) (Object) qt.end))
  .fetch();
```

This works, but the typecast is ugly. The resulting JPQL query is

```
select tariff
from Tariff tariff
order by tariff.end asc
```

which works just fine.

I also tried `@QueryType(PropertyType.COMPARABLE)` on the `Optional<YearMonth>` but then `QTariff` didn’t compile.

I think it’s
- rather common to have an `javax.persistence.AttributeConverter` to decouple database from Java types
- uncommon for a DBMS not to be able to sort on an expression like a column
- not required by JPA to have this restriction
- reasonable to use `java.util.Optional` which doesn’t implement `Comparable` and cannot be extended or more complex custom types for fields (and not just in getters/setters, that’s not a reasonable place to do the conversion if the custom type is used in many places, that’s what `AttributeConverter`s with `@javax.persistence.Converter(autoApply = true)` are for)

**Comment by timowest** [comment]
Should there be instead unwrapping of `Optional<T>` to `T`in the querydsl models?

**Comment by maffe** [comment]
That would work for me right now, but I think it would be nicer to have the flexibility of using any type (with an appropriate `AttributeConverter` of course).

**Comment by maffe** [comment]
In a similar case I need to use a `between` expression with an `Optional<YearMonth>`. For now I changed `Optional<YearMonth>` properties to `YearMonth` in my model. As `Optional` is probably the most important currently unsupported type, the unwrapping you suggested sounds reasonable. If the `T` extends `Comparable`, a `ComparablePath` should be generated instead of a `SimplePath<Optional<T>>` (I’m not sure if `ComparablePath<Optional<T>>` or `ComparablePath<T>`, probably the latter would be easier to work with).

**Comment by jwgmeligmeyling** [comment]
> Should there be instead unwrapping of `Optional<T>` to `T`in the querydsl models?

Optional fields are generally discouraged. I'd stick to nullable fields and wrap them in `Optional.ofNullable` inside the getters.

No need for custom types, attribute convertors, no problems with simple query features (like operators) and the appropiate metamodel will be generated as well.

**Comment by maffe** [comment]
As I mentioned above, there are other types (for example, `InetAddress`) which do not implement `Comparable` but can be sorted by the database – QueryDSL is missing a clean, easy way to do that with those types.

**Comment by jwgmeligmeyling** [comment]
There are various ways to map an `InetAddress` in various database products. Some of these declare an ordering, but not all of them do. Some might support only Ipv4, some only Ipv6, some only declare ordering between IP's of the same version. And some actually store subnets instead of single inet addresses. The ordering for these types is not well defined.

If you really need it for your application and it works well with the schema you've set up, by all means just use a raw typed order specifier: `new OrderSpecifier(Order.ASC, Expressions.path(InetAddress.class, "exammple"), OrderSpecifier.NullHandling.NullsFirst)`. But we cannot support an use case that is going to cause issues for the majority of users.
