### ISSUE TITLE
Cannot use query transform with offset and/or limit (infinite scroll)

### ISSUE THREAD

**Issue by fabiohaertel** [querydsl/querydsl#1962]
Hi!

Im trying to group my query results using the transform function.

Query:
`select documentEntityInfo
from DocumentEntityInfo documentEntityInfo
  left join fetch documentEntityInfo.defaultTemplate
  left join fetch documentEntityInfo.formLayout
where lower(documentEntityInfo.typeName) like ?1 escape '!' and lower(documentEntityInfo.title) like ?1 escape '!'
order by documentEntityInfo.creationDate asc`

Java:
`LinkedHashMap<?, List<T>> result = (LinkedHashMap) query
                .transform(GroupBy.groupBy(groupBy).as(GroupBy.list(qEnt)));`

When I apply offset and limit to the query

`query.offset(page.getCalculatedStartRow());
query.limit(page.getPageSize());`

I get this error:

**11:06:28,170 ERROR SqlExceptionHelper:146 - Column 'neoId1_376_1_' specified more than once 'inner_query'.
11:06:28,171 ERROR SqlExceptionHelper:146 - Column  'neoId1_376_1_' specified more than once  'query'.**

I couldn't find a solution. 
Is it a limitation of the transform function? Any alternatives?

Thanks!

**Comment by timowest** [comment]
Which Querydsl version do you use?

**Comment by fabiohaertel** [comment]
Im using 4.1.1.

Thanks.

**Comment by timowest** [comment]
Looks like Querydsl JPA, could you confirm? Also please provide the used SQL. The Query looks like JPQL. What database do you use?
