### ISSUE TITLE
Inner join added ON condition to previously performed JOIN

### ISSUE THREAD

**Issue by mbadarau** [querydsl/querydsl#1964]
Hello,
We have some strange behavior. I'll try to provide both queries:
Generated query, I think you can ignore select clause:
"select 
placemetad0_.dplam2_id as dplam1_5_0_, placematch1_.plam2_id as plam1_8_1_, placemetad0_.dplam2_createdBy as dplam2_5_0_, 
placemetad0_.dplam2_creationDate as dplam3_5_0_, placemetad0_.dplam2_deleted as dplam4_5_0_, placemetad0_.dplam2_updateDate as dplam5_5_0_, 
placemetad0_.dplam2_updatedBy as dplam6_5_0_, placemetad0_.dplam2_uuid as dplam7_5_0_, placemetad0_.dplam2_countryCode as dplam8_5_0_, 
placemetad0_.dplam2_latLngMatched as dplam9_5_0_, placemetad0_.dplam2_idplacematch2 as dplam15_5_0_, placemetad0_.dplam2_placeNameMatched as dplam10_5_0_, 
placemetad0_.dplam2_processed as dplam11_5_0_, placemetad0_.dplam2_processedDate as dplam12_5_0_, placemetad0_.dplam2_userStartDate as dplam13_5_0_, 
placemetad0_.dplam2_userStopDate as dplam14_5_0_, placematch1_.plam2_createdBy as plam2_8_1_, placematch1_.plam2_creationDate as plam3_8_1_, 
placematch1_.plam2_deleted as plam4_8_1_, placematch1_.plam2_updateDate as plam5_8_1_, placematch1_.plam2_updatedBy as plam6_8_1_, 
placematch1_.plam2_uuid as plam7_8_1_, placematch1_.plam2_countryCode as plam8_8_1_, placematch1_.plam2_additionalInformations as plam9_8_1_, 
placematch1_.plam2_businessZipCode as plam10_8_1_, placematch1_.plam2_lastAdministrativeDivision as plam11_8_1_, placematch1_.plam2_latLng as plam12_8_1_, 
placematch1_.plam2_line1 as plam13_8_1_, placematch1_.plam2_idplace as plam17_8_1_, placematch1_.plam2_placeName as plam14_8_1_, 
placematch1_.plam2_uuiduser as plam15_8_1_, placematch1_.plam2_zipCode as plam16_8_1_, placematch1_.plam2_idgender as plam18_8_1_ 
from place.tm_metadataplacematch2_dplam2 placemetad0_ 
inner join place.tm_placematch2_plam2 placematch1_ on placemetad0_.dplam2_idplacematch2=placematch1_.plam2_id 
inner join place.tm_placematch2_plam2 placematch2_ on placemetad0_.dplam2_idplacematch2=placematch2_.plam2_id and (placeentit3_.pla_uuid='4028f62a-10e8-11e5-a0f0-c3b19bf77afb') 
inner join place.tr_place_pla placeentit3_ on placematch2_.plam2_idplace=placeentit3_.pla_id"

AND

"select placeMetadataMatch2Entity
from PlaceMetadataMatch2Entity placeMetadataMatch2Entity
  inner join fetch placeMetadataMatch2Entity.placeMatchEntity
  inner join placeMetadataMatch2Entity.placeMatchEntity.placeEntity with placeMetadataMatch2Entity.placeMatchEntity.placeEntity.uuid = ?1"

this is very strange

**Comment by Shredder121** [comment]
What does your Querydsl query look like?
What versions of Querydsl and related libraries do you use?

**Comment by mbadarau** [comment]
QAbstractMetadataPlaceMatchEntity qEntity = placeMatchType.getMetadataQEntity();
        HibernateQueryFactory factory = new HibernateQueryFactory(getCurrentSession());
        AbstractMetadataPlaceMatchEntity<? extends AbstractPlaceMatchEntity> abstractMetadataPlaceMatchEntity = factory
                .selectFrom(qEntity).innerJoin(qEntity.placeMatchEntity._super).fetchJoin()
                .innerJoin(qEntity.placeMatchEntity.placeEntity)
                .on(QPlaceEntity.placeEntity.uuid.eq(placeUuid),
                QPlaceEntity.placeEntity.deleted.isFalse())
                .fetchOne();
        return this.placeMatchMetadataEntityConverter.fromEntityToDTO(abstractMetadataPlaceMatchEntity);
I'm using latest version of Querydsl.

**Comment by timowest** [comment]
What kind of query do you want to express? 
It looks like you try to use JPQL like SQL.

**Comment by mbadarau** [comment]
I'm not fetching last join, thus ON clause should work. But instead of generating WITH it appends condition with AND to previously defined join. And this is strange.
I'm trying to use the power of joins. 
Thanks for reply. I can go deeper to find out the problem.

**Comment by timowest** [comment]
could you try the following

```
QAbstractMetadataPlaceMatchEntity qEntity = placeMatchType.getMetadataQEntity();
    HibernateQueryFactory factory = new HibernateQueryFactory(getCurrentSession());
    AbstractMetadataPlaceMatchEntity<? extends AbstractPlaceMatchEntity> abstractMetadataPlaceMatchEntity = factory
            .selectFrom(qEntity).innerJoin(qEntity.placeMatchEntity._super).fetchJoin()
            .innerJoin(qEntity.placeMatchEntity, qPlaceMatchEntity)
            .innerJoin(qPlaceMatchEntity.placeEntity, qPlaceEntity)
            .on(qPlaceEntity.uuid.eq(placeUuid), qPlaceEntity.placeEntity.deleted.isFalse())
            .fetchOne();
```

For non-fetch joins it's advisable to use aliases, otherwise they might not be used properly.
