### ISSUE TITLE
Cache solution recommendation

### ISSUE THREAD

**Issue by pvcastro** [querydsl/querydsl#1965]
Hi there,

I use projected queries a lot in my projects, and need a recommendation on what would be a good solution for caching these queries' results.

I tried using hibernate's 2nd level cache with ehcache and setting .setCacheable on the queries, but this doesn't seem to work. I'm guessing it's not supposed to work with projected queries, right?

Could I get some recommendations for this?

Thanks!

**Comment by timowest** [comment]
Querydsl doesn't provide any caching integration. One way to solve this would be to use Spring's caching abstractions at the DAO/Service level http://docs.spring.io/spring/docs/current/spring-framework-reference/html/cache.html

**Comment by timowest** [comment]
The Querydsl Google Group is a better place for support questions

**Comment by pvcastro** [comment]
Great, thanks! I'll remember this for my next support question!
