### ISSUE TITLE
...ConstantImpl cannot be cast to ...Predicate

### ISSUE THREAD

**Issue by hylkevds** [querydsl/querydsl#1966]
I'm trying to do some boolean logic with constants. To do this I've created a class:

```
public static class ConstantBooleanExpression extends BooleanExpression {

        public ConstantBooleanExpression(final Boolean constant) {
            super(ConstantImpl.create(constant));
        }

        @Override
        @Nullable
        public <R, C> R accept(Visitor<R, C> v, C context) {
            return v.visit((Constant<Boolean>) mixin, context);
        }
    }
```

However when I use this class by doing something like:

```
ConstantBooleanExpression t = new ConstantBooleanExpression(Boolean.TRUE);
ConstantBooleanExpression f = new ConstantBooleanExpression(Boolean.FALSE);
QTesttable qt = QTesttable.testtable;
SQLQuery<Tuple> query = createQueryFactory()
                .select(qt.id, qt.description)
                .from(qt)
                .where(t.or(f));
query.fetchFirst();
```

I get an exception: 
```
java.lang.ClassCastException: com.querydsl.core.types.ConstantImpl cannot be cast to com.querydsl.core.types.Predicate
	at com.querydsl.core.types.dsl.BooleanExpression.or(BooleanExpression.java:105)
```

I've extended my test project that demonstrates the error:
https://github.com/hylkevds/QueryDslTests
If you point it at an empty database (in pom.xml and src/main/resources/db.properties) it'll create a table with some data and run a unit test against it. For me that fails with the above mentioned exception.

I'm guessing the two Boolean constants in ConstantImpl.Constants should also implement Predicate?

**Comment by timowest** [comment]
You have two options to fix this setup
* Use custom constants that implement the Predicate interface instead of ConstantImpl
* Use Expressions.TRUE and Expressions.FALSE instead

**Comment by hylkevds** [comment]
Indeed, that works.

Maybe it would be good to have Expressions.TRUE and Expressions.FALSE also implement com.querydsl.core.types.Constant, and redirect the two Boolean constants in ConstantImpl.Constants to the two in Expressions?
Then users don't need to treat boolean constants differently from other constants.

**Comment by timowest** [comment]
Expressions.TRUE and FALSE aren't constants, they are template expressions, they encode the values as serialized "true" and "false"
