### ISSUE TITLE
limit and offset in query dsl 

### ISSUE THREAD

**Issue by teo89** [querydsl/querydsl#1967]
I have the following query

```
JPAQuery<Supplier> q2 = new JPAQueryFactory(em).selectFrom(qSupplier).limit(5);
List<Supplier> suppliers = q2.fetch();
```

The sql query is 
 ```
select
        supplier0_.id as id1_18_,
        supplier0_.CONTRACT_DATE as CONTRACT2_18_,
        supplier0_.DOMAIN_OF_ACTIVITY as DOMAIN_O3_18_,
        supplier0_.IS_GROUP as IS_GROUP4_18_,
        supplier0_.lot as lot5_18_,
        supplier0_.name as name6_18_,
        supplier0_.STATUS_ID as STATUS_I9_18_,
        supplier0_.GROUP_ID as GROUP_I10_18_,
        supplier0_.TAX_REG_NUM as TAX_REG_7_18_,
        supplier0_.TAXPAYER_ID as TAXPAYER8_18_
    from
        DF_SUPPLIER supplier0_ limit ?
```

As you can see query is not correct. I am using 4.0.7 version . How i can use limit and offset in querydsl?

I get error :
ORA-00933: SQL command not properly ended
javax.persistence.PersistenceException: org.hibernate.exception.SQLGrammarException: could not extract ResultSet

**Comment by Shredder121** [comment]
We don't generate the SQL only the JPQL.
So the issue is probably with your JPA provider.

**Comment by teo89** [comment]
I am using hibernate.

**Comment by Shredder121** [comment]
And which hibernate dialect are you using?

**Comment by teo89** [comment]
4.3.6.Final

**Comment by Shredder121** [comment]
Oh I'm sorry.
I meant these dialects.
https://docs.jboss.org/hibernate/orm/4.3/javadocs/org/hibernate/dialect/package-summary.html

I believe there is a wrong dialect condigured, since Oracle uses a different structure for paginated queries .
I'm sure hibernate supports this, as long as you tell hibernate to use the right dialect.

**Comment by teo89** [comment]
You are right, I had a wrong dialect thank you for the immediate response
