### ISSUE TITLE
How to set naming strategy for PostgresQuery

### ISSUE THREAD

**Issue by tak2siva** [querydsl/querydsl#1976]
Im using Query DSL for my project

Have some entity like

```
@Entity
@Table(name = "table_name")
class TableName {
 @Column(name="column_name")
  private Integer columnOne;
}
```

```
QTableName table = QTableName.tableName
PostgresQuery postgresQuery = 
    new PostgresQuery(dataSource.getConnection(),
    PostgresTemplates.DEFAULT);

postgresQuery.from(table).list(table.columnOne);
```

Above code executes query like

`select columnOne from tableName;`

Whereas its supposed execute like(as per naming strategy configured for JPA)

`select column_one from table_name;`

Not sure how to send entitymanager properties to PostgresQuery object. Am I missing something ? Any examples will be helpful 

PS: I'm trying to use PostgresQuery Instead of JPAQuery because I need to use window functions like rank(), row_number()

**Comment by Shredder121** [comment]
More details needed, looks like you're mixing Querydsl SQL and Querydsl JPA.

**Comment by tak2siva** [comment]
@Shredder121 How to configure naming strategy for Querydsl SQL ? Its not recognizing correct column names and table names (values of `@Table` and `@Column`) 

I couldnt find any documentation or example either. What am I missing ?

**Comment by Shredder121** [comment]
There is no such thing as a naming strategy for Querydsl SQL, because we don't name the tables.
Querydsl SQL takes the database as input, and makes model objects based on that.
http://www.querydsl.com/static/querydsl/latest/reference/html_single/#d0e725

`@Table` and `@Column` are JPA annotations, and are not used in Querydsl SQL.
You can generate the SQL metamodel after your JPA Persistence Provider generated the tables.

**Comment by tak2siva** [comment]
In gradle where do I add those configurations ? 
https://gist.github.com/EdwardBeckett/5377401

**Comment by Shredder121** [comment]
I think you should either be able to call the ant task(not sure?), or you could write a class that (configures and) invokes the exporter.
Then you can build a task out of that so you can run it on demand and check that in.

**Comment by Shredder121** [comment]
If you think the documentation is lacking gradle instructions, you can also add a PR for it with your findings.
