### ISSUE TITLE
MySQL null schema

### ISSUE THREAD

**Issue by natros** [querydsl/querydsl#1977]
Hello, 

I'm using maven with querydsl sql (4.1.3) generator to generate some classes from a mysql 5.7.13 database

The basic maven configuration I'm using is

``` xml
 <jdbcDriver>com.mysql.jdbc.Driver</jdbcDriver>
              <jdbcUrl>jdbc:mysql://127.0.0.1:3306/maxmail_cliente_123?useSSL=false</jdbcUrl>
              <jdbcUser>root</jdbcUser>
              <jdbcPassword>root123</jdbcPassword>
              <packageName>foo.bar.entities.maxmailclient</packageName>
              <targetFolder>${project.build.sourceDirectory}</targetFolder>
              <exportBeans>true</exportBeans>
              <schemaToPackage>true</schemaToPackage>
```

And in the generated Q\* files, the schema is set to "null". From what I can see the mysql jdbc driver uses the catalog information instead of schema.

``` java
 public QMaxmailingClientes(String variable) {
        super(MaxmailingClientes.class, forVariable(variable), "null", "maxmailing_clientes");
        addMetadata();
    }

    public QMaxmailingClientes(String variable, String schema, String table) {
        super(MaxmailingClientes.class, forVariable(variable), schema, table);
        addMetadata();
    }

    public QMaxmailingClientes(Path<? extends MaxmailingClientes> path) {
        super(path.getType(), path.getMetadata(), "null", "maxmailing_clientes");
        addMetadata();
    }

    public QMaxmailingClientes(PathMetadata metadata) {
        super(MaxmailingClientes.class, metadata, "null", "maxmailing_clientes");
        addMetadata();
    }
```

I'm using printSchema in the template because I need to access different databases in a single connection

``` java
SQLTemplates templates = MySQLTemplates.builder()
        .printSchema()
        .build();
```

but I'm getting errors:

```
com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'null.maxmailing_lists' doesn't exist
```

Most of the time I'm using oracle and everything is perfect, but not with mysql.

**Comment by oxygenecore** [comment]
I have the same issue, but this is the only relevant page I can find on Internet about it. I don't understand - is QueryDSL known to not support Mysql 5.X? I can't find anywhere what is supported (similar to what Lukas has here https://www.jooq.org/download/support-matrix).

**Comment by lalilisa** [comment]
How did you config SQLTemplates? If you config printSchema() in SQLTemplates, schema at Qtable is always added in query, comment line //.printSchema() and it worked for me. Goodluck
