### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by mbadarau** [querydsl/querydsl#1984]
Does it possible to generate Querydsl types from a specific schema, for using Native SQL in JPA queries if others are generated from Hibernate Mapped entities. Configuration to be performed on gradle.

Thanks

**Comment by timowest** [comment]
Official Gradle support is not provided, but Maven based SQL schema based code generation is documented here http://www.querydsl.com/static/querydsl/4.1.3/reference/html_single/#d0e716
