### ISSUE TITLE
Feature Request: Issue warning when Expressions.path used with unknown property of known Q-type

### ISSUE THREAD

**Issue by bennesher** [querydsl/querydsl#1991]
Some of the static error-checking provided by QueryDSL can be bypassed when using `Expressions.path(Class<?>,Path<?>,String)` to build a column reference.  I know that part of the reason that is allowed is to support SQL generation without generated Q-types, but there is a difference between the situation where there is no available Q-type and a programmer error of passing an invalid column name to Expressions.path.  A warning in the latter case, whether at the time of the call to Expressions.path, or at SQL generation time, would aid in troubleshooting.

(see #1980 )

**Comment by Shredder121** [comment]
Could you for completeness also add a snippet here with what would not be allowed?

The Class, QClass and snippet.

Then we can think of what would be a good way to fix it.
