### ISSUE TITLE
how to generate Q class via plugin not use annotation in POJO

### ISSUE THREAD

**Issue by cloudSher** [querydsl/querydsl#1995]
hi,I have a problem with Querydsl via plugin generate Q class, I find if want to generate Q class must use annotation except sql schema, so how can I not use annotation appoint the POJO to generate  Q class, 
Is able to via plugin configure a scanner of source package and processor to generate Q class, or have a best way to generate Q class not invade POJO?

**Comment by timowest** [comment]
Querydsl doesn't provide that out of the box, GenericExporter could be maybe changed to support that, but that's currently not planned.
