### ISSUE TITLE
fetch method doen't exist when select enumPath.

### ISSUE THREAD

**Issue by uuidcode** [querydsl/querydsl#1997]
querydsl 4.1.3 using MySQLQueryFactory with Querying SQL.

qProject.projectType is enumPath.
below code, there is error, fetch method doent's exits.
```
select(qProject.projectType, qProject.count())
.from(qProject)
.groupBy(qProject.supportStatus)
.fetch();
```

qProject.name is stringPath.
below code, compiling is OK.
```
select(qProject.name, qProject.count())
.from(qProject)
.groupBy(qProject.name )
.fetch();
```

Thanks.

**Comment by timowest** [comment]
What is the type returned by groupBy(...) in your first example?

**Comment by uuidcode** [comment]
I think it's IntelliJ IDEA 13.1.6 bug.
Below code, compiling OK, testing OK(sorry, it's my mistake above metions.)
But IDEA show error indicator.
Thanks.

```
select(qProject.projectType, qProject.count())
.from(qProject)
.groupBy(qProject.supportStatus)
.fetch();
```
![20160821](https://cloud.githubusercontent.com/assets/17076435/17837902/45943344-67fa-11e6-95d7-36efc0111866.png)

![20160821_01](https://cloud.githubusercontent.com/assets/17076435/17837956/6ef7b674-67fb-11e6-8f37-0b1b21bdc15d.png)
