### ISSUE TITLE
@Since API documentation on StringExpression?

### ISSUE THREAD

**Issue by chenrui333** [querydsl/querydsl#1998]
When I tried to search when did `likeIgnoreCase` of `StringExpression` firstly get introduced, I found it is quite difficult, can we add `@Since` annotation to StringExpression API? That would be helpful.

Thanks,

**Comment by chenrui333** [comment]
This is the [api docs reference](http://www.querydsl.com/static/querydsl/4.0.7/apidocs/com/querydsl/core/types/dsl/StringExpression.html#likeIgnoreCase-com.querydsl.core.types.Expression-)

**Comment by Shredder121** [comment]
For the 'when it was introduced' question you can for example use git blame.
https://github.com/querydsl/querydsl/blame/master/querydsl-core/src/main/java/com/querydsl/core/types/dsl/StringExpression.java#L373-L391

**Comment by Shredder121** [comment]
I'll leave the answering of the question of `@since tags` to @timowest.

**Comment by chenrui333** [comment]
OK, that looks great (did not think about that) !

But still it would be nice that `@since` could be added to the code for documentation reference. it may incur the maintenance burden as well. I can take it to read the source code. 

Feel free to close the issue.
