### ISSUE TITLE
Dynamic queries doesn't allow to query property of a descendant class

### ISSUE THREAD

**Issue by casteng** [querydsl/querydsl#2001]
I use Querydsl-jpa  3.7.4 + Hibernate 4.3.11 and Spring Data repository.
The class hierarchy:

```
@Entity
@Table
@Inheritance(strategy = InheritanceType.SINGLE_TABLE)
public abstract class VObject {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
}

@Entity
public class RObject extends VObject {
    @ManyToOne
    private Street street;
}

@Entity
public class Request {
    @Id
    @GeneratedValue
    private Long id;

    @ManyToOne(optional = false)
    private VObject obj;
}

```

I need different queries for Request for different VObject descendants. E.g. for query containing only request with obj of RObject class I need to filter them with fields specific for RObject.
There is BeanPath.as(Class<U> clazz) method which seems to be the solution.
But when I try to use it:

```
QRequest vr = QRequest.request;
BooleanBuilder builder = new BooleanBuilder();

QRObject obj = vr.obj.as(QRObject.class);
builder.and(obj.street.fullTitle.containsIgnoreCase(filter.getAddress()));    // NPE here as obj.street is null
```

I get NPE as obj.street is null.
It doesn't seem to get initialized.

There is a workaround:
Just set obj.street to "new QStreet(new PathMetadata<String>(obj, "street", PathType.PROPERTY))" via reflection and the query appears to work.

But it seems to me like a bug.

**Comment by timowest** [comment]
The NPE happens because of Path initialization limits http://www.querydsl.com/static/querydsl/4.1.3/reference/html_single/#d0e2260

To fix the issue add an explicit join between request and request.obj:
```
query.from(request).innerJoin(request.obj, obj).where(...
```

**Comment by casteng** [comment]
Thanks for your answer.

But the NPE happens when building Predicate object which used as parameter for where() method of query. I.e. before it's possible to use explicit join.

When I building the predicate I can use BeanPath.as() method which seems to work incorrectly.

If I trying to use @QueryInit annotation:

```
@Entity
public class Request {
    @Id
    @GeneratedValue
    private Long id;

    @ManyToOne(optional = false)
    @QueryInit({"street"})
    private VObject obj;
}
```

I'm getting the compilation error:
Illegal inits of Request.obj: street not found.

It may be correct as Request.obj is of type VObject which doesn't have such property. Only it's descendant (RObject) does.

**Comment by timowest** [comment]
The joins are serialized before where, you can refer to joined elements in the where part.

**Comment by casteng** [comment]
The code:
```
QRequest vr = QRequest.request;
BooleanBuilder builder = new BooleanBuilder();

QRObject obj = vr.obj.as(QRObject.class);
builder.and(obj.street.fullTitle.containsIgnoreCase(filter.getAddress()));    // NPE here as obj.street is null

JPAQuery query = new JPAQuery(em).from(vr).where(builder.getValue());
```

Results in NPE at the commented line. I.e. **before** call to JPAQuery.where().

The line:
`QRObject obj = vr.obj.as(QRObject.class);`

Doesn't initialize instance of QRObject fully. Fields which belong to VObject are initialized, but not ones which belong to RObject (street in that case).

Initialization of the field via reflection hack solve the NPE and the query work as expected.

But the necessity of this hack seems like a bug. And I'm not sure that such initialization is correct and will always work.

**Comment by casteng** [comment]
Why this issue is labeled as resolved?
It's definitely a bug as [Casting expressions](http://www.querydsl.com/static/querydsl/4.1.3/reference/html_single/#d0e2121) works incompletely.

**Comment by Shredder121** [comment]
We're investigating a bit, I see what you mean.

**Comment by ernestorumo** [comment]
I have the same problem and know that issue has many time, but ¿could you detail the workaround used?

> There is a workaround:
> Just set obj.street to "new QStreet(new PathMetadata(obj, "street", PathType.PROPERTY))" via reflection and the query appears to work.

**Comment by jwgmeligmeyling** [comment]
I think my PR for treated paths (#2530) can also be considered a fix for this, as the treated paths have all default PathInits sets.
