### ISSUE TITLE
DB_LINK Postgresql

### ISSUE THREAD

**Issue by adrianobr** [querydsl/querydsl#2002]
hello, I need to use the queryDSL with db_link. https://www.postgresql.org/docs/9.3/static/dblink.html

Has anyone ever experienced this? Can you tell me if it would work?

`select distinct cd_departamento, trim(departamento.descricao)as descricao
from tb_produto p
inner join tb_documentoitem di on di.cd_produto = p.id_produto
inner join tb_documento d on di.cd_documento = d.id_documento
inner join dblink('dbname=feira user=sysdba', 'select cod as codigo, dsc as descricao from GCEDEP01') 
as departamento(codigo numeric(3,0), descricao varchar(30)) on departamento.codigo = p.cd_departamento 
where d.dt_movimento between '2016-08-23' and '2016-08-25'
order by descricao
`

**Comment by timowest** [comment]
The left hand side for the join could be expressed using a RelationalFunctional call, but the right hand side of the join must be a Path in Querydsl.

Even if you would manage to construct this part in Querydsl, you might not be able to express it in a typesafe way.
