### ISSUE TITLE
Subquery alias does not work in querydsl 4

### ISSUE THREAD

**Issue by mdomasevicius** [querydsl/querydsl#2005]
After upgrading from querydsl 3.x to 4.1.2 path aliases do not wok as they used to.

Working example:

```
new JPAQuery<Tuple>(em)
    .select(QPerson.person.id.as("idAlias"))
    .from(QPerson.person)
    .orderBy(new OrderSpecifier<>(DESC, stringPath("idAlias")))
    .fetch();
```

Broke (worked in 3.x):

```
new JPAQuery<Tuple>(em)
    .select(QPerson.person.id.as("idAlias"),
        JPAExpressions.select(count.as(numberPath(Long.class, "childrenCount")))
        .from(QChildren.children)
        .where(QChildren.children.father.eq(QPerson.person))
)
    .from(QPerson.person)
    .orderBy(new OrderSpecifier<>(DESC, stringPath("childrenCount")))
    .fetch();
```

Stacktrace reads:

```
javax.persistence.PersistenceException: org.hibernate.exception.SQLGrammarException: could not prepare statement
    at org.hibernate.jpa.spi.AbstractEntityManagerImpl.convert(AbstractEntityManagerImpl.java:1692)
    at org.hibernate.jpa.spi.AbstractEntityManagerImpl.convert(AbstractEntityManagerImpl.java:1602)
    at org.hibernate.jpa.internal.QueryImpl.getResultList(QueryImpl.java:492)
    at com.querydsl.jpa.impl.AbstractJPAQuery.getResultList(AbstractJPAQuery.java:160)
    at com.querydsl.jpa.impl.AbstractJPAQuery.fetch(AbstractJPAQuery.java:202)
```

While still working example constructs SQL which ends `order by col_0_0_ desc` (generated column name) in broken example query ends with `order by childrenCount desc` but the entire query does not have such alias.

**Comment by Shredder121** [comment]
And what if you use `JPAExpressions.select()` instead?

**Comment by mdomasevicius** [comment]
Sorry I have made a mistake in my original post. It is actually `JPAExpressions.select()` not `Expressions.select()`.

**Comment by timowest** [comment]
Here is a workaround, I will try to find a better solution:

new JPAQuery<Tuple>(em)
    .select(QPerson.person.id.as("idAlias"),
        ExpressionUtils.as(
           JPAExpressions.select(count)
          .from(QChildren.children)
          .where(QChildren.children.father.eq(QPerson.person)), "childrenCount")
)
    .from(QPerson.person)
    .orderBy(new OrderSpecifier<>(DESC, stringPath("childrenCount")))
    .fetch();

**Comment by Shredder121** [comment]
Question, would you also be able to submit a PR to `QUERYDSL_3`? 😄
