### ISSUE TITLE
[QueryDSL-Collections]issue related to left join

### ISSUE THREAD

**Issue by scupperscupper** [querydsl/querydsl#2009]
The class CollQuerySerializer contains a bug in the 

> public Void visit(Path<?> path, Void context) 

lines[97 - 101] : the append((path.getType()).getName()).append(">get(");
should be replaced by something like this :

```
                    // field access by reflection
                    append(CollQueryFunctions.class.getName() + ".<");
                    append((path.getType()).getName());
                    if((path.getType()).getName().equals("java.util.List")) {
                        if(path instanceof ParameterizedPathImpl) {
                            append("<"+((ParameterizedPathImpl) path).getParameter(0).getName()+">");
                        }
                    }
                    append(">get(");
                    handle(parent);
                    append(", \"" + property + "\")");
```

Since I no nothing about the architecture I leave this part for you guys to fix accordingly.
With this the issue with Generics and left join should be fixed

**Comment by timowest** [comment]
Could you provide an example where the current serialization logic fails?

**Comment by scupperscupper** [comment]
Hi

please open this link: http://stackoverflow.com/q/39270096/2236205

Best Regards

On 1 Sep 2016 9:05 p.m., "Timo Westkämper" <notifications@github.com> wrote:

Could you provide an example where the current serialization logic fails?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/querydsl/querydsl/issues/2009#issuecomment-244173170>,
or mute the thread

**Comment by Shredder121** [comment]
I'll at least add the test code to the test sources.
