### ISSUE TITLE
Insert value in many to many connection

### ISSUE THREAD

**Issue by teo89** [querydsl/querydsl#2013]
I am trying that query
new JPAUpdateClause(em, qA).where(qA.id.eq(id))
        .set(qA.bs, new JPAQueryFactory(em).selectFrom(qB).where(qB.id.in(listWithIDs)).fetch())
        .execute();

A and B have manyToMany connection. 

This creates a sql query 
 update
       B,
    set
        .=?
    where
        id=?

and i get this error Caused by: java.sql.SQLException: Missing IN or OUT parameter at index:: 2

How we handle many to many connection in create and insert cases with querydsl.
my database is oracle and i have querydsl 4.0.7

**Comment by Shredder121** [comment]
> This creates a sql query

We don't generate SQL queries, could you post the JPQL query instead?
