### ISSUE TITLE
executeWithKeys syntax failure with postgres database.

### ISSUE THREAD

**Issue by melvinmonteiro** [querydsl/querydsl#2015]
I am using querydsl with postgres 
                 <dependency>
            <groupId>com.querydsl</groupId>
            <artifactId>querydsl-sql</artifactId>
            <version>4.1.3</version>
        </dependency>

I get a sql grammar error with postgres, works fine with h2 database.

the returning value in enclosed in double quotes which postgres doesn't parse. 

eg. of the resulting query with excecuteWithKeys results in
insert into users(first_name,last_name) returning "ID"
error is no column "ID" found

Let me know if you need more info.

**Comment by vbartacek** [comment]
See #971
