### ISSUE TITLE
querydsl-codegen: add an option to generate chained setters

### ISSUE THREAD

**Issue by amanteaux** [querydsl/querydsl#2023]
It would be great to be able to generate chained setters in the generated beans. This way we could write something like:

```
MyGeneratedBean bean = new MyGeneratedBean().setProperty1("value").setProperty2("value");
```

If you are ok with the idea, I could do the change in the `BeanSerializer` class to add the option to generate chained setters.

**Comment by amanteaux** [comment]
Do you have any feedback for this feature?

Please do note that if you are ok, I can make the pull request.

**Comment by alexandrebensimon** [comment]
Hello, can we have some update on this issue?

**Comment by amanteaux** [comment]
It would be a nice feature though

**Comment by jwgmeligmeyling** [comment]
What kind of setters would you like to see on the Q classes?

Or are you talking about `querydsl-codegen` use outside of `querydsl-core`/`querydsl-jpa`/`querydsl-sql`?

**Comment by amanteaux** [comment]
Actually the main issue is with `BeanSerializer` in `querydsl-codegen`. It is not possible to extend this class to configure the setters. If I want to do that, I need to completely rewrite the `BeanSerializer` class.

It would be great if the `BeanSerializer#serialize(...)` method was more modular, so it would be easier to extend it and change the way accessors are generated.
