### ISSUE TITLE
Problems with generated QClasses since 4.1.3

### ISSUE THREAD

**Issue by thackel** [querydsl/querydsl#2024]
4.1.3 introduced some "PropertyHandler/Config" and this changed the behavior how fields/properties are being generated.

There is an abstract "base entity" which defines the getter for the ID field which is declared in the subclass:

``` java
@MappedSuperclass
public abstract class BaseEntity implements Serializable {
    public abstract Long getId();
[...]
```

This field is no longer created in the generated class:

``` java
/**
 * QBaseEntity is a Querydsl query type for BaseEntity
 */
@Generated("com.querydsl.codegen.SupertypeSerializer")
public class QBaseEntity extends EntityPathBase<BaseEntity> {
[...]
```

It seems thats not possible with the maven-plugin to set the configuration of the `PropertyHandling` to another value than the default `PropertyHandling.JPA`.
I would expect that configuration option `PropertyHandling.ALL` would restore the former behavior.

**Comment by thackel** [comment]
To get rid of the old issues, i've retested it with the current 4.2.1.
And i had no more problems so far, so i close this issue by myself to clear the view for the important issues.

**Comment by Shredder121** [comment]
Ahh, thanks so much.
