### ISSUE TITLE
querydsl-sql : Joda time should be optional

### ISSUE THREAD

**Issue by amanteaux** [querydsl/querydsl#2025]
I am using Java 8 so I don't want Joda time in my classpath.
Indeed it messes with the imports: if I want to use a `java.time.LocalDate`, I have to be careful not to import `org.joda.time.LocalDate`.

Currently if I try to exclude Joda time from my classpath, I cannot initialize Querydsl because in `JavaTypeMapping`, the `CalendarType` is registered and it depends on Joda time. 
Moreover:
- still in `JavaTypeMapping`, Joda time types are registered,
- the `Configuration` class is final and reference `JavaTypeMapping`, so there is no way around.

In a first step, the modifications that needs to be done are:
- Refactor `AbstractDateTimeType` to remove the Joda time dependency,
- In `JavaTypeMapping`, do the joda time initialization the same way java 8 types are registered,
- Mark joda time as optional in the pom.xml :)

If that is ok, I can do the change.
However, it is a breaking change: libraries and projects depending on querydsl-sql and using joda time will have to explicitly add joda time in their pom.xml, gradle etc.
So the version on which this development will be made has to be decided.

**Comment by janneri** [comment]
Spring Boot will autoconfigure a formatter when joda-time is in classpath. The formatter wants a newer version of joda-time than querydsl. So to me, the joda-time dependency seems pretty useless in 2020 and it's causing problems. I would greatly appreciate this fix!

p.s. Declaring joda-time as a dependency is a trivial fix. I wouldn't worry about this as a breaking change.

**Comment by Neikius** [comment]
> Spring Boot will autoconfigure a formatter when joda-time is in classpath. The formatter wants a newer version of joda-time than querydsl. So to me, the joda-time dependency seems pretty useless in 2020 and it's causing problems. I would greatly appreciate this fix!
> 
> p.s. Declaring joda-time as a dependency is a trivial fix. I wouldn't worry about this as a breaking change.

Same here. Please take the joda-time out.

**Comment by lagnat** [comment]
Another vote to address this issue.  Thank you.

**Comment by digsim** [comment]
Same problem here, we can't update spring-boot any longer. Would be great if we can get rid of joda-time.

**Comment by germatpreis** [comment]
Same problem here.

**Comment by daniel-shuy** [comment]
I've decided to take up this task.

The main issue is how to replace joda-time's [DateTimeFormatter](https://www.joda.org/joda-time/apidocs/org/joda/time/format/DateTimeFormatter.html).

There are 4 alternatives:
- Use [SimpleDateFormat](http://docs.oracle.com/javase/6/docs/api/java/text/SimpleDateFormat.html). The main issue with this is that `SimpleDateFormat` is not thread-safe and is expensive to initialize, which would require creating new instances of `SimpleDateFormat` for each thread using `ThreadLocal`, which has a performance cost.
- Import Apache Commons Lang to use  [FastDateFormat](https://commons.apache.org/proper/commons-lang/apidocs/org/apache/commons/lang3/time/FastDateFormat.html), a thread-safe equivalent to `SimpleDateFormat`. This would however introduce Apache Commons Lang as a new transitive dependency.
- Increase QueryDSL's Java target version to Java 8, which would allow us to use Java 8's [DateTimeFormatter](https://docs.oracle.com/javase/8/docs/api/java/time/format/DateTimeFormatter.html). This would however require dropping support for Java 6/7.
- Use Java 8's [DateTimeFormatter](https://docs.oracle.com/javase/8/docs/api/java/time/format/DateTimeFormatter.html) if Java 8 is available, else use joda-time's [DateTimeFormatter](https://www.joda.org/joda-time/apidocs/org/joda/time/format/DateTimeFormatter.html) if joda-time is imported, else fallback to [SimpleDateFormat](http://docs.oracle.com/javase/6/docs/api/java/text/SimpleDateFormat.html). This would however greatly increase the code complexity.

**Comment by lagnat** [comment]
Java 8 is my vote.

**Comment by daniel-shuy** [comment]
> Java 8 is my vote.
That's my preference as well, however I would need someone from the QueryDSL team to make the decision, as it is a major change

**Comment by jwgmeligmeyling** [comment]
We want to keep supporting Java 7 for 4.x. Java 8 API's can still be used through reflection though. As long as they are not imported, which would prevent classes from loading on Java 7.

**Comment by daniel-shuy** [comment]
@jwgmeligmeyling agreed. I've created a PR using the [SimpleDateFormat](http://docs.oracle.com/javase/6/docs/api/java/text/SimpleDateFormat.html) with `ThreadLocal` approach.

**Comment by daniel-shuy** [comment]
Good news everyone! The upcoming QueryDSL 5.x release will require Java 8+, which allows us to remove the transitive dependency on joda-time, using the Java 8's [DateTimeFormatter](https://docs.oracle.com/javase/8/docs/api/java/time/format/DateTimeFormatter.html) approach, which imo is the cleanest approach.

Many thanks to @jwgmeligmeyling for the Java 8 migration, and for reviewing and merging the PR.
