### ISSUE TITLE
Update Morphia/MongoDB Java Drivers

### ISSUE THREAD

**Issue by Nogyara** [querydsl/querydsl#2027]
Hi guys,

are there any plans to upgrade MongoDB Java drivers (via Morphia) to the 3.x line? They're out for some time now, would be nice to be able to use them.

I just recently upgraded QueryDSL to the latest 4.x version - works like a charm, but attempt to upgrade Morphia to 1.2.x line failed because of just this - QueryDSL relies on Morphia pre-1.0.x (and thus MongoDB Java driver from 2.x.x line), which are binary incompatible with the current version.

Thanks

**Comment by cstrempfer** [comment]
I've created a pull request: https://github.com/querydsl/querydsl/pull/2029

**Comment by Nogyara** [comment]
That was ligthing-fast! Thanks

**Comment by cstrempfer** [comment]
I was working on it even before you asked. ;-)

But note that I'm not a team member of QueryDSL, therefore it could take some time to get this merged. I don't know their schedule.

**Comment by jwgmeligmeyling** [comment]
Drivers are in fact updated in the current master.
