### ISSUE TITLE
About MongodbQuery(in 3.x) and AbstractMongodbQuery(in 4.x) and DBCursor's close method

### ISSUE THREAD

**Issue by yacota** [querydsl/querydsl#2031]
MongodbQuery should call DBCursor's close method every time a runtime exception may occur, for instance when applying the transformer
- in 3.x branch 

```
@Override
    public List<K> list() {
        try {
            DBCursor cursor = createCursor();
            List<K> results = new ArrayList<K>();
            for (DBObject dbObject : cursor) {
                results.add(transformer.apply(dbObject));
            }
            return results;
        } catch (NoResults ex) {
            return Collections.emptyList();
        }
    }
```
- or its counterpart method in 4.x

```
@Override
    public List<K> fetch() {
        try {
            DBCursor cursor = createCursor();
            List<K> results = new ArrayList<K>();
            for (DBObject dbObject : cursor) {
                results.add(transformer.apply(dbObject));
            }
            return results;
        } catch (NoResults ex) {
            return Collections.emptyList();
        }
    } 
```

As stated in MongoDB's docs a DBCursor will be closed after 10 minutes of inactivity, OR if the client has exhausted the cursor, I guess the later is the reason why cursor.close() is never called in MongodbQuery.
https://docs.mongodb.com/manual/tutorial/iterate-a-cursor/#closure-of-inactive-cursors

Last but not least take a look at that the "streaming" method 
`public CloseableIterator<K> iterate()`
which creates an inner CloseableIterator whom again does not close the cursor in its close method.

**Comment by Shredder121** [comment]
Good call.

**Comment by yacota** [comment]
Do you want me to send a PR ?

**Comment by Shredder121** [comment]
Well, if we don't get around to it, you can do so.
I'm slowly taking a bit more issues to fix.
This one will be one of them, but if you want you can start a PR of course.
