### ISSUE TITLE
error messages when running gradle plugin

### ISSUE THREAD

**Issue by remmeier** [querydsl/querydsl#2032]
The annotation processor of querydsl gives a number of error messages that should be info/debug messages:

Note: Running JPAAnnotationProcessor
Note: Serializing Embeddable types
Note: Generating ch.adnovum.jcan.jpa.audit.QAuditInfo for [ch.adnovum.jcan.jpa.audit.AuditInfo]

environment: gradle, windows, java 8

**Comment by Shredder121** [comment]
Which gradle plugin do you use?
I think you mean [this gradle plugin](https://github.com/ewerk/gradle-plugins/tree/master/querydsl-plugin).

It is not hosted or maintained by us.
(or at least, we do not have a gradle plugin)

**Comment by remmeier** [comment]
oh, sorry, the ticket was not quite correct, there is no dedicated plugin, just the querydsl annotation processed plugged into gradle.

**Comment by Shredder121** [comment]
We already [print to the APT messager with `NOTE` level](https://github.com/querydsl/querydsl/blob/master/querydsl-apt/src/main/java/com/querydsl/apt/AbstractQuerydslProcessor.java#L68).
This is the 'informative message' level.
http://grepcode.com/file/repository.grepcode.com/java/root/jdk/openjdk/8u40-b25/javax/tools/Diagnostic.java#Diagnostic.Kind

**Comment by Shredder121** [comment]
Do you mean the red text during compilation?
I think Gradle doesn't have a way of discerning which text gets printed (javac bad output, or annotation processing tool info output).

**Comment by remmeier** [comment]
yes, the red text. Is a bit annoying as red text is supposed to be a problem.

I think it is a general problem with the notes log level. There is a ticket for that in the jdk:

https://bugs.openjdk.java.net/browse/JDK-6949601

that is open for a while now. It would be helpful if there is is a possiblity to disable the logging messages in querydsl.

**Comment by reegnz** [comment]
I think the problem is that you cannot opt out from just the NOTE messages with javac. you either have INFO and WARN, or you have nothing (see -nowarn flag for javac).

This is quite frustrating for me as well, since if I am curious if my build has warnings, I have to also opt-in for the NOTE level messages, that querydsl prints.

**Comment by reegnz** [comment]
Maybe make it opt-in with 'SupportedOptions' https://docs.oracle.com/javase/8/docs/api/javax/annotation/processing/Processor.html#getSupportedOptions--
Then you could pass a command line arg to javac that enables the NOTE messages when someone still needs it.
