### ISSUE TITLE
Selecting JPAExpressions.type throws java.lang.ClassCastException

### ISSUE THREAD

**Issue by tox87** [querydsl/querydsl#2034]
I am trying to fetch entity class by id  (single table inheritence), but query:
`
from(DOCUMENT).select(JPAExpressions.type(DOCUMENT)).where(DOCUMENT.id.eq(id)).fetchOne();
`
throws java.lang.ClassCastException: java.lang.Class cannot be cast to java.lang.String

Debugging AbstractJPAQuery#getSingleResult shows that I get java.lang.Class but fetchOne casts it to string since JPAExpressions.type(DOCUMENT) returns StringExpression.

QueryDSL-JPA 4.1.4

Looks like the root cause can be the same for #1747

**Comment by flokle** [comment]
If anyone should encounter the same problem:

```Expressions.dslTemplate(Class.class, "type({0})", path)```

Did it for me. Seems to be a very similar solution to the fix proposed in #1747
