### ISSUE TITLE
please add support to listagg for [OVER (PARTITION BY )] analytical functions

### ISSUE THREAD

**Issue by TYCOBKA** [querydsl/querydsl#2040]
Trying to convert Oracle Native queries to Querydsl. LISTAGG analytics function supports [OVER (PARTITION BY )] as of 11g release 2 and we rely on this.  Would be great if support was added to querydsl for SQL, currently only GROUP BY is supported.

Good examples here:
http://www.oracle-developer.net/display.php?id=515

**Comment by jwgmeligmeyling** [comment]
Can be easily implemented yourself:

```
new WindowOver<T>(expr.getType(), SQLOps.GROUP_CONCAT, expr)
```
