### ISSUE TITLE
Right joining polymorphic tables in JPA

### ISSUE THREAD

**Issue by ghost** [querydsl/querydsl#2042]
Hi there, I have experienced a particular edge case when using querydsl to right join a polymorphic table on JPA. Allow me to pass an example:

<img width="409" alt="screen shot 2016-10-26 at 10 46 09" src="https://cloud.githubusercontent.com/assets/16209037/19721272/7202ab2a-9b69-11e6-8ac6-1083eb497066.png">

let's say we want to execute the following:

```
new JPAQuery(EntityManager).from(A)
        .rightJoin(A.b, B)
        .groupBy(B.id)
        .map(B.id, A.numberOfStars.sum())
```

The expected result is:

```
1, 3
2, 0
3, 0
```

Now let's imagine A is a Polymorphic representation of C using JPA's `@Inheritance(strategy = InheritanceType.SINGLE_TABLE)`.
What happens is querydsl will inject the extra filter into the underlying query as a where clause making it similar to what the following query would generate:

```
new JPAQuery(EntityManager).from(A)
        .rightJoin(A.b, B)
        .where(A.discriminatorColumn.eq(a))
        .groupBy(B.id)
        .map(B.id, A.numberOfStars.sum())
```

this results in losing records in the output, namely the record for B = 3 will not be present in the result because discriminatorColumn would be null and the record would be filtered out.

I would argue this is not the expected behaviour, the expected behaviour would be for the results to be the same, since the polymorphism should be transparent.
In such cases the correct query should be something in the lines of:

```
new JPAQuery(EntityManager).from(A)
        .rightJoin(A.b, B)
        .on(A.discriminatorColumn.eq(a))
        .groupBy(B.id)
        .map(B.id, A.numberOfStars.sum())
```

Please let me know if that was clear or made any sense :)

**Comment by pedrocborges2** [comment]
@timowest Although the case is edgy it might just have a very simple fix under the hood. Can someone give it 5m of their attention to at least triage?

**Comment by Shredder121** [comment]
Can you also post the JPQL query that we generate?
Sorry for the absence :sweat_smile:

**Comment by pedrocborges2** [comment]
It's fine @Shredder121, it's easy to heal on the resulting map, cumbersome, yet easy :)

The query it generates is the exact mapping of the two examples I gave you, it filters the discriminator column by means of adding a `WHERE` clause instead of adding an `ON` condition in the join.

**Comment by jwgmeligmeyling** [comment]
> What happens is querydsl will inject the extra filter into the underlying query as a where clause making it similar to what the following query would generate:

Its actually your ORM doing this while generating the SQL. So it's probably an issue there.

If you still want to look into it, please report your ORM vendor and version.
