### ISSUE TITLE
Using a `StringTemplate` in .where `Predicate` replaces .like `String` with "?1" 

### ISSUE THREAD

**Issue by JonTizz** [querydsl/querydsl#2047]
Hi,

I've been using QueryDSL for a little while and it has made my development so much easier!
I have run into a problem, though.

I'm writing a query to search for "Customers" by postcode. To do this I'm formatting a search string, removing any whitespace, and doing the same to the column with `Expressions.stringTemplate("replace({0},' ','')", qCustomer.postCode)`. I'm then using `.likeIgnoresCase` to match to my search term, `postco` for example.

The issue I'm having is that, when the I actually run the query it resolves the query string to `select customer from Customer customer where lower(replace(customer.postCode,' ','')) like ?1`. You can see that where `postco` was has been replaced with `?1`.

My code is as follows:
```
    public Page<Customer> findByCustomerPostcode(String postcode, Pageable pageable) {
        
        // Reformat the Postcode to remove whitespace and normalise case
        String formattedPostcode = postcode.replace(" ", "");
        formattedPostcode = formattedPostcode.toLowerCase();
        
        // Create where with removal spaces from the column values
        BooleanExpression whereClause = Expressions.stringTemplate("REPLACE({0},' ','')", qCustomer.postCode).likeIgnoreCase(formattedPostcode);
        
        // Create the query factory for the Customer
        JPAQueryFactory queryFactory = new JPAQueryFactory(getEntityManager());
        JPAQuery<Customer> customerJPAQuery = queryFactory.selectFrom(qCustomer);
        
        // Run the query to get the whole count, and the actual paginated list
        Long totalResults = customerJPAQuery.where(whereClause).fetchCount();
        List<Customer> resultList = customerJPAQuery.where(whereClause).limit(pageable.getPageSize()).offset(pageable.getOffset()).fetch();
        
        // Return the page
        return new PageImpl<>(resultList, pageable, totalResults);
    }
```

The issue presents itself when `customerJPAQuery.where(whereClause).fetchCount();` is called. At this point `whereClause` is `lower(replace(customer.postCode,' ','')) like postco`, but `customerJPAQuery` is `select customer from Customer customer where lower(replace(customer.postCode,' ','')) like ?1`.
Interestingly, both the `queryMixin` and `QueryBase.queryMixin` from the `customerJPAQuery` contain the correct `where` clause in their metadata.

Does anyone have any pointers as to why this isn't working?
Thanks!

**Comment by JonTizz** [comment]
Annnnnd I'm an idiot. Absolutely nothing wrong with the library - My test data was wrong!

Thank you for your time :)

**Comment by Shredder121** [comment]
Sorry for the late reply.

Good to hear that it was fixed!
