### ISSUE TITLE
JPQL: Null instead of Tuple with null value is returned

### ISSUE THREAD

**Issue by ladislavlencucha** [querydsl/querydsl#2048]
**Problem:** 
When I execute JPQL where only one column is selected and value on some of the rows is NULL in database, QueryDSL returns list of tuples where some of the items are NULL.
When I execute JPQL where two columns are selected and value on some of the rows are NULL for both columns in database, QueryDSL returns list where all items are instances of Tuple.

**Expected behaviour:**
Do not return null instead of Tuple having 1 null value.

**Environment:**
QueryDsl 3.6.x, 3.7.x
EclipseLink 2.6.2
jtds 1.3.1

**Code to fix:**
com.mysema.query.jpa.impl.AbstractJPAQuery::getResultList
instead of adding null to result when "o" is null, create instance with 1 null value.
rv.add(null); -> rv.add(projection.newInstance((new Object[] {null}));

**Logic behind:**
My observation is that javax.persistence.Query implementation (EclipseLink in my case) returns either list of type of single column (e.g. List<String>) if only one column is selected, otherwise, array of objects is returned (List<Object[]>). However, this should not be the case, when mapping to Tuple is expected.

**Current workaround:**
Select at least 2 columns.

**Comment by jwgmeligmeyling** [comment]
Please verify on a new version of QueryDSL and EclipseLink.

**Comment by ladislavlencucha** [comment]
Hi, I retested on latest version and have the following update:

- Tuple instance is returned properly
- However, content of the Tuple instance is not correct (QTuple#TupleImpl#a array is null) and causes NPE when data is being retrieved or tested

I suggest fixing directly in TupleImpl constructor by checking whether input is null. If it is, then new Object[] {null} is created. I have pushed a test case to branch issue/2048, check lines 104 to 124, error occurs on line 120:
https://github.com/querydsl/querydsl/commit/9b7fbd1ad4a8b9918300ad6ad984f9551a04f56a

**Comment by jwgmeligmeyling** [comment]
Thanks, I'll have a look!

**Comment by ladislavlencucha** [comment]
Or check this one: https://github.com/querydsl/querydsl/pull/2710
