### ISSUE TITLE
NullExpressions in Projections

### ISSUE THREAD

**Issue by jerome-terry-vgh** [querydsl/querydsl#2049]
I'm porting a project from QueryDSL 3.4 to version 4.1.4. I'm running into an issue will NullExpressions used in projections. 

Consider this contrived class (imagine this is a DTO with a nullable constructor parameter). 

`public class DoubleWrapper {
    private final Double value;
    public DoubleWrapper(Double value) {
        this.value = value;
    }
}
`

This tests fails

`@Test
    public void testNullExpression() {
        Projections.constructor(DoubleWrapper.class, Expressions.nullExpression(Double.class));
    }`

Here's the stack trace

`com.querydsl.core.types.ExpressionException: No constructor found for class DoubleWrapper with parameters: [class java.lang.Object]
	at com.querydsl.core.util.ConstructorUtils.getConstructorParameters(ConstructorUtils.java:119)
	at com.querydsl.core.types.ConstructorExpression.<init>(ConstructorExpression.java:82)
	at com.querydsl.core.types.ConstructorExpression.<init>(ConstructorExpression.java:72)
	at com.querydsl.core.types.Projections.constructor(Projections.java:122)`

I can make this test pass, in an inelegant way.

`@Test
    public void testNullExpression_passes() {
        Expression<Double> expr =
                Expressions.template(Double.class, TemplateFactory.DEFAULT.create("null"), Collections.emptyList());
        Projections.constructor(DoubleWrapper.class, expr);
    }`

What I would like to see is that Expressions.nullExpression pass the type information to the superclasses. I.e. make the following test pass:

`@Test
    public void epressions_nullExpression_validateCorrectType() {
        NullExpression<Double> expr = Expressions.nullExpression(Double.class);
        assertThat(expr.getType().getName(), is(Double.class.getName()));
    }`

**Comment by Shredder121** [comment]
Thanks for the report.
It seems an assumption I made while changing some things for Querydsl 4 didn't hold true.

**Comment by Zelgadis87** [comment]
I actually have the same problem, 4 years later. NullExpression is always considered an expression of Object, which fails when searching for a valid constructor.

**Comment by dsarrio** [comment]
Same here, unable to use `Projections.constructor(..., Expressions.nullExpression())`.

**Comment by jwgmeligmeyling** [comment]
PR is now merged, so this can be closed.
