### ISSUE TITLE
Can't create custom types with Ant Task

### ISSUE THREAD

**Issue by danielbalog** [querydsl/querydsl#2052]
I don't think it's possible to create custom types using AntMetaDataExporter, because there is no way of using an array of strings as a property. You are kind of stuck:

```
<queryDSLTask jdbcDriver="${db.driver}"
                  jdbcUrl="${db.url}"
                  jdbcUser="${db.username}"
                  jdbcPassword="${db.password}"
                  packageName="${package_name}"
                  targetFolder="${target}"
                  schemaPattern="${schemaPattern}"
                  <!-- customTypes="my.custom.types" throws unknown attribute exception -->
                  >
         <!-- Impossible to add custom types here. None of the following works: -->
         <!-- <customTypes></customTypes> throws unknown nested element exception -->

    </queryDSLTask>
```

I believe the solution is simple though: Use the same workaround as typeMappings, numericMappings and renameMappings. These all use ArrayLists and nested elements, which makes them work just fine.

```
    /**
     * custom type mappings to use
     */
    private List<TypeMapping> typeMappings = Lists.newArrayList();

    /**
     * Adds TypeMapping instance, called by Ant
     */
    public void addTypeMapping(TypeMapping mapping) {
        typeMappings.add(mapping);
    }
```

I would have fixed this myself, but I can't seem to create a new remote branch due to a 403.

**Comment by danielbalog** [comment]
I created a pull request for this:

https://github.com/querydsl/querydsl/pull/2054

**Comment by htjo** [comment]
I'm using gradle with ant and want to use JSR310. So I tried to apply `customTypes`, but It couldn't apply because `customTypes` attribute not supported by ant in gradle since version is 4.1.4. 😄 I'm really looking forward to release #2054 at next version. Thanks @danielbalog
