### ISSUE TITLE
Missing join when using sub-type in a predicate and InheritanceType.JOINED

### ISSUE THREAD

**Issue by Ramblurr** [querydsl/querydsl#2055]
### Summary:

Given a base `Person` class, and an `Employee subtype` specified with InheritanceType.JOINED, along with a `PersonContainer` that has a relationship to a person, invalid sql is generated given the predicate:
```java
QPersonContainer.personContainer.person.as(QEmployee.class).name.likeIgnoreCase(name)
```

### Details:

```java
// Base type
@Entity
@Inheritance(strategy = InheritanceType.JOINED)
@DiscriminatorColumn(discriminatorType = DiscriminatorType.STRING)
class Person {
  @Id
  Long id;
}

// Sub type
@Entity
@DiscriminatorValue("employee")
class Employee extends Person {
 
  @Column
  String name;
}

// The object I'm querying by
@Entity
class PersonContainer {
  @OneToOne
  private Person person;
}
```

I create a predicate with:

```java
BooleanBuilder bb = new BooleanBuilder();
bb.and(QPersonContainer.personContainer.person.as(QEmployee.class).name.likeIgnoreCase(name))
personContainerRepository.findAll(bb);
```

The generated SQL looks like this:

```sql
SELECT count(personcont0_.id) AS col_0_0_
FROM db.person_container personcont0_
  CROSS JOIN db.person person1_
WHERE personcont0_.person_id = person1_.id
      AND (lower(person1_1_.name) LIKE '%mary%')
```

This fails with the root cause:

```
org.postgresql.util.PSQLException: ERROR: missing FROM-clause entry for table \"person1_1_\"\
```

You can see in the generated sql the error: person1_1_ is referenced but is not defined in a join anywhere. The query would work fine if this line was added after the cross join:

```sql
INNER JOIN db.employee as person1_1_ on person1_1_.id = person1_.id
```

Since I'm using a spring-data repository I don't have access to the JPQLQuery and can't specify the join myself. But anyways, it should be automatically created no?

**Comment by Ramblurr** [comment]
I went ahead and tried this out with straight up querydsl:

```java
JPQLQuery<PersonContainer> searchQuery = this.getQuerydsl().createQuery()
                .select(qPersonContainer)
                .from(qPersonContainer)
                .where(QPersonContainer.personContainer.person.as(QEmployee.class).name.likeIgnoreCase(name));
```

Here is the rendered JPQL:

```sql
select personContainer
from PersonContainer personContainer
where lower(personContainer.person.name) like ?1 escape '!'
```

This causes postgres to error `missing FROM-clause entry for table "person1_1_"`

Adding in an innerJoin fixes it: `query.innerJoin(qPersonContainer.person, qEmployee._super);`

**Comment by trenatov** [comment]
still reproduced

**Comment by Ramblurr** [comment]
Yea, I've given up hope that it will ever be fixed. I've moved on from querydsl.

**Comment by jwgmeligmeyling** [comment]
QueryDSL doesn't generate joins. We just render the JPQL query exactly as you define the query AST. So `QHello.hello.world.name.like("test").or(QHello.hello.world.isNull())` is rendered to `hello.world.name LIKE :param_1 OR hello.world IS NULL` in JPQL/HQL. Hibernate just tends to use a cross join for implicit joins (i.e. `hello.world.name`). For one, I suggest upgrading to a more recent version of Hibernate, but also according to the JPA specification, you should just prefer to use an explicit join instead:

```java
.from(hello)
.leftJoin(hello.world, QWorld.world)
.where(QWorld.world.name.like("test").or(QWorld.world.isNull())
```

Which in JPQL renders:

```sql
FROM Hello hello LEFT JOIN hello.world world WHERE world.name LIKE :param OR world IS NULL
```

**Comment by jwgmeligmeyling** [comment]
Also, Joined inheritance has been plagued by regressions in Hibernate in both 5.3 and 5.4 until recent patch versions of these releases, so keep that in mind when encountering this issue.

- https://hibernate.atlassian.net/browse/HHH-13670
- https://hibernate.atlassian.net/browse/HHH-13712
- https://hibernate.atlassian.net/browse/HHH-13742
- https://hibernate.atlassian.net/browse/HHH-13638
- https://hibernate.atlassian.net/browse/HHH-13796
