### ISSUE TITLE
Support for notLikeIgnoreCase

### ISSUE THREAD

**Issue by vguna** [querydsl/querydsl#2058]
Hi.

I'm using `StringExpression.likeIgnoreCase` successfully. No I wonder, whether are any plans to add `notLikeIgnoreCase` as well :)?

Thanks!

**Comment by isthar13** [comment]
Hello,

I would also like to see this. Currently I'm using a custom method that uses `containsIgnoreCase`, `startsWithIgnoreCase`, `endsWithIgnoreCase` or `equalIgnoreCase` depending on where the "%" is in the filter, but this is a bit tedious :)

Thank you!
