### ISSUE TITLE
Docs: Add examples with TemplateExpression 

### ISSUE THREAD

**Issue by sergiomichels** [querydsl/querydsl#2060]
I spent a quite significant amount of time to find and example of Boolean expressions with parameters.  Most examples in StackOverflow demonstrate how to use it without args, and seems silly but I didn't know that the expression uses the `MessageFormat` pattern style.

Example from [this SO post](http://stackoverflow.com/questions/22984343/how-to-call-mysql-function-using-querydsl)
`query.where(Expressions.booleanTemplate("func1({0}, {1})", arg1, arg2));`

**Comment by jwgmeligmeyling** [comment]
Defining custom Operators and registering these in a subclass of JPATemplates is preferable over overusing TemplateExpressions, as  the latter come with the risk of query injection.
