### ISSUE TITLE
Upgrade RooAnnotationProcessor class to Spring Roo 2

### ISSUE THREAD

**Issue by eruiz** [querydsl/querydsl#2062]
We have upgraded the `com.querydsl.apt.roo.RooAnnotationProcessor` class to Spring Roo 2 and we will like to commit it to the QueryDSL project.

We could send the changes via pull-request, but, should we have to overwrite the current class? do we have to maintain the current class as is and create a new class?

Thanks

**Comment by jwgmeligmeyling** [comment]
We'd still welcome a PR.

I am uncertain how widely used Spring Roo still is. I am fine with supporting both versions through separate modules or a single module with optional dependencies if possible.
