### ISSUE TITLE
QueryDslPredicateExecutor.FindAll with Predicate, Sort AND Pageable ?

### ISSUE THREAD

**Issue by philippeboyd** [querydsl/querydsl#2066]
Hello!

Am I missing something or there's no 

`Page<T> findAll(Predicate predicate, Sort sort, Pageable pageable)` method in `org.springframework.data.querydsl.QueryDslPredicateExecutor` ?

Would be a nice feature for a future release!

**Comment by Shredder121** [comment]
Excuse me, this is not the spring data project.
For the `org.springframework.data` package you should go to them.

**Comment by philippeboyd** [comment]
@Shredder121 you are right, apologies. And I just found out `PageRequest` has a constructor with a `Sort` parameter.

Have a nice day!
