### ISSUE TITLE
LGPL license text in LICENSE.querydsl.txt?

### ISSUE THREAD

**Issue by tazle** [querydsl/querydsl#2067]
It seems that https://github.com/querydsl/querydsl/blob/master/querydsl-jpa/src/license/LICENSE.querydsl.txt contains LGPL 2.1 text. All the source files of binary distributables refer to Apache License 2.0 instead, and that license text is present in https://github.com/querydsl/querydsl/blob/master/querydsl-jpa/src/license/LICENSE.apache20.txt

What does LICENSE.querydsl.txt apply to?

**Comment by tazle** [comment]
The situation does not appear to have changed. Why is there an LGPL license text in querydsl-jpa? What does it apply to?

**Comment by jwgmeligmeyling** [comment]
The entire repository is Apache 2 licensed as the original author (timo) pointed out several times in comments out here. I guess we should just remove the file. Its probably an old license from before apache was chosen. However, with only new contributors out here and Timo being absent, its hard to know for sure
