### ISSUE TITLE
APT doesn't generate when using java 8 lambda expressions in code

### ISSUE THREAD

**Issue by augustobreno** [querydsl/querydsl#2070]
APT maven plugin is not generation Q classes when existing  lambda expression in my. The expression is outside @Entity classes, but it still crashes. For example:

If I use the code bellow it doesn't generates::
`colaborador.getPermissoes().forEach(permissao -> permissao.setColaborador(colaborador));`

If I change to the following, it works:

```
for (PermissaoAvaliacaoColaborador permissao : colaborador.getPermissoes()) {
            permissao.setColaborador(colaborador);
}
```

I realized that the classes were generated when I run "mvn compile", but it doesn't when integrated with "Eclipse Maven Builder" integration.

I'm using this configuration:
- Java 8
- apt-maven-plugin 1.1.3
- querydsl-apt 4.1.4
- querydsl-jpa 4.1.4

**Comment by simenflatby** [comment]
@augustobreno I know it's been a long time, but it's worth a shot: Did you work this out?

**Comment by augustobreno** [comment]
@simenflatby I don't see the problem anymore. I don't know what fixed it, I just kept everything updated and it's was gone.

**Comment by simenflatby** [comment]
@augustobreno Thank you for your reply. The error turned out to be Jenkins running some Maven commands with Java 7.

**Comment by Shredder121** [comment]
:thinking: weird.
Thanks for the follow-up at least.
