### ISSUE TITLE
Specify supported options for APT

### ISSUE THREAD

**Issue by slinstaedt** [querydsl/querydsl#2080]
The current version of QueryDSL's APT processor is not specifying, which configuration parameters it's supporting, leading to annoying compiler warnings like:
`[WARNING] The following options were not recognized by any processor: '[querydsl.packageSuffix]'`.

Having the `AbstractQuerydslProcessor `implementing the `javax.annotation.processing.AbstractProcessor#getSupportedOptions` method would fix this.

**Comment by Shredder121** [comment]
This indeed sounds good.

**Comment by IncPlusPlus** [comment]
I just ran across this issue while looking for something unrelated. This issue is duplicated by #2772 and can be closed with the merge of #2773.
