### ISSUE TITLE
Update with alias objects

### ISSUE THREAD

**Issue by zheins** [querydsl/querydsl#2082]
I'm trying to do sql updates with querydsl using alias objects. I'm getting this compilation error when following the alias pattern described in the documentation:

`queryFactory.update($(qMyAlias)).where( ... `

`incompatible types: no instance(s) of type variable(s) D exist so that EntityPathBase<D> conforms to RelationalPath<?>`

Am I missing something in how alias objects work?

**Comment by Shredder121** [comment]
It looks like you're mixing the jpa query objects with the sql API.

For SQL you need to export the metadata of the database, and not use the JPA metamodel.
