### ISSUE TITLE
LEFT JOIN with JOINED inheritance strategy

### ISSUE THREAD

**Issue by danielyien** [querydsl/querydsl#2089]
Hello,

I have a class Person and two classes (Employee and Manager) that extends Person. I'm using hibernate JOINED inheritance strategy.
I also have a class Work that has an attribute person of type Person.

I'm having problems with the following query:

```java
QWork work = Qwork.work;
QEmployee employee = QEmployee.employee;
QManager manager = QManager.manager;

getJPAQuery()
	.from(work)
	.leftJoin(work.person, employee)
	.leftJoin(work.person, manager)
	.fetch();
```

The generated SQL is something like:

```sql
SELECT *
FROM
    Work
    LEFT JOIN Person ON Work.personId = Person.personId
    INNER JOIN Employee ON Person.personId = Employee.personId
    INNER JOIN Manager ON Person.personId = Manager.personId
```

The problem is that my query is getting no results because of the INNER JOIN clauses.
The join between the parent table Person and the child tables (Employee and Manager) should have been done with LEFT JOIN instead of INNER JOIN.

I also tried adding the _super reference but it didn't work: 

```java
getJPAQuery()
	.from(work)
	.leftJoin(work.person, employee._super)
	.leftJoin(work.person, manager._super)
	.fetch();
```

How can I do this kind of query involving LEFT JOIN between parent and child tables?

**Comment by johnjaylward** [comment]
Are you trying to just get the `work` details, or do you want the `work` details along with the `employee` and `manager` details?

**Comment by jwgmeligmeyling** [comment]
QueryDSL is not responsible for rendering SQL, your ORM is, probably Hibernate. This appears to be a Hibernate issue. Please validate on a recent Hibernate version.
