### ISSUE TITLE
Upgrade version of findbugs

### ISSUE THREAD

**Issue by murphp15** [querydsl/querydsl#2090]
You are using a very old version of findbugs, do you think you could upgrade it as it is conflicting with versions in our project which is pulled in by other projects.

**Comment by Shredder121** [comment]
That sounds like a reasonable request.
As far as I know we only need the annotations from Findbugs and the dependencies it pulls in.
Can you maybe try excluding our version of Findbugs to see if it works with your version?

**Comment by murphp15** [comment]
Yeah that's what we are doing at the moment. I just don't like having lots of exclusions in my poms. I can make the change, test and issue a problem if you are busy ?

**Comment by murphp15** [comment]
Yeah that's what we are doing at the moment. I just don't like having lots of exclusions in my poms. I can make the change, test and issue a PR if you are busy ?

**Comment by Shredder121** [comment]
I at least would like to know if Querydsl works with newer versions of Findbugs at runtime.
A PR would be okay.

**Comment by jwgmeligmeyling** [comment]
We've migrated away form JSR305 in #2674
