### ISSUE TITLE
Document how querydsl-apt classifiers can be used

### ISSUE THREAD

**Issue by maffe** [querydsl/querydsl#2091]
I think it’s cleaner to have the `querydsl-apt` dependency only on the build plugin instead of using the `provided` scope. So instead of

```XML
<dependency>
  <groupId>com.querydsl</groupId>
  <artifactId>querydsl-apt</artifactId>
  <version>${querydsl.version}</version>
  <scope>provided</scope>
</dependency>
```
do this:
```XML
<build>
  <plugins>
    ...
    <plugin>
      <groupId>com.mysema.maven</groupId>
      <artifactId>apt-maven-plugin</artifactId>
      <version>1.1.3</version>
      <executions>
        <execution>
          <goals>
            <goal>process</goal>
          </goals>
          <configuration>
            <outputDirectory>target/generated-sources/java</outputDirectory>
            <processor>com.querydsl.apt.jpa.JPAAnnotationProcessor</processor>
          </configuration>
        </execution>
      </executions>
      <dependencies>
        <dependency>
          <groupId>com.querydsl</groupId>
          <artifactId>querydsl-apt</artifactId>
          <version>${querydsl.version}</version>
        </dependency>
      </dependencies>
    </plugin>
    ...
  </plugins>
```

This way the IDE doesn’t suggest classes from the `querydsl-apt` dependency which aren’t available at runtime.

**Comment by Shredder121** [comment]
I think this sounds fine. Thanks for the suggestion.
It might even be good to review the documentation in that field, will do!

**Comment by jwgmeligmeyling** [comment]
Its even cleaner to do:

```xml
<dependency>
  <groupId>com.querydsl</groupId>
  <artifactId>querydsl-apt</artifactId>
  <version>${querydsl.version}</version>
  <scope>provided</scope>
  <classifier>jpa</classifier>
</dependency>
```


Which makes the entire `apt-maven-plugin` unnecessairy.

**Comment by maffe** [comment]
@jwgmeligmeyling That’s exactly the opposite of this request. It’s (except for the `classifier`) the same as currently documented and makes the IDE suggest classes which are not available at runtime (for example, `com.querydsl.apt.Configuration`), which does not happen with the dependency moved to the plugin.

**Comment by jwgmeligmeyling** [comment]
I know.

Its just that we shouldn't encourage users to use the Maven plugin in the first place. Using the properly classified dependency in the provided scope is the prefered method. As long as our documentation points to the Maven plugin and show examples using a bunch of unnecessairy dependencies, requests like these will keep popping in.
