### ISSUE TITLE
Create query without FROM clause.

### ISSUE THREAD

**Issue by asaarnak** [querydsl/querydsl#2094]
In MSSQL and PostgreSql sql i could write: 
```SELECT CASE WHEN EXISTS(SELECT * FROM someTable) THEN true ELSE false END;```

In querydsl i tried:
```
jpaQueryFactory.select(
  JPAExpressions.select(someTable)
  .from(someTable)
  .exists()
  .when(Expressions.TRUE)
  .then(Boolean.TRUE)
  .otherwise(Boolean.FALSE)
).fetchOne();
```
But this gives me IllegalArgumentException("No sources given") from here:
https://github.com/querydsl/querydsl/blob/master/querydsl-jpa/src/main/java/com/querydsl/jpa/JPAQueryBase.java#L56

Is there a reason that FROM clause can't be ignored by querydsl?

**Comment by Shredder121** [comment]
In Querydsl SQL this is possible (dummy tables if needed), but not in Querydsl JPA.

**Comment by asaarnak** [comment]
Why not in JPA ?

**Comment by Shredder121** [comment]
Because, in the [JPQL BNF](http://docs.oracle.com/cd/E11035_01/kodo41/full/html/ejb3_langref.html#ejb3_langref_bnf) it says this:
```
select_statement ::= select_clause from_clause [where_clause] [groupby_clause] [having_clause] [orderby_clause]
```
The `from_clause` is not optional but required.
