### ISSUE TITLE
read and write with QueryDSL 3.2

### ISSUE THREAD

**Issue by normancash** [querydsl/querydsl#2097]
I need to  implement reading and writing using field type BLOB. 

I assumed that QDSL did do this automatically ...
When I begin to implement that...
I had the fallowing error:

	//execute query
    	List<Tuple> resultadoConsulta = query.list(fieldSelect.toArray(new StringExpression[0])); 
    
the compiler go to the exception: 
	
select * from (
 select a.*, rownum rn from (
  
from test_archivo
 ) a) where rn > 0 and rn <= 1
Invalid column type: getString not implemented for class oracle.jdbc.driver.T4CBlobAccessor

I need any help.

**Comment by Shredder121** [comment]
This does not give a complete picture of what your code does, or what you want it to do.
Could you update the Google group post instead?

**Comment by normancash** [comment]
Ok, 


I'm using QueryDSL 3.2, and I needed to read and write BLOB-type data. I had implemented reading and writing data but there were no long data like BLOB.
What I need urgently is to see how to implement reading and writing with QueryDSL.SQL for BLOB type data.

 A clear example I can not find, ASAP, if it is possible please help

**Comment by normancash** [comment]
Ruben, I need solved this problem, i have that implemeting BLOB with QueryDSL 3.2.0 
But whatever I do, it always gives me this error.
"Invalid column type: getString not implemented for class oracle.jdbc.driver.T4CBlobAccessor".

The codigo is:

`
public Map<String,List<Map<String,String>>> consultar(final Bolsa bolsa,final Connection connection) throws Exception{
    	SQLQuery query = crearSQLQuery(bolsa,null,connection);
    	query.offset(0).limit(1);
    	
    	_logger.info("Prueba Consulta: " + query.toString());
    	
    	
    	StringBuffer queryString = new StringBuffer("SELECT ");
    	StringBuffer camposString = new StringBuffer();
    	List<StringExpression> camposSelect = new ArrayList<StringExpression>(50);
    	for(BolsaCampo bolsaCampo:bolsa.getBolsaCampos()){
    		camposSelect.add(StringTemplate.create( bolsaCampo.getCampo() ));    		
    	}   
    	  	
    	camposString.append(camposSelect.toString().substring(1,camposSelect.toString().length() - 1)); 
    	
    	SQLTemplates dialect = obtenerSQLTemplate(connection);    	
    	Configuration configuration = new Configuration(dialect);    	
      
        JavaTypeMapping j = new JavaTypeMapping();
        j.register(new InputStreamType());
        configuration.register(new InputStreamType());
    	// ejecutar la consulta
    	List<Tuple> resultadoConsulta = query.list(camposSelect.toArray(new StringExpression[0])); 
    	
    	// convertir al formato esperado
    	List<Map<String,String>> resultadoConsultaFormateado = convertirResultadoTuple2ListaMapa(bolsa, resultadoConsulta);
    	
    	Map<String,List<Map<String,String>>> resultado = new HashMap<String,List<Map<String,String>>>(2);
    	queryString.append(camposString + " ");
    	
    	
    	queryString.append(query.toString());
    	
    	
    	resultado.put(queryString.toString(),resultadoConsultaFormateado);
    	
    	return resultado;
    }
`

**Comment by Shredder121** [comment]
I think something goes wrong in `convertirResultadoTuple2ListaMapa()`
If there is a `BLOB` column, then I don't think reading that using `getString` (in JDBC, what we use under the hood) will work.
Could you maybe set up an example project?

**Comment by normancash** [comment]
Ruben, thx.

The error happens in the previous line.

"List<Tuple> resultadoConsulta = query.list(camposSelect.toArray(new StringExpression[0])); "

I try implementing the uso de Custom Type with blob but do not know how to register my Custom Type in QueryDSL, with the version 3.2 not exist the method Configuration.setType();

` public void test(){
        Configuration configuration = new Configuration(new MySQLTemplates());
        /* THIS METHOD IS NOT EXIST WITH VERSION 3.2, WHAT DO I USE?
        configuration.setType(Types.BLOB, InputStream.class);
        configuration.register(new InputStreamType());        
        assertEquals(InputStream.class, configuration.getJavaType(Types.BLOB, "", ""));
    }
`

**Comment by normancash** [comment]
The post to which I refer is: 

https://groups.google.com/forum/#!topic/querydsl/wf_StLffiFw
