### ISSUE TITLE
NoSuchMethodError problem when quering hibernate5.2.6

### ISSUE THREAD

**Issue by zhhal** [querydsl/querydsl#2100]
QUser qUser = QUser.user;
HibernateQuery<User> query = new HibernateQuery<User>(getSession());
User user = query.from(qUser).where(qUser.userId.eq(userId)).fetchOne();

exception:
java.lang.NoSuchMethodError: org.hibernate.Session.createQuery(Ljava/lang/String;)Lorg/hibernate/Query;
com.querydsl.jpa.hibernate.DefaultSessionHolder.createQuery(DefaultSessionHolder.java:36)
com.querydsl.jpa.hibernate.AbstractHibernateQuery.createQuery(AbstractHibernateQuery.java:104)
com.querydsl.jpa.hibernate.AbstractHibernateQuery.fetchOne(AbstractHibernateQuery.java:328)

org.hibernate.Query is deprecated.  
(since 5.2) use org.hibernate.query.Query instead.

**Comment by Shredder121** [comment]
#1917 We are already aware of this problem, but finding a good middle ground between supporting all possible distinct Hibernate versions and having support packages is difficult.
@querydsl/developers Any thoughts? 😩

**Comment by jwgmeligmeyling** [comment]
Hibernate 5.x integration was fixed in QueryDSL 4.4.0.
