### ISSUE TITLE
QueryDSL not generating entities for MySql tables

### ISSUE THREAD

**Issue by rajeevkri** [querydsl/querydsl#2113]
I am trying to use QueryDSL with MySql. To begin with, I'm trying to get Entity classes generated for the tables in my database.

Here is my POM:

    <plugin>
    <groupId>com.querydsl</groupId>
    <artifactId>querydsl-maven-plugin</artifactId>
    <version>4.0.3</version>
    <executions>
      <execution>
        <goals>
          <goal>test-export</goal>
        </goals>
      </execution>
    </executions>
    <configuration>
      <jdbcDriver>${jdbc.driver}</jdbcDriver>
        <jdbcUrl>${jdbc.url}</jdbcUrl>
        <jdbcUser>${jdbc.user}</jdbcUser>
        <jdbcPassword>${jdbc.password}</jdbcPassword>
        <tableNamePattern>.*</tableNamePattern>
      <packageName>app.domain</packageName>
      <targetFolder>${project.basedir}/src/main/java</targetFolder>
      <sourceFolder>${project.basedir}/src/main/java</sourceFolder>
    </configuration>
    <dependencies>
      <dependency>
        <groupId>mysql</groupId>
        <artifactId>mysql-connector-java</artifactId>
        <version>6.0.3</version>
      </dependency>
    </dependencies>
  </plugin>
Properties:

        <properties>
            <jdbc.user>root</jdbc.user>
            <jdbc.password>root</jdbc.password>
            <jdbc.url>jdbc:mysql://localhost:3306/test</jdbc.url>
            <jdbc.driver>com.mysql.cj.jdbc.Driver</jdbc.driver>
            <querydsl.version>4.0.3</querydsl.version>
        </properties>
However, this is not working. There are no exceptions.

QueryDSL doc: https://github.com/querydsl/querydsl/tree/master/querydsl-sql

Any ideas on what I might be missing here?

**Comment by Shredder121** [comment]
Could you share a bigger part of the `pom.xml`?
Or maybe an example project?
Where did you put the `<plugin />` element?

**Comment by rajeevkri** [comment]
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<groupId>com.navint</groupId>
	<artifactId>hello-dsl</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<packaging>jar</packaging>

	<name>Hello querydsl</name>
	<description>Hello querydsl</description>

	<properties>
		<maven.compiler.source>1.7</maven.compiler.source>
		<maven.compiler.target>1.7</maven.compiler.target>
	</properties>

	<dependencies>
		<dependency>
			<groupId>mysql</groupId>
			<artifactId>mysql-connector-java</artifactId>
			<version>6.0.3</version>
		</dependency>
		
		
		<dependency>
		  <groupId>com.mysema.querydsl</groupId>
		  <artifactId>querydsl-sql</artifactId>
		  <version>${querydsl.version}</version>
		</dependency>
		<dependency>
		  <groupId>com.mysema.querydsl</groupId>
		  <artifactId>querydsl-apt</artifactId>
		  <version>${querydsl.version}</version>
		</dependency>
		<dependency>
		  <groupId>com.mysema.querydsl</groupId>
		  <artifactId>querydsl-jpa</artifactId>
		  <version>${querydsl.version}</version>
		</dependency>    
		<dependency>
		  <groupId>com.mysema.querydsl</groupId>
		  <artifactId>querydsl-sql-codegen</artifactId>
		  <version>${querydsl.version}</version>
		  <scope>provided</scope>
		</dependency>
		
		<dependency>
			<groupId>org.slf4j</groupId>
			<artifactId>slf4j-log4j12</artifactId>
			<version>1.6.1</version>
		</dependency>
	</dependencies>
	
	<build>
		<plugins>
		
		
		<plugin>
        <groupId>com.querydsl</groupId>
        <artifactId>querydsl-maven-plugin</artifactId>
        <version>4.0.3</version>
        <executions>
          <execution>
            <goals>
              <goal>test-export</goal>
            </goals>
          </execution>
        </executions>
        <configuration>
          <jdbcDriver>${jdbc.driver}</jdbcDriver>
		    <jdbcUrl>${jdbc.url}</jdbcUrl>
		    <jdbcUser>${jdbc.user}</jdbcUser>
		    <jdbcPassword>${jdbc.password}</jdbcPassword>
		    <tableNamePattern>.*</tableNamePattern>
          
          <packageName>app.domain</packageName>
          
          <targetFolder>${project.basedir}/src/main/java</targetFolder>
          <sourceFolder>${project.basedir}/src/main/java</sourceFolder>
        </configuration>
        <dependencies>
          
          <dependency>
            <groupId>mysql</groupId>
            <artifactId>mysql-connector-java</artifactId>
            <version>6.0.3</version>
          </dependency>
        </dependencies>
      </plugin>
		
		

			<plugin>
				<groupId>org.codehaus.mojo</groupId>
				<artifactId>exec-maven-plugin</artifactId>
				<version>1.5.0</version>
				<executions>
					<execution>
						<goals>
							<goal>exec</goal>
						</goals>
					</execution>
				</executions>
				<configuration>
					<systemProperties>
						<systemProperty>
							<key>jdbc.driver</key>
							<value>${jdbc.driver}</value>
						</systemProperty>
						<systemProperty>
							<key>jdbc.user</key>
							<value>${jdbc.user}</value>
						</systemProperty>
						<systemProperty>
							<key>jdbc.password</key>
							<value>${jdbc.password}</value>
						</systemProperty>
						<systemProperty>
							<key>jdbc.url</key>
							<value>${jdbc.url}</value>
						</systemProperty>
					</systemProperties>
				</configuration>
			</plugin>
		</plugins>
	</build>

	<profiles>
		<profile>
			<id>default</id>
			<activation>
				<activeByDefault>true</activeByDefault>
			</activation>
			<properties>
				<jdbc.user>root</jdbc.user>
				<jdbc.password>root</jdbc.password>
				<jdbc.url>jdbc:mysql://localhost:3306/test</jdbc.url>
				<jdbc.driver>com.mysql.cj.jdbc.Driver</jdbc.driver>
				<querydsl.version>4.0.3</querydsl.version>
			</properties>
		</profile>
	</profiles>
	

</project>


this is complete pom. i was trying to create a hello project to generate entities from database and query from database. i don't anything in project.

**Comment by natros** [comment]
try removing `<tableNamePattern>.*</tableNamePattern>` to see if it helps.

**Comment by rajeevkri** [comment]
If i remove <tableNamePattern>.*</tableNamePattern> i see following error - 
[ERROR] Failed to execute goal com.querydsl:querydsl-maven-plugin:4.0.3:test-export (default) on project hello-dsl: Table name pattern can not be NULL or empty

**Comment by rajeevkri** [comment]
is querydsl really generating entities from sql tables. has anyone done it?

**Comment by DiasNetoJ** [comment]
@rajeevkri, same issue here and probably, like me, you are using MySQL JDBC 6.0.2+

To solve the problem, just append **nullNamePatternMatchesAll=true** to your connection string.

> The default value of the "nullNamePatternMatchesAll" connection property changed between versions 5.1.38 and 6.0.2 of mysql-connector-java.  It is "true" in 5.1.38, it is "false" in 6.0.2.

read more in: https://bugs.mysql.com/bug.php?id=81105

**Comment by rajeevkri** [comment]
@DiasNetoJ Thanks it resolved issue.
