### ISSUE TITLE
schemaPattern not working

### ISSUE THREAD

**Issue by rajeevkri** [querydsl/querydsl#2114]
I am trying to generate Entity from mysql.

below is configuration which i am using -

< configuration>
          < jdbcDriver>com.mysql.cj.jdbc.Driver</ jdbcDriver>
		    < jdbcUrl>jdbc:mysql://localhost:3306/test?nullNamePatternMatchesAll=true< /jdbcUrl>
		    < jdbcUser>root</ jdbcUser>
		    < jdbcPassword >root</ jdbcPassword>
		     < schemaPattern>test%</ schemaPattern>
		    < tableNamePattern>%b%</ tableNamePattern>
		    < exportBeans>true</ exportBeans>
          
          < packageName>app.domain</ packageName>
          
          < targetFolder>${project.basedir}/src/main/java</ targetFolder>
          < sourceFolder>${project.basedir}/src/main/java</ sourceFolder>
          < schemaToPackage>true</ schemaToPackage>
        < /configuration>

Schema pattern doesn't look like working as this is exporting all entities matching with the table pattern given from all schemas in my database.

**Comment by rajeevkri** [comment]
Has anyone used mysql with querydsl?
Please clarify this.

**Comment by rajeevkri** [comment]
Found answer in other thread.
https://github.com/querydsl/querydsl/issues/1877

**Comment by xjianyu** [comment]
> @rajeevkri - how did uou make it work?

@ashish-moglix https://github.com/querydsl/querydsl/pull/1989#issuecomment-822567351,

> `<schemaPattern>test</schemaPattern>`
