### ISSUE TITLE
Unable to query by mapped superclass - invalid path

### ISSUE THREAD

**Issue by mrginglymus** [querydsl/querydsl#2115]
Hi all,

Let's say I have the following:

    @MappedSuperclass
    public abstract class BaseEntity {
        private boolean active = true;
    }

    @Entity
    public class User extends BaseEntity {
         //... etc
    }

Then I can do a `queryFactory.selectFrom(QUser.user).where(QUser.user.active.isTrue()).fetch()`, no worries.

However, as I have multiple entities that will extend the `BaseEntity`, and I want a service that can return only active entities, I want to be able to have something that looks like...

    public abstract BaseService<E extends BaseEntity> {
        protected abstract EntityPathBase<E> getBase()

        protected JpaQuery<E> getQuery() {
             return queryFactory.selectFrom(getBase()).where(QBaseEntity.baseEntity.active.isTrue());
        }

        public List<E> findStuff(Predicate... predicates) {
             return getQuery().where(predicates).fetch();
        }
    }

implemented as

    public UserService extends BaseService<User> {
        protected EntityPathBase<User> getBase() {
             return QUser.user;
        }
    }

amongst others.

However, `baseEntity.active` is not a valid path for the query. There doesn't seem to be a suitable generic way to query a descendant of a mapped superclass without implementing e.g. `BooleanPath getActivePath()` on each implementation.

Am I missing an easy (or complicated!) fix here, or is this all by design and I just need to put up with it? :)

**Comment by pawel-piatkowski** [comment]
Very interesting question. I'm also interested what is the right answer.

**Comment by bundery** [comment]
Is there a solution now ？

**Comment by jwgmeligmeyling** [comment]
`QEmployee` does not extend `QBaseEntity`, but it does reference QBaseEntity through the `super_` field. This is by design, to decrease the memory footprint and computational intensity to initialise the static metamodel.

You could use:

```
    @Override
    protected QBaseEntity getBase() {
         return QUser.user.super_;
    }
```

This is as generic as it gets :)
