### ISSUE TITLE
AbstractDAO

### ISSUE THREAD

**Issue by iurylira** [querydsl/querydsl#2121]
Guys,

I would like to create an AbstractDAO using QueryDSL but I don't know how to do it.

My idea:  

1 - public abstract class AbstractDAO<T, I>
2-  public  class UserDAO<User, Long>

**Comment by Shredder121** [comment]
There's some insight in the example projects in the `querydsl-examples` folder.
But otherwise a better place to discuss non-issues is the Querydsl Google group.
