### ISSUE TITLE
how to express where (id,type) in ((?,?),(?,?),(?,?)) with querydsl?

### ISSUE THREAD

**Issue by liuchangit** [querydsl/querydsl#2122]
how to express where (id,type) in ((?,?),(?,?),(?,?)) with querydsl?

**Comment by jwgmeligmeyling** [comment]
In JPQL this is not possible. In SQL: `Expressions.operation(Object.class, Ops.WRAPPED, Expressions.operation(Object.class, Ops.LIST, a, b)` renders `(a, b)`. Which you can then pass to `expression.in(expression)`.
