### ISSUE TITLE
Q Classes for Entities in target/generated-sources/.... folder

### ISSUE THREAD

**Issue by ynahshal** [querydsl/querydsl#2131]
Hallo there, 
To facilitate the Developers work and to reduce the lines of Code, we have developed an annotation to generate Entities automatically: e.g ( if you have the Entity "Employee" then this annotation will generate the Entity EmployeeHistory). Using APT from java like QueryDsl, the generated source is written in "target/generated-source/annotations/...." folder. The problem then is that Querydsl does not generate the "Q" classes for those generated Entities. Can you please help me out and tell me how to tell QueryDsl to do so.

Best and thanks in advanced.

**Comment by ynahshal** [comment]
Found the solution, thanks

**Comment by Shredder121** [comment]
You'll have to make sure that the directory is added to the Maven source directories I suppose.
