### ISSUE TITLE
spring data mongodb miss $near query

### ISSUE THREAD

**Issue by muka** [querydsl/querydsl#2141]
Hi
I am using spring boot  1.5.2 and followed more or less this code with Double[] and Point

https://bugs.launchpad.net/querydsl/+bug/727942

I see there is no `near` method, maybe due to missing boot support.

Is it possible to explicitly add to the querydsl Predicate a $near* query?

Thank you

**Comment by Shredder121** [comment]
There is a `near` method, but on the `Point` class.
https://github.com/querydsl/querydsl/blob/421049b4718350963679204d6521241c1a8cf366/querydsl-mongodb/src/main/java/com/querydsl/mongodb/Point.java#L50-L52

Did you maybe not set up the annotation processing correctly/completely to make use of the `Point` class?
