### ISSUE TITLE
EnumPath.stringValue in CaseBuilder: Error converting data type varchar to float on SQLServer

### ISSUE THREAD

**Issue by LeszekLeszczynski** [querydsl/querydsl#2143]
We have a CaseBuilder that works on an EnumPath and returning a default value in some cases. Something like

```java
com.querydsl.core.types.dsl.StringExpression state = new CaseBuilder().when(jobExecution.status.eq(JobStatus.FAILED)).then("FAILED")
            .when(jobExecution.status.in(runningStatus)).then("RUNNING")
            .otherwise(jobExecution.status.stringValue());
```

(jobExecution is the EnumPath)

This creates an SQL like 

```sql
select case when jpabatchjo0_.STATUS='FAILED' then 'FAILED' 
    when jpabatchjo0_.STATUS in ('STARTING' , 'STARTED') then 'RUNNING'
    else str(jpabatchjo0_.STATUS) 
end
...
```
This causes an error to be thrown *[S0005][8114] Error converting data type varchar to float.* 

[Consulting the SQLServer reference](https://docs.microsoft.com/en-us/sql/t-sql/functions/str-transact-sql), we see that the STR function converts a numeric value to string, so the above is incorrect for this DBMS.

Please fix the casting or provide a workaround for SQLServer.

**Comment by jwgmeligmeyling** [comment]
Seems you found the work around.
