### ISSUE TITLE
Upgrade version of org.reflections:reflections library

### ISSUE THREAD

**Issue by manish-in-java** [querydsl/querydsl#2153]
The `codegen` module v4.1.4 has a compile-time dependency on `org.reflections:reflections` library v0.9.9. That version of the library has a dependency on `com.google.code.findbugs:annotations` v2.0.1, which is licensed only under GPL. Therefore, `org.reflections:reflections:v0.9.9`, `org.querydsl:querydsl-codegen:4.1.4` and `org.querydsl:querydsl-apt:4.1.4` should all be licensed under GPL.

The current version of `org.reflections:reflections` (v0.9.11) has got rid of the problematic dependency. Therefore, the `codegen` module should upgrade its dependency version to avoid licensing issues related to the use of GPL software.

**Comment by manish-in-java** [comment]
I would also suggest to use the [Maven License Check plugin](https://github.com/mrice/license-check) to avoid using any dependencies that may cause licensing issues for QueryDSL.

**Comment by manish-in-java** [comment]
Apologies, it seems that `com.google.code.findbugs:annotations` is licensed under LGPL, not GPL.

**Comment by Shredder121** [comment]
Thanks for investigating anyway!
