### ISSUE TITLE
ComparableExpressionBase::stringValue() removed in version 4.x

### ISSUE THREAD

**Issue by oasiste** [querydsl/querydsl#2155]
Hello,
In querydsl 3.x we use the function ComparableExpressionBase::stringValue()  to transform our custom objects in StringExpression and then use string operations on it (contains, like) but in querydsl 4.x we notice that this function was removed. So I would like to know what is the right way in querydsl 4.x to transform a ComparablePath<CustomObject> to StringExpression so we can make String operations on it (our custom object is stored as String on database).

Our code using querydsl 3.x

`qClient.person.name.stringValue().contains("TEST")`

**Comment by Shredder121** [comment]
We moved it to `LiteralExpression`, but it should be available on most types.

**Comment by daniel-shuy** [comment]
For anyone wondering how to convert an `Expression` that doesn't extend `LiteralExpression` to a `StringExpression` in querydsl 4.x, eg. `ComparableExpression<UUID>`, you can use:
```java
Expressions.stringOperation(Ops.STRING_CAST, expression);
```
(this is taken from the source of `LiteralExpression#stringValue()`)

**Comment by jwgmeligmeyling** [comment]
I wouldn't opt for adding `ComparableExpressionBase::stringValue()` back, but we can make casting to a String a bit easier to find.

For example: `Expressions.castString(Expression<?>)`
