### ISSUE TITLE
How to join a table with itself ?

### ISSUE THREAD

**Issue by ijiaojian** [querydsl/querydsl#2156]
like a sql : select id from user c, user p where c.pid = p.id.    how to get this SQL via QueryDSL ?

**Comment by Shredder121** [comment]
You would need multiple instances of the meta object.

[This is an example, which joins the Employee table with itself](https://github.com/querydsl/querydsl/blob/421049b4718350963679204d6521241c1a8cf366/querydsl-sql/src/test/java/com/querydsl/sql/SelectBase.java#L287-L300).

**Comment by ijiaojian** [comment]
@Shredder121 thanks, i got it .

**Comment by Shredder121** [comment]
Good good!
