### ISSUE TITLE
OderBy multiple columns as optional list that can be send in API

### ISSUE THREAD

**Issue by ynahshal** [querydsl/querydsl#2162]
Hi there, 
In my API, I need to provide orderBy function. The sortParameters comes as list in the API which represent an Enum class in the server side, so you do not know which column will be send. let us suppose that you have table with the columns (id, name, age, job, status), now it could be that the request comes with sortParameter((name->Asc, age->Desc, job->Asc, status->Asc)). Now, in normal case if you want to order by e.g name asc, you do the following:
`
query.from(...).where(...).orderBy(new OrderSpecifier(Order.asc, something.name));
`
Or, if you know that (name and age) will be there, then you can do 

`
OrderSpecifier<String> sortOrder1 = Qsomething.something.name.asc();
OrderSpecifier<Integer> sortOrder2 = Qsomething.something.age.desc()

query.from(...).where(...).orderBy(sortOrder1, sortOrder2));
`

Now, if you want to build list of OrderSpecifiers according to the request and then pass it to the method orderBy, how can you do that. Additionally, if one of the sort Parameters has different name than the column, then can it work like this (.list(new QTuble(Qsomething.something.name.as(nameInTheRequest))

I would appreciate any help there.

**Comment by johnjaylward** [comment]
you create a function that maps your request parameters to orderby statements as you did in your own example:

```java
List<OrderSpecifier> orderBy = new LinkedList<>();
if(myParams["orderBy"].contains("name"){
    orderBy.add(Qsomething.something.name.asc());
}
if(myParams["orderBy"].contains("name"){
   orderBy.add(Qsomething.something.age.desc());
}
// ... more orderby possibilityes

query.from(...).where(...).orderBy(orderBy.toArray());
```

You can also add in logic to get the `ASC` or `DESC` as required.

**Comment by ynahshal** [comment]
Thank you so much for your reply, it is a bit late, but this is what I did at the end, thanks anyway.

**Comment by johnjaylward** [comment]
go ahead and close the ticket then if this is resolved for you.
