### ISSUE TITLE
Custom query with SELECT *

### ISSUE THREAD

**Issue by mmedic** [querydsl/querydsl#2163]
How does one write a query like this using querydsl:

```
SELECT 
      * 
    FROM 
      ( 
        SELECT 
          a.id          AS myId,
          a.name        AS myName,
          a.privilege   AS myPrivilege,
          a.owner       AS myOwner,
          b.title       AS myTitle,
          row_number() OVER (PARTITION BY id ORDER BY privilege DESC) AS row_num
        FROM 
          tableA a
          INNER JOIN tableB b 
            ON (a.id = b.id)
        WHERE
          a.name = :name 
      ) 
    WHERE 
      row_num = 1
    ORDER BY
      id DESC
```

**Comment by EwingTsai** [comment]
Just keep the same projection and alias:

`        QBean<Object> bean = Projections.bean(Object.class,Expressions...);
        
        queryFactory
                .select(bean)
                .from(
                        SQLExpressions.select(bean)....
                ).where(...)
                .orderBy(...);`

**Comment by EwingTsai** [comment]
select(Expressions.template(Result.class,"*")).from(SubQuery...)...

**Comment by EwingTsai** [comment]
You can also using Projections instead '*':
Projections.bean(
    YourResult.class,
    Expressions.numberPath(Long.class,"myId"),
    Expressions.stringPath("myName"),
    ......
)

**Comment by coder-free** [comment]
> select(Expressions.template(Result.class,"*")).from(SubQuery...)...

not work

the result is `Long`, not `Result`
