### ISSUE TITLE
Why not support left join with restrictions

### ISSUE THREAD

**Issue by kespinosa05** [querydsl/querydsl#2165]
How can I do this with querydsl
queryDSL.leftJoin(qPerson.books, qBooks, qBooks.type.eq("MAT")); in criteria it is done thus
criteria.createCriteria("books", "book", Criteria.LEFT_JOIN, Restrictions.eq("book.type", "MAT"));

i want sql generate are 
select * from person p left join books b on b.personid = p.id and b.type='MAT'
not
select * from person p left join books b on b.personid = p.id where b.type='MAT'

**Comment by Maze-fr** [comment]
There is a "dirty" way, if you use Hibernate and that "MAT" never changes : you can use `@Where` annotation with the `@OneToMany` join condition.

But I think to remember that it requires the use of `com.querydsl.apt.hibernate.HibernateAnnotationProcessor` to generate Q classes.

**Comment by kespinosa05** [comment]
I use HibernateAnnotationProcessor to generate  Q classes.
This was only for representations, temporally i use @filter in relations but criteria support left join with restrictions why querydsl not

**Comment by Maze-fr** [comment]
Interesting... does filter apply after or during the request ?

Don't forget that JPA is not SQL.
So, when you use Criteria, it is a SQL API, but when you use JPA query, you are more restricted.
For example, you can't do `select ... from (select` with JPA, or you must have all columns of a composite PK as FK in other tables for join purpose with annotations.

**Comment by kespinosa05** [comment]
I enable filter in current session for that query and  after disabled

@OneToMany(mappedBy = "Person")
@Filter(name = "bookTypeMat")
private Collection<Book> books;

session.enableFilter("bookTypeMat");

make query using querydsl

session.disableFilter("bookTypeMat");

**Comment by Maze-fr** [comment]
OK, I understand.

So you use Hibernate session for querying... be careful : another issue is opened about problems with Hibernate 5.2 and QueryDSL not supporting Hibernate queries (the class has changed package).
Hibernate is going closer to JPA specifications and so sessions are depreciated and being replaced by entity managers.

Another solution is to test if `(bookId is null or bookType = 'MAT')`.
That will prevent to generate an undue inner join.

**Comment by kespinosa05** [comment]
OK, thanks.
But i not found other solution

**Comment by jwgmeligmeyling** [comment]
The proper syntax would have been `queryDSL.leftJoin(qPerson.books, qBooks).on(Books.type.eq("MAT"))`
