### ISSUE TITLE
JPA: Using collection.any().in(...) in element collections

### ISSUE THREAD

**Issue by luisfpg** [querydsl/querydsl#217]
When using collection.any().in(...) in a collection path representing a collection of elements (not persistent entities), the generated JPQL contains "from ElementClass alias ...", which is invalid.
Here is an example of a possible solution, imagining the User entity with a collection of enums Role:

``` java
QUser u = QUser.user1;
from(u).where(u.roles.any().in(Role.ADMIN, Role.MANAGER);
```

could generate:

``` sql
select u
from User u
where exists (
    select 1
    from User u1 join u1.roles r
    where u1 = u
    and  r in :roles
)
```

**Comment by H-Lo** [comment]
This feature stopped working with Hibernate 6.

https://stackoverflow.com/questions/77409442/querydsl-collection-contains
