### ISSUE TITLE
Mongo isNull check and null values

### ISSUE THREAD

**Issue by jefflann** [querydsl/querydsl#2173]
Hello,

I am using Spring Boot with QueryDSL & MongoDB using `querydsl-mongodb` version 3.7.4.  I have a MongoRepository and am using a QueryDSL Predicate to check if a field contains a `null` value like:

`repository.findAll(QPerson.person.personId.isNull())`

However, this isn’t retrieving results where the value of the field is `null` as expected. 

Looking at the code for [MongodbSerializer](https://github.com/querydsl/querydsl/blob/master/querydsl-mongodb/src/main/java/com/querydsl/mongodb/MongodbSerializer.java#L238-L240), it appears the `isNull` operation is translated to an `$exists` check in MongoDB which checks if the property exists.  Instead, I need to check if the value of the field is `null`, which was what I was expecting `isNull` to do.

Is there a way to check if a field (that exists) has a `null` value using QueryDSL Predicates & MongoDB?

Thank you!

**Comment by A-Zaiats** [comment]
The issue was created 1.5 years ago. And no update?

**Comment by simonered** [comment]
Maybe it's late, but you can try `QPerson.person.personId.eq(null)` (I've not tried, but I think it should work)

**Comment by Shredder121** [comment]
In general `eq(null)` is not allowed, since the chance of accidentally passing `null` is very much present.

https://github.com/querydsl/querydsl/blob/2bf234caf78549813a1e0f44d9c30ecc5ef734e3/querydsl-core/src/main/java/com/querydsl/core/types/dsl/SimpleExpression.java#L126-L127

**Comment by trgoofi** [comment]
[Query for Null or Missing Fields: ](https://docs.mongodb.com/manual/tutorial/query-for-null-fields/)
> The { item : null } query matches documents that either contain the item field whose value is null or that do not contain the item field.

As MongoDB state that query `null` treated as `null` or `missing field`. `Q.isNull()` should serialize to `null` query instead of `$exists` query.

**Comment by butzy92** [comment]
Any updates on this issue?

**Comment by jwgmeligmeyling** [comment]
Pretty sure the MongoDBSerializer/Templates needs to be updated to address this properly, but as a workaround, just use a template expression:

`Expressions.booleanTemplate("{0} is null", QPerson.person.personId)`

**Comment by butzy92** [comment]
It's not working...
`java.lang.UnsupportedOperationException: null
	at org.springframework.data.mongodb.repository.support.MongodbDocumentSerializer.visit(MongodbDocumentSerializer.java:124) ~[spring-data-mongodb-2.2.2.RELEASE.jar:2.2.2.RELEASE]
	at org.springframework.data.mongodb.repository.support.MongodbDocumentSerializer.visit(MongodbDocumentSerializer.java:54) ~[spring-data-mongodb-2.2.2.RELEASE.jar:2.2.2.RELEASE]
	at com.querydsl.core.types.TemplateExpressionImpl.accept(TemplateExpressionImpl.java:80) ~[querydsl-core-4.2.2.jar:na]`

**Comment by butzy92** [comment]
Found a workaround: 
`public class NullConstant implements Constant<Object> {

	public static final NullConstant NULL_CONSTANT = new NullConstant();

	private NullConstant() {
	}

	@Override
	public Object getConstant() {
		return null;
	}

	@Nullable
	@Override
	public Object accept(Visitor v, @Nullable Object context) {
		return null;
	}

	@Override
	public Class getType() {
		return Object.class;
	}

}`

and use it: 
`
qEntity.field.eq(NullConstant.NULL_CONSTANT)
`

**Comment by onmishkin** [comment]
Nice workaround @butzy92! One improvement I made:
```
public Object getConstant() {
    return new Document("$type", 10);
}
```
This yields a MongoDB filter with a term like `{xx: {$type: 10}}` which means:

* Field `xx` is present and has the value `null`.

as opposed to `{xx: null}` which MongoDB interprets as:

* Field `xx` is present with a value of null _or_ field `xx` is not present.

The latter interpretation potentially yields a slower query and is not what you'd want if you know you never need to match on the "field not present" case. (See [this documentation](https://www.mongodb.com/docs/manual/reference/operator/query/type/) for info on the `$type` operator.)

**Comment by onmishkin** [comment]
Also, I think the `accept()` method needs to look like this:
```
    public Object accept(Visitor v, Object context) {
        return v.visit(this, context);
    }
```
at least if you want `.toString()` to work right on predicates (whose `.toString()` method ends up in this `accept()` method and expects a non-null return. (The Java debugger ends up calling `.toString()` when you look at variables, for example.)
