### ISSUE TITLE
JPA: Polymorphic classes with same field names being cast to incorrect class type

### ISSUE THREAD

**Issue by ronaldheft** [querydsl/querydsl#2174]
I have an object model I'm working with that features a set of polymorphic classes using the JPA joined inheritance strategy, so each subclass has its own table. The subclasses are not very normalized, so some classes and tables feature columns named the same, and this is the crux of the problem I've run into with QueryDSL.

When querying the base model and casting out to a subclass, the resulting SQL will incorrectly reference the first table in the join that features the column name queried. I have a simplified example of my issue.

Given this object model:

`Post`:
  - postId

`ExpediaReview`:
  - postId
  - rating
  - expediaUniqueField

`HotelsReview`:
  - postId
  - rating
  - hotelsUniqueField

You see both `ExpediaReview` and `HotelReview` have a field called `rating`. Now, if I want to write a query with a predicate on `ExpediaReview` I would do the following:

```
this.getQuerydsl().createQuery()
    .from(post)
    .where(
        post.instanceOf(ExpediaReview.class).and(post.as(QExpediaReview.class).rating.eq(5))
    )
    .list(post);
```

Here, I am querying the base object `Post` and writing a predicate clause on `ExpediaReview`. The QueryDSL looks good and compiles fine, however, the resulting SQL has an error:

```
select
    post1_.postId
from
    post post1_
left outer join
    hotels_review post1_3_ 
        on post1_.postId=post1_3_.postId  
left outer join
    expedia_review post1_5_ 
        on post1_.postId=post1_5_.postId
where
    case 
        when post1_3_.postId is not null then 27 
        when post1_5_.postId is not null then 25
        when post1_.postId is not null then 'Post' 
    end=? 
    and (
        post1_3_.rating = 5
    )
```

You'll see, the actual where clause is referencing joined table `post1_3_`, which corresponds to `HotelsReview` and not `ExpediaReview`.

After playing around with the query, I've discovered that the issue is somehow related to both `ExpediaReview` and `HotelsReview` having a common field name. If I query a field like `expediaUniqueField` the where clause will reference the correct table.

The issue seems to stem from QueryDSL choosing the first polymorphic class with the field name in the query, which in this case is `HotelsReview`.

Obviously, everything works fine if I query `ExpediaReview` directly, but for my use case, I unfortunately have a complex query that will need to use the base table and reference into fields on each polymorphic table.

I'm using QueryDSL 3.7.4 with Hibernate 4.3.11.Final.

I'm unfamiliar with the source of QueryDSL, but I'd love to help track down this problem.

**Comment by liias** [comment]
Adding also the Google Groups link for same issue: https://groups.google.com/forum/#!topic/querydsl/gGLolk4Khz8
