### ISSUE TITLE
querydsl cross join ?why? how to left join lnner join auto?

### ISSUE THREAD

**Issue by zengfr** [querydsl/querydsl#2182]
querydsl cross join ?why? how to left join lnner join auto?
code:
@Test
	public void testfindList() {
		QBean<ProductItem> p = Projections.bean(ProductItem.class,
				QProductItem.productItem.productItemId,
				QProductItem.productItem.product().category().categoryName);
		
		List<Long> ids=new ArrayList<>();
		ids.add(2L);ids.add(23L);ids.add(123L);
		Predicate f=QProductItem.productItem.productItemId.in(ids);
		
		List<ProductItem> result =productItemJpaRepository.findList(f,p);
		boolean condition=!result.isEmpty();
		assertTrue(condition);
	}
sql：
Hibernate: select productite0_.productItemId as col_0_0_, category2_.categoryName as col_1_0_ 
from ProductItem productite0_ 
cross join Product product1_ 
cross join Category category2_
 where productite0_.productId=product1_.productId 
and product1_.categoryId=category2_.categoryId 
and (productite0_.productItemId in (? , ? , ?))

**Comment by txwszq** [comment]
I have the same problem. Do you have any idea to resolve that?

**Comment by mihirthuse** [comment]
Even I have the same problem. And for me, it is specifically happening when I'm using multiple OR conditions in the predicate.

**Comment by alextadams88** [comment]
Having this same problem. Causing big issues with my predicates. Its doing Cross Joins on a table causing some values not to appear when I need it to be doing a left join instead.
