### ISSUE TITLE
How to  add a SubQuery in the FROM clause

### ISSUE THREAD

**Issue by zhangzhongbin001** [querydsl/querydsl#2185]
usa jpa
sql: `select *from (subquery ) a  left join(subquery ) b on a.xx=b.xx`

**Comment by Shredder121** [comment]
JPQL does *not* support subqueries in the `FROM` part.

**Comment by ecormaksin** [comment]
@Shredder121 Then, the statement [here](https://querydsl.com/static/querydsl/4.4.0/reference/html_single/#d0e415) `To create a subquery you use the static factory methods of JPAExpressions and define the query parameters via from, where etc.` is not right, isn't it?

**Comment by jwgmeligmeyling** [comment]
It is right, the documentation means that the static factory needs to be used to obtain a subquery instance on which the subqueries FROM and WHERE clause can be set.

If you need to use subqueries in the FROM clause in JPQL/JPA, check out the Querydsl integration for Blaze-Persistence: https://persistence.blazebit.com/documentation/1.6/core/manual/en_US/index.html#querydsl-integration

This allows you to do use queries in the from clause:

```java
QRecursiveEntity recursiveEntity = new QRecursiveEntity("t");

List<Author> fetch = new BlazeJPAQuery<>(entityManager, cbf)
    .select(author)
    .from(select(author)
        .from(author)
        .orderBy(author.name.asc())
        .limit(1L), recursiveEntity)
    .fetch();
```

**Comment by ecormaksin** [comment]
@jwgmeligmeyling Thank you for your answer so very quickly! I'm sorry that I misunderstood. But I'm happy to know Blaze-Persistence which I can use a subquery in a from clause.
