### ISSUE TITLE
scala query return types in version 4.x

### ISSUE THREAD

**Issue by khoran** [querydsl/querydsl#2186]
I've just been trying to migrate some scala code to QueryDSL 4.x from 3.x. I have found two problems I can't fix. The first is that simple queries return a java.util.List object instead of a scala list like they used to: 
```
val q = new SQLQuery(new GrnDataSource().getConnection(),templates)
val t = QPartScannedDocument

val result =  q select(t.partNumber) from t where(t.partNumber eq 3857089) fetch
```
"result" is a java.util.List[Long]. Even using "import scala.collection.JavaConversions._" doesn't help. 

Second, and more problematic, selecting more than one field does not return a scala tuple anymore:
```
val result =  q select(t.partNumber,t.partName) from t where(t.partNumber eq 3857089) fetch
```
"result" is now a java.util.List[com.querydsl.core.Tuple]. In QueryDSL 3.x this would have returned a List[(Long,String)] which is much more usable. 

Is there any way to accomplish this in version 4? If not, could that functionality be re-created?  
It looks like this functionality used to be in the com.mysema.query.scala.Helpers class, which has been removed in version 4.
I would have a very hard time using QueryDSL 4 in scala going forward without this, and the required modifications to existing code would be too much to carry out. 
Thanks.

**Comment by Shredder121** [comment]
Oh interesting find, thanks for the report!
