### ISSUE TITLE
QueryDSL enum field not correctly generated.

### ISSUE THREAD

**Issue by archmagece** [querydsl/querydsl#2187]
My Source
```
package hello.domain.model.embed;

import com.querydsl.core.annotations.PropertyType;
import com.querydsl.core.annotations.QueryType;
import lombok.*;
import hello.core.ContentFormatType;

import javax.persistence.*;
import java.io.Serializable;

/**
 * @author archmagece
 * @date 2017-06-25
 */
@Entity(name = "T_ARTICLE_CATEGORY")
@NoArgsConstructor(access = AccessLevel.PROTECTED)
@Getter
@EqualsAndHashCode
@ToString
public class ArticleCategoryEntity implements Serializable {

	public ArticleCategoryEntity(String code, String name) {
		this.code = code;
		this.name = name;
	}

	public ArticleCategoryEntity(String code) {
		this.code = code;
		this.name = code;
	}

	@Id
	@GeneratedValue
	private Long id;

	@Enumerated(EnumType.STRING)
	@QueryType(PropertyType.ENUM)
	private ContentFormatType formatType = ContentFormatType.HTML;

	private String code;
	private String name;

}
```

Generated Source
```
package sc.micro.domain.model.embed;

import static com.querydsl.core.types.PathMetadataFactory.*;

import com.querydsl.core.types.dsl.*;

import com.querydsl.core.types.PathMetadata;
import javax.annotation.Generated;
import com.querydsl.core.types.Path;


/**
 * QContentEmbedModel is a Querydsl query type for ContentEmbedModel
 */
@Generated("com.querydsl.codegen.EmbeddableSerializer")
public class QContentEmbedModel extends BeanPath<ContentEmbedModel> {

    private static final long serialVersionUID = 428450061L;

    public static final QContentEmbedModel contentEmbedModel = new QContentEmbedModel("contentEmbedModel");

    public final StringPath content = createString("content");

    public final EnumPath<ContentFormatType> formatType = createEnum("formatType", ContentFormatType.class);

    public final StringPath title = createString("title");

    public QContentEmbedModel(String variable) {
        super(ContentEmbedModel.class, forVariable(variable));
    }

    public QContentEmbedModel(Path<? extends ContentEmbedModel> path) {
        super(path.getType(), path.getMetadata());
    }

    public QContentEmbedModel(PathMetadata metadata) {
        super(ContentEmbedModel.class, metadata);
    }

}
```

Problem:
import is not included in generated source.
`import hello.core.ContentFormatType;`

**Comment by archmagece** [comment]
After write this, I run `gradle generateQueryDSL` command in terminal then it works fine.
system gradle version 4.0

gradle wrapper version 3.3


`
/**
 * QContentEmbedModel is a Querydsl query type for ContentEmbedModel
 */
@Generated("com.querydsl.codegen.EmbeddableSerializer")
public class QContentEmbedModel extends BeanPath<ContentEmbedModel> {

    private static final long serialVersionUID = 428450061L;

    public static final QContentEmbedModel contentEmbedModel = new QContentEmbedModel("contentEmbedModel");

    public final StringPath content = createString("content");

    public final EnumPath<sc.micro.core.ContentFormatType> formatType = createEnum("formatType", sc.micro.core.ContentFormatType.class);

    public final StringPath title = createString("title");

    public QContentEmbedModel(String variable) {
        super(ContentEmbedModel.class, forVariable(variable));
    }

    public QContentEmbedModel(Path<? extends ContentEmbedModel> path) {
        super(path.getType(), path.getMetadata());
    }

    public QContentEmbedModel(PathMetadata metadata) {
        super(ContentEmbedModel.class, metadata);
    }

}
`

**Comment by Shredder121** [comment]
Could you maybe format them into *three* backtick blocks?
