### ISSUE TITLE
Bug in code generation when having JTS Geometry object in parent class

### ISSUE THREAD

**Issue by twiechert** [querydsl/querydsl#2188]
Hi,

I'm using code generation for two classes A and B, where B extends A and A contains a geometry field from the JTS library. The generated code for the subclass looks like:

```
...
public final com.querydsl.spatial.jts.JTSGeometryPath location = new com.querydsl.spatial.jts.JTSGeometryPath(_super.location);
...
```

which is not compilable, as JTSGeometryPath  does not have such constructor. Changing the code to

```
...
new com.querydsl.spatial.jts.JTSGeometryPath(_super.location.getMetadata());
...
```
would work.

**Comment by jwgmeligmeyling** [comment]
Could you provide a reproducer domain model?
