### ISSUE TITLE
JPASQLQuery querying SQL and returning Entity with Projections.constructor() fails

### ISSUE THREAD

**Issue by renanleandrof** [querydsl/querydsl#2191]
The code above works fine:

```java
private QUser user = new QUser("user");
private SUser sUser = new SUser("user");
...
getJPASQLQuery()
                .select(user)
                .from(sUser)
                .fetch();
```

This one fails with ```java.lang.IllegalArgumentException: argument type mismatch```

```java
private QUser user = new QUser("user");
private SUser sUser = new SUser("user");
...
getJPASQLQuery()
                .select(Projections.constructor(UserDTO.class, user))
                .from(sUser)
                .fetch();
```

The class UserDTO has a constructor:

```java
public UserDTO (User user) {
...
}
```

Not sure if its a new Feature request or a Bug.

query-dsl version: 4.1.3

**Comment by Shredder121** [comment]
So to be clear, you're mixing two different metamodel types?

**Comment by renanleandrof** [comment]
Yeah, just like the docs says.

http://www.querydsl.com/static/querydsl/4.1.3/reference/html_single/#d0e431

Em 25 de ago de 2017 18:52, "Ruben Dijkstra" <notifications@github.com>
escreveu:
