### ISSUE TITLE
how to use group_concat in queryDSL?

### ISSUE THREAD

**Issue by powek** [querydsl/querydsl#2192]
i just to use querydsl in my project, there is my problerm that i don't know how to use group_concat in queryDSL,.

  may someone help me ?  thanks!

**Comment by kevzz81517** [comment]
import sql dependency.
use SQLExpressions.groupConcat()

**Comment by jwgmeligmeyling** [comment]
For SQL use `SQLExpressions.groupConcat`. For JPA this is not supported, because `GROUP_COPONCAT` is not a function defined for JPQL. None of the ORM vendors ship it by default, although the function can be registered manually in some cases. Duplicate of  #2192.

**Comment by jwgmeligmeyling** [comment]
Duplicate of #2192.

**Comment by jwgmeligmeyling** [comment]
Duplicates #2056

**Comment by jwgmeligmeyling** [comment]
Duplicate of #2020.
