### ISSUE TITLE
invalid BooleanBuilder orAllOf

### ISSUE THREAD

**Issue by finalnova** [querydsl/querydsl#2194]
using BooleanBuilder `orAllOf` method like

`e1.orAllof(e2, e3)`

expected result is `e1 or (e2 and e3)` but actual result is `e1 or e2 and e3`

and this where cluase result occur diffrent result in mySql.

This is a fatal flaw in the BooleanBuilder. anyone know about this issue?

**Comment by Shredder121** [comment]
Are you sure?
`and` should have higher precedence than or, so parentheses aren't necessary.

**Comment by finalnova** [comment]
@Shredder121 
sorry my bad :( close issue
