### ISSUE TITLE
How to user an custom function(mysql)

### ISSUE THREAD

**Issue by zhangzhongbin001** [querydsl/querydsl#2200]
I have created an function.How to use it? Thanks U.
`CREATE FUNCTION  date_week(p_date DATETIME,p_week_only INT) 
RETURNS VARCHAR(10)
BEGIN
 .................
RETURN v_res;
END//`

**Comment by Shredder121** [comment]
RelationalFunctionCall should do the trick.

**Comment by zhangzhongbin001** [comment]
I want use like : `select date_week(a,b) ,c1,c2 from table`

**Comment by zhangzhongbin001** [comment]
I know:
application.properties
**spring.jpa.properties.hibernate.dialect=xx.xx.MyDialect**
`public class MyDialect extends MySQL5Dialect {
    public MyDialect() {
        super();
        registerFunction("date_week",
                new SQLFunctionTemplate(StandardBasicTypes.STRING,"date_week(?1,?2)"));
    }
}`
