### ISSUE TITLE
Adding JPAExpressions results

### ISSUE THREAD

**Issue by baxol** [querydsl/querydsl#2207]
There is no option to add result of JPAExpressions. I think i should be placed in ExpressionUtils or maybe there is some possibility to do this?

**Comment by Shredder121** [comment]
Could you elaborate on what you mean?
I'm not sure on how to interpret this, for when we pick this up.

**Comment by Doopler** [comment]
For example i have two columns where sum is calculated by JPAExpression
`ConstructorExpression(Person) constructor = new QPerson(
	JPAExpressions.select(QSalary.salary.value.sum().from(QSalary.salary).where(QSalary.salary.jobId.eq(10))),
	JPAExpressions.select(QSalary.salary.value.sum().from(QSalary.salary).where(QSalary.salary.jobId.eq(11)))
);`
but I can not find option to put to third column sum results of these two expressions

**Comment by jwgmeligmeyling** [comment]
`select 1 as a, 2 as b, a + b as c` is not valid JPQL nor SQL.

Its not allowed to reference select aliases in the select clause. You'd have to duplicate the subqueries:

```java
JPAExpressions.select(
    QSalary.salary.value.sum().from(QSalary.salary).where(QSalary.salary.jobId.eq(10)),
    QSalary.salary.value.sum().from(QSalary.salary).where(QSalary.salary.jobId.eq(11)),

    Expressions.asNumber(QSalary.salary.value.sum().from(QSalary.salary).where(QSalary.salary.jobId.eq(10)))
        .plus(QSalary.salary.value.sum().from(QSalary.salary).where(QSalary.salary.jobId.eq(11))
)
```

Luckily,

The above can be simplified using variables:

```java
a = Expressions.asNumber(QSalary.salary.value.sum().from(QSalary.salary).where(QSalary.salary.jobId.eq(10)))
b = Expressions.asNumber( QSalary.salary.value.sum().from(QSalary.salary).where(QSalary.salary.jobId.eq(11)))
// ...
JPAExpressions.select(
    a, b, a.plus(b)
)
```
