### ISSUE TITLE
Left join with nested query

### ISSUE THREAD

**Issue by qzqzzz** [querydsl/querydsl#2208]
I'm using querydsl 4.x and I'm wondering if there's any way to express the query below with querydsl syntax:

```
SELECT cars.id, cars.model, cars.owner, mileage.total_mileage
FROM cars
LEFT JOIN (SELECT SUM(mileage) AS total_mileage FROM cars_mileage GROUP BY car_id) AS mileage 
ON cars.id = mileage.car_id
GROUP BY cars.id
```

If there isn't, what would be the recommended way to approach this type of queries?

**Comment by seamusmac** [comment]
I just found myself trying to figure the exact same thing, 

Did you find a solution in QueryDsl for this or your went native on the query?

**Comment by jwgmeligmeyling** [comment]
This is possible in QueryDSL SQL but not in QueryDSL JPA, because JPA itself does not support it in its query language JPQL. As you did not find the feature already, I assume you were looking for it in JPA.
