### ISSUE TITLE
Groovy Q class generation fail when using maven-compiler-plugin

### ISSUE THREAD

**Issue by vitormcruz** [querydsl/querydsl#2212]
Generating a new maven project with it’s quickstart archetype, adding the following class:

	@Entity
	@Table(name = "DUMMY_ENTITY")
	class DummyEntity {

		@Column(name = "VALUE")
		private String value;

		String getValue() {
			return value
		}

		void setValue(String value) {
			this.value = value
		}
	}

and changing the pom to be like this:

	<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
			 xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
		<modelVersion>4.0.0</modelVersion>

		<groupId>teste</groupId>
		<artifactId>teste</artifactId>
		<version>1.0-SNAPSHOT</version>
		<packaging>jar</packaging>

		<name>teste</name>
		<url>http://maven.apache.org</url>

		<properties>
			<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		</properties>

		<dependencies>
			<dependency>
				<groupId>org.codehaus.groovy</groupId>
				<artifactId>groovy-all</artifactId>
				<version>2.4.12</version>
			</dependency>

			<dependency>
				<groupId>com.querydsl</groupId>
				<artifactId>querydsl-jpa</artifactId>
				<version>4.1.4</version>
				<scope>compile</scope>
			</dependency>

			<dependency>
				<groupId>org.hibernate</groupId>
				<artifactId>hibernate-core</artifactId>
				<version>5.2.11.Final</version>
				<scope>compile</scope>
			</dependency>

			<dependency>
				<groupId>junit</groupId>
				<artifactId>junit</artifactId>
				<version>3.8.1</version>
				<scope>test</scope>
			</dependency>
		</dependencies>

		<build>
			<plugins>
				<plugin>
					<artifactId>maven-compiler-plugin</artifactId>
					<version>3.6.1</version>
					<configuration>
						<compilerId>groovy-eclipse-compiler</compilerId>
						<source>1.8</source>
						<target>1.8</target>
						<encoding>UTF-8</encoding>
						<showWarnings>true</showWarnings>
						<generatedSourcesDirectory>target/generated-sources/java</generatedSourcesDirectory>
						<compilerArgs>
							<arg>-Aquerydsl.entityAccessors=true</arg>
							<arg>-Aquerydsl.useFields=true</arg>
						</compilerArgs>
					</configuration>
					<dependencies>
						<dependency>
							<groupId>org.codehaus.groovy</groupId>
							<artifactId>groovy-eclipse-compiler</artifactId>
							<version>2.9.2-01</version>
						</dependency>
						<dependency>
							<groupId>org.codehaus.groovy</groupId>
							<artifactId>groovy-eclipse-batch</artifactId>
							<version>2.4.3-01</version>
						</dependency>
						<dependency>
							<groupId>com.querydsl</groupId>
							<artifactId>querydsl-apt</artifactId>
							<version>4.1.4</version>
							<classifier>jpa</classifier>
						</dependency>
						<dependency>
							<groupId>org.hibernate.javax.persistence</groupId>
							<artifactId>hibernate-jpa-2.1-api</artifactId>
							<version>1.0.0.Final</version>
						</dependency>
					</dependencies>
				</plugin>
			</plugins>
		</build>
	</project>

when I run mvn compile I got the following error:

> [ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.6.1:compile (default-compile) on project teste: Execution default-compile of goal org.apache.maven.plugins:maven-compiler-plugin:3.6.1:compile failed: An API incompatibility was encountered while executing org.apache.maven.plugins:maven-compiler-plugin:3.6.1:compile: java.lang.NoSuchMethodError: com.google.common.collect.ImmutableList.of(Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;[Ljava/lang/Object;)Lcom/google/common/collect/ImmutableList;

If I remove the querydsl-apt dependency the compilation works. 

It seems that querydsl-apt is using an old version of guava, and when compiling it tries to use a method not supported by newer versions. I tried to put guava exclusions on groovy-eclipse-batch and groovy-eclipse-compiler, I also tried to declare guava versions 18.0 and 15.0 on maven-compiler-plugin, none of these worked. 

Maybe updating guava version used on querydsl-apt could fix it?

**Comment by vitormcruz** [comment]
I figure out what is happening: groovy-eclipse-compiler uses com.google.collections, which clashes with google guava :( 

Putting an exclusion fix the problem:

	<dependency>
	  <groupId>org.codehaus.groovy</groupId>
	  <artifactId>groovy-eclipse-compiler</artifactId>
	  <version>2.9.2-01</version>
	  <exclusions>
		  <exclusion>
			  <artifactId>google-collections</artifactId>
			  <groupId>com.google.collections</groupId>
		  </exclusion>
	  </exclusions>
	</dependency>

guava seems to keep compatibility with collections, but it may causa problems. I don’t know what could be done to fix it for good (report to groovy-eclipse-compiler as google.collections seems deprecated?)
Also, using “hibernate” classifier fails because the Hibernate dependency must be declared in the plugins dependencies. Shouldn't this happen? If declaring hibernate is mandatory in maven-compiler-plugin would be nice to have that on the docs.

**Comment by jwgmeligmeyling** [comment]
Guava is removed per the upcoming 5.x release, so this issue should no longer occur.
