### ISSUE TITLE
Document API-based MongodbSerializer

### ISSUE THREAD

**Issue by mp911de** [querydsl/querydsl#2215]
We'd like to MongoDB's Document-API with `MongodbSerializer` to use it with the asynchronous/reactive MongoDB driver. Any chance of migration or providing a new type (side-by-side) supporting `Document`?

**Comment by olivergierke** [comment]
I'd second that. The more mature the 3.x drivers get, the more we risk the `DBObject`-based API being dropped in 4.x. That would effectively make Querydsl useless on MongoDB, which would be a shame. Spring Data currently maintains quite a bit of code to make sure we fall back to that legacy API only for Querydsl and it would be cool if we could get rid of it.

**Comment by Shredder121** [comment]
Now that's a good idea, and inevitable when they decide to axe the old API.
