### ISSUE TITLE
querydsl.packageSuffix messes with QueryDslJpaRepository

### ISSUE THREAD

**Issue by panih2o** [querydsl/querydsl#2219]
By introducing `<querydsl.packageSuffix>.query</querydsl.packageSuffix>` I am getting the following exception (for brevity sake, I have eliminated other lines).

```
Caused by: java.lang.IllegalArgumentException: Did not find a query class a.b.c.d.QEntity for domain class a.b.c.d.Entity!
	at org.springframework.data.querydsl.SimpleEntityPathResolver.createPath(SimpleEntityPathResolver.java:63)
	at org.springframework.data.jpa.repository.support.QueryDslJpaRepository.<init>(QueryDslJpaRepository.java:85)
	at org.springframework.data.jpa.repository.support.QueryDslJpaRepository.<init>(QueryDslJpaRepository.java:69)
```

Note this wasn't an issue before introducing this suffix.

I still see the query classes getting generated at the desired path using the suffix.

The following is my configuration

```
  <!-- QueryDSL Query Classes Generation -->
      <plugin>
        <groupId>com.mysema.maven</groupId>
        <artifactId>apt-maven-plugin</artifactId>
        <version>1.1.3</version>
        <executions>
          <execution>
            <goals>
              <goal>process</goal>
            </goals>
            <configuration>
              <outputDirectory>${project.build.directory}/generated-sources/java</outputDirectory>
              <processor>
                com.querydsl.apt.jpa.JPAAnnotationProcessor,lombok.launch.AnnotationProcessorHider$AnnotationProcessor
              </processor>
              <options>
                <querydsl.packageSuffix>.query</querydsl.packageSuffix>
              </options>
            </configuration>
          </execution>
        </executions>
      </plugin>
```

The dependencies are

```
 <dependency>
      <groupId>com.querydsl</groupId>
      <artifactId>querydsl-apt</artifactId>
      <version>${querydsl.version}</version>
    </dependency>
    <dependency>
      <groupId>com.querydsl</groupId>
      <artifactId>querydsl-jpa</artifactId>
      <version>${querydsl.version}</version>
    </dependency>

```
where `querydsl.version` is `4.1.4`.

`QueryDslJpaRepository` is coming from `org.springframework.data:spring-data-jpa:1.11.7.RELEASE`

Please let me know what other version of dependencies do you need but I am guessing it might be straightforward to check if `QueryDslJpaRepository` respects `querydsl.packageSuffix`?

**Comment by chosema** [comment]
I have the same problem. It is working only if query class is in the same package as entity. But whats the purpose of "querydsl.packageSuffix" option if its not working with different subpackages?

**Comment by Shredder121** [comment]
`querydsl.packageSuffix` is a way of structuring the generated entities for human consumption.
Spring Data is machine consuming the entities, so I wouldn't be surprised if you shouldn't touch the expected package.

Could you ask the people over at Spring Data whether it's even supported?
In the meantime I would leave it as default.

**Comment by chosema** [comment]
Yes it is the problem with Spring Data which currently does not support query classes in different packages than entity class. By default JpaRepositoryFactory is creating QueryDslJpaRepository with SimpleEntityPathResolver. And this resolver doesnt support different packages as you can see [here](https://github.com/spring-projects/spring-data-commons/blob/0237760345faa011bdc6639ec838790be3d41e9b/src/main/java/org/springframework/data/querydsl/SimpleEntityPathResolver.java#L98)

**Comment by chosema** [comment]
In Spring Data configuration you can provide your custom implementation of JpaRepositoryFactory with `factory-class` attribute in xml settings:
`<jpa:repositories factory-class="x.y.z"/>`
[This](https://dzone.com/articles/customizing-spring-data-jpa) short tutorial shows you howto.

**Comment by panih2o** [comment]
@chosema I didn't quite follow the logic of creating this new factory class for Query class resolution, I expect this parameter `querydsl.packageSuffix` to be supported out of the box and not when I need to twist things. @Shredder121 I think based on the [clear evidence](https://github.com/spring-projects/spring-data-commons/blob/0237760345faa011bdc6639ec838790be3d41e9b/src/main/java/org/springframework/data/querydsl/SimpleEntityPathResolver.java#L98) given by @chosema (Thanks!) it should be easy to file an issue with them to support this parameter, otherwise using the `querydsl.packageSuffix` is really a no-go for folks.

**Comment by panih2o** [comment]
FYI I have filed the issue here : https://jira.spring.io/browse/DATAJPA-1234

**Comment by Shredder121** [comment]
Ah, thanks
Although still, the package configuration would have to be kept in sync
But we'll see what they say, whether they want to support it at all or not
:+1:

**Comment by schauder** [comment]
I'm looking into this from the Spring Data side. Tweaking the method to consider a package suffix shouldn't be much of a problem. But the question is: do we have a way to determine the suffix without forcing the user to configure it again somewhere in Spring Data?

**Comment by Shredder121** [comment]
> But the question is: do we have a way to determine the suffix without forcing the user to configure it again somewhere in Spring Data?

I don't think so, hence my "Although still, the package configuration would have to be kept in sync".

**Comment by mmm8955405** [comment]
> > But the question is: do we have a way to determine the suffix without forcing the user to configure it again somewhere in Spring Data?
> 
> I don't think so, hence my "Although still, the package configuration would have to be kept in sync". Apt takes the options at compile time.

Why not under different packages? You just leave the problem to spring data? To pass the buck and turn off the problem directly.

**Comment by mmm8955405** [comment]
In the same newspaper, the name also conflicts with the entity starting with Q, which is a confusing name and design method

**Comment by mmm8955405** [comment]
Spring data also does not provide a simple configuration method. So what a pain and hard to use thing!!!!!
