### ISSUE TITLE
UUID primary key mapping

### ISSUE THREAD

**Issue by selimnairb** [querydsl/querydsl#2220]
Hello,

I am experimenting with using Querydsl on a PostgreSQL database that uses time-based UUIDs for primary keys.  The problem I am having is that the generated classes from Querydsl are mapping the UUID columns to `SimplePath<byte[]>`. This means it is not possible to (or at least I haven't figured out how to) order query results in ascending order based on the time-based UUID key.  It seems like mapping the UUID columns to something like `ComparablePath<UUID>` would be more appropriate. 

I am new to Querydsl, so please accept my apologies if UUID support/custom mapping is described somewhere, however I could not figure out how to change the mapping of the UUID primary key columns.  Thanks.

**Comment by selimnairb** [comment]
Okay, I can get the UUID columns to map to `java.util.UUID` instead of `byte[]` as follows:

```
<typeMappings>
  <typeMapping>
    <table>FOO</table>
    <column>ID</column>
    <type>java.util.UUID</type>
  </typeMapping>
</typeMappings>
```

As per [here](http://www.querydsl.com/static/querydsl/latest/reference/html/ch02s03.html), however the final mapped type is still `SimplePath<UUID>`.  Is there anyway to customize the mapping to force it to be `ComparablePath<UUID>`?

**Comment by selimnairb** [comment]
@timowest I have issued a PR against https://github.com/querydsl/codegen that addresses this problem: https://github.com/querydsl/codegen/pull/41.  Do you have any plans to do releases of codegen and querydsl in the near future?

**Comment by Shredder121** [comment]
Timo wants to distance himself from the Querydsl project, he's really busy lately, however I/we do not have all the keys, so to speak.
But I'm sure if I poke him, releases can be made.
Thanks anyway 👍
