### ISSUE TITLE
rows().preceding not working on MS SQL

### ISSUE THREAD

**Issue by rgra** [querydsl/querydsl#2223]
SQLExpressions.sum(tr.value)
		.over()
		.partitionBy( tr.productId)
		.orderBy(tr.valueDate)
		.rows().preceding(3);

This creates the following SQL
sum( "value" ) over(partition by product_id order by value_date desc rows preceding 3)

This won't execute on MS SQL Server 2012+ because it has to be
rows 3 preceding 

Currently there  is no way to fix this with templates, because it is hard coded in WindowRows.

**Comment by jwgmeligmeyling** [comment]
Accepting PRs.

**Comment by allanhaywood** [comment]
@jwgmeligmeyling I'm looking into this. Can I be assigned?

**Comment by allanhaywood** [comment]
Created PR: https://github.com/querydsl/querydsl/pull/3111
