### ISSUE TITLE
JPASQLQuery does not work after upgrading Hibernate 5.1 to 5.2

### ISSUE THREAD

**Issue by lpandzic** [querydsl/querydsl#2226]
I'm opening new issue for this like it was suggested in https://github.com/querydsl/querydsl/issues/1917.

I've created a project with test that can be used to easily reproduce the issue:
https://github.com/lpandzic/querydsl-hibernate-5.2-integration-test/blob/master/src/test/java/com/github/lpandzic/QuerydslHibernateIntegrationTest.java

Keep in mind to start docker for database as is described in test javadoc on top of class.

Hibernate and querydsl version can be calibrated with https://github.com/lpandzic/querydsl-hibernate-5.2-integration-test/blob/master/pom.xml#L27-L33

**Comment by jwgmeligmeyling** [comment]
Hibernate 5.x should be properly supported on 5.0-SNAPSHOT.
