### ISSUE TITLE
querydsl-maven-plugin doesn't support type which constructor has params

### ISSUE THREAD

**Issue by hsupu** [querydsl/querydsl#2230]
`querydsl-maven-plugin` support a way to generate code via maven, but I found that it doesn't support some types:

`com.querydsl.sql.types.EnumByNameType` is a generic class, and it's constructor require a param(`Class<T>`). But `com.querydsl.sql.codegen.support.TypeMapping` only accept type as a class name, and instance without arguments.

**Comment by jwgmeligmeyling** [comment]
Closing as duplicate of #2561 which was fixed in QueryDSL 4.4.0.
