### ISSUE TITLE
Missing NonUniqueResultException from Fetchable.fetchOne() method documentation

### ISSUE THREAD

**Issue by cdalexndr** [querydsl/querydsl#2232]
```
Description copied from interface: com.querydsl.core.Fetchable 
Get the projection as a unique result or null if no result is found
Overrides:
fetchOne in class ProjectableSQLQuery
Returns:
first result or null
```
If more than one result is returned, NonUniqueResultException is thrown.

**Comment by reegnz** [comment]
Where in the documentation did you find the missing exception declaration?
In the JavaDoc it's there, also generated into the html:
http://www.querydsl.com/static/querydsl/4.1.3/apidocs/com/querydsl/core/Fetchable.html#fetchOne--

**Comment by reegnz** [comment]
OK, I see what the problem is:
For subclasses JavaDoc only copies the description, but '@throws' part of the javadoc is not copied to implementors/subclasses.

Couldn't find a solution yet on how to force javadoc to copy that as well.

**Comment by reegnz** [comment]
Example of '@throws' not being copied:
http://www.querydsl.com/static/querydsl/4.1.3/apidocs/com/querydsl/collections/AbstractCollQuery.html#fetchOne--

**Comment by reegnz** [comment]
Another project seems to have found this solution:
https://github.com/joel-costigliola/assertj-core/issues/93

Seems suboptimal, having to redeclare the exception type in the subclass/implementor javadoc.

**Comment by reegnz** [comment]
Quoting from javadoc documentation: https://docs.oracle.com/javase/7/docs/technotes/tools/windows/javadoc.html#inheritingcomments

> When a @throws tag for a particular exception is missing, the @throws tag is copied only if that exception is declared.

I would try explicitly declaring the throw and see if it gets copied properly. Apparently declaring thows only in javadoc and not in the java code makes copying the @throws part not being executed.

**Comment by reegnz** [comment]
Did the experiment. The results are:
* ❌  Not declaring throws in the interface, not declaring throws in the impl: @ throws javadoc not copied
* ❌  Declaring throws in the interface, not declaring throws in the impl: @throws javadoc not copied
* ✔️ Declaring throws in the interface, declaring throws in the impl: @throws javadoc is copied
* ✔️ Not declaring throws in the interface, declaring throws in the impl: @throws javadoc is copied

**Comment by reegnz** [comment]
So to resolve this I would suggest to always delcare throws in interfaces, even if they are runtime exceptions.
Most IDE-s then copy the entire signature with throws declaration, so the declaration would be copied on all implementations.

Existing implementations have to be adjusted by hand to include the throws declaration.
