### ISSUE TITLE
Iterating over query results without loading all

### ISSUE THREAD

**Issue by hylkevds** [querydsl/querydsl#2237]
Hi,

I've got a resultset that does not fit in memory. The problem is that Query.fetch() and Query.fetchResults() both try to fetch the entire resultset and put it in a List. That doesn't work in my case.

The only way I found so far that properly uses the database cursor to iterate over the result is Query.getResults(). However, I've not found a way to nicely create Tuples from a java.sql.ResultSet so I can use the nice type-safe interfaces. AbstractSQLQuery does this internally of course, but all the required information is hidden in private members.

Am I overlooking something, or is there really no nice way to do this at the moment?

**Comment by Shredder121** [comment]
You should be able to use `iterate()`  after using an appropriate `select()`

As seen here only 2 fields are selected of the resultset, one at a time (iterating).

https://github.com/querydsl/querydsl/blob/421049b4718350963679204d6521241c1a8cf366/querydsl-sql/src/test/java/com/querydsl/sql/SelectBase.java#L1418-L1426

**Comment by hylkevds** [comment]
Ah, excellent. Thanks for the pointer!
