### ISSUE TITLE
Can JPAUpdateClause addBatch Function?

### ISSUE THREAD

**Issue by rplees** [querydsl/querydsl#2240]
Hi,I found `SQLUpdateClause.addbatch()` only in an example while exploring theJPAUpdateClauseclass, but I didn't find any possibility of batch update. Can you suggest any workaround? Thanks!

**Comment by timowest** [comment]
Are batches supported in JPA update clauses?
AI can't think of any other workaround then doing Object modifications and to persist the changes.

**Comment by rplees** [comment]
@timowest understand, thks
