### ISSUE TITLE
Annotation processing breaks with Java 9 

### ISSUE THREAD

**Issue by reegnz** [querydsl/querydsl#2242]
Related issue:
https://github.com/google/auto/issues/560

Solution is to use type mirrors correctly:
* javax.annotation.Generated for pre java9
* javax.annotation.processing.Generated for java9 onwards.

**Comment by reegnz** [comment]
In auto-value they solved it like this:
https://github.com/google/auto/blob/master/common/src/main/java/com/google/auto/common/GeneratedAnnotations.java#L54

**Comment by reegnz** [comment]
Dagger also faced the same issue: https://github.com/google/dagger/issues/880

**Comment by reegnz** [comment]
There is a reasonable workaround:
https://github.com/rzwitserloot/lombok/issues/1472#issuecomment-339779910

But this just means the processor won't break during compile time.
The annotation javax.annotations.Generated is still deprecated with java9 forward, so there needs to be a future-proof solution as well that doesn't include having to pull that jar with you.

**Comment by cdalexndr** [comment]
Relevant stacktrace in querydsl-codegen-4.2.1, when running MetaDataExporter from gradle task:
```
Caused by: java.lang.NoClassDefFoundError: javax/annotation/Generated
	at com.querydsl.codegen.EntitySerializer.introImports(EntitySerializer.java:423)
	at com.querydsl.sql.codegen.MetaDataSerializer.introImports(MetaDataSerializer.java:167)
	at com.querydsl.codegen.EntitySerializer.intro(EntitySerializer.java:269)
	at com.querydsl.codegen.EntitySerializer.serialize(EntitySerializer.java:594)
	at com.querydsl.sql.codegen.MetaDataExporter.write(MetaDataExporter.java:435)
	at com.querydsl.sql.codegen.MetaDataExporter.serialize(MetaDataExporter.java:420)
	at com.querydsl.sql.codegen.MetaDataExporter.handleTable(MetaDataExporter.java:393)
	at com.querydsl.sql.codegen.MetaDataExporter.handleTables(MetaDataExporter.java:260)
	at com.querydsl.sql.codegen.MetaDataExporter.export(MetaDataExporter.java:251)
	at com.querydsl.sql.codegen.MetaDataExporter$export$5.call(Unknown Source)
	at build_6do9vdrevjymc6k4n3vzehc62$_run_closure14$_closure41.doCall(C:\...\build.gradle:183)
```

**Comment by thackel** [comment]
J9 in classpath mode you'll need another dependency:
`<dependency>
    <groupId>javax.annotation</groupId>
    <artifactId>javax.annotation-api</artifactId>
</dependency>
`

**Comment by Maia-Everett** [comment]
Adding the `javax.annotation-api` artifact fixes the issue for me with javac.

Annotation processing seems to be still broken when compiling with ecj. Under Java 10, ecj silently ignores the querydsl annotation processor (Java 8 works fine). That one seems to be a separate issue.

**Comment by onacit** [comment]
Do we have any chance for having an option for suppressing `@Generated` annotation?
[JPAMetaModelEntityProcessor](http://docs.jboss.org/hibernate/orm/current/javadocs/org/hibernate/jpamodelgen/JPAMetaModelEntityProcessor.html) has [an option](http://docs.jboss.org/hibernate/jpamodelgen/1.2/reference/en-US/html/chapter-usage.html#d0e349) for that.

**Comment by reegnz** [comment]
This issue was fixed with #785.
@onacit please open a different ticket for your issue.

**Comment by OrangeDog** [comment]
The pom for querydsl-apt should declare a dependency on `javax.annotation-api`. That should fix it.

**Comment by kamko** [comment]
It should even more because as of java 11 it was removed from jdk.
https://stackoverflow.com/questions/48204141/replacements-for-deprecated-jpms-modules-with-java-ee-apis/48204154#48204154

**Comment by mhorehle** [comment]
Is there any plans or chances for a soon fix? This issue has apparently been open for a while, and as we would like to upgrade to Java 9/10 or even 11, we would really need this fix. Or is there any known workaround (with maven build)? We have tried a ton of conceivable approaches, unfortunately none worked.

**Comment by IdoSalomon** [comment]
> Is there any plans or chances for a soon fix? This issue has apparently been open for a while, and as we would like to upgrade to Java 9/10 or even 11, we would really need this fix. Or is there any known workaround (with maven build)? We have tried a ton of conceivable approaches, unfortunately none worked.

Didn't [this](https://github.com/querydsl/querydsl/issues/2488) work? Personally, I use Gradle 5 + Java 11 + Spring (spring-boot-starter-data-jpa annotation processor) so I'm covered by persistence-api. :)

**Comment by mhorehle** [comment]
We are using maven and we have tried the workaround as described (adding >jakarta.persistence-api< and >javax.annotation-api< dependencies):

> <plugin>
	<configuration>
		<annotationProcessorPaths>
			<path>
				<groupId>com.querydsl</groupId>
				<artifactId>querydsl-apt</artifactId>
				<version>${querydsl.version}</version>
				<classifier>jpa</classifier>
			</path>
		</annotationProcessorPaths>
		<compilerArgs>
			<arg>-Aquerydsl.entityAccessors=true</arg>
			<arg>-Aquerydsl.useFields=false</arg>
			<arg>-Amapstruct.defaultComponentModel=spring</arg>
		</compilerArgs>
	</configuration>
	<dependencies>
		<dependency>
			<groupId>jakarta.persistence</groupId>
			<artifactId>jakarta.persistence-api</artifactId>
			<version>2.2.3</version>
		</dependency>
		<dependency>
			<groupId>javax.annotation</groupId>
			<artifactId>javax.annotation-api</artifactId>
			<version>1.3.2</version>
		</dependency>
	</dependencies>
</plugin>

However, we still get the NoClassDefFoundError:

> [ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.
8.0:compile (default-compile) on project dca-core-persistence-entity-jar: Fa
tal error compiling: java.lang.NoClassDefFoundError: javax/annotation/Generated:
 javax.annotation.Generated -> [Help 1]

**Comment by kamko** [comment]
Could you provide a full example POM?

**Comment by OrangeDog** [comment]
@mhorehle if you're using `annotationProcessorPaths` then the dependencies need to go there, not in the project dependencies.

**Comment by mhorehle** [comment]
@kamko this is the full POM we are using (sorry, it's quite big - I have already cleaned it up a bit, but did not want to remove too much or anything essential; @OrangeDog we are in fact using 
`annotationProcessorPaths` and if you have a look at the POM, we have added the dependencies there as well right after the `configuration` tag ):

> <project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<groupId>at.gv.bmf.zk.parent</groupId>
	<artifactId>abc-parent-pom</artifactId>
	<name>ABC Parent Project</name>
	<version>1.0.37-SNAPSHOT</version>
	<packaging>pom</packaging>
	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>2.2.1.RELEASE</version>
	</parent>
	<properties>
		
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
		<use-minified-res>false</use-minified-res>
		<flyway.version>6.1.0</flyway.version>
		<spring-boot.version>2.2.1.RELEASE</spring-boot.version>
		<tomcat.version>8.5.5</tomcat.version>
		<cxf.version>3.3.4</cxf.version>
		<wss4j.version>2.2.2</wss4j.version>
		<ojdbc8.version>12.2.0.1</ojdbc8.version>
		<org.mapstruct.version>1.3.0.Final</org.mapstruct.version>
		<com.google.guava.version>27.1-jre</com.google.guava.version>
		<org.projectlombok.version>1.18.10</org.projectlombok.version>
		<jcl-over-slf4j.version>1.7.25</jcl-over-slf4j.version>
		<org.apache.commons.version>3.6</org.apache.commons.version>
		<org.apache.commons.text.version>1.6</org.apache.commons.text.version>
		<version.org.apache.validator>1.6</version.org.apache.validator>
		<commons-io.version>2.6</commons-io.version>
		<org.assertj-core.version>3.6.2</org.assertj-core.version>
		<javax-inject.version>1</javax-inject.version>
		<javax.el-api.version>3.0.0</javax.el-api.version>
		<javax.servlet-api.version>3.1.0</javax.servlet-api.version>
		<tibco-ems.version>6.1.0</tibco-ems.version>
		<jms.version>2.0</jms.version>
		<version.joox>1.4.0</version.joox>
		<version.com.fasterxml.jackson>2.10.1</version.com.fasterxml.jackson>
		<javax.activation.version>1.2.0</javax.activation.version>
		<jaxb.api.version>2.3.0</jaxb.api.version>
		<jaxws-api.version>2.3.1</jaxws-api.version>
		
		<maven-clean-plugin.version>3.1.0</maven-clean-plugin.version>
		<maven-versions-plugin.version>2.5</maven-versions-plugin.version>
		<maven-compiler-plugin.version>3.8.0</maven-compiler-plugin.version>
		<maven-source-plugin.version>3.0.1</maven-source-plugin.version>
		<maven-resources-plugin.version>3.0.2</maven-resources-plugin.version>
		<maven-surefire-plugin.version>2.22.0</maven-surefire-plugin.version>
		<maven-surefire-report-plugin.version>2.22.0</maven-surefire-report-plugin.version>
		<maven-failsafe-plugin.version>2.19.1</maven-failsafe-plugin.version>
		<maven-jar-plugin.version>3.0.2</maven-jar-plugin.version>
		<maven-war-plugin.version>2.0.1</maven-war-plugin.version>
		<maven-install-plugin.version>2.3.1</maven-install-plugin.version>
		<build-helper-maven-plugin.version>3.0.0</build-helper-maven-plugin.version>
		<jaxws-maven-plugin.version>2.5</jaxws-maven-plugin.version>
		<flyway-maven-plugin.version>6.1.0</flyway-maven-plugin.version>
		<cxf-codegen-plugin.version>3.3.4</cxf-codegen-plugin.version>
		
		<dir.resources.main>${basedir}/src/main/resources</dir.resources.main>
		<dir.resources.test>${basedir}/src/test/resources</dir.resources.test>
		
		<dir.resources.filter.test>${basedir}/src/test/filters</dir.resources.filter.test>
		<resources.filter.filename.test>testFilter.properties</resources.filter.filename.test>
	</properties>
	<dependencyManagement>
		<dependencies>
			
			<dependency>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-starter</artifactId>
				<version>${spring-boot.version}</version>
				<exclusions>
					<exclusion>
						<groupId>org.springframework.boot</groupId>
						<artifactId>spring-boot-starter-logging</artifactId>
					</exclusion>
				</exclusions>
			</dependency>
			<dependency>
				<groupId>org.apache.tomcat.embed</groupId>
				<artifactId>tomcat-embed-core</artifactId>
				<version>9.0.29</version>
			</dependency>
			
			<dependency>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-starter-data-jpa</artifactId>
				<version>${spring-boot.version}</version>
			</dependency>
			
			<dependency>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-starter-web</artifactId>
				<version>${spring-boot.version}</version>
			</dependency>
			
			<dependency>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-autoconfigure</artifactId>
				<version>${spring-boot.version}</version>
			</dependency>
			
			<dependency>
				<groupId>org.apache.cxf</groupId>
				<artifactId>cxf-rt-frontend-jaxws</artifactId>
				<version>${cxf.version}</version>
			</dependency>
			<dependency>
				<groupId>org.apache.cxf</groupId>
				<artifactId>cxf-rt-transports-http</artifactId>
				<version>${cxf.version}</version>
			</dependency>
			<dependency>
				<groupId>org.apache.cxf</groupId>
				<artifactId>cxf-rt-features-logging</artifactId>
				<version>${cxf.version}</version>
			</dependency>
			<dependency>
				<groupId>org.apache.cxf</groupId>
				<artifactId>cxf-rt-ws-security</artifactId>
				<version>${cxf.version}</version>
			</dependency>
			<dependency>
				<groupId>org.apache.cxf</groupId>
				<artifactId>cxf-rt-bindings-soap</artifactId>
				<version>${cxf.version}</version>
			</dependency>
			<dependency>
				<groupId>org.apache.wss4j</groupId>
				<artifactId>wss4j-ws-security-dom</artifactId>
				<version>${wss4j.version}</version>
			</dependency>
			<dependency>
				<groupId>org.apache.wss4j</groupId>
				<artifactId>wss4j-ws-security-common</artifactId>
				<version>${wss4j.version}</version>
			</dependency>
			
			<dependency>
				<groupId>javax.inject</groupId>
				<artifactId>javax.inject</artifactId>
				<version>${javax-inject.version}</version>
			</dependency>
			
			<dependency>
				<groupId>org.mapstruct</groupId>
				<artifactId>mapstruct-jdk8</artifactId>
				<version>${org.mapstruct.version}</version>
			</dependency>
			
			<dependency>
				<groupId>com.oracle.jdbc</groupId>
				<artifactId>ojdbc8</artifactId>
				<version>${ojdbc8.version}</version>
			</dependency>
			<dependency>
				<groupId>org.flywaydb</groupId>
				<artifactId>flyway-core</artifactId>
				<version>${flyway.version}</version>
			</dependency>
			<dependency>
				<groupId>org.apache.tomcat</groupId>
				<artifactId>tomcat-dbcp</artifactId>
				<version>${tomcat.version}</version>
			</dependency>
			
			<dependency>
				<groupId>com.google.guava</groupId>
				<artifactId>guava</artifactId>
				<version>${com.google.guava.version}</version>
			</dependency>
			
			<dependency>
				<groupId>org.projectlombok</groupId>
				<artifactId>lombok</artifactId>
				<version>${org.projectlombok.version}</version>
			</dependency>
			
			<dependency>
				<groupId>javax.el</groupId>
				<artifactId>javax.el-api</artifactId>
				<version>${javax.el-api.version}</version>
			</dependency>
			
			<dependency>
				<groupId>org.assertj</groupId>
				<artifactId>assertj-core</artifactId>
				<version>${org.assertj-core.version}</version>
			</dependency>
			
			<dependency>
				<groupId>org.apache.commons</groupId>
				<artifactId>commons-lang3</artifactId>
				<version>${org.apache.commons.version}</version>
			</dependency>
			<dependency>
				<groupId>org.apache.commons</groupId>
				<artifactId>commons-text</artifactId>
				<version>${org.apache.commons.text.version}</version>
			</dependency>
			
			<dependency>
				<groupId>commons-io</groupId>
				<artifactId>commons-io</artifactId>
				<version>${commons-io.version}</version>
			</dependency>
			
			<dependency>
				<groupId>commons-validator</groupId>
				<artifactId>commons-validator</artifactId>
				<version>${version.org.apache.validator}</version>
			</dependency>
			
			<dependency>
				<groupId>javax.servlet</groupId>
				<artifactId>javax.servlet-api</artifactId>
				<version>${javax.servlet-api.version}</version>
			</dependency>
			
			<dependency>
				<groupId>org.jooq</groupId>
				<artifactId>joox</artifactId>
				<version>${version.joox}</version>
			</dependency>
			
			<dependency>
				<groupId>com.fasterxml.jackson.core</groupId>
				<artifactId>jackson-core</artifactId>
				<version>${version.com.fasterxml.jackson}</version>
			</dependency>
			
			<dependency>
				<groupId>com.querydsl</groupId>
				<artifactId>querydsl-apt</artifactId>
				<version>${querydsl.version}</version>
			</dependency>
			<dependency>
				<groupId>com.querydsl</groupId>
				<artifactId>querydsl-jpa</artifactId>
				<version>${querydsl.version}</version>
			</dependency>
			<dependency>
				<groupId>com.sun.xml.bind</groupId>
				<artifactId>jaxb-xjc</artifactId>
				<version>${jaxb.api.version}</version>
			</dependency>
			<dependency>
				<groupId>com.sun.activation</groupId>
				<artifactId>javax.activation</artifactId>
				<version>${javax.activation.version}</version>
			</dependency>
			<dependency>
				<groupId>javax.xml.bind</groupId>
				<artifactId>jaxb-api</artifactId>
				<version>${jaxb.api.version}</version>
			</dependency>
			<dependency>
				<groupId>com.sun.xml.bind</groupId>
				<artifactId>jaxb-core</artifactId>
				<version>${jaxb.api.version}</version>
			</dependency>
			<dependency>
				<groupId>com.sun.xml.bind</groupId>
				<artifactId>jaxb-impl</artifactId>
				<version>${jaxb.api.version}</version>
			</dependency>
			<dependency>
				<groupId>javax.xml.ws</groupId>
				<artifactId>jaxws-api</artifactId>
				<version>${jaxws-api.version}</version>
			</dependency>
			<dependency>
				<groupId>javax.annotation</groupId>
				<artifactId>javax.annotation-api</artifactId>
				<version>1.3.2</version>
			</dependency>
			<dependency>
				<groupId>javax.xml.bind</groupId>
				<artifactId>jaxb-api</artifactId>
				<version>2.4.0-b180725.0427</version>
			</dependency>
			<dependency>
				<groupId>com.sun.xml.ws</groupId>
				<artifactId>jaxws-ri</artifactId>
				<version>2.3.0</version>
			</dependency>
			<dependency>
				<groupId>commonj.sdo</groupId>
				<artifactId>commonj.sdo</artifactId>
				<version>2.1.1.v201112051852</version>
			</dependency>
			<dependency>
				<groupId>org.glassfish.jaxb</groupId>
				<artifactId>jaxb-runtime</artifactId>
				<version>2.4.0-b180725.0644</version>
			</dependency>
			<dependency>
				<groupId>jakarta.persistence</groupId>
				<artifactId>jakarta.persistence-api</artifactId>
				<version>2.2.3</version>
			</dependency>
			<dependency>
				<groupId>com.sun.xml.ws</groupId>
				<artifactId>jaxws-rt</artifactId>
				<version>2.3.1</version>
				<type>pom</type>
			</dependency>
			<dependency>
				<groupId>com.sun.xml.ws</groupId>
				<artifactId>rt</artifactId>
				<version>2.3.1</version>
			</dependency>
			<dependency>
				<groupId>com.sun.istack</groupId>
				<artifactId>istack-commons-runtime</artifactId>
				<version>3.0.7</version>
			</dependency>
			<dependency>
				<groupId>javax.xml.bind</groupId>
				<artifactId>jaxb-api</artifactId>
				<version>2.3.0</version>
			</dependency>
			<dependency>
				<groupId>org.glassfish.jaxb</groupId>
				<artifactId>jaxb-core</artifactId>
				<version>2.3.0.1</version>
			</dependency>
			<dependency>
				<groupId>com.sun.xml.bind</groupId>
				<artifactId>jaxb-impl</artifactId>
				<version>2.3.0</version>
			</dependency>
			<dependency>
				<groupId>org.glassfish.jaxb</groupId>
				<artifactId>jaxb-runtime</artifactId>
				<version>2.3.2</version>
			</dependency>
			<dependency>
				<groupId>com.sun.xml.ws</groupId>
				<artifactId>jaxws-ri</artifactId>
				<version>2.3.0</version>
				<type>pom</type>
			</dependency>
		</dependencies>
	</dependencyManagement>
	<build>
		<pluginManagement>
			<plugins>
				
				<plugin>
					<groupId>org.apache.maven.plugins</groupId>
					<artifactId>maven-enforcer-plugin</artifactId>
					<version>3.0.0-M2</version>
					<executions>
						<execution>
							<id>enforce-java</id>
							<goals>
								<goal>enforce</goal>
							</goals>
							<configuration>
								<rules>
									<requireMavenVersion>
										<version>3.0.5</version>
									</requireMavenVersion>
									<requireJavaVersion>
										<version>[1.8,)</version>
									</requireJavaVersion>
									<requireProperty>
										<property>project.build.sourceEncoding</property>
										<message>Encoding must be set
											and at UTF-8!</message>
										<regex>UTF-8</regex>
										<regexMessage>Encoding must be
											set and at UTF-8</regexMessage>
									</requireProperty>
								</rules>
								<fail>true</fail>
							</configuration>
						</execution>
					</executions>
				</plugin>
				<plugin>
					<groupId>org.codehaus.mojo</groupId>
					<artifactId>versions-maven-plugin</artifactId>
					<version>${maven-versions-plugin.version}</version>
					<configuration>
						<generateBackupPoms>false</generateBackupPoms>
					</configuration>
				</plugin>
				
				<plugin>
					<groupId>org.apache.maven.plugins</groupId>
					<artifactId>maven-clean-plugin</artifactId>
					<version>${maven-clean-plugin.version}</version>
				</plugin>
				
				<plugin>
					<groupId>org.apache.maven.plugins</groupId>
					<artifactId>maven-compiler-plugin</artifactId>
					<version>${maven-compiler-plugin.version}</version>
					<configuration>
						<release>11</release>
						<annotationProcessorPaths>
							<path>
								
								<groupId>org.projectlombok</groupId>
								<artifactId>lombok</artifactId>
								<version>${org.projectlombok.version}</version>
							</path>
							
							<path>
								<groupId>org.mapstruct</groupId>
								<artifactId>mapstruct-processor</artifactId>
								<version>${org.mapstruct.version}</version>
							</path>
							
							<path>
								<groupId>org.hibernate</groupId>
								<artifactId>hibernate-jpamodelgen</artifactId>
								<version>${hibernate.version}</version>
							</path>
							
							<path>
								<groupId>org.hibernate.javax.persistence</groupId>
								<artifactId>hibernate-jpa-2.1-api</artifactId>
								<version>1.0.0.Final</version>
							</path>
							
							<path>
								<groupId>com.querydsl</groupId>
								<artifactId>querydsl-apt</artifactId>
								<version>${querydsl.version}</version>
								<classifier>jpa</classifier>
							</path>
						</annotationProcessorPaths>
						<compilerArgs>
							<arg>-Aquerydsl.entityAccessors=true</arg>
							<arg>-Aquerydsl.useFields=false</arg>
							<arg>-Amapstruct.defaultComponentModel=spring</arg>
						</compilerArgs>
					</configuration>
					<dependencies>
						<dependency>
							<groupId>jakarta.persistence</groupId>
							<artifactId>jakarta.persistence-api</artifactId>
							<version>2.2.3</version>
						</dependency>
						<dependency>
							<groupId>javax.annotation</groupId>
							<artifactId>javax.annotation-api</artifactId>
							<version>1.3.2</version>
						</dependency>
					</dependencies>
				</plugin>
				<plugin>
					<groupId>org.apache.maven.plugins</groupId>
					<artifactId>maven-source-plugin</artifactId>
					<version>${maven-source-plugin.version}</version>
					<executions>
						<execution>
							<id>attach-sources</id>
							<goals>
								<goal>jar</goal>
							</goals>
						</execution>
					</executions>
				</plugin>
				
				<plugin>
					<groupId>org.apache.maven.plugins</groupId>
					<artifactId>maven-resources-plugin</artifactId>
					<version>${maven-resources-plugin.version}</version>
				</plugin>
				
				<plugin>
					<groupId>org.apache.maven.plugins</groupId>
					<artifactId>maven-jar-plugin</artifactId>
					<version>${maven-jar-plugin.version}</version>
				</plugin>
				
				<plugin>
					<groupId>org.apache.cxf</groupId>
					<artifactId>cxf-codegen-plugin</artifactId>
					<version>${cxf-codegen-plugin.version}</version>
				</plugin>
				<plugin>
					<groupId>org.codehaus.mojo</groupId>
					<artifactId>jaxws-maven-plugin</artifactId>
					<version>${jaxws-maven-plugin.version}</version>
				</plugin>
			</plugins>
		</pluginManagement>
		<plugins>
			
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-enforcer-plugin</artifactId>
			</plugin>
		</plugins>
	</build>
</project>

**Comment by kamko** [comment]
You added the 2 packages to `maven-compiler-plugin` dependencies, not to annotation paths.
This works for me:
```
Maven home: C:\Users\j\.m2\wrapper\dists\apache-maven-3.6.2-bin\795eh28tki48bv3l67maojf0ra\apache-maven-3.6.2
Java version: 11.0.4, vendor: AdoptOpenJDK, runtime: C:\bin\jdk-11.0.4.11-hotspot
Default locale: en_US, platform encoding: Cp1252
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"
```

```
<plugin>
    <groupId>org.apache.maven.plugins</groupId>
    <artifactId>maven-compiler-plugin</artifactId>
    <version>${maven-compiler-plugin.version}</version>
    <configuration>
        <release>11</release>
        <annotationProcessorPaths>
            <!-- QueryDSL -->
            <path>
                <groupId>com.querydsl</groupId>
                <artifactId>querydsl-apt</artifactId>
                <version>${querydsl.version}</version>
                <classifier>jpa</classifier>
            </path>
            <path>
                <groupId>javax.annotation</groupId>
                <artifactId>javax.annotation-api</artifactId>
                <version>1.3.2</version>
            </path>
            <path>
                <groupId>jakarta.persistence</groupId>
                <artifactId>jakarta.persistence-api</artifactId>
                <version>2.2.3</version>
            </path>
        </annotationProcessorPaths>
        <compilerArgs>
            <arg>-Aquerydsl.entityAccessors=true</arg>
            <arg>-Aquerydsl.useFields=false</arg>
            <arg>-Amapstruct.defaultComponentModel=spring</arg>
        </compilerArgs>
    </configuration>
</plugin>
```

**Comment by mhorehle** [comment]
@kamko perfect. Thank you, that works for me too now.

**Comment by reegnz** [comment]
I will close this issue as it's been open for close to 3 years without anyone trying to fix this. Workarounds are worked fine in these past 3 years (add the annotations to the classpath), so I consider this issue closed. If somebody is willing to fix this later on, please open a separate issue and/or pull-request.

**Comment by kamko** [comment]
Actually, the issue was recently added to the backlog for 5.x

**Comment by gsych** [comment]
For those who are still fighting with the issue and when all proposed workarounds don't work, here is what helped me (Java 11):
```
    // querydsl
    annotationProcessor     'com.querydsl:querydsl-apt:4.1.3:jpa'
    annotationProcessor     'org.springframework.boot:spring-boot-starter-data-jpa' // needed because the query dsl annotation processor doesn't recognize javax.persistence.Entity
    compile                 'com.querydsl:querydsl-jpa:4.1.3'
```

Taken from https://stackoverflow.com/questions/50537096/annotationprocessor-and-dependencies

**Comment by kamko** [comment]
The option with adding jakarta packages is correct. You definitely don't want to import whole `spring-boot-starter-data-jpa` just for jpa annotations...

**Comment by gsych** [comment]
Indeed. Maybe can be helpful still if one already has `spring-boot-starter-data-jpa` as a dependency.
