### ISSUE TITLE
Illegal operation for date fields

### ISSUE THREAD

**Issue by rodrigorodrigues** [querydsl/querydsl#2244]
Hi everyone,

I'm trying to convert a date to string but got the following exception:
`java.lang.UnsupportedOperationException: Illegal operation str(workOrder.creationDate) = 1970
	at com.querydsl.mongodb.MongodbSerializer.visit(MongodbSerializer.java:99)`

Anyone knows how to achieve that please?
The expression I'm using is `QWorkOrder.workOrder.creationDate.stringValue().eq(dynamicSearch)` and the Q classes were generated using the maven apt plugin.

`public class QWorkOrder extends EntityPathBase<WorkOrder> {
public final DateTimePath<java.time.ZonedDateTime> creationDate = createDateTime("creationDate", java.time.ZonedDateTime.class);
}
`
I believe the problem is when I call the method `stringValue()` but not sure how to compare a date field with a text value.

Thanks

**Comment by timowest** [comment]
It's currently not supported. Is there a way to express that for a Mongodb query? Feel free to create a PR to fix it.

**Comment by andreas-schilling** [comment]
Just stumbled on this as well, not for dates though. Seems this is not possible in general, it should however for dates. You can apply a `$dateToStr` (or any other expression operating on dates) using `$expr` in queries. No clue though how one would find a good way to apply all the parameters for date conversion...
So it looks like as of now there is not really a nice solution to this.
@rodrigorodrigues how is your date stored within the DB? If it is stored as a String but is a `DateTime` on application side then you might be able to use `@QueryType( PropertyType.STRING )` on the field. That helped in my case (I have a `URI` in the data model, but it's stored as a plain string).
