### ISSUE TITLE
Problem generating Q-Types with List

### ISSUE THREAD

**Issue by Birmania** [querydsl/querydsl#2245]
Hi

I have problem generating (with APT annotations) Q-Types for domain that contain List property.
Indeed, it generate QList instead of ListPath. Have you got any idea why ?

Example :
```
@QueryEntity
public class MyClass {
    private List<String> myProperty;
}
```

This is what is being generated :
```
/**
 * QMyClass is a Querydsl query type for MyClass
 */
@Generated("com.querydsl.codegen.EntitySerializer")
public class QMyClass extends EntityPathBase<MyClass> {

    private static final long serialVersionUID = -1055167226L;

    public static final QMyClass myClass = new QMyClass("myClass");

    // custom
    public final ext.java.util.QList myProperty = new ext.java.util.QList(forProperty("myProperty"));

    public QMyClass(String variable) {
        super(MyClass.class, forVariable(variable));
    }

    public QMyClass(Path<? extends MyClass> path) {
        super(path.getType(), path.getMetadata());
    }

    public QMyClass(PathMetadata metadata) {
        super(MyClass.class, metadata);
    }

}
```

QueryDSL version : 4.1.4
Eclise : 4.7.1a
Maven Integration For Eclipse JDT APT : 1.3.0

Thanks in advance for your help.
Yours faithfully,
Birmania

**Comment by Shredder121** [comment]
>QList

Can you check you do not have any `@QueryDelegate`s for List?
In order to add functionality to classes we do not control (like `java.util.List`) we have to make a Q-type of that as well.

**Comment by Birmania** [comment]
Never used the @QueryDelegate as I don't know perfectly how to use it.
So, java.util.List properties are not natively generated to ListPath ?

Is the "// custom" comment just above QList generated normal ?

Here is my maven POM (Something wrong ?) :
```
		<!-- QueryDSL -->
		<dependency> 
		    <groupId>com.querydsl</groupId> 
		    <artifactId>querydsl-apt</artifactId>
		    <version>4.1.4</version>
		    <optional>true</optional>
	    </dependency>
```

**Comment by Shredder121** [comment]
Could you show more of the entity class?
You really don't have `@QueryDelegate`?
Or did you maybe `import java.awt.*` and is it generating a Q-type for `java.awt.List`, since it's out of our control?

**Comment by Birmania** [comment]
Thanks a lot @Shredder121 for your help !
Following your indications, I just discovered that someone add, in the project, a @QueryEntity on a class that extends ArrayList !
I don't know why, but this @QueryEntity was generating a QList Q-Type which was also reused when generating Q-Type of the domain shown in the initial post.
