### ISSUE TITLE
Oracle bulk  insert

### ISSUE THREAD

**Issue by RazmikMkrtchyan** [querydsl/querydsl#2246]
I want to do bulk_insert on Oracle by  querydsl.

I  use   insert.setBatchToBulk(true) and **querydsl** as a results generates  following query

INSERT ALL
  INTO mytable (column1, column2, column_n) VALUES (expr1, expr2, expr_n)
  INTO mytable (column1, column2, column_n) VALUES (expr1, expr2, expr_n)
select * from dual

This query execution(executeWithKeys()) in oracle brings unique constraint error , reason  of unique pk.

fore more in image

<img width="1413" alt="screen shot 2018-01-25 at 8 37 09 pm" src="https://user-images.githubusercontent.com/11534590/35400232-9c510e5e-020f-11e8-80bc-619ffce315f3.png">

How to solve the problem?

**Comment by timowest** [comment]
This looks more like a support issue that should be handled in the Querydsl Google Group.

Do the two batches have different bindings for the primary key columns?

**Comment by RazmikMkrtchyan** [comment]
No,I am using the same table , and all the batches have the same binding. And the primary key is autoIncrementing  and does not participate in query.

**Comment by timowest** [comment]
This looks more like a Oracle issue. Could you reopen the issue again, if this turns out to be caused by Querydsl?

**Comment by RazmikMkrtchyan** [comment]
Ok.
