### ISSUE TITLE
Dependency issues querydsl-jpa on querydsl-sql

### ISSUE THREAD

**Issue by clucinvt** [querydsl/querydsl#2247]
It seems querydsl-jpa 4.1.4 does not declare dependency on querydsl-sql.
Error when querydsl-sql is missing:

> COMPILATION ERROR : 
> -------------------------------------------------------------
> some.package/SomeService.java:[40,30] cannot access javax.inject.Provider
>   class file for javax.inject.Provider not found

**Comment by clucinvt** [comment]
After checking querydsl-jpa / pom file, I see that the dependency on querydsl-sql is optional.

This is probably not a real issue.

**Comment by Shredder121** [comment]
Oh good catch!
Although I'm not sure we *need*... hmm
How are you depending on querydsl-jpa?

**Comment by clucinvt** [comment]
I was writing a simple Spring Boot command-line app.
Partial pom looks like this:

> <dependencies>
>         <dependency>
>             <groupId>org.springframework.boot</groupId>
>             <artifactId>spring-boot-starter-data-jpa</artifactId>
>         </dependency>
>         <dependency>
>             <groupId>com.h2database</groupId>
>             <artifactId>h2</artifactId>
>             <scope>runtime</scope>
>         </dependency>
>         <dependency>
>             <groupId>org.projectlombok</groupId>
>             <artifactId>lombok</artifactId>
>             <optional>true</optional>
>         </dependency>
>         <dependency>
>             <groupId>org.springframework.boot</groupId>
>             <artifactId>spring-boot-starter-test</artifactId>
>             <scope>test</scope>
>         </dependency>
>         <dependency>
>             <groupId>com.querydsl</groupId>
>             <artifactId>querydsl-jpa</artifactId>
>         </dependency>
>         <dependency>
>             <groupId>com.querydsl</groupId>
>             <artifactId>querydsl-sql</artifactId>
>             <version>4.1.4</version>
>         </dependency>
>         <dependency>
>             <groupId>org.springframework.boot</groupId>
>             <artifactId>spring-boot-starter-validation</artifactId>
>         </dependency>
>     </dependencies>

I manually added querydsl-sql after getting compilation error.

**Comment by timowest** [comment]
Could you provide more details on the compilation issue?

**Comment by clucinvt** [comment]
I think this will will help. This is the version containing compilation error.
[querydsljpa.zip](https://github.com/querydsl/querydsl/files/1697086/querydsljpa.zip)

**Comment by jwgmeligmeyling** [comment]
`querydsl-jpa` does not require `querydsl-sql`, but it does require  `javax-inject` (at least when using the QueryFactories).

QueryDSL 4.1.4 did not declare a dependency on `javax-inject` directly, thus relying on `querydsl-sql` to ship it transitively.

This was fixed in 4.2.0 by commit https://github.com/querydsl/querydsl/commit/e948321ea3a5003cb1be4b5feaaaf95c2b817f8f
