### ISSUE TITLE
QueryResults should return the input limit and offset

### ISSUE THREAD

**Issue by SzabKel** [querydsl/querydsl#2254]
Currently `QueryResults<T>.EMPTY` is returned (`QueryResults.emptyResults()` method) when the counting query returned zero result rows

For example: `AbstractJPAQuery.fetchResults()`, which returns `QueryResults<T>`:

```
Query countQuery = createQuery(null, true);
long total = (Long) countQuery.getSingleResult();
if (total > 0) {
	QueryModifiers modifiers = getMetadata().getModifiers();
	Query query = createQuery(modifiers, false);
	@SuppressWarnings("unchecked")
	List<T> list = (List<T>) getResultList(query);
	return new QueryResults<T>(list, modifiers, total);
} else {
	return QueryResults.emptyResults();
}
```

It should instead return a `QueryResults` with the input parameters. Otherwise, We need to explicitly check, whether we got empty `QueryResults` (because it changes the given limit to `Long.MAX_VALUE` and the offset to `0`), fix the limit and return our model. It would be easier to just process the `QueryResults` the same as when you get actual results.

**Comment by timowest** [comment]
You are right, this is inconsistent. Would you like to prepare a PR for a fix?
