### ISSUE TITLE
Multiple Column In clause Parameter 

### ISSUE THREAD

**Issue by ooxaam** [querydsl/querydsl#2257]
I'm new to query dsl and what I'm trying to do is that:

I have a list of accounts and currency and I want to search from table based on both of these params by passing them "IN" clause.

What I'm doing right now is :
```
JPASQLQuery query = JPASQLQuery(entityManager, OracleTemplates.DEFAULT);

SimpleExpression<List<String>>  idExpr = SimpleTemplate.create(List.class, "({0}, {1})", accountStatement.accountNumber, accountStatement.currency);

query.from(Qbean).where.(idExpr.in(accNum, currency).list();
```
accNum = List of String;
currency = List of String;

The result **I'm expecting** is that the query to be generated looks like this:
```
Select *
from PTE_ACC_STMNT accountStatement
where (accountStatement.ACCOUNT_NUMBER, accountStatement.currency) in (('accnum1', 'currency1'),('accnum2', 'currency2'), ('accnum3', 'currency3'));
```
**Actually what Querydsl** is generating is:

```
Select *
from PTE_ACC_STMNT accountStatement
where (accountStatement.ACCOUNT_NUMBER, accountStatement.currency) in (('accnum1', 'accnum2', 'accnum3'),('currency1', 'currency2', 'currency3'));
```

Does QueryDsl support such logic or not ?
Thanks in anticipation

**Comment by LukeChow** [comment]
I have same question. 
```
HashMap<Integer, Long> usedImageMap = ...
List<Tuple> list = new ArrayList<>();
//But how to initial list from usedImageMap???
queryFactory.selectFrom(qImage)
                .where(Expressions.list(qImage.index, qImage.imgId).in(list))
                ....
```

**Comment by pcsiszar** [comment]
Hi!
 I have found another sollution that is more elegant:

                QTuple qTuple = Projections.tuple(qImage.index, qImage.imgId);
                Set<Tuple> set = usedImageMap.entrySet()
                                               .stream()
                                               .map(e -> qTuple.newInstance(e.getKey(), e.getValue()))
                                               .collect(Collectors.toSet());
               queryFactory.selectFrom(qImage)
                  .where(Expressions.list(qImage.index, qImage.imgId).in(set))

**Comment by wallet-allergy** [comment]
@pcsiszar https://html-lists840.github.io/pmes1iFFPmpuot-U3SCHGkG-wLPQjfEbnzbuLUnbz_iWIAJ6aoI21uc/
