### ISSUE TITLE
 SQL Server 2013  offset and limit

### ISSUE THREAD

**Issue by RazmikMkrtchyan** [querydsl/querydsl#2258]
I have issue with using offset and limit in SQL Server 2013.
sqlQuery.offset(startIndex).limit(count);
In case of majorVersion is 13 ,SQLTemplatesRegistry returns default case(SQLServerTemplates.builder() ) and in that case offset and limit not supports.

<img width="775" alt="screen shot 2018-03-01 at 6 25 13 pm" src="https://user-images.githubusercontent.com/11534590/36849722-329daf00-1d7e-11e8-83ab-d76b8198d82e.png">

**Comment by Shredder121** [comment]
Should be fixed next release, thanks for reporting! 😅 

https://github.com/querydsl/querydsl/pull/2211/files#diff-f5c33c3f1159cb37a68f1fa1e8d73484R68

**Comment by RazmikMkrtchyan** [comment]
Thank you,and can you say when it  will be released

**Comment by Shredder121** [comment]
I've asked Timo to release this weekend, or whenever he can.
So any day now.
I also backported it to querydsl 3, so it's definitely fixed.

**Comment by RazmikMkrtchyan** [comment]
Thank you very much.
 I am using 4.1.4 .
