### ISSUE TITLE
Query fails in hibernate 5.2

### ISSUE THREAD

**Issue by cdalexndr** [querydsl/querydsl#2264]
After upgrading hibernate to 5.2.14, the following example query fails:
`select {product.*} from product...`
with the following eror:
`org.postgresql.util.PSQLException: ERROR: syntax error at or near "{"`

From my investigation, **HibernateHandler** doesn't set entity alias/type on query because it is expecting it to be of type **HibernateQuery**, but instead it's a **NativeQueryImpl** type, thus silently skipping (should log?):
```
    public void addEntity(Query query, String alias, Class<?> type) {
        if (query instanceof HibernateQuery) {
            org.hibernate.Query hibernateQuery = ((HibernateQuery) query).getHibernateQuery();
            if (hibernateQuery instanceof SQLQuery) {
                ((SQLQuery) hibernateQuery).addEntity(alias, type);
            }
        }
    }
```

Proposed solution:
Check also if `query instanceof NativeQuery`. Same for other methods inside **HibernateHandler**.

Note that hibernate SQLQuery is: 

> Deprecated (since 5.2) use NativeQuery instead.

**Comment by Shredder121** [comment]
We've not pushed for Hibernate 5.2 yet but thanks a lot for reporting. Would seem this is easy to miss.
First need to get some things going regarding Querydsl 5.

**Comment by RayN** [comment]
I managed to make queryDsl work with Sprinboot 2 and Hibernate 5.2 using holon plataform.

The code is here: https://github.com/RayN/queryDslHibernate5SpringBoot2

**Comment by heesuk-ahn** [comment]
any update? I solved it by creating a new implementation.

```
[code implementation]

public class HibernateQueryHandlerImpl implements QueryHandler {

    public static final QueryHandler QUERY_HANDLER = new HibernateQueryHandlerImpl();

    @Override
    public void addEntity(Query query, String alias, Class<?> type) {
        if (query instanceof NativeQueryImplementor) {
            ((NativeQueryImplementor) query).addEntity(alias, type);
        } else {
            throw new IllegalArgumentException(String.format("invalid Query type `%s` in HibernateHandler", query.getClass()));
        }
    }

    @Override
    public void addScalar(Query query, String alias, Class<?> type) {
        if (query instanceof NativeQueryImplementor) {
            ((NativeQueryImplementor) query).addScalar(alias);
        } else {
            throw new IllegalArgumentException(String.format("invalid Query type `%s` in HibernateHandler", query.getClass()));
        }
    }

    @Override
    public boolean createNativeQueryTyped() {
        return false;
    }

    @SuppressWarnings("unchecked")
    @Override
    public <T> CloseableIterator<T> iterate(Query query, FactoryExpression<?> projection) {
        if (query instanceof NativeQueryImplementor) {
            NativeQueryImplementor hQuery = (NativeQueryImplementor) query;
            ScrollableResults results = hQuery.scroll(ScrollMode.FORWARD_ONLY);
            CloseableIterator<T> iterator = new ScrollableResultsIterator<T>(results);
            if (projection != null) {
                iterator = new TransformingIterator<T>(iterator, projection);
            }
            return iterator;
        } else {
            Iterator<T> iterator = query.getResultList().iterator();
            if (projection != null) {
                return new TransformingIterator<T>(iterator, projection);
            } else {
                return new IteratorAdapter<T>(iterator);
            }
        }
    }

    @Override
    public boolean transform(Query query, FactoryExpression<?> projection) {
        if (query instanceof NativeQueryImplementor) {
            ResultTransformer transformer = new FactoryExpressionTransformer(projection);
            ((NativeQueryImplementor) query).setResultTransformer(transformer);
            return true;
        } else {
            return false;
        }
    }

    @Override
    public boolean wrapEntityProjections() {
        return true;
    }
}
```

```
[unit test]

public class HibernateQueryHandlerImplTest {

    private final HibernateQueryHandlerImpl hibernateQueryHandlerImpl = new HibernateQueryHandlerImpl();
    private final NativeQueryImpl nativeQuery = mock(NativeQueryImpl.class);
    private final String alias = "moAppPushAlarmSet";
    private final Class<MoAppPushAlarmSet> classType = MoAppPushAlarmSet.class;

    @Test
    public void should_AddEntity() {
        when(nativeQuery.addEntity(alias, classType)).thenReturn(nativeQuery);

        hibernateQueryHandlerImpl.addEntity(nativeQuery, alias, classType);

        verify(nativeQuery, times(1)).addEntity(alias, classType);
    }

    @Test
    public void should_ThrowException_WhenInvalidQueryType() {
        Query invalidQueryType = mock(Query.class);

        Assertions.assertThrows(IllegalArgumentException.class, () -> hibernateQueryHandlerImpl.addEntity(invalidQueryType, alias, classType));
    }

    @Test
    public void should_AddScalar() {
        when(nativeQuery.addScalar(alias)).thenReturn(nativeQuery);

        hibernateQueryHandlerImpl.addScalar(nativeQuery, alias, classType);

        verify(nativeQuery, times(1)).addScalar(alias);
    }

    @Test
    public void should_GetFalse_WhenCheckNativeQueryType() {
        assertEquals(false, hibernateQueryHandlerImpl.createNativeQueryTyped());
    }

    @Test
    public void should_GetTrue_WhenCheckWrapEntityProjections_ForHibernateQuerySyntax_ByUsingCurlyBraces() {
        assertEquals(true, hibernateQueryHandlerImpl.wrapEntityProjections());
    }

    @Test
    public void should_ReturnIteratorQueryResult() {}

    @Test
    public void should_Transform() {}
    
}
```

I have confirmed that this is working fine, but I am trying to figure out what the consequences of the `transform` and` iterate` behavior are.

If there are any other updates, I will share them.

**Comment by IdoSalomon** [comment]
> any update? I solved it by creating a new implementation.
> 
> ```
> [code implementation]
> 
> public class HibernateQueryHandlerImpl implements QueryHandler {
> 
>     public static final QueryHandler QUERY_HANDLER = new HibernateQueryHandlerImpl();
> 
>     @Override
>     public void addEntity(Query query, String alias, Class<?> type) {
>         if (query instanceof NativeQueryImplementor) {
>             ((NativeQueryImplementor) query).addEntity(alias, type);
>         } else {
>             throw new IllegalArgumentException(String.format("invalid Query type `%s` in HibernateHandler", query.getClass()));
>         }
>     }
> 
>     @Override
>     public void addScalar(Query query, String alias, Class<?> type) {
>         if (query instanceof NativeQueryImplementor) {
>             ((NativeQueryImplementor) query).addScalar(alias);
>         } else {
>             throw new IllegalArgumentException(String.format("invalid Query type `%s` in HibernateHandler", query.getClass()));
>         }
>     }
> 
>     @Override
>     public boolean createNativeQueryTyped() {
>         return false;
>     }
> 
>     @SuppressWarnings("unchecked")
>     @Override
>     public <T> CloseableIterator<T> iterate(Query query, FactoryExpression<?> projection) {
>         if (query instanceof NativeQueryImplementor) {
>             NativeQueryImplementor hQuery = (NativeQueryImplementor) query;
>             ScrollableResults results = hQuery.scroll(ScrollMode.FORWARD_ONLY);
>             CloseableIterator<T> iterator = new ScrollableResultsIterator<T>(results);
>             if (projection != null) {
>                 iterator = new TransformingIterator<T>(iterator, projection);
>             }
>             return iterator;
>         } else {
>             Iterator<T> iterator = query.getResultList().iterator();
>             if (projection != null) {
>                 return new TransformingIterator<T>(iterator, projection);
>             } else {
>                 return new IteratorAdapter<T>(iterator);
>             }
>         }
>     }
> 
>     @Override
>     public boolean transform(Query query, FactoryExpression<?> projection) {
>         if (query instanceof NativeQueryImplementor) {
>             ResultTransformer transformer = new FactoryExpressionTransformer(projection);
>             ((NativeQueryImplementor) query).setResultTransformer(transformer);
>             return true;
>         } else {
>             return false;
>         }
>     }
> 
>     @Override
>     public boolean wrapEntityProjections() {
>         return true;
>     }
> }
> ```
> 
> ```
> [unit test]
> 
> public class HibernateQueryHandlerImplTest {
> 
>     private final HibernateQueryHandlerImpl hibernateQueryHandlerImpl = new HibernateQueryHandlerImpl();
>     private final NativeQueryImpl nativeQuery = mock(NativeQueryImpl.class);
>     private final String alias = "ALIAS";
>     private final Class<FOO> classType = FOO.class;
> 
>     @Test
>     public void should_AddEntity() {
>         when(nativeQuery.addEntity(alias, classType)).thenReturn(nativeQuery);
> 
>         hibernateQueryHandlerImpl.addEntity(nativeQuery, alias, classType);
> 
>         verify(nativeQuery, times(1)).addEntity(alias, classType);
>     }
> 
>     @Test
>     public void should_ThrowException_WhenInvalidQueryType() {
>         Query invalidQueryType = mock(Query.class);
> 
>         Assertions.assertThrows(IllegalArgumentException.class, () -> hibernateQueryHandlerImpl.addEntity(invalidQueryType, alias, classType));
>     }
> 
>     @Test
>     public void should_AddScalar() {
>         when(nativeQuery.addScalar(alias)).thenReturn(nativeQuery);
> 
>         hibernateQueryHandlerImpl.addScalar(nativeQuery, alias, classType);
> 
>         verify(nativeQuery, times(1)).addScalar(alias);
>     }
> 
>     @Test
>     public void should_GetFalse_WhenCheckNativeQueryType() {
>         assertEquals(false, hibernateQueryHandlerImpl.createNativeQueryTyped());
>     }
> 
>     @Test
>     public void should_GetTrue_WhenCheckWrapEntityProjections_ForHibernateQuerySyntax_ByUsingCurlyBraces() {
>         assertEquals(true, hibernateQueryHandlerImpl.wrapEntityProjections());
>     }
> 
>     @Test
>     public void should_ReturnIteratorQueryResult() {}
> 
>     @Test
>     public void should_Transform() {}
>     
> }
> ```
> 
> ```
> [use case]
> 
> JPASQLQuery query = new JPASQLQuery<Void>(entityManager, new Configuration(sqlTemplates), HibernateQueryHandlerImpl.QUERY_HANDLER);
> ```
> 
> I have confirmed that this is working fine, but I am trying to figure out what the consequences of the `transform` and` iterate` behavior are.
> 
> If there are any other updates, I will share them.

Thanks for the update, I wasn't sure if this was still an issue.
If you'd like to open a PR then we'll be glad to look into it.

**Comment by heesuk-ahn** [comment]
@IdoSalomon ok, I will do. :D

**Comment by idosal** [comment]
Fixed in #2354. It will be featured in the next official release, which will also remove support for Hibernate 4. For now, you can try it out in 4.2.3-SNAPSHOT. I'd appreciate your feedback. Thanks!

**Comment by heesuk-ahn** [comment]
hello, salomon.

I'm glad this problem is solved.

I checked this pull request and put some code reviews on some parts.

In particular, I think the handling of throw exceptions is essential.

https://github.com/querydsl/querydsl/pull/2510

if you can still edit it, can you check the comments?

thanks!


2020년 3월 1일 (일) 오전 2:12, Ido Salomon <notifications@github.com>님이 작성:

**Comment by idosal** [comment]
@heesuk-ahn Hey, I can't see your comments. If you could add them I'll have a look and create a new PR. Thanks.

**Comment by heesuk-ahn** [comment]
hello, salomon! :)

I added the change and sent a PR.

https://github.com/querydsl/querydsl/pull/2537

thanks!

2020년 3월 4일 (수) 오후 6:52, Ido Salomon <notifications@github.com>님이 작성:

**Comment by johnktims** [comment]
Querydsl is now compatible with hibernate 5.
