### ISSUE TITLE
No serializer found for class com.querydsl.core.types.QTuple$TupleImpl

### ISSUE THREAD

**Issue by Reshma2112** [querydsl/querydsl#2268]
#I am using Querydsl in spring data jpa Application. I want to know How to select specific column using Querydsl. I joined 4 table using inner join. It contains 15-20 column . but i want to display only 7 column on grid. How to do that with Querydsl?

When I am adding select clause I am getting following exception.
**org.springframework.http.converter.HttpMessageNotWritableException: Could not write JSON:
com.fasterxml.jackson.databind.JsonMappingException**

**Account.java**
```
package com.demo.model;


import java.io.Serializable;
import java.sql.Timestamp;

import javax.persistence.CascadeType;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

@Entity
@Table(name="account")

//@JsonAutoDetect(fieldVisibility = Visibility.ANY)
public class Account implements Serializable{

	private static final long serialVersionUID = 1L;
	
	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "account_seq_generator")
	@SequenceGenerator(name="account_seq_generator", sequenceName = "account_seq")

	public Integer naccountid;
	public String namount;
	public String sacctdesc;
	public Integer naccountcpcmappingid;
	public Integer nindirectcostrate;
	public Integer nagencyid ;
	public Integer ndeptid ;
	public String sgrantnum;
	public Timestamp dstartdate;
	public Timestamp denddate;
	public String slocation;
	public String sclientacctid;
	public Integer ninvestigatorid;
	public Integer ninstid;
	public Integer ntempaccountid;
	
	
    @ManyToOne(optional = true,cascade = {CascadeType.MERGE})
    @JoinColumn(name="ndeptid",insertable =  false, updatable = false)
    public Department department;
	
    @ManyToOne(optional = true,cascade = {CascadeType.ALL})
    @JoinColumn(name="ninvestigatorid",insertable =  false, updatable = false)
    public Investigator investigator;
    
    @ManyToOne(optional = true,cascade = {CascadeType.ALL})  
    @JoinColumn(name="naccountcpcmappingid",insertable =  false, updatable = false)
    public AccountCPCMapping accountCPC;
    
    //Getter and Setter
	public Department getDepartment() {
		return department;
	}

	public void setDepartment(Department department) {
		this.department = department;
	}
	    
	public Investigator getInvestigator() {
		return investigator;
	}

	public void setInvestigator(Investigator investigator) {
		this.investigator = investigator;
	}

	public AccountCPCMapping getAccountCPC() {
		return accountCPC;
	}

	public void setAccountCPC(AccountCPCMapping accountCPC) {
		this.accountCPC = accountCPC;
	}

	public Integer getNaccountid() {
		return naccountid;
	}

	public void setNaccountid(Integer naccountid) {
		this.naccountid = naccountid;
	}

	public String getNamount() {
		return namount;
	}

	public void setNamount(String namount) {
		this.namount = namount;
	}

	public String getSacctdesc() {
		return sacctdesc;
	}

	public void setSacctdesc(String sacctdesc) {
		this.sacctdesc = sacctdesc;
	}

	public Integer getNaccountcpcmappingid() {
		return naccountcpcmappingid;
	}

	public void setNaccountcpcmappingid(Integer naccountcpcmappingid) {
		this.naccountcpcmappingid = naccountcpcmappingid;
	}

	public Integer getNindirectcostrate() {
		return nindirectcostrate;
	}

	public void setNindirectcostrate(Integer nindirectcostrate) {
		this.nindirectcostrate = nindirectcostrate;
	}

	public Integer getNagencyid() {
		return nagencyid;
	}

	public void setNagencyid(Integer nagencyid) {
		this.nagencyid = nagencyid;
	}

	public Integer getNdeptid() {
		return ndeptid;
	}

	public void setNdeptid(Integer ndeptid) {
		this.ndeptid = ndeptid;
	}

	public String getSgrantnum() {
		return sgrantnum;
	}

	public void setSgrantnum(String sgrantnum) {
		this.sgrantnum = sgrantnum;
	}

	public Timestamp getDstartdate() {
		return dstartdate;
	}

	public void setDstartdate(Timestamp dstartdate) {
		this.dstartdate = dstartdate;
	}

	public Timestamp getDenddate() {
		return denddate;
	}

	public void setDenddate(Timestamp denddate) {
		this.denddate = denddate;
	}

	public String getSlocation() {
		return slocation;
	}

	public void setSlocation(String slocation) {
		this.slocation = slocation;
	}

	public String getSclientacctid() {
		return sclientacctid;
	}

	public void setSclientacctid(String sclientacctid) {
		this.sclientacctid = sclientacctid;
	}

	public Integer getNinvestigatorid() {
		return ninvestigatorid;
	}

	public void setNinvestigatorid(Integer ninvestigatorid) {
		this.ninvestigatorid = ninvestigatorid;
	}

	public Integer getNinstid() {
		return ninstid;
	}

	public void setNinstid(Integer ninstid) {
		this.ninstid = ninstid;
	}

	public Integer getNtempaccountid() {
		return ntempaccountid;
	}

	public void setNtempaccountid(Integer ntempaccountid) {
		this.ntempaccountid = ntempaccountid;
	}
	
	//Default Constructor.
	public Account() {
		super();
	}	
}    
```

**AccountController.java**

```

@RestController
@RequestMapping("/SpaceStudy/SpaceAdmin")
public class AccountController {

	@Autowired
	AccountService accService;

	@CrossOrigin(origins = "*")
	@GetMapping("/AccountMaintenance/LoadGrid")
	public List<Account> btnSearchClick(String sclientacctid, String sacctdesc,String sinvestigatorname,String sclientdeptid) {
		return accService.btnSearchClick("1124100" ,sacctdesc, sinvestigatorname, sclientdeptid);
	}
}
```

**AccountService.java**

```
@Service
public class AccountService {
	@Autowired
	AccountRepository accRepo;

       @PersistenceContext
	EntityManager em;

        @SuppressWarnings("unchecked")
	public List<Account> btnSearchClick(String sclientacctid, String sacctdesc, String sinvestigatorname,String sclientdeptid) {

		QAccount account = QAccount.account;
		QDepartment department = QDepartment.department;
		QAccountCPCMapping accountCPCMapping = QAccountCPCMapping.accountCPCMapping;
		QInvestigator investigator = QInvestigator.investigator;

		@SuppressWarnings("rawtypes")
		JPAQuery query = new JPAQuery<>(em);
		query.select(account.sclientacctid, account.sacctdesc ,account.slocation, department.sdeptname, department.sclientdeptid,investigator.sinvestigatorname , accountCPCMapping.sccpcode)
		     .from(account).innerJoin(account.department, department).innerJoin(account.accountCPC, accountCPCMapping)
		     .innerJoin(account.investigator, investigator).where(account.ninstid.eq(60));

		if (sclientacctid != null) {
			query.where(account.ninstid.eq(60).and(account.sclientacctid.eq(sclientacctid)));

		}
		if (sacctdesc != null) {
			query.where(account.ninstid.eq(60).and(account.sacctdesc.eq(sacctdesc)));
		}
		if (sinvestigatorname != null) {
			query.where(account.ninstid.eq(60).and(investigator.sinvestigatorname.eq(sinvestigatorname)));
		}
		if (sclientdeptid != null) {
			query.where(account.ninstid.eq(60).and(department.sclientdeptid.eq(sclientdeptid)));
		}
		return query.fetch();
	}
}

```

**Comment by Shredder121** [comment]
> `@SuppressWarnings("rawtypes")`

Looks like you're using Querydsl 4, where the select comes first, and then the execution method (i.e. fetch).

**Comment by Reshma2112** [comment]
I tried with select clause also. I am getting exception
org.springframework.http.converter.HttpMessageNotWritableException: Could not write JSON:
com.fasterxml.jackson.databind.JsonMappingException

**Comment by Shredder121** [comment]
That alone doesn't tell me enough.
What are you trying to serialize, and what is the (underlying) exception?

**Comment by Reshma2112** [comment]
Using above Query I getting following exceptions
Type Exception Report

Message Could not write JSON: No serializer found for class com.querydsl.core.types.QTuple$TupleImpl and no properties discovered to create BeanSerializer (to avoid exception, disable SerializationFeature.FAIL_ON_EMPTY_BEANS); nested exception is com.fasterxml.jackson.databind.JsonMappingException: No serializer found for class com.querydsl.core.types.QTuple$TupleImpl and no properties discovered to create BeanSerializer (to avoid exception, disable SerializationFeature.FAIL_ON_EMPTY_BEANS) (through reference chain: java.util.ArrayList[0])

Description The server encountered an unexpected condition that prevented it from fulfilling the request.

Exception

org.springframework.http.converter.HttpMessageNotWritableException: Could not write JSON: No serializer found for class com.querydsl.core.types.QTuple$TupleImpl and no properties discovered to create BeanSerializer (to avoid exception, disable SerializationFeature.FAIL_ON_EMPTY_BEANS); nested exception is com.fasterxml.jackson.databind.JsonMappingException: No serializer found for class com.querydsl.core.types.QTuple$TupleImpl and no properties discovered to create BeanSerializer (to avoid exception, disable SerializationFeature.FAIL_ON_EMPTY_BEANS) (through reference chain: java.util.ArrayList[0])
	org.springframework.http.converter.json.AbstractJackson2HttpMessageConverter.writeInternal(AbstractJackson2HttpMessageConverter.java:293)
	org.springframework.http.converter.AbstractGenericHttpMessageConverter.write(AbstractGenericHttpMessageConverter.java:106)
	org.springframework.web.servlet.mvc.method.annotation.AbstractMessageConverterMethodProcessor.writeWithMessageConverters(AbstractMessageConverterMethodProcessor.java:231)
	org.springframework.web.servlet.mvc.method.annotation.RequestResponseBodyMethodProcessor.handleReturnValue(RequestResponseBodyMethodProcessor.java:174)
	org.springframework.web.method.support.HandlerMethodReturnValueHandlerComposite.handleReturnValue(HandlerMethodReturnValueHandlerComposite.java:81)
	org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:113)
	org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:827)
	org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:738)
	org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)
	org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:967)
	org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:901)
	org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
	org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:861)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:635)
	org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99)
	org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	org.springframework.web.filter.HttpPutFormContentFilter.doFilterInternal(HttpPutFormContentFilter.java:108)
	org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:81)
	org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:197)
	org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
Root Cause

com.fasterxml.jackson.databind.JsonMappingException: No serializer found for class com.querydsl.core.types.QTuple$TupleImpl and no properties discovered to create BeanSerializer (to avoid exception, disable SerializationFeature.FAIL_ON_EMPTY_BEANS) (through reference chain: java.util.ArrayList[0])
	com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:284)
	com.fasterxml.jackson.databind.SerializerProvider.mappingException(SerializerProvider.java:1110)
	com.fasterxml.jackson.databind.SerializerProvider.reportMappingProblem(SerializerProvider.java:1135)
	com.fasterxml.jackson.databind.ser.impl.UnknownSerializer.failForEmpty(UnknownSerializer.java:69)
	com.fasterxml.jackson.databind.ser.impl.UnknownSerializer.serialize(UnknownSerializer.java:32)
	com.fasterxml.jackson.databind.ser.std.CollectionSerializer.serializeContents(CollectionSerializer.java:149)
	com.fasterxml.jackson.databind.ser.std.CollectionSerializer.serialize(CollectionSerializer.java:112)
	com.fasterxml.jackson.databind.ser.std.CollectionSerializer.serialize(CollectionSerializer.java:25)
	com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:416)
	com.fasterxml.jackson.databind.ObjectWriter$Prefetch.serialize(ObjectWriter.java:1425)
	com.fasterxml.jackson.databind.ObjectWriter.writeValue(ObjectWriter.java:951)
	org.springframework.http.converter.json.AbstractJackson2HttpMessageConverter.writeInternal(AbstractJackson2HttpMessageConverter.java:286)
	org.springframework.http.converter.AbstractGenericHttpMessageConverter.write(AbstractGenericHttpMessageConverter.java:106)
	org.springframework.web.servlet.mvc.method.annotation.AbstractMessageConverterMethodProcessor.writeWithMessageConverters(AbstractMessageConverterMethodProcessor.java:231)
	org.springframework.web.servlet.mvc.method.annotation.RequestResponseBodyMethodProcessor.handleReturnValue(RequestResponseBodyMethodProcessor.java:174)
	org.springframework.web.method.support.HandlerMethodReturnValueHandlerComposite.handleReturnValue(HandlerMethodReturnValueHandlerComposite.java:81)
	org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:113)
	org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:827)
	org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:738)
	org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)
	org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:967)
	org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:901)
	org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
	org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:861)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:635)
	org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99)
	org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	org.springframework.web.filter.HttpPutFormContentFilter.doFilterInternal(HttpPutFormContentFilter.java:108)
	org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:81)
	org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:197)
	org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)

**Comment by Shredder121** [comment]
Ah, yes you shouldn't be serializing the tuple, but use it to populate an object instead.
You can also use Projections.bean if you want to limit properties set, but populate an existing class.

**Comment by Reshma2112** [comment]
what i need to changed

**Comment by noe23** [comment]
query.select(Projections.bean(Account.class, account. sacctdesc, account.naccountid, ...))

it should work for you  :)

**Comment by Reshma2112** [comment]
I tried this query.select(Projections.bean(Account.class, account.sacctdesc ,account.slocation));
I am getting error message at bean The method bean(Class<T>, Expression<?>...) in the type Projections is not applicable for the arguments (Class<Account>, StringPath, StringPath)

**Comment by Reshma2112** [comment]
Any other solution to avoid above exception

**Comment by Reshma2112** [comment]
I added all code

**Comment by Shredder121** [comment]
> I tried this query.select(Projections.bean(Account.class, account.sacctdesc ,account.slocation));
I am getting error message at bean The method bean(Class, Expression<?>...) in the type Projections is not applicable for the arguments (Class, StringPath, StringPath)

Could you also add the attempt at the query?
Also, I highly recommend you use `JPAQuery<Account>` as the type, or if you want to select the Tuple manually `JPAQuery<Tuple>`.

**Comment by Reshma2112** [comment]
JPAQuery<Tuple> query = new JPAQuery<>(em);
		query.select(Projections.bean(Account.class,account.sclientacctid, account.sacctdesc ,account.slocation, department.sdeptname,
				                                    department.sclientdeptid,investigator.sinvestigatorname , accountCPCMapping.sccpcode))
		     .from(account)
		     .innerJoin(account.department, department)
		     .innerJoin(account.accountCPC, accountCPCMapping)
		     .innerJoin(account.investigator, investigator)
		     .where(account.ninstid.eq(60));

error at bean
The method bean(Class<T>, Expression<?>...) in the type Projections is not applicable for the arguments (Class<Account>, StringPath, StringPath, StringPath, StringPath, StringPath, StringPath, StringPath)

**Comment by Reshma2112** [comment]
In above code i am importing wrong projections. I solved above error.  But I am not getting expected result . In current output only printing account model value(account.sclientacctid, account.sacctdesc ,account.slocation). other value printing as null. what I need to changed for getting expected result.

current Result
```
[
    {
        "naccountid": null,
        "namount": null,
        "sacctdesc": "SRIRAM",
        "naccountcpcmappingid": null,
        "nindirectcostrate": null,
        "nagencyid": null,
        "ndeptid": null,
        "sgrantnum": null,
        "dstartdate": null,
        "denddate": null,
        "slocation": "ON",
        "sclientacctid": "1124100",
        "ninvestigatorid": null,
        "ninstid": null,
        "ntempaccountid": null,
        "department": null,
        "investigator": null,
        "accountCPC": null
    }
]
```

Expecting Result like this
```

[
    {
        "sacctdesc": "SRIRAM",
        "slocation": "ON",
        "sclientacctid": "1124100",
        "sdeptname" : "abc",
        "sclientdeptid" :"12345",
        "sinvestigatorname": "abcd",
        "sccpcode" : "xyz"

    }
]

```

**Comment by Shredder121** [comment]
That's an object mapper problem, are you using Jackson?
It has `@JsonInclude(NON_NULL)` which would filter the output like you expect.
But, now that the query is fixed I'll close this, I hope you can find the solution for your mapper output.

**Comment by Reshma2112** [comment]
ok Thank you so much
