### ISSUE TITLE
Getting random ClassCastException in a Tomcat Container

### ISSUE THREAD

**Issue by sailingcat** [querydsl/querydsl#2271]
Hi,

We have a Web application deployed on a Tomcat Container.
The production server configuration is 

- Tomcat 7
- Java 7
- QueryDsl 3.6.5

We randomly have this exception (not able to reproduce it on our developpement machine).

```
java.lang.ClassCastException: com.mysema.query.types.path.StringPath cannot be cast to com.mysema.query.types.path.EntityPathBase
at com.mysema.query.alias.Alias.$(Alias.java:162)
```

I have checked the code and each time we have such an exception, the $() call that failed was the first one made by the calling request.

I am wondering if this could be due to the fact that Alias uses Threadlocal variables and that the current value was not reset correctly.

Maybe you could help.

I am available if you need any more information.

Thank you.

**Comment by Shredder121** [comment]
Do you have Querydsl in the lib/ directory of tomcat?
Just wondering.

I suppose we could reset the threadlocal on startup/class load

**Comment by sailingcat** [comment]
No our libs are in the WEB-INF/lib folder of our application.

Maybe if i called Alias.resetAlias in a servlet filter, this would ensure that the threadlocal variables are properly cleaned up

**Comment by Shredder121** [comment]
Yes that would be best, just in case.
Still not quite sure how an old class can stick around from a different classloader, except when you redeploy but not restart, or something like that.
Could you try that?

**Comment by sailingcat** [comment]
Not sure i understand what you mean. 
What do you want me to try ?
The problem seems lies here 
EntityPathBase<D> rv = aliasFactory.<EntityPathBase<D>> getCurrentAndReset();

Somehow the value of getCurrentAndReset was not properly reset ...

That is why i suspect the problem here lies with the fact that Tomcat reuses threads, but i'm really not sure. 
Also this only happens on the production environment at a mean rate of about twice every day (but sometimes 10 times a day some days none). We have on average 500+ sessions at anytime with 10 hits / second (but probably less than 1 / sec using a request that relies on querydsl).

**Comment by Shredder121** [comment]
So, if I understand you correctly, this exception occurs with no pattern? While the web app is running, afresh? (so not after having redeployed, for example)
Nothing special?

`getCurrentAndReset` does in fact reset the ThreadLocal though... (setting the value to `null`)

**Comment by sailingcat** [comment]
Yes it happens while the app is running for a few days without any restart. I have not seen any pattern apart from the fact that it is the first call to $() made by the request.

**Comment by sailingcat** [comment]
What i'll do is update the production code with a little fix that calls
Alias.resetAlias();
before treating any request.

The next production release should be scheduled next week. I will keep you up to date if i don't get any more of these after a few days.

**Comment by Shredder121** [comment]
Can you share the query where the exception occurs?
Just for reference?

**Comment by sailingcat** [comment]
In the case of the given exception it is this query (but there are others queries concerned on other entities as well) :

// in abstract class proxies are declared
public static final ElementConsulte elementConsulte = alias(ElementConsulte.class);	

//  query does not even execute
JPAQuery query = new JPAQuery(em).from($(viewedElements)).where(($(viewedElements.geClient()).eq(client)));	
		query.where($(viewedElements.getContact().getId()).eq(idContact));	
		return query.singleResult($(viewedElements));

**Comment by Shredder121** [comment]
Is it okay if this issue will be closed, until you find a way to replicate it, either via a project we can run, or something similar?

**Comment by sailingcat** [comment]
Well i don't mind. This could be reopened later if someone has the same issue.
Anyway, this seems to be fixed in our project by calling `Alias.resetAlias();` before any query is processed on the current thread.

I don't see how i can provide a way to replicate it. I have tried to replicate it on my own but cannot seem to be able to do it on my local environment. This bug used to happen up to a few times a day (some days never). Since the fix was delivered on our latest production build (about 20 days ago), the problem never occured again.

**Comment by Shredder121** [comment]
Yes, agreed.
Very strange, if there were multiple class loaders I can see an issue arising, but this is for unrelated paths.
Highly interested if this ever occurs again.
