### ISSUE TITLE
Eclipse compile time code generation with QueryDSL 4.1.4 

### ISSUE THREAD

**Issue by spk23** [querydsl/querydsl#2274]
Is there any support for eclipse compile time code generation with queryDSL 4.1.4, I could successfully generate QClasses with query dsl 3.3.2 but I am not able to generate QClass code with 4.1.4. 
P.S. I am not using maven.

**Comment by Shredder121** [comment]
If you use javac directly, and have the `apt` classifier jar (`querydsl-jpa:{version}:apt`) on the classpath the annotation processors should be picked up as-is.
You can also use the `querydsl-apt:{version}:{backend}` classifier jars.

There are quite a few different classifiers, which you can manually download.
https://search.maven.org/#search%7Cga%7C1%7Cg%3A%22com.querydsl%22

P.S. I recommend you use some kind of build tool, even if it's just to manage dependencies.

**Comment by Shredder121** [comment]
So, to be sure.
[This release](https://www.eclipse.org/eclipse/news/4.7.3a/) breaks annotation processing?
https://projects.eclipse.org/projects/eclipse/releases/4.7.3a

Can anyone get me a diff between those versions? (4.7.3 to 4.7.3a)
Want to see why they're throwing an exception with that message. The message itself doesn't tell me much.

**Comment by ArloL** [comment]
I believe so. I will try to download an older oxygen release tomorrow. Not sure whether that will work though.

The current TypesImpl can be found here: https://git.eclipse.org/c/jdt/eclipse.jdt.core.git/tree/org.eclipse.jdt.compiler.apt/src/org/eclipse/jdt/internal/compiler/apt/model/TypesImpl.java?h=master

If I am seeing this correctly there was a validation step added with:

https://git.eclipse.org/c/jdt/eclipse.jdt.core.git/commit/org.eclipse.jdt.compiler.apt/src/org/eclipse/jdt/internal/compiler/apt/model/TypesImpl.java?id=0574db9360ba34dc60ca55c743cc86eb6aa06d51

I will try and see whether I can get a Eclipse PDE up and running tomorrow and set a breakpoint for more information.

**Comment by ArloL** [comment]
Could the problem be that [JPAConfiguration.java#L116](https://github.com/querydsl/querydsl/blob/8f96f416270d0353f90a6551547906f3c217833a/querydsl-apt/src/main/java/com/querydsl/apt/jpa/JPAConfiguration.java#L116) is being called for an ExecutableElement? Does it even make sense to try and call `erasure()` on `ExecutableElement.asType()?

**Comment by ArloL** [comment]
I confirm that the problem is that erasure() is being called with an ExecutableTypeImpl. Is this a problem with ecj or with querydsl? I don't have a lot of experience with annotation processing. Should erasure maybe be called on the return type of the ExecutableElement?

**Comment by ArloL** [comment]
I have just created an Eclipse Neon environment and checked what erasure returns for ExecutableTypeImpl:

![image](https://user-images.githubusercontent.com/195367/38984406-e1aedfd2-43c6-11e8-80f5-fa0b480822fc.png)

I believe something like this would work:

````
TypeMirror erasure;
if (element instanceof ExecutableElement) {
  erasure = ((ExecutableElement) element).getReturnType();
} else {
  erasure = types.erasure(element.asType());
}
````

**Comment by ArloL** [comment]
I have included my "fix" and could successfully execute `mvn test`.
