### ISSUE TITLE
querydsl-maven-plugin: collation issue after upgrading jdbc driver

### ISSUE THREAD

**Issue by mpschaeuble** [querydsl/querydsl#2277]
Generating entities from a sql server database with querydsl-maven-plugin worked perfectly fine using the old jdbc driver sqljdbc4 in version 4.0.2206.100. After upgrading to mssql-jdbc 6.4.0, I get the following exception when generating entities:
`
[ERROR] Failed to execute goal com.querydsl:querydsl-maven-plugin:4.1.4:export (default-cli) on project mercator: Cannot resolve the collation conflict between "Latin1_General_CI_AS" and "SQL_Latin1_General_CP1_CI_AS" in the equal to operation. -> [Help 1]
`
All my tables and columns are using the collation "SQL_Latin1_General_CP1_CI_AS". Same issue also happened with a different database that uses the collation "SQL_Latin1_General_CP1_CI_AS". When a datbase with collation "Latin1_General_CI_AS" is used, everything works fine.

Not sure if this is really a problem in the querydsl-maven-plugin.

**Comment by Shredder121** [comment]
What version of sql server?
And maybe some steps to reproduce, so I can look into it?

**Comment by mpschaeuble** [comment]
I'm using SQL Server 2016 (13.0.1742.0) with a server default collation "Latin1_General_CI_AS". I was able to reproduce the issue with a new database with collation "SQL_Latin1_General_CP1_CI_AS" and a single table with one column of any type.
