### ISSUE TITLE
Consider replacing CGLIB with ByteBuddy

### ISSUE THREAD

**Issue by TuomasKiviaho** [querydsl/querydsl#2279]
I ran again to the java.lang.NoClassDefFoundError: net/sf/cglib/proxy/Callback issue that is caused by me not taking care of my classpath properly when using aliases. 

Could it be possible to replace the enhancer with ByteBuddy which doesn't bring any proxy classes to the final bytecode like both JavaAssist and CGLIB do. This how Hibernate for instance has been lately solving similar issues around their bytecode enhancement.

**Comment by Shredder121** [comment]
Is there anything we can do to combat this? Or would we need to migrate?

**Comment by TuomasKiviaho** [comment]
This merely an annoyance unless CGLIB becomes again incompatible with latest jdk updates as it has in the past been. It's quite easy to forget to put CGLIB as a dependency because it's an optional one. With ByteBuddy, there is no such need because it doesn't leave any track of itself.

**Comment by jwgmeligmeyling** [comment]
The core team is unlikely to pick this up any time soon. PR's will be accepted though.

**Comment by persapiens** [comment]
Just to inform about [cglib issue with JDK 17+](https://github.com/cglib/cglib/issues/191)
