### ISSUE TITLE
QueryDsl problem (group by, aggregation with projection)

### ISSUE THREAD

**Issue by jess-park** [querydsl/querydsl#2288]
**1. This is what i want to do with SQL**

SELECT mp.prog_sq AS prog_sq
       ,mp.prog_name AS prog_name
       ,STRING_AGG(mci.item_key,', ') AS item_key
       ,STRING_AGG(mci.item_name,', ') AS item_name
       ,mp.approver AS approver
FROM mx_prog mp
JOIN mx_clctr_item mci ON mci.prog_sq = mp.prog_sq
JOIN mx_user mu ON mp.approver = mu.user_sq
GROUP BY mp.prog_sq
WHERE 1=1

**2. This is what i did with querydsl** 

JPQLQuery<Object> query = from(collectProgram, collectItem);
query.where(collectProgram.progSq.eq(collectItem.collectItemId.progSq));
query.groupBy(collectProgram.progSq);
		
		List<CollectProgramSearchListDto> collectProgramSearchList = query.select(Projections.constructor(CollectProgramSearchListDto.class, 
		collectProgram.progName,
		collectItem.itemName,
		collectProgram.progDesc)).fetch();

**3. This is what i am wondering** 
How i can get "string aggregation" with collectItem.itemName after groupBy.
Actually i can get count after groupby with collectItem.count(); 
but....is there any way get string aggregation after groupby??

**4. If that is not possible** 
Could you give me some example of using "Group" instance after group by with mutiple result column.
I don't know how to handle this "com.querydsl.core.group.Group" data.

Map<Integer, Group> results = query.from(post, comment)
    .where(comment.post.id.eq(post.id))
    .transform(groupBy(post.id).as(post.name, set(comment.id)));

thanks in advance.

**Comment by ravenblackdusk** [comment]
I'd like to know how to use STRING_AGG in querydsl as well

**Comment by ravenblackdusk** [comment]
this is how you can use `STRING_AGG`:
`stringTemplate("STRING_AGG({0}, ',')", mci.itemKey)`

**Comment by jwgmeligmeyling** [comment]
Or: `SQLExpressions.groupconcat(mci.itemKey, ",")`.

However, either solutions only work for `querydsl-sql` and not `querydsl-jpa` because `STRING_AGG` or `GROUP_CONCAT` are not defined functions in JPQL.

**Comment by giovanni-nabil** [comment]
@jwgmeligmeyling How can it be done in QueryDSL-JPA ? I'm also trying to achieve the same. do I have to use `.transform()` or something similar?
