### ISSUE TITLE
JPA native sql query with custom db type results in exception

### ISSUE THREAD

**Issue by cdalexndr** [querydsl/querydsl#2289]
Querydsl 4.2.1
Using a postgres custom db type with a `com.querydsl.jpa.sql.JPASQLQuery` results in the following exception: `org.hibernate.MappingException: No Dialect mapping for JDBC type: 1111`.

From my investigation, the `com.querydsl.jpa.HibernateHandler` when adds the scalar, it doesn't register its type, thus hibernate has to autodetect the type and fails. Note that the `type` variable is never used:
```
 public void addScalar(Query query, String alias, Class<?> type) {
        if (query instanceof HibernateQuery) {
            org.hibernate.Query hibernateQuery = ((HibernateQuery) query).getHibernateQuery();
            if (hibernateQuery instanceof SQLQuery) {
                ((SQLQuery) hibernateQuery).addScalar(alias);
            }
        }
    }
```
The hibernate query also has a method to register the scalar with a custom hibernate type:
`org.hibernate.SQLQuery addScalar(String columnAlias, org.hibernate.type.Type type)`

A nice feature will be to automatically make a bridge between the `com.querydsl.sql.types.Type` registered in Querydsl configuration and an on-the-fly new hibernate type that uses querydsl custom type.

**Comment by cdalexndr** [comment]
An alternative quick fix is to check if there is a hibernate type already registered and use it:
```
entityManager
        .getEntityManagerFactory()
        .unwrap( org.hibernate.SessionFactory.class )
        .getTypeHelper()
        .basic( type )
```
For this to work, the `HibernateHandler` must have access to entity manager instance;

**Comment by shivamtiwari2009** [comment]
I am getting similar issue, how to fix this?

**Comment by bigbang4u2** [comment]
In order to support JSONB, I modified above code to 

```
import com.fasterxml.jackson.databind.JsonNode;
import com.querydsl.jpa.HibernateHandler;
import com.vladmihalcea.hibernate.type.json.JsonNodeBinaryType;
import javax.persistence.EntityManager;
import javax.persistence.Query;
import org.hibernate.SessionFactory;
import org.hibernate.query.NativeQuery;
import org.hibernate.type.BasicType;

public void addScalar(Query query, String alias, Class<?> type) {
    final BasicType basic =
        entityManager
            .getEntityManagerFactory()
            .unwrap(SessionFactory.class)
            .getTypeHelper()
            .basic(type);
    final NativeQuery unwrap = query.unwrap(NativeQuery.class);
    if (type.equals(JsonNode.class)) {
      unwrap.addScalar(alias, JsonNodeBinaryType.INSTANCE);
    } else {
      unwrap.addScalar(alias, basic);
    }
  }
```
