### ISSUE TITLE
Struggling with syntax on how to bind for a sub-list field with QList

### ISSUE THREAD

**Issue by gt-tech** [querydsl/querydsl#2293]
I have a class like

```
@com.querydsl.core.annotations.QueryEntity
public class User  implements Serializable {
  private static final long serialVersionUID = 1L;

  @JsonProperty("id")
  private String id = null;

  @JsonProperty("userName")
  private String userName = null;

  @JsonProperty("emails")
  @Valid
  private List<Email> emails = null;
}
```

After processing by Maven APT plugin, following Q type classes are generated, trimmed down to only relevant piece while pasting code in issue:

@Generated("com.querydsl.codegen.EntitySerializer")
public class QUser extends EntityPathBase<User> {

    private static final long serialVersionUID = -668927352L;

    private static final PathInits INITS = PathInits.DIRECT2;

    public static final QUser user = new QUser("user");

    // custom
    public final ext.java.util.QList emails = new ext.java.util.QList(forProperty("emails"));

    public final StringPath id = createString("id");

    public final ext.java.util.QList emails = new ext.java.util.QList(forProperty("emails"));

}

And then the QEmail generated class -

```
@Generated("com.querydsl.codegen.EntitySerializer")
public class QEmail extends EntityPathBase<Email> {

    private static final long serialVersionUID = 723129471L;

    public static final QEmail email = new QEmail("email");

    public final BooleanPath _default = createBoolean("_default");

    public final BooleanPath default$ = createBoolean("default");

    public final StringPath label = createString("label");

    public final StringPath value = createString("value");

    public final BooleanPath verified = createBoolean("verified");

    public QEmail(String variable) {
        super(Email.class, forVariable(variable));
    }

    public QEmail(Path<? extends Email> path) {
        super(path.getType(), path.getMetadata());
    }

    public QEmail(PathMetadata metadata) {
        super(Email.class, metadata);
    }

}
```

I am unsure how I can customize bindings (I am using Spring Data QueryDSL support)

I can use - QUser.userName for username but if I want to create a custom binding on QUser.emails.value???

A related question - unclear on when does ListPath gets used vs when does QList gets used in code generation. We do not use @QueryDelegate anywhere.

**Comment by jwgmeligmeyling** [comment]
For example `QUser.emails.any()`.
