### ISSUE TITLE
Deep projection

### ISSUE THREAD

**Issue by devcken** [querydsl/querydsl#2295]
I have three tables. The relationship between A and B, B and C is one to many. A -> B, B -> C

As a result, I want the JSON format as follows:

```javascript
[
    {
        id: 1,
        ...,
        bs: [
            {
                id: 1,
                ...,
                cs: [
                    {
                        id: 1,
                        ...
                    }
                ]
            }
        ]
    }
]
```

So, I implemented a query as follows:

```java
final SQLQueryFactory queryFactory;

public List<APojo> find() {
  return this.queryFactory
    .from(A)
    ...
    .leftJoin(A...., B)
    .leftJoin(B...., C)
    .transform(
      groupBy(A.id)
        .list(
          bean(
            APojo.class,
            ...,
            set(
              bean(
                BPojo.class,
                B.someProperty,
                set(
                  bean(CPojo.class, C.all())
                ).as("cs")
          )
        )
      )
    )
}
```

The problem is not the query. The query is executed well. But a exception for projection is being occured:

```
...
Caused by: java.lang.IllegalArgumentException: argument type mismatch
...
```

I debugged the exception and found the problem. It is occured on `newInstance(Object... a)#QBean`:

```java
public T newInstance(Object... a) {
...
        } else {
            for (int i = 0; i < a.length; i++) {
                Object value = a[i];
                if (value != null) {
                    Method setter = setters.get(i);
                    if (setter != null) {
                        setter.invoke(rv, value); // <-------
                    }
                }
            }
        }
...
```

I expected that a instance of `Set<C>` is generated, but just a instance of C is actually generated. Then, when `setter.invoke` is invoked, the exception is occured. I don't understand this situation.

How can I project nested set or list?

**Comment by Shredder121** [comment]
Is this at the first, or the second set?

**Comment by devcken** [comment]
@Shredder121 the second set for C

**Comment by daniel-pittman** [comment]
@devcken Did you ever find a resolution to your issue? I am encountering the same problem with a nested Set projection. Thanks!

**Comment by devcken** [comment]
> @devcken Did you ever find a resolution to your issue? I am encountering the same problem with a nested Set projection. Thanks!

@daniel-pittman Unfortunately it is impossible. Timowest said it is a unavoidable characteristic on ORM. I think maybe it is related to lazy loading. This is all I know.

**Comment by corporalaris** [comment]
I realize this is pretty much confirmed but I wanted to note I can easily get this to work with 2 layer projection but the moment I uncomment the 3rd layer I get this exception. It sure would be nice to have this all buttoned up. Workarounds for now! :)
