### ISSUE TITLE
README.md - Tutorials links not working

### ISSUE THREAD

**Issue by Necropaw** [querydsl/querydsl#2299]
The links in the README.md to the tutorials are not working.
Instead of a tutorial a HTTP error code 404 is returned.

Examples of the not working links from the README.md:
* [Querying JPA](http://www.querydsl.com/static/querydsl/latest/reference/html/ch02.html#jpa_integration)
* [Querying SQL](http://www.querydsl.com/static/querydsl/latest/reference/html/ch02s03.html)
* [Querying Mongodb](http://www.querydsl.com/static/querydsl/latest/reference/html/ch02s07.html)
* [Querying Lucene](http://www.querydsl.com/static/querydsl/latest/reference/html/ch02s05.html)
* [Querying Collections](http://www.querydsl.com/static/querydsl/latest/reference/html/ch02s08.html)
* [Querydsl Spatial](http://www.querydsl.com/static/querydsl/latest/reference/html/ch02s04.html)
* [Querying JDO](http://www.querydsl.com/static/querydsl/latest/reference/html/ch02s02.html)

**Comment by Shredder121** [comment]
Oh. Okay.
@timowest was there anything lost in the previous outage?

**Comment by Shredder121** [comment]
I reinstated a link for `latest`. Turns out that was all that was needed.
Thanks for reporting!
