### ISSUE TITLE
Escape '!' generated by LIKE clauses in JPA templates prevents database indexes from being used

### ISSUE THREAD

**Issue by Stormsurfer36** [querydsl/querydsl#2300]
We've run into a situation using querydsl jpa templates that is causing indexes on columns we are searching against to be ignored.

The generated SQL by the QueryDSL JPA template is adding a ESCAPE '!' to the end of our like clauses

`WHERE (retailcust0_.CUSTOMER_LAST_NAME LIKE ? ESCAPE '!') `

In the scenario above there is an index on CUSTOMER_LAST_NAME that due to the escape '!' is being ignored. This renders the querydsl generated query slow and basically unusable when going over millions of rows.

This appears to have been added due to [https://github.com/querydsl/querydsl/issues/87](https://github.com/querydsl/querydsl/issues/87) which seems valid, but ideally we could turn this on/off.

Can we get a way to flag the generation of ESCAPE '!' on/off for LIKE statements for querydsl jpa templates?

**Comment by mattwmj** [comment]
We run into this, too.
There should be a configuable property to turn on/off escape.

**Comment by jwgmeligmeyling** [comment]
It is configurable, through the means of providing a different implementation of `JPQLTemplates`:

```java
public class MyTemplates extends JPQLTemplates {

    public MyTemplates() {
        add(Ops.LIKE, "{0} like {1}");
    }

}
```

Then use it as follows: `new JPAQuery(entityManager, new MyTemplates())`.

**Comment by piscoyu** [comment]
If you use ‘QuerydslPredicateExecutor’, how to configure it

**Comment by jwgmeligmeyling** [comment]
I don’t know, thats not a Querydsl class. You would have to ask the folks at Spring Data
