### ISSUE TITLE
ClassCastException with comparables when aliasing

### ISSUE THREAD

**Issue by TuomasKiviaho** [querydsl/querydsl#2301]
I'm getting...

```
Caused by: java.lang.ClassCastException: com.querydsl.core.types.dsl.ComparableEntityPath cannot be cast to com.querydsl.core.types.dsl.EntityPathBase
	at com.querydsl.core.alias.Alias.$(Alias.java:308)
```

<details>
  <summary>Alias.$</summary>

``` java
    /**
     * Convert the given alias to an expression
     *
     * @param arg alias
     * @param <D>
     * @return expression
     */
    public static <D extends Comparable<?>> ComparablePath<D> $(D arg) {
        return Alias.getPath(arg);
    }

    /**
     * Convert the given alias to an expression
     *
     * @param arg alias
     * @param <D>
     * @return expression
     */
    @SuppressWarnings("unchecked")
    @Nullable
    public static <D> EntityPathBase<D> $(D arg) {
        EntityPathBase<D> rv = aliasFactory.getCurrentAndReset();
        if (rv != null) {
            return rv;
        } else if (arg instanceof EntityPath<?>) {
            return (EntityPathBase<D>) arg; //NOSONAR
        } else if (arg instanceof ManagedObject) {
            return (EntityPathBase<D>) ((ManagedObject) arg).__mappedPath();
        } else {
            return null;
        }
    }
```

</details>

... when using `Alias.$(Alias.alias((Class<?>)subClassOfComparable))` .  

<details>
  <summary>ComparableEntityPath</summary>

``` java
    @SuppressWarnings("unchecked")
    @Override
    public <T> Path<T> createEntityPath(Class<T> type, PathMetadata metadata) {
        if (Comparable.class.isAssignableFrom(type)) {
            return Expressions.comparableEntityPath((Class) type, metadata);
        } else {
            return new EntityPathBase<T>(type, metadata);
        }
    }

```

</details>

Reason is that the `ComparableEntityPath` does not extend `EntityPathBase` which is the type that one of the dollar methods is expecting.

<details>
  <summary>DefaultPathFactory</summary>

``` java
    @SuppressWarnings("unchecked")
    @Override
    public <T> Path<T> createEntityPath(Class<T> type, PathMetadata metadata) {
        if (Comparable.class.isAssignableFrom(type)) {
            return Expressions.comparableEntityPath((Class) type, metadata);
        } else {
            return new EntityPathBase<T>(type, metadata);
        }
    }
```

</details>

The origin of `ComparableEntityPath` is in `DefaultPathFactory` and it has been so for quite a long time so the problem has been lurking around at least as long since usually people tend to enforce the comparability so that the right dollar method is chosen.

I propose that dollar methods of `Alias` ditch the `EntityPathBase` in favor of `EntityPath` by using the `@WithBridgeMethods` to preserve backwards compatibility. The problem is that `EntityPathBase` is extended from BeanPath that has couple of public methods namely...

- `public <U extends BeanPath<? extends T>> U as(Class<U> clazz)`
- `public <B extends T> BooleanExpression instanceOf(Class<B> type)`
- `public BooleanExpression instanceOfAny(Class... types)`

... that people may be using. These should be introduced as `default` methods into `EntityPath` so that this change doesn't cause binary incompatibilities.

This is not a big issue and in most cases it's easily worked around as it is  but it was quite a hard one to spot so that's why I reported it although the severity is minimal compared to the amount of work/risk involved in fixing it.

**Comment by jwgmeligmeyling** [comment]
The suggested solution won't work, as `EntityPath` also misses the methods provied through `BeanPath` and `SimpleExpression`, like `.eq(...)`. This would cause a major inconvience for users.

The proper fix is to address the inheritance hierarchy. Maybe we can move a couple of methods up in the hierarchy. Alternatively, we could convert some classes to interfaces so that `ComparableEntityPath` can extend both `EntityPathBase` and `ComparablePath`.

I think `ComparableExpression` and `ComparablePath` should be interfaces, then the implementation of `ComparableExpression` and `ComparablePath` should move to `ComparableExpressionBase` and `ComparablePathBase`. `ComparableEntityPath` can then extend `EntityPathBase` and implement `ComparablePath` at the same time.

Its a change I am willing to make, however, due to the breaking nature we would need something of a vote for that.
