### ISSUE TITLE
com.querydsl.core.types.dsl.ComparableExpression.lt is Final

### ISSUE THREAD

**Issue by cbriarnold** [querydsl/querydsl#2302]
I assume this was not intentional, since com.querydsl.core.types.dsl.ComparableExpression.gt is not Final. But when I was mocking this for some unit testing, the finality of the 'lt' method made it so that it was not mockable.

**Comment by jwgmeligmeyling** [comment]
Duplicate of https://github.com/querydsl/querydsl/issues/2564
