### ISSUE TITLE
Predicate throws IllegalArgumentException

### ISSUE THREAD

**Issue by linyongfu2013** [querydsl/querydsl#2311]
springboot version: 1.5.9
querydsl version: 4.1.4

service query code:
```
    public List<Timeline> searchAllByUserId(long userId, int pageIndex, int pageSize) {
        QTimeline qTimeline = QTimeline.timeline;
        Predicate predicate = qTimeline.userId.longValue().eq(userId);
        PageRequest page = new PageRequest(pageIndex, pageSize, new Sort(Sort.Direction.DESC, "createAt"));

        return timelineRepository.findAllByUserId(predicate, page);
    }
```

exception:
```
org.springframework.dao.InvalidDataAccessApiUsageException: Parameter value [timeline.userId = 2] did not match expected type [java.lang.Long (n/a)]; nested exception is java.lang.IllegalArgumentException: Parameter value [timeline.userId = 2] did not match expected type [java.lang.Long (n/a)]

Caused by: java.lang.IllegalArgumentException: Parameter value [timeline.userId = 2] did not match expected type [java.lang.Long (n/a)]
	at org.hibernate.jpa.spi.BaseQueryImpl.validateBinding(BaseQueryImpl.java:897)
	at org.hibernate.jpa.internal.QueryImpl.access$000(QueryImpl.java:61)
	at org.hibernate.jpa.internal.QueryImpl$ParameterRegistrationImpl.bindValue(QueryImpl.java:235)
	at org.hibernate.jpa.spi.BaseQueryImpl.setParameter(BaseQueryImpl.java:638)
```

anyone could give me some tips ?

**Comment by linyongfu2013** [comment]
so disappointed no one give a damn to new issue...
@meatballhat @rocketraman @johnktims @ponzao @msiedlarek

**Comment by tiarebalbi** [comment]
@linyongfu2013 Why don't you help to look after this issue? This is an open source project, so everyone can help with it.

**Comment by Shredder121** [comment]
Sorry that we don't answer within 24 hours on all new issues.
You named your method incorrectly.

**Comment by Shredder121** [comment]
Or you can give the userId to the method like you indicate in the method name. Your choice.

**Comment by linyongfu2013** [comment]
@Shredder121 which method incorrect ? and what do mean by 【give the userId to the method】?

**Comment by Shredder121** [comment]
findAll*ByUserId*

Spring data will generate a `select ... where user.id = ?` query.
So you just pass in the id, not a predicate.

**Comment by linyongfu2013** [comment]
@Shredder121  thank you ! I just figure it out ! no need to add the suffix to the method name in the Repository interface.
