### ISSUE TITLE
can add new interface?

### ISSUE THREAD

**Issue by yhydev** [querydsl/querydsl#2316]
i english is not good,hope you can understantd.
i have a idea, look down code.

`
QBean qbean = Projections.bean(
member.id,
member.name
);

CustomBean customBean = jpaqueryfactory.select(qbean ).from(member).fetchOne();

customBean.get(member.id);

`

**Comment by jwgmeligmeyling** [comment]
This won't work, because `member.id` might not be in the query result. And there might be several expressions with the exact same outcome as `member.id`.

Instead, use `QTuple`:


```java
QTuple tuple= jpaqueryfactory.select(Projections.tuple(member.id)).from(member).fetchOne()
Integer id = tulpe.get(member.id);
```
