### ISSUE TITLE
using any() in join

### ISSUE THREAD

**Issue by ghost** [querydsl/querydsl#2317]
I'm trying to achieve something like this:
```
JPQLQuery<Entity> query = new JPAQuery<>(entityManager);
    query.select(qEntity).distinct().from(qEntity);
    query.join(qEntity.attra.attrSetEager.any().attrb.attrSetLazy).fetchJoin();
```
But it generates this:
> select distinct entity from com.a.b.entity.Entity entity inner join fetch any(entity.attra.attrSetEager).attrb.attrSetLazy

With this error:
> unexpected token: any
Is it possible to use any() keyword in a join clause ?

**Comment by jwgmeligmeyling** [comment]
No its not (as per JPA specification). It is however allowed in the ON clause of a join.
