### ISSUE TITLE
Querydsl Projection.bean not finding setters when usin fluent pattern

### ISSUE THREAD

**Issue by areisyus** [querydsl/querydsl#2323]
We use fluent setters pattern in our Entities and DTOs so trying to use Projections.bean I found that querydsl cant find setters for QBean.

I think it is convenient to support fluent setters as some good programming approaches and patterns like builder pattern take advantages on it.

If I can find some time I'll also try to submit a pull request if it is welcome... 

What you guys think about it?

**Comment by MickeyWZC** [comment]
### the key code:

> java.beans.Introspector

`if (void.class.equals(resultType) && name.startsWith(SET_PREFIX))`


--------------

> java.beans.PropertyDescriptor

`if (!writeMethod.getReturnType().equals(void.class)) {
                    writeMethod = null;
}`
