### ISSUE TITLE
Left Join with condition on right table not working

### ISSUE THREAD

**Issue by alicebobecila** [querydsl/querydsl#2328]
I have two tables - `user` and `booking`. Each user may have many bookings (one-to-many relationship). 

    user:                          booking:
    
        id | name    |               id | country    | user_id | price   |
        -------------|               ------------------------------------|
         1 | Alice   |                1 | Italy      | 1       | 2000    |
         2 | Bob     |                2 | France     | 1       | 2500    |
                                      3 | Spain      | 1       | 3000    |

I want to select all users and all bookings where booking's price is greater than 2000 using `Query DSL`. If a user doesn't have any bookings or bookings don't match the condition I still want to select this user. 

First, let's have a look at how it would look like using a simple SQL left join query:

    SELECT u.*, b.* FROM user u LEFT JOIN booking b ON u.id = b.user_id AND b.price > 2000

The above query should provide the following result:

        id | name    | id    | country    | user_id | price   |
        -------------|----------------------------------------|
         1 | Alice   | 2     | France     | 1       | 2500    |
         1 | Alice   | 3     | Spain      | 1       | 3000    |
         2 | Bob     | null  | null       | null    | null    |
      

Now I want to do it using `JPA` with `Query DSL`

**JPA-related stuff:**

    @Entity
    public class User {
    
        @Id
        private Long id;
        private String name;
    
        @OneToMany(cascade = ALL, fetch = EAGER, orphanRemoval = true, mappedBy = "user")
        private List<Booking> bookings;
    
        // getters and setters
    }

    @Entity
    public class Booking {
    
        @Id
        private Long id;
        private String name;
        private Integer price;
    
        @ManyToOne(fetch = LAZY)
        @JoinColumn(name = "user_id")
        private User user;
    
        // getters and setters
    }

**Query DSL:**

    public List<User> getUsersAndBookings() {
        QUser user = QUser.user;
        QBooking booking = QBooking.booking;
    
        JPAQuery<User> jpaQuery = new JPAQuery(entityManager);

        List<User> result = jpaQuery.from(user).leftJoin(user.bookings, booking).on(booking.price.gt(2000)).fetchJoin().fetch();
    
        return result;
    }

In fact, this code is not working and I get the following exception:

    org.hibernate.hql.internal.ast.QuerySyntaxException: with-clause not allowed on fetched associations; use filters [select user from com.example.demo.entity.User user left join fetch user.bookings as booking with booking.price > ?1]

The problem is that the condition clause is specified in `on` method - `on(booking.price.gt(2000))`. 

After some research I found that this condition should be specified in `where` method and should look like this:

    List<User> result = jpaQuery.from(user).leftJoin(user.bookings, booking).where(booking.price.gt(2000)).fetchJoin().fetch();

This works, but not how I would expect it to work, since it doesn't return ALL users, it returns only one user (Alice), which has some bookings, matching the condition clause. Basically, it just filters the merged table (result table after left join operation) and that's not what I'm looking for.

I want to retrieve all users, and if there are no any bookings for a specific user, then just have `null` instead of booking list for this user.
 

Please help, been struggling for hours without any success. 

<hr/>
Versions used:

- Spring Boot 2.0.2   
- Spring Data JPA 2.0.7  
- Hibernate 5.2.16.Final   
- QueryDSL 4.1.4

**Comment by dagi12** [comment]
Affects me too

**Comment by yejianfengblue** [comment]
I have the same problem

**Comment by sweetacaro** [comment]
#metoo

**Comment by icrona** [comment]
#me too

**Comment by belrbeZ** [comment]
The same one #metoo

**Comment by pch851130** [comment]
Affects me too

**Comment by pch851130** [comment]
@IdoSalomon 
List<User> result = jpaQuery.from(user).leftJoin(booking).on(booking.price.gt(2000)).fetchJoin().fetch();
It's a good solution. but fetchJoin() doesn't work. so user.bookings is "org.hibernate.LazyInitializationException"

**Comment by IdoSalomon** [comment]
> @IdoSalomon
> **List result = jpaQuery.from(user).leftJoin(booking).on(booking.price.gt(2000)).fetchJoin().fetch();**
> It's a good solution. but fetchJoin() doesn't work. so user.bookings is "org.hibernate.LazyInitializationException"

Oops, didn't notice it's Lazy. Edited my answer so it'd be initialized. Thanks.

**Comment by domschmidt** [comment]
[select user from com.example.demo.entity.User user left join fetch user.bookings as booking **with** booking.price > ?1]

the solution would be to replace "with" by "on" in the query. Are there any plans to fix this issue?

**Comment by jwgmeligmeyling** [comment]
This is a limitation of Hibernate. The WITH clause is simply not supported for fetch joins in that version of Hibernate. Depending on the dialect used, Hibernate supports the `ON` clause just fine. In order to use that with QueryDSL, be sure to use the `JPQLTemplates` instead of the `HQLTemplates`.

```java
    JPAQuery<User> jpaQuery = new JPAQuery(entityManager, JPQLTemplates.DEFAULT);
```

**Comment by cb-salamonm** [comment]
@jwgmeligmeyling Is still left join with ON condition is not supported yet.I'm still getting the same error

**Comment by cb-salamonm** [comment]
@alicebobecila  is the issue resolved for you?

**Comment by jwgmeligmeyling** [comment]
It is.

**Comment by cb-salamonm** [comment]
@jwgmeligmeyling  here my code: 
JPAQuery<EmployeeDetail> employeeDetailJPQLQuery = new JPAQuery<>(entityManager, JPQLTemplates.DEFAULT);
employeeDetailJPQLQuery.select(employeeDetail)
                .from(employeeDetail)
                .innerJoin(employeeDetail.departmentDetail).fetchJoin()
                .leftJoin(employeeDetail.payrollDetailList,payrollDetail)
                .on(payrollDetail.payrollDetailDate.eq(startDate))
                .fetchJoin()
                .where(employeeDetail.employeeId.like(employeeId)
                        .and(employeeDetail.departmentDetail.displayName.eq(departmentName)))
                .orderBy(payrollDetail.updatedAt.desc(),employeeDetail.hireDate.desc())
                .fetch();

- I'm having employee table , department table and payroll details table.
- I'm trying to fetch the payroll details for the particular month but still getting the error
Can you please help here?

**Comment by dipack-v** [comment]
```
List result = jpaQuery.from(user).leftJoin(booking).where(booking.isNull()
                                           .or(booking.price.gt(2000))).fetchJoin().fetch(); 
```
this worked for me
