### ISSUE TITLE
Is there any way to do dynamic projections in querydsl?

### ISSUE THREAD

**Issue by gravitywp** [querydsl/querydsl#2329]
like this: https://url?exclude=field1,fiedl2,  to exclude fields that I don't need, maybe also make fields don't select in SQL to help performance.

**Comment by shrds** [comment]
did you try something like what I have posted here https://github.com/querydsl/querydsl/issues/2331 ??

**Comment by gravitywp** [comment]
@shrds 
I don't fully understander your code. I can't select one-to-many field correctly. 
My code:
![image](https://user-images.githubusercontent.com/8477504/42141024-ad957b38-7dd8-11e8-9a66-eb4224faeceb.png)
The tags field is a one-to-many mapping field.
I got this error: 
"You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'as col_1_0_, tags2_.id as id1_2_, tags2_.created_time as created_2_2_, tags2_.pr' at line 1"
Do you have any idea?

**Comment by shrds** [comment]
@gravitywp you can import these 2 imports and then use them to load 1 to many relationship.
```
import static com.querydsl.core.group.GroupBy.groupBy;
import static com.querydsl.core.group.GroupBy.list;
```

I had to break my query into 2 parts so that I dont loose any child records during the transformation. Before transforming the result set first I loaded the Ids of the parent by creating the query with join conditions and others if there are any and then using the second query I read all the columns I needed. 

the first query looks something like this
```
    JPAQuery<Tuple> queryForIds =
        select(definition, clientId, definition.id).distinct().from(definition);
   return queryForIds;
```

and Second query is like below where I have used the ids of the parents to get al the relations
 ```

//the QueryDsl Query types look like

private final QGroupDefinitionEntity definition = QGroupDefinitionEntity.groupDefinitionEntity;
  private final QAliasEntity alias = QAliasEntity.aliasEntity;

//the 2nd query to transform the result set is like this. I have 1 to may relationship between definition and aliases.

newQuery().distinct().from(definition)
        .where(definition.clientId.in(clientId))
        .where(definition.id.in(ids))
        .orderBy(orderBy)
       .leftJoin(definition.aliases, alias)
        .transform(
            groupBy(definition.id).list(
                Projections.fields(
                    GroupDefinitionEntity.class,
                    definition.id,
                    definition.clientId,
                    definition.name,
                    definition.groupType,
                    definition.mnemonic,
                    definition.opaqueId,
                    list(Projections.fields(
                        AliasEntity.class,
                        alias.clientId,
                        alias.aliasId,
                        alias.aliasType,
                        alias.assigningAuthority,
                        alias.source).skipNulls())
                        .as(definition.aliases),
                    definition.createdDtTm,
                    definition.updatedDtTm)
                    .skipNulls()));
```

If you post your SQL query I might be able to suggest you some pseudo code.

**Comment by gravitywp** [comment]
@shrds  Thanks for the reply.
I changed to this
![image](https://user-images.githubusercontent.com/8477504/42203043-2c7b5e3e-7ed0-11e8-83c1-606d30ccdd23.png)
but I got this error: 
Caused by: java.lang.IllegalArgumentException: Unsupported expression new ElementTag(elementTag.createdTime)

**Comment by shrds** [comment]
If you are joining the 2 entities then you need to add another construct in the query with the join clause. I don't see where are you joining ElementTag in your query.

**Comment by areisyus** [comment]
> 
> 
> @gravitywp you can import these 2 imports and then use them to load 1 to many relationship.
> 
> ```
> import static com.querydsl.core.group.GroupBy.groupBy;
> import static com.querydsl.core.group.GroupBy.list;
> ```
> 
> I had to break my query into 2 parts so that I dont loose any child records during the transformation. Before transforming the result set first I loaded the Ids of the parent by creating the query with join conditions and others if there are any and then using the second query I read all the columns I needed.
> 
> the first query looks something like this
> 
> ```
>     JPAQuery<Tuple> queryForIds =
>         select(definition, clientId, definition.id).distinct().from(definition);
>    return queryForIds;
> ```
> 
> and Second query is like below where I have used the ids of the parents to get al the relations
> 
> ```
> 
> //the QueryDsl Query types look like
> 
> private final QGroupDefinitionEntity definition = QGroupDefinitionEntity.groupDefinitionEntity;
>  private final QAliasEntity alias = QAliasEntity.aliasEntity;
> 
> //the 2nd query to transform the result set is like this. I have 1 to many relationship between definition and aliases.
> 
> newQuery().distinct().from(definition)
>        .where(definition.clientId.in(clientId))
>        .where(definition.id.in(ids))
>        .orderBy(orderBy)
>       .leftJoin(definition.aliases, alias)
>        .transform(
>            groupBy(definition.id).list(
>                Projections.fields(
>                    GroupDefinitionEntity.class,
>                    definition.id,
>                    definition.clientId,
>                    definition.name,
>                    definition.groupType,
>                    definition.mnemonic,
>                    definition.opaqueId,
>                    list(Projections.fields(
>                        AliasEntity.class,
>                        alias.clientId,
>                        alias.aliasId,
>                        alias.aliasType,
>                        alias.assigningAuthority,
>                        alias.source).skipNulls())
>                        .as(definition.aliases),
>                    definition.createdDtTm,
>                    definition.updatedDtTm)
>                    .skipNulls()));
> ```
> 
> If you post your SQL query I might be able to suggest you some pseudo code.

Hi @shrds , would you know how to do this same transformation but using a subquery instead of the join clause to project collection attributes?

With examples that I found on the internet I couldn't find a chaining and clearer way to aggregate neasted lists as projections... do you have any suggestion about it?

**Comment by shrds** [comment]
> Hi @shrds , would you know how to do this same transformation but using a subquery instead of the join clause to project collection attributes?

With examples that I found on the internet I couldn't find a chaining and clearer way to aggregate neasted lists as projections... do you have any suggestion about it?

I haven't tried the subquery but why can't you use join?

**Comment by areisyus** [comment]
So, as JPA doesn't allow subqueries on select clause I think it must be done in some transformation API that manages "detached" subqueries and aggregate them on projections (just like hibernate manage to do when collections are annotated with @Fetch(FetchMode.SUBSELECT)) but I couldn't find a cleaner way to combine the transformer's helpers that I found on documentation to create something like this: (please, ignore absence of "transforms" and consider the structure of the query, I know that it is syntactically incorrect is just to illustrate the problem, consider that each entity used as example had a bunch of other fields and relations that we don't want to project on the query/resultSet)

```
newQuery().from(qMainEntity)
          .where(qMain.type.eq(1))
          .select(Projections.fields(
              MainEntity.class,
              qMainEntity.id, 
              qMainEntity.name, 
              list(Projection fields(
                  SecondEntity.class,
                  qSecondEntity.id,
                  qSecondEntity.description,
                  list(Projections.fields(ThirdEntity.class, qThirdEntity.id, qThirdEntity.value).as(qSecondEntity.thirdEntities)
             ).as(qMainEntity.secondEntities)
         )
```

the main problem that I see on using joins in this scenario is that tuple results will be multiplied by each collection size and also the data from columns that we don't need to be multiplied (like qMainEntity.name) for example. It will potentially lead to performance issues...

I think that QueryDSL just doesn't have an API to handle this kind of problem in a straightforward way like the example tries to illustrate, probably yet (I hope), but, I want to be sure and find all possibilities as much as possible.

**Comment by shrds** [comment]
@areisyus, If I am understanding the requirements correctly then your mainEntity is a parent and secondEntity is a child, so maybe its a one-to-many relationship??  If yes, can you not group by a field from main entity and while projecting select the columns you need from main entity, which will also contain a list of second entity (children). That way you will read only the columns you need and that should resolve your concern.
eg. the way I did and posted in the previous comment. definition is my parent entity and alias is my child entity. 
```
 newQuery().distinct().from(definition)
       .where(definition.clientId.in(clientId))
       .where(definition.id.in(ids))
       .orderBy(orderBy)
      .leftJoin(definition.aliases, alias)
       .transform(
           groupBy(definition.id).list(
               Projections.fields(
                   GroupDefinitionEntity.class,
                   definition.id,
                   definition.clientId,
                   definition.name,
                   definition.groupType,
                   definition.mnemonic,
                   definition.opaqueId,
                   list(Projections.fields(
                       AliasEntity.class,
                       alias.clientId,
                       alias.aliasId,
                       alias.aliasType,
                       alias.assigningAuthority,
                       alias.source).skipNulls())
                       .as(definition.aliases),
                   definition.createdDtTm,
                   definition.updatedDtTm)
                   .skipNulls()));
```
