### ISSUE TITLE
Projection error on collection field

### ISSUE THREAD

**Issue by gravitywp** [querydsl/querydsl#2332]
My code:
![image](https://user-images.githubusercontent.com/8477504/42143629-ba0154e0-7de8-11e8-94f1-9de0a8b20cca.png)
Here is the sql HQL generated:
SELECT          prnindexcl0_.prn    AS col_0_0_, 
                prnindexcl0_.NAME   AS col_1_0_, 
                .                   as col_2_0_, 
                tags2_.id           AS id1_2_, 
                tags2_.created_time AS created_2_2_, 
                tags2_.prn          AS prn3_2_, 
                tags2_.tag          AS tag4_2_, 
                tags2_.updated_time AS updated_5_2_ 
FROM            prn_index prnindexcl0_ 
LEFT OUTER JOIN `element_tag` tags1_ 
ON              prnindexcl0_.prn=tags1_.prn 
INNER JOIN      `element_tag` tags2_ 
ON              prnindexcl0_.prn=tags2_.prn 
WHERE           prnindexcl0_.`DELETE`<>? 
ORDER BY        prnindexcl0_.create_time DESC

I got this error: 
"You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'as col_2_0_, tags1_.id as id1_2_, tags1_.created_time as created_2_2_, tags1_.pr' at line 1"

I'm confused with "." column in the select statement. what is that mean?

**Comment by jchampemont** [comment]
Hi, I'm running into the same issue, did you manage to find a way around?

**Comment by thackel** [comment]
*.tags sounds like a list/1:n maybe this is a problem here.
Just select the tag and join the Prn to it. Stream it into a map with prn as key and you get all the tags for one prn.
