### ISSUE TITLE
java.lang.Integer cannot be cast to java.math.BigDecimal

### ISSUE THREAD

**Issue by zqr95518** [querydsl/querydsl#2333]
Try to use tuple.get(0, BigDecimal.class).
When get Integer is OK. 
I need to use new BigDecimal(tuple.get(0, Integer.class).intValue()) and will get null.
How about add auto convert?
querydsl-jpa 4.2.1

**Comment by jwgmeligmeyling** [comment]
Auto convert comes at the risk of losing precision. If you want your result as a bigdecimal, make sure to cast it inside the query to a numeric type.
