### ISSUE TITLE
SQLExpressions.unionAll allow super types

### ISSUE THREAD

**Issue by cdalexndr** [querydsl/querydsl#2336]
The following fails because `SQLExpressions.unionAll` method accepts `List<SubQueryExpression<T>>` as parameter:
```
            SQLQuery<Tuple> first = SQLExpressions.select();
            SQLQuery<Tuple> second = SQLExpressions.select();
            List<SQLQuery<Tuple>> queries = Arrays.asList( first, second );
            Union<Tuple> union = SQLExpressions.unionAll( queries );
```
The method parameter should be changed to `List<? extends SubQueryExpression<T>>` to allow super types.

Workaround:
`Union<Tuple> union = SQLExpressions.unionAll( Collections.unmodifiableList( queries ) );`

**Comment by jwgmeligmeyling** [comment]
This issue should have been fixed in QueryDsl 4.x where the SubQuery and Query hierarchies are combined.
