### ISSUE TITLE
Order by field(id, 2,1,3)

### ISSUE THREAD

**Issue by beamofsoul** [querydsl/querydsl#2342]
I am trying to get a list of data in order by ids like 2,1,3, so the mysql query should look like:
`SELECT * FROM `hm_data_stream` WHERE id in (2, 1, 3) ORDER BY FIELD(id, 2, 1, 3);`
or
`SELECT * FROM `hm_data_stream` WHERE id in (2, 1, 3) ORDER BY FIND_IN_SET(id,'3, 1, 2');`

I have no idea about how to organize my querydsl query code:
`query.where($.id.in(2,1,3)).orderBy(???)`

Does anyone have any idea about this?

**Comment by linyongfu2013** [comment]
Hi, did u have any solutions yet ?

**Comment by linyongfu2013** [comment]
@Shredder121  any helpful idea , pls ?

**Comment by Shredder121** [comment]
I'm pretty sure we don't yet have sorting by a predefined set of values. 🤔

**Comment by beamofsoul** [comment]
Right right right...
@linyongfu2013 no solutions so far...

**Comment by imtiazShakil** [comment]
This would be a very nice to have feature!

**Comment by imtiazShakil** [comment]
As a workaround I created this simple static function which does the ordering.

```java
  /**
   * Reorders {@code itemList} according to the index list provided in {@code indexList}
   * Example:
   * itemList = [ {id: 10, ..}, {id: 12, ...}, {id: 13, ...} ]
   * indexList = [ 12, 13, 10]
   * output: [ {id: 12, ..}, {id: 13, ...}, {id: 10, ...} ]
   * <p>
   * Complexity: O(n), Memory: O(1)
   *
   * @param itemList  given list of items
   * @param indexList given list of indexes
   * @return reordered list of items
   */
  public static <T extends BaseModel> List<T> orderByAccordingToIndex(List<T> itemList,
      List<Long> indexList) {
    HashMap<Long, T> hashMap = new HashMap<>(itemList.size());
    itemList.forEach(item -> hashMap.put(item.getId(), item));

    ArrayList<T> output = new ArrayList<>(itemList.size());
    for (Long indx : indexList) {
      output.add(hashMap.get(indx));
    }

    return output;
  }
```


And This is my `BaseModel`:
```java
public class BaseModel {
  @Id
  @GeneratedValue(strategy = GenerationType.IDENTITY)
  private long id;

  @Version
  private int version;
  
  // getter and setter methods
}
```
