### ISSUE TITLE
Expression.list() with size =1 return exception

### ISSUE THREAD

**Issue by jzlima** [querydsl/querydsl#2344]
I've been used ops.in with expression.list and the users sends a list dynamicly. 
```
Expression target[] = new Expression[values.size()];
            for (int i = 0; i < values.size(); i++) {
                target[i]=(Expressions.constant(values.get(i)));
            }
Expressions.predicate(Ops.IN, propPath, Expressions.list(target));
```

but when user sent to me an only one value the follow error was showed:
`java.lang.ClassCastException: java.lang.Integer cannot be cast to java.util.Collection`

**Comment by jwgmeligmeyling** [comment]
Could you share the full stack trace?
