### ISSUE TITLE
Attempted to write multiple times to …, please check your configuration

### ISSUE THREAD

**Issue by pascal-hofmann** [querydsl/querydsl#2347]
With version 4.2.1 I get the error

https://github.com/querydsl/querydsl/blob/8f96f416270d0353f90a6551547906f3c217833a/querydsl-sql-codegen/src/main/java/com/querydsl/sql/codegen/MetaDataExporter.java#L430

 while using querydsl-maven-plugin together with `jdbcDriver com.mysql.cj.jdbc.Driver` (mysql-connector-java 8.0.11). This happens because the user I use to connect to MySQL has access to multiple databases. As a workaround I had to add `nullCatalogMeansCurrent=true` to `jdbcUrl`.

**Comment by Shredder121** [comment]
Do you configure separate packages for the multiple schemas?
Or do you filter the schemas with a pattern?
Can you paint the picture a bit more, since it's intended to fail when the maven plugin detects the class was already generated.

**Comment by pascal-hofmann** [comment]
I filter the tables via tableNamePattern, and tried to filter via schemaPattern, but this has no effect. (schema is always null, catalog is different depending on database name).

**Comment by starsoheil2007** [comment]
I have same issue !

**Comment by sashuprosperoware** [comment]
Workaround : Create a new user in database which has access to only the given database for which you want to create Q files for. Done.
