### ISSUE TITLE
Why does sum() not return NumberPath <Long>?

### ISSUE THREAD

**Issue by cel533** [querydsl/querydsl#2356]
table column is Integer,but sum(Integer)  return  NumberPath\<Integer\>  .
but  sum(Integer) has the possibility of exceeding the length;

**Comment by jwgmeligmeyling** [comment]
Most operations in ANSQI SQL and JPA return the type of their parameters.

If you need bigger numbers, you should cast the parameters. Or if your DBMS doesn't need it, feel free to cast the result instead.

**Comment by jpmsilva** [comment]
For anyone running into this issue, the JPA spec specifies that the result will be Long when summing Integers:

**4.8.5 Aggregate Functions in the SELECT Clause**

[...snip...]
The Java type that is contained in the result of a query using an aggregate function is as follows:
• COUNT returns Long.
• MAX, MIN return the type of the state field to which they are applied.
• AVG returns Double.
• SUM returns Long when applied to state fields of integral types (other than BigInteger); Double when applied to state fields of floating point types; BigInteger when applied to state fields of type BigInteger; and BigDecimal when applied to state fields of type BigDecimal.
