### ISSUE TITLE
Helpers / support for Seek / KeySet pagination ?

### ISSUE THREAD

**Issue by ieugen** [querydsl/querydsl#2360]
Hello, 

Do you know if querydsl has added support or helpers for implementing seek / keyset pagination as described in [use-the-index] . I only found some mentions in this [old-discussion] . 

Other tools like jooq and blaze have some built-in support for this kind of thing (some for quite some time) and it would be great if querydsl had something as well. 

Regards, 

[use-the-index] https://use-the-index-luke.com/sql/partial-results/fetch-next-page#sb-row-values 
[old-discussion] https://groups.google.com/forum/#!msg/querydsl/bG_2MssrcTo/G8WdKrlHQ7kJ 
[blaze-persistence] https://blazebit.com/blog/2016/pagination-blog-post.html
[jook-pagination] https://blog.jooq.org/2013/10/26/faster-sql-paging-with-jooq-using-the-seek-method/

**Comment by andygoossens** [comment]
There is no such support in QueryDSL. :-(

It is a bit hidden, but at least row values expression are possible. See my comment: https://github.com/querydsl/querydsl/issues/2315#issuecomment-410660384

**Comment by jwgmeligmeyling** [comment]
There is now a QueryDSL Blaze-Persistence integration which can be used to achieve pagination in `querydsl-jpa`.
