### ISSUE TITLE
Custom operators

### ISSUE THREAD

**Issue by sinuhepop** [querydsl/querydsl#2363]
I've made a custom operator which is created from `@QueryDelegate` methods using `ExpressionUtils.predicate()`. Everything goes correctly, except invoking `toString()` on a predicate containing such operator. The exception is the same as in other issues ([1](https://github.com/querydsl/querydsl/issues/1638), [2](https://github.com/querydsl/querydsl/issues/41)):

```
java.lang.NullPointerException
	at com.querydsl.core.types.Templates.getPrecedence(Templates.java:335)
	at com.querydsl.core.types.ToStringVisitor.visit(ToStringVisitor.java:61)
	at com.querydsl.core.types.ToStringVisitor.visit(ToStringVisitor.java:24)
	at com.querydsl.core.types.OperationImpl.accept(OperationImpl.java:83)
	at com.querydsl.core.types.ExpressionBase.toString(ExpressionBase.java:57)
	at com.querydsl.core.types.dsl.DslExpression.toString(DslExpression.java:77)
	...
```
The reason is `DEFAULT `instance in `Templates `has no precedence nor template defined for my operator. Calling `setPrecedence()` method solves the issue, but is protected. I've tried it using reflection.

Is there any other way to solve that issue? Do you think calls to `setPrecedence()` are legitimate and thus should be public?

**Comment by jwgmeligmeyling** [comment]
The call is legitimate.

An operator is not aware of the dialect it is serialized against. The toString implementation for expressions uses a visitor that assumes the default dialect. This error is pretty much expected.

The only work around is to not rely on `toString()`, but instead use `expression.accept(ToStringVisitor.DEFAULT, YourCustomTemplates.INSTANCE)` (or override `toString` - if at all possible for that particular expression type).
