### ISSUE TITLE
Support .min() and .max() for ComparableExpression

### ISSUE THREAD

**Issue by grubeninspekteur** [querydsl/querydsl#2366]
As Comparable enforces a total ordering, all comparables should offer a maximum and minimum. This is useful for types like Instant:

```java
class Shipping {Instant departure; /*...*/}
Shipping shipping = alias(Shipping.class);
new JPAQuery<Instant>(em).select($(shipping.getDeparture()).max()).from($(shipping));
```

**Comment by jwgmeligmeyling** [comment]
I agree that `min`/`max` could be moved up from `NumberExpression` and `DateExpression` to `ComparableExpression`.
