### ISSUE TITLE
Oracle paging performance 

### ISSUE THREAD

**Issue by cel533** [querydsl/querydsl#2368]
limitOffsetTemplate is  as slow When sql contains  listagg and left join . 
my fix: 
 `  private String limitOffsetStart = "select * from (\n select a.*, rownum rn from (\n";`
  `  private String limitOffsetEnd = "\n ) a where rownum <={0s}) where ";`
  `  private String limitOffsetTemplate = " rn > {0s}";`

 

                   if (mod.getLimit() == null) {  context.append(outerQueryStart);
                    context.serializeForQuery(metadata, forCountRow);
                    context.append(outerQueryEnd); 
                    context.handle(offsetTemplate, mod.getOffset());
                } else {
                    context.append(limitOffsetStart);
                    context.serializeForQuery(metadata, forCountRow);
                    context.handle(limitOffsetEnd,mod.getOffset()+ mod.getLimit()); 
                    context.handle(limitOffsetTemplate, mod.getOffset());
                }

**Comment by jwgmeligmeyling** [comment]
Without the a full patch, we can't look at this.
