### ISSUE TITLE
ListPath count error

### ISSUE THREAD

**Issue by nonpool** [querydsl/querydsl#2370]
code:
```
@Entity
@Data
public class Bar {

  @Id private Long id;

  private Long number;
}
```

```
@Entity
@Data
public class Foo {

  @Id private Long id;

  @OneToMany
  private List<Bar> bars;
}
```

```
@Repository
interface BarRepository extends JpaRepository<Bar, Long>, QuerydslPredicateExecutor<Bar> {}

@Repository
interface FooRepository extends JpaRepository<Foo, Long>, QuerydslPredicateExecutor<Foo> {}

public class TestClass extends BasicDataJpaTest {

  @Autowired FooRepository fooRepository;

  @Test
  public void shouldFindAllSuccess() throws Exception {
    Iterable<Foo> foos = fooRepository.findAll(QFoo.foo.bars.any().number.gt(5).count().gt(5));
  }
}
```

run this test got a error:
`org.springframework.dao.InvalidDataAccessApiUsageException: org.hibernate.hql.internal.ast.QuerySyntaxException: unexpected token: exists near line 3, column 13 [select foo
from sg.gov.msf.dss.model.entity.Foo foo
where count(exists (select 1
from foo.bars as foo_bars_0
where foo_bars_0.number > ?1)) > ?1]; nested exception is java.lang.IllegalArgumentException: org.hibernate.hql.internal.ast.QuerySyntaxException: unexpected token: exists near line 3, column 13 [select foo
from sg.gov.msf.dss.model.entity.Foo foo
where count(exists (select 1
from foo.bars as foo_bars_0
where foo_bars_0.number > ?1)) > ?1]`

**Comment by nonpool** [comment]
This is a bug or a wrong way to query with ListPath?

**Comment by Shredder121** [comment]
Yes that's a wrong way to query a listpath.
you can't really combine a .any().gt() and also do aggregation (`.count()`)
Because we rewrite the query.

Also it's preferable to do easy crud with spring data, and do more complex queries manually.

If you need more support, please get in contact with spring data.
