### ISSUE TITLE
Mixing contains and containsIgnoreCase - should use separate parameters

### ISSUE THREAD

**Issue by kdebski85** [querydsl/querydsl#2374]
I am using Querydsl 4.2.1, Hibernate 5.0.0 and DB2 10.5.
I have a predicate:

```
someEntity.propertyA.stringValue().contains(text)
.or(someEntity.propertyB.containsIgnoreCase(text))
```
As you can see, the first property uses "contains" and the second "containsIgnoreCase".
Additionally, the same variable "text" is passed to both methods.

It does not work as expected when "text" variable contains upper-cased characters and the text should match propertyB.

I enabled logging of Hibernate parameters and I can see that only one parameter is bound:
`binding parameter [1] as [VARCHAR] - [%Hammond%]`

In this case, Querydsl should use two parameters.
The first one, used for propertyA, should have the original case - %Hammond%
The second, used for propertyB, should be lower-cased - %hammond%

As a workaround, I currently convert the text passed to containsIgnoreCase to lower-case manually.

```
someEntity.propertyA.stringValue().contains(text)
.or(someEntity.propertyB.containsIgnoreCase(text.toLowerCase()))
```

**Comment by jwgmeligmeyling** [comment]
QueryDSL uses a parameter per object (based on instance based equality). As named parameters may be reused, this should cause no issues. In the conversion from a JPQL to SQL query in your ORM provider, the parameters will be split up again.

What was the actual problem you were seeing? Besides observing an unexpected amount of parameters?
