### ISSUE TITLE
support for incremental annotation processing in gradle 4.7+

### ISSUE THREAD

**Issue by basmastr** [querydsl/querydsl#2380]
Since version 4.7 gradle allows annotation processors to opt-in for incremental annotation processing. Without it any change in a project with a dependency on querydsl results in full rebuild, including the generation of Q classes. Adapting this would reduce build times considerably.

[Relevant  documentation ](https://docs.gradle.org/4.7-rc-2/userguide/java_plugin.html#sec:incremental_annotation_processing)

The gradle team is providing support to implement this for popular projects relying on annotation processors. Originated in this [ticket](url).

**Comment by jwgmeligmeyling** [comment]
PR's will be accepted.
