### ISSUE TITLE
QueryDSL, illegal argument type when projecting LocalDateTime from JPASQLQuery into DTO

### ISSUE THREAD

**Issue by TumanovViktor** [querydsl/querydsl#2382]
Very similar situation to [issue#575](https://github.com/querydsl/querydsl/issues/575), but with conversion Timestamp/Date -> LocalDate/LocalDateTime in native queries. In my s-classes I use LocalDate field and when I use Projection.constuctor to fill in my DTO, I get java.lang.IllegalArgumentException: argument type mismatch error. I used SQLQuery before, but it was not the best choice for me, since it doesn't pass through JPA. Do you have any advice in that case?

**Comment by kimsangkyun** [comment]
@TumanovViktor hi im same problem
u solved this?

**Comment by trenatov** [comment]
faced this issue but with ZonedDateTime
