### ISSUE TITLE
QueryDSL / spring: jdbcConfiguration example looks wrong

### ISSUE THREAD

**Issue by fylb** [querydsl/querydsl#2383]
Had some issue with this: https://github.com/querydsl/querydsl/blob/2bf234caf78549813a1e0f44d9c30ecc5ef734e3/querydsl-examples/querydsl-example-sql-spring/src/main/java/com/querydsl/example/config/JdbcConfiguration.java#L56

These lead to a connection being opened twice.

Preferred configuration would look like this:

    @Bean
    public SQLQueryFactory queryFactory(DataSource datasource) {
        Provider<Connection> provider = new SpringConnectionProvider(dataSource);
        return new SQLQueryFactory(querydslConfiguration(), provider);
    }

    @Bean
    public PlatformTransactionManager transactionManager(DataSource datasource) {
        return new DataSourceTransactionManager(dataSource);
    }

**Comment by Seti87** [comment]
Did you annotate your class with @Configuration? It is required to inject bean from context in place of "dataSource()" instead creating new data source.

**Comment by fylb** [comment]
Damn it, I imported it in a main configuration class annotated with `@Configuration` but forgot the annotation it in the imported class, my bad. Thanks.
