### ISSUE TITLE
Maven plugin does not filter packages

### ISSUE THREAD

**Issue by smuret** [querydsl/querydsl#2384]
Trying to generate code with the jpa-export goal using "querydsl-maven-plugin" does not seem to restrict the generated classes to the packages in the configuration.
Here is the plugin part of my pom.xml:
`<plugin>
<groupId>com.querydsl</groupId>
<artifactId>querydsl-maven-plugin</artifactId>
<version>${querydsl.version}</version>				
<executions>
<execution>
<goals>
<goal>jpa-export</goal>
</goals>
</execution>
</executions>
<configuration>
<targetFolder>src/main/generated</targetFolder>
<packages>
<package>test</package>
</packages>
</configuration>
<plugin>`

The generated code includes all the jpa entities in my classpath.
**Querydsl version is 4.2.1**

**Comment by jwgmeligmeyling** [comment]
Might have been fixed by https://github.com/querydsl/querydsl/pull/2586
