### ISSUE TITLE
How can i subtract NumberExpression values? 

### ISSUE THREAD

**Issue by JadChahine** [querydsl/querydsl#2389]
Hi,

I have 2 **NumberExpression<Integer>** fields and I need to make a query in QueryDSL in order to get all the matching records that have field1 - field2 = certain number.

In brief I want to get the "int" value from **NumberExpression<Integer>** variable, how can i achieve this?

**Comment by robertandrewbain** [comment]
Where `myTable` is the generated `Q` class (extends `RelationalPathBase`) and `field1` and `field2` are `NumberPath<Integer>` (JDBC maps the database column types to `Integer`):

`.where(myTable.field1.subtract(myTable.field2).eq(Expressions.constant(<certain_number>))`

**Comment by zchstart** [comment]
But I have this problem
Ora-00904: "ADD_DAYS": invalid identifier
I'm using Oracle
