### ISSUE TITLE
Filtering in Spring Data JPA Repository using QueryDslPredicateExecutor with a nullable foreign key causes issue from cross join

### ISSUE THREAD

**Issue by dkindel** [querydsl/querydsl#2391]
This issue is pretty similar to [Issue 1833](https://github.com/querydsl/querydsl/issues/1833) in that a cross join is generated instead of something like a left join.

The whole issue I've run across is detailed [here ](https://stackoverflow.com/questions/53621940/filtering-in-spring-data-jpa-repository-using-querydsl-with-a-nullable-foreign-k).  If I should go ahead and reiterate all of that here, I can but the gist is that I tried I have a table with a nullable foreign key to another table.  When I try to filter based on contents of the foreign table, it doesn't matter that I may have found a match in the primary table because of the JPQL query that was generated, using a cross join instead of a left join. 

I'm currently working through some potential workarounds but they all entail something does not include the ease of use that the QueryDslPredicateExecutor provides. 

There could also be something I'm missing here since I'm relatively new to Spring Data JPA repositories and QueryDSL so if that's the case, let me know.

**Comment by neogetz** [comment]
Any progress on this issue? It's quite annoying to use Specifications or any other workaround...
