### ISSUE TITLE
incorrect insert with composite primary key

### ISSUE THREAD

**Issue by Lofv** [querydsl/querydsl#2392]
Hello there.
I have the problem with insert.
I have table

    @Generated("com.mysema.query.sql.codegen.MetaDataSerializer")
    public class QProjectSet extends com.mysema.query.sql.RelationalPathBase<QProjectSet> {

    private static final long serialVersionUID = -1160170628;

    public static final QProjectSet projectSet = new QProjectSet("PROJECT_SET");

    public final StringPath note = createString("note");

    public final NumberPath<Long> projectId = createNumber("projectId", Long.class);

    public final NumberPath<java.math.BigInteger> psId = createNumber("psId", java.math.BigInteger.class);

    public final NumberPath<Long> templateId = createNumber("templateId", Long.class);

    public final com.mysema.query.sql.PrimaryKey<QProjectSet> projectSetPk = createPrimaryKey(projectId,psId);

    public final com.mysema.query.sql.ForeignKey<QProjects> projectSetProjectIdFk = createForeignKey(projectId, "ID");

    public final com.mysema.query.sql.ForeignKey<QTemplates> projectSetTemplateIdFk = createForeignKey(templateId, "ID");

    public QProjectSet(String variable) {
        super(QProjectSet.class, forVariable(variable), "TEST", "PROJECT_SET");
        addMetadata();
    }

    public QProjectSet(String variable, String schema, String table) {
        super(QProjectSet.class, forVariable(variable), schema, table);
        addMetadata();
    }

    public QProjectSet(Path<? extends QProjectSet> path) {
        super(path.getType(), path.getMetadata(), "TEST", "PROJECT_SET");
        addMetadata();
    }

    public QProjectSet(PathMetadata<?> metadata) {
        super(QProjectSet.class, metadata, "TEST", "PROJECT_SET");
        addMetadata();
    }

    public void addMetadata() {
        addMetadata(note, ColumnMetadata.named("NOTE").withIndex(4).ofType(Types.VARCHAR).withSize(1000));
        addMetadata(projectId, ColumnMetadata.named("PROJECT_ID").withIndex(3).ofType(Types.DECIMAL).withSize(18).notNull());
        addMetadata(psId, ColumnMetadata.named("PS_ID").withIndex(1).ofType(Types.DECIMAL).withSize(0).notNull());
        addMetadata(templateId, ColumnMetadata.named("TEMPLATE_ID").withIndex(2).ofType(Types.DECIMAL).withSize(18).notNull());
    }

and in insert something like this 

    public BigInteger insertNewProjectSet(Long templateId, String comment, final List<Project> projectList) {

        Long first = projectList.get(0).getId();
        BigInteger psId = dslTemplate.insertWithKey(qProjectSet, insert -> {
            insert.set(qProjectSet.templateId, templateId);
            insert.set(qProjectSet.note, comment);
            insert.set(qProjectSet.projectId, first);
            return insert.executeWithKey(qProjectSet.psId);
        });
        if (size > 1) {
            dslTemplate.insert(qProjectSet, insert -> {
                for (int i = 1; i < size; i++) {

                    insert.set(qProjectSet.templateId, templateId);
                    insert.set(qProjectSet.note, comment);
                    insert.set(qProjectSet.projectId, projectList.get(i).getId());
                    insert.set(qProjectSet.psId, psId);
                    insert.addBatch();
                }
                return insert.execute();
            });
        }
        return psId;
    }

we will get something like this 

 ps_id | templateId | projectId | note
-------|-------------|-----------|------
 25302 | 53602 | 673002    
 673002 | 53602 | 673102    
 673002 | 53602 | 673202    
 673002 | 53602 | 673302

where 673002,673102, 673202, 673302 was in a list.

As you can see after first insert, my BigInteger psId got 673002 as primary key and started to insert other rows with that psId.

Why does it happens?

If i do change   

    public final com.mysema.query.sql.PrimaryKey<QProjectSet> projectSetPk = createPrimaryKey(projectId,psId);  

to

    public final com.mysema.query.sql.PrimaryKey<QProjectSet> projectSetPk = createPrimaryKey(psId,projectId);  
 everything gets ok.

**Comment by Lofv** [comment]
As i found in the package com.mysema.query.sql.dml;
 there is method
  private <T> T executeWithKey(Class<T> type, @Nullable Path<T> path) 
where there is line with    return configuration.get(rs, path, 1, type);

And when I stop debugger on that line I can get
 
rs.getBigDecimal(1) return 684002 ( I do not need that number, And why it was casted to BigInteger although it is Long type)
rs.getBigDecimal(2) return 27002 (I need that )
inside rs->statement->numReturnParams we can see how much elements as parameters. In my issue i have 2;

Could you help me with that?

**Comment by Seti87** [comment]
Really nice investigation. 
For me it looks like bug, hovewer I doubt if someone will be able to provide fix soon, as there are many pull requests already waiting for merging.

Try to use executeWithKeys() as workaround - it returns ResultSet, and you will have access to all columns of PK.

**Comment by Lofv** [comment]
Thank you for your answer.
Unfortunatelly,

    public <T> List<T> executeWithKeys(Path<T> path) {
        return executeWithKeys((Class<T>) path.getType(), path);
    }

go here

    private <T> List<T> executeWithKeys(Class<T> type, @Nullable Path<T> path) {
    ....
    while (rs.next()) {
                rv.add(configuration.get(rs, path, 1, type));
            }
    ....
    }

So, executeWithKeys() don`t help me (

**Comment by Seti87** [comment]
I mean this one with no args:

public ResultSet executeWithKeys() {

**Comment by Shredder121** [comment]
> inside ((OracleStatement)rs.getStatement()).numReturnParams we can see how much elements as parameters. In my issue i have 2;

Just wondering, could you set up a minimal reproduction case. I do have to admit I haven't ran my Oracle instance in some time, but I will need to have sources (db in this case) , the exact configuration to generate the offending Qclasses, tests to see when a solution works, etc.
I can't guarantee *when* I will be able to pick this up, but a flipped metadata sounds strange enough that I will need to fix this.

**Comment by Seti87** [comment]
I believe this one is not related to specific database, as I met this also in MySQL. 
Method executeWithKey(...) simply deesn't check for ResultSet metadata, returning always first column of PK.
I will try to provide simple example with H2.

We are also missing method to return more than one column of PK after insert.

PS. Shredder121 it's nice to see you still around :)

**Comment by Shredder121** [comment]
> Method executeWithKey(...) simply deesn't check for ResultSet metadata, returning always first column of PK.

Well probably if we generate the flipped metadata (see below) then we can still pick the first result. But maybe something more clever than a dumb `[0]` is needed.
Which is why the project would help, to see the metadata as it is processed.

> If i do change
> 
> ```
> public final com.mysema.query.sql.PrimaryKey<QProjectSet> projectSetPk = createPrimaryKey(projectId,psId);  
> ```
> to
> 
> ```
> public final com.mysema.query.sql.PrimaryKey<QProjectSet> projectSetPk = createPrimaryKey(psId,projectId);  
> ```
> everything gets ok.

P.S. no problem, although I really wish I had more time to do more meaningful things, but I'm still around.

**Comment by Lofv** [comment]
> Just wondering, could you set up a minimal reproduction case. I do have to admit I haven't ran my Oracle instance in some time, but I will need to have sources (db in this case) , the exact configuration to generate the offending Qclasses, tests to see when a solution works, etc.

Excuse me, but I`m a little misunderstand what should I provide now.
I post my Q object on the first post with it`s metadata.
I use Oracle db. Also I use 3.6.8 v. of com.mysema.querydsl



> I mean to use this one with no args directly:
> 
> public ResultSet executeWithKeys() {

Thank you for that variant, I`ll try it soon

**Comment by Lofv** [comment]
Collegeaus, is there any new information?

**Comment by Shredder121** [comment]
> > Excuse me, but I'm a little misunderstand what should I provide now.
> > I post my Q object on the first post with it`s metadata.
> > I use Oracle db. Also I use 3.6.8 v. of com.mysema.querydsl
> 
> but I will need to have sources (db in this case) , the exact configuration to generate the offending Qclasses, tests to see when a solution works


Yes thanks for that, but I mean in order to be able to fix the combination between SQLInsertClause, MetadataExporter, a working DatabaseMetaData to peek into the ResultSet, the expected result, we'd need a project to repeatedly run the tests.

*Sorry this was as a draft for so long.*

**Comment by Lofv** [comment]
Unfortunatelly, I can`t send the project which is in production already. Maybe I send you other information for test?

**Comment by Lofv** [comment]
I`ve tried with method insert.executeWithKeys() but id wasn`t helpfull.
I couldn`t get anything except 
```
 ResultSet set= dslTemplate.insertWithKey(qProjectSet, insert -> {
            insert.set(qProjectSet.templateId, templateId);
            insert.set(qProjectSet.note, comment);
            insert.set(qProjectSet.projectId, project.getId());
            return insert.executeWithKeys();
        });
ResultSetMetaData meta=set.getMetadata();
or
BigInteger big=set.getBigDecimal("PS_ID");
```

I can`t get set.getArray("PS_ID");  or set.getObject("PS_ID"); even if I point column index, it doesn`t help too.
