### ISSUE TITLE
Missing oracle jars

### ISSUE THREAD

**Issue by guilhermecgs** [querydsl/querydsl#2394]
Hi folks,

I have already installed oracle jars locally in my maven repo using this command:

> ..\mvnw install:install-file -Dfile=ojdbc8.jar  -DgroupId=com.oracle -DartifactId=ojdbc8 -Dversion=12.2.0.1 -Dpackaging=jar

Why dont querydsl plugin complains about missing jars?

![image](https://user-images.githubusercontent.com/8465337/49799133-4baf4980-fd2b-11e8-9a64-462865eb4b4a.png)

![image](https://user-images.githubusercontent.com/8465337/49799169-64b7fa80-fd2b-11e8-9c93-2bd836f98d46.png)

ERROR:

> org.eclipse.aether.transfer.ArtifactNotFoundException: Failure to find com.oracle:ojdbc8:jar:12.2.0.1 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates

**Comment by thackel** [comment]
Its not allowed to provide any "oracle jars".
There is no maven artifact at all, the oracle jdbc driver needs to be installed by yourself.
For an example of how to install the driver in your local repository see here: [](https://springframework.guru/configuring-spring-boot-for-oracle/)

**Comment by guilhermecgs** [comment]
I already did the installation -> thats the point

..\mvnw install:install-file -Dfile=ojdbc8.jar -DgroupId=com.oracle -DartifactId=ojdbc8 -Dversion=12.2.0.1 -Dpackaging=jar

**Comment by thackel** [comment]
Put the dependency in the plugins dependency section

**Comment by guilhermecgs** [comment]
Already tried that too

![image](https://user-images.githubusercontent.com/8465337/49799606-849bee00-fd2c-11e8-8b1f-bea6a36eb1f6.png)

**Comment by thackel** [comment]
Thats not a Querydsl problem.
It has something to do with your local maven setup. Check if the driver is already in the local repository (e.g. .m2/repositorycom/oracle/...).

Also for generating Q-Classes from JPA entites you don't need any JDBC driver or a real connection.
