### ISSUE TITLE
PreparedStatement not closed when using fetchOne() or fetchFirst()

### ISSUE THREAD

**Issue by rklerke** [querydsl/querydsl#2395]
hi
As far as i can see the preparedStatement in AbstractSQLQuery initialized in l. 364 and used in l. 370 is never closed in case of exception is thrown when it is being used in l. 370. It should be closed in the finally clause which is already present.

thanks for a great framework!

best regards
Rasmus

**Comment by jwgmeligmeyling** [comment]
The `PreparedStatement` and the `ResultSet` are associated with the `SQLListenerContextImpl` which takes care of closing these resources. Closing happens automatically after the `Iterator` is exhausted in `SQLResultIterator`. In case of an exception, the context is closed by the catch-block.
