### ISSUE TITLE
COSMOS DB - MongoDB regex query Issue on contains ignore case 

### ISSUE THREAD

**Issue by rvpashok** [querydsl/querydsl#2396]
**Project Overview:** 
I have spring boot project using MongoDB for storage. Added Spring-data-mongodb-2.0.6.RELEASE.jar as mongodb dependency. Having **http://<domain>/{contextpath}/findAll** rest service API's,  using QueryDsl predicate for filter, sort and search functionalities. Using predicate **contains, containsIgnoreCase, startsWithIgnoreCase ,endsWithIgnoreCase** functions/operation for mongo document fields. Its generating regex for correponding functionalities as below:

**Ex:** Searching "Offers" string in name field from "offers" collection entries. { "name" : { "$regex" : ".*\\DOffers\\E.*"}} .
Everything working fine for Standalone Mongo server.

**Issue:**
When We are connecting our spring boot application with Azure Cosmos DB multi-model database with MongoDB driver facing some issues regarding regex engine. Standalone Mongo Server using PCRE(Perl compatible regular expressions) but Cosmos DB using ECMAScript based regex engine. So QueryDsl generated regex doesn't support in Cosmos due to incompatible syntax issues while running against Cosmos database.

**Solution Tried:**
1) Changed contains functions to matches but matches function is case sensitive. Need a case-insensitive search. MATCHES_IC operation available in predicate operation model but don't have an exposed API/Method for machesIgnoreCases. 
2) Don't have an option to combine the custom query with a predicate object.

**Solution Expected:**
1) Need an option for the case-insensitive search for Azure CosmosDB.
2) Any other way to achieve this from a custom query.

Please Refer below docs for reference:
[Azure Doc](https://feedback.azure.com/forums/263030-azure-cosmos-db/suggestions/32760031-support-q-and-e-escape-sequence-for-regex)
[MongoDB Doc](https://docs.mongodb.com/manual/reference/operator/query/regex/)

**Comment by idosal** [comment]
Looks like Azure is [on it](https://feedback.azure.com/forums/263030-azure-cosmos-db/suggestions/32760031-support-q-and-e-escape-sequence-for-regex).
