### ISSUE TITLE
Remove releases section from the site

### ISSUE THREAD

**Issue by dashorst** [querydsl/querydsl#2397]
The website for querydsl has a releases page that is seriously out of date. Only because I was fortunate enough to check the github repository I found that QueryDSL is alive and not dead since 2016.

Just link the releases to the github.com releases page and you're set to go.

**Comment by Shredder121** [comment]
Oh that is also possible.
I was (a long long while ago) busy with updating the DOM to be more semantically meaningful, but is it really worthy to throw the page away? 🤔

**Comment by jwgmeligmeyling** [comment]
The site has since been updated.
