### ISSUE TITLE
How can I get @ElementCollection values

### ISSUE THREAD

**Issue by ldwqh0** [querydsl/querydsl#2398]
This is my entity
```
@Entity
public class Person  {

     ... more

    @ElementCollection
    private Set<String> post;

}
```
and then ,I want to only get all distinct posts  in all Person entity.

How can I do it ?

wait online......

**Comment by jwgmeligmeyling** [comment]
You would use a join: `.from(QPerson.person).innerJoin(QPerson.person.post, QPost.post)`

**Comment by ldwqh0** [comment]
@jwgmeligmeyling
there is no QPost in my project

I see that jpql query is like this

"select distinct post from Person  p ,in (p.post) post".
but i do not know how to do it in querydsl
