### ISSUE TITLE
querydsl-jpa batch insert not work

### ISSUE THREAD

**Issue by linsage** [querydsl/querydsl#2402]
[querydsl-jpa]

```
@Id
@GeneratedValue(strategy = GenerationType.AUTO)
@Column(name = "id", nullable = false)
```
spring boot config
```
spring.jpa.properties.hibernate.jdbc.batch_size=100
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true
spring.jpa.properties.hibernate.generate_statistics=true
```
```
insert into ...
insert into ...
insert into ...
```
MySQL
save()
batch insert not working 

JPADeleteClause、JPAUpdateClause    **no  JPAInsertClause?**

**Comment by jwgmeligmeyling** [comment]
Batch insert does not work `@GeneratedValue(strategy = GenerationType.AUTO)`, as it requires a roundtrip to the database for each insert in order to generate the ID. You should use another identifier generation strategy.
