### ISSUE TITLE
How to construct a QueryDSL query between unrelated entities?

### ISSUE THREAD

**Issue by JadChahine** [querydsl/querydsl#2405]
I am trying to join two entities that are not related, I mean without using foreign keys as the column in the database is used to link to several tables.. so I cannot use foreign key constraint, hence the column will be as integer and not object in ORM.

I have two main tables

- TABLE2, contains ID, ...
- TABLE1, contains ID, nonforeignKeyColumn that should reference to TABLE2, ...

Below is the code that I am trying 

```
subQuery.select(TABLE1.ID).from(TABLE1)
	.join(TABLE2).on(TABLE1.nonforeignKeyColumn.eq(TABLE2.ID));

List<Predicate> predicates = new ArrayList<>();
predicates.add(TABLE3.TABLE1.ID.in(subQuery));

JPAQuery<TABLE3> query = new JPAQuery<>(em);
TABLE3 result =  query.from(TABLE3)
	.where(predicates.toArray(new Predicate[predicates.size()]))
	.orderBy(TABLE3.creationTimestamp.asc())
	.limit(1)
	.fetchFirst();
```

This piece of code is causing the error as I am linking the column to the object without using FK

`subQuery.select(TABLE1.ID).from(TABLE1)
	.join(TABLE2).on(TABLE1.nonforeignKeyColumn.eq(TABLE2.ID));
`

Error 

> java.lang.IllegalArgumentException: org.hibernate.hql.internal.ast.QuerySyntaxException: Path expected for join! 

What do you suggest? I cannot use queryDSL for joining two related entities?

**Comment by thackel** [comment]
JPA does not support unrelated joins and QueryDSL is tied to JPA when using ORM.

Also a nice blogpost by one of the hibernate developers:
https://vladmihalcea.com/how-to-join-unrelated-entities-with-jpa-and-hibernate/

**Comment by jwgmeligmeyling** [comment]
An unrelated join is also called an entity join which is actually supported in Hibernate 5.1 and above, as also indicated by the aforementioned blog post.

Which Hibernate version are you testing against?
