### ISSUE TITLE
Eclipse building workspace takes 30 seconds with QueryDSL after any file change

### ISSUE THREAD

**Issue by nbon12** [querydsl/querydsl#2406]
Hi,

I notice the QueryDSL-sql codegen plugin seems to slow my Eclipse "Building workspace" down. It used to take 1 second, but with querydsl it takes about 30 seconds. 
![building workspace](https://user-images.githubusercontent.com/17408265/51203142-4adf7980-18ce-11e9-95eb-4a822d69fa1e.png)

Every time I save a file in my Java application, I wait for Eclipse to build the workspace. It usually takes less than a second without QueryDSL. After I added QueryDSL-sql codegen into my POM, it now takes 30 seconds every time. For example, I created a JUnit hello world java class, and after I edit the file and "Save" it, it takes 30 seconds to build the workspace before the JUnit test will run.
![helloworld](https://user-images.githubusercontent.com/17408265/51202181-25517080-18cc-11e9-8040-986edf5d490a.png)

The below XML is what I added into my POM that causes this. if I edit the plugin out, my workspace builds in less than 1 second, however with the following plugin it takes 30 seconds:
`
 <plugin>
		        <groupId>com.querydsl</groupId>
		        <artifactId>querydsl-maven-plugin</artifactId>
		        <executions>
		          <execution>
		            <goals>
		              <goal>export</goal>
		            </goals>
		          </execution>
		        </executions>
		        <configuration>
		          <jdbcDriver>oracle.jdbc.OracleDriver</jdbcDriver>
		          <jdbcUrl>jdbc:oracle:thin:@//example.domain.com:1521/service_name_example</jdbcUrl>
		          <jdbcUser>example</jdbcUser>
		          <schemaPattern>example</schemaPattern>
		          <jdbcPassword>example</jdbcPassword>
		          <packageName>com.myproject.domain</packageName>
		          <targetFolder>${project.basedir}/target/generated-sources/java</targetFolder>
		        </configuration>
		        <dependencies>
		          <dependency>
				    <groupId>com.oracle</groupId>
				    <artifactId>ojdbc6</artifactId>
				    <version>11.2.0.3</version>
				  </dependency>
		        </dependencies>
		      </plugin>
`
Note the database that has several hundred tables with many foreign keys. Is there a way to specify less tables to load in? Or to disable some feature that's taking a long time?

**Comment by thackel** [comment]
Just move the QClass generation into an other maven project and depend on it so its not "rebuild" each time when you change something relevant in your current project.

The Mojo supports the "tableNamePattern" parameter which allows to specify table names maybe this helps to speed up the meta-data generation process.
Also you could create a database user for you which can only read the tables you want...
