### ISSUE TITLE
lower() and likeIgnoreCase() are unsupported for MongoDb

### ISSUE THREAD

**Issue by saveriopuccia** [querydsl/querydsl#2407]
I am using QueryDsl and MongoDb and I have an issue when I apply likeIgnoreCase or lower on a StringPath object. I get an  'java.lang.UnsupportedOperationException: Illegal operation lower' at MongoSerializer.visit(). It is my problem or is a known issue?

**Comment by frontng** [comment]
Is the problem solved?

**Comment by gaetan224** [comment]
Having the same problem

**Comment by kpundru** [comment]
Is the problem solved?

**Comment by spuccia** [comment]
I think that is not solved because @gaetan224 had the same problem two months ago. There are workaround that we can use, so if you want to close the issue you can do.

**Comment by spuccia** [comment]
I think that is not solved because @gaetan224 had the same problem two months ago. There are workaround that we can use, so if you want to close the issue you can do.

**Comment by saveriopuccia** [comment]
I think that is not solved because @gaetan224 had the same problem two months ago. There are workaround that we can use.
