### ISSUE TITLE
javax.inject dependency triggering compiler warnings

### ISSUE THREAD

**Issue by cowwoc** [querydsl/querydsl#2408]
When compiling code that depends on querydsl I get the following warning:

`[WARNING] Can't extract module name from org.apache.servicemix.bundles.javax-inject-1_2.jar: org.apache.servicemix.bundles.javax.inject.1.2: Invalid module name: '1' is not a Java identifier`

See https://github.com/javax-inject/javax-inject/issues/33 for a related discussion

**Comment by jwgmeligmeyling** [comment]
This dependency is now removed.
