### ISSUE TITLE
Java9+ support

### ISSUE THREAD

**Issue by cowwoc** [querydsl/querydsl#2409]
I know you guys are probably far away from requiring Java9+ but at the very least let's make this library compatible with it.

Please add `Automatic-Module-Name` to the manifest file of all querydsl artifacts.

See http://branchandbound.net/blog/java/2017/12/automatic-module-name/ for a related discussion.

**Comment by jwgmeligmeyling** [comment]
QueryDSL has always supported Java 9+ in classpath mode. The generated classes however used a `@Generated` annotation that was removed in Java 9. QueryDSL now decides which annotation to use based on the JDK and configuration.


The `Automatic-Module-Name` helps using Java 9 in module mode. I've fixed this in https://github.com/querydsl/querydsl/pull/2727.  Keep in mind that it is not sufficient to run Java 9 through `jlink`. Although we've experimented with real world usecases for QueryDSL with `jlink`, these experiments got stuck at various dependencies not declaring the proper modules yet.
