### ISSUE TITLE
how to use rescursive and ||

### ISSUE THREAD

**Issue by dianfenzhan** [querydsl/querydsl#2430]
with RECURSIVE T(dept_id,dept_name,parent_dept_id,path,depth) as(
  select dept_id,dept_name,parent_dept_id,Array[dept_id] as path,1 as depth from department
      where dept_id=1
               union all
     select d.dept_id,d.dept_name,d.parent_dept_id,t.path||d.dept_id as path,t.depth+1 as depth
               from department d join t on d.parent_dept_id = T.dept_id

)select dept_id,dept_name,parent_dept_id,path,depth from T

**Comment by jwgmeligmeyling** [comment]
With recursive:

```java
 query.withRecursive(sub, sub.get(e.id), sub.get(e.firstname), sub.get(e.superiorId)).as(
                unionAll(
                        select(e.id, e.firstname, e.superiorId).from(e).where(e.firstname.eq("Mike")),
                        select(e.id, e.firstname, e.superiorId).from(e, sub).where(e.superiorId.eq(sub.get(e.id)))))
             .from(sub);
```

Mind, this will only work in `querydsl-sql`, as JPQL does not support CTE's.

`t.path||d.dept_id` should just be a matter of `t.path.concat(d.deptId)`, or possibily with the required String casts: `Expressions.stringOperation(Ops.CAST_STRING, t.path).concat(Expressions.stringOperation(Ops.CAST_STRINGd.deptId))`
