### ISSUE TITLE
Compare BigInteger to BigDecimal

### ISSUE THREAD

**Issue by TribuneX** [querydsl/querydsl#2431]
I am trying to implement an equal expression, with two colums. One is BigInteger, the other one is a BigDecimal. 

Is there a proper way in querdsl to compare a BigInteger with a BigDecimal with an equal expression?

Something like does not work obviously:

```
queryFactory.select(qItemA)
	.from(qItemA)
	.where(qItemA.biginteger_column.eq(qItemB.bigdecimal_colum))
```

**Comment by jwgmeligmeyling** [comment]
Yes, by casting the BigInteger to a BigDecimal or the other way around.

Or just use an untyped equality expression: `Expressions.predicate(Ops.EQ, qItemA.biginteger_column, qItemB.bigdecimal_colum)`
