### ISSUE TITLE
Update Morphia version from 1.3.2 to 1.4.0

### ISSUE THREAD

**Issue by robertoclavijob** [querydsl/querydsl#2433]
**Expected Result**
Use Morphia version 1.4.0, in that release the package was changed from org.mongodb.morphia to xyz.morphia.morphia
https://github.com/MorphiaOrg/morphia/releases/tag/r1.4.0

**Actual Result**
Morphia version 1.3.2 is used

**Comment by ft0907** [comment]
Give a small suggestion: I hope that the Morphia scope provided is canceled, because our introduction is generally used at compile time. If we follow the current practice, we need to introduce morphia extra. I think this is not necessary.

**Comment by jwgmeligmeyling** [comment]
They have since moved to yet another group id `dev.morphia.morphia:core`. Do people still use this?

**Comment by zenbones** [comment]
I do and I'd like to upgrade to morphia 2.2.2 or later

**Comment by jwgmeligmeyling** [comment]
So with Morphia switching group ids and package names three times, there is no way we can preserve backwards compatibele other than provide separate modules for all three versions.

I will accept PRs introducing modules that target newer versions of Morphia in a non breaking way. Its yet unclear for me which version(s) we should aim for.

**Comment by zenbones** [comment]
The old morphia (1.3.2 and earlier, maybe as far as 1.5) is a dead project. The code has been contributed and moved, through whatever the middle project is, to its current destination at dev.morphia.morphia:core, which is where you should aim. Not sure how you make this a non-breaking change, but leaving it where it is leaves everyone who might want to use it stranded from the evolving project. I think you need some breaking change. I would suggest a service based approach with different maven artifacts presenting different versions of the service, querydsl-morphia-1.x, querydsl-morphia-2.x, if you really want to provide some backward compatability.
