### ISSUE TITLE
How to use custom fields to achieve distinct?

### ISSUE THREAD

**Issue by zuoxuanrui** [querydsl/querydsl#2435]
Hello, in version 4.1.4 querydsl-jpa,Full field query, I want to use custom fields to achieve distinct , but I have not found this method, how to use it? Thank you.

`jpaQueryFactory.select(contentMonitorDO).from(contentMonitorDO).distinct().
                where(predicate).fetch();`

distinct method no parameters

**Comment by thackel** [comment]
`
jpaQueryFactory.from(contentMonitorDO).where(predicate).distinct().select(contentMonitorDO.field).fetch()
`

**Comment by zuoxuanrui** [comment]
Thank you for your reply. It's already available.
