### ISSUE TITLE
UUID contains with ignore case

### ISSUE THREAD

**Issue by mantoshelis** [querydsl/querydsl#2436]
It seems like there is no ability to search UUID type with `contains` or `containsIgnoreCase` query. From database perspective it is possible to do that in Postgres after casting `uuid` to `varchar` and then doing `LIKE` query. What about adding this to QueryDSL?

**Comment by alexandr-efimov** [comment]
Any information on it?

**Comment by jwgmeligmeyling** [comment]
`Expressions.stringOperation(Ops.CAST_STRING, uuid).containsIgnoreCase("....")`
