### ISSUE TITLE
0..n result transformation with offset and limit produces inaccurate results

### ISSUE THREAD

**Issue by wiecia** [querydsl/querydsl#2437]
I've searched for proper answer but unfortunately did't find any working solution for QueryDsl SQL module.
I'm trying to fetch simple entities with 0..n relation using left join on custom property:
```java
class Parent {
    private Long id;
    private String uuid;
    private Set<Child> children;
}
class Child {
    private Long id;
    private String uuidRef;
}
```
To be able to populate dto's I'm transforming results as follows:
```java
queryFactory().from(qParent)
    .leftJoin(qChild).on(qParent.uuid.eq(qChild.uuidRef))
    .where(...)
    .transform(GroupBy.groupBy(qParent.id).list(parentQBean))
```
There are Parent rows having multiple Child relations.
Everything works fine unless I add additional limit and offset to the query for pagination pupropses. Let's day I want first 20 results so I'm adding .offset(0).limit(20).

In db there are 2 parent records having 2 child rows each. After transformig/grouping I only get 18 rows/objects as a result. I'm aware that this is due to SQL query itself as it returns left joined rows as separate result row and transforming is done in memory, but I wonder if this is possible to handle on SQL module somehow. I don't want to use JPA as this is rather small project with only few tables and JPA/Hibernate would be overkill. SQL module is perfect for this :)

Using QueryDsl SQL 4.2.1 with PostgreSQL 11.2

**Comment by thackel** [comment]
Why do you group after the retrieval and not in the database (result transformation vs 'real' groupBy)?
```
queryFactory().from(qParent)
    .leftJoin(qChild).on(qParent.uuid.eq(qChild.uuidRef))
    .where(...)
    .groupBy(qParent.id).select(otherProjectionTarget)).fetch()
```

**Comment by wiecia** [comment]
How can you then write the query that populates each Parent with it's Child collections without need to specify each and every Parent and Child properties in groupBY clause (and there can be lot of other properties)?

**Comment by dongshengYoung** [comment]
I have the same problem as you have！I have an alternative for you。

```
//find parents' ids of target page
//do pagination at this step
List<Long> parentIds = queryFactory().from(qParent).where(...)
    .offset(0).limit(20).select(qParent.id).fetch();

//find all row data belong to these parents, then do aggregation
//notic this query condition
list<parentQBean> parents = queryFactory().from(qParent)
    .leftJoin(qChild).on(qParent.uuid.eq(qChild.uuidRef))
    .where(qParent.id.in(parentIds))                              
    .transform(GroupBy.groupBy(qParent.id).list(parentQBean))
```

this is how I solve this problem.

>  I'm aware that this is due to SQL query itself as it returns left joined rows as separate result row and transforming is done in memory

there seems no way to do aggregation first, then do pagination.  imagine you have 1 million rows, 
would you do aggregation first?

**Comment by wiecia** [comment]
Thanks @dongshengYoung - this seems like a very reasonable solution

**Comment by Little0Sheep** [comment]
my method
`        //paging query
        long startPage=1;
        long pageSize=1;
        Long totalCount=jpaQueryFactory
                .from(qtUserEntity,qtPostEntity,qtDeptEntity)
                .where(
                        qtUserEntity.id.eq(qtPostEntity.userId),
                        qtUserEntity.deptId.eq(qtDeptEntity.id),
                        qtUserEntity.userName.like("%123%")
                ).fetchCount();
        if(totalCount<=startPage*pageSize && startPage>0){
            startPage= 0;
            pageSize=1;
        }

        List<LoginUserVo> loginUserVoList=jpaQueryFactory
                .select(qtUserEntity,qtPostEntity,qtDeptEntity)
                .from(qtUserEntity,qtPostEntity,qtDeptEntity)
                .where(
                        qtUserEntity.id.eq(qtPostEntity.userId),
                        qtUserEntity.deptId.eq(qtDeptEntity.id),
                        qtUserEntity.userName.like("%123%")
                )
                .offset(startPage)
                .limit(pageSize)
                .transform(GroupBy.groupBy(qtUserEntity.id)
                        .list(
                                Projections.bean(
                                        LoginUserVo.class,
                                        qtUserEntity.id,
                                        qtUserEntity.userName,
                                        qtUserEntity.userPswd,
                                        Projections.bean(
                                                DeptVo.class,
                                                fields
                                        ).as("deptVo"),
                                        GroupBy.set(
                                                Projections.bean(
                                                        PostVo.class,
                                                        qtPostEntity.id,
                                                        qtPostEntity.postName
                                                )
                                        ).as("postVoSet")
                                )
                        ));`

**Comment by jwgmeligmeyling** [comment]
@dongshengYoung posted the correct solution in his comment https://github.com/querydsl/querydsl/issues/2437#issuecomment-505701079

**Comment by Little0Sheep** [comment]
> I have the same problem as you have！I have an alternative for you。
> 
> ```
> //find parents' ids of target page
> //do pagination at this step
> List<Long> parentIds = queryFactory().from(qParent).where(...)
>     .offset(0).limit(20).select(qParent.id).fetch();
> 
> //find all row data belong to these parents, then do aggregation
> //notic this query condition
> list<parentQBean> parents = queryFactory().from(qParent)
>     .leftJoin(qChild).on(qParent.uuid.eq(qChild.uuidRef))
>     .where(qParent.id.in(parentIds))                              
>     .transform(GroupBy.groupBy(qParent.id).list(parentQBean))
> ```
> 
> this is how I solve this problem.
> 
> > I'm aware that this is due to SQL query itself as it returns left joined rows as separate result row and transforming is done in memory
> 
> there seems no way to do aggregation first, then do pagination. imagine you have 1 million rows,
> would you do aggregation first?

why in error
[https://github.com/querydsl/querydsl/issues/2624](url)
