### ISSUE TITLE
How to use `Querydsl` in the `spring-boot-starter-data-elasticsearch` project,

### ISSUE THREAD

**Issue by BoomManPro** [querydsl/querydsl#2442]
How to use `Querydsl` in the `spring-boot-starter-data-elasticsearch` project, example：
https://docs.spring.io/spring-data/elasticsearch/docs/2.1.11.RELEASE/reference/html/#core.extensions.querydsl

**Comment by ft0907** [comment]
暂时不支持。

**Comment by BoomManPro** [comment]
@ft0907 thanks
