### ISSUE TITLE
How to both use `Querydsl` and `lombok` with gradle? 

### ISSUE THREAD

**Issue by LilithBristol** [querydsl/querydsl#2444]
----------
java 11
gradle 5.4
idea 2018.3
--------

This is my gradle config

```java

plugins {
    id 'java'
    id 'idea'
    id "com.ewerk.gradle.plugins.querydsl" version "1.0.10"
    id "org.springframework.boot" version "2.1.4.RELEASE"
    id "io.franzbecker.gradle-lombok" version "3.0.0"
    id 'io.spring.dependency-management' version "1.0.7.RELEASE"
}

group 'cn.org.cczr'
version '1.0-SNAPSHOT'
//apply plugin: 'io.spring.dependency-management'

sourceCompatibility = 11
targetCompatibility = 11

sourceSets {
    main {
        java {
            srcDir "$buildDir/generated/source/main"
        }
    }
}

compileQuerydsl {
    options.annotationProcessorPath = configurations.querydsl
}

querydsl {
    jpa = true
    querydslSourcesDir = "$buildDir/generated/source/main"
}

project.afterEvaluate {
    project.tasks.compileQuerydsl.options.compilerArgs = [
            "-proc:only",
            "-processor", project.querydsl.processors() +
                    ',lombok.launch.AnnotationProcessorHider$AnnotationProcessor'
    ]
}

repositories {
    mavenLocal()
    mavenCentral()
    jcenter()
}

dependencies {
    implementation('org.springframework.boot:spring-boot-starter-web')
    implementation('org.springframework.boot:spring-boot-starter-data-jpa')

    implementation "com.querydsl:querydsl-jpa" // querydsl
    implementation "com.querydsl:querydsl-apt"  // querydsl
    implementation("org.projectlombok:lombok:1.18.6")

    annotationProcessor(
            "com.querydsl:querydsl-apt:4.1.4:jpa",
            "org.hibernate.javax.persistence:hibernate-jpa-2.1-api:1.0.2.Final",
            "javax.annotation:javax.annotation-api",
            "org.projectlombok:lombok:1.18.6"
    )

    testImplementation('org.springframework.boot:spring-boot-starter-test')
    testImplementation group: 'junit', name: 'junit', version: '4.12'
    testImplementation("org.projectlombok:lombok:1.18.6")
    testAnnotationProcessor("org.projectlombok:lombok:1.18.6")
}

```
then when i use gradle build 

it report error 
**Execution failed for task ':compileQuerydsl'.**
**Annotation processor 'lombok.launch.AnnotationProcessorHider$AnnotationProcessor' not found**

if i delete the lombok dependcies ,the querydsl even not work normal ，
it report error
**can't find find symbol and the package don't exist**

so how can i both use `Querydsl` and `lombok` with gradle? 

and i think use querydsl with gradle is so difficulty，you must config so many option，
just like

```java
sourceSets {
    main {
        java {
            srcDir "$buildDir/generated/source/main"
        }
    }
}

compileQuerydsl {
    options.annotationProcessorPath = configurations.querydsl
}

querydsl {
    jpa = true
    querydslSourcesDir = "$buildDir/generated/source/main"
}

project.afterEvaluate {
    project.tasks.compileQuerydsl.options.compilerArgs = [
            "-proc:only",
            "-processor", project.querydsl.processors() +
                    ',lombok.launch.AnnotationProcessorHider$AnnotationProcessor'
    ]
}

```
compare with maven config,it's too troublesome.
Is there a easier way?

**Comment by IdoSalomon** [comment]
This worked for me (only querydsl-related lines are shown for brevity):
`buildscript {
    ext {
        springBootVersion = '2.1.3.RELEASE'
        queryDslVersion = '4.2.1'
    }
}

plugins {
    id 'idea'
}

idea {
    module {
        sourceDirs += file('generated/')
        generatedSourceDirs += file('generated/')
    }
}

dependencies {
    // QueryDSL
    compile("com.querydsl:querydsl-core:${queryDslVersion}")
    compileOnly "com.querydsl:querydsl-jpa:${queryDslVersion}"
    annotationProcessor("com.querydsl:querydsl-apt:${queryDslVersion}:jpa")
    implementation("com.querydsl:querydsl-jpa:${queryDslVersion}")

    // Lombok
    compileOnly "org.projectlombok:lombok:${lombokVersion}"
    annotationProcessor "org.projectlombok:lombok:${lombokVersion}"
    implementation("org.projectlombok:lombok:${lombokVersion}")
}
`

Emphasis is on compileOnly for both lombok and querydsl.

I hope it helps. :)

**Comment by sema4-oleksiisanak** [comment]
@IdoSalomon pls see another solution [](https://github.com/ewerk/gradle-plugins/issues/39#issuecomment-197308241)

**Comment by LilithBristol** [comment]
> This worked for me (only querydsl-related lines are shown for brevity):
> 
> ```
> buildscript {
>     ext {
>         springBootVersion = '2.1.3.RELEASE'
>         queryDslVersion = '4.2.1'
>     }
> }
> 
> plugins {
>     id 'idea'
> }
> 
> idea {
>     module {
>         sourceDirs += file('generated/')
>         generatedSourceDirs += file('generated/')
>     }
> }
> 
> dependencies {
>     // QueryDSL
>     compile("com.querydsl:querydsl-core:${queryDslVersion}")
>     compileOnly "com.querydsl:querydsl-jpa:${queryDslVersion}"
>     annotationProcessor("com.querydsl:querydsl-apt:${queryDslVersion}:jpa")
>     implementation("com.querydsl:querydsl-jpa:${queryDslVersion}")
> 
>     // Lombok
>     compileOnly "org.projectlombok:lombok:${lombokVersion}"
>     annotationProcessor "org.projectlombok:lombok:${lombokVersion}"
>     implementation("org.projectlombok:lombok:${lombokVersion}")
> }
> ```
> 
> Emphasis is on compileOnly for both lombok and querydsl.
> 
> I hope it helps. :)

Thanks for you help,
yours config can work well

i think ,it is crucial that both use "compileOnly" and "annotationProcessor "
and appoint the sourcedir .

the querydsl gradle plugin is unnecessary .because it's can't work with java 11 and gradle 5.0.

**Comment by minhanhhere** [comment]
Hi @IdoSalomon,
I use your build.gradle and upgrade it with mongodb version.
But I don't know how to make it generate the QueryDSL.
java 11
gradle 5.4
idea 2018.3


`
buildscript {
	ext {
		springBootVersion = '2.1.4.RELEASE'
		queryDslVersion = '4.2.1'
	}
}

plugins {
	id 'idea'
	id 'org.springframework.boot' version '2.1.4.RELEASE'
	id 'java'
}

apply plugin: 'io.spring.dependency-management'

idea {
	module {
		sourceDirs += file('generated/')
		generatedSourceDirs += file('generated/')
	}
}

group = 'com.api'
version = '0.0.1-SNAPSHOT'
sourceCompatibility = '11'

repositories {
	jcenter()
	mavenCentral()
}

dependencies {

	implementation 'io.jsonwebtoken:jjwt-api:0.10.5'
	implementation 'io.jsonwebtoken:jjwt-jackson:0.10.5'
	implementation 'com.google.firebase:firebase-admin:6.8.0'
	implementation 'org.springframework.boot:spring-boot-starter-data-mongodb:2.1.4.RELEASE'
	implementation 'org.springframework.boot:spring-boot-starter-web:2.1.4.RELEASE'
	implementation 'org.springframework.boot:spring-boot-starter-security:2.1.4.RELEASE'
	implementation 'org.springframework.boot:spring-boot-starter-oauth2-client:2.1.4.RELEASE'
	implementation 'org.springframework.boot:spring-boot-starter-oauth2-resource-server:2.1.4.RELEASE'
	implementation 'org.springframework.security.oauth.boot:spring-security-oauth2-autoconfigure:2.1.4.RELEASE'

	// QueryDSL
	compile("com.querydsl:querydsl-core:${queryDslVersion}")
	compileOnly "com.querydsl:querydsl-mongodb:${queryDslVersion}"
	annotationProcessor("com.querydsl:querydsl-apt:${queryDslVersion}:morphia")
	implementation("com.querydsl:querydsl-mongodb:${queryDslVersion}")

	compileOnly 'org.projectlombok:lombok:1.18.6'
	annotationProcessor 'org.projectlombok:lombok:1.18.6'

	runtimeOnly 'org.springframework.boot:spring-boot-devtools:2.1.4.RELEASE'

	runtime 'io.jsonwebtoken:jjwt-impl:0.10.5'

	testImplementation 'org.springframework.boot:spring-boot-starter-test'
}


`

**Comment by noSleepOwl** [comment]
so hard!!!!

**Comment by isaaclcl** [comment]
I'm getting a error msg:

* What went wrong:
Execution failed for task ':compileJava'.
> java.lang.NoClassDefFoundError: javax/persistence/Entity

Any tips?

**Comment by IdoSalomon** [comment]
@isaaclcl You seem to miss the annotation processor for it (e.g 'org.springframework.boot:spring-boot-starter-data-jpa'). You might be overriding it in your attempts to add querydsl. You can try explicitly defining all three:

```
dependencies {
    // For javax/persistence/Entity
    **annotationProcessor("org.springframework.boot:spring-boot-starter-data-jpa:${springBootVersion}")**

    // QueryDSL
    compile "com.querydsl:querydsl-jpa:${queryDslVersion}"
    **annotationProcessor("com.querydsl:querydsl-apt:${queryDslVersion}:jpa")**

    // Lombok
    compileOnly "org.projectlombok:lombok:${lombokVersion}"
    **annotationProcessor "org.projectlombok:lombok:${lombokVersion}"**
}
```

**Comment by LilithBristol** [comment]
After several mouths , i find a perfect method to solve this question.

First , don't use plugin 'com.ewerk.gradle.plugins.querydsl', it's  deprecated ,not complie with gradle 5.0+.

You must use plugin 'java-library'  ,this is a gradle core plugin which maintenance by gradle officer,so you don't need worry it will deprecated .


For more information about java-library.you can see it [https://docs.gradle.org/current/userguide/java_library_plugin.html](url)

That's my config

```java

plugins{
    id 'java-library'
}

dependencies {
    api(
            "com.querydsl:querydsl-jpa:4.2.1",
    )

    implementation(
            platform("org.springframework.boot:spring-boot-dependencies:$springBootVersion"),
            ......
    )
    annotationProcessor(
            platform("org.springframework.boot:spring-boot-dependencies:$springBootVersion"),
            "javax.persistence:javax.persistence-api",
            "javax.annotation:javax.annotation-api",
            "com.querydsl:querydsl-apt:4.2.1:jpa"
    )
    runtimeOnly 'org.springframework.boot:spring-boot-devtools'
    runtimeOnly 'mysql:mysql-connector-java'
}

jar {
    manifest {
        attributes(
                "Manifest-Version":"1.0",
                "Main-Class": "tv.acgn.advertisment.publish.PublishApplication"
        )
    }

    archiveBaseName ='ad-publish'
    version = '1.0.0.-SNAPSHOT'
}
```

the crucial is two attribute in dependencies task: api 、annotationProcessor

you must use "com.querydsl:querydsl-jpa:4.2.1" in **api**
and         
"javax.persistence:javax.persistence-api",
            
"javax.annotation:javax.annotation-api",
          
  "com.querydsl:querydsl-apt:4.2.1:jpa"
in **annotationProcessor**

like this:
```

dependencies {
    api(
            "com.querydsl:querydsl-jpa:4.2.1",
    )

   .......
    annotationProcessor(
            platform("org.springframework.boot:spring-boot-dependencies:$springBootVersion"),
            "javax.persistence:javax.persistence-api",
            "javax.annotation:javax.annotation-api",
            "com.querydsl:querydsl-apt:4.2.1:jpa"
    )

}


```
'javax.* ' need not point out version if you both dependies 'springdatajpa' or hibernate,
because of  these two 'javax.* '  has clear version and  import by springdatajpa/hibernate.

Usually now you can correctly both use querydsl and spring-data-jpa，
but i find sometime  the project even report error:can't find symbol when you go build project and project use the querydsl generated 'Q-Class',
if this situation happen ，you can appoint the source dir to solve it.

```java

sourceSets {
    main {
        java {
            srcDirs = ["$projectDir/src/main/java", "$projectDir/build/generated"]
        }
    }
}

```

**Comment by isaaclcl** [comment]
It works like a magic.
 **annotationProcessor("org.springframework.boot:spring-boot-starter-data-jpa:${springBootVersion}")**

Thanks for the reply, you guys are awesome.

> 
> 
> @isaaclcl You seem to miss the annotation processor for it. You might be overriding it in your attempts to add querydsl. You can try explicitly defining all three:
> 
> ```
> dependencies {
>     // For javax/persistence/Entity
>     **annotationProcessor("org.springframework.boot:spring-boot-starter-data-jpa:${springBootVersion}")**
> 
>     // QueryDSL
>     compile "com.querydsl:querydsl-jpa:${queryDslVersion}"
>     **annotationProcessor("com.querydsl:querydsl-apt:${queryDslVersion}:jpa")**
> 
>     // Lombok
>     compileOnly "org.projectlombok:lombok:${lombokVersion}"
>     **annotationProcessor "org.projectlombok:lombok:${lombokVersion}"**
> }
> ```
> 
> Let me know if you need further assistance.

**Comment by idosal** [comment]
Annotation processor issue is related to https://github.com/querydsl/querydsl/issues/2522.

**Comment by marcusadrian** [comment]
I think the preferred way whatever it is should be indicated in the official querydsl doc as this is the case with maven and ant integration. gradle seems to  me far more relevant nowadays than ant is...

**Comment by alexcg1986** [comment]
THANK YOU, like seriously, I've been struggling to make this ******* library work for hours and I couldn't find any working solution until I tried yours. In my case only the lines with "// QueryDSL must have" were needed, the rest are just dependencies given by the Spring Boot Initializr builder itself, but I leave them just as a reference for anybody facing the same problems. The Initializr added everything I needed related to Lombok so no extra dependencies were required for me.

`plugins {
	id 'org.springframework.boot' version '2.4.3'
	id 'io.spring.dependency-management' version '1.0.11.RELEASE'
	id 'java'
	id 'war'
	id 'java-library' // QueryDSL must have
} 

group = 'com.restaurant'
version = '0.0.1-SNAPSHOT'
sourceCompatibility = '1.8'

configurations {
	compileOnly {
		extendsFrom annotationProcessor
	}
}

repositories {
	mavenCentral()
}

dependencies {
	api 'com.querydsl:querydsl-jpa:4.4.0' // QueryDSL must have

	implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
	implementation 'org.springframework.boot:spring-boot-starter-hateoas'
	implementation 'org.springframework.boot:spring-boot-starter-jdbc'
	implementation 'org.springframework.boot:spring-boot-starter-thymeleaf'
	implementation 'org.springframework.boot:spring-boot-starter-web'
	implementation 'org.projectlombok:lombok'

	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	
	annotationProcessor 'org.projectlombok:lombok'
	annotationProcessor 'com.querydsl:querydsl-apt:4.4.0:jpa' // QueryDSL must have (exactly this way, including :jpa)
	annotationProcessor 'javax.annotation:javax.annotation-api' // QueryDSL must have
	// annotationProcessor 'javax.persistence:javax.persistence-api'

	developmentOnly 'org.springframework.boot:spring-boot-devtools'

	runtimeOnly 'mysql:mysql-connector-java'
	providedRuntime 'org.springframework.boot:spring-boot-starter-tomcat'
}

test {
	useJUnitPlatform()
}`

**Comment by spajicstefan** [comment]
Hello everyone, i have different issue. Al my Q classes are generated but compileJava can't see them:
`error: cannot find symbol`
I tried everything, setting sourceSets, idea.module etc, still can't make gradle see those files ?
