### ISSUE TITLE
ClassCastException while using withRecursive

### ISSUE THREAD

**Issue by andre-stefanov** [querydsl/querydsl#2447]
Hello, 

I am having troubles getting values generated by a recursive function:

```
    public List<Long> recursion() {
        NumberPath<Long> n = numberPath(Long.class, "n");
        Path<Long> f = new PathBuilder<>(Long.class, "rec");

        JPASQLQuery<Long> query = query().withRecursive(f, new NumberPath[]{n})
            .as(query().unionAll(
                query().select(Expressions.asNumber(0L).as(n)),
                query().select(n.add(1L).as(n)).from(f).where(n.lt(10L))
            ))
            .select(n.longValue())
            .from(f);

        return query.fetch();
    }
```
This results in a ClassCastException:
`java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Number`

[Official MySQL documentation](https://dev.mysql.com/doc/refman/8.0/en/with.html) states:
```
The types of the CTE result columns are inferred from the column types of the nonrecursive SELECT part only, and the columns are all nullable. For type determination, the recursive SELECT part is ignored.
```
So in my understanding the Expressions.asNumber should be actually enough to tell querydsl that the column will be of the type number and not string.

Did I miss something or is there an issue with the `withRecursive` implementation?

**Comment by andre-stefanov** [comment]
After several evenings figured out that the actual issue was my dev db (H2). [H2 docs ](http://www.h2database.com/html/advanced.html#recursive_queries)state:

_All columns of the table expression are of type VARCHAR, and may need to be cast to the required data type._

Meaning i have to use `n.castToNum(Long.class)` in order to get results as List<Long> correctly.

**Comment by andre-stefanov** [comment]
But now i have a question about querydsl itself ... maybe querydsl should make this cast implicitelly since it knows about the required column types in withRecursive statement?

**Comment by jwgmeligmeyling** [comment]
> But now i have a question about querydsl itself ... maybe querydsl should make this cast implicitelly since it knows about the required column types in withRecursive statement? 

QueryDSL doesn't necessarily knows that this cast is required, because it is database dialect dependent. In most dialects such a cast is not necessary.

QueryDSL expressions transparently serialise to plain queries. If the query needs a cast, you will need to use a cast expression.

Perhaps the conclusion is that omitting the cast when we _think_ its unnecessary a premature optimisation.
