### ISSUE TITLE
querydsl is abandoned. It's time to fork.

### ISSUE THREAD

**Issue by robertandrewbain** [querydsl/querydsl#2456]
There are numerous posts about the status of querydsl. I dipped in from time to time as a contributor but full-time job/ life/ etc. meant I couldn't offer much. The project is now stagnant. In its current state, *it is dead*. We use it extensively in our codebase. querydsl is a great library. Let's move forward. My thoughts are in this SO post: https://stackoverflow.com/questions/55668960/whats-the-latest-status-of-querydsl/56029689#56029689

I propose that we use this issue to focus on a common fork. Who is in? I think querydsl-sql and querydsl-jpa would be a good start. Java version upgrade, dependency reduction, trim the fat.

**Comment by IdoSalomon** [comment]
Querydsl is awesome. I might be able to contribute (either in this repo or a fork).

**Comment by NiklasMehner** [comment]
Is anybody in contact wiht Timo? Getting him to appoint new maintainers would perhaps be better than forking.

**Comment by mrjavascript** [comment]
querydsl is wonderful.  I would love to see this project actively developed, and I have been fighting urges to switch over to jOOQ in hopes this project is brought back to life.

**Comment by robertandrewbain** [comment]
> Is anybody in contact wiht Timo? Getting him to appoint new maintainers would perhaps be better than forking.

@NiklasMehner I totally agree. I've emailed him with your suggestion. Hopefully, he gets back to us.

**Comment by robertandrewbain** [comment]
I've been in touch with Timo, he's happy to hand the project over. I'm going to close this and create a new issue stating that and see if we can get a team in place.
