### ISSUE TITLE
Improvement: @Generated annotation to mark code that should be ignored by JaCoCo

### ISSUE THREAD

**Issue by akayoshi29** [querydsl/querydsl#2460]
Hi,
It would be nice to have an "@Generated" annotation with class retention policy that can be ignored by code coverage tools like [JaCoCo](https://www.jacoco.org/jacoco/). This should work similar to how it's done for [Immutables](https://github.com/jacoco/jacoco/issues/656) and [Lombok](https://github.com/jacoco/jacoco/pull/495).
Thanks in advanced.

**Comment by niclarcipretti** [comment]
@akayoshi29 I guess you could just mark the entire generated folder as an exclusion to jacoco. In gradle it will look like this:

```
<build.gradle>
...
jacocoTestReport {
	afterEvaluate {
		classDirectories.from = files(classDirectories.files.collect {
			fileTree(dir: it,
			exclude: [
				"com/myapp/genDir/**",
				"com/myapp/someOtherexclusion/**"
			])
		})
	}
}
...
```

Cheers

Nikao

**Comment by akayoshi29** [comment]
@niclarcipretti Thanks for your response but JaCoCo analyzes only the bytecode. If I do what you say, I exclude tests for abstract or default methods. I don't want to exclude them, I want to exclude only generated code.

**Comment by niclarcipretti** [comment]
Hi @akayoshi29,

Querydsl generates whole classes. So, you shouldn't have any non generated code within it imo. Making them the perfect candidates for jacocos exclusions. Can you elaborate a little more with some examples, if you disagree?

Cheers

**Comment by akayoshi29** [comment]
@niclarcipretti Yes, QueryDsl generate the whole class but it is in the same directory of the interface or abstract class in the bytecode.

For example : 
- files project :
-- src/main/java/org/example/querydsl/Object.java
-- target/generated-sources/org/example/querydsl/Qobject.java
- bytecode :
-- target/classes/org/example/querydsl/Object.java
-- target/classes/org/example/querydsl/Qobject.java
So, if I exclude "org/example/querydsl/**", I exclude the Object.java but I want to keep it. 

I can exclude "org/example/querydsl/Q*" but if  I have different folders which use QueryDsl, I have to do this for all of these and they must not have object start with Q. 
I prefer a generic solution like Lombok. With Lombok, I use the default behavior of JaCoCo : 
- Lombok behavior : add only a file "lombok.config" in the project  with the value "lombok.addLombokGeneratedAnnotation = true" which generate their own @Generated tag in bytecode
- JaCoco behavior : check Lombok tag to ignore all methods and classes generated by Lombok.

Cheers

**Comment by niclarcipretti** [comment]
@akayoshi29 in this use case, you're right.

Usually, we separate entity mapping classes in a specific package and add this package to exclusions, once you don't need  code coverage in entity classes.

Best of luck

Nikao

**Comment by NaixSpirit** [comment]
@akayoshi29 I found the same problem, then I found the solution in the [documentation](http://www.querydsl.com/static/querydsl/4.1.3/reference/html_single/#d0e2276), you can set an option `querydsl.packageSuffix` in your pom.xml or build.gradle.

for example, in my pom.xml 
```xml
<plugin>
  <groupId>com.mysema.maven</groupId>
  <artifactId>apt-maven-plugin</artifactId>
  <version>1.1.3</version>
  <executions>
    <execution>
      <goals>
        <goal>process</goal>
      </goals>
      <configuration>
        <outputDirectory>target/generated-sources/java</outputDirectory>
        <processor>com.querydsl.apt.jpa.JPAAnnotationProcessor</processor>
        <options>
          <!-- set the generated-sources package suffix-->
          <querydsl.packageSuffix>.querydsl</querydsl.packageSuffix>
        </options>
      </configuration>
    </execution>
  </executions>
</plugin>
```
and then, the files project:
- -- src/main/java/org/example/domain/object.java
- -- target/generated-sources/org/example/domain/querydsl/Qobject.java

you can ignore the **querydsl** package in your test coverage config

**Comment by akayoshi29** [comment]
Thank you @NaixSpirit.
I would have preferred the annotation in the bytcode but it's a good alternative.
Thanks again.

**Comment by idosal** [comment]
Sounds reasonable to me. If anyone would like to contribute this change I think we can merge it.

**Comment by rob-valor** [comment]
I have a pull request for this. https://github.com/querydsl/querydsl/pull/2657
