### ISSUE TITLE
ARRAY is now a keyword in MySQL

### ISSUE THREAD

**Issue by lukelalo** [querydsl/querydsl#2464]
The word 'array' is now a keyword in mysql from version 8.0.17. It needs to be escaped

Regards
Pablo García

**Comment by jwgmeligmeyling** [comment]
Where exactly does it need to be escaped? We don't escape anywhere?

**Comment by jwgmeligmeyling** [comment]
`ARRAY` was added in 8.0.17 (reserved); became nonreserved in 8.0.19. It seems we only treat reserved keywords, so I am not sure if this is still an issue: https://github.com/querydsl/querydsl/blob/master/querydsl-sql/src/main/resources/keywords/mysql .

Otherwise, please provide a patch 😄
