### ISSUE TITLE
R2DBC support

### ISSUE THREAD

**Issue by mirromutth** [querydsl/querydsl#2468]
R2DBC (Reactive Relational Database Connectivity) is for reactive programming and containing concise SPI. Looks like it will be very well integrated with the DSL-style frameworks.

See:

- R2DBC SPI: https://github.com/r2dbc/r2dbc-spi
- JavaDoc: https://r2dbc.io/spec/0.8.0.M8/api

**Comment by fzoli** [comment]
I wrote a [reference implementation](https://github.com/fzoli/querydsl-r2dbc).

**Comment by riba2101** [comment]
So..its been almost a year, can we at least get an answer? will/wont do/prs accepted etc

**Comment by jwgmeligmeyling** [comment]
PR's will be accepted :)

**Comment by riba2101** [comment]
@jwgmeligmeyling  - for R2DBC we would need to bump the min version of java to 1.8, would that be ok?

**Comment by idosal** [comment]
@riba2101 Yes, it's on the roadmap for 5.0.

**Comment by jwgmeligmeyling** [comment]
Yes, and if you implement it in a dedicated module (`querydsl-r2dbc`) only that module has to be JDK8 afaik. So that also helps while the other modules are still on Java 7. But with 5.x we'll go to Java 8 anyway.

**Comment by riba2101** [comment]
oh sry, was kinda busy - yeah that's how I've started and exactly how it's currently implemented, and yes, you are correct, a single module can have a different compile version

**Comment by riba2101** [comment]
Hey guys, so...the changes are kinda huge...dunno how you guys wanna do this? (atm it's only compiling, need to test is extensively)

**Comment by lpandzic** [comment]
If you want to use R2DBC with Querydsl now and are using Spring Data, [Infobip Spring Data Querydsl now has R2DBC support](https://github.com/infobip/infobip-spring-data-querydsl#R2DBC).
Example usage:
```
interface TRepository extends ReactiveSortingRepository<T, ID>, ReactiveQuerydslPredicateExecutor<T>, QuerydslR2dbcFragment<T> {
}
```

[QuerydslJdbcFragment](https://github.com/infobip/infobip-spring-data-querydsl/blob/master/infobip-spring-data-r2dbc-querydsl/src/main/java/com/infobip/spring/data/r2dbc/QuerydslR2dbcFragment.java) provides access to `SQLQuery`, `SQLUpdateClause` and delete with `Predicate ` support.

**Comment by j30ng** [comment]
Hi all, when will #2610 be merged? Anything remains to be done?

**Comment by riba2101** [comment]
Hi guys, 

sorry I was really busy lately, will try to address the last comment shortly

**Comment by lpandzic** [comment]
5.0.0.M1 with Java 8 as baseline has been released so that addresses the https://github.com/querydsl/querydsl/issues/2468#issuecomment-638989912.

**Comment by Camsteack** [comment]
Hi ! Are there any update on R2DBC support ?
Cheers !

**Comment by riba2101** [comment]
guys, im super busy atm, pls try to support/further as i am currently not able to

**Comment by charlesvhe** [comment]
I am doing a demo of springboot3, which includes using QueryDSL as the Interface to generate SQL, and the underlying execution is taken over by R2DBC. Reference code: https://github.com/charlesvhe/native-image/blob/main/core/src/main/java/com/github/charlesvhe/nativeimage/QueryDslR2dbcTemplate.java

sample code：https://github.com/charlesvhe/native-image/blob/main/provider/src/main/java/com/github/charlesvhe/nativeimage/provider/ConfigMetaService.java

QBE
```
 @GetMapping
    public Mono<PagingResponse<ConfigMeta, ConfigMeta>> get(Paging paging) {
        return queryDslR2DbcTemplate.select(q -> q
                        .select(Projections.bean(ConfigMeta.class, QueryDslR2dbcTemplate.buildColumn(paging.getFields(), qConfigMeta.getColumns())))
                        .from(qConfigMeta)
                        .where(QueryDslR2dbcTemplate.buildWhere(paging.getFilter(), qConfigMeta.getColumns(), ExampleMatcher.StringMatcher.CONTAINING))
                        .orderBy(QueryDslR2dbcTemplate.buildOrder(paging.getSort(), qConfigMeta.getColumns()))
                        .offset(paging.getOffset())
                        .limit(paging.getLimit())
                )
                .collectList()
                .map(data -> new PagingResponse(data, paging.next()));
    }
```

**Comment by SledgeHammer01** [comment]
> If you want to use R2DBC with Querydsl now and are using Spring Data, [Infobip Spring Data Querydsl now has R2DBC support](https://github.com/infobip/infobip-spring-data-querydsl#R2DBC). Example usage:
> 
> ```
> interface TRepository extends ReactiveSortingRepository<T, ID>, ReactiveQuerydslPredicateExecutor<T>, QuerydslR2dbcFragment<T> {
> }
> ```
> 
> [QuerydslJdbcFragment](https://github.com/infobip/infobip-spring-data-querydsl/blob/master/infobip-spring-data-r2dbc-querydsl/src/main/java/com/infobip/spring/data/r2dbc/QuerydslR2dbcFragment.java) provides access to `SQLQuery`, `SQLUpdateClause` and delete with `Predicate ` support.

Does it handle relationships?

**Comment by lpandzic** [comment]
https://github.com/infobip/infobip-spring-data-querydsl?tab=readme-ov-file#R2DBCInnerJoin

**Comment by SledgeHammer01** [comment]
Just uses `SQLQuery` so it doesn't work with Hibernate annotations
