### ISSUE TITLE
Add getSuper() to EntityPath<T>

### ISSUE THREAD

**Issue by daniel-shuy** [querydsl/querydsl#2469]
Not sure if this should be here or in [codegen](https://github.com/querydsl/codegen).

Currently there is no way to get the super `EntityPath` from a generic `EntityPath` without the generated concrete implementation class (and getting `_super`).

I suggest to add a `getSuper()` method with return type `EntityPath<?>`, or better yet, modify `EntityPath<T> extends Path<T>` to `EntityPath<S, T extends S> extends Path<T>` and have `getSuper()` return `EntityPath<S>`,

then have the generated implementation class to return `_super` in `getSuper()`, and return `null` in `EntityPathBase#getSuper()` (or create `getSuper()` as a default method that returns `null` in `EntityPath`).

**Comment by jwgmeligmeyling** [comment]
What is the use-case for this? The entity path already has all super types attributes.

**Comment by daniel-shuy** [comment]
Its been so long I can't remember, I'll close this issue
