### ISSUE TITLE
Put the project up for adoption

### ISSUE THREAD

**Issue by johnjaylward** [querydsl/querydsl#2470]
Not sure who takers would be, but this project is so useful. It would be a shame to see it die from low activity from the current maintainers. Not sure if anyone has looked at getting it included in the Apache umbrella or similar ones, but it may be worth while to see if there are any takers.

**Comment by kartoffelsup** [comment]
https://github.com/querydsl/querydsl/issues/2459

**Comment by johnjaylward** [comment]
Thanks @kartoffelsup ! I didn't see that issue when searching. used the wrong keyword.
