### ISSUE TITLE
GroupBy.groupBy(..).list treats FactoryExpression differently when upcasting to Expression

### ISSUE THREAD

**Issue by wojcikt** [querydsl/querydsl#2472]
Hi,

I believe I've found a bug or at least a slightly misleading method signature.

Using `com.querydsl.core.group.GroupByBuilder#list` with a `FactoryExpression` upcasted to `Expression` in a query fails after fetching results with an exception:
```
com.querydsl.core.QueryException: java.lang.IllegalArgumentException: argument type mismatch
	at com.querydsl.sql.SQLResultIterator.next(SQLResultIterator.java:106)
	at com.querydsl.core.group.GroupByList.transform(GroupByList.java:60)
	at com.querydsl.core.group.GroupByList.transform(GroupByList.java:36)
...
```

`com.querydsl.core.group.GroupByBuilder#list` has overloads taking a `com.querydsl.core.types.FactoryExpression` parameter and a generic `com.querydsl.core.types.Expression` parameter. Both of these methods have different implementations which makes the behave differently depending on the type being passed to the method (because of Java's static dispatch).

Since `FactoryExpression` inherits after `Expression`I believe, that `com.querydsl.core.group.GroupByBuilder#list(com.querydsl.core.types.Expression<V>)` could perform a `instanceOf` on the given expression, and when that expression is an instance of `FactoryExpression` the `com.querydsl.core.group.GroupByBuilder#list(com.querydsl.core.types.FactoryExpression<V>)` should be called.

I've prepared a [minimal example](https://github.com/wojcikt/querydsl-groupby-issue-example) to show this problem. Take a look at `com.example.demo.FooDao` and tests.

Quick look at the code suggests that the same problem will occur when calling other `com.querydsl.core.group.GroupByBuilder`'s methods.

I will gladly prepare a pull request if you think this deserves a fix.

**Comment by jwgmeligmeyling** [comment]
I would try to get rid of the overload methods instead and just have the ones that accept any `Expression` and then do the necessities for a `FactoryExpression` through an expression visitor rather than an instanceof check.
