### ISSUE TITLE
Migrate off of jsr305

### ISSUE THREAD

**Issue by ptahchiev** [querydsl/querydsl#2479]
As discussed here:

https://github.com/google/guava/issues/2960

and here:

https://github.com/spotbugs/spotbugs/pull/180

JSR305 is dead and further more any jar that has classes in java or javax packages violates the Oracle JVM redistribution license.
Please use the spotbugs annotations instead.

**Comment by OrangeDog** [comment]
I'm not sure why it's needed at runtime for `querydsl-core` either. Should be e.g. `provided`.

**Comment by jwgmeligmeyling** [comment]
Some projects seem to migrate to https://github.com/JetBrains/java-annotations or https://github.com/typetools/checker-framework .

Guava hasn't decided yet.

Spotbugs decided to ship their own annotations.

A benefit of the Jetbrains java-annotations seem to be that they have CLASS retention. As a result we only require the dependency compile-time and it can have the `provided` scope, whereas with JSR305 is still required in `compile` scope.

**Comment by jwgmeligmeyling** [comment]
Provided an implementation in https://github.com/querydsl/querydsl/pull/2674
