### ISSUE TITLE
hi i am using JPASQLQuery but why get timestamp mysql db date

### ISSUE THREAD

**Issue by kimsangkyun** [querydsl/querydsl#2484]
why jpasqlquery is get db datetime type to java timestamp object
i use localdatetime or localdate
type error 

projections.filed is type error
projections.bean is null setter object

projections.bean
```
private LocalDateTime

public void setStartDate(LocalDateTime startDate) {
            this.startDate = startDate;
}
```
above type error

![image](https://user-images.githubusercontent.com/9389857/67647455-c0a46580-f975-11e9-8c71-ad94503d5c68.png)
above setter null...

function parameter type have to check then variable type check

stringtemplate date to string.....again java logic is convert string to localdatetime...
what is this....??

**Comment by jwgmeligmeyling** [comment]
Could be a duplicate of #2489.
