### ISSUE TITLE
JPASQLQuery does not return entities

### ISSUE THREAD

**Issue by ThePinkPanther** [querydsl/querydsl#2491]
As described in the SO question here: [https://stackoverflow.com/questions/58937264/querydsl-native-jpa-query-return-entities-instead-of-object-array](https://stackoverflow.com/questions/58937264/querydsl-native-jpa-query-return-entities-instead-of-object-array)

It seems that  JPASQLQuery is not able to project result queries into the jpa entities. 
```

QPriceModel pm = QPriceModel.priceModel;

List<PriceModel> fetch = new JPASQLQuery<PriceModel>(entityManager, new OracleTemplates())
    .select(pm)
    .from(pm)
    .fetch();
```

Returns 
`List<Object[]>`

**Comment by ThePinkPanther** [comment]
Ok, so it seems that `JPASQLQuery` does not use `DefaultQueryHandler` by default, which is needed to pass a type to the `entityManager` as seen here 
https://github.com/querydsl/querydsl/blob/QUERYDSL_4_2_1/querydsl-jpa/src/main/java/com/querydsl/jpa/sql/AbstractJPASQLQuery.java#L105-L113

My solution is to pass the `DefaultQueryHandler` to the constructor of the `JPASQLQuery`

```

        Configuration configuration = new Configuration(new OracleTemplates());

        new JPASQLQuery<>(entityManager, configuration,  DefaultQueryHandler.DEFAULT);
```

But I suggest it should become a constant in the overloaded constructors

**Comment by idosal** [comment]
Sounds good to me.
