### ISSUE TITLE
how to use queydsl in  elasticsearch java project?

### ISSUE THREAD

**Issue by zengfr** [querydsl/querydsl#2497]
https://github.com/querydsl/querydsl-contrib 
Querydsl Elasticsearch Not updated ?Not maintained?
how to use queydsl in  elasticsearch java project?querydsl new version Support？

**Comment by IdoSalomon** [comment]
I'm sorry to say that Elasticsearch is a community project, and as such is not actively maintained by the team (or anyone else for that matter).
Leaving this open for a little while in case someone has input on the issue, but I wouldn't hold my breath.
