### ISSUE TITLE
UUID is no longer supportet

### ISSUE THREAD

**Issue by michelu89** [querydsl/querydsl#2505]
UUID types can't be serialized in Oracle via Querydsl SQL, since the JDBC String mapping doesn't work here. I see it was fixed in version 3.4.3 and now it's out again?

**Comment by jwgmeligmeyling** [comment]
Do you have an example domain and query that we can use to reproduce this issue?

I don't think its intentionally not supported. I am not sure even if this is actually a QueryDSL issue or a JDBC/ ORM issue instead.

**Comment by johnktims** [comment]
We have uuid tests that run against oracle 11 so I'm going to close this. @michelu89 feel free to respond with more info and we'll take a look.
