### ISSUE TITLE
Use JPA Entities to create QueryDSL-SQL queries

### ISSUE THREAD

**Issue by eXsio** [querydsl/querydsl#2506]
Hello

Didn't know where to write this so I've chosen the place that many people interested in querydsl might look :)

I've created a tool taht allows using JPA Entity mappings to construct native sql with the use of QueryDSL-SQL api. If you find yourself missing a SQL feature that JPA is not supporting, there may be a good chance that EntitQL might help you out :)

Check it out here: https://github.com/eXsio/querydsl-entityql

**Comment by jwgmeligmeyling** [comment]
IMO the issue tracker is not a good place to advertise libraries. The repository owners might be interested in the inclusion of a "related works" list in the projects README. I'd like to encourage you to create such a PR that points to this extension, so we can close this issue 😄

**Comment by eXsio** [comment]
Thanks! Will do :)
