### ISSUE TITLE
Spring roo dependency

### ISSUE THREAD

**Issue by mwolfthal** [querydsl/querydsl#2513]
What maven repo is this supposed to be resolved from?

springframework.roo:org.springframework.roo.annotations:jar:1.2.3.RELEASE

And is it still needed going forward?

**Comment by jwgmeligmeyling** [comment]
It's an optional dependency for generating [Spring Roo](https://docs.spring.io/spring-roo/docs/current/reference/html/) metamodel classes using the [`RooAnnotationProcessor`](https://github.com/querydsl/querydsl/blob/master/querydsl-apt/src/main/java/com/querydsl/apt/roo/RooAnnotationProcessor.java), which handles `@RooJpaActiveRecord` and `@RooJpaEntity` annotations.

Version `1.2.3.RELEASE` is available in Springs own repository: https://mvnrepository.com/artifact/org.springframework.roo/org.springframework.roo.annotations/1.2.3.RELEASE

We should probably bump it to `1.3.2.RELEASE` which is also listed in Maven Central.
It has also been requested to support Spring Roo 2.0.0.RELEASE instead: #2062.
