### ISSUE TITLE
occasionally  Found shared references to a collection

### ISSUE THREAD

**Issue by smudgeJJJ** [querydsl/querydsl#2514]
one entity:
```
   @OneToMany(cascade = CascadeType.ALL, fetch = FetchType.EAGER)
    @JoinColumn(name = "demand_no", referencedColumnName = "demand_no", insertable = false, updatable = false)
    List<Goods> goodsList;
```
query:
```
QueryResults<ProduceDemand> tuples = jpaQueryFactory.selectFrom(qProduceDemand)
                .where(buildPredicate(demandPageQuery))
                .orderBy(qProduceDemand.id.asc())
                .offset(pageable.getOffset())
                .limit(demandPageQuery.getPageSize())
                .fetchResults();
```

Occasionally. What seems to be the problem,thanks

**Comment by idosal** [comment]
Could you please provide more detail? This includes version numbers of Querydsl and other relevant dependencies, the relevant stacktrace and any other relevant information that could help others to understand the problem. Thanks!

**Comment by smudgeJJJ** [comment]
> Could you please provide more detail? This includes version numbers of Querydsl and other relevant dependencies, the relevant stacktrace and any other relevant information that could help others to understand the problem. Thanks!
-----------------------
querydsl:4.2.2
hibernate-core:5.4.9-Final
springboot:2.2.2.RELEASE
tomcat:9
jdk:11

ProduceDemand.goodsList once in a while is empty.

I found org.hibernate.engine.internal.StatefulPersistenceContext#addCollectionByKey  sometimes return empty

ProduceDemand:
```
@Getter
@Setter
@javax.persistence.Entity
@Table(name = "osiris_produce_demand")
@DynamicInsert
@DynamicUpdate
@AggregateRoot
@FieldDefaults(level = AccessLevel.PRIVATE)
@NoArgsConstructor
public class ProduceDemand extends BaseJpaEntity implements Entity<ProduceDemand> {

    private static final long serialVersionUID = 8147306687313406381L;

    @Column(name = "demand_no")
    String demandNo;

    @Column(name = "demand_status")
    @Convert(converter = DemandStatusEnumConverter.class)
    DemandStatusEnum demandStatus;

    @Column(name = "seller_id")
    String sellerId;

    @Column(name = "seller_name")
    String sellerName;

    @Column(name = "company_name")
    String companyName;

    @Column(name = "total_amount")
    Long totalAmount;

    @Embedded
    Invoice invoice;

    @OneToOne(cascade = CascadeType.ALL, fetch = FetchType.LAZY)
    @JoinColumn(name = "demand_no", referencedColumnName = "demand_no", insertable = false, updatable = false)
    Craft craft;

    @OneToMany(cascade = CascadeType.ALL, fetch = FetchType.EAGER)
    @JoinColumn(name = "demand_no", referencedColumnName = "demand_no", insertable = false, updatable = false)
    List<Goods> goodsList;
```

Goods:
```
@Getter
@Entity
@Table(name = "osiris_produce_demand_goods")
@DynamicInsert
@DynamicUpdate
@AllArgsConstructor
@NoArgsConstructor
public class Goods extends BaseJpaEntity implements ValueObject<Goods> {

    @Column(name = "demand_no")
    String demandNo;

    String goodsName;

    Long goodsUnitPrice;

    Integer goodsNums;

    Long goodsTotalPrice;
```

query:
```
 @Override
    public ProduceDemand loadByDemandNo(String demandNo) {
        return jpaQueryFactory.select(qProduceDemand)
                .from(qProduceDemand)
                .where(qProduceDemand.demandNo.eq(demandNo))
                .fetchOne();
    }
```

**Comment by jwgmeligmeyling** [comment]
From : https://stackoverflow.com/a/1694236/2104280

> Hibernate shows this error when you attempt to persist more than one entity instance sharing the same collection reference (i.e. the collection identity in contrast with collection equality).
>
> Note that it means the same collection, not collection element - in other words relatedPersons on both person and anotherPerson must be the same. Perhaps you're resetting that collection after entities are loaded? Or you've initialized both references with the same collection instance?


This issue happens because managed entities in the persistence context that reference synchronised table spaces (the tables projected in the queries) are flushed to the database before executing the query.

If you want to prevent this flush you can do so by setting `setFlushMode(FlushModeType.COMMIT)` on your QueryDSL query.

Most likely however, you want to fix the bug in your code that causes these collisions between managed collections.
