### ISSUE TITLE
startup performance

### ISSUE THREAD

**Issue by mychalvlcek** [querydsl/querydsl#2515]
hi, just experiencing perf issue on first few runs of querydsl queries, we have spring rest controller fetching one simple select query (1 row) and whole endpoint tooks for the first time e.g. 3sec, for the second time 50ms, is there any cache or warmuping of query parsing or something like that?

version: 4.1.4

**Comment by johnktims** [comment]
How have you determined that querydsl is the culprit? Which querydsl modules are you using? Can you share a project that reproduces the issue?

**Comment by jwgmeligmeyling** [comment]
Its more likely a startup issue for the database or ORM than QueryDSL.

I suggest to hook your JVM to a profiler and investigate where the time is spent during the 3 seconds at cold start.
