### ISSUE TITLE
How can I query colletion in @OneToMany relationship

### ISSUE THREAD

**Issue by ldwqh0** [querydsl/querydsl#2519]
There are 2 entity in my project

```java
@Entity
public class Project {
    @Id
    private Long id;

    ......

    @OneToMany
    @JoinTable(name = "pm_project_file_")
    @OrderBy(value = "createdDate DESC")
    private List<FileInfo> files;
}

@Entity
public class FileInfo {
    ... // fileInfo
}
```
I want to query files with querydsl. How can I do this?

I know that can be query by jpql like this 
```
 @Query("select f from Project p, in(p.files) f where p.id=?1 order by f.createdDate desc")
```
but how to query with querydsl?

I do not want to change onetomany to (mappedBy="xxx"),because the FileInfo entity will be used other way 

My English is not good ,sorry.

**Comment by nwbkhan** [comment]
` JpaQueryFactory queryFactory = new JpaQueryFactory();`
`QProject project = QProject.project;`
`QFileInfo fileInfo = QFileInfo.fileInfo;`
`queryFactory.from(project).leftJoin(project.files, fileInfo).where(fileInfo.in(//your passed`
`result//)).fetchAll().fetch()`

**Comment by ldwqh0** [comment]
@nwbkhan  I want to query many files in a project , not the project entity.

and i'm try your code , the errror is happend

```
Caused by: org.hibernate.hql.internal.ast.QuerySyntaxException: Invalid path: 'project.files' [select fileInfo
from com.dm.file.entity.FileInfo fileInfo
  inner join project.files as fileInfo fetch all properties]
```

**Comment by nwbkhan** [comment]
>  @Query("select f from Project p, in(p.files) f where p.id=?1 order by f.createdDate desc")
```
JpaQueryFactory queryFactory = new JpaQueryFactory();
QProject project = QProject.project;
QFileInfo fileInfo = QFileInfo.fileInfo;
queryFactory
   .from(project)
   .leftJoin(project.files, fileInfo)
   .where(project.id.eq(productId).and(project.fileInfo.any.id.eq(fileInfo.id)))  // <---- pass your project id from here from ?1
   .fetchAll()    //<---- remove fetch from here
   .transform(GroupBy.from(project.id).list(GroupBy.list(fileInfo)));  // <-- this will transform your query to project files only.
```
@ldwqh0  
If you want to transform your data to only files then make transform at last list line or remove if you don't want, and remove fetch all (It creates fetch all type query, my mistake).


Remember that limit will not going to work in this case.
Let me know if it still not working.

**Comment by jwgmeligmeyling** [comment]
```java
QProject project = QProject.project;
QFileInfo fileInfo = QFileInfo.fileInfo;
List<FileInfo> projectFileInfos = queryFactory
   .from(project)
   .innerJoin(project.files, fileInfo)
   .where(project.id.eq(productId))
   .select(fileInfo)
   .fetch()    //<---- remove fetch from here
```

renders:

```sql
select f from Project p inner join p.files f where p.id=?1 order by f.createdDate desc
```

Which is functionally equivalent to your original question.
