### ISSUE TITLE
Annotation processor ‘com.querydsl.apt.jpa.JPAAnnotationProcessor’ not found

### ISSUE THREAD

**Issue by Venkat091988** [querydsl/querydsl#2522]
The issue I am facing:

What went wrong:
Execution failed for task ‘:generateQueryDSL’.
Annotation processor ‘com.querydsl.apt.jpa.JPAAnnotationProcessor’ not found

Can you please help me out how to manually add the annotation processor configuration. I am using querydsl 4.1.4 version. already adding the JAVAX Persistence.

Below is the sample:

implementation group: ‘org.hibernate.javax.persistence’, name: ‘hibernate-jpa-2.1-api’, version: ‘1.0.2.Final’

implementation group: ‘com.querydsl’, name: ‘querydsl-maven-plugin’, version: ‘4.1.4’
implementation group: ‘com.querydsl’, name: ‘querydsl-core’, version: ‘4.1.4’
implementation group: ‘com.querydsl’, name: ‘querydsl-apt’, version: ‘4.1.4’
implementation group: ‘com.querydsl’, name: ‘querydsl-jpa’, version: ‘4.1.4’
implementation group: ‘com.querydsl’, name: ‘querydsl-collections’, version: ‘4.1.4’
implementation group: ‘com.querydsl’, name: ‘querydsl-codegen’, version: ‘4.1.4’

task generateQueryDSL(type: JavaCompile, group: ‘build’, description: ‘Generates the QueryDSL query types’) {
source = sourceSets.main.java
classpath = configurations.compileClasspath
options.compilerArgs = [
‘-proc:only’,
‘-processor’,
‘com.querydsl.apt.jpa.JPAAnnotationProcessor’
]
options.warnings = false
destinationDir = sourceSets.generated.java.srcDirs.iterator().next()
}

**Comment by kamko** [comment]
You should classify the apt dependency:

 implementation group: ‘com.querydsl’, name: ‘querydsl-core’, version: ‘4.1.4’ implementation group: ‘com.querydsl’, name: ‘querydsl-apt’, version: ‘4.1.4’, classifier: 'jpa'

**Comment by Venkat091988** [comment]
@kamko 

I just added like this

implementation group: 'com.querydsl', name: 'querydsl-apt', version: '4.1.4', classifier: 'jpa'

Still I am facing the same issue.

> Task :generateQueryDSL FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':generateQueryDSL'.
> Annotation processor 'com.querydsl.apt.jpa.JPAAnnotationProcessor' not found


One more thing i did is 

implementation group: 'com.querydsl', name: 'querydsl-jpa', version: '4.1.4' , classifier: 'jpa'

by this also I am also facing the issue not in this link.

https://jcenter.bintray.com/com/querydsl/querydsl-jpa/4.1.4/

**Comment by kamko** [comment]
What version of gradle is it? 
You aren't using a plugin, right?
The second change is not right, don't do that.

**Comment by Venkat091988** [comment]
Gradle 6.0.1

Here are the plugins I am using

apply plugin: 'java'
apply plugin: 'org.springframework.boot'
apply plugin: 'eclipse'
apply plugin: 'project-report'
apply plugin: 'com.jfrog.artifactory'
apply plugin: 'maven-publish'

This is how I declared:

implementation group: 'com.querydsl', name: 'querydsl-maven-plugin', version: '4.2.2'
implementation group: 'com.querydsl', name: 'querydsl-core', version: '4.2.2'
annotationProcessor 'com.querydsl:querydsl-apt:4.2.2:jpa'
implementation group: 'com.querydsl', name: 'querydsl-jpa', version: '4.2.2'
implementation group: 'com.querydsl', name: 'querydsl-collections', version: '4.2.2'
implementation group: 'com.querydsl', name: 'querydsl-codegen', version: '4.2.2'

Still facing the same issue.

**Comment by Venkat091988** [comment]
This is how I declared and facing same issue.

implementation group: 'com.querydsl', name: 'querydsl-maven-plugin', version: '4.2.2'
		implementation group: 'com.querydsl', name: 'querydsl-core', version: '4.2.2'
		annotationProcessor 'org.hibernate.javax.persistence:hibernate-jpa-2.1-api:1.0.2.Final'
		annotationProcessor 'com.querydsl:querydsl-apt:4.2.2:jpa'
		implementation group: 'com.querydsl', name: 'querydsl-jpa', version: '4.2.2'
		implementation group: 'com.querydsl', name: 'querydsl-collections', version: '4.2.2'
		implementation group: 'com.querydsl', name: 'querydsl-codegen', version: '4.2.2'

* What went wrong:
Execution failed for task ':generateQueryDSL'.
> Annotation processor 'com.querydsl.apt.jpa.JPAAnnotationProcessor' not found

**Comment by kamko** [comment]
OK.

Adding 
```
annotationProcessor('javax.annotation:javax.annotation-api:1.3.2')
annotationProcessor('org.hibernate.javax.persistence:hibernate-jpa-2.1-api:1.0.2.Final')
annotationProcessor('com.querydsl:querydsl-apt:4.2.2:jpa')
```

Makes it generate classes when you run compileJava so that means the problem comes from your task declaration.

I see zero reasons for you to create own task but well ok.

```
task generateQueryDSL(type: JavaCompile, group: "build", description: "Generates the QueryDSL query types") {
    source = sourceSets.main.java
    classpath = configurations.compileClasspath
    options.annotationProcessorPath = sourceSets.main.annotationProcessorPath
    options.compilerArgs = [
            "-proc:only",
            "-processor",
            "com.querydsl.apt.jpa.JPAAnnotationProcessor"
    ]
    options.warnings = true
    destinationDir = sourceSets.generated.java.srcDirs.iterator().next()
}
```

The problem is that you were missing the annotationProcessorPath for the java compile task, see
https://docs.gradle.org/current/userguide/java_plugin.html
and

**Comment by Venkat091988** [comment]
Hi 
Now I am getting different error. 

error: cannot access QueryDslPredicateExecutor

public static interface XXX extends EntityQueryableRepository<XXX, XXX> {

class file for org.springframework.data.querydsl.QueryDslPredicateExecutor not found

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':generateQueryDSL'.
> Compilation failed; see the compiler error output for details.

**Comment by Venkat091988** [comment]
Thanks for the help kamko.
