### ISSUE TITLE
How do we generate Java Entity class from database. Is there a specific Maven configuration.

### ISSUE THREAD

**Issue by ksiram** [querydsl/querydsl#2524]
How do we generate Java Entity class from database. Is there a specific Maven configuration.
Thanks.

**Comment by lpandzic** [comment]
Here's one approach: https://github.com/infobip/infobip-spring-data-querydsl/blob/b10510f58566a46dcf8073a094d141c053f0dc59/infobip-spring-data-jdbc-querydsl/pom.xml#L41-L179

**Comment by jwgmeligmeyling** [comment]
For JPA entities there are approaches per vendor as well: https://mkyong.com/hibernate/how-to-generate-code-with-hibernate-tools/
