### ISSUE TITLE
Ignore table prefix

### ISSUE THREAD

**Issue by gggitpl** [querydsl/querydsl#2533]
How to ignore table prefixes when generating code
For example: t_account-> QAccount

**Comment by jwgmeligmeyling** [comment]
You should implement a custom [`NamingStrategy`](https://github.com/querydsl/querydsl/blob/master/querydsl-sql-codegen/src/main/java/com/querydsl/sql/codegen/NamingStrategy.java). It can be specified using `MetaDataExporter#setNamingStrategy(NamingStrategy)`.

**Comment by gggitpl** [comment]
@jwgmeligmeyling I use querydsl-maven-plugin plugin to generate, I don't know how to configure custom NamingStrategy

**Comment by gggitpl** [comment]
@jwgmeligmeyling Do you know how to specify the database name? I tried to specify it after jdbcurl, but it didn't work

**Comment by jwgmeligmeyling** [comment]
You should specifiy the [`namingStrategyClass `](https://github.com/querydsl/querydsl/blob/2bf234caf78549813a1e0f44d9c30ecc5ef734e3/querydsl-maven-plugin/src/main/java/com/querydsl/maven/AbstractMetaDataExportMojo.java#L168). For it to work, your naming strategy implementation needs to be on the plugin classpath. I.e. create a separate Maven for it, install it locally and add as dependency it to the `<dependencies>` section of your `<plugin>` configuration for `querydsl-maven-plugin`.

**Comment by gggitpl** [comment]
thank you very much
