### ISSUE TITLE
(Projections) Instantiating object when FK column is null

### ISSUE THREAD

**Issue by laudecir** [querydsl/querydsl#2542]
### Issue
I have a query with a projection where I need to search for referenced table information (FK) in addition to the main table information. However, when the FK is null, the object (entity) is instantiated after fetching. 

### Expected result
FK object must come null, not instantiated with null properties.

### Example bellow

**ERD:**

![ERD](https://user-images.githubusercontent.com/5587795/76885332-d56a9280-685d-11ea-85bd-0acd6796dacb.png)

**QueryDSL:**

```
        JPAQueryFactory factory = new JPAQueryFactory(getEntityManager());
        List<SiloFan> siloFanList =
                factory.select(
                        Projections.bean(
                                SiloFan.class,
                                QSiloFan.siloFan.id,

                                Projections.bean(
                                        DeviceProperty.class,
                                        QDeviceProperty.deviceProperty.id
                                ).as(QSiloFan.siloFan.motorStatusDeviceProperty)
                        )
                )
                .from(QSiloFan.siloFan)

                .leftJoin(QSiloFan.siloFan.motorStatusDeviceProperty, QDeviceProperty.deviceProperty)

                .fetch();
```

**Generated SQL:**
```
select
	silofan0_.id as col_0_0_,
	deviceprop1_.id as col_1_0_
from 
        aut_silo_fan silofan0_
left outer join
       aut_device_property deviceprop1_ on silofan0_.motor_status_device_property_id = deviceprop1_.id
```

**SQL Result:**

|col_0_0_|col_1_0_|
|--------|--------|
|1bc0bad9-2a4e-4a94-b693-89a206645436||
|2e98758c-050a-41c7-93d2-bde90a25e22d||

**Comment by jwgmeligmeyling** [comment]
`FactoryExpressions` are executed inside Java, not SQL. Therefore a database side NULL or COALESCE check won't make a difference here. It will always create the DeviceProperty bean, as you specified in the projection definition.

The only workaround to this is to implement your own `FactoryExpression` that returns null of any of the fields in the tuple are null.
