### ISSUE TITLE
JpaSQLQuery with @ManyToOne -> where criteria not working

### ISSUE THREAD

**Issue by stefanbulzan** [querydsl/querydsl#2543]
I use the QueryDSL 4.3.0
I have the entity:

```kotlin
data class PersonCertificate(
    @Id
    val id: String = UUID.randomUUID().toString(),
    @Column(name = "expiration_date", nullable = false)
    val expirationDate: LocalDate,
    @ManyToOne
    val certificate: Certificate,
    @ManyToOne
    val person: Person, // this is mapped by a personId column in person_certificate table
)
```

I want to get all resources for a person id, and I need some data calculations so I need to use JPASQLQuery.
So I have the following code:

```kotlin
        val sqlQuery = JPASQLQuery<PersonCertificate>(
            entityManager, MySQLTemplates.builder()
                .build()
        )
        val resultList = sqlQuery
            .from(pc)
            .where(pc.person.id.eq(personId))
            .createQuery()
            .resultList
```

this generates the following query:

```sql
 select personCertificate.id as id1_7_0_, personCertificate.certificate_id as certific4_7_0_, personCertificate.expiration_date as expirati2_7_0_, personCertificate.file_id as file_id3_7_0_, personCertificate.person_id as person_i5_7_0_
from person_certificate personCertificate
where personCertificate.person.id = ? and personCertificate.person.id = ?
```

As you see the personId is referred as `personCertificate.person.id` which is not correct. Also it's duplicated...
What am I doing wrong here?
It works with `JPAQuery`, but I need to use `SQLExpressions.datediff` which doesn't work with `JPAQuery`.

**Comment by jwgmeligmeyling** [comment]
I  am not too familiar with `JPASQLQuery` so I can't help you with that. But I do want to point out that is perfectly possible to use `datadiff` in JPAQuery, as long as you create a custom function for it in your dialect. For example, for Hibernate, have a look at: https://thoughts-on-java.org/database-functions/
