### ISSUE TITLE
Sorting unpaged results?

### ISSUE THREAD

**Issue by dkarasopi** [querydsl/querydsl#2544]
Why is it not possible to sort unpaged results?
I did some debugging and found following lines in class Querydsl:

>  if (pageable.isUnpaged()) {
            return query;
        } else {
            query.offset(pageable.getOffset());
            query.limit((long)pageable.getPageSize());
            return this.applySorting(pageable.getSort(), query);
        }

Why is query returned as is if pageable is unpaged?

**Comment by kamko** [comment]
Where exactly did you find that? 

As I don't think that snippet is from this repository.

**Comment by dkarasopi** [comment]
Sorry, that's my bad, it's from:
package org.springframework.data.jpa.repository.support;

So it doesn't really qualify as querydsl's misbehaviour.
