### ISSUE TITLE
On the abbreviation of fields

### ISSUE THREAD

**Issue by guojinpeng** [querydsl/querydsl#2548]
`Projections.bean(
                                                AuthUserDTO.class,
                                                qAuthUser.id,
                                                qAuthUser.state,
                                                qAuthUser.source,
                                                qAuthUser.phone,
                                                qAuthUser.email,
                                                qAuthUser.username
 )`
Is there any way to abbreviate the above code as follows?
`Projections.bean(
                                                AuthUserDTO.class,
                                                qAuthUser
 )`

**Comment by jwgmeligmeyling** [comment]
It gets slightly better using a `@QueryProjection`:

```java
class CustomerDTO {

  @QueryProjection
  public CustomerDTO(long id, String name) {
     ...
  }

}
```

```java
QCustomer customer = QCustomer.customer;
JPQLQuery query = new HibernateQuery(session);
List<CustomerDTO> dtos = query.select(new QCustomerDTO(customer.id, customer.name))
                              .from(customer).fetch();
```


You can also get inspiration from the generated code from `QueryProjection` and cook a static utility method up in your own codebase.
