### ISSUE TITLE
Support to SqlServer 2017 (version 14.0)

### ISSUE THREAD

**Issue by slma80** [querydsl/querydsl#2555]
Modify SQLServerTemplates.getBuilder method to associate version 14 of Sql Server to SQLServer2012Templates

With SQLServerTemplates there are errors with OFFSET clause

Regards
Luca

**Comment by jwgmeligmeyling** [comment]
`SQLServerTemplates.Builder` is not aware of which SQL Server version is used, and by the lack of accessibility to a JDBC `Connection` it isn't able to figure out which version is used either. The intended and only solution is to just specify that you want to use the `SQLServer2012Templates`, which are for SQL Server 2012 and up, manually.

Works as intended, and in a best effort.
