### ISSUE TITLE
when in(...)  from where ,and cant select from database

### ISSUE THREAD

**Issue by lyxaaadf** [querydsl/querydsl#2556]
exp:===============>

	qMoment.creator.in(408491126342467584L,408491133254680576L,408491135939035136L,408491136241025024L,
            					408491136845004800L,408491141458739200L,408491220127105024L,408491220462649344L,408491220798193664L,
            					408491221142126592L,408491221477670912L,408491221821603840L,408491222157148160L,408491222492692480L,
            					408491222836625408L,408491223180558336L,408491223524491264L,408491223876812800L,408491224220745728L,
            					408491224573067264L,408491224917000192L,408491225269321728L,408491225613254656L,408491225965576192L,
            					408491226317897728L,408491226661830656L,408491227014152192L,408491227366473728L,408491227710406656L,
            					408491228062728192L,408491228406661120L,408491228767371264L,408491229111304192L,408491229472014336L,
            					408491229824335872L,408491230176657408L,408491230528978944L,408491230881300480L,408491231233622016L,
            					408491233364328448L,408491233716649984L,408491234060582912L,408491234412904448L,408491234765225984L).and(qMoment.status.eq(3)))

this cant select data from database,but  this can ....==>

qMoment.creator.in(408491126342467584L,408491133254680576L,408491135939035136L,408491136241025024L).and(qMoment.status.eq(3)))

======================>

I guess have a bug that  char is very more so cant work from in

**Comment by lyxaaadf** [comment]
i use  the postgresql

**Comment by jwgmeligmeyling** [comment]
What is the exception? Some ORMs and JDBC Drivers have limitations in the amount of parameters that can be bound.

**Comment by lyxaaadf** [comment]
> What is the exception? Some ORMs and JDBC Drivers have limitations in the amount of parameters that can be bound.

NO exception ，I dubbg and find maybe entityManager's problem，but cant To solve this problem

**Comment by lyxaaadf** [comment]
> What is the exception? Some ORMs and JDBC Drivers have limitations in the amount of parameters that can be bound.

it's always pending.....and no result

**Comment by jwgmeligmeyling** [comment]
That seems a query execution problem in your database. Its unrelated to QueryDSL or the SQL it generates. Probably the structure of your table doesn't allow this to be optimized very well.

Please look at alternatives for passing these variables. Alternatives may be:
- Using a native array type and bind this as a single parameter (requires a database that supports arrays as well as a custom type implementation for this array  type in your ORM)
- Using a VALUES clause (SQL only)
- Storing the ids in a temporary table (pretty much SQL only)

**Comment by jwgmeligmeyling** [comment]
A quick fix might be to create an index on the column used for `creator` in `Moment`.

**Comment by lyxaaadf** [comment]
> That seems a query execution problem in your database. Its unrelated to QueryDSL or the SQL it generates. Probably the structure of your table doesn't allow this to be optimized very well.
> 
> Please look at alternatives for passing these variables. Alternatives may be:
> 
> * Using a native array type and bind this as a single parameter (requires a database that supports arrays as well as a custom type implementation for this array  type in your ORM)
> * Using a VALUES clause (SQL only)
> * Storing the ids in a temporary table (pretty much SQL only)

In fact, performs the SQL statements in the database, there is no problem. It should not be the cause of the database. I go querydsl breakpoint, when obtain the Query results, is in a wait state. I am look for practical reasons, I am also exclude the querydsl itself now

**Comment by lyxaaadf** [comment]
> A quick fix might be to create an index on the column used for `creator` in `Moment`.

now I am sure that is querydsl's problem or related with it ,bacause I choose jpa <@query > method，it's ok.

**Comment by lyxaaadf** [comment]
> A quick fix might be to create an index on the column used for `creator` in `Moment`.

see=================>package com.querydsl.jpa.impl  AbstractJPAQuery.class

 private List<?> getResultList(Query query) {
        // TODO : use lazy fetch here?
        if (projection != null) {
            List<?> results = query.getResultList();
            List<Object> rv = new ArrayList<Object>(results.size());
            for (Object o : results) {
                if (o != null) {
                    if (!o.getClass().isArray()) {
                        o = new Object[]{o};
                    }
                    rv.add(projection.newInstance((Object[]) o));
                } else {
                    rv.add(null);
                }
            }
            return rv;
        } else {
            return query.getResultList();     ==========> when here ,its pending and 
        }

**Comment by lyxaaadf** [comment]
> A quick fix might be to create an index on the column used for `creator` in `Moment`.

=================》
i try .fetchFirst() and fetch()  ,the result is fetchFirst is ok and fetch  is pending

**Comment by jwgmeligmeyling** [comment]
Yes, its pending because your database is not returning results.

If you execute the same query using `@Query` , you'd see the same results.

Be sure in your tests to use parameters instead of constants. Because that's whats happening in the QueryDSL example as well.

**Comment by lyxaaadf** [comment]
> Yes, its pending because your database is not returning results.
> 
> If you execute the same query using `@Query` , you'd see the same results.
> 
> Be sure in your tests to use parameters instead of constants. Because that's whats happening in the QueryDSL example as well.

==========>ok ,i will try and tell you  final result,.wate for a moment

**Comment by lyxaaadf** [comment]
> Yes, its pending because your database is not returning results.
> 
> If you execute the same query using `@Query` , you'd see the same results.
> 
> Be sure in your tests to use parameters instead of constants. Because that's whats happening in the QueryDSL example as well.

yeath, The result shows your conclusion is correct

**Comment by jwgmeligmeyling** [comment]
This issue can be closed then 😄 

Btw, if you want you could try constantifying the ID's by using a `TemplateExpression` instead of a `ConstantExpression`: `Expressions.templatExpression(Long.toString(123456L))`.
