### ISSUE TITLE
CaseBuilder expression in "otherwise" is considered as variable to bind instead of expression

### ISSUE THREAD

**Issue by ulk200** [querydsl/querydsl#2559]
I'm suing the latest QueryDSLSQL build, 4.3.1 and am doing something like this : 

```
(new CaseBuilder())
.when(table1.dateStart.lt(table2.date))
.then(Expressions.nullExpression())
.otherwise(table2.date)
```
the SQL looks like :
`case when table1.dateStart < table2.date null else ? end`
The interrogation mark is what bothers me, it crashes the query at execution

Looking at the code inside CaseBuilder i saw that the `then` method calls `thenDateTime`, but such transformation is not done in the otherwise method.

With that in mind i tried to reverse my condition :
```
(new CaseBuilder())
.when(table1.dateStart.goe(table2.date))
.then(table2.date)
.otherwise(Expressions.nullExpression())
```
And now the SQL is OK :
`case when table1.dateStart >= table2.date table2.date else null end`

It seems to me that `otherwise()` should handle such Expression object like `then()` is doing
Thanks

**Comment by jwgmeligmeyling** [comment]
I am a bit surpised.

The interrogation mark indicates that the expression is serialized as a parameter. Parameters are not allowed in the `SELECT` clause as-per JPA specification (some implementations do deviate from this for dialects that support it). As a workaround, the `JPQLSerializer` constantifies expressions in the `SELECT` clause - also for `CASE ... WHEN ...` constructs.

However, that would mean that `table2.date` is a constant, and it seems to be a `PathExpression` instead. Or isn't it? What is the type for `table2.date`?

**Comment by ulk200** [comment]
I'm using QueryDSL SQL, there is no JPA involved
table2.date is a DateTimePath<java.sql.Timestamp>, auto generated with the MetaDataExporter

**Comment by jwgmeligmeyling** [comment]
My bad. Mostly the same. We'd have to look into what the `SQLSerializer` is doing and why its rendering a parameter. A test case would be helpful. Are you willing to contribute that? You can extend [`SQLSerializerTest`](https://github.com/querydsl/querydsl/blob/master/querydsl-sql/src/test/java/com/querydsl/sql/SQLSerializerTest.java)

**Comment by ulk200** [comment]
Here is a test 

```
    @Test
    public void casesOtherwiseWithExpression() {
        SQLSerializer serializer = new SQLSerializer(Configuration.DEFAULT);
        serializer.handle(
            Expressions.cases()
                .when(QEmployee.employee.id.gt(0)).then(Expressions.nullExpression())
                .otherwise(QEmployee.employee.timefield)
        );
        assertEquals("case when EMPLOYEE.ID > ? then null else EMPLOYEE.TIMEFIELD end", serializer.toString());
        assertEquals(Arrays.asList("0"), serializer.getConstants());
    }
```

Constants are `[0, EMPLOYEE.timefield]` instead of `[0]`, so i checked them as well

**Comment by jwgmeligmeyling** [comment]
This is a limitation of Java generics.

`otherwise` has two overloads:

1. `public Q otherwise(Expression<A> expr)`
2. `public Q otherwise(A constant)`

Because your `nullExpression` is not typed, the result is a `CaseBuilder.Cases<Object, SimpleExpression<Object>>`. Although your second expression is a `TimePath<Time>`, which is an `SimpleExpression<Time>`, but also an `Object` - so it satisfies `public Q otherwise(A constant)` and uses this method instead.

Two fixes:

## Qualifying the generic for `nullExpression`
```java
Expressions.cases()
        .when(QEmployee.employee.id.gt(0)).then(Expressions.<Time >nullExpression())
        .otherwise(QEmployee.employee.timefield)
```

## Forcing `public Q otherwise(Expression<A> expr)` to be used:


```java
Expressions.cases()
        .when(QEmployee.employee.id.gt(0)).then(Expressions.nullExpression())
        .otherwise((Expression) QEmployee.employee.timefield)
```

**Comment by ulk200** [comment]
Thank you
This is tricky indeed, now that i understand it i will pay attention but it's confusing. And it will certainly confuse other newcomers like me
Maybe an explanation in the documentation about the special case for nullExpression ?

**Comment by jwgmeligmeyling** [comment]
It was tricky for me as well 😉 


I think the best change would be to deprecate `nullExpression()` and mandate a type to be specified as parameter that defines the generic, like so: `nullExpression(Time.class)`.

Not the most fluent, but I am afraid that people are still going to struggle if we only put the explanation in the documentation.
