### ISSUE TITLE
HibernateHandler.iterate does not use scrolling (Hibernate 5.4 JPA)

### ISSUE THREAD

**Issue by martinufo** [querydsl/querydsl#2566]
I've upgraded from Hibernate 5.1.10.Final + Querydsl 4.2.2 to Hibernate 5.4.14.Final + Querydsl 4.3.1. Everything seems to work except results iteration. The implementation in HibernateHandler does not use scrolling and always fetches the whole list.

I found that if i change the condition `query instanceof NativeQuery` to `query instanceof org.hibernate.query.Query` (and the `unwrap` call under it), it stats working properly again.

Unfortunately `HibernateHandler` is package protected and I haven't found a way to register my own `QueryHandler`. So I hacked the temporary solution with Javassist:

```kotlin
        val pool = ClassPool.getDefault()
        val hibernateHandler = pool.get("com.querydsl.jpa.HibernateHandler")

        val iterate = hibernateHandler.getDeclaredMethod("iterate")
        iterate.insertBefore("""
            if ($1 instanceof org.hibernate.query.Query) {
                return shim.FixedHibernateHandler.iterate($$);
            }
        """)

        val transform = hibernateHandler.getDeclaredMethod("transform")
        transform.insertBefore("""
            if ($1 instanceof org.hibernate.query.Query) {
                return shim.FixedHibernateHandler.transform($$);
            } 
        """)

        hibernateHandler.toClass()
```

```java
package shim;

public final class FixedHibernateHandler {

    @SuppressWarnings("unchecked")
    public static <T> CloseableIterator<T> iterate(Query query, FactoryExpression<?> projection) {
        org.hibernate.query.Query<?> hQuery = query.unwrap(org.hibernate.query.Query.class);
        ScrollableResults results = hQuery.scroll(ScrollMode.FORWARD_ONLY);
        CloseableIterator<T> iterator = new ScrollableResultsIterator<>(results);
        if (projection != null) {
            iterator = new TransformingIterator<>(iterator, projection);
        }
        return iterator;
    }

    @SuppressWarnings("deprecation")
    public static boolean transform(Query query, FactoryExpression<?> projection) {
        ResultTransformer transformer = new FactoryExpressionTransformer(projection);
        query.unwrap(org.hibernate.query.Query.class).setResultTransformer(transformer);
        return true;
    }
```

**Comment by jwgmeligmeyling** [comment]
This should be fixed in https://github.com/querydsl/querydsl/commit/3dfc9dd7b8132c3bda8f9e3d74b21606ff695784 . Please try upgrading to 4.3.x instead.

**Comment by jwgmeligmeyling** [comment]
Ah actually, that commit still misses the same fix for `transform`... Minor oversight. Same fix applies though... I'll create a PR if no one gets there first

**Comment by martinufo** [comment]
I have Querydsl 4.3.1. The mentioned fix does not handle my case.

Query I get in this method is of type `org.hibernate.query.internal.QueryImpl`, which does not implement `NativeQuery`. It implements `org.hibernate.query.Query` that has all the required methods.

**Comment by heesuk-ahn** [comment]
@martinufo 
Thanks for reporting. I created pull request for this issue :)
