### ISSUE TITLE
When using ne(), but working eq()

### ISSUE THREAD

**Issue by hojak99** [querydsl/querydsl#2589]
I'm using querydsl-jpa:4.1.3

I made `JPAExpressions`. 
<img width="1085" alt="image" src="https://user-images.githubusercontent.com/17019847/82727632-a32a5500-9d26-11ea-9ce9-048d715ff9c4.png">

here is used booleanBuilder and `ne()` to compare the results.
<img width="707" alt="image" src="https://user-images.githubusercontent.com/17019847/82727656-d5d44d80-9d26-11ea-92b5-95110ee7b5e2.png">

but, the implementation of ne() was the same as eq().
<img width="525" alt="image" src="https://user-images.githubusercontent.com/17019847/82727751-61e67500-9d27-11ea-9c05-64096ff17280.png">

so, predicate was:
<img width="667" alt="image" src="https://user-images.githubusercontent.com/17019847/82727794-9c501200-9d27-11ea-8921-ad6df79a809d.png">

---

I want to know why it works like this.

Is this a bug?

**Comment by jwgmeligmeyling** [comment]
From which class is the code in the screenshot?

**Comment by hojak99** [comment]
Are you say to the implementation class?
implemetation class is `FetchableSubQueryBase` class. 

![image](https://user-images.githubusercontent.com/17019847/82747730-260ae880-9dd7-11ea-8a99-5670265f3194.png)

Look at the bottom method(ne()) in the screenshot.

**Comment by jwgmeligmeyling** [comment]
The code above is indeed faulty and has been resolved in https://github.com/querydsl/querydsl/commit/dde4771aab4c0f392e63f1a83ed4d8e3ac7e4abe#diff-4e255b89fc919d3743d1995fc971ec25 which has landed in release 4.2.1. I'd suggest to upgrade to QueryDSL 4.2.1 minimally if you rely on this methods in `FetchableSubQueryBase` al lot.

**Comment by hojak99** [comment]
thx!!!
