### ISSUE TITLE
querydsl how to solve the problem of AND/OR priority

### ISSUE THREAD

**Issue by lveeJava** [querydsl/querydsl#2593]
hello, although AND has higher precedence then OR, but how can i transfer it
sql: e1 and e2 or ( e3 and e4 or e7)

**Comment by jwgmeligmeyling** [comment]
QueryDSL has the `WRAPPED` operator that wraps an expression within parentheses.

Use:

```java
Expressions.predicate(Ops.WRAPPED, firstExpression.and(secondExpression))
```
