### ISSUE TITLE
Mongodb query guide is incomplete and incorrect please make sure it is complete .

### ISSUE THREAD

**Issue by ashutoshbibyan** [querydsl/querydsl#2614]
the reference of using the query dsl with the mongo db is incorrect .
http://www.querydsl.com/static/querydsl/2.1.0/reference/html/ch02s07.html
this is the url of the page which show how to add the query dsl to the project for mongodb but in this page it says that annotate the model class with the @Entity annotation of the com.google.code.morphia.annotations.Entity but documentation don't put com.google.code.morphia.annotations.Entity in the required maven dependency and it don't mention which version to used i add it manually but still it don't generate the Qclass when i run the mvn clean install 
the solution i found is when i use these dependency and this plugin 
dependency 

		
		<dependency>
	  <groupId>com.querydsl</groupId>
	  <artifactId>querydsl-apt</artifactId>
	  <version>${querydsl.version}</version>
	  <scope>provided</scope>
	</dependency>
	
	<dependency>
	  <groupId>com.querydsl</groupId>
	  <artifactId>querydsl-mongodb</artifactId>
	  <version>${querydsl.version}</version>
	</dependency>
	
	<dependency>
	  <groupId>org.slf4j</groupId>
	  <artifactId>slf4j-log4j12</artifactId>
	  <version>1.6.1</version>
	</dependency>		

and this plugin 

		
		<plugin>
        <groupId>com.mysema.maven</groupId>
        <artifactId>apt-maven-plugin</artifactId>
        <version>1.1.3</version>
        <executions>
          <execution>
            <goals>
              <goal>process</goal>
            </goals>
            <configuration>
              <outputDirectory>target/generated-sources/java</outputDirectory>
              <processor>com.querydsl.apt.QuerydslAnnotationProcessor</processor>
            </configuration>
          </execution>
        </executions>
      </plugin>

**Comment by jwgmeligmeyling** [comment]
You're using the old link. The new documentation is available at http://www.querydsl.com/static/querydsl/4.4.0/reference/html/ch02s07.html
