### ISSUE TITLE
StringExpressions.lpad in concatenate operation doesn't work

### ISSUE THREAD

**Issue by gzfhz** [querydsl/querydsl#2615]
I tried to write `'F' || lpad(cast(numeric_column as varchar), 10, '0')`  as querydsl Expression: 
```
Expressions.stringOperation(
                    Ops.CONCAT,
                    Expressions.constant("F"),
                    StringExpressions.lpad(numericColumn.stringValue(), 10, '0')
                ) 
```
But it doesn't work because the final sql query for H2 is `?||lpad(cast(numericColumn as varchar)||?||'0')` in place of `?||lpad(cast(numericColumn as varchar), ?, '0')`.

I also tried `StringExpressions.lpad(numericColumn.stringValue(), 10, '0').prepend("F")` or `Expressions.stringTemplate("F").concat(
                    StringExpressions.lpad(numericColumn.stringValue(), 10, '0'))` . The result is the same.

Any idea ?

**Comment by jwgmeligmeyling** [comment]
The LPAD function with 3 parameters uses the `LPAD2` operator, for which a default template ([`lpad({0},{1},'{2s}'`](https://github.com/querydsl/querydsl/blob/426baeec6d5be6c3d5081a204a5ef2800ee68acf/querydsl-core/src/main/java/com/querydsl/core/types/Templates.java#L161)) is declared in `Templates` which is not overridden in `SQLTemplates` nor `H2Templates`.

So I don't think this is a problem *anymore*. Which version of QueryDSL are you on? And which type of `Templates` are you using?

**Comment by gzfhz** [comment]
Yes, it works well If only LPAD function like` StringExpressions.lpad(numericColumn.stringValue(), 10, '0')`. But when the LPAD function is concatenated with the constant string, it doesn't work any more. 
The version used is 4.2.2. QueryDSL is used with jpa and hibernate in a spring boot application. I don't know which Template is used because there is no particular configuration for it.

**Comment by jwgmeligmeyling** [comment]
Now thats interesting because the `HQLTemplates` and the `JPQLTemplates` use `concat(...)` for string concatenation. We don't even use the `||` operator there. So this is most likely a bug in your ORM provider and not Querydsl.

Could you provide a reproducer test case?

**Comment by gzfhz** [comment]
@jwgmeligmeyling you are right. The error is reproduced when hql is translated into sql by hibernate antlr. It seems that hql doesn't support lpad/rpad function. So I replace lpad function by substring `numericColumn.stringValue().prepend("00000000").substring(-1, 9).prepend("F")` and it works.

Thanks a lot for your help.
