### ISSUE TITLE
How to querydsl with spring-data-mongodb and gradle

### ISSUE THREAD

**Issue by viktorgt** [querydsl/querydsl#2617]
I'm unable to configure gradle to generate the query types for Querydsl. Following advices like #2444, my configuration looks as follows:

```
plugins {
	id 'org.springframework.boot' version '2.3.1.RELEASE'
	id 'io.spring.dependency-management' version '1.0.9.RELEASE'
	id 'java'
}

group = 'com.example'
version = '0.0.1-SNAPSHOT'
sourceCompatibility = '11'

repositories {
	mavenCentral()
}

dependencies {
	implementation 'org.springframework.boot:spring-boot-starter-data-mongodb'
	implementation 'org.springframework.boot:spring-boot-starter-web'

	compile 'com.querydsl:querydsl-mongodb:4.3.1'
	annotationProcessor 'com.querydsl:querydsl-apt:4.3.1:morphia'
	annotationProcessor 'org.springframework.boot:spring-boot-starter-data-mongodb'
}
```

The query types are not generated. 
Gradle version: 6.4.1

Unfortunately, the documentation provides only a configuration for maven and all other guides on the web seem to be deprecated.

Sample repository: [https://github.com/viktorgt/spring-mongo-querydsl](https://github.com/viktorgt/spring-mongo-querydsl)

**Comment by somudas93** [comment]
Hi @viktorgt please try this, I'm able to generate the Q-Classes with this.. hope it helps you and its also running for me.. Note I'm not using the Morphia annotations and the dependency, instead i'm using `@com.querydsl.core.annotations.QueryEntity` and as for your build.gradle 

```
compileOnly 'com.querydsl:querydsl-apt'
compile 'com.querydsl:querydsl-mongodb:4.3.1'
compile 'com.querydsl:querydsl-core'

annotationProcessor ('com.querydsl:querydsl-apt:4.3.1:general', 'javax.annotation:javax.annotation-api')
```

**Comment by viktorgt** [comment]
@somudas93 thank you a lot. This one actually works 👍

**Comment by PhilippS93** [comment]
We could also add `delete new File(projectDir, '/src/main/generated/').listFiles()` in the `doFirst` part of the `compileJava`, so old files will be overriden, when there are changes.
