### ISSUE TITLE
mongo dsl文件自定义

### ISSUE THREAD

**Issue by Pianaixiaoyu** [querydsl/querydsl#2618]
QuerydslBindingsFactory spring加载bean时写死dsl文件路径

**Comment by Pianaixiaoyu** [comment]
在jpa中都可以将dsl文件自定义路径放出来,为什么mongo就写死呢

**Comment by jwgmeligmeyling** [comment]
Google translate only brings me so far, what is the actual issue with QueryDSL code generation here?

**Comment by Pianaixiaoyu** [comment]
No problem, it works fine, I like it too, but in Mongo the DSL file mapping address can't be customized, it's a bit of a hassleNo problem, it works fine, I like it too, but in Mongo the DSL file mapping address can't be customized, it's a bit of a hassle
