### ISSUE TITLE
Using QueryDSL with JDBC, Spring Boot Data and Postgresql

### ISSUE THREAD

**Issue by kremerkp** [querydsl/querydsl#2619]
Hello, 
I just try to find out if it will be possible to use QueryDSL with Spring Boot Data JDBC and postgresql. 

I tried to follow your Website

https://github.com/querydsl/querydsl/tree/master/querydsl-sql

but cant get it running. 

I add dependencies and the plugin in my pom.xml as follows: 

```
<jdbcDriver>org.apache.derby.jdbc.EmbeddedDriver</jdbcDriver>
<jdbcUrl>jdbc:postgresql://localhost:5433/sandbox;create=true</jdbcUrl>
```

Result was: 

```
Failed to execute goal com.querydsl:querydsl-maven-plugin:4.3.1:export (default) on project jdbc-sandbox: No suitable driver found for jdbc:postgresql:localhost:5433/sandbox
```

Then I Changed to

```
<jdbcDriver>org.postgresql.Driver</jdbcDriver>
<jdbcUrl>jdbc:postgresql://localhost:5433/sandbox;create=true</jdbcUrl>
```

But then I get 

```
Failed to execute goal com.querydsl:querydsl-maven-plugin:4.3.1:export (default) on project jdbc-sandbox: org.postgresql.Driver -> [Help 1]
```

Is it possible at all to use QueryDSL with this configuration? What am I doing wrong? 

thanks in advance

**Comment by johnktims** [comment]
Have you added the postgres driver to your project?
Do you have postgres running on 5433(postgres runs on 5432 by default) with an existing `sandbox` database?

**Comment by kremerkp** [comment]
Hi, thanks for the quick answer. I just uploaded to project to github. Here you can find the pom.xml 

https://github.com/kremerkp/spring-boot-jdbc-querydsl/blob/master/pom.xml

Without QueryDSL I am allready able to use Spring Data JDBC. Configuration for that is in the application.properties. So Port and DB-Name are valid. 

https://github.com/kremerkp/spring-boot-jdbc-querydsl/blob/master/src/main/resources/application.properties

**Comment by kremerkp** [comment]
Hello John, 
thanks for your quick answer. I have taken a step further and got it running. The main issue was, that I did not add the postgresql Driver in the dependencies of the QueryDSL-Plugin. I also added jdbcuser and jdbcpassword to the pluginconfiguration. It know looks like:

```
<plugin>
				<groupId>com.querydsl</groupId>
				<artifactId>querydsl-maven-plugin</artifactId>
				<version>${querydsl.version}</version>
				<executions>
				<execution>
					<goals>
					<goal>export</goal>
					</goals>
				</execution>
				</executions>
				<configuration>
				<jdbcDriver>org.postgresql.Driver</jdbcDriver>
				<jdbcUrl>jdbc:postgresql://localhost:5433/sandbox</jdbcUrl>
				<jdbcUser>myuser</jdbcUser>
				<jdbcPassword>mypassword</jdbcPassword>
				<packageName>lu.eyet.qclasses</packageName>
				<targetFolder>${project.basedir}/target/generated-sources/java</targetFolder>
				</configuration>
				<dependencies>
					<dependency>
						<groupId>org.postgresql</groupId>
						<artifactId>postgresql</artifactId>
						<version>42.1.1</version>
					</dependency>
				</dependencies>
			</plugin>
```
