### ISSUE TITLE
@QuerydslPredicate

### ISSUE THREAD

**Issue by 0703gaoxiaobo** [querydsl/querydsl#2623]
@QuerydslPredicate(root = SysUser.class) Predicate predicate    

How to use like，ne ...   in parameters

**Comment by jwgmeligmeyling** [comment]
This is a Spring Data annotation and is not from QueryDSL itself. Your question is better asked at one of the Spring forums 😄

**Comment by 0703gaoxiaobo** [comment]
> This is a Spring Data annotation and is not from QueryDSL itself. Your question is better asked at one of the Spring forums 😄

thank you
