### ISSUE TITLE
how can I conver  query result DateTimePath to NumberPath？

### ISSUE THREAD

**Issue by RobertoHuang** [querydsl/querydsl#2629]
The type in the database is DateTimestamp type, 
I want to query in Java that converted to Long type， what can I do？

**Comment by RobertoHuang** [comment]
i try to use milliSecond()， but got

java.lang.IllegalArgumentException: Unsupported expression millisecond

**Comment by jwgmeligmeyling** [comment]
`milliSecond()` is supported for dialects that support it. It returns the milliseconds portion of the timestamp however, not the time since Linux epoch.

What is the dialect you're using?

**Comment by RobertoHuang** [comment]
i am using JPA with mysql database

**Comment by jwgmeligmeyling** [comment]
JPQL, the query language of JPA, does not define any date extract functions. Hibernates proprietairy HQL declares a bunch of date extract functions, but millSeconds nor epoch isn't one of them. As such, this is not a QueryDSL limitation, but a limitation of your query language.

What you need to do is define a custom function for your ORM (presumably Hibernate), and then define a custom template in QueryDSL. See also my answer on this Stackoverflow question: https://stackoverflow.com/questions/40744385/querydsl-4-with-rownumber-window-function/62200160#62200160 .
