### ISSUE TITLE
Why querydsl-jpa not support hibernate's annotation @Filter and @FilterDef

### ISSUE THREAD

**Issue by HopscotchSen** [querydsl/querydsl#2633]
How to use querydsl-jpa with Hibernate's annotation @Filter and @FilterDef? 

I am trying to use hibernate @Filter annotation or interceptor dynamically add where clauses with querydsl, but it does not work. is it actually supposed to work together ?

Thanks in advance.

**Comment by jwgmeligmeyling** [comment]
Just enable the filter before executing the query.

Did you manage to get it to work?
