### ISSUE TITLE
Hi, Is there have any way to generate a userself bean.

### ISSUE THREAD

**Issue by zfavourite99** [querydsl/querydsl#2634]
I am using querydsl-maven-plugin, my configuration is:
```
<plugin>
	<groupId>com.querydsl</groupId>
	<artifactId>querydsl-maven-plugin</artifactId>
	<version>4.3.1</version>
	<configuration>
		<jdbcDriver>com.mysql.jdbc.Driver</jdbcDriver>
		<jdbcUrl>jdbc:mysql://****?useUnicode=true</jdbcUrl>
		<jdbcUser>***</jdbcUser>
		<jdbcPassword>***</jdbcPassword>
		<exportForeignKeys>false</exportForeignKeys>
		<packageName>com.**.entity.qentity</packageName>
		<targetFolder>${project.basedir}/src/main/java</targetFolder>
		<sourceFolder>src/main/resources</sourceFolder>
		<exportBeans>true</exportBeans>
		<beanAddFullConstructor>true</beanAddFullConstructor>
		<beanAddToString>true</beanAddToString>
		<beanPackageName>com.**.entity</beanPackageName>
		<tableNamePattern>%</tableNamePattern>
		<customTypes>
			<customType>com.querydsl.sql.types.UtilDateType</customType>
		</customTypes>
	</configuration>
	<dependencies>
		<dependency>
			<groupId>mysql</groupId>
			<artifactId>mysql-connector-java</artifactId>
			<version>5.1.44</version>
		</dependency>
	</dependencies>
</plugin>
```
now i double click maven -> plugin -> querydsl -> querydsl:export, like image show:
![image](https://user-images.githubusercontent.com/2630290/89997915-646dc080-dcbf-11ea-87e8-07377d1c0f60.png)

i get a bean like this:
```
import javax.annotation.Generated;

/**
 * Config is a Querydsl bean type
 */
@Generated("com.querydsl.codegen.BeanSerializer")
public class Config {

    public Config() {
    }

    public Config(Integer configid) {
        this.configid = configid;
    }

    private Integer configid;

    public Integer getConfigid() {
        return configid;
    }

    public void setConfigid(Integer configid) {
        this.configid = configid;
    }

    @Override
    public String toString() {
         return "configid = " + configid;
    }

}
```
but i want get bean like this:
```

import io.swagger.annotations.ApiModelProperty;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.ToString;

import javax.annotation.Generated;

/**
 * Config is a Querydsl bean type
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
@ToString
@Generated("com.querydsl.codegen.BeanSerializer")
public class Config {

    @ApiModelProperty(value = "config id")
    private Integer configid;

}
```

`@ApiModelProperty(value = "config id")`, "config id" is table field's comment. see image:

![image](https://user-images.githubusercontent.com/2630290/89999038-e01c3d00-dcc0-11ea-8527-2ed897b7cfe8.png)
 

Is there any way to generate the result I want?

**Comment by jwgmeligmeyling** [comment]
Lombok is a code generation tool, so is APT or the QueryDSL export task. There is absolutely no need for Lombok in generated code. The code is aught to be not touched again. The purpose of code generation is that it can be regenerated if the context changes, which would reset your own changes anyway.

As for annotating the generated fields with an additional parameter, in this case `@ApiModelProperty` - no, that is currently not possible.

Your're probably better of separating your domain and presentation layer anyway, so I would recommend writing a seperate class for this and just map between the two. You could have a look at MapStruct (https://mapstruct.org/), it probably gets the job done!

Alternatively, you could slightly alter the exporter and use this custom exporter on your project. The code is available in this repository!

**Comment by zfavourite99** [comment]
@jwgmeligmeyling Thanks for your answer. For alter the exporter, I think it is more suitable for my situation. But I don't know how to customize the exporter. Are there any examples?

**Comment by zfavourite99** [comment]
@jwgmeligmeyling Hello, I have completed the task using mapstruct. Thank you.
