### ISSUE TITLE
querydsl  jpa 将常量加入查询结果怎么写法？

### ISSUE THREAD

**Issue by chen527522066** [querydsl/querydsl#2637]
select 1 a from dual;
这样的写法怎么写，没有找到，常量1  对应别名a

**Comment by jwgmeligmeyling** [comment]
`select(Expressions.numberTemplate("1").as("a"))` will do the trick.

**Comment by chen527522066** [comment]
> `select(Expressions.numberTemplate("1").as("a"))` will do the trick.

thank you！
