### ISSUE TITLE
Querydsl-core: medium severity vulnerability found on com.google.guava:guava@18.0

### ISSUE THREAD

**Issue by s-jepsen** [querydsl/querydsl#2646]
According to Snyk securityscan of Querydsl 4.3.1, there is a medium severity vulnerability found on com.google.guava:guava@18.0.

[WARNING] ✗ medium severity vulnerability found on com.google.guava:guava@18.0
[WARNING] - desc: Deserialization of Untrusted Data
[WARNING] - info: https://snyk.io/vuln/SNYK-JAVA-COMGOOGLEGUAVA-32236
[WARNING] - from: com.querydsl:querydsl-core@4.3.1 > com.google.guava:guava@18.0

See remediation:
https://snyk.io/vuln/SNYK-JAVA-COMGOOGLEGUAVA-32236

**Comment by jwgmeligmeyling** [comment]
Do don't have to use Guava 18.0, as long as any version of Guava is provided it is fine. We require 18.0 minimally. So its recommended to just bump the version  of Guava in your project.
