### ISSUE TITLE
Dependency conflicts on org.mongodb:mongo-java-driver, leading to inconsistent program behaviors

### ISSUE THREAD

**Issue by HelloCoCooo** [querydsl/querydsl#2647]
Hi, in **querydsl-QUERYDSL_4_3_1/querydsl-mongodb**, there are mulptiple versions of library **org.mongodb:mongo-java-driver**. However, according to Maven's dependency management strategy: **_"first declaration wins"_**, only **org.mongodb:mongo-java-driver:3.5.0** can be loaded, and **org.mongodb:mongo-java-driver:3.4.0** will be shadowed.

**In total, there are 18 conflicting API pairs between these two library version.**

As shown in the following figure, your project expects to invoke method **_<com.mongodb.MongoClientOptions: equals(Ljava/lang/Object;)Z>_**  in library _**org.mongodb:mongo-java-driver:3.4.0**_ (along the _original dependency path_). As it has been shadowed, this method defined in **_org.mongodb:mongo-java-driver:3.5.0_** is actually forced to be referenced via the following invocation path (along the _actual dependency path_):

```
<com.querydsl.mongodb.morphia.MorphiaSerializer: visit(Lcom/querydsl/core/types/Constant;Ljava/lang/Void;)Ljava/lang/Object;> /home/wwww/wangSensor/unzip/querydsl-QUERYDSL_4_3_1/querydsl-mongodb/target/classes
<org.mongodb.morphia.mapping.Mapper: toMongoObject(Lorg/mongodb/morphia/mapping/MappedField;Lorg/mongodb/morphia/mapping/MappedClass;Ljava/lang/Object;)Ljava/lang/Object;> /home/wwww/.m2/repository/org/mongodb/morphia/morphia/1.3.2/morphia-1.3.2.jar
<org.mongodb.morphia.mapping.Mapper: getMappedClass(Ljava/lang/Object;)Lorg/mongodb/morphia/mapping/MappedClass;> /home/wwww/.m2/repository/org/mongodb/morphia/morphia/1.3.2/morphia-1.3.2.jar
<org.mongodb.morphia.mapping.Mapper: addMappedClass(Lorg/mongodb/morphia/mapping/MappedClass;Z)Lorg/mongodb/morphia/mapping/MappedClass;> /home/wwww/.m2/repository/org/mongodb/morphia/morphia/1.3.2/morphia-1.3.2.jar
<relocated.morphia.org.apache.commons.collections.ReferenceMap: put(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;> /home/wwww/.m2/repository/org/mongodb/morphia/morphia/1.3.2/morphia-1.3.2.jar
<com.mongodb.MongoClientOptions: equals(Ljava/lang/Object;)Z>
```

![querydsl-QUERYDSL](https://user-images.githubusercontent.com/46306510/93574291-d2965900-f9ca-11ea-9f26-1a683d14e9f4.png)

Although both of these conflicting libraries contain the referenced methods (**_with the same signature_**), they have **_different implementations_**. This issue will not cause runtime crashes, but it can introduce inconsistent semantic program hehaviors----

Code snippet of **_<com.mongodb.MongoClientOptions: equals(Ljava/lang/Object;)Z>_** in _**org.mongodb:mongo-java-driver:3.4.0**_  (shadowed but expected to invoke method):

<details><summary>detailed method body</summary>

```java
@Override
    public boolean equals(final Object o) {
......
        if (!commandListeners.equals(that.commandListeners)) {
            return false;
        }
        if (!clusterListeners.equals(that.clusterListeners)) {
            return false;
        }
        if (!serverListeners.equals(that.serverListeners)) {
            return false;
        }
......

        return true;
    }
```

</details>

Code snippet of **__** in _**org.mongodb:mongo-java-driver:3.5.0**_ (loaded version):

<details><summary>detailed method body</summary>

```java
@Override
    public boolean equals(final Object o) {
......
        if (!clusterListeners.equals(that.clusterListeners)) {
            return false;
        }
        if (!commandListeners.equals(that.commandListeners)) {
            return false;
        }
......
        return true;
    }
```

</details>

**The detailed informantion of the remaining 17 conflicting API pairs can be found in the following attachment.**
[18 conflicting API pairs in project querydsl-mongodb.txt](https://github.com/querydsl/querydsl/files/5428292/18.conflicting.API.pairs.in.project.querydsl-mongodb.txt)

## **Dependency tree--**

[INFO] com.querydsl:querydsl-mongodb:jar:4.3.1
[INFO] +- **org.mongodb:mongo-java-driver:jar:3.5.0:compile**
[INFO] +- org.mongodb.morphia:morphia:jar:1.3.2:compile
[INFO] |  +- **(org.mongodb:mongo-java-driver:jar:3.4.0:compile - omitted for conflict with 3.5.0)**
[INFO] |  +- cglib:cglib-nodep:jar:2.2.2:compile
[INFO] |  \- (com.thoughtworks.proxytoys:proxytoys:jar:1.0:compile - omitted for duplicate)
[INFO] +- com.thoughtworks.proxytoys:proxytoys:jar:1.0:compile
[INFO] +- com.querydsl:querydsl-core:jar:4.3.1:compile
[INFO] |  +- com.google.guava:guava:jar:18.0:compile
[INFO] |  +- com.google.code.findbugs:jsr305:jar:1.3.9:compile
[INFO] |  +- com.mysema.commons:mysema-commons-lang:jar:0.2.4:compile
[INFO] |  \- com.infradna.tool:bridge-method-annotation:jar:1.13:compile
[INFO] +- com.querydsl:querydsl-apt:jar:4.3.1:provided
[INFO] |  \- com.querydsl:querydsl-codegen:jar:4.3.1:provided
[INFO] |     +- (com.querydsl:querydsl-core:jar:4.3.1:provided - omitted for duplicate)
[INFO] |     +- com.mysema.codegen:codegen:jar:0.6.8:provided
[INFO] |     |  +- (com.google.guava:guava:jar:18.0:provided - omitted for duplicate)
[INFO] |     |  \- org.eclipse.jdt.core.compiler:ecj:jar:4.3.1:provided
[INFO] |     +- javax.inject:javax.inject:jar:1:provided
[INFO] |     \- (org.reflections:reflections:jar:0.9.9:provided - omitted for duplicate)
[INFO] +- org.slf4j:slf4j-api:jar:1.6.1:compile
[INFO] +- org.slf4j:slf4j-log4j12:jar:1.6.1:provided
[INFO] |  +- (org.slf4j:slf4j-api:jar:1.6.1:provided - omitted for duplicate)
[INFO] |  \- log4j:log4j:jar:1.2.16:provided
[INFO] +- com.querydsl:querydsl-core:test-jar:tests:4.3.1:test
[INFO] |  +- (com.google.guava:guava:jar:18.0:test - omitted for duplicate)
[INFO] |  +- (com.google.code.findbugs:jsr305:jar:1.3.9:test - omitted for duplicate)
[INFO] |  +- (com.mysema.commons:mysema-commons-lang:jar:0.2.4:test - omitted for duplicate)
[INFO] |  \- (com.infradna.tool:bridge-method-annotation:jar:1.13:test - omitted for duplicate)
[INFO] +- junit:junit:jar:4.12:test
[INFO] |  \- org.hamcrest:hamcrest-core:jar:1.3:test
[INFO] +- org.hamcrest:hamcrest-library:jar:1.3:test
[INFO] |  \- (org.hamcrest:hamcrest-core:jar:1.3:test - omitted for duplicate)
[INFO] +- org.easymock:easymock:jar:3.0:test
[INFO] |  \- org.objenesis:objenesis:jar:1.2:test
[INFO] +- org.reflections:reflections:jar:0.9.9:test
[INFO] |  +- (com.google.guava:guava:jar:15.0:test - omitted for conflict with 18.0)
[INFO] |  +- org.javassist:javassist:jar:3.18.2-GA:test
[INFO] |  \- com.google.code.findbugs:annotations:jar:2.0.1:test
[INFO] \- org.codehaus.mojo:animal-sniffer-annotations:jar:1.18:compile

## **Suggested solutions:**

**Solution1:** Remove the conflicting Jars.

**Solution2:** Downgrade direct dependency version org.mongodb:mongo-java-driver from 3.5.0 to 3.4.0.

Thanks.
Best regards,
Coco

**Comment by HelloCoCooo** [comment]
Executing the following test case on **org.xerial.snappy:snappy-java:1.1.1.6** and **1.6** separately, the risky method **_<org.xerial.snappy.SnappyOutputStream: write([BII)V>_** will get different return values:

```java
@Test(timeout = 4000)
    public void test01()  throws Throwable  {
        Base64 base64 = new Base64();
        byte[] byteArray0 = new byte[]{(byte) 25, (byte) 76, (byte) 56};
        byte[] byteArray1 = base64.decodeBase64(byteArray0);
        assertEquals(1, byteArray1.length);
    }
```

Output results:

```java
byteArray1.length == 1   //On **org.xerial.snappy:snappy-java:1.1.2.6**

byteArray1.length == 2    //On **org.xerial.snappy:snappy-java:1.1.1.6**
```

Variable **_token_** (defined in class **org.apache.http.impl.auth.GGSSchemeBase** of library **org.apache.httpcomponents:httpclient:jar:4.3.6**) is assigned by the return value of method **_<org.xerial.snappy.SnappyOutputStream: write([BII)V>_**.

As such, **_token_** value would be changed when the client project references **_org.xerial.snappy:snappy-java:1.1.1.6_** (compared with the shadowed but expected version **_1.6_**), which could affect program semantic behaviors. 


```java
@Override
    protected void parseChallenge(
            final CharArrayBuffer buffer,
            final int beginIndex, final int endIndex) throws MalformedChallengeException {
        final String challenge = buffer.substringTrimmed(beginIndex, endIndex);
        if (log.isDebugEnabled()) {
            log.debug("Received challenge '" + challenge + "' from the auth server");
        }
        if (state == State.UNINITIATED) {
            token = Base64.decodeBase64(challenge.getBytes());
            state = State.CHALLENGE_RECEIVED;
        } else {
            log.debug("Authentication already attempted");
            state = State.FAILED;
        }
    }
```

**Comment by HelloCoCooo** [comment]
@johnktims Could please help me check this issue?
May I pull a request to fix it?
Thanks again.

**Comment by jwgmeligmeyling** [comment]
Feel free to provide a patch.
