### ISSUE TITLE
Order ignoreCase with column date generate SQL inconsistent

### ISSUE THREAD

**Issue by marcusvoltolim** [querydsl/querydsl#2648]
Ordering with ignore case in a date field is generating an **order by lower** (date column) which totally bugs the sorting result, using pure Spring-JPA no problem occurs.

**Spring-JPA**
![image](https://user-images.githubusercontent.com/9442331/93636095-b2b26580-f9c9-11ea-8131-b705cbfeb2d1.png)

**QueryDSL**
![image](https://user-images.githubusercontent.com/9442331/93636076-a928fd80-f9c9-11ea-8a8f-184a5666d169.png)
Add "lower" ignoring the column type

**Comment by marcusvoltolim** [comment]
**Spring-JPA**
![image](https://user-images.githubusercontent.com/9442331/93636095-b2b26580-f9c9-11ea-8131-b705cbfeb2d1.png)

**QueryDSL**
![image](https://user-images.githubusercontent.com/9442331/93636076-a928fd80-f9c9-11ea-8a8f-184a5666d169.png)
Add "lower" ignoring the column type

**Comment by jwgmeligmeyling** [comment]
`buildOrderPropertyPathFrom` does not exists in QueryDSL anymore, please upgrade to a more recent version of QueryDSL.

For example:

```xml
<dependency>
    <groupId>com.querydsl</groupId>
    <artifactId>querydsl-jpa</artifactId>
    <version>4.3.1</version>
</dependency>
```

**Comment by marcusvoltolim** [comment]
134/5000
I am using version 4.3.1. I'm using Sort and not QSort, the Sort is converted to OrderSpecifier using buildOrderPropertyPathFrom

**Comment by jwgmeligmeyling** [comment]
`Sort` and `QSort` aren't classes in QueryDSL, and `buildOrderPropertyPathFrom` doesn't exist in our entire codebase: https://github.com/querydsl/querydsl/search?q=buildOrderPropertyPathFrom&unscoped_q=buildOrderPropertyPathFrom .

Are you sure this isn't an issue in Spring Data instead?

Also, please verify the dependencies you're actually using with `mvn dependency:tree` or anything equivalent.

**Comment by jwgmeligmeyling** [comment]
Here is your bug, in Spring Data instead: https://github.com/spring-projects/spring-data-jpa/blob/e27933455efa6d1821dea23abd2bbe109b5d59a7/src/main/java/org/springframework/data/jpa/repository/support/Querydsl.java#L238-L241 . Please file an issue there 😄

**Comment by marcusvoltolim** [comment]
Yes, 

> Aqui está seu bug, no Spring Data: [https://github.com/spring-projects/spring-data-jpa/blob/e27933455efa6d1821dea23abd2bbe109b5d59a7/src/main/java/org/springframework/data/jpa/repository/support/ Querydsl.java # L238-L241](https://github.com/spring-projects/spring-data-jpa/blob/e27933455efa6d1821dea23abd2bbe109b5d59a7/src/main/java/org/springframework/data/jpa/repository/support/Querydsl.java#L238-L241) . Registre um problema lá😄

Yes, you are right, thank you very much, I was creating 1 test case to open the issue there!
