### ISSUE TITLE
Handle JPA Convert annotation in determining property type

### ISSUE THREAD

**Issue by jwgmeligmeyling** [querydsl/querydsl#2652]
Currently, a `List` mapped as a basic type is represented in the metamodel as a `ListPath`, where the actual query type should be derived from the destination type of the attribute converter (String usually).

See also #2651

**Comment by Credo-Zhao** [comment]
> Currently, a mapped as a basic type is represented in the metamodel as a , where the actual query type should be derived from the destination type of the attribute converter (String usually).`List``ListPath`
> 
> See also #2651

Let me add some code

entity：
`@QueryType(PropertyType.STRING)
    @Convert(converter = BaseListJsonConverter.class)
    @Column(name = "log_list_json", columnDefinition = "text")
    private List<SimpleLog> logList;`

test：
        `QSmsSetting qSmsSetting = QSmsSetting.smsSetting;
        JPAUpdateClause jpaUpdateClause = jpaQueryFactory.update(qSmsSetting);
        List<SimpleLog> logList2 = new ArrayList<>();
        SimpleLog simpleLog1 = SimpleLog.builder().notes("1xxxxx").bizDate(LocalDateTime.now()).build();
        SimpleLog simpleLog2 = SimpleLog.builder().notes("2xxxxx").bizDate(LocalDateTime.now()).build();
        logList2.add(simpleLog1);
        logList2.add(simpleLog2);

        jpaUpdateClause.set(qSmsSetting.logList, this.objectMapper.writeValueAsString(logList2));
//      if entity no @QueryType(PropertyType.STRING) use--->  jpaUpdateClause.set(qSmsSetting.logList, logList2);
        long xx=jpaUpdateClause.where(qSmsSetting.tenantId.eq("XXX")).execute();`

Exception

With or without @QueryType(PropertyType.STRING),All the same Exception.

`java.lang.IllegalArgumentException: Parameter value [SimpleLog(realName=null, bizDate=2020-09-30T11:28:10.985654, event=null, notes=1xxxxx)] did not match expected type [java.util.List (n/a)]

	at org.hibernate.query.spi.QueryParameterBindingValidator.validate(QueryParameterBindingValidator.java:54)
	at org.hibernate.query.spi.QueryParameterBindingValidator.validate(QueryParameterBindingValidator.java:27)
	at org.hibernate.query.internal.QueryParameterBindingImpl.validate(QueryParameterBindingImpl.java:90)
	at org.hibernate.query.internal.QueryParameterBindingImpl.setBindValue(QueryParameterBindingImpl.java:55)
	at org.hibernate.query.internal.QueryParameterBindingsImpl.expandListValuedParameters(QueryParameterBindingsImpl.java:640)
	at org.hibernate.query.internal.AbstractProducedQuery.doExecuteUpdate(AbstractProducedQuery.java:1629)
	at org.hibernate.query.internal.AbstractProducedQuery.executeUpdate(AbstractProducedQuery.java:1612)
	at com.querydsl.jpa.impl.JPAUpdateClause.execute(JPAUpdateClause.java:77)`

**Comment by jwgmeligmeyling** [comment]
The case without `QueryType(PropertyType.STRING` is actually a Hibernate bug though 😉

**Comment by Credo-Zhao** [comment]
> The case with `QueryType(PropertyType.STRING` is actually a Hibernate bug though 😉

Yes, you're right.I ran a lot of tests today.
Now run UPDATE JPQL using the EntityManager, with the same error.
Only run em.persist(entity) or em.merge(entity),It can be handled correctly.

Sad...

**Comment by jwgmeligmeyling** [comment]
Its so weird that an actually standard JPA feature gives so many issues in the query language... Seems like a bit of an after thought...

**Comment by Credo-Zhao** [comment]
> Its so weird that an actually standard JPA feature gives so many issues in the query language... Seems like a bit of an after thought...

Yes, I don't understand either.

**Comment by cnlinjie** [comment]
Sad to meet the same problem

**Comment by Nhoutain** [comment]
I simply want to share my experience about this bug.

## Model
I have an entity like
```
@Entity
public class JobLog {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private String id;

    @QueryType(PropertyType.STRING)
    private LocalizedString message;
}
```

## Issue
I want to perform some predicate about message. Unfortunately, with this configuration, I can't do this
```
predicates.and(jobLog.message.likeIgnoreCase(escapedTextFilter));
```

because I have the same issues that all people! 

## Solution
But I find a way to workaround :)

```
predicates.and(
	(jobLog.id.likeIgnoreCase(escapedTextFilter).and(jobLog.id.isNull()))
    .or(jobLog.message.likeIgnoreCase(escapedTextFilter)));

```

Why it work?
* It's important that `escapedTextFilter` is the same in both predicate!
* Indeed, in this case, the constant is converter to SQL in the first predicate (which is of String type). And in the second predicate, we use the conterted value

Bad thing?
* Add a performance overflow because we have OR in predicate

---

Hope this can help someone :)

**Comment by jwgmeligmeyling** [comment]
I don't see what problem the above is trying to solve, why `escapedTextFilter` is a predicate, nor why `jobLog.message.likeIgnoreCase(escapedTextFilter)` would in any scenario be functionally equivalent to `jobLog.id.likeIgnoreCase(escapedTextFilter).and(jobLog.id.isNull())).or(jobLog.message.likeIgnoreCase(escapedTextFilter))`, but hopefully someone can take benefit from it...

**Comment by Nhoutain** [comment]
Okey, I firstly think that we meet the same issue, but I face another issue. 
My issue appear when I need to use an attribute define with `@QueryType`.
May be this comment must appear in another ticket

Firstly, `jobLog.message.likeIgnoreCase(escapedTextFilter)` doesn't work. I receive a message such that QueryDSL expect that `escapteTextFilter` must be a `LocalizedString`. It's completely wrong, because in DB, the field `jobLog.message` is a varchar. This is the stacktrace:
```
Caused by: java.lang.IllegalArgumentException: Parameter value [%xx%] did not match expected type [com.emasphere.common.type.localization.LocalizedString (n/a)]
	at org.hibernate.query.spi.QueryParameterBindingValidator.validate(QueryParameterBindingValidator.java:54)
	at org.hibernate.query.spi.QueryParameterBindingValidator.validate(QueryParameterBindingValidator.java:27)
	at org.hibernate.query.internal.QueryParameterBindingImpl.validate(QueryParameterBindingImpl.java:90)
	at org.hibernate.query.internal.QueryParameterBindingImpl.setBindValue(QueryParameterBindingImpl.java:55)
	at org.hibernate.query.internal.AbstractProducedQuery.setParameter(AbstractProducedQuery.java:512)
	at org.hibernate.query.internal.AbstractProducedQuery.setParameter(AbstractProducedQuery.java:115)
	at com.querydsl.jpa.impl.JPAUtil.setConstants(JPAUtil.java:56)
	at com.querydsl.jpa.impl.AbstractJPAQuery.createQuery(AbstractJPAQuery.java:102)
	at com.querydsl.jpa.impl.AbstractJPAQuery.createQuery(AbstractJPAQuery.java:94)
	at com.querydsl.jpa.impl.AbstractJPAQuery.fetch(AbstractJPAQuery.java:201)
	at org.springframework.data.jpa.repository.support.QuerydslJpaPredicateExecutor.findAll(QuerydslJpaPredicateExecutor.java:162)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.data.repository.core.support.ImplementationInvocationMetadata.invoke(ImplementationInvocationMetadata.java:72)
	at org.springframework.data.repository.core.support.RepositoryComposition$RepositoryFragments.invoke(RepositoryComposition.java:382)
	at org.springframework.data.repository.core.support.RepositoryComposition.invoke(RepositoryComposition.java:205)
	at org.springframework.data.repository.core.support.RepositoryFactorySupport$ImplementationMethodExecutionInterceptor.invoke(RepositoryFactorySupport.java:550)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.data.repository.core.support.QueryExecutorMethodInterceptor.doInvoke(QueryExecutorMethodInterceptor.java:155)
	at org.springframework.data.repository.core.support.QueryExecutorMethodInterceptor.invoke(QueryExecutorMethodInterceptor.java:130)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.data.projection.DefaultMethodInvokingMethodInterceptor.invoke(DefaultMethodInvokingMethodInterceptor.java:80)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:367)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:118)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:139)
	... 103 common frames omitted
```

Secondly, `jobLog.id.likeIgnoreCase(escapedTextFilter).and(jobLog.id.isNull())).or(jobLog.message.likeIgnoreCase(escapedTextFilter))` is functionnally equivalent because `jobLog.id` is NEVER null in my case. So, the first condition is always FALSE and the result only depend of the second part `jobLog.message.likeIgnoreCase(escapedTextFilter)`.

---

So, what's the point? My understanding is that in the first scenario, the engine try to convert the parameter `escapedTextFilter` based on the java type (`LocalizedString`) instead of the db type (`String`). He doesn't take in account the fact that there is a `@QueryType`.
In the second scenario, the engine convert the `escapeTextFilter` based on the java type of `jobLog.id` (which is `String`) and there successfully convert it. When he want to convert the second part of the predicate, the engine REUSE the already converter parameter (to avoid convert it again and again). In that case, the engine successfully convert the predicate.

---

At the end:
* Predicate are equivalent because of `jobLog.id.isNull()` which is always FALSE
* It's just a workaround, where you need to use the parameter in another predicate with a `String` attribute in order to convert it correctly and then reuse later, which workaround the bug.

**Comment by jwgmeligmeyling** [comment]
Please try `Expressions.FALSE.or(jobLog.message.likeIgnoreCase(escapedTextFilter))` for the same purpose.

**Comment by Nhoutain** [comment]
@jwgmeligmeyling : I guess that you don't understand the workaround. The workaround is not to add a `OR` condition. The workaround is to add `escapedTextFilter` (meaning the same parameter) in another predicate before!

```
(jobLog.id.likeIgnoreCase(escapedTextFilter).and(Expressions.FALSE)).or(jobLog.message.likeIgnoreCase(escapedTextFilter))
```

The main point is to have `jobLog.id.likeIgnoreCase(escapedTextFilter)` before the other predicate. (Assuming that `jobLog.id` refer a String)

**Comment by jwgmeligmeyling** [comment]
Then try:

```
jobLog.message.likeIgnoreCase(
  ConstantImpl.create(new TypedParameterValue(StringType.INSTANCE, escapedTextFilter)
)
```

**Comment by Nhoutain** [comment]
Unfortunately, it doesn't work.. The engine still try to match the constant type (String) with the `jobLog.message` type (LocalizedString) without take in account the @QueryType

**Comment by jwgmeligmeyling** [comment]
Very weird. In Blaze-Persistence you could probably work around this issue using `JPQLNextExpressions.treat(String.class, jobLog.message).likeIgnoreCase(escapedTextFilter)`. In plain Hibernate, `TREAT_STRING` is not a function.

**Comment by monster5475** [comment]
**Firstly, my English is pool. So if I have some error, ignore it.**

I find one way to solve this problem, main ideas is use mysql function `cast(xx as char)`  to cheat hibrenate. Below is my base info. My code is work for company, so I make an example.

```java
// StudentRepo.java
public interface StudentRepo<Student, Long> extends JpaRepository<Student, Long>,  QuerydslPredicateExecutor<Student>, JpaSpecificationExecutor<Student> {
}

// Student.java
@Data
@AllArgsConstructor
@NoArgsConstructor
@EqualsAndHashCode(of = "id")
@Entity
@Builder
@Table(name = "student")
public class Student {
    @Convert(converter = ClassIdsConvert.class)
    private List<String> classIds;
    
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
}

// ClassIdsConvert.java
public class ClassIdsConvert implements AttributeConverter<List<String>, String> {
    @Override
    public String convertToDatabaseColumn(List<String> ips) {
        // classid23,classid24,classid25
        return String.join(",", ips);
    }
    @Override
    public List<String> convertToEntityAttribute(String dbData) {
        if (StringUtils.isEmpty(dbData)) {
            return null;
        } else {
            return Stream.of(dbData.split(",")).collect(Collectors.toList());
        }
    }
}
```



my db is below

| id   | classIds    | name | address |
| ---- | ----------- | ---- | ------- |
| 1    | 2,3,4,11    | join | 北京市  |
| 2    | 2,31,14,11  | hell | 福建省  |
| 3    | 2,12,22,33  | work | 福建省  |
| 4    | 1,4,5,6     | ouy  | 广东省  |
| 5    | 11,31,34,22 | yup  | 上海市  |

```sql
-- ----------------------------
-- Table structure for student
-- ----------------------------
DROP TABLE IF EXISTS `student`;
CREATE TABLE `student`  (
  `id` int(11) NOT NULL,
  `classIds` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL,
  `name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL,
  `address` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL,
  PRIMARY KEY (`id`) USING BTREE
) ENGINE = InnoDB CHARACTER SET = utf8mb4 COLLATE = utf8mb4_general_ci ROW_FORMAT = Dynamic;

SET FOREIGN_KEY_CHECKS = 1;
```



1. Use `JpaSpecificationExecutor` solve the problem

```java
Specification<Student> specification = (root, query, criteriaBuilder) -> {
    String classId = "classid24"
    String classIdStr = StringUtils.wrap(classId, "%");
    var predicate = criteriaBuilder.like(root.get("classIds").as(String.class), classIdStr);
    return criteriaBuilder.or(predicate);
};
var students = studentRepo.findAll(specification);
log.info(new Gson().toJson(students))
```



>attention the code `root.get("classIds").as(String.class)`
>
>In my opinion, if not add `.as(String.class)` , hibnerate will think the type of  `student.classIds`  is list. And throw Exception as below.
>
>SQL will like below which can run correct in mysql. But hibnerate cann't work.

```sql
org.springframework.dao.InvalidDataAccessApiUsageException: Parameter value [%classid24%] did not match expected type [java.util.List (n/a)]; nested exception is java.lang.IllegalArgumentException: Parameter value [%classid24%] did not match expected type [java.util.List (n/a)]
    
SELECT
	student0_.id AS id1_0_,
	student0_.class_ids AS class_ids2_0_
FROM
	student student0_ 
WHERE
 	student0_.class_ids LIKE '%classid24%' ESCAPE '!'
```



> if you add `.as(String.class)` , hibnerate will think the type of  `student.classIds`  as string. And don't check it at all.
>
>SQL will like below which can run correct in mysql. Also in JPA.

```sql
SELECT
	student0_.id AS id1_0_,
	student0_.class_ids AS class_ids2_0_
FROM
	student student0_ 
WHERE
 	cast( student0_.class_ids AS CHAR ) LIKE '%classid24%' ESCAPE '!'
```



2. when the problem is solve by `JpaSpecificationExecutor`, so I think this may can solve also in querydsl. At last I find the `template` idea in querydsl.

```java
String classId = "classid24";
StringTemplate st = Expressions.stringTemplate("cast({0} as string)", qStudent.classIds);
var students = Lists.newArrayList<studentRepo.findAll(st.like(StringUtils.wrap(classId, "%"))));
log.info(new Gson().toJson(students));
```

it's sql is like below.

```sql
SELECT
	student0_.id AS id1_0_,
	student0_.class_ids AS class_ids2_0_
FROM
	student student0_ 
WHERE
 	cast( student0_.class_ids AS CHAR ) LIKE '%classid24%' ESCAPE '!'
```

**Comment by Tarrowren** [comment]
```java
@Convert(converter = HelloData.ObjectConverter.class)
private HelloData data;

@QueryType(PropertyType.SIMPLE)
@Convert(converter = HelloData.ArrayConverter.class)
private List<HelloData> datas;
```
```java
public final SimplePath<HelloData> data = createSimple("data", HelloData.class);
public final SimplePath<java.util.List<HelloData>> datas = createSimple("datas", java.util.List.class);
```

The problem seems to be with type validation, do we have a comment to turn off type validation for this field?
Or we may need a "ListSimplePath"

**Comment by x403368945** [comment]
Change to array 

`
    @Convert(converter = BaseListJsonConverter.class)
    @Column(name = "log_list_json", columnDefinition = "text")
    private SimpleLog[] logList;
`
