### ISSUE TITLE
I can’t find plugin 

### ISSUE THREAD

**Issue by NikitaKochkurov** [querydsl/querydsl#2653]
Hello, I try generate PointPath for Point class from https://mvnrepository.com/artifact/org.locationtech . If I right understood from documentation need using plugin (2.4.2. Code generation via Maven), but plugin doesn’t exist. Please can someone explain what is wrong? Thank you!

**Comment by jwgmeligmeyling** [comment]
QueryDSL is currently only compatible with the old groupId/Artefact ID of JTS: `com.vividsolutions`.


As long as  `com.vividsolutions` is on the projects classpath, QueryDSL will automatically generate the appropiate path types during metamodel generation.
