### ISSUE TITLE
ExceptionInInitializerError in JPAProvider.java with fat jar (shadowJar)

### ISSUE THREAD

**Issue by hpoul** [querydsl/querydsl#2655]
I am bundling all my dependencies in one .jar file which I use for deployment (using the [gradle shadowJar plugin](https://github.com/johnrengelman/shadow))

Now in the latest querydsl version (4.4.0) it [tries to read the package of the Session class](https://github.com/querydsl/querydsl/blob/182de7fe5d7521ff34c9a87670ec295bb791f782/querydsl-jpa/src/main/java/com/querydsl/jpa/impl/JPAProvider.java#L51-L54), and detects the hibernate version based on the `Implementation-Version` of the `MANIFEST-MF` - Now since all classes are merged into one `jar` file, there is only one `Implementation-Version` for the whole application. I was able to workaround this by writing some 5.x.x into it. But this is a bit strange, what happens when two libraries try to get the dependent versions through the manifest file.. 

Maybe there is another way to detect the hibernate version based on java class files? Maybe provide some workaround like reading a custom `hibernate-version` property or something.

Here is the stack trace I am seeing:

```
01:40:04.328 [nioEventLoopGroup-4-1] ERROR design.codeux.cloudfill.Server - Error during request //api/user/pdf
java.lang.ExceptionInInitializerError: null
	at com.querydsl.jpa.impl.JPAQuery.<init>(JPAQuery.java:48)
	at com.querydsl.jpa.impl.JPAQueryFactory.query(JPAQueryFactory.java:147)
	at com.querydsl.jpa.impl.JPAQueryFactory.select(JPAQueryFactory.java:81)
	at com.querydsl.jpa.impl.JPAQueryFactory.selectFrom(JPAQueryFactory.java:111)
[...]
	at java.base/java.lang.Thread.run(Thread.java:832)
Caused by: java.lang.NullPointerException: null
	at com.querydsl.jpa.impl.JPAProvider.<clinit>(JPAProvider.java:52)
	... 69 common frames omitted
```

**Comment by jwgmeligmeyling** [comment]
I'll change the logic to assume Hibernate 5+ if it cant be determined. We only care whether or not an ancient version of Hibernate is being used.

**Comment by jwgmeligmeyling** [comment]
This was fixed in https://github.com/querydsl/querydsl/commit/44eb2420f9e4b38c37c3801a761c3431d107f2b4 which will be available in the next QueryDSL release.
