### ISSUE TITLE
Add support of pagination from a Union object

### ISSUE THREAD

**Issue by mandrader** [querydsl/querydsl#2656]
Add paging support from a Union object... as a workaround we had to create a database view

**Comment by robertandrewbain** [comment]
It's not clear from your description what the problem is. Can you provide a minimal reproducible example please?

**Comment by mandrader** [comment]
We have the need to make a query to the database in which the union of two or more tables must be made. 

The query must support filter conditions and also allow pagination. 

For example:

SQLQuery<Dto> q1 = queryFactory.select(Projections.fields(Dto.class,...)).from(QTable1.table1).where(predicate1);
SQLQuery<Dto> q2 = queryFactory.select(Projections.fields(Dto.class,...)).from(QTable2.table2).where(predicate2);

Union union = queryFactory.query().unionAll(q1,q2);
// What I can't find how to do is:
union.offset(page * pageSize); // this
union.limit(pageSize); // and this
List<Dto> result = union.fetch();

**Comment by jwgmeligmeyling** [comment]
Limit is not allowed on set operations. Not in QueryDSL, but more importantly, not in ANSI SQL as well. The limit operation after the set operation, actually sets the limit of the right hand side of the set operation (so the right subquery).

To reliably specify a limit on a set operation, you will have to create an outer query that selects from the set operation result. 

select(...).from(union).limit(limit)
