### ISSUE TITLE
How to use db column as condition?

### ISSUE THREAD

**Issue by SidneyLann** [querydsl/querydsl#2659]
where a_date_column >= current_date - interval a_integer_column day
whereBuilder.and(queryEntity.onsaleTime.after("current_date - interval a_integer_column day"));

How to create above expression to use db column as where condition?

**Comment by jwgmeligmeyling** [comment]
JPA or SQL? And which database?

Anyways, there is no standard way to deal with intervals between database vendors. Therefore your approach will be specific to your database and not portable, and it also cannot be supported by QueryDSL generically.
