### ISSUE TITLE
QueryDSL projections with Spring Data JPA

### ISSUE THREAD

**Issue by marcusvoltolim** [querydsl/querydsl#2661]
From the interface definition, we can clearly see that projections are not supported - there is only one type parameter for the main entity class. Yet, we can quite easily extend the executor interface and provide support for projections and more sophisticated QueryDSL queries.

All implementation: https://www.talkischeap.dev/querydsl-projections-spring-data/

**Comment by jwgmeligmeyling** [comment]
Thanks for your heads up! Unfortunately this only touches classes in `spring-data` and not actually in `querydsl` itself, so there is no way for us to integrate it upstream. You could consider contributing it to `spring-data` perhaps?

Also, I am working of a "related works" section in the readme, so I'll try to reference your blogpost from there.
