### ISSUE TITLE
JPA insert from select error

### ISSUE THREAD

**Issue by paradoxfm** [querydsl/querydsl#2662]
```java
final QShift shs = new QShift("sh");
final SQLQuery<Tuple> sql = SQLExpressions.select(shs.dateTimeInterval, shs.employeePosition, shs.positionType, shs.positionIndex, shs.lunch, shs.outstaff, shs.availableForAssignment, shs.status, shs.edited, shs.ftePositionGroup, shs.plannedAbsence, Expressions.constant(newPcr.getId()))
                .from(shs).where(shs.positionCategoryRosterId.eq(oldPcr.getId()));
final QShift sh = QShift.shift;
final InsertClause<?> insertClause = query.insert(sh).columns(sh.dateTimeInterval, sh.employeePosition, sh.positionType, sh.positionIndex, sh.lunch, sh.outstaff, sh.availableForAssignment, sh.status, sh.edited, sh.ftePositionGroup, sh.plannedAbsence, sh.positionCategoryRoster)
                .select(sql);
return insertClause.execute();
```
throw error 
`Caused by: org.hibernate.hql.internal.ast.QuerySyntaxException: expecting OPEN, found 'shift' near line 1, column 19 [insert into Shift shift (shift.dateTimeInterval, shift.employeePosition, shift.positionType, shift.positionIndex, shift.lunch, shift.outstaff, shift.availableForAssignment, shift.status, shift.edited, shift.ftePositionGroup, shift.plannedAbsence, shift.positionCategoryRoster)
select sh.dateTimeInterval, sh.employeePosition, sh.positionType, sh.positionIndex, sh.lunch, sh.outstaff, sh.availableForAssignment, sh.status, sh.edited, sh.ftePositionGroup, sh.plannedAbsence, ?1
from ru.abcconsulting.domain.entity.roster.Shift sh
where sh.positionCategoryRosterId = ?2]
`

**Comment by jwgmeligmeyling** [comment]
You're not ment to use `SQLExpresions` and `InsertClause` in JPQL. Its best to remove `querydsl-sql` from the classpath to remove issues like these.

You need to use `JPAExpresions` and `JPAInsertClause`.

**Comment by paradoxfm** [comment]
```java
JPQLQueryFactory query;
final QShift shs = new QShift("sh");
final JPQLQuery<Tuple> jpqlQuery = query.select(shs.dateTimeInterval, shs.employeePosition, shs.positionType, shs.positionIndex, shs.lunch, shs.outstaff,
                                            shs.availableForAssignment, shs.status, shs.edited, shs.ftePositionGroup, shs.plannedAbsence, Expressions.constant(newPcr.getId()))
        .from(shs).where(shs.positionCategoryRosterId.eq(oldPcr.getId()));
final QShift sh = QShift.shift;
final InsertClause<?> insertClause = query.insert(sh).columns(sh.dateTimeInterval, sh.employeePosition, sh.positionType, sh.positionIndex, sh.lunch, sh.outstaff,
                                                              sh.availableForAssignment, sh.status, sh.edited, sh.ftePositionGroup, sh.plannedAbsence, sh.positionCategoryRoster)
        .select(jpqlQuery);
return insertClause.execute();
```
ok. im make on JPA and remove querydsl-sql.
after clean rebuild
`
Caused by: org.hibernate.hql.internal.ast.QuerySyntaxException: expecting OPEN, found 'shift' near line 1, column 19 [insert into Shift shift (shift.dateTimeInterval, shift.employeePosition, shift.positionType, shift.positionIndex, shift.lunch, shift.outstaff, shift.availableForAssignment, shift.status, shift.edited, shift.ftePositionGroup, shift.plannedAbsence, shift.positionCategoryRoster)
select sh.dateTimeInterval, sh.employeePosition, sh.positionType, sh.positionIndex, sh.lunch, sh.outstaff, sh.availableForAssignment, sh.status, sh.edited, sh.ftePositionGroup, sh.plannedAbsence
from ru.abcconsulting.domain.entity.roster.Shift sh
where sh.positionCategoryRosterId = ?1]
`

**Comment by paradoxfm** [comment]
JPAExpresions class not found
