### ISSUE TITLE
OR isNull() predicate not working on nullable foreign key relation due to cross join

### ISSUE THREAD

**Issue by alextadams88** [querydsl/querydsl#2664]
I have two tables, `hello` and `world`. `hello` contains a column `world_id` which is a reference to `world.id`. This is a nullable reference; some `hello` have null `world_id`. 

I have created the following predicate: `QHello.hello.world.name.like("test").or(QHello.hello.world.isNull())`. When executing this predicate, QueryDSL / Hibernate creates the following HQL: 

```
SELECT hello0_.id AS id1_0_
	,hello0_.world_id AS world_id2_0_
FROM hello hello0_
CROSS JOIN world world1_
WHERE hello0_.world_id = world1_.id
	AND (
		world1_.name LIKE ? ESCAPE '!'
		OR hello0_.world_id IS NULL
		)
```

Due to the cross join, entities where `hello.world_id` is null do not appear, even though I included them as an OR clause in my predicate. It needs to be some sort of LEFT JOIN instead. 

JPA implementation: Hibernate
Database: Postgres
QueryDSL version: 4.3.1 (tested on 4.4.0 as well, issue exists there as well)

**Comment by jwgmeligmeyling** [comment]
QueryDSL doesn't generate joins. We just render the JPQL query exactly as you define the query AST. So `QHello.hello.world.name.like("test").or(QHello.hello.world.isNull())` is rendered to `hello.world.name LIKE :param_1 OR hello.world IS NULL` in JPQL/HQL. Hibernate just tends to use a cross join for implicit joins (i.e. `hello.world.name`). For one, I suggest upgrading to a more recent version of Hibernate, but also according to the JPA specification, you should just prefer to use an explicit join instead:

```java
.from(hello)
.leftJoin(hello.world, QWorld.world)
.where(QWorld.world.name.like("test").or(QWorld.world.isNull())
```

Which in JPQL renders:

```sql
FROM Hello hello LEFT JOIN hello.world world WHERE world.name LIKE :param OR world IS NULL
```
