### ISSUE TITLE
Generate redundant Q files and fail to compile

### ISSUE THREAD

**Issue by andyli722** [querydsl/querydsl#2695]
The compiled code generates redundant Q files
Such as QHistoryPO and QHistoryPO 3, QHistoryPO 2,
IDEA reports an error The QHistoryPO class is public and should be declared in the QHistoryPO.java file

**Comment by jwgmeligmeyling** [comment]
Please provide a reproducer.

**Comment by andyli722** [comment]
Sorry, i didn't understand what you mean

**Comment by jwgmeligmeyling** [comment]
We need an example.

**Comment by andyli722** [comment]
<img width="453" alt="截屏2020-11-12 上午11 25 09" src="https://user-images.githubusercontent.com/60224692/99016504-36d03600-2592-11eb-98df-148b1473d61e.png">
