### ISSUE TITLE
WITH RECURSIVE wrong value generated inside from clause

### ISSUE THREAD

**Issue by Ivanov-Alexander** [querydsl/querydsl#2700]
## Observed vs. expected behavior
Hi guys,
I try to get all child categories with recursive query:

    WITH RECURSIVE subcategories AS(
  	    SELECT c.*
        FROM categories c
        WHERE c.category_id IN (4)
  	    UNION
        SELECT c.*
        FROM subcategories sub
        JOIN categories c ON  c.parent_category_id = sub.category_id
    )
    SELECT * from subcategories;

## Steps to reproduce
With this code: 

        JPASQLQuery<CategoryEntity> q = new JPASQLQuery<>(em, SQLTemplates.DEFAULT);
        QCategoryEntity c = new QCategoryEntity("c");
        QCategoryEntity sub = new QCategoryEntity("sub");

        List<Tuple> fetch = q.withRecursive(sub, c.categoryId, c.name)
            .as(union(
                select(c.categoryId, c.name).from(c).where(c.categoryId.in(id)),
                select(c.categoryId, c.name).from(sub).innerJoin(c).on(c.parent_category_id.eq(sub.categoryId)))
            )
          .select(sub.categoryId, sub.name).from(sub).fetch();

Both FROM (after union and last one includes table name and alias instead of name specified in with recursive - **sub**)
SQL query in console:

    Hibernate: with recursive sub (category_id, name) as ((
    select c.category_id, c.name
    from categories c
    where c.category_id = ?)
    union
    (select c.category_id, c.name
    from categories sub
    inner join categories c
    on c.parent_category_id = sub.category_id))
    select sub.category_id, sub.name from categories sub

If I change FROM values manually, it works as expected:

    with recursive sub (category_id, name) as ((
        select c.category_id, c.name
        from categories c
        where c.category_id = 4)
        union
        (select c.category_id, c.name
        from sub
        inner join categories c
        on c.parent_category_id = sub.category_id))
    select sub.category_id, sub.name from sub

## Environment

Spring Boot 2.4.0

Querydsl version: 4.4.0

Querydsl module: querydsl-jpa

Database: MariaDB

JDK: 11

**Comment by jwgmeligmeyling** [comment]
Sub is not a QCategoryEntity, as it has a different table, namely the CTE alias.

You need to create a different kind of entity path base that just references “sub”. Optionally, you can create an entity for your CTE and have Querydsl generate the metamodel for you.

**Comment by Ivanov-Alexander** [comment]
Many thanks, found EntityPathBase that does what I need.
