### ISSUE TITLE
JPAQuery addFlag  not working

### ISSUE THREAD

**Issue by luyuanx2** [querydsl/querydsl#2701]
## Observed vs. expected behavior

I want JPAQuery Generate SQL with `SQL_CACHE`:
```sql
select
        sql_cache
        instancebi0_.billing_item as col_0_0_ 
    from
        dt_instance_bill instancebi0_ 
```
this is my code:
```java 
QInstanceBillPO billPO = QInstanceBillPO.instanceBillPO;
        JPAQuery<String> jpaQuery = jpaQueryFactory.select(billPO.billingItem);
        QueryMetadata metadata = jpaQuery.getMetadata();

        metadata.addFlag(new QueryFlag(QueryFlag.Position.AFTER_SELECT, ExpressionUtils.template(String.class, "SQL_CACHE")));
        return jpaQuery
                .from(billPO)
                .fetch();
```
but i got sql is:
```sql
select
        instancebi0_.billing_item as col_0_0_ 
    from
        dt_instance_bill instancebi0_ 
```

**Comment by jwgmeligmeyling** [comment]
JPQL doesn't define any flags that are allowed after the SELECT clause. The only flag available in JPQL is "FETCH" for fetch-joins (and Hibernate declares FETCH ALL PROPERTIES in HQL as well).

As JPQL doesn't have any flags, there is no need for the JPASerializer to serialize these, as they would inherently result in invalid queries that can't be executed anyway.

Bottom line: SQL query flags can only be used in SQL queries, not in JPQL queries.

If you need to pass the `SQL_CACHE` flag down to the actual SQL query produced, you need more changes than just in QueryDSL. You'll also need to create a custom Hibernate function to render the SQL for it.
