### ISSUE TITLE
is there any way to store query dsl as dsl file or string？and load runtime

### ISSUE THREAD

**Issue by 40lsgy1** [querydsl/querydsl#2717]
in my case，I wan to store query dsl as string in config，and construct runtime and then convert to some other user defined query object（json），is it possible？

**Comment by jwgmeligmeyling** [comment]
Yes, just serialize the query:

```java
JPQLSerializer serializer = new JPQLSerializer();
serializer.serialize(query.getMetadata(), false, null);
String query = serializer.toString();
```

Then write the string to a file. This string can then be passed as a query to for example `EntityManager.createQuery`

Its however not possible to create a QueryDSL AST back from a String.
