### ISSUE TITLE
kotlin multi project question

### ISSUE THREAD

**Issue by jonsoku2** [querydsl/querydsl#2719]
Hello I'm kotlin newbie programmer.

I searched a lot to run querydsl in multiproject, but it eventually failed.

The current situation is 
(https://github.com/jonsoku2/kotlin-multi-querydsl-spring-boot/blob/master/build.gradle.kts)

Build Success occurs when  `compileKotlin`  is executed, but no files are created.

How can I do it? Help me please.

+ what is this mean...
```
kotlin scripting plugin: project ':common'.compileQuerydslKotlin - configuration not found: querydslKotlinScriptDef, the plugin is probably applied by a mistake
```

![image](https://user-images.githubusercontent.com/51524954/103917761-524e5c00-5151-11eb-88ef-751908a7715f.png)

**Comment by jwgmeligmeyling** [comment]
Please take inspiration from our Kotlin example projects: https://github.com/querydsl/querydsl/tree/master/querydsl-examples/querydsl-example-kotlin-jpa

These examples use Maven. There are currently no Gradle plugins for QueryDSL, but the APT plugin should work fine when used with kapt (as shown by the maven examples). Some Gradle related configurations users ended up using is discussed in #1828.
