### ISSUE TITLE
Classifier requirement of APT makes using Spring's Dependency Management Gradle plugin awkward

### ISSUE THREAD

**Issue by mjustin** [querydsl/querydsl#2722]
## Background

Currently, as stated in [the Querydsl documentation](http://www.querydsl.com/static/querydsl/4.4.0/reference/html/ch03s03.html), a classifier is necessary to use `querydsl-apt`:

> Notice that you need to use a proper classifier when defining dependency to `com.querydsl:querydsl-apt`. Those additional artifacts define the annotation processor to be used in `META-INF/services/javax.annotation.processing.Processor`.
>
> Available classifiers include:
>
> * general
> * hibernate
> * jdo
> * jpa

This means that the classifier needs to be specified in the build.  In a vanilla Gradle project, this would typically be done as follows:

```groovy
dependencies {
    annotationProcessor 'com.querydsl:querydsl-apt:4.4.0:general'
    compileOnly 'com.querydsl:querydsl-core:4.4.0'
    implementation 'com.querydsl:querydsl-mongodb:4.4.0'
}
```

Spring's [Dependency Management Plugin](https://docs.spring.io/dependency-management-plugin/docs/current/reference/html/) Gradle plugin allows specifying project dependency versions in a `dependencyManagement` block.  This allows versions to be consistent with the underlying frameworks, consistent cross-project versions, and adds convenience when specifying dependencies as the version numbers are excluded.

The [spring-boot-dependencies](https://mvnrepository.com/artifact/org.springframework.boot/spring-boot-dependencies/2.4.1) BOM is commonly used with this by Spring Boot projects, and includes dependencies on Querydsl:

```
com.querydsl:querydsl-apt:4.4.0
com.querydsl:querydsl-collections:4.4.0
com.querydsl:querydsl-core:4.4.0
com.querydsl:querydsl-jpa:4.4.0
com.querydsl:querydsl-mongodb:4.4.0
```

## The problem

However, the dependency management plugin does not support the use of classifiers (https://github.com/spring-gradle-plugins/dependency-management-plugin/issues/67).  This is stated to be due to a limitation with Gradle itself (https://github.com/gradle/gradle/issues/1947) not providing the classifier through its API.

## Workaround

This means that a somewhat awkward workaround is necessary to use the dependency without hardcoding the version.  One solution is to use the [`importedProperties`](https://docs.spring.io/dependency-management-plugin/docs/current/reference/html/#accessing-properties) option to access the `querydsl.version` property in the `spring-boot-dependencies` Maven BOM, as suggested in another issue (https://github.com/querydsl/querydsl/issues/2459#issuecomment-659892795):

```groovy
dependencies {
    annotationProcessor 'com.querydsl:querydsl-apt:4.4.0:general'
}
```

A similar solution that's worked for me is to use the [`managedVersions` map](https://docs.spring.io/dependency-management-plugin/docs/current/reference/html/#working-with-managed-versions-programmatic-access) to use the managed version of the `querydsl-apt` dependency.  This also has the benefit of working in a non-Boot Gradle project that uses the Spring Dependency Management plugin.

```groovy
dependencies {
  annotationProcessor "com.querydsl:querydsl-apt:${dependencyManagement.managedVersions['com.querydsl:querydsl-apt']}:general"
}
```

## Feature request

It would be nice if Querydsl & the Spring Dependency Management plugin would play together better so that the version would not need to be redundantly declared if it's brought in through `dependencyManagement`.  I don't have any clever solutions in mind; the best I've got is to have different artifacts rather than different classifiers (e.g. `querydsl-apt-general` instead of `name: querydsl-apt, classifier: general`.  But that seems a pretty heavy-handed solution to the problem, unless that was a change you wanted to make anyway.

At a minimum, it would be nice if the workaround was documented.  There does not appear to be much on the web around this specific issue, and the workaround within the Querydsl project is in large comment thread in an [unrelated issue](https://github.com/querydsl/querydsl/issues/2459#issuecomment-659892795), linking to a [Korean language blog entry](http://honeymon.io/tech/2020/07/09/gradle-annotation-processor-with-querydsl.html).

**Comment by jwgmeligmeyling** [comment]
You don’t actually need to use the classifier as long as you provide the APT processor classname as compiler argument.

Actually most of the Querydsl documentation/tutorials out there do precisely that.

That said, we currently do not actively support Gradle. As we provide just a plain APT plugin, it should work, but we do not provide working examples.

**Comment by natros** [comment]
I thought the spring dependency management plugin was deprecated and that we should use platform().

**Comment by mjustin** [comment]
> You don’t actually need to use the classifier as long as you provide the APT processor classname as compiler argument.
>
> Actually most of the Querydsl documentation/tutorials out there do precisely that.

That's great to know.  Is the purpose of the classifiers/usage of the APT processor classname documented somewhere?  This would be very helpful to have a canonical reference to indicate how this is intended to be used, and what the classifiers were used for.

In my own situation, I guess I was reading the [Querydsl documentation](http://www.querydsl.com/static/querydsl/4.4.0/reference/html/ch03s03.html) documentation in the wrong context.  I misunderstood it to say that the usage of a classifier was required, when I guess it's only saying that it's necessary to use the `maven-compiler-plugin`:

> Notice that you need to use a proper classifier when defining dependency to `com.querydsl:querydsl-apt`. Those additional artifacts define the annotation processor to be used in `META-INF/services/javax.annotation.processing.Processor`.

**Comment by jwgmeligmeyling** [comment]
@mjustin `querydsl-apt` contains various processors, for JPA, SQL, MongoDB, etc.

While it is possible to register the processor on the classpath using `META-INF/services/javax.annotation.processing.Processor`, having all these implementations in there would cause all modules to generate code individually.

The classifiers basically specify which implementation is provided in `META-INF/services/javax.annotation.processing.Processor`.

If you omit the classifier (use the default classifier), `META-INF/services/javax.annotation.processing.Processor` is simply missing and you have to register the APT processor as command line argument.

I'll make sure to change the documentation accordingly.

Did you manage to get APT processing to work in Gradle though?

**Comment by mjustin** [comment]
> Did you manage to get APT processing to work in Gradle though?

I currently have it working by using the classifier (`com.querydsl:querydsl-apt:4.4.0:general`).

I played around with using the default classifier.  Specifying the processor as a `-processor` compilation argument is not a good solution for me, since I have several other annotation processors declared (using `annotationProcessor` dependencies), and it looks like if I declare one in `-processor` I need to declare them all.

I confirmed that adding a `META-INF/services/javax.annotation.processing.Processor` to the classpath with a value of `com.querydsl.apt.QuerydslAnnotationProcessor` does cause that processor to be used.  However, I'm not sure there's a clean way in Gradle to use that file in the annotation classpath but not in the compile classpath without doing a fair amount of boilerplate build code, at which point using the classifier workaround mentioned in this issue becomes a win.

**Comment by jwgmeligmeyling** [comment]
QueryDSL supports Gradle for `jpa` code generation, as described in https://github.com/querydsl/querydsl/issues/2231#issuecomment-357956070 . Doing so neatly requires the use of the `jpa` classifier. Because Gradle does not support classifiers in the dependency management plugin (gradle/gradle#1947) this doesn't work properly when a version for `querydsl-apt` is provided through a bill-of-materials.

Probably best to fix this in Gradle or Springs BOM instead, although I would accept a PR for this change I am going to close this for now as the documentation aspect as far as Gradle support goes will already be covered in #2231.
