### ISSUE TITLE
Wrong quotes

### ISSUE THREAD

**Issue by hogmuzzle** [querydsl/querydsl#2723]
I get SQLSyntaxErrorException

Here is the sql generated
select distinct repairs_order_v.dealer_code, to_char(repairs_order_v.order_payment_date,'MM-YYYY'), repairs_auto_v.vin, repairs_cardatabase.car_model, repairs_cardatabase.myear, repairs_cardatabase.saledate, cr.delivery_customer_date
from repairs_order_v
inner join repairs_auto_v
on repairs_order_v.id = repairs_auto_v.order_id
inner join repairs_cardatabase
on repairs_cardatabase.vin = repairs_auto_v.vin
left join **"cars@cardb_dblink"** cr
on repairs_auto_v.vin = cr.vin

My code

SQLQueryFactory queryFactory = HibernateUtilities.getSqlQueryFactory();
            QRepairsOrderV repairs_order_v = new QRepairsOrderV("repairs_order_v");
            QRepairsAutoV repairs_auto_v = new QRepairsAutoV("repairs_auto_v");
            QRepairsCardatabase repairs_cardatabase = new QRepairsCardatabase("repairs_cardatabase");
            QFleetDealers fleet_dealers = new QFleetDealers("fleet_dealers");
            QCar car = new QCar(Expressions.path(Car.class, "cars@cardb_dblink"));
            PathBuilder<Car> cr = new PathBuilder<>(Car.class, "cr");

queryFactory.select(Projections.constructor(UniqueVinRow.class, repairs_order_v.dealer_code,
                    HibernateUtilities.TO_CHAR(repairs_order_v.order_payment_date, "MM-YYYY"),
                    repairs_auto_v.vin, repairs_cardatabase.car_model, repairs_cardatabase.myear, repairs_cardatabase.saledate,
                    cr.getDate("delivery_customer_date", Date.class)))
                    .from(repairs_order_v)
                    .innerJoin(repairs_auto_v).on(repairs_order_v.id.eq(repairs_auto_v.order_id))
                    .innerJoin(repairs_cardatabase).on(repairs_cardatabase.vin.eq(repairs_auto_v.vin))
                    .leftJoin(car, cr).on(repairs_auto_v.vin.eq(cr.get("vin")))

I do not need any quotes NOWHERE and NEVER WHY they always appear here and there for no reason. They break everything. The lib also use quotes with ROWID as well. I lost a lot of time struggling with ROWID and now I don not know how to overcome this behavior with the  table name.

**Comment by jwgmeligmeyling** [comment]
Please provide the version of QueryDSL used, which subclass of SQLTemplates youre using with your queries and which database vendor youre using.

**Comment by hogmuzzle** [comment]
I use query sql 4.3.1 with OracleTemplates. The only workaround I have found is to extend the oracle template and override the method requiresQuotes. The logic in this method is valid for some other vendors but in Oracle all queries work without quotes.
Names in oracle be it table, column, object, view, package, procedure, function, etc. are by default UPPER CASE unless quoted with double quotes.  Actually I have never encountered any case in Oracle where quotes were needed in queries.

**Comment by jwgmeligmeyling** [comment]
Could be true, although we do test against Oracle in our integration test suite. Which version of Oracle are you using?

**Comment by hogmuzzle** [comment]
I work with two Oracle installations 11 and 12 versions. We have been developing 3 report systems for 6 or 7 years and our projects have hundreds of queries written in SQL and none of them have quotes.  I come across this issues trying to rewrite my sql to querydsl. By the way I like your framework very much. Thank you for what you are doing.
