### ISSUE TITLE
Lost Predicate

### ISSUE THREAD

**Issue by EmelyanovKonstantin** [querydsl/querydsl#2725]
## Observed vs. expected behavior

Lost Predicate at the intersection of predicates using BooleanBuilder.and()
Only the last predicate gets into the final query if the type is List.
## Steps to reproduce

```
public class Application {
    ...
    @Field("requests")
    private List<Request> requests;

    @Field("results")
    private List<Result> results;
}
```

in Service:
```
public class ApplicationsService {
     ...
     BooleanBuilder predicateBuilder = new BooleanBuilder();
     predicateBuilder.and(application.requests.isEmpty());
     predicateBuilder.and(application.results.isEmpty());
}
```
Result query:
`{"$or" : [{ "results" : [] }, { "results" : { "$exists" : false } }] } `
## Environment
```
<dependency>
			<groupId>com.querydsl</groupId>
			<artifactId>querydsl-mongodb</artifactId>
			<version>${querydsl.version}</version>
</dependency>
```

Querydsl version:  4.4.0

Querydsl module: querydsl-mongodb

Database: mongodb

JDK: 11.0.8

**Comment by jwgmeligmeyling** [comment]
Could be related to https://github.com/querydsl/querydsl/issues/2638

Be ware that the `querydsl-mongodb` module is currently unmaintained. We are accepting pull requests though.
