### ISSUE TITLE
querydsl-mongodb: Support for DateExpression.currentDate(), TimeExpression.currentTime(), DateTimeExpression.currentTimestamp()

### ISSUE THREAD

**Issue by Kobee1203** [querydsl/querydsl#2771]
## Why the new feature should be added

I try to use `DateExpression.currentDate()` (`Ops.DateTimeOps.CURRENT_DATE`), `TimeExpression.currentTime()` (`Ops.DateTimeOps.CURRENT_TIME`) and `DateTimeExpression.currentTimestamp()` (`Ops.DateTimeOps.CURRENT_TIMESTAMP`).
These classes are present in [`querydsl-core`](https://github.com/querydsl/querydsl/tree/master/querydsl-core/src/main/java/com/querydsl/core/types/dsl), but they are not supported by `querydsl-mongodb`.
It would be good to support these operations to be consistent with other implementations (jpa, sql...).

## How the new feature should work

My suggestions would be the following:

**DateTimeExpression.currentTimestamp() -> "new Date()"**
Examples:
Expressions.predicate(Ops.LOE, x, DateTimeExpression.currentTimestamp()) -> db.collection.find({ "Expiration": { "$lte": new Date() } })
Expressions.predicate(Ops.GOE, x, DateTimeExpression.currentTimestamp()) -> db.collection.find({ "Expiration": { "$gte": new Date() } })

**DateExpression.currentDate() -> use a range**
```
var start = new Date();
start = new Date( start.valueOf() - start.valueOf() % ( 1000 * 60 * 60 * 24 ) );
end  = new Date( start.valueOf() + ( 1000 * 60 * 60 * 24 ) );
```
Examples: 
Expressions.predicate(Ops.EQ, x, DateTimeExpression.currentDate()) -> db.collection.find({ "Expiration": { "$gte": start, $lt": end } })
Expressions.predicate(Ops.LOE, x, DateTimeExpression.currentDate()) -> db.collection.find({ "Expiration": { "$lte": start } })
Expressions.predicate(Ops.GOE, x, DateTimeExpression.currentDate()) -> db.collection.find({ "Expiration": { "$gte": end } })

**TimeExpression.currentTime() -> I don't know, sorry** 😢 
It would be needed to extract the time from "new Date()" and compare this time with the field to be compared.

These are only suggestions and there may be better solutions.

Anyway, would there be any workarounds to get an equivalent result with the current version of querydsl-mongodb?

**Comment by jwgmeligmeyling** [comment]
For the first case the proper way is to use a constant expression instead: `Expressions.asDate(new Date())`. Is explicit and doesn't pretend MongoDB has features it hasn't.

I don't think the second scenario can be supported, because the serializer is not context aware. You could however try to pull it off in a PR, if it works, I can have a look at it.

**Comment by Kobee1203** [comment]
When we do `Expressions.asDate(new Date())`, we don't use the date of the system where mongodb is hosted but the date where the application is hosted. This may not be correct if the app and mongodb are not on the same location.
I tried to do a query for the first scenario but I can't seem to get something that matches for "new Date()".  I tried with a converter which converts to:
  * `new BsonJavascript ("new Date()")`,
  * or `new BsonDocument ("$date", new BsonJavascript ("new Date()"))`,
  * or `new BsonDocument ("$date", new BsonString("new Date()"))`.
But it didn't work.

Do you have an idea how to get the following query with querydsl-mongodb and send `new Date()` as value ?
`{ "Expiration": { "$lte": new Date() } }`

**Comment by Kobee1203** [comment]
For the second scenario, it is indeed necessary to be aware of the operator used but it does not seem obvious, given that the context does not contain this information.  We might need a TimeOperation class that wraps a TemporalExpression and the operator used in order to resolve the different rules depending on the operator.

**Comment by jwgmeligmeyling** [comment]
Ah, it wasn't clear to me whether `new Date()` in your example was the serialized query or pseudo code.

Feel free to implement `Ops.DateTimeOps.CURRENT_TIMESTAMP` in https://github.com/querydsl/querydsl/blob/68c02aaa11310d7f708c90a920b7931e7c19044f/querydsl-mongodb/src/main/java/com/querydsl/mongodb/MongodbSerializer.java#L260-L261

From the examples it should be quite trivial to serialize `new Date()` for it.

I am still quite sceptical about the suggestion for `currentDate()`, but feel free to try that out as well.

**Comment by Kobee1203** [comment]
Sorry if it wasn't clear.

I tried your example but the query doesn't work.

So I tried with the following:
```
} else if (op == Ops.LOE) {
    if(expr.getArg(1) instanceof  Operation<?>) {
        Operation<?> rhs = (Operation<?>) expr.getArg(1);
        if (rhs.getOperator() == Ops.DateTimeOps.CURRENT_TIMESTAMP) {
            return asDBObject(asDBKey(expr, 0), Document.parse("{ $lte: new Date() }"));
        }
    }
    return asDBObject(asDBKey(expr, 0), asDBObject("$lte", asDBValue(expr, 1)));
}
```
And the query works.

I checked out what the Document.parse(...) method did:
- It calls [JsonReader.readBsonType()](https://github.com/mongodb/mongo-java-driver/blob/528160a6e7cdf5637fafbce77d4d6591012dd753/bson/src/main/org/bson/json/JsonReader.java#L123). 
- The token type is equal to `UNQUOTED_STRING`,
- then it calls the [visitNew()](https://github.com/mongodb/mongo-java-driver/blob/528160a6e7cdf5637fafbce77d4d6591012dd753/bson/src/main/org/bson/json/JsonReader.java#L546) method, 
- then it calls the [visitDateTimeConstructor()](https://github.com/mongodb/mongo-java-driver/blob/528160a6e7cdf5637fafbce77d4d6591012dd753/bson/src/main/org/bson/json/JsonReader.java#L859) method.
- then it calls the Java code `new Date().getTime();`.

So it uses the system date of the application and not the system date of the system where mongodb is hosted.

So I have the impression that it is not possible to send the query with the raw value `new Date()` and that it is interpreted by MongoDB 😞 

I can always try to do a PR for `Ops.DateTimeOps.CURRENT_DATE` and `Ops.DateTimeOps.CURRENT_TIMESTAMP` by handling the current date in Java as JsonReader, but it's not perfect 😃

**Comment by Kobee1203** [comment]
I created the PR to support `DateExpression.currentDate()` and `DateTimeExpression.currentTimestamp()`

However, I find the code for `Ops.DateTimeOps.CURRENT_DATE` a bit intrusive.
If anyone has any suggestions to improve that, I'm open to them.
