### ISSUE TITLE
Annotation processor options are supposedly not being recognized

### ISSUE THREAD

**Issue by IncPlusPlus** [querydsl/querydsl#2772]
## Observed vs. expected behavior
Given a project that uses query-querydsl-apt (the specific classifier shouldn't matter but I used `jpa`) which also specifies the following in `build.gradle`:
```
compileJava {
    options.compilerArgs += "-Aquerydsl.packageSuffix=.qclass"
}
```
When this project is run...

The **observed** behavior is: Building the project issues the following warning: `warning: The following options were not recognized by any processor: '[querydsl.packageSuffix]'`

The **expected** behavior is: Building the project works without any warnings in the build output

## Steps to reproduce

1. Clone [IncPlusPlus/querydsl-missing-supportedoptions-demo](https://github.com/IncPlusPlus/querydsl-missing-supportedoptions-demo) (this is a minimal example that can reproduce this issue)
2. Run `./gradlew clean build`
3. Observe the warning printed in the console

## Environment

Querydsl version: 4.4.0

Querydsl module: querydsl-jpa

Database: MySQL

JDK: openjdk 11.0.9.1 2020-11-04

## Additional details

I believe I know the reason behind the issuance of the above warning. I confirmed my suspicion by proving that specifying `-Aquerydsl.logInfo=true`. I believe that the reason why warnings are created for `querydsl.packageSuffix` (warnings also happen with all the other [APT options listed in the documentation](http://www.querydsl.com/static/querydsl/latest/reference/html/ch03s03.html#d0e2339)) but not for `querydsl.loginfo` is because [`com.querydsl.apt.AbstractQuerydslProcessor.getSupportedOptions`](https://github.com/querydsl/querydsl/blob/master/querydsl-apt/src/main/java/com/querydsl/apt/AbstractQuerydslProcessor.java#L547) only adds the [`querydsl.logInfo`](https://github.com/querydsl/querydsl/blob/master/querydsl-apt/src/main/java/com/querydsl/apt/APTOptions.java#L102) key.

I cloned querydsl in an attempt to see if adding the other `APTOptions` to the strings returned by `getSupportedOptions` but couldn't figure out how to install querydsl-apt and then point [my Gradle project](https://github.com/IncPlusPlus/querydsl-missing-supportedoptions-demo) to the version with my changes (which installed to `~/.m2/repository/com/querydsl/querydsl-apt/5.0.0-SNAPSHOT/querydsl-apt-5.0.0-SNAPSHOT-jpa.jar` as expected).

If my reasoning is correct, I'd be happy to make a pull request that adds the rest of the keys from APTOptions to the supported options strings.

**Comment by jwgmeligmeyling** [comment]
Because the issue only exists on an unsupported build system, I consider this a feature (Gradle support).

Whether the extension of `APTOptions` fixes remains to be seen, if it does, please provide a PR!

You should be able to address the locally installed QueryDSL version by simply referencing the version `5.0.0-SNAPSHOT` in your Grade dependency.

**Comment by IncPlusPlus** [comment]
I can now confirm that the area I described in `AbstractQuerydslProcessor` is the culprit. I'll make a PR a little later today.

**Comment by IncPlusPlus** [comment]
I've gone ahead and made a pull request. Review at your leisure.

**Comment by IncPlusPlus** [comment]
About this being a feature and introducing Gradle support. I think it might be best to consider this an enhancement as Gradle already worked in some scenarios. The problem with deeming this change as the introduction of Gradle support is that there are still scenarios where Gradle seemingly cannot be used like #2770 for exmaple.

**Comment by jwgmeligmeyling** [comment]
Thanks for your PR! I'll integrate the PR as soon as the build passes (I've restarted it).

> ...  as Gradle did already work in some scenarios. The problem with deeming this change as the introduction of Gradle support is that there are still scenarios where Gradle seemingly cannot be used like #2770 for exmaple.

`querydsl-apt` is an APT plugin for `querydsl-jpa` and modules relying on a domain model annotated with QueryDSL annotations, such as `querydsl-collections`. `querydsl-apt` works just fine with Gradle, just like any other APT plugin. How to do so is undocumented, but there are plenty examples out there that succesfully use it. It would be useful to have some documentation on how to use QueryDSL with Gradle as this is its getting more and more frequently used. However to some degree I also think that Gradle users should be well aware on how to configure APT plugins themselves. I don't think its our responsibility to explain the underlying query languages like HQL, JPQL or SQL either.

In `querydsl-sql` the metamodel is usually not generated from annotated classes (what `querydsl-apt` does), but instead by querying the database for its schema. This requires a different type of plugin which is currently only implemented as a Maven plugin, and does not work for Gradle. That said, the generated code does not have to be generated. You can use `querydsl-sql` just fine by manually maintaining a metamodel in your codebase. Some of our tests actually do precisely that.

Personally I am mostly maintaining `querydsl-core`, `querydsl-collections`, `querydsl-jpa` and `querydsl-apt` - so the changes for a Gradle plugin for `querydsl-sql`  to see the light of day are best if someone is willing to contribute it.

**Comment by IncPlusPlus** [comment]
Gotcha. I'll relay the message. Thanks for the quick feedback and thanks for being an awesome open source maintainer! Take care!
