### ISSUE TITLE
Add generic listagg method

### ISSUE THREAD

**Issue by michele-bergia** [querydsl/querydsl#2778]
During my development, I had to use `SQLExpressions.listagg` method and I've noticed that it returns `WithinGroup<Object>`. Since I think it can be useful to user to have a more specialised class type, I would suggest to add this simple method in the `SQLExpressions` class that could solve the issue and I think it can be a good addition:

```
public static <T> WithinGroup<T> listagg(Expression<T> expr, String delimiter, Class<T> clazz) {
        return new WithinGroup<>(clazz, SQLOps.LISTAGG, expr, ConstantImpl.create(delimiter));
}
```

that it's very similar to the already existing `listagg` method:

```
public static WithinGroup<Object> listagg(Expression<?> expr, String delimiter) {
        return new WithinGroup<Object>(Object.class, SQLOps.LISTAGG, expr, ConstantImpl.create(delimiter));
}
```

**Comment by jwgmeligmeyling** [comment]
It can just be changed to `public static <T> WithinGroup<T> listagg(Expression<T> expr, String delimiter)` instead.

**Comment by jwgmeligmeyling** [comment]
However, isn't the result of a listagg always a String?

**Comment by michele-bergia** [comment]
Not sure what happens if the output is still a String when we pass a number without any delimiter in listagg. Maybe the datatype is kept

**Comment by jwgmeligmeyling** [comment]
> The return data type is RAW if the measure column is RAW; otherwise the return value is VARCHAR2.

https://docs.oracle.com/cd/B28359_01/server.111/b28318/datatype.htm#CNCPT012

So, in Java the return type would always be a String.

So instead of `WithinGroup<T>` - I suggest we return `WithinGroup<String>`.

**Comment by michele-bergia** [comment]
Ok, I see. Then, yes, I agree too for `WithinGroup<String>`

**Comment by yang03265** [comment]
Pull requests issued for this: https://github.com/querydsl/querydsl/pull/3114

**Comment by jwgmeligmeyling** [comment]
The pr for this is actually merged
