### ISSUE TITLE
Update Website

### ISSUE THREAD

**Issue by SebastianDietrich** [querydsl/querydsl#2787]
## The Website http://www.querydsl.com/ is outdated, please update it

The following things are obviously outdated and should be updated. Otherwise people might think that querydsl is no longer maintained:

- copyright notice at end of each page
- release history (should be updated or just point to https://github.com/querydsl/querydsl/releases)

**Comment by jwgmeligmeyling** [comment]
We switched to using http://querydsl.github.io/ and are awaiting DNS access to the domain as part of the repository takeover.

**Comment by SebastianDietrich** [comment]
Is it possible to forward www.querydsl.com to http://querydsl.github.io/ - otherwise people will still find the old, outdated site
