### ISSUE TITLE
Bad generics usage on NumberExpression causes ClassCastException

### ISSUE THREAD

**Issue by mirkoscotti** [querydsl/querydsl#2788]
In NumberExpression, both divide methods apply a bad cast for preserving the type of the final expression. This is the code for one of the methods:
```
public <N extends Number & Comparable<?>> NumberExpression<T> divide(Expression<N> right) {
    @SuppressWarnings("unchecked")
    Class<T> type = (Class<T>) getDivisionType(getType(), right.getType());
    return Expressions.numberOperation(type, Ops.DIV, mixin, right);
}
```
And this is the code of the method getDivisionType invoked inside:
```
private Class<?> getDivisionType(Class<?> left, Class<?> right) {
    if (!left.equals(right)) {
        return Double.class;
    } else {
        return left;
    }
}
```
This code absolutely violates the contract of the divide method when N is different from T. In such case, the returned NumberExpression is of type Double, whereas the contract requires that the type **must** be the same as the instance type.
You can reproduce an effect of this violation connecting to a database and executing the following code:
```
NumberPath<BigDecimal> field1 = entityPath.createNumber(fieldName, BigDecimal.class);
NumberPath<BigInteger> field2 = entityPath.createNumber(fieldName, BigInteger.class);
NumberExpression<BigDecimal> field3 = field1.divide(field2) //BigDecimal is correct by contract,
List<BigDecimal> list = query.select(field3).fetch(); //The type of the list is correct: List<Double> of course does not compile
list.forEach(System.out::println); //ClassCastException raised here
```
This is because even if the list is safely typed by BigDecimal, it might contain Double objects. The following test dramatically shows how to raise an exception independently on the database the program is connecting to:
```
@Test
void numberExceptionTest() throws Exception
{
    NumberPath<BigDecimal> field1 = Expressions.numberPath(BigDecimal.class, "field1");
    NumberPath<BigInteger> field2 = Expressions.numberPath(BigInteger.class, "field2");
    // The assignment below is correct by contract. The assignment to NumberExpression<Double> of course does not compile.
    NumberExpression<BigDecimal> field3 = field1.divide(field2);
    Assertions.assertThrows(NoSuchMethodException.class, () -> field3.getType().getConstructor(BigInteger.class).newInstance(BigInteger.ZERO));
}
```
The reason is quite simple: BigDecimal defines the constructor accepting BigInteger, but Double does not!

As a workaround I am forced to use:
```
NumberPath<BigDecimal> field1 = Expressions.numberPath(BigDecimal.class, "field1");
NumberPath<BigInteger> field2 = Expressions.numberPath(BigInteger.class, "field2");
NumberExpression<BigDecimal> field3 = Expressions.numberOperation(BigDecimal.class, Ops.DIV, field1, field2) ; //Correct!
```
I wonder if you could fix this issue removing the bad cast in method divide. A possible solution would be to deprecate the buggy method adding the following:
```
public NumberExpression<Double> divide(Expression<? extends Number> right) {
    return Expressions.numberOperation(Double.class, Ops.DIV, mixin, right);
}
```
A more sohisticated, even if not so clearly useful solution, could be to give priority to number types depending on their domain size:
```
public NumberExpression<? extends Number> divide(Expression<? extends Number> right) {
    List<Class<? extends Number>> list = Arrays.asList(Byte.class, Short.class, Integer.class, Long.class, Double.class, BigInteger.class, BigDecimal.class);
    Class<?> leftType = getType();
    Class<?> rightType = right.getType();
    int index1 = list.indexOf(leftType);
    int index2 = list.indexOf(rightType)
    return Expressions.numberOperation(index1 < index2 ? rightType : leftType, Ops.DIV, mixin, right);
}
```
This last example allows clients using xxxValue() methods of Number to convert results to the desired primitive/boxed type.
Thanks for your attention.

**Comment by jwgmeligmeyling** [comment]
I believe this was done for JPA, which clearly specifies the division output for every combination of types. I would have to get back to the code.

As a workaround you can always cast back to a BigDecimal: castToNum(BigDecimal.class).
