### ISSUE TITLE
I try to use kotlin to add an extension method to it. Why is the index out of bounds?

### ISSUE THREAD

**Issue by edcjian** [querydsl/querydsl#2789]
## Environment

Querydsl version:

Querydsl module:

Database:

JDK:

## Additional details

![NH~UQ6HQN{V{@$37)EDIL{G](https://user-images.githubusercontent.com/48635933/111462703-b39a3900-8759-11eb-9986-7271178560fc.png)
![))PWJ64QQ6_9UF)Y)8F6FRK](https://user-images.githubusercontent.com/48635933/111462734-bdbc3780-8759-11eb-981c-8ec1a5bd60b3.png)
![Y4G8$K`1XXXASR%XVBXB}4N](https://user-images.githubusercontent.com/48635933/111462739-bf85fb00-8759-11eb-8f68-5107994cbde9.png)
![6K1@48O%X6TSP3HMZM C)PK](https://user-images.githubusercontent.com/48635933/111462813-d3c9f800-8759-11eb-9042-2743a5515cd8.png)

**Comment by jwgmeligmeyling** [comment]
Needs more info
