### ISSUE TITLE
Custom mapping for Expressions 

### ISSUE THREAD

**Issue by kanimaru** [querydsl/querydsl#2790]
Hi is it possible to map the columns to beans? My columns and queries use underscores and my beans use camelcase. So when I do an Expression like:
`Expressions.as(constant(0), "layer_id")` and have a Bean like 
```java
class SomeBean {
   long layerId;
  /* Getter & Setter */
}
```
they won't get filled when I do:
```java
      var projections = Projections.fields(SomeBean.class, Expressions.as(Expressions.constant(10), "layer_id"));
      List<SomeBean> layerIds = sqlQueryFactory.select(projections).fetch();
```

Usage:
Java 11
querydsl 4.4.0
Postgres

**Comment by jwgmeligmeyling** [comment]
The alias needs to be the field name in order to work with `Projections.fields`. So `layer_id` needs to be `layerId`.

**Comment by kanimaru** [comment]
Hi Thanks for your fast answer.
But then I end up with mixed casing in the SQL :S columns from tables still has underscores but only when I don't use alias. 
But when there is no other solution I need to mixit :(

**Comment by jwgmeligmeyling** [comment]
Projections has an additional method overload for fields which allows you to provide a Map<String, Expression> as parameter, where you can explicitly map field names to expression without relying on aliases of the expressions.

**Comment by kanimaru** [comment]
Perfect that is what I was looking for Big Thanks!
To complete the example for other ppls that are looking for this:
```
var projections = Projections.fields(SomeBean.class, Map.of("layerId", Expressions.as(Expressions.constant(10), "layer_id")));
      List<SomeBean> layerIds = sqlQueryFactory.select(projections).fetch();
```
