### ISSUE TITLE
what is the mean of mixin , can i use "this" Replace  it

### ISSUE THREAD

**Issue by edcjian** [querydsl/querydsl#2795]
## Description

![image](https://user-images.githubusercontent.com/48635933/113563899-11c08a80-963b-11eb-9f75-f3e6e0bd5e99.png)
![image](https://user-images.githubusercontent.com/48635933/113563937-1d13b600-963b-11eb-986b-87b76bc34bca.png)

**Comment by jwgmeligmeyling** [comment]
Yes you can, but it adds serialization overhead.
