### ISSUE TITLE
querydsl generates invalid JPA (that hibernate accepts)

### ISSUE THREAD

**Issue by emmanueltouzery** [querydsl/querydsl#2799]
## Observed vs. expected behavior

We write a querydsl expression which compiles. When we run it, the expression works as expected with a JPA hibernate backend, but fails at runtime with a JPA eclipselink backend.

We would like to see that if a query compiles as per querydsl, then it will work. So maybe querydsl must require the parameter to be present, or maybe there could be some setting somewhere to generate a stricter version of the calls that require the parameter. If querydsl could "infer" or generate the parameter a compilation time, it would be even better...

## Steps to reproduce

This seems to be a long-known issue, for instance this is explained with full steps to reproduce there:
https://leanpub.com/opinionatedjpa/read#leanpub-auto-eager-to-one-without-joins

Basically we must add aliases in the querydsl join, or the query will fail on eclipselink at runtime. I'll now paste all the info from that link, but we also see this in our setup:

```java
 1 @Entity
 2 public class Dog {
 3 
 4   @Id
 5   @GeneratedValue(strategy = GenerationType.IDENTITY)
 6   private Integer id;
 7 
 8   private String name;
 9 
10   @ManyToOne(fetch = FetchType.EAGER)
11   @JoinColumn(name = "owner_id")
12   private Owner owner;
```
```java
 1 @Entity
 2 public class Owner implements Serializable {
 3 
 4   @Id
 5   @GeneratedValue(strategy = GenerationType.IDENTITY)
 6   private Integer id;
 7 
 8   private String name;
 9 
10   @OneToMany(mappedBy = "owner")
11   private Set<Dog> dogs;
```

```java
1 List<Dog> dogs = new JPAQuery<>(em)
2   .select(QDog.dog)
3   .from(QDog.dog)
4   .leftJoin(QDog.dog.owner)
5   .fetch();
```

This previous query works on hibernate, fails on eclipselink (which reports that `An identification variable must be defined for a JOIN expression`), and eclipselink seems to be in the right when it comes to the JPA specification. This works on eclipselink too:

````java
1 List<Dog> dogs = new JPAQuery<>(em)
2   .select(QDog.dog)
3   .from(QDog.dog)
4   .leftJoin(QDog.dog.owner, QOwner.owner)
5   .fetch();
````

## Environment

Querydsl version: 4.1.4

Querydsl module: JPA

Database: H2

JDK: 11

**Comment by jwgmeligmeyling** [comment]
The "bug" here is that you use QueryDSL to create invalid queries. That actually happens to be valid query (as for Hibernate) but is simply unsupported by EclipseLink.

QueryDSL is a DSL that allows you to write anything you want. We don't do special transformations and we don't make assumptions on what the user might have meant. The expressions translate directly to a query fragment equivalent.

So yes, you can create invalid queries using QueryDSL, and no, there is not much we can (or want) to do about it.
