### ISSUE TITLE
Postgres custom function call with Spring JPA & Querydsl

### ISSUE THREAD

**Issue by alimoullim91** [querydsl/querydsl#2806]
Hello there,
I am trying to integrate a custom function call that returns a table into Spring, JPA, Querydsl. I did come across forum https://github.com/querydsl/querydsl/issues/35 and wanted to confirm whether the RelationalFunctionCall method would still work in case of primary table with no join? The function itself returns a table i.e. "SELECT * FROM FUNCTION_NAME(PARAMS....)". If not how can I implement this in spring, jpa, querydsl. A little help will speed things up.

**Comment by jwgmeligmeyling** [comment]
This is practically impossible to do with JPA and Hibernate, and therefore not something where QueryDSL can help.
