### ISSUE TITLE
There is no documentation about how to handle arrays when using native queries

### ISSUE THREAD

**Issue by aaramg** [querydsl/querydsl#2808]
Hi.
I have done my best to find how to call, but could not find anywhere:
```
List<String> list = new ArrayList<>();
Set<String> set = new HashSet<>();
Expressions.template(
                Tuple.class,
                "calculate_func({0}, {1})",
                list,
                set
                );
```
when my postgresql function is:
```
CREATE OR REPLACE FUNCTION calculate_func(
    list varchar[],
    set varchar[]
)
    returns table
            (
                id  varchar,
                ids varchar[]
            )
AS
$$
-- something here
$$
    LANGUAGE SQL;
```

1. How to do the conversions?? 
2. How to convert set or list to querydsl format array or collection, don't know which later will be translated to array???
3. How to get `ids` from return type `varchar[]`?? I mean how to convert back to set or list?
4. How to initialize an empty array like this: '{}' as it is in postgresql? for example, null values are handled as : `Expressions.nullExpression()`. Which is the equivalent for arrays?
Please help me to figure it out. It is very urgent for our project to go forward. Would be great to have documentation about this.
Thanks in advance

P.S. >>> I am using: `final JPASQLQuery<Tuple> sqlQuery = new JPASQLQuery<>(entityManager, PostgreSQLTemplates.builder().build())`

**Comment by jwgmeligmeyling** [comment]
As long as the JDBC driver supports arrays, the `ArrayType` should be used. For example, look at the https://github.com/querydsl/querydsl/blob/master/querydsl-sql/src/test/java/com/querydsl/sql/ArrayTypesTest.java .

The variables would need to be an array instead of a collection though.
