### ISSUE TITLE
SQL cannot be executed using custom column names as conditions in having

### ISSUE THREAD

**Issue by 943739901** [querydsl/querydsl#2810]
## Observed vs. expected behavior

```
QScExEscore escore = QScExEscore.scExEscore;
QScExStudent student = QScExStudent.scExStudent;

List<ScExStudentRespDTO> scores = jpaQueryFactory.select(
        Projections.bean(
                ScExStudentRespDTO.class,
                student.id,
                student.name,
                escore.score.coalesce(BigDecimal.ZERO).asNumber().avg().castToNum(BigDecimal.class).as("score")
        )
).from(student)
        .leftJoin(escore).on(student.id.eq(escore.studentId), student.isDeleted.eq(0))
        .groupBy(student.id)
        .having(Expressions.numberPath(BigDecimal.class, "score").goe(new BigDecimal(60)))
        .orderBy(Expressions.numberPath(BigDecimal.class, "score").desc()).fetch();
```

----- report exception
com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Unknown column 'score' in 'having clause'

SELECT
	scexstuden0_.id AS col_0_0_,
	scexstuden0_.NAME AS col_1_0_,
	cast( avg( COALESCE ( scexescore1_.score, ? ) ) AS DECIMAL ( 19, 2 ) ) AS col_2_0_ 
FROM
	sc_ex_student scexstuden0_
	LEFT OUTER JOIN sc_ex_escore scexescore1_ ON ( scexstuden0_.id = scexescore1_.student_id AND scexstuden0_.is_deleted =? ) 
WHERE
	( scexstuden0_.is_deleted = 0 ) 
GROUP BY
	scexstuden0_.id 
HAVING
	score >=? 
ORDER BY
	col_2_0_ DESC

I found that orderby was converted to " col_2_0_  " , but having not.

## Environment

Querydsl version: 4.4.0

Querydsl module:querydsl-jpa

Database:mysql

JDK:1.8

**Comment by jwgmeligmeyling** [comment]
JPQL doesn't support referencing select aliases in the having clause and nor does Hibernate.

This is expected  behaviour for JPA queries. You could suggest it as an enhancement to Hibernate though. And possibly if you upgrade to the newest Hibernate version it might already be fixed. I vagely remember implementing something over @ hibernate.

**Comment by 943739901** [comment]
thank you

**Comment by jwgmeligmeyling** [comment]
I didn't implement it for the having clause, but I did implement it for the group by clause and the fix should be quite similar https://github.com/hibernate/hibernate-orm/pull/3022
