### ISSUE TITLE
MathExpressions.max/min support Date

### ISSUE THREAD

**Issue by coder-free** [querydsl/querydsl#2812]
## Why the new feature should be added

I want get the max value from tow datetime field. But  `MathExpressions.max/min` only support number field. I think date that is `Comparable` type. Should support it.

## How the new feature should work

Code like this:
```
DateTimeExpression<Date> createTimeExpression = MathExpressions.max(
                QTableName.tableName.createtime1,
                QTableName.tableName.createtime2);
```

**Comment by jwgmeligmeyling** [comment]
There is `QTableName.tableName.createtime1.max()`. I think you're looking for `greatest`. `ComparableBaseExpression` seems a a more appropiate place to implement that extension than `MathExpressions`.

**Comment by nganne** [comment]
Hi I am trying to help out on this issue and wonder what's the difference between max and greatest? What is the feature supposed to do? 

Thank you!

**Comment by jwgmeligmeyling** [comment]
Greatest returns the biggest value of two values (so it takes two expressions as arguments). Max is an aggregate function that returns the greatest value for a single expession.
