### ISSUE TITLE
How to Globally Configure Serializer Using Gradle

### ISSUE THREAD

**Issue by b0dea659-c92f** [querydsl/querydsl#2818]
## Description

Hello,

I am running into an issue using Query DSL and Spring where I have an overridden getter in my Entity class that returns a custom type, but it is just a String field under the hood. I am getting a ConverterNotFoundException

org.springframework.core.convert.ConverterNotFoundException: No converter found capable of converting from type [java.lang.String] to type [Custom Type]

According to the documentation, we can globally configure QueryDSL to use the fields to determine metadata types rather than getters. This seems like it would solve my issue. However, the docs only show how to do this using Maven, and I am using Gradle. Could you provide details on how to do this?

Also, according to the docs both useFields and useGetters have a default value of true. How is this possible? I would think they are mutually exclusive. Thanks!!

![Documentation](https://user-images.githubusercontent.com/83670785/117060387-dcb55f80-acee-11eb-8292-30b98a2bdbfc.PNG)

**Comment by jwgmeligmeyling** [comment]
There is currently no Gradle plugin for QueryDSL SQL codegen. There are plenty of issues about that.

Please ask questions like this on StackOverflow or in the Querydsl Google Group. We only use Github for bug reports and feature requests.
