### ISSUE TITLE
Integrate with spring-security

### ISSUE THREAD

**Issue by Mark1161993** [querydsl/querydsl#2824]
## Why the new feature should be added
Please consider the integration with spring-security to automatic filter queries with #{ authentication?.name } predicate.

## How the new feature should work
Support spring-security authentication filter, for example like:
https://docs.spring.io/spring-security/site/docs/current/reference/html5/#data-query

**Comment by jwgmeligmeyling** [comment]
Spring Data integrates with QueryDSL, not the other way around.
