### ISSUE TITLE
missing from docs, minimum hibernate version

### ISSUE THREAD

**Issue by gcbw** [querydsl/querydsl#2828]
## Description

README and docs in general (wiki?) does not mention any hibernate or other dependencies version. pom.xml is set at [5.4](https://github.com/querydsl/querydsl/blob/abec6411b4656c3cb4c83c1f2e912328552cf039/pom.xml#L60) (and since 5.2-5.3 had some interface changes, am i correct to assume queryDSL is only supported with 5.3+?)

---

Trying to add to a project with hibernate 4.4, i saw [explicit calls for](https://github.com/querydsl/querydsl/blob/f7254f4e0d8898f7a47b0b124f09d30b3f26fcbd/querydsl-jpa/src/main/java/com/querydsl/jpa/HibernateHandler.java#L90) `org.hibernate.query.Query.class` (present on 5.x only) but other than [this specific case](https://github.com/querydsl/querydsl/blob/f7254f4e0d8898f7a47b0b124f09d30b3f26fcbd/querydsl-jpa/src/test/java/com/querydsl/jpa/HibernateHandlerTest.java#L139) things mostly work fine with hibernate 4.4

**Comment by jwgmeligmeyling** [comment]
QueryDSL supports any implementation of JPA. So Hibernate 3-6 are fine.

**Comment by gcbw** [comment]
`org.hibernate.query.Query.class` causes a class not found exception. that class is not available before hibernate-5.x branch as I stated before.

**Comment by jwgmeligmeyling** [comment]
The Hibernate integration requires Hibernate 5.4.x, for Hibernate 5.3 I recommend using the JPA API's only. So `JPAQuery` instead of `HQLQuery` with a `JPQLTemplates` as Templates instance.

**Comment by jwgmeligmeyling** [comment]
Anyways, with such old Hibernate versions, its better to use old QueryDSL versions as well. 😄 

The upgrade path to Hibernate 5.x is not too bad and well over due it seems.

**Comment by gcbw** [comment]
Thank you for the quick reply! indeed, we had HQLTemplate and I missed this was triggering the hibernate flow when looking at the code here.

querydsl is our upgrade path out of our hibernate 4 predicament :)
thanks again!
