### ISSUE TITLE
How to use mysql find_in_set function in querydsl?

### ISSUE THREAD

**Issue by lin-mt** [querydsl/querydsl#2831]
`Expressions.booleanTemplate("FIND_IN_SET({0}, {1})", path, param)`

It doesn't working.

It cause
```java
Caused by: org.hibernate.hql.internal.ast.QuerySyntaxException: unexpected AST node: ( near line 3, column 18 [select task
from com.simple.entity.Task task
where FIND_IN_SET(task.parentIds, ?1)]
```

**Comment by jwgmeligmeyling** [comment]
This is because Hibernate doenst allow the find in set function in the MySQL dialect.

You should use a custom dialect or register a custom function. It is also possible to wrap the function in a JPQL Function-function.
