### ISSUE TITLE
Dependency management clash with Spring boot

### ISSUE THREAD

**Issue by tstavinoha** [querydsl/querydsl#2921]
## Observed vs. expected behavior

When using Querydsl BOM to manage dependencies in Maven projects, if Querydsl BOM is listed before Spring Boot dependencies, it causes the scope modifier `provided` to be added to dependency `jakarta.persistence:jakarta.persistence-api`. This causes a usability issue, because it makes the users have to manually list a dependency which would ideally be completely transient and pulled into the project by Spring Boot starter. We need to have Querydsl in front of Spring Boot BOM in order to use newer version of Querydsl.

Would you consider removing the `provided` modifier from the parent project?
It was recently [adjusted](https://github.com/querydsl/querydsl/commit/356be9d752b4da64bce41875755c738925f0c83e#diff-9c5fb3d1b7e3b0f54bc5c4182965c4fe1f9023d449017cece3005d3f90e8e4d8)

## Steps to reproduce

Create a minimal project setup, add a dependency to spring-boot-starter-data-jpa and dependency management in order that querydsl bom precedes spring boot BOM.

```
    <dependencyManagement>
        <dependencies>

            <dependency>
                <groupId>com.querydsl</groupId>
                <artifactId>querydsl-bom</artifactId>
                <version>5.0.0.M1</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>

            <!-- SPRING BOM -->
            <dependency>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-dependencies</artifactId>
                <version>2.5.1</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>

        </dependencies>
    </dependencyManagement>
    <dependencies>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-jpa</artifactId>
        </dependency>

    </dependencies>
```

Output of `dependency:tree` should be something like:
```
[INFO] --- maven-dependency-plugin:2.8:tree (default-cli) @ demo ---
[INFO] com.example:demo:jar:0.0.1-SNAPSHOT
[INFO] \- org.springframework.boot:spring-boot-starter-data-jpa:jar:2.5.1:compile
[INFO]    \- jakarta.persistence:jakarta.persistence-api:jar:2.2.3:provided (scope managed from compile)
```

## Environment

Querydsl version: 5.0.0.M1

Querydsl module: general

Database: n/a

JDK: 16

## Additional details
I can prepare a PR if maintainers are OK with this.

**Comment by jwgmeligmeyling** [comment]
We can change the scope for the parent-pom / BOM to `compile`, as long as the scope is still overridden as `provided` in all Querydsl sub-modules.

However, doesn't the Spring Boot BOM already declare QueryDSL dependencies? To what extent is it actually a sensible use case to combine both BOMs?

**Comment by tstavinoha** [comment]
Use case we're aiming for is to use the newest version of Querydsl (milestone) which is still not present in current Spring Boot. Overriding is possible only if Querydsl is listed first, otherwise the dependency versions get mixed up.
It makes more sense to use BOM from the source rather than to define our own.

**Comment by F43nd1r** [comment]
Is there a reason not to override `querydsl.version` with just the spring bom?

**Comment by tstavinoha** [comment]
We can't override it in that manner because it only works when using spring boot parent, and we are using just the dependency management part (due to the fact that we use a company parent project).

**Comment by tstavinoha** [comment]
Opened PR: https://github.com/querydsl/querydsl/pull/2923
