### ISSUE TITLE
IN clause with a single value creates an invalid predicate

### ISSUE THREAD

**Issue by andygoossens** [querydsl/querydsl#2922]
## Observed vs. expected behavior

Using an IN clause with a single value on the right hand side creates an invalid predicate. Having two or more values is OK. 

See example in the section below.
I expected the serializer in `comparingTuples()` to return `... in ((?, ?))` or even `... = (?, ?)`.
I expected the serializer in `comparingStrings()` to return `... in (?)` or even `... = ?`.

## Steps to reproduce

Example is based on https://github.com/querydsl/querydsl/issues/2920#issuecomment-864852911
```java
@Test
public void comparingTuples() {
    SQLSerializer serializer = new SQLSerializer(Configuration.DEFAULT);
    BooleanExpression expression = tuple(employee.firstname, employee.lastname).in(
            tuple(new Param<String>(String.class, "a"), new Param<String>(String.class, "b")));
    serializer.handle(expression);

    /*
    org.junit.ComparisonFailure: 
    Expected :(EMPLOYEE.FIRSTNAME, EMPLOYEE.LASTNAME) in ((?, ?))
    Actual   :(EMPLOYEE.FIRSTNAME, EMPLOYEE.LASTNAME) in (?, ?)
    */
    assertEquals("(EMPLOYEE.FIRSTNAME, EMPLOYEE.LASTNAME) in ((?, ?))", serializer.toString());
}

public SimpleExpression<Object> tuple(Expression<?>... args) {
    return Expressions.template(Object.class, "({0}, {1})", args);
}

@Test
public void comparingStrings() {
    SQLSerializer serializer = new SQLSerializer(Configuration.DEFAULT);
    BooleanExpression expression = employee.firstname.in(
          new Param<String>(String.class, "a"));
    serializer.handle(expression);

    /*
    org.junit.ComparisonFailure:
    Expected :EMPLOYEE.FIRSTNAME in (?)
    Actual   :EMPLOYEE.FIRSTNAME in ?
     */
    assertEquals("EMPLOYEE.FIRSTNAME in (?)", serializer.toString());
}
```

## Environment

Querydsl version: current master (d0329fc4b), but issue exists in 4.* releases as well

Querydsl module: SQL, JPA

Database: n/a (invalid SQL syntax that is probably rejected by all database implementations)

JDK: 11

## Additional details

The JPA module has a similar issue. To reproduce replace
`SQLSerializer serializer = new SQLSerializer(Configuration.DEFAULT);`
by
`JPQLSerializer serializer = new JPQLSerializer(JPQLTemplates.DEFAULT);`.

**Comment by jwgmeligmeyling** [comment]
Please open a discussion instead.
