### ISSUE TITLE
Grouping result using QueryDslPredicateExecutor

### ISSUE THREAD

**Issue by vitomanu96** [querydsl/querydsl#2969]
## Why the new feature should be added

 I can not group by result when using QueryDslPredicateExecutor. 
 The interface QueryDslPredicateExecutor should implement another method to groupBy result, even with pagination.

## How the new feature should work

```
  Page<T> findAllAndGroupBy(String groupByKey,Predicate var1, Pageable var2);

 @Entity
 class People {
    String name
    String surname
}

repository.findAllAndGroupBy('surname', predicate, page);
```

**Comment by jwgmeligmeyling** [comment]
`QueryDslPredicateExecutor` is a class from Spring Data, not from Querydsl. Please file your issue there 😄
