### ISSUE TITLE
OSGI manifest is missing for 5.0.0

### ISSUE THREAD

**Issue by jherkel** [querydsl/querydsl#2979]
## Observed vs. expected behavior

OSGI manifest is missing for querydsl 5.0.0

## Steps to reproduce
Open final JAR and check MANIFEST.MF.  
```
Querydsl 5.0.0 :
Manifest-Version: 1.0
Automatic-Module-Name: com.querydsl.core
Build-Jdk-Spec: 1.8
Created-By: Maven Jar Plugin 3.2.0
```

Querydsl 4.4.0:
```
Manifest-Version: 1.0
Bundle-Description: core module for querydsl
Bundle-License: http://www.apache.org/licenses/LICENSE-2.0.txt
Bundle-SymbolicName: com.querydsl.core
Archiver-Version: Plexus Archiver
Built-By: jkt
Bnd-LastModified: 1600524810352
Bundle-ManifestVersion: 2
Bundle-DocURL: http://www.querydsl.com
Bundle-Vendor: Querydsl
Import-Package: com.google.common.base;version="18.0.0",com.google.com
 mon.cache;version="18.0.0",com.google.common.collect;version="18.0.0"
 ,com.google.common.primitives;version="18.0.0",com.mysema.commons.lan
 g;version="[0.2,1)",javax.annotation,javax.lang.model,net.sf.cglib.pr
 oxy;resolution:=optional
Tool: Bnd-2.1.0.20130426-122213
Export-Package: com.querydsl.core;uses:="com.mysema.commons.lang,com.q
 uerydsl.core.types,javax.annotation";version="4.4.0",com.querydsl.cor
 e.alias;uses:="com.querydsl.core.types,com.querydsl.core.types.dsl,ja
 vax.annotation";version="4.4.0",com.querydsl.core.annotations;version
 ="4.4.0",com.querydsl.core.dml;uses:="com.querydsl.core,com.querydsl.
 core.types,javax.annotation";version="4.4.0",com.querydsl.core.group;
 uses:="com.mysema.commons.lang,com.querydsl.core,com.querydsl.core.ty
 pes,com.querydsl.core.types.dsl";version="4.4.0",com.querydsl.core.su
 pport;uses:="com.mysema.commons.lang,com.querydsl.core,com.querydsl.c
 ore.types,com.querydsl.core.types.dsl,javax.annotation";version="4.4.
 0",com.querydsl.core.types;uses:="com.google.common.base,com.google.c
 ommon.collect,com.querydsl.core,javax.annotation";version="4.4.0",com
 .querydsl.core.types.dsl;uses:="com.google.common.collect,com.queryds
 l.core,com.querydsl.core.types,javax.annotation";version="4.4.0",com.
 querydsl.core.util;uses:="com.google.common.base,com.querydsl.core.ty
 pes,javax.annotation";version="4.4.0"
Bundle-Name: Querydsl - Core module
Bundle-Version: 4.4.0
Created-By: Apache Maven Bundle Plugin
Build-Jdk: 1.8.0_202
```

## Environment

Querydsl version:
5.0.0

**Comment by jwgmeligmeyling** [comment]
The `felix` configuration is still there: https://github.com/querydsl/querydsl/blob/master/pom.xml#L336-L358 Not sure why it's not working anymore. We did make a couple of manifest changes for the support of Automatic Modules.

Apparently, the OSGi functionality was never tested to begin with (not in the test suite at least). I am not planning on supporting it without a proper test suite for it. We will be accepting PR's . For now I'll just mention in the changelog that OSGI support is removed.

**Comment by jherkel** [comment]
For non osgi enviroment (majority of querydsl users) there won't be any problem if jar archive will contain OSGI manifest entries as before. Of course there is a way how to add unit test via pax osgi exam but lot of libraries export OSGI entries without any unit tests. Because pax exam for this case means that during test phase a test server will be loaded (for example karaf) and also lot of additional libraries will be downloaded like hibernate, aries, etc.). So it is a possible way but I think it is overhead because as I wrote above OSGI entries cannot break querydsl for non osgi users. And for OSGI users (like me) if there will be a problem we will have to fix it ourselves. And if there will be a problem that no one will fix broken manifest entries someone could remove OSGI manifest from build process.
If it is a possible way for you I can check build and found out why manifest entries are missing. Also I can check if querydsl is loaded under karaf.

**Comment by F43nd1r** [comment]
Maybe related #2836

**Comment by jwgmeligmeyling** [comment]
We will definitely accept PR's that fix the OSGi compatibility and I am also willing to finish uncompleted attempts in doing so. However I have never worked with OSGi before, so it would be nice to have a proper test case or example project to test it against.

**Comment by jwgmeligmeyling** [comment]
Actually a PR is provided for this and we intend to include that in the next release.
