### ISSUE TITLE
HibernateHandler#iterate does not automatically close the session in querydsl 4.4.0，Is it correct?

### ISSUE THREAD

**Issue by ankelen** [querydsl/querydsl#2980]
## Observed vs. expected behavior
Describe the issue you are experiencing: 
What behaviour do you see: session is not closed
What is the expected behaviour: session should be closed

## Environment

Querydsl version: 4.4.0

Querydsl module: querydsl-jpa

Database: mysql 8.0

JDK: 1.8

## Additional details
querydsl 4.3.1 HibernateHandler#iterate use query.getResultList(), and the session is closed correctly

**Comment by jwgmeligmeyling** [comment]
The calling code is responsible for both opening and closing the session. The iterator returned by `HibernateHandler` should also be invoked from calling code and is in turn responsible for closing the JDBC Result and freeing up the resources.

**Comment by ankelen** [comment]
I fetch data through JPAQueryFactory in another thread. the data fetch code like this
```java
// inject by spring
JPAQueryFactory factory;

Map<ID,ENTITY> result = factory.select(entity)
       .from(entity)
       .transform(GroupBy.groupBy(entity.id).as(GroupBy.list(entity)));
```
in querydsl4.4.0, i dont konw how to close the session.

**Comment by jwgmeligmeyling** [comment]
The session is not opened by Querydsl. Its provided to Spring through the `JPAQueryFactory`. Spring has to close the session.

**Comment by nathanmolinari** [comment]
We had the same problem. Only with iterator method. The other methods spring closes the connection properly. So it should be a spring problem @jwgmeligmeyling?
