### ISSUE TITLE
version 5.0.0 missing from https://querydsl.com/

### ISSUE THREAD

**Issue by froque** [querydsl/querydsl#2987]
Reference documentation and Javadocs are not available for release v5.0.0:

![querydsl_releases](https://user-images.githubusercontent.com/8249379/128025971-77656947-3a7b-40b1-ba1e-53f46e4ab7f9.png)

The links https://querydsl.com/static/querydsl/5.0.0/reference/html_single/ and https://querydsl.com/static/querydsl/5.0.0/apidocs/ don't work.

In releases history there is no information about version 5.0.0. 

![querydsl_releases_history](https://user-images.githubusercontent.com/8249379/128026081-452f535e-dc29-4340-a22c-fa4fddb5e8b5.png)

**Comment by jwgmeligmeyling** [comment]
Yes, there are a few post release tasks that need to be done.

We just recently got access to the querydsl.com DNS, so we're in the process of redeploying the website.
Unfortunately we do not currently have access to Twitter or any other socials to make release announcements.

As a result, the changelog is posted on Github instead: https://github.com/querydsl/querydsl/releases/tag/QUERYDSL_5_0_0

**Comment by jwgmeligmeyling** [comment]
Changelog is now available at: https://querydsl.com/releases.html
Reference documentation (although slightly outdated): https://querydsl.com/static/querydsl/5.0.0/reference/html_single/
Javadoc: generation seems broken in 5.x branch currently
