### ISSUE TITLE
Default Annotation resolution inconsistent

### ISSUE THREAD

**Issue by johnjaylward** [querydsl/querydsl#2995]
https://github.com/querydsl/querydsl/blob/26f3c89a8a007a9135eb57f095b07e6fc24c516d/querydsl-codegen/src/main/java/com/querydsl/codegen/GeneratedAnnotationResolver.java#L49

**How to reproduce:**

1. Initial setup:
    * Have multiple JVMs available (java 1.8 and java 1.10+)
    * `build.gradle` setup to compile against java 1.8
    * Run Eclipse on JVM 1.10+
2. Build via gradle on the command line - properly generates files using `javax.annotation.Generated` - compatible with Java 1.8
3. Build via gradle using the Eclipse interface and the tool incorrectly locates `javax.annotation.processing.Generated` - which is not compatible with Java 1.8

**Expected Results**

The tool should consistently use the annotation in the target runtime regardless of the runtime being used to generate the code.

Example `build.gradle`

```groovy
buildscript {
    repositories {
        jcenter()
        maven { url 'https://plugins.gradle.org/m2/' }
    }
}

wrapper { gradleVersion = '4.10.3' }

apply plugin: 'java'

repositories {
    mavenCentral()
}

sourceCompatibility = 1.8
targetCompatibility = 1.8

sourceSets {
    main
    test
    generated
}

task generateAptSources(type: JavaCompile, group: 'build', description: 'Generates the QueryDSL query types') {
    source = sourceSets.main.java
    classpath = sourceSets.main.compileClasspath
    options.annotationProcessorPath = configurations.annotationProcessor + sourceSets.main.compileClasspath
    options.compilerArgs = [
        '-proc:only',
        '-processor',
        'com.querydsl.apt.hibernate.HibernateAnnotationProcessor',
        // Annotation Processor config options
        '-Aquerydsl.entityAccessors=true'
    ]
    options.warnings = false
    destinationDir = sourceSets.generated.java.srcDirs[0]
    outputs.dir destinationDir
}

compileJava.source generateAptSources.outputs.files

clean {
    delete sourceSets.generated.java.srcDirs
}

dependencies {
    compile group: 'com.querydsl', name: 'querydsl-core', version:'5.0.0'
    compile group: 'com.querydsl', name: 'querydsl-jpa', version:'5.0.0'

    // this is only needed for auto code generation, not deployed
    annotationProcessor group: 'com.querydsl', name: 'querydsl-apt', version: '5.0.0'
    compileOnly group: 'javax.annotation', name: 'javax.annotation-api', version: '1.3.2'
}

```

output of `./gradlew --version`:
```
$ ./gradlew --version

------------------------------------------------------------
Gradle 4.10.3
------------------------------------------------------------

Build time:   2018-12-05 00:50:54 UTC
Revision:     e76905e3a1034e6f724566aeb985621347ff43bc

Kotlin DSL:   1.0-rc-6
Kotlin:       1.2.61
Groovy:       2.4.15
Ant:          Apache Ant(TM) version 1.9.11 compiled on March 23 2018
JVM:          1.8.0_242 ( 25.242-b08)
OS:           Windows 10 10.0 amd64
```

output of Eclipse -> help -> about
```
Version: 2021-03 (4.19.0)
Build id: 20210312-0638

Buildship plugin 3.1.5v20210113-0929
```

**Installed JREs:**

* jdk-8.0.242.08-hotspot (AdoptOpenJDK release)
* jdk-11.0.1 (AdoptOpenJDK release)

**Comment by jwgmeligmeyling** [comment]
This change is intentional as the JRE 11 moved the `Generated` annotation to a different package. The default implementation simply picks the annotation present on the compilation classpath. Its possible that whilst the annotation is not available in your JRE itself, you have shipped it through a dependency, hence it still being available on the classpath, at least the compilation classpath that is.

If you want to make sure any compiler results in the same annotation being used, you can specify the annotation to use with `generatedAnnotationClass`. We even ship a candidate annotation within Querydsl itself: [com.querydsl.core.annotations.Generated](https://github.com/querydsl/querydsl/blob/master/querydsl-core/src/main/java/com/querydsl/core/annotations/Generated.java).

**Comment by johnjaylward** [comment]
Thanks. Updating my gradle config to look like this worked:

```groovy
task generateAptSources(type: JavaCompile, group: 'build', description: 'Generates the QueryDSL query types') {
    source = sourceSets.main.java
    classpath = sourceSets.main.compileClasspath
    options.annotationProcessorPath = configurations.annotationProcessor + sourceSets.main.compileClasspath
    options.compilerArgs = [
        '-proc:only',
        '-processor',
        'com.querydsl.apt.hibernate.HibernateAnnotationProcessor',
        // Annotation Processor config options
        '-Aquerydsl.entityAccessors=true',
        '-Aquerydsl.generatedAnnotationClass=com.querydsl.core.annotations.Generated'
    ]
    options.warnings = false
    destinationDir = sourceSets.generated.java.srcDirs[0]
    outputs.dir destinationDir
}

```

**Comment by johnjaylward** [comment]
Although, comparing the retention policy of all the options, it looks like `com.querydsl.core.annotations.Generated` is using the `CLASS` retention while the other annotations are using `SOURCE` retention.

Not sure if that should be consistent.
