### ISSUE TITLE
NoSuchMethodError in HibernateUtil.setValueWithNumberedLabel in Hibernate 5.2.0

### ISSUE THREAD

**Issue by alantan** [querydsl/querydsl#2997]
## Observed vs. expected behavior

When running update with "where... in (...) clause" query, there is an exception:

java.lang.NoSuchMethodError: 'org.hibernate.Query org.hibernate.query.Query.setParameterList(int, java.util.Collection)'
	com.querydsl.jpa.hibernate.HibernateUtil.setValueWithNumberedLabel(HibernateUtil.java:84)
	com.querydsl.jpa.hibernate.HibernateUtil.setConstants(HibernateUtil.java:78)
	com.querydsl.jpa.hibernate.HibernateUpdateClause.execute(HibernateUpdateClause.java:85)

## Steps to reproduce

Create an update with "where... in (...) clause", for example:

```
LocalDateTime now = LocalDateTime.now(ZoneOffset.UTC);
List<Long> ids =...
long countUpdated = new HibernateUpdateClause(session, qMyEntity)
                .set(qMyEntity.processedAt, now)
                .where(qMyEntity.id.in(ids))
                .execute();
```

## Environment

Querydsl version: 5.0.0

Querydsl module:
```
            <dependency>
                <groupId>com.querydsl</groupId>
                <artifactId>querydsl-apt</artifactId>
                <version>${querydsl.version}</version>
                <scope>provided</scope>
            </dependency>
            <dependency>
                <groupId>com.querydsl</groupId>
                <artifactId>querydsl-jpa</artifactId>
                <version>${querydsl.version}</version>
            </dependency>
```

Database: Postgresql

Hibernate: 5.2.0

JDK: 1.8

**Comment by kdebski85** [comment]
This method is not present in 5.2.
It is present in 5.3, but it is deprecated:
https://docs.jboss.org/hibernate/orm/5.3/javadocs/org/hibernate/Query.html#setParameterList-int-java.util.Collection-

Hibernate 5.2 had a lot of backwards-compatibility issues, what were resolved in 5.3. Maybe Querydsl 5.x should require Hibernate 5.3+

**Comment by jwgmeligmeyling** [comment]
There provider specific stuff can actually just be removed. A plain JPA API is all we need to do our stuff. No need to break Hibernate compatibility. The compatibility was mostly needed from back when Hibernate supported more than plain JPA (like WITH joins).

Why are you using  `HibernateUpdateClause`  instead of `JPAUpdateClause`?

**Comment by alantan** [comment]
> JPAUpdateClause

Oops, you're absolutely right. I replaced it with `JPAUpdateClause` and it worked perfectly. I'm closing this issue.
