### ISSUE TITLE
JSR310LocalDateType produces incorrect value for 2014-03-31

### ISSUE THREAD

**Issue by NathanJAdams** [querydsl/querydsl#3001]
## Observed vs. expected behavior
When getting a LocalDate with a value of 2014-03-31, the value is incorrectly interpreted as 2014-03-30

## Steps to reproduce
Create a JSR310LocalDateType
Call getValue() with a ResultSet containing a Date value of 2014-03-31
Return value is incorrect

## Environment
Querydsl version: 4.4.0
Querydsl module: querydsl-sql
JDK: 1.8

## Bugfix
I believe replacing the method contents with this should work as expected:

```
        Date date = rs.getDate(startIndex, utc());
        return (date != null) ? date.toLocalDate() : null;
```

**Comment by jwgmeligmeyling** [comment]
Please provide a pull request with the change.

Also: any particular reason why is the issue specific to 2014-03-31?

**Comment by RafaMassoni** [comment]
Hello, I have the same problem, when performing a query, the records come with data prior to the filter;

I made a query to return records from 2021/08/10 until 2021/09/10,
but the records returned are from  2021/08/09 to 2021/09/10

**Comment by jwgmeligmeyling** [comment]
@RafaMassoni I don't think your issue is related to this. `BETWEEN x AND y` expressions always include both bounds.

**Comment by RafaMassoni** [comment]
I'll explain in more detail,
in a table with the following records:

table: birthday
id  name           data
1  Rafa              2021/08/09
2  Jessica          2021/08/10
3  Samantha    2021/08/15

I'm using it this way
SELECT * FROM birthday WHERE birthday.date BETWEEN '2021-08-10' and '2021-08-20'

expected outcome:
id  name           data
2  Jessica        2021/08/10
3  Samantha   2021/08/15

published result:
id  name          data
1  Rafa             2021/08/09
2  Jessica         2021/08/10
3  Samantha   2021/08/15

in my code the date is correct, but when setting up a query and sending it to the bank, it receives the date one day late;

**Comment by davoudsa** [comment]
Unable to re-produce this issue, is it fixed?

**Comment by jwgmeligmeyling** [comment]
This issue is fixed now.
