### ISSUE TITLE
Querydsl parameter binding problem with @Convert Field

### ISSUE THREAD

**Issue by tj3828** [querydsl/querydsl#3017]
## Observed vs. expected behavior

When the field to which @Convert is applied is used as a search condition, 
if true is returned to the casebuilder statement in select, the @Convert is not applied to the parameter in the where statement.

Observed : select case when runsubject0_.Contents_Grade_Cd='' then 1 else 1 end as col_0_0_ from TBL_RUN_SUBJECT runsubject0_ where runsubject0_.Pass_Confirmed_Yn=**1**

expected behavior : select case when runsubject0_.Contents_Grade_Cd='' then 1 else 1 end as col_0_0_ from TBL_RUN_SUBJECT runsubject0_ where runsubject0_.Pass_Confirmed_Yn=**'Y'**

## Steps to reproduce

- entity field
```java
@Convert(converter = BooleanToYNConverter.class)
@Column(name="Pass_Confirmed_Yn")
private boolean passConfirmedYn;	
```

- converter
```java
public class BooleanToYNConverter implements AttributeConverter<Boolean, String> {
	
	@Override
	public String convertToDatabaseColumn(Boolean attribute) {
		return (attribute != null && attribute) ? "Y" : "N";
	}
	
	@Override
	public Boolean convertToEntityAttribute(String s) {
	    return "Y".equals(s);
    }
}
```
- Observed sample query
```java
JPAQuery<GovernmentSupportFundEnrollDTO> query = new JPAQuery<>(em);
            query
                .select(
                        Projections.fields(GovernmentSupportFundEnrollDTO.class,
                        new CaseBuilder()
                            .when(runSubject.contentsGradeCd.eq(""))
                                .then(true)
                            .otherwise(false)
                            .as("refundYn"))
                    )
                .from(runSubject)
                .where(runSubject.passConfirmedYn.eq(true))
                .fetch();
```
result : select case when runsubject0_.Contents_Grade_Cd='' then 1 else 1 end as col_0_0_ from TBL_RUN_SUBJECT runsubject0_ where runsubject0_.Pass_Confirmed_Yn=**1**

If the sample query does not return true to the case builder, @convert is normally applied.

- expected behavior sample query
```java
JPAQuery<GovernmentSupportFundEnrollDTO> query = new JPAQuery<>(em);
            query
                .select(
                        Projections.fields(GovernmentSupportFundEnrollDTO.class,
                        new CaseBuilder()
                            .when(runSubject.contentsGradeCd.eq(""))
                                .then(false)
                            .otherwise(false)
                            .as("refundYn"))
                    )
                .from(runSubject)
                .where(runSubject.passConfirmedYn.eq(true))
                .fetch();
```
result : select case when runsubject0_.Contents_Grade_Cd='' then 1 else 1 end as col_0_0_ from TBL_RUN_SUBJECT runsubject0_ where runsubject0_.Pass_Confirmed_Yn=**'Y'**

## Environment

Querydsl version: 4.2.1

Querydsl module: com.querydsl:querydsl-core:4.2.1

Database: mariadb

JDK: 1.8

**Comment by jwgmeligmeyling** [comment]
See https://github.com/querydsl/querydsl/issues/2652
