### ISSUE TITLE
Simplify distinct usage in API

### ISSUE THREAD

**Issue by timowest** [querydsl/querydsl#303]
`countDistinct`, `iterateDistinct`, `listDistinct` and `listDistinctResults` will be deprecated in Querydsl  3.0 and removed at a later time. This is because the same effect can be achieved with `distinct()` + `count/iterate/list/listResults`. This usage is more in line with other result modifiers such as `limit`, `offset` and `orderBy`.

As an example the following query

```
query.from(...).listDistinct(...)
```

can then be expressed as

```
query.from(...).distinct().list(...)
```

**Comment by hamavaro** [comment]
How Select DISTINCT on specific field can be done in querydsl 4.0.2 ?
Thanks.

**Comment by danielhiguerasgoold** [comment]
@hamavaro I think you are looking for the GROUP BY clause.
