### ISSUE TITLE
querydsl-codegen-utils:5.0.0 is missing in maven central

### ISSUE THREAD

**Issue by Sachpat** [querydsl/querydsl#3031]
## Observed vs. expected behavior
Hi, **com.querydsl:querydsl-codegen-utils:jar:5.0.0** which is mentioned in [querydsl-bom](https://search.maven.org/artifact/com.querydsl/querydsl-bom/5.0.0/pom) is not present in maven central or deployed in maven central .  But rather **com.querydsl:codegen-utils:5.0.0** is. Can you please let us know if it was by mistake or intended? 

## Steps to reproduce
Search for com.querydsl:codegen-utils:5.0.0 in Maven central

Querydsl version: 5.0.0

**Comment by Sachpat** [comment]
@jwgmeligmeyling can you please take a look at it?

**Comment by jwgmeligmeyling** [comment]
@lpandzic should we update the BOM or relocate the artefact according to convention?

**Comment by lpandzic** [comment]
I assume we should update the bom, but why have coordinates changed?

**Comment by jwgmeligmeyling** [comment]
I have no clue actually. Did they change though? It appears to me as if I just didn't follow artefact naming conventions while creating the POM which you seem to have assumed I had followed while creating the BOM 😉

**Comment by lpandzic** [comment]
I also don't recall, I remember copying most of it so it's likely it could also be a simple CP error.
Anyway, I'd agree with just aligning the bom with how artifact is defined, not the other way around.

**Comment by F43nd1r** [comment]
Yes, moving artifacts is quite a bit of hassle. Let's just adjust the pom

**Comment by lpandzic** [comment]
Ok I found out the reason: module is called `querydsl-codegen-utils` (root pom.xml) but artifact is called `codegen-utils`.
