### ISSUE TITLE
querydsl-sql生成类问题

### ISSUE THREAD

**Issue by xl-code-bit** [querydsl/querydsl#3069]
![image](https://user-images.githubusercontent.com/70997993/138663362-66d2183e-1f2c-4d21-9d77-dcc5783866fa.png)
生成的文件名应该和类名一致，现在不一致！

**Comment by kdebski85** [comment]
Have you renamed class AjJcBytimRequire to AjJcBytimrequire?
Do you use case-insensitive system (Windows)?

I would just delete QAjJcBytimrequire.java and generate again.

**Comment by xl-code-bit** [comment]
![image](https://user-images.githubusercontent.com/70997993/140440897-0d3f9206-272d-4ae1-9c6b-af96b546a2c9.png)
这是我的表名，我用的是Windows 10，类名我没有手动改过，都是生成的。

**Comment by aboutZZ** [comment]
Looks like the Q java file name is generated by JPA entity class name, but the Q class name is generated by database table name.
Your database table name is `aj_jc_bytimrequire`, so try rename your JPA entity class from `AjJcBytimRequire` (my guess) to `AjJcBytimrequire` and build again.
