### ISSUE TITLE
Add fetch methods returning java.util.Optional

### ISSUE THREAD

**Issue by Maia-Everett** [querydsl/querydsl#3073]
## Why the new feature should be added

Many data queries might either have or not have a result. For example, calling a max query on an empty dataset will return no value.

In Java 8, `java.util.Optional` and friends (`OptionalInt`, etc.) were added and are used consistently in new platform APIs, including the Stream API, to represent return results that may be missing. For example, `Stream.reduce` and `IntStream.max` return optionals. Using them with QueryDSL requires calling `Optional.ofNullable` at the call site, which is not very convenient.

## What is the current behavior?

Currently, `fetchOne` and `fetchFirst` will return `null` for queries that do not return a value, which is error-prone, especially if the project does not use a null-checking analysis tool.

## How the new feature should work

The existing API will be unchanged. Two new methods will be added to the `Fetchable` interface, with the following default implementations (names might be different):

```java
default Optional<T> fetchFirstOptional() {
    return Optional.ofNullable(fetchFirst());
}

default Optional<T> fetchOneOptional() throws NonUniqueResultException {
    return Optional.ofNullable(fetchOne());
}
```

## How does it affect existing features?

As this feature will introduce new terminal operations without changing the existing API, existing clients will not be affected.

**Comment by lpandzic** [comment]
I'm all for switching to Optional, if we want to switch all methods to Optional instead of nullable it's best we coordinate with Spring Data.
With the delivery we have I suspect by the time we have this released Java will have Optional as inline type.
