### ISSUE TITLE
QClass not generated for entity defined in src/test directory

### ISSUE THREAD

**Issue by arjunchhabra-invitae** [querydsl/querydsl#3096]
## Observed vs. expected behavior

QClasses are not generated for classes in `src/test` directory, but are generated fine for the same class if it is in `src/main` directory.

## Steps to reproduce

Add entity in `src/main/x.y.models` package. Run queryDSL task to confirm that QClass is generated.

Move this same entity class to `src/test/x.y.models` package. Run queryDSL task and see that QClass is not generated.

This makes it difficult to test QueryDSL functionality in example test entity class.

## Environment

Querydsl version: querydsl-core:4.4.0

Querydsl module: querydsl-jpa:4.4.0
 
Database: H2 in memory database

JDK: JDK 11

Kotlin: version 1.5.31

Spring Boot: 2.5.5

## Additional details

Please let me know if you require any additional details, I will work on creating a reproducer project.

**Comment by ahrytsiuk** [comment]
Hello @arjunchhabra-invitae, not sure what build tool you use and what is your configuration. However, the following minimal `pom.xml` will configure QueryDSL annotation processing for JPA/Hibernate annotations:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.github.ahrytsiuk</groupId>
    <artifactId>playground-querydsl</artifactId>
    <version>1.0-SNAPSHOT</version>

    <properties>
        <maven.compiler.source>17</maven.compiler.source>
        <maven.compiler.target>17</maven.compiler.target>
    </properties>

    <dependencies>
        <dependency>
            <groupId>com.querydsl</groupId>
            <artifactId>querydsl-core</artifactId>
            <version>4.4.0</version>
        </dependency>
        <dependency>
            <groupId>com.querydsl</groupId>
            <artifactId>querydsl-jpa</artifactId>
            <version>4.4.0</version>
        </dependency>
        <dependency>
            <groupId>com.querydsl</groupId>
            <artifactId>querydsl-apt</artifactId>
            <version>4.4.0</version>
            <scope>provided</scope>
            <optional>true</optional>
            <classifier>jpa</classifier>
        </dependency>
        <dependency>
            <groupId>org.hibernate</groupId>
            <artifactId>hibernate-core</artifactId>
            <version>5.6.5.Final</version>
        </dependency>
        <dependency>
            <groupId>javax.annotation</groupId>
            <artifactId>javax.annotation-api</artifactId>
            <version>1.3.2</version>
        </dependency>
    </dependencies>

</project>

```

The key part is the following dependency:
```xml
<dependency>
    <groupId>com.querydsl</groupId>
    <artifactId>querydsl-apt</artifactId>
    <version>4.4.0</version>
    <scope>provided</scope>
    <optional>true</optional>
    <classifier>jpa</classifier>
</dependency>
```

Also not that it is version `5.0.0` already available. And then you don't need to specify the following dependency:
```xml
<dependency>
    <groupId>javax.annotation</groupId>
    <artifactId>javax.annotation-api</artifactId>
    <version>1.3.2</version>
</dependency>
```

Hope this helps.

**Comment by jamesdh** [comment]
@arjunchhabra-invitae I was able to get this to work by adding the entity in question to my `src/test/java` directory, then made the following changes to `build.gradle`:

```groovy
sourceSets {
    main {
        java {
            srcDirs 'src/main/java'
            srcDirs "${buildDir}/generated/sources/annotationProcessor/java/main/"
        }
    }
    test {
        groovy {
            srcDirs 'src/test/java'
            srcDirs "${buildDir}/generated/sources/annotationProcessor/java/test/"
        }
    }
}

compileTestJava {
    options.annotationProcessorPath = configurations.annotationProcessor
    options.compilerArgs << "-proc:only"
    options.compilerArgs << "-processor"
    options.compilerArgs << "com.querydsl.apt.jpa.JPAAnnotationProcessor"
}
```

Bear in mind, my tests are written in Groovy, not Java. I tried making the test entity groovy as well, but hadn't no luck with compilation.

**Comment by Akhilesh170194** [comment]
@arjunchhabra-invitae did you find any solution to generate the Q classes for the entities under `src/test/java`?

**Comment by jamesdh** [comment]
@Akhilesh170194 see [this comment](https://github.com/querydsl/querydsl/issues/3096#issuecomment-1111376620)
