### ISSUE TITLE
JPAInsertClause insert error(maybe bug)

### ISSUE THREAD

**Issue by mr-raiden** [querydsl/querydsl#3097]
### Code

QCoin qCoin = QCoin.coin;
JPAInsertClause insert = new JPAInsertClause(getEntityManager(), qCoin);
long result = insert.columns(qCoin.id, qCoin.totalAmount).values(id,coin).execute();

### Exception Message

Caused by: org.hibernate.hql.internal.ast.QuerySyntaxException: unexpected token: values near line 3, column 1 [insert into Coin (id, totalAmount)
values  (?1, ?2)]

### Environment

Querydsl version: com.querydsl:querydsl-jpa:5.0.0
Database: mysql:mysql-connector-java:8.0.24
JDK: 1.8.0

**Comment by yafevin** [comment]
I have the same problem. Is there any solution?

**Comment by jeon6192** [comment]
I have the same problem. Is there any solution?

**Comment by wemeetwonhee** [comment]
I have the same problem. Is there any solution?

**Comment by xpwmaosldk** [comment]
Same here

**Comment by jangwd88** [comment]
Same... Here.... Help me

**Comment by jowoohyeong** [comment]
I have the same problem. Is there any solution?

**Comment by well-balanced** [comment]
I have the same problem. Is there any solution?

**Comment by hutlearner** [comment]
same here

**Comment by yiyi910** [comment]
I have the same problem. Is there any solution?

**Comment by boydiRS** [comment]
I have the same problem. Is there any solution?
