### ISSUE TITLE
Missing query parameters in the log

### ISSUE THREAD

**Issue by slma80** [querydsl/querydsl#3104]
Updating querydsl from 4.3.1 to 5.0.0, query parameters are no longer logged, also replacing `querydsl.parameters` with `querydsl_parameters` as indicated in [CHANGELOG.md](https://github.com/querydsl/querydsl/blob/master/CHANGELOG.md) file.

In `com.querydsl.sql.AbstractSQLQuery.logQuery(String, Collection<Object>)` method, MDC usage was removed with commit d489638f9e13cf1a3f94ab5da2bc4a85ba191a53

## Environment

Querydsl version: 5.0.0

Querydsl module: querydsl-sql

Database: MSSQL 2017

JDK: 11

**Comment by davoudsa** [comment]
I will work on this issue

**Comment by davoudsa** [comment]
I created this PR to fix this issue, please check: https://github.com/querydsl/querydsl/pull/3113/files
