### ISSUE TITLE
Build fails due to warnings after upgrading to QueryDSL 5.0

### ISSUE THREAD

**Issue by MalteJoe** [querydsl/querydsl#3124]
## Observed vs. expected behavior

Upgrading our project from Spring Boot 2.5.x to 2.6.x / to Spring Data 2021.1 / QueryDSL 5.0 fails with a very odd compiler warning:

```
[INFO] --- maven-compiler-plugin:3.8.1:compile (default-compile) @ spring-boot-26 ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 3 source files to /home/$USER/git/spring-boot-26/target/classes
[INFO] -------------------------------------------------------------
[WARNING] COMPILATION WARNING : 
[INFO] -------------------------------------------------------------
[WARNING] Cannot find annotation method 'from()' in type 'org.jetbrains.annotations.Range': class file for org.jetbrains.annotations.Range not found
[WARNING] Cannot find annotation method 'to()' in type 'org.jetbrains.annotations.Range'
[WARNING] Cannot find annotation method 'from()' in type 'org.jetbrains.annotations.Range'
[WARNING] Cannot find annotation method 'to()' in type 'org.jetbrains.annotations.Range'
[WARNING] Cannot find annotation method 'from()' in type 'org.jetbrains.annotations.Range'
[WARNING] Cannot find annotation method 'to()' in type 'org.jetbrains.annotations.Range'
[WARNING] Cannot find annotation method 'from()' in type 'org.jetbrains.annotations.Range'
[WARNING] Cannot find annotation method 'to()' in type 'org.jetbrains.annotations.Range'
[INFO] 8 warnings 
[INFO] -------------------------------------------------------------
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] warnings found and -Werror specified
```

We do not use Kotlin or Jetbrains annotations anywhere in the project, so this was very hard to track down, but I think it has to do with Spring-Data-JPAs Upgrade to QueryDSL 5, specifically with this: https://github.com/querydsl/querydsl/issues/2479 which now breaks our build (as we use `-Werror`).

## Steps to reproduce

* Minimal Reproduction Repo: https://github.com/MalteJoe/spring-boot-26-query-dsl-compiler-warnings
* Use Spring Initializr to create a Spring Boot Project with Spring Data JPA
* Add QueryDSL dependencies + APT Maven Plugin
* Add a basic entity

## Environment

Querydsl version: `5.0`

Querydsl module:

Database:

JDK: OpenJDK 17

## Additional details

Reverting the Spring Boot version to 2.5.7 (and thus QueryDSL 4.4.0) "fixes" the issue and generates the Query-classes correctly.

I'm sorry if this is a Spring Data issue, but to me it looks like the annotations being not present in QueryDSL are to blame.

**Comment by kdebski85** [comment]
Is there any reason why you still use apt-maven-plugin?
With new maven-compiler-plugin it is not needed.

You should instead use `annotationProcessorPaths` and `annotationProcessors` for maven-compiler-plugin. See https://maven.apache.org/plugins/maven-compiler-plugin/compile-mojo.html

**Comment by mmb-davidsmith** [comment]
would guess that it's because that's how the documentation says to do it: http://querydsl.com/static/querydsl/latest/reference/html/ch02.html#jpa_integration

**Comment by fp024** [comment]
hello.

The same warning was displayed after applying querydsl 5.0.0, but it was resolved after adding the following library.

```xml
     <dependency>
       <groupId>org.jetbrains</groupId>
       <artifactId>annotations</artifactId>
       <version>23.0.0</version>
     </dependency>
```

**Comment by fp024** [comment]
hello.

After applying querydsl 5.0.0, the same warning was output, but it was resolved after adding the following library.

```xml
       <dependency>
         <groupId>org.jetbrains</groupId>
         <artifactId>Annotation</artifactId>
         <version>23.0.0</version>
       </dependencies>
```

I don't know if it's correct, but in my case, it's a study project, so I didn't feel burdened with adding a library, so I just added it. 😅

And the maven-compiler-plugin version I use is 3.10.1,
Even without the apt-manven-plugin setting, the Q class was created well.

**Comment by maffe** [comment]
If you build fat JARs (including dependencies), you can use the _`provided`_ [scope](https://maven.apache.org/guides/introduction/introduction-to-dependency-mechanism.html#Dependency_Scope) to make the warnings disappear without bloating the JAR. Example:
```
<dependency>
    <groupId>org.jetbrains</groupId>
    <artifactId>annotations</artifactId>
    <version>24.0.1</version>
    <scope>provided</scope>
</dependency>
```
