### ISSUE TITLE
Legacy MongoDB driver included as dependency

### ISSUE THREAD

**Issue by mjustin** [querydsl/querydsl#3134]
## Observed vs. expected behavior

QueryDSL has been updated to support the MongoDB 4.x API, per #2689 (addressing #2681).  However, querydsl-mongodb exports the 3.x driver as a compile-time dependency.  This can be a problem when using alongside code or another library that expects the 4.x dependency.  The 3.x dependency (`org.mongodb:mongo-java-driver`) has a different artifact ID than the 4.x dependency (`org.mongodb:mongodb-driver-core`) but the same class names with breaking changes, so it could partially shadow the 4.x classes in a way that breaks at compilation or runtime.

I ran across this issue in a Spring Boot application where the built-in `micrometer-core` library failed at runtime due to methods added to the MongoDB interfaces in the 4.x version that were not present in the 3.x version.

I worked around this by explicitly excluding the `mongo-java-driver` from the `querydsl-mongodb` class.

```gradle
dependencies {
    implementation('com.querydsl:querydsl-mongodb') {
        exclude group: 'org.mongodb', module: 'mongo-java-driver' // Compile error in MongoMetricsConnectionPoolListener
    }
}
```

As far as expected behavior… I think I would expect the newer version of the MongoDB library to be the one used instead of the old one?  Maybe it's time to drop support for 3.x, or maybe there should be a different `querydsl-mongodb3` module.  Maybe make the 3.x version a "provided" dependency, and thus not pull in the dependency at all unless the user provides either the 3.x or 4.x version themselves.  I've seen this handled different ways in different projects; not sure which fits this project best.

### `build.gradle`

```groovy
plugins {
    id 'org.springframework.boot' version '2.6.2'
    id 'io.spring.dependency-management' version '1.0.11.RELEASE'
    id 'java'
}

group = 'com.example'
version = '0.0.1-SNAPSHOT'
sourceCompatibility = '11'

repositories {
    mavenCentral()
}

dependencyManagement {
    imports {
        mavenBom 'org.springframework.boot:spring-boot-dependencies:2.6.2'
    }
}

dependencies {
    implementation 'com.querydsl:querydsl-mongodb'
    implementation 'org.mongodb:mongodb-driver-sync'
}
```

### `IssueExample.java`

```java
package com.example.querydslmongodbissue;

import com.mongodb.event.*;

/*
 * Due to 3.x methods changed to default methods in 4.x, this compiles if
 * ConnectionPoolListener from mongodb-driver-core is the one that happens
 * to be chosen by the build system, but not if the one from mongo-java-driver is.
 */
public class IssueExample implements ConnectionPoolListener {
}
```

If the `mongo-java-driver` is excluded from the `querydsl-mongodb`, everything compiles as expected:

```groovy
implementation('com.querydsl:querydsl-mongodb') {
    exclude group: 'org.mongodb', module: 'mongo-java-driver'
}
```

### Dependencies:

```
$ ./gradlew dependencies --configuration compileClasspath

> Task :dependencies

------------------------------------------------------------
Root project 'querydsl-mongodb-issue'
------------------------------------------------------------

compileClasspath - Compile classpath for source set 'main'.
+--- com.querydsl:querydsl-mongodb -> 5.0.0
|    +--- org.mongodb:mongo-java-driver:3.12.8
|    \--- com.querydsl:querydsl-core:5.0.0
|         \--- com.mysema.commons:mysema-commons-lang:0.2.4
\--- org.mongodb:mongodb-driver-sync -> 4.4.0
     +--- org.mongodb:bson:4.4.0
     \--- org.mongodb:mongodb-driver-core:4.4.0
          \--- org.mongodb:bson:4.4.0

(*) - dependencies omitted (listed previously)

A web-based, searchable dependency report is available by adding the --scan option.

BUILD SUCCESSFUL in 752ms
1 actionable task: 1 executed
```

## Environment

Querydsl version: 5.0.0

Querydsl module: querydsl-mongodb

Database: MongoDB

JDK: 11

Gradle: 7.3.2

**Comment by Tobisaninfo** [comment]
Since updating to Spring Boot 2.6.x I got the same issue with maven as the build tool

**Comment by matthiasbruns** [comment]
Same problem here

``` 
val queryDslVersion = "5.0.0"
    implementation("com.querydsl:querydsl-mongodb:${queryDslVersion}") {
        exclude(group = "org.mongodb", module = "mongo-java-driver")
    }
    kapt("com.querydsl:querydsl-apt:${queryDslVersion}")
```

**Comment by PhilippS93** [comment]
yes, same problem here

**Comment by lmj12** [comment]
**querydsl-mongodb (5.0.0)
-> mongo-java-driver (3.12.11).  <--- legacy

spring-boot-starter-data-mongodb ( after 2.3.x  ~ 2.7.3(current) )
-> mongo-driver-sync (4.x.x)
--->  mongodb-driver-core (4.x.x)**

this two driver confilt.. 
please modify..

**p.s:  if you want use queryDSL on mongo, use spring 2.2.13 REALSES version.
in my case, it works**

**Comment by fmignone-appdirect** [comment]
Hi everyone! I'm having the same issue, could you solve it? Thanks!
