### ISSUE TITLE
Could not set configuration property "catalogPattern"  for querydsl-maven-plugin

### ISSUE THREAD

**Issue by USK-DIMA** [querydsl/querydsl#3174]
## Observed vs. expected behavior
I tried to set property "catalogPattern" for reading tables from different catalogs but this property is ignored.
I tried to debug this problem and found that this property is not set for the class AbstractMetaDataExportMojo.
Also I noticed that property "catalogPattern" is absent in the file plugin.xml.
I think the mistake is that line `@parameter` is lost in the java-doc for the field `private String catalogPattern;` in the class AbstractMetaDataExportMojo

## Steps to reproduce
1) Use MySQL DB
2) Create two schemas and fill it by tables
3) Config the plugin like this

```
            <plugin>
                <groupId>com.querydsl</groupId>
                <artifactId>querydsl-maven-plugin</artifactId>
                <version>${querydsl.version}</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>export</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <catalogPattern>schema1,schema2</catalogPattern>
                    <jdbcDriver>com.mysql.jdbc.Driver</jdbcDriver>
                    <jdbcUrl>jdbc:mysql://127.0.0.1:3306</jdbcUrl>
                    <jdbcUser>root</jdbcUser>
                    <jdbcPassword>root</jdbcPassword>
                    <packageName>com.demo.db.model</packageName>
                    <targetFolder>${project.basedir}/target/generated-sources/java</targetFolder>
                </configuration>
                <dependencies>
                    <dependency>
                        <groupId>mysql</groupId>
                        <artifactId>mysql-connector-java</artifactId>
                        <version>5.1.37</version>
                    </dependency>
                </dependencies>
            </plugin> 
```
4) run plugin

Expected behavior:
The plugin generated classes and place it to the directory ${project.basedir}/target/generated-sources/java

Actual behavior:
There is no any classes in the directory ${project.basedir}/target/generated-sources/java

Querydsl version: 5.0.0

Querydsl module: querydsl-maven-plugin

Database: MySql Community Server (GPL) 5.6.25 

JDK: 
java version "1.8.0_291"
Java(TM) SE Runtime Environment (build 1.8.0_291-b10)
Java HotSpot(TM) 64-Bit Server VM (build 25.291-b10, mixed mode)

**Comment by USK-DIMA** [comment]
I built my branch locally and verified my change. Bug is not reproduced

**Comment by jwgmeligmeyling** [comment]
Change is merged.
