### ISSUE TITLE
Control over the annotation processing execution in maven build

### ISSUE THREAD

**Issue by mheydem** [querydsl/querydsl#3185]
By having this dependency in my project
`
<dependency>
	<groupId>com.querydsl</groupId>
	<artifactId>querydsl-apt</artifactId>
	<version>4.2.2</version>
</dependency>
`
it is possible to
- use annotation processing in eclipse
- omit annotation processing in maven build by not configuring the apt-maven-plugin

After updating the dependency to
`
<dependency>
	<groupId>com.querydsl</groupId>
	<artifactId>querydsl-apt</artifactId>
	<version>5.0.0</version>
	<classifier>jakarta</classifier>
</dependency>
`
the annotation processing seems to run without a plugin configuration (e.g. apt-maven-plugin) during maven build.

Is there a way to get control over the annotation processing execution in maven? (except removing the dependency)
Is there a skip feature already?

**Comment by jwgmeligmeyling** [comment]
If you don't want APT, why not just remove the dependency on `querydsl-apt`. There is no need to have it in order to use just `querydsl-core`.

**Comment by mheydem** [comment]
We are using the querydsl code generation through the annotation processing of the eclipse ide.
That's why it is enough to have a `querydsl-jpa`  dependency in the pom.xml.
Thank you for your answer.
