### ISSUE TITLE
Allow generated code to implement given interfaces

### ISSUE THREAD

**Issue by fenuks** [querydsl/querydsl#3192]
## Why the new feature should be added
It's quite often that all entities share set of fields, for the sake of simplicity assume it's `id`. Currently it's not possible to write generic code that operates on all such entities. It would be useful if I could define interface

```java
public interface Shared {
   NumberPath<Long> getId();
   // more common fields
}
```

and entity

```java
@Config(entityAccessors=true, interfaces = {Shared.class})
@Entity
public class User {
    private Long id;
   // rest of fields
}
```

This way, one could write functions that work on all types of entities. Of course, it is now possible to write generic code over `EntityPathBase<User>`, but without access to fields, user is quite limited in what can be done.

## How the new feature should work
Config annotation could accept list of interfaces that generated QueryDSL classes are expected to implement.

**Comment by jwgmeligmeyling** [comment]
Interesting question, but with entity accessors themselves being an optional configuration I think this would become another rather obscure feature of Querydsl.

However, maybe you're able to pull of your desired flexibility using [Querydsl aliases](http://querydsl.com/static/querydsl/latest/reference/html/ch03s04.html):

```java
public static void test() {
    Document d = Alias.alias(Document.class, "d");
    Person p = Alias.alias(Person.class, "p");
    
    select(
            Alias.$(d.getId()),
            getId(d)
    ).from(Alias.$(d));
}

public static Expression<Long> getId(LongSequenceEntity longSequenceEntity) {
    return select(Alias.$(longSequenceEntity.getId()));
}
```

**Comment by fenuks** [comment]
Thank you for workaround. I've been using different approach with wrapper and like so:
```java
public class QTestWrapper extends QTest implements MyInterface {
    public static final QTestWrapper test = new QTestWrapper("test");
}
```

It works, but requires boilerplate. You might be right, that this feature would become obscure, but to defence of the idea, it should be relatively easy to add it.
