### ISSUE TITLE
[SQL] First element of sub-lists eg ((1,2), (1,3), (1,4)) is not enclosed with round brackets (usage with IN operator)

### ISSUE THREAD

**Issue by ulk200** [querydsl/querydsl#3200]
I'm trying to use the IN operator on multiple columns with actual values (not a subquery) like this :
`(SURVEY.ID, SURVEY.NAME) in ((1, 'test1'), (2, 'test2'))`
Unfortunatly the first set of elements is not enclosed with parentheses, i get this :
`(SURVEY.ID, SURVEY.NAME) in (1, 'test1', (2, 'test2'))`

Here is a test i wrote in `com.querydsl.sql.SQLSerializerTest`

```
    @Test
    public void list_in_other_lists() {
        Expression<?> expr = Expressions.list(survey.id, survey.name).in(
                Expressions.list(Expressions.constant(1), Expressions.constant("test1")),
                Expressions.list(Expressions.constant(2), Expressions.constant("test2"))
        );
        String str = new SQLSerializer(Configuration.DEFAULT).handle(expr).toString();
        assertEquals("(SURVEY.ID, SURVEY.NAME) in ((?, ?), (?, ?))", str);
    }
```

Tested in 4.3.1 and 5.0.0

**Comment by kashev** [comment]
Per @jwgmeligmeyling 's answer [here](https://github.com/querydsl/querydsl/discussions/2926#discussioncomment-908577), this isn't a bug, but instead `Expressions.list()` isn't meant to be nested, and instead one should use `Template` expressions.
