### ISSUE TITLE
custom Generated annotations

### ISSUE THREAD

**Issue by HonoluluHenk** [querydsl/querydsl#3212]
## Why the new feature should be added

We're using JaCoCo to compute test-coverage.
JaCoCo supports ignoring generated code if the code has annotations named `@Generated` with `RetentionPolicy.CLASS` or `RUNTIME`.

Unfortunately, `javax.annotation.processing.Generated` (and also `javax.annotation.Generated` for that matter) has just  `RetentionPolicy.SOURCE` and thus cannot be seen by JaCoCo (or any other class-file based analyzer for that matter).
Configuration for ignoring QueryDSL Q-classes is non-standard, tedious and error prone since the only other option is filename-patterns.

So I'd like to use some of the other existing `@Generated` annotations or of one of our own.

## How the new feature should work
Implement a parameter for the source generator (and (e.g.) maven-plugin) that receives a fully qualified name to an annotation class.
If this parameter is not set, the generator could fallback to current behavior.

For a more generic option: allow for a source code template that might also allow filling in fields of the annotation.
Example: 
`generated-template=javax.annotation.processing.Generated(value="{{queryDSL.generatorClass}}", date="{{queryDSL.timestamp}}", comments="Version: {{queryDSL.version}}")`

**Comment by F43nd1r** [comment]
This feature already exists via annotation processor parameter. Quoting from the documentation:

generatedAnnotationClass | The fully qualified class name of the Single-Element Annotation (with String element) to be added on the generated sources. Build in `com.querydsl.core.annotations.Generated` has CLASS retention which can be used for byte code analysis tools like Jacoco. (default: `javax.annotation.Generated` or `javax.annotation.processing.Generated` depending on the java version).
-- | --
