### ISSUE TITLE
[Feature Request] Hibernate 6 support

### ISSUE THREAD

**Issue by kdebski85** [querydsl/querydsl#3233]
Please add Hibernate 6 support.
You can read about this release here: https://in.relation.to/2022/03/31/orm-60-final/

Hibernate 6 moved from javax dependencies to Jakarta.

**Comment by jherkel** [comment]
Also hibernate 5.6.x moved from javax to jakarta namespace

**Comment by ullenboom** [comment]
As a side note, this is also an open issue for the Spring Data JPA team: https://github.com/spring-projects/spring-data-jpa/issues/2423

**Comment by odrotbohm** [comment]
> Also hibernate 5.6.x moved from javax to jakarta namespace

There's already support for this in `querydsl-jpa` with the classifier `jakarta`.

**Comment by IceBlizz6** [comment]
@odrotbohm It's great to hear that support for this already exists.
Would you be able to expand on your reply?

I don't understand how to configure querydsl to use jakarta.
your explanation is a bit too short to lead me to where i should be reading to figure it out.

**Comment by UkonnRa** [comment]
> > Also hibernate 5.6.x moved from javax to jakarta namespace
> 
> There's already support for this in `querydsl-jpa` with the classifier `jakarta`.

Is `jarkata.persistance.*` supported? Since I tryed on Spring boot 3.0 and errors thrown:

![image](https://user-images.githubusercontent.com/16066720/180635437-b92d4bfd-efd0-459c-8783-edfed0131866.png)
![image](https://user-images.githubusercontent.com/16066720/180635460-a3702566-db62-4651-828a-9abe2d03a36e.png)

**Comment by odrotbohm** [comment]
As already indicated in the comment you quoted, you need to use the `jakarta` qualifier for Querydsl dependencies to get the ones that use `jakarta.…` packages, which are required for use with Spring Boot 3.

**Comment by UkonnRa** [comment]
> As already indicated in the comment you quoted, you need to use the `jakarta` qualifier for Querydsl dependencies to get the ones that use `jakarta.…` packages, which are required for use with Spring Boot 3.

Thanks!! the `jakarta` qualifier is the right answer.

The `dependencies` should be:

```
  implementation("org.springframework.boot:spring-boot-starter-data-jpa") // Spring boot 3.0.0-M4
  implementation("com.querydsl:querydsl-jpa:5.0.0")
  annotationProcessor("com.querydsl:querydsl-apt:5.0.0:jakarta") // the `jakarta` qualifier
  annotationProcessor("jakarta.persistence:jakarta.persistence-api:3.1.0") // `jakarta` annotations should be included
```

**Comment by oldshensheep** [comment]
> **But I cannot find anything related in doc**. In fact, I don't even know the possible values about the qualifier. Could you please give me the path about the qualifier related part?

Ten years later. It finally worked....

**Comment by rootshk** [comment]
> > 正如您引用的评论中已经指出的那样，您需要使用`jakarta`Querydsl 依赖项的限定符来获取使用`jakarta.…`包的依赖项，这些包是与 Spring Boot 3 一起使用所必需的。
> 
> 谢谢！！限定符是`jakarta`正确答案。
> 
> `dependencies`应该是：
> 
> ```
>   implementation("org.springframework.boot:spring-boot-starter-data-jpa") // Spring boot 3.0.0-M4
>   implementation("com.querydsl:querydsl-jpa:5.0.0")
>   annotationProcessor("com.querydsl:querydsl-apt:5.0.0:jakarta") // the `jakarta` qualifier
>   annotationProcessor("jakarta.persistence:jakarta.persistence-api:3.1.0") // `jakarta` annotations should be included
> ```
> 
> **但我在 doc 中找不到任何相关内容**。事实上，我什至不知道有关限定符的可能值。你能给我关于限定符相关部分的路径吗？

How to configure in maven

**Comment by PatrickGotthard** [comment]
Hibernate 6 is already supported via the jakarta-specific Packages. For a complete Maven migration have a look at https://github.com/querydsl/querydsl/issues/3436#issuecomment-1328637362

**Comment by klu2** [comment]
The problem I see that even if applying `annotationProcessor("com.querydsl:querydsl-apt:5.0.0:jakarta")`, I still have the `com.querydsl.jpa.impl.JPAQueryFactory` inside `com.querydsl:querydsl-jpa:5.0.0` which only accepts a `javax.persistence.EntityManager` (and that does not exist anymore with Hibernate 6 and Spring Boot 3

**Comment by PatrickGotthard** [comment]
@klu you have to add the jakarta qualifier also to the querydsl-jpa dependency

**Comment by klu2** [comment]
ah, that works, thanks

**Comment by nobel6018** [comment]
It works for me too.
Thanks a lot.

I write kotlin spring boot gradle configuration for other developers.
This is how I change.

from:
```
implementation("com.querydsl:querydsl-jpa:5.0.0")
kapt("com.querydsl:querydsl-apt:5.0.0:jpa")
```


to: 
```
implementation("com.querydsl:querydsl-jpa:5.0.0:jakarta")
kapt("com.querydsl:querydsl-apt:5.0.0:jakarta")
```

**Comment by imtiazShakil** [comment]
> How to configure in maven

```xml
    <dependency>
      <groupId>com.querydsl</groupId>
      <artifactId>querydsl-apt</artifactId>
      <scope>provided</scope>
      <classifier>jakarta</classifier>
      <version>${querydsl.version}</version> <!-- you've to fix version to 5.0.0 or it won't work -->
    </dependency>

    <dependency>
      <groupId>com.querydsl</groupId>
      <artifactId>querydsl-jpa</artifactId>
      <classifier>jakarta</classifier>
      <version>${querydsl.version}</version>
    </dependency>
```

**Comment by lifaxin** [comment]
Great! it works!

**Comment by tfactor2** [comment]
Could the ticket be closed then?

**Comment by cnlinjie** [comment]
Great!  thanks!

**Comment by velo** [comment]
Hi,

I have forked this project and we just released a released a milestone to maven central that is compatible with **hibernate 6**.
https://repo1.maven.org/maven2/io/github/openfeign/querydsl/querydsl-core/6.0.0.M1/

If you can, please try `6.0.0.M1` and let us know how it goes.


Also note the artifact GAV changed:

```
    <dependency>
      <groupId>io.github.openfeign.querydsl</groupId>
      <artifactId>querydsl-jpa</artifactId>
      <version>6.0.0.M1</version>
    </dependency>
```
