### ISSUE TITLE
fetchResults deprecation doesn't suggest what to do for simple cases

### ISSUE THREAD

**Issue by pglizniewicz** [querydsl/querydsl#3251]
I have several usages of `fetchResults` in the code I'm working with. All of these are simple queries (no aggregates, no group bys) with limit and offset set, and I need the count. What am I expected to migrate these `fetchResults` calls to? The only suggestion the Javadoc gives is adding Blaze Persistence for queries, that break `fetchResults`, but there is no hint what to migrate to for simple queries, that work well with the current implementation. Adding Blaze Persistence for these cases seems like an overkill.

**Comment by jwgmeligmeyling** [comment]
See the discussion at https://github.com/querydsl/querydsl/discussions/3206
