### ISSUE TITLE
[querydsl-sql] Performance issues with large number of parameters

### ISSUE THREAD

**Issue by balazs-zsoldos** [querydsl/querydsl#3256]
## Observed vs. expected behavior

With the number of parameters, the time effort of generating the SQL statement grows a lot.

## Steps to reproduce

    sqlQueryFactory.select(x.y).from(x).where(x.y.in(largeArray)).fetch();

In case the _largeArray_ attribute contains e.g.: 400.000 elements, creating the query takes a minute.

## Environment

Any environment.

Querydsl version: 5.0.0

Querydsl module: querydsl-sql

Database: Any database

JDK: Any JDK

## Additional details

The reason is that the _objects_ parameter of _AbstractSQLQuery.setParameters(...)_ function is a LinkedList. However, _objects.get(i)_ is called that is expensive for a LinkedList, especially if the value of _i_ is high.

Either the LinkedList should be changed to an ArrayList, or instead of an indexed for loop, an iterator should be used and the _i_ variable should be a separate variable that is incremented manually.

Please note that _constantPaths_ parameter is also a LinkedList.

About the performance penalty of LinkedList.get(i). As it has to iterate always from the beginning, iterating through a list with 10.000 elements in this way costs 10.001 * 5000 = 50.005.000 iterations. With 400.000 elements it is 80billion iterations.

**Comment by jwgmeligmeyling** [comment]
I believe we have seen a performance improvement for this, but it unfortunately caused regressions and had to be reverted. There was no shown interest since in fixing the issue, but we're accepting PR's.
