### ISSUE TITLE
The apt plugin generates invalid code for child entities (if the base class has a Geometry type field) when using querydsl-spatial

### ISSUE THREAD

**Issue by appserzh** [querydsl/querydsl#3294]
## Observed vs. expected behavior

In the presence of Geometry type field in parent class apt generates the correct code for the child classes.

Observed:
```java
public final com.querydsl.spatial.locationtech.jts.JTSGeometryPath baseGeometry = new com.querydsl.spatial.locationtech.jts.JTSGeometryPath(_super.baseGeometry);
```

Expected something like:
```java
public final com.querydsl.spatial.locationtech.jts.JTSGeometryPath baseGeometry = _super.baseGeometry;
```
Or an additional constructor is needed for `JTSGeometryPath` class.

## Steps to reproduce

I upload sample project here https://github.com/appserzh/querydsl-spatial-apt-inheritance-issue

```java
@MappedSuperclass
public class BaseEntity {
    protected Geometry baseGeometry;
}

@Entity
public class SampleEntity extends BaseEntity{

    private Geometry sampleGeometry;
}
```

## Environment

Querydsl version: 5.0.0

Querydsl module: querydsl-spatial

Database: not applicable

JDK: 11

## Additional details

I didn't understand too much about querydsl, but it seems to me it is necessary to add a constructor to `com.querydsl.spatial.locationtech.jts.JTSGeometryPath` like:
```java
    public JTSGeometryPath(JTSGeometryPath jtsGeometryPath) {
        this(jtsGeometryPath.getMetadata());
    }
```

**Comment by dengyumin** [comment]
I have a similar problem
