### ISSUE TITLE
adding CreateTableClause support 

### ISSUE THREAD

**Issue by ismailsimsek** [querydsl/querydsl#3295]
is it possible to add/continue  `CreateTableClause` ddl support? i can see it in commit history but its missing in master branch. adding it as is could be good start.

https://github.com/querydsl/querydsl/blob/514605b3adff48f3d1cf0d10434d43f80c88d7ce/querydsl-sql/src/main/java/com/mysema/query/sql/ddl/CreateTableClause.java

 i could help working on it adding further improvements.

**Comment by jwgmeligmeyling** [comment]
Not sure why it got removed. We would accept PR's reintroducing it.

**Comment by ismailsimsek** [comment]
@jwgmeligmeyling https://github.com/querydsl/querydsl/pull/3419 is ready any chance to merge it before next release?
