### ISSUE TITLE
Spatial  generation from sql creates incorrect import path

### ISSUE THREAD

**Issue by randompasi** [querydsl/querydsl#3298]
## Observed vs. expected behavior

    Describe the issue you are experiencing:
Generating class from sql table that has geometry data type will create incorrect import path on generated class.
Incorrect path on generated class:
```java
import com.querydsl.spatial.jts.path.*;
import com.querydsl.spatial.path.*;
```

looking code querydsl code I think it should be:
```java
import com.querydsl.spatial.*;
import com.querydsl.spatial.*;
```

## Steps to reproduce

Have postgre database with sql table that has Geometry data type
Generate class from that table.

Pom:
```pom
</dependency>
        <dependency>
            <groupId>com.querydsl</groupId>
            <artifactId>querydsl-sql</artifactId>
  <version>5.0.0</version>
        </dependency>
        <dependency>
            <groupId>com.querydsl</groupId>
            <artifactId>querydsl-sql-spring</artifactId>
  <version>5.0.0</version>
        </dependency>
        <dependency>
            <groupId>com.querydsl</groupId>
            <artifactId>querydsl-sql-spatial</artifactId>
          <version>5.0.0</version>
        </dependency>
        <dependency>
     <plugin>
                <groupId>com.querydsl</groupId>
                <artifactId>querydsl-maven-plugin</artifactId>
              <version>5.0.0</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>export</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <jdbcDriver>org.postgresql.Driver</jdbcDriver>
                    <jdbcUrl>${database.uri}</jdbcUrl>
                    <jdbcUser>${database.user}</jdbcUser>
                    <jdbcPassword>${database.password}</jdbcPassword>
                    <packageName>fi.hel.allu</packageName>
                    <targetFolder>${project.basedir}/target/generated-sources/java</targetFolder>
                    <spatial>true</spatial>
                    <schemaPattern>allu</schemaPattern>
                </configuration>
                <dependencies>
                    <dependency>
                        <groupId>org.postgresql</groupId>
                        <artifactId>postgresql</artifactId>
                        <version>${postgresql.version}</version>
                    </dependency>
                  <dependency>
                    <groupId>com.querydsl</groupId>
                    <artifactId>querydsl-sql-spatial</artifactId>
                    <version>5.0.0</version>
                  </dependency>
            </plugin>
```

## Environment

Querydsl version:
5.0.0

Querydsl module:
querydsl-sql-spatial
querydsl-maven-plugin

Database:
postgre 14.1

JDK:
1.8

**Comment by doraemonunexpected** [comment]
You can add a custom MetaDataSerializer to remove those imports.

    /**
     * export code
     */
    public static void main(String[] args) throws SQLException
    {
        MetaDataExporter exporter = new MyMetaDataExporter();
        exporter.setSerializerClass(MyMetaDataSerializer.class);
        Connection conn = ...
        exporter.export(conn.getMetaData());
    }



`
public class MyMetaDataSerializer extends MetaDataSerializer {

    @Inject
    public MyMetaDataSerializer(
            TypeMappings typeMappings,
            NamingStrategy namingStrategy,
            @Named(SQLCodegenModule.INNER_CLASSES_FOR_KEYS) boolean innerClassesForKeys,
            @Named(SQLCodegenModule.IMPORTS) Set<String> imports,
            @Named(SQLCodegenModule.COLUMN_COMPARATOR) Comparator<Property> columnComparator,
            @Named(SQLCodegenModule.ENTITYPATH_TYPE) Class<?> entityPathType,
            @Named(SQLCodegenModule.GENERATED_ANNOTATION_CLASS) Class<? extends Annotation> generatedAnnotationClass
    )
    {
        super(typeMappings,
                namingStrategy,
                innerClassesForKeys,
                Collections.emptySet(), // imports == {'com.querydsl.spatial.jts.path.*', 'com.querydsl.spatial.path.*'}
                columnComparator,
                entityPathType,
                generatedAnnotationClass
        );
    }

}
`

**Comment by rimuln** [comment]
Probably you are missing dependency. Class is located in querydsl\querydsl-sql-codegen\src\main\java\com\querydsl\sql\codegen\MetaDataSerializer.java
