### ISSUE TITLE
how to use user variable in sql 

### ISSUE THREAD

**Issue by adminSxs** [querydsl/querydsl#3299]
**Example**
i want to use queryDsl impl below sql
```sql
select @rowno := @row+1
from 
(select id, from `user`, (select @rowno := 0) b
 where xxx
) a;

```

**Comment by jwgmeligmeyling** [comment]
You can use a template expression. `Expressions.numberTemplate(Integer.class, "@rowno")` should render `@rowno` in your query. Similarly you can also do `Expressions.numberTemplate(Integer.class, "@row").add(1)`.
