### ISSUE TITLE
Add Example Gradle Project Configuration to Documentation

### ISSUE THREAD

**Issue by EarthCitizen** [querydsl/querydsl#3313]
## Description

There is a lot of confusion on how to set up QueryDSL in a Gradle project. Please add some example project configurations for Gradle, including a JPA configuration.

That I could find, there does not seem to be clear example anywhere of the correct way to set up QueryDSL for Gradle.

**Comment by vanphuoc9** [comment]
plugins {
    id 'org.springframework.boot' version '2.4.1'
    id 'io.spring.dependency-management' version '1.0.10.RELEASE'
    id 'java'
    id 'idea'
}

idea {
    module {
        sourceDirs += file('generated/')
        generatedSourceDirs += file('generated/')
    }
}

ext['tomcat.version'] = '9.0.41'

group = 'com.abc'
version = '1.0.202107091'
sourceCompatibility = '11'

configurations {
    compileOnly {
        extendsFrom annotationProcessor
    }
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'com.querydsl:querydsl-jpa:4.4.0'

    compileOnly 'org.projectlombok:lombok'
    runtimeOnly 'org.postgresql:postgresql'
    annotationProcessor("org.springframework.boot:spring-boot-starter-data-jpa:2.4.1")
    annotationProcessor 'org.projectlombok:lombok'
    annotationProcessor 'com.querydsl:querydsl-apt:4.4.0:jpa'
    testImplementation('org.springframework.boot:spring-boot-starter-test') {
        exclude group: 'org.junit.vintage', module: 'junit-vintage-engine'
    }
    testImplementation 'org.springframework.security:spring-security-test'
}

test {
    useJUnitPlatform()
}

**Comment by EarthCitizen** [comment]
@vanphuoc9 I think it is unnecessary to duplicate the `annotationProcessor` configuration, isn't it?. I use Lombok, and I have never had to do that. What is the purpose?

**Comment by rohitkrishna094** [comment]
I am getting the error `Unable to load class javax.persistence.Entity`
