### ISSUE TITLE
Jackson serialization with Spring Pagable and QSort applied

### ISSUE THREAD

**Issue by cswan-log** [querydsl/querydsl#3322]
## Observed vs. expected behavior

Getting data via a queryDSL repository with a pagable applied and a specific QSort order returns the desired result. Feeding it back to a rest controller endpoint will result in an exepection thrown by jackson because of a cyclic dependency in the sort path:

```
org.springframework.http.converter.HttpMessageConversionException: Type definition error: [simple type, class com.querydsl.core.types.Path<java.lang.Object>]; nested exception is com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Direct self-reference leading to cycle (through reference chain: org.springframework.data.domain.PageImpl["pageable"]->org.springframework.data.domain.PageRequest["sort"]->org.springframework.data.querydsl.QSort["orderSpecifiers"]->java.util.Arrays$ArrayList[0]->com.querydsl.core.types.OrderSpecifier["target"]->com.querydsl.core.types.PathImpl["metadata"]->com.querydsl.core.types.PathMetadata["parent"]->my.package.model.QMyEntity["created"]->com.querydsl.core.types.dsl.DateTimePath["root"]->com.querydsl.core.types.PathImpl["root"])
```

## Steps to reproduce

* Spring Project with QueryDSL and Jackson configured
* Create an entity and a repository with QueryDSL support
* Add a rest controller with the following code: 
```
return repository.findAll(PageRequest.of(0, 10, QSort.by(QMyEntity.created.asc())))
```

## Environment

Querydsl version: 5.0.0

Querydsl module: JPA

Database: MariaDB

JDK: 17

## Additional details

To work around this error, you can supply some custom jackson mixins to avoid the serialization of specific fields:
Kotlin Code

```kotlin
@Suppress("unused")
abstract class PathMetadataMixin {
    @JsonIgnore
    abstract fun getParent(): Path<*>?

    @JsonIgnore
    abstract fun getRootPath(): Path<*>?
}

@Suppress("unused")
abstract class PathMixin {
    @JsonIgnore
    abstract fun getRoot(): Path<*>?

    @JsonIgnore
    abstract fun getAnnotatedElement(): AnnotatedElement?
}

// ...

@Bean
@Primary
fun objectMapper(): ObjectMapper {
    // builder is injected
    return jackson2ObjectMapperBuilder.createXmlMapper(false)
        .mixIn(PathMetadata::class.java, PathMetadataMixin::class.java)
        .mixIn(Path::class.java, PathMixin::class.java)
        .build()
}
```

----

I am not quite sure if this is the correct place to report the issue - sorry, if is the wrong place!

**Comment by jwgmeligmeyling** [comment]
I think its Spring Data's responsibility to transform their Page model to a serialisable representation in their Spring Data Querydsl integration. These are Querydsl internal classes that are not designed to be returned as response models. And I don't think adding a compile time dependency on Jackson and scattering a few `@JsonIgnore` annotations around the code base is by any means a desirable solution.
