### ISSUE TITLE
querydsl create the QXX.class with error tableName or columnName

### ISSUE THREAD

**Issue by liuyunqiushui** [querydsl/querydsl#3345]
@Data
@Entity
@Table(name = "TEST_USER")
public class TestUser {
    @Id
    @GeneratedValue(generator = "idGenerator", strategy = GenerationType.AUTO)
    @GenericGenerator(name = "idGenerator", strategy = "native")
    private Long id;
    @Column(name = "name")
    private String nameaa;
    private Long age;
    private String address;
}
-- entity class
@Generated("com.querydsl.codegen.DefaultEntitySerializer")
public class QTestUser extends EntityPathBase<TestUser> {

    private static final long serialVersionUID = 1306679448L;

    public static final QTestUser testUser = new QTestUser("testUser");

    public final StringPath address = createString("address");

    public final NumberPath<Long> age = createNumber("age", Long.class);

    public final NumberPath<Long> id = createNumber("id", Long.class);

    public final StringPath nameaa = createString("nameaa");

    public QTestUser(String variable) {
        super(TestUser.class, forVariable(variable));
    }

    public QTestUser(Path<? extends TestUser> path) {
        super(path.getType(), path.getMetadata());
    }

    public QTestUser(PathMetadata metadata) {
        super(TestUser.class, metadata);
    }

}
-- QTestUser 
there are wrong tableName and columnName for field name
how this happened

**Comment by liuyunqiushui** [comment]
like this:
jpaQueryFactory.update(qTestUser)
                .set(qTestUser.nameaa, "99")
                .set(qTestUser.address, "北京")
                .set(qTestUser.age, 22L)
                .where(qTestUser.id.eq(1L))
                .execute();
result is ok
bug like this :
 Long id = jpaQueryFactory.insert(qTestUser)
                .set(qTestUser.nameaa, "99")
                .set(qTestUser.address, "北京")
                .set(qTestUser.age, 22L)
                .execute();
return 
antlr.NoViableAltException: unexpected token: testUser
the sql is this:
[insert into TestUser (nameaa, address, age)
testUser.nameaa = ?1, testUser.address = ?2, testUser.age = ?3]

**Comment by huanm** [comment]
i meet this problem too,and i'd like to fix this by rewite AbstractSQLInsertClause when adding columns and  recompile it
