### ISSUE TITLE
Expressions.booleanTemplate

### ISSUE THREAD

**Issue by tanhh326** [querydsl/querydsl#3370]
Quser q= QUser().user;
        if(?){
            where.and(Expressions.booleanTemplate("date({0}) between date({1}) and date({2})",q.createdTime,date[0],date[1]))
        }

        if(?){
            where.and(Expressions.booleanTemplate("date({0}) between date({1}) and date({2})",q.other,date[0],date[1]))
        }

Why doesn't each booleanTemplate maintain its own variable ordinal, but is shared globally, so that I get an error like the following when I have a conditional judgment, or is there an easier way to query like this?
We look forward to your answers (#^.^#)
`org.hibernate.QueryException:Unexpected gap in ordinal parameter labels [5 -＞ 7]
`

**Comment by jwgmeligmeyling** [comment]
I think that this is a duplicate of an older issue that was fixed in Querydsl 5.0.

Which queryDSL version are you using?

**Comment by tanhh326** [comment]
Thank you, my version number is lower than 5.0. 
(●'◡'●)
