### ISSUE TITLE
Q classes are not generated by AP where using jakarta.persistence.* instead of javax.persistence.*

### ISSUE THREAD

**Issue by alt3fcat** [querydsl/querydsl#3371]
When I use Annotation of jakarta.persistence.*  instead of javax.persistence.*, the Q classes are not generated by the annotation processor.

I tried using 

```          
            <plugin>
                <groupId>com.mysema.maven</groupId>
                <artifactId>apt-maven-plugin</artifactId>
                <version>1.1.3</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>process</goal>
                        </goals>
                        <configuration>
                            <processor>com.querydsl.apt.jpa.JPAAnnotationProcessor</processor>
                        </configuration>
                    </execution>
                </executions>
                <dependencies>
                    <dependency>
                        <groupId>com.querydsl</groupId>
                        <artifactId>querydsl-apt</artifactId>
                        <version>${querydsl.version}</version>
                    </dependency>
                </dependencies>
           </plugin>`

```
and 

```

           <plugin>
                <groupId>org.bsc.maven</groupId>
                <artifactId>maven-processor-plugin</artifactId>
                <version>2.2.4</version>
                <executions>
                    <execution>
                        <id>process</id>
                        <goals>
                            <goal>process</goal>
                        </goals>
                        <phase>generate-sources</phase>
                        <configuration>
                            <processors>
                                <processor>com.querydsl.apt.jpa.JPAAnnotationProcessor</processor>
                            </processors>
                        </configuration>
                    </execution>
                </executions>
                <dependencies>
                    <dependency>
                        <groupId>com.querydsl</groupId>
                        <artifactId>querydsl-apt</artifactId>
                        <version>${querydsl.version}</version>
                    </dependency>
                </dependencies>
            </plugin>
```
 
I'm using Maven 3.3 with Java15 and QueryDSL version 5.0.0

I got same results with direct maven call or using intelliJ compiler.
But, when I change jakarta imports by javax in entities, Q classes are well generated. (using 2 kind of APT)

**Comment by alt3fcat** [comment]
I'll answer by myself after lot of searching, 

To use jakarta package, I had to add  `<classifier>jakarta</classifier>` in the dependency.

like this :
```
                    <dependency>
                        <groupId>com.querydsl</groupId>
                        <artifactId>querydsl-apt</artifactId>
                        <version>${querydsl.version}</version>
                        <classifier>jakarta</classifier>
                    </dependency>
```

**Comment by lizhongyue248** [comment]
Hello, do you know how to use it in gradle kotlin DSL?

**Comment by lizhongyue248** [comment]
I found the config that work
```
implementation("com.querydsl:querydsl-jpa")
annotationProcessor(
  group = "com.querydsl", name = "querydsl-apt", classifier = "jakarta"
)
annotationProcessor("jakarta.persistence:jakarta.persistence-api")

```

**Comment by mmm8955405** [comment]
> I'll answer by myself after lot of searching,
> 
> To use jakarta package, I had to add `<classifier>jakarta</classifier>` in the dependency.
> 
> like this :
> 
> ```
>                     <dependency>
>                         <groupId>com.querydsl</groupId>
>                         <artifactId>querydsl-apt</artifactId>
>                         <version>${querydsl.version}</version>
>                         <classifier>jakarta</classifier>
>                     </dependency>
> ```

Where can I find examples about Jakarta

**Comment by rmohamed-pinc** [comment]
Hi. what is the version  of querydsl. i have used 5.0.0 Still Q classes are not generated,

**Comment by j0y0nt** [comment]
Leaving comment here, just in case some one need it.

`
<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>3.1.4</version>
		<relativePath /> 
	</parent>
	<groupId>org.j0</groupId>
	<artifactId>hello-gql</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<name>hello-gql</name>
	<description>Demo project for Spring Boot</description>
	<properties>
		<java.version>17</java.version>
		<apt-maven-plugin.version>1.1.3</apt-maven-plugin.version>
	</properties>
	<dependencies>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-graphql</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-data-jpa</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.springframework</groupId>
			<artifactId>spring-webflux</artifactId>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.springframework.graphql</groupId>
			<artifactId>spring-graphql-test</artifactId>
			<scope>test</scope>
		</dependency>
		
		<dependency>
			<groupId>com.querydsl</groupId>
			<artifactId>querydsl-jpa</artifactId>
			<version>${querydsl.version}</version>
			<classifier>jakarta</classifier>
		</dependency>
		<dependency>
			<groupId>com.querydsl</groupId>
			<artifactId>querydsl-apt</artifactId>
			<version>${querydsl.version}</version>
			<classifier>jakarta</classifier>
		</dependency>

		<dependency>
			<groupId>org.hibernate.javax.persistence</groupId>
			<artifactId>hibernate-jpa-2.1-api</artifactId>
			<version>1.0.2.Final</version>
		</dependency>

		
		<dependency>
			<groupId>jakarta.persistence</groupId>
			<artifactId>jakarta.persistence-api</artifactId>
		</dependency>
		<dependency>
			<groupId>org.postgresql</groupId>
			<artifactId>postgresql</artifactId>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-devtools</artifactId>
			<optional>true</optional>
		</dependency>
	</dependencies>

	<build>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
			</plugin>
		</plugins>
	</build>

</project>

`

**Comment by hohwille** [comment]
IMHO this is the problem:
https://github.com/querydsl/querydsl/blob/master/querydsl-codegen/src/main/java/com/querydsl/codegen/AbstractModule.java#L23
when using this:
```
<groupId>com.mysema.maven</groupId>
<artifactId>apt-maven-plugin</artifactId>
<version>1.1.3</version>
```
Adding `<classifier>jakarta</classifier>` to `com.querydsl` dependencies does not resolve the `apt-maven-plugin` problem.
Maybe that plugin shall not be used with JakartaEE and instead apt via standard maven-compiler-plugin. If so it would be worth to state explicitly.

**Comment by hohwille** [comment]
Ah, now I got the real problem:
Your classifier approach does not work so well:
There is always just one POM in maven per GAV. So if you are using a classifier this is not affecting any of the dependencies.
Hence, you need to exclude all dependencies manually in your POM and manually add them all with the classifier `jakarta` as well:
https://repo1.maven.org/maven2/com/querydsl/querydsl-apt/5.0.0/querydsl-apt-5.0.0.pom
Citation:
```
<dependency>
<groupId>com.querydsl</groupId>
<artifactId>querydsl-codegen</artifactId>
<version>${project.version}</version>
<exclusions>
<exclusion>
<groupId>cglib</groupId>
<artifactId>cglib</artifactId>
</exclusion>
</exclusions>
</dependency>
```
No classifier here, hence using the "wrong" `querydsl-codegen` dependency.

**Comment by hohwille** [comment]
There is no `querydsl-codegen` with classifier `jakarta`:
https://repo1.maven.org/maven2/com/querydsl/querydsl-codegen/5.0.0/
So IMHO the problem cannot be resolved and the issue should be reopened.
You have coded `javax.inject` [here](https://github.com/querydsl/querydsl/blob/master/querydsl-codegen/src/main/java/com/querydsl/codegen/AbstractModule.java#L23) and provide no alternative for `jakarta.inject`.

**Comment by hohwille** [comment]
So the conclusion is not that you cannot make your code compile but that you cannot use querydsl code-generation without having `javax.inject` dependency as well so this is polluting the namespace and `jakarta` users get trouble with content-assist (auto-completion) as you always get both JEE and JakartaEE.

**Comment by youyinnn** [comment]
Just confirmed what @j0y0nt said. You can use just the following:
``` XML
<dependency>
    <groupId>com.querydsl</groupId>
    <artifactId>querydsl-apt</artifactId>
    <version>${querydsl.version}</version>
    <scope>provided</scope>
    <classifier>jakarta</classifier>
</dependency>

<dependency>
    <groupId>com.querydsl</groupId>
    <artifactId>querydsl-jpa</artifactId>
    <version>${querydsl.version}</version>
    <classifier>jakarta</classifier>
</dependency>
```

No `apt-maven-plugin` is needed, at least for IDEA users.

**Comment by saviobosco** [comment]
Use this to generate the Q classes and change the generated classes' destination.    By default, it is placed in target/generated-sources/annotations/**

` spring boot version: 3.2.7`

```
<properties>
		<java.version>17</java.version>
		<querydsl.generated.sources>target/generated-sources/java</querydsl.generated.sources>
</properties>

<dependencies>
	<dependency>
		<groupId>com.querydsl</groupId>
		<artifactId>querydsl-jpa</artifact>
		<version>${querydsl.version}</version>
		<classifier>jakarta</classifier>
	</dependency>
</dependencies>

<build>
	<plugins>
		<plugin>
			<groupId>org.apache.maven.plugins</groupId>
			<artifactId>maven-compiler-plugin</artifactId>
			<configuration>
				<source>${java.version}</source>
				<target>${java.version}</target>
				<annotationProcessorPaths>
					<path>
						<groupId>org.projectlombok</groupId>
						<artifactId>lombok</artifactId>
						<version>${lombok.version}</version>
					</path>
					<path>
						<groupId>com.querydsl</groupId>
						<artifactId>querydsl-apt</artifactId>
						<version>${querydsl.version}</version>
						<classifier>jakarta</classifier>
					</path>
					<path>
						<groupId>jakarta.persistence</groupId>
						<artifactId>jakarta.persistence-api</artifactId>
						<version>3.1.0</version>
					</path>
				</annotationProcessorPaths>
                                <!-- change the querydsl output -->
                                 <compilerArgs>
						<arg>-Aquerydsl.entityAccessors=true</arg>
						<arg>-Aquerydsl.createDefaultVariable=true</arg>
						<arg>-s</arg>
						<arg>${querydsl.generated.sources}</arg>
			        </compilerArgs>
			</configuration>
		</plugin>
	<plugins>
<build>
```

**Comment by ankit111998sharma** [comment]
Hello Team,

After removing the **@mjeffrey** suggested plugin, I encountered the following error: **Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.13.0:compile (default-compile) on project demoSpringProject: Fatal error compiling: Cannot load from object array because "this.hashes" is null.**

**My project configuration includes:**

**- Spring Boot 3.3.2**
**- Java 17**
**- Querydsl**
**- Liquibase **

Any insights on resolving this issue would be greatly appreciated.
