### ISSUE TITLE
Case on BooleanExpression seems to wrongly serialize to JPQL

### ISSUE THREAD

**Issue by c0stra** [querydsl/querydsl#3391]
## Observed vs. expected behavior

I'm using a case structure to convert BooleanExpression to NumberExpression in order to be able e.g. to aggregate (sum) records matching my criteria.

I use following querydsl code:
```
return queryFactory.selectFrom(rootEntity).select(Projections.list(rootEntity.size.gt(1).when(true).then(1).otherwise(0))).fetch();
```
The part:
```
rootEntity.size.gt(1)
```
is my BooleanExpression, I'm trying to map to numbers - 1 for true, 0 for false. That's the part:
```
.when(true).then(1).otherwise(0)
```

When executing the code above, I get following QuerySyntaxError:
```
org.hibernate.hql.internal.ast.QuerySyntaxException: unexpected AST node: > near line 1, column 39 [select sum(case when (rootEntity.size > ?1) = ?2 then ?3 else 0 end)
from foundation.jpa.querydsl.test.schema.RootEntity rootEntity]
```

The whole `case ... when ... otherwise` structure looks strange there. Case has no parameter, and `when` part contains complex boolean expression built from my original expression being equal to `true`.
But the HQL parser cannot parse it (I'm using H2 db, if that can make any difference).

## Steps to reproduce

As I suspect the `case` on `BooleanExpression`, I tried even without the `sum()`, and get into the same parse error. So minimal steps to reproduce are to run following code:
```
queryFactory.selectFrom(rootEntity).select(Projections.list(QRootEntity.rootEntity.size.gt(1).when(true).then(1).otherwise(0))).fetch();
```
given RootEntity having numeric size property.

## Environment

I observe this on querydsl-jpa 5.0.0

Querydsl version: 5.0.0

Querydsl module: querydsl-jpa

Database: H2

JDK: 
/usr/lib/jvm/java-8-oracle/bin/java -version
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)

## Additional details

When debugging the JPAQuery internal representation, the projection.toString() results in better form: case size > 1 when true then 1 otherwise 0.

**Comment by jwgmeligmeyling** [comment]
Querydsl JPA by default uses parameters for constants. Literal rendering needs to be used explicitly through `Expressions.literal` (or through `TemplateExpressions`).
