### ISSUE TITLE
OperationImpl::equals ignoring commutative property of operators

### ISSUE THREAD

**Issue by matheus-mr** [querydsl/querydsl#3395]
## Observed vs. expected behavior

[OperationImpl::equals](https://github.com/querydsl/querydsl/blob/master/querydsl-core/src/main/java/com/querydsl/core/types/OperationImpl.java#L73) method checks if the args of both operations are the same using the ArrayList equals implementation which validates if both lists have the same size and contains the same elements in the same order.

The problem is that a lot of operations are [commutative](https://en.wikipedia.org/wiki/Commutative_property) which makes the order irrelevant. 

I was having this problem when trying to cache requests using querydsl web support. Two different requests which produces the same results were not being cached because the Predicate objects were not equals.

## Steps to reproduce

Using querydsl web support to instantiate a Predicate, make two requests which produces the same results and assert that predicate1.equals(predicate2) == false. For example:
/persons?age=42&height=180
/persons?height=180&age=42

## Environment

Querydsl version: 5.0.0

Querydsl module: com.querydsl.core

## Additional details

Looking at the code, it seems to me that the com.querydsl.core.types.Operator interface could add a new method `boolean isCommutative()` so that this can be used in the OperationImpl::equals method to check if the args list are the same ignoring the order when the operator is commutative.

**Comment by jwgmeligmeyling** [comment]
Come on, this is not a bug. Relying on a stricter equality contract makes perfect sense here.

Feel free to provide a PR for `isCommutative`.
