### ISSUE TITLE
When query dsl uses inheritance, the base class from other modules will not be able to generate Q classes

### ISSUE THREAD

**Issue by Yangyy99** [querydsl/querydsl#3396]
## Steps to reproduce

not be able to generate Q classes

## Environment

When query dsl uses inheritance, the base class from other modules will not be able to generate Q classes

Querydsl version: 5.0.0

Querydsl module: jpa

Database: any 

JDK: 17 

## Additional details
eg :  

Student extends BaseDB

but : Person and Student are in different modules 

At this time: 
error :  Symbol cannot be found
 public final base.QBaseDB _super = new base.QBaseDB(this);

**Comment by Yangyy99** [comment]
sorry   , Student and BaseDB  are in different modules

**Comment by yeyunce2023ok** [comment]
I have encountered the same problem. How can I solve it? thank you

**Comment by rush-3** [comment]
Hello, how did you solve it?

**Comment by rush-3** [comment]
> 我也遇到过同样的问题。我该如何解决？谢谢

Hello, have you solved this problem?
