### ISSUE TITLE
method 【limit()】 is invalid

### ISSUE THREAD

**Issue by wsq93** [querydsl/querydsl#3418]
## Observed vs. expected behavior

![图片](https://user-images.githubusercontent.com/44887680/198469946-adc8ecc3-1a0b-40c5-a589-7802f973f507.png)

## Steps to reproduce

---
import com.querydsl.jpa.impl.JPAQueryFactory;

	@Autowired
	private JPAQueryFactory queryFactory;

---

## Environment

Querydsl version: 5.0.0

Database:PostgreSQL

JDK:17

**Comment by jwgmeligmeyling** [comment]
Limit isn't invalid, the toString() is. The actual handling of the limit clause is not done during query serialisation but at the very end, to support pagination etc.

Weird design choice, but it is what it is.

In the eventual query it is rendered - look at the generated SQL. There is a known issue w.r.t. limit clauses in subqueries, for which I am still not sure if Querydsl or the JPA spec is to blame, but using Blaze-Persistence querydsl integration we'll get you past that limitation as well.

**Comment by wsq93** [comment]
Thanks!
I solved the problem by using a variable to transfer and receive.
