### ISSUE TITLE
JPASQLQuery uses java.sql.Date instead of java.time.LocalDate

### ISSUE THREAD

**Issue by naihil** [querydsl/querydsl#3425]
I have a simple entity with LocalDate createdAt field, simple select query throws an exception java.lang.IllegalArgumentException: argument type mismatch:
`
		final JPASQLQuery<TestEntityDto> query = new JPASQLQuery<>(this.db.getEntityManager(), configuration)
				.select(Projections.bean(TestEntityDto.class,
						qTestEntity.id,
						qTestEntity.title,
						qTestEntity.createdAt))
				.from(qTestEntity);

		final List<TestEntityDto> rows = query.fetch();
`
You can see full info here [StackOverflow](https://stackoverflow.com/questions/74419551/querydsls-jpasqlquery-uses-java-sql-date-instead-of-java-time-localdate)
JDK 1.8, QueryDSL 5.0.0, Hibernate 5.6.9

**Comment by jwgmeligmeyling** [comment]
I don't think `JPASQLQuery` was ever updated for the new JSR timestamp types. But I generally discourage the use of `JPASQLQuery` anyway.

**Comment by naihil** [comment]
@jwgmeligmeyling why do you discourage the use of JPASQLQuery? 
There are some JSR310 classes in com.querydsl.sql.types package => there should be some support i think...

**Comment by jwgmeligmeyling** [comment]
You should be able to get anything you need done with JPQL in a much more reliable way.

**Comment by naihil** [comment]
Got it. Thanks for reply!
