### ISSUE TITLE
HibernateQuery does not utilize the hibernate session properly

### ISSUE THREAD

**Issue by eocak** [querydsl/querydsl#3433]
## Observed vs. expected behavior

I want the query to call SessionFactoryOptionsBuilder#LiteralHandlingMode.interpret method from Hibernate session, whenever the query is fetched. But it is not called and  so **hibernate.criteria.literal_handling_mode=inline** property becomes ineffective. 
It is called when directly creating JPQL without querydsl but not with querydsl's HibernateQuery.

## Steps to reproduce

I initialize HibernateQuery as below: 
HibernateQuery<FlexQueryPictureDTO> query = new HibernateQuery<>(reportEntityManager.unwrap(Session.class));

Any call with this should be ok for reproducing issue. 

## Environment

SpringBoot: 2.6.2
Hibernate: 5.6.3  
Querydsl version: 5.0.0
Querydsl module: 
Database: Oracle
JDK: 17

## Additional details
Root cause:

Hibernate fails when creating groupBy statement with literals in it. For example, below statement returns ORA-00979 error even though the expression in groupBy is also in select statement. I think Hibernate creates new bind parameter for every literal (40, in this example). Because of this issue with Hibernate, I have decided to use inline parameters for literals.
 (ttvehdeflo4_.LOCX-mod(ttvehdeflo4_.LOCX,
        40))/40 as col_1_0_

I asked a question about this on stackoverflow [Link](https://stackoverflow.com/questions/74548270/hibernate-binding-problem-causes-ora-00979-not-a-group-by-expression)

[Hibernate bug link](https://hibernate.atlassian.net/browse/HHH-14726?jql=text%20~%20%22ORA-00979%22%20order%20by%20created%20DESC)

**Comment by alexeev** [comment]
@eocak, would you mind closing this issue, since this bug is not related to querydsl?
