### ISSUE TITLE
How to use kotlin custom getter in Qfile?

### ISSUE THREAD

**Issue by bingbingpa** [querydsl/querydsl#3446]
## Why the new feature should be added

Jpa Entitiy has many custom getter.
this property is not database column.
therefore i have to write same code in Jpa Entity and Qfile.

jpa entity
~~~kotlin
@Entity
class BillMaster(
    val priceA: Long,
    val priceB: Long
) {
    val totalPrice
        get() = priceA + priceB
}
~~~
queryDsl Qfile
~~~kotlin
val QBillMaster.totalPrice: NumberExpression<Long>
        get() =
            this.priceA
                .add(this.priceB)
~~~

**How can I merge duplicate code in entity and qfile?**

**Comment by debop** [comment]
Add `@Transient` to entity getter property

```
@Entity
class BillMaster(
    val priceA: Long,
    val priceB: Long
) {
   @get:javax.persistence.Transient
    val totalPrice
        get() = priceA + priceB
}
```

**Comment by debop** [comment]
Try extension methods for QBillMaster class

```
    private val qBillMaster = QBillMaster.billMaster

    private val QBillMaster.totalPrice: NumberExpression<Long>
        get() = this.priceA.add(this.priceB)
```

**Comment by bingbingpa** [comment]
@debop 
Thanks for your comments.
However, I want like this.
totalPrice property of entity and qfile is perform the same function.
totalPrice of eneity cannot be reused in Qfile and must be defined as an extended property again.
Can't we just reuse entity's custom getter in qfile?

**Comment by debop** [comment]
@bingbingpa 
그 방법은 없습니다. 보통 Entity의 속성으로 calculated column 을 대체하는 방식이 우선이고, QUERY 용 Expression 은 따로 만들 수 밖에 없는 것 같네요.

**Comment by bingbingpa** [comment]
@debop 그렇군요. 이렇게 답변해주셔서 감사합니다. 
이 pr 은 닫도록 하겠습니다.
