### ISSUE TITLE
How to use JSON_CONTAINS in jpa?

### ISSUE THREAD

**Issue by ddxl123** [querydsl/querydsl#3471]
I can't find methods in both stackhoverflow and issue.

**Comment by tanhh326** [comment]
`Expressions.booleanTemplate("JSON_CONTAINS(columns,'" + id + "') = 1")`

**Comment by ddxl123** [comment]
> `Expressions.booleanTemplate("JSON_CONTAINS(columns,'" + id + "') = 1")`

Can you write the specific parameters in JSON_CONTAINS in detail? thank you!

For example,
```
row1 ["cat","dog","bird"]
row2 ["horse","dog","bird"]
row3 ["honeybee","cat"]
...
```
I want to query whether cat exists in the categories field in the animal table.What should I do?

**Comment by ddxl123** [comment]
It has been solved and needs to be written as follows:
```
"""JSON_CONTAINS('categorys','"cat"') = 1"""
```

**Comment by ddxl123** [comment]
> `Expressions.booleanTemplate("JSON_CONTAINS(columns,'" + id + "') = 1")`

Can you tell me the meaning of "=1"? Thanks.

**Comment by tanhh326** [comment]
@ddxl123 `= true`
