### ISSUE TITLE
QueryDsl core should support column annotation or similar kind in Entity class 

### ISSUE THREAD

**Issue by dshivaji** [querydsl/querydsl#3473]
## Why the new feature should be added

To map the entity java field to column name for query serializer

## How the new feature should work

Example
`@Entity
public class Person {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(name = "first_name")
    private String firstname;    
}`

Generated class should have property like this

`@Generated("com.querydsl.codegen.EntitySerializer")
public class QPerson extends EntityPathBase<Person> {

    private static final long serialVersionUID = -809632337L;

    public static final QPerson person = new QPerson("person");   

    public final StringPath firstname = createString("first_name");
    

    public QPerson(String variable) {
        super(Person.class, forVariable(variable));
    }

    public QPerson(Path<? extends Person> path) {
        super(path.getType(), path.getMetadata());
    }

    public QPerson(PathMetadata metadata) {
        super(Person.class, metadata);
    }

}`

**Comment by jwgmeligmeyling** [comment]
Columns names cannot be used in JPQL queries, it uses attribute names.

The attribute to column name translation is done in the Serializer for JPASQLQuery but in regular JPA queries you dont deal with column names anyway.
