### ISSUE TITLE
Support for Hibernate Reactive

### ISSUE THREAD

**Issue by milgner** [querydsl/querydsl#3488]
## Why the new feature should be added

QueryDSL is still the best way to build type-safe queries without awkward string manipulation. When looking to integrate it into a project based on Hibernate Reactive, I found that using the JPA 1.0 `EntityManager.createQuery` method will create query objects that are incompatible with the reactive API.

In `com.querydsl.jpa.impl.AbstractJPAQuery.getResultList(AbstractJPAQuery.java:191)` it will ultimately throw 
```
java.lang.UnsupportedOperationException: Use performReactiveList instead
```

## How the new feature should work

Ideally an equivalent to `JPAQuery` exists which uses reactive APIs to access the data. Instead of `EntityManager`, it would use a `Stage.Session` (or use a passed-in `Stage.SessionFactory` to create one) to call `.createQuery` on and work with the reactive API instead.

From what I saw of the code so far, I imagine it would be quite straightforward to implement as the JPA functionality being used has a direct equivalent in the reactive API. The only change is when the actual database access happens, so most of the work will be to create a concept for how to avoid duplicating all the code in between.

I'd be even willing to give it a shot if you'd be interested in having that feature and merging the code; but for me it would be a difference in how to implement it: building it as a standalone extension project just to scratch my itch, I'd use Kotlin and `kotlinx.coroutines` (for a clean implementation using `suspend` functions) - but if the goal were to make it a new feature of this library, I'd probably use Java to avoid additional dependencies and cognitive complexity from having two languages.

**Comment by encircled** [comment]
@milgner https://github.com/encircled/Joiner is an extension library for querydsl which provides support for project reactor and kotlin coroutines, using hibernate reactive framework. Hibernate orm 6 support is WIP as there are a few incompatibilities with querydsl

**Comment by milgner** [comment]
> @milgner https://github.com/encircled/Joiner is an extension library for querydsl which provides support for project reactor and kotlin coroutines, using hibernate reactive framework. Hibernate orm 6 support is WIP as there are a few incompatibilities with querydsl

That looks very promising! Thanks for pointing it out! I'll close this issue then.
