### ISSUE TITLE
querydsl's namingStrategy  is different hibernate's namingStrategy

### ISSUE THREAD

**Issue by minesunny** [querydsl/querydsl#3490]
the column named userId in the User Entity;it generated by hiberate and named user_id in table user; why querydsl genreate the column'name as userId;

**Comment by fireplace009** [comment]
We have the same issue. Version 5 has this issue, We reverted to 4.2.1 to be able to continue.

**Comment by progreon** [comment]
Update on the above: version 4.2.1 has the same issue when compiling our project with java17, but not with java8

**Comment by fireplace009** [comment]
Hey @minesunny , were you able to find a solution for this issue?

**Comment by minesunny** [comment]
> Hey @minesunny , were you able to find a solution for this issue?
I tired to rewirte class com.querydsl.codegen.GenericExporter to handle this issue,but my code is not exist ,I can write it again ,if you need it. if you want use it with plugin,I suggest that you can write a main class to invoke  the new GenericExporter which you rewrite, and using exec-maven-plugin to exec the main class;that is my solution

**Comment by fireplace009** [comment]
ah, ok, great.
No need to write again. 
I will jump in myself and probably end up with the same kind of solution.
Thank you for the feedback.
