### ISSUE TITLE
Querying collections with entities, output in POJO

### ISSUE THREAD

**Issue by dvkuenssberg** [querydsl/querydsl#3491]
## Description
I could not find any documentation for the following problem.

Hello,

I am currently facing an issue when dealing with Projections and collections of objects. I have an Entity and a regular POJO and would like to fetch data from the database and get the POJO as a result. Example scenario:

```java
@Entity
public class House {
	private String houseId;
}

@Entity
public class Room {
	private Long roomId;
	private House house;
	private Set<Thing> things;
}

@Entity
public class Thing {
	private String name;
}

public class RoomInHouse {
	private Long roomId;
	private String houseId;
	private Set<Thing> things;
}
```

My query initially looked like this:

```java
final var pageable = PageRequest.of(getPageNumber(requestParams), getPageSize(requestParams)); // stuff for pagination
QHouse house = new QHouse("house");
QRoom room = new QRoom("room");
QThing thing = new QThing("thing");
final JPAQueryFactory = new JPAQueryFactory(entityManager);
final JPAQuery<RoomInHouse> query = queryFactory.select(
		Projections.constructor(
			RoomInHouse.class,
			room.roomId,
			house.houseId,
			room.things
		)
	)
	.from(room)
	.leftJoin(room.house, house)
	.leftJoin(room.things, thing)
	.groupBy(room.roomId, house.houseId, thing.name);
final List<RoomInHouse> rooms = querydsl.applyPagination(pageable, query).fetch();
```

However, it seems I cannot directly query the collection without some extra steps. I found [this](https://stackoverflow.com/questions/60833916/querydsl-projection-elementcollection) where somebody had a similar problem and used `transform` to solve it but I got a type error when trying to use the `GroupBy.set()` or `Expressions.set()` method.

As a workaround, I created a second query where I query the entity directly (without any projections so there I can get the collection) and then compare the two query results and add the collections to the POJOs manually. Doing it like this makes other things like sorting quite difficult.

How can I query collections like this and put it into a POJO directly?

Thanks!

**Comment by dvkuenssberg** [comment]
Thank you for the quick reply! However when using this code, I receive a `Map<List<?>, RoomInHouse>` instead of a `List<RoomInHouse>`. I removed the `.groupBy(...)` part from the `query` and replaced `fetch` with your code since `transform` also fetches the query directly. I tried it with `GroupBy.list()` and `Expressions.list()` but it yields the same result.

Did I make a mistake somewhere?

**Comment by tanhh326** [comment]
⚡️
```java
List<RoomInHouse> result = new JPAQuery<>(entityManager)
    .select(Projections.constructor(RoomInHouse.class, room.roomId, house.houseId, room.things))
    .from(room)
    .join(room.house, house)
    .fetchJoin()
    .leftJoin(room.things, thing)
    .transform(GroupBy.groupBy(room.roomId, house.houseId)
        .as(Projections.constructor(RoomInHouse.class, room.roomId, house.houseId, GroupBy.list(thing))))
    .fetch();
```

**Comment by dvkuenssberg** [comment]
Hi, in the meantime I stumbled on this problem again. I'm still receiving a `Map` instead of a `List` from this call. The only difference from your code is that I first create the query, then apply the pagination and then call transform (see my initial post). From what I can see, `as` always returns a `Map`. Is there another way?
