### ISSUE TITLE
Add docs for querydsl-kotlin extenstions

### ISSUE THREAD

**Issue by rvinzent** [querydsl/querydsl#3492]
## Description

I can't seem to find any equivalent documentation for `querydsl-kotlin` extension methods, including the docstrings of the functions themselves.

It would be nice to have a brief section similar to [Scala](http://querydsl.com/static/querydsl/5.0.0/reference/html_single/#scala) support. We've been using QueryDSL in kotlin for a while now without the Kotlin extensions, but it's not clear in any docs how they are intended to be used and what problem they solve.

Thanks!

**Comment by tanhh326** [comment]
Java and kt are interlinked, it is enough to read java

**Comment by rvinzent** [comment]
> Java and kt are interlinked, it is enough to read java

@tanhh326 I agree for the rest of querydsl, but `querydsl-kotlin` is a package for kotlin specific extensions. It should have examples in kotlin since it would be completely pointless to use in a Java app
