### ISSUE TITLE
Update the documentation for 5.0.0

### ISSUE THREAD

**Issue by tw-kang-namas** [querydsl/querydsl#3497]
## Description

I'm new to Querydsl and would like to use the latest version, but on querydsl.com, there is no 5.0.0 in the version selection list.
![스크린샷 2023-04-21 오후 12 28 25](https://user-images.githubusercontent.com/121791952/233534138-c6d5a26a-5cd9-4b2c-8b8a-cd3782fb2984.png)

**Comment by weissstep** [comment]
Hi @tw-kang-namas, not sure why this happens for you but the 5.0.0 version is displayed fine for me:
![grafik](https://user-images.githubusercontent.com/22427850/233558217-428e9974-294d-4fa0-b1d2-0e69c3db7db5.png)

**Comment by tw-kang-namas** [comment]
Wha...??? That's so strange....
@weissstep Can you give me the link of 5.0.0 documentation? I tried http://querydsl.com/static/querydsl/5.0.0/reference/html_single/, but it says 5.0.0.M1 so I guess this is not a valid link.

**Comment by weissstep** [comment]
Only thing I can think of is that browser cache has an old version of the website. The link you guessed is correct btw, I also get the M1 doc when I go via my link.

**Comment by tw-kang-namas** [comment]
Oh, I see. Then I'll have to use it for now.
Does "M1" part indicate that the documentation is not up to date, or is it just a typo? Can anybody confirm?
