### ISSUE TITLE
fetchCount() method prompts for expiration?

### ISSUE THREAD

**Issue by liming1010** [querydsl/querydsl#3499]
fetchCount() method prompts for expiration，may I ask what to replace it with if query count

version:
<querydsl.version>5.0.0</querydsl.version>

**Comment by jonnybecker** [comment]
This is not a bug. You might want to change that label.

**Comment by liming1010** [comment]
> fetchCount() method prompts for expiration，may I ask what to replace it with if query count
> 
> version: <querydsl.version>5.0.0</querydsl.version>
