### ISSUE TITLE
APT generation of plain SQL query types

### ISSUE THREAD

**Issue by giorgiga** [querydsl/querydsl#350]
I wanted to use QueryDSL over plain JDBC (no JPA or JDO), but I couldn't find a way to generate the query types starting from annotated beans (as opposed to "from the database tables").

This seems not to be supported, but I'm not sure... if it actually is, please make this ticket a request for documentation instead of an enhancement request.

**Comment by emmanueltouzery** [comment]
I'm also interested in this feature. Actually I would be happy to be able to generate the `Sql` types from anything but the live tables. Could be from the JPA model, could be from a XML file or even from a code specification. I'd just like to avoid querying the live DB at compilation time due to complications with CI integration, difficulty in getting it to generate bindings for only a few tables out of a very large schema, basically the same concerns as @dgsmith2 and @giorgiga.

**Comment by thackel** [comment]
Why do you closed this issue/feature request?
Do you have a solution?

**Comment by giorgiga** [comment]
Not really: it's just that, a 2015 comment aside, this has been inactive for 5 years... should I re-open?

**Comment by coder-hugo** [comment]
Please re-open this issue. Not having an option to generate the meta-classes from the source code is the only reason why we still stuck to JPA, Hibernate and co.

**Comment by giorgiga** [comment]
Re-opening as requested

**Comment by getaceres** [comment]
+1 for this. QueryDSL already have @QueryEntity and @Column annotations. Maybe a subset of JPA could be enough to generate the QClasses. So far I've been using JPA but for some really complex queries we might need to use plain SQL (for example, JPA doesn't support subqueries in the FROM field which is a fairly common usage. Being able to express SQL queries in a type safe manner for this corner cases would be really appreciated.

**Comment by ichenhe** [comment]
What is the status of this feature? I noticed that the apt [has an `general` classifier](https://querydsl.com/static/querydsl/4.0.4/reference/html_single/#sql_integration), but it doesn't seem to work.

I tried: `kapt("com.querydsl:querydsl-apt:5.0.0:general")` and here's my Entity:

```kotlin
@QueryEntity
@Table("usr")
data class User(
    @Id
    @JsonSerialize(using = ToStringSerializer::class)
    val id: Long,
    val nickname: String,
    val avatar: String?,
)
```

It did generate the Q class, but from `EntityPathBase` which can not be used to `update` as described [#1613](https://github.com/querydsl/querydsl/issues/1613).

If it still cannot be generated without JPA, So what's the difference between `general` and `jpa` classifier?

**Comment by jwgmeligmeyling** [comment]
`general` uses the Querydsl annotations, `jpa` uses the JPA annotations, i.e. `@QueryEntity` or `@Entity`.

`general` cannot be used for `querydsl-sql` as it misses the required metadata. It generates regular paths as opposed to [`RelationalPaths`](https://github.com/querydsl/querydsl/blob/master/querydsl-sql/src/main/java/com/querydsl/sql/RelationalPath.java).

I would welcome PRs introducing an APT codegen extension for `querydsl-sql`.

**Comment by ichenhe** [comment]
@jwgmeligmeyling I'll try to see if I can achieve one.

But other than APT, how can I generate Q classes? It is troublesome to write each model manually like [the sample](https://github.com/querydsl/querydsl/blob/master/querydsl-examples/querydsl-example-sql-spring/src/main/java/com/querydsl/example/dao/CustomerDaoImpl.java).
