### ISSUE TITLE
setLimit and setOffset crash when given null

### ISSUE THREAD

**Issue by akimd** [querydsl/querydsl#3531]
## Observed vs. expected behavior

It is my understanding that, since they explicitly accept nullable arguments, setOffset and setLimit can be given null to clear offset/limit.  But it crashes.

## Steps to reproduce

https://github.com/querydsl/querydsl/blob/cd608f04ed7534b1b62a78a28beb141071d149b6/querydsl-core/src/main/java/com/querydsl/core/DefaultQueryMetadata.java#L301 reads

```java
    public void setLimit(Long limit) {
        if (modifiers == null || modifiers.getOffset() == null) {
            modifiers = QueryModifiers.limit(limit);
        } else {
            modifiers = new QueryModifiers(limit, modifiers.getOffset());
        }
    }
```

so if I pass null, it invokes `QueryModifiers.limit(null)`.  But `QueryModifiers.limit` is:

```java
    public static QueryModifiers limit(@Range(from = 0, to = Integer.MAX_VALUE) long limit) {
        return new QueryModifiers(limit, null);
    }
```

IOW, it requires a non null argument.  And then it crashes.

## Environment

Querydsl version: latest

Querydsl module:

Database:

JDK:

## Additional details

Cheers!

**Comment by akimd** [comment]
I can't see how to revert this misbehavior from that bot.

**Comment by akimd** [comment]
This is ridiculous.  There is nothing fixed, so there is nothing to mark as completed.

**Comment by velo** [comment]
Well, project is abandoned. 

If you want to fix it, you can make a PR on my fork and I will get it released
https://github.com/OpenFeign/querydsl/
