### ISSUE TITLE
Dead again?

### ISSUE THREAD

**Issue by tbadalov** [querydsl/querydsl#3542]
Any news on the future of the project? The last release was in 2021.

**Comment by GourdErwa** [comment]
Seems to be stagnant, abandoning the community version?

**Comment by jherkel** [comment]
Maybe someone from commiters @rdicroce, @jwgmeligmeyling could response? I think the same situation like in the past is repeated. No additional information, no communication. Other projects can remove support (like spring boot) if project seems to be dead like it is now.

**Comment by jwgmeligmeyling** [comment]
I am waiting for Hibernate 6.3 to be released so we can make a Hibernate 6 specific release that takes benefit from new Hibernate features available. Hibernate 6.3 contains improvements that make that possible.

The current version of Querydsl can already be used with Hibernate 6 (when sticking to the basic JPA features), so there was no need to update yet.

**Comment by rdicroce** [comment]
@jherkel For the record, I've offered a bunch of PRs recently, but I have no authority over this repo.

**Comment by jherkel** [comment]
@rdicroce sorry I was mistaken
