### ISSUE TITLE
jdk 11 querydsl 5.0.0 error:  Symbol: class Generated

### ISSUE THREAD

**Issue by cocoCzl** [querydsl/querydsl#3565]
The dependency I introduced is version 5.0.0     
   <dependency>
            <groupId>com.querydsl</groupId>
            <artifactId>querydsl-jpa</artifactId>
            <version>5.0.0</version>
        </dependency>
my jdk 11
spring-boot-version 2.6.6

When I start the project, I always get an error:
java: symbol not found
  Symbol: class Generated
  Location: Package javax.annotation.processing

Is there a solution to this please? 4.4.0 version is no problem

**Comment by cocoCzl** [comment]
I need to use version 5.0.0 because I want to use the JPAQueryFactory insert method to do data

**Comment by naihil** [comment]
JDK 11 dont have javax.annotation.* classes. Add javax.annotation:javax.annotation-api to your dependencies
