### ISSUE TITLE
怎么使用位运算（how to use bitwise operator）

### ISSUE THREAD

**Issue by 1863thuser** [querydsl/querydsl#3591]
querydsl：5.0.0  hibernate：6.2.7  mysql：8.0
我正在使用querydsl-jpa，hibernate，mysql，但我发现并没有位运算表达式。
I'm using querydsl-jpa，hibernate，mysql， butI find that there is no bitwise operator。

我定义了一个BooleanExpression，像这样：
I defined a BooleanExpression like this:
![image](https://github.com/querydsl/querydsl/assets/71204147/1c4677bd-c00d-4de8-8c8d-fea72197ebdd)

我像这样使用：
I use it like this:
![image](https://github.com/querydsl/querydsl/assets/71204147/e94990a3-7b54-4058-a8f2-f7b6b0dcf679)

但我获得了一个错误，hibernate无法识别 '&'：
But I got an error，hibernate didn't recognize '&' :
![image](https://github.com/querydsl/querydsl/assets/71204147/d12ba6c2-af81-41e8-90a6-eb8067633645)

我该如何解决呢，前提是不使用JPQL、HQL、Criteria、SQL
How do I solve this problem if I don't use JPQL, HQL, Criteria, Native SQL

期待大佬的回复
looking forward to a reply，thanks

**Comment by 1863thuser** [comment]
I solved it.

**Comment by xiaopanghhh** [comment]
@1863thuser    乍解决的。
