### ISSUE TITLE
QClass not generated querydslDir in Gradle Setting

### ISSUE THREAD

**Issue by Voyager003** [querydsl/querydsl#3615]
## Observed vs. expected behavior

After installing the querydsl dependency, 
running build-> compileQuerydsl generate a QClass under build/generated/queydsl with the path to def querydsl. 

However when run the application, the path of QClass is changed to build/generated/querydsl/generated and 
'the error java: Attempt to recreate a file for type ...' occurs.

<img width="291" alt="스크린샷 2023-10-30 오후 5 11 07" src="https://github.com/querydsl/querydsl/assets/85725033/bafa435c-3d98-4997-8abd-565b72dc4e72">

it's directory befroe running application.

![스크린샷 2023-10-30 오후 5 08 20](https://github.com/querydsl/querydsl/assets/85725033/182832ea-6e77-4e10-818a-befaad793054)

it's directory after running application and occur 'java: Attempt to recreate a file for type' error

## Steps to reproduce

1. Add the Gradle settings.

```java
plugins {
    id 'java'
    id 'org.springframework.boot' version '3.1.0'
    id 'io.spring.dependency-management' version '1.1.0'
    id "com.ewerk.gradle.plugins.querydsl" version "1.0.10"
}

dependencies {
    // Querydsl
    implementation 'com.querydsl:querydsl-jpa:5.0.0:jakarta'
    annotationProcessor "com.querydsl:querydsl-apt:${dependencyManagement.importedProperties['querydsl.version']}:jakarta"
    annotationProcessor "jakarta.annotation:jakarta.annotation-api"
    annotationProcessor "jakarta.persistence:jakarta.persistence-api"
}

// setting
def querydslDir = "$buildDir/generated/querydsl"

querydsl {
    jpa = true
    querydslSourcesDir = querydslDir
}
sourceSets {
    main.java.srcDir querydslDir
}
compileQuerydsl{
    options.annotationProcessorPath = configurations.querydsl
}
configurations {
    compileOnly {
        extendsFrom annotationProcessor
    }
    querydsl.extendsFrom compileClasspath
}

tasks.named('test') {
    useJUnitPlatform()
}
```

2. Gradle build and CompileJava
3. Run the application

## Environment

Querydsl version: 5.0.0

Querydsl module: querydsl-jpa, querydsl-apt

Database: H2 DB

JDK: Java 17

Spring Boot: 3.1.0

## Additional details

After the path is changed, move the toy to generated and run the application again and it should work.

**Comment by rpkyrych** [comment]
@Voyager003 try to remove `id "com.ewerk.gradle.plugins.querydsl" version "1.0.10"` from plugins and to build again.
It looks like the plugin is outdated and conflicts with querydsl v5

**Comment by Voyager003** [comment]
@rpkyrych I fixed to remove plugin as you said, but build is failed and occured this error,

```
A problem occurred evaluating root project '--'.
Could not find method querydsl() for arguments [build_1nsrjt4d8dqaimc38lgg23yy3$_run_closure4@29dd41d6] on root project '--' of type org.gradle.api.Project.
```

So I'm using the following settings this stopgap.

```java
def generated = 'src/main/generated'

// add script
clean {
    delete file (generated)
}

querydsl {
    jpa = true
    querydslSourcesDir = generated
}
sourceSets {
    main.java.srcDir generated
}

// add script
tasks.compileQuerydsl.dependsOn(clean);

compileQuerydsl{
    options.annotationProcessorPath = configurations.querydsl
}

configurations {
    compileOnly {
        extendsFrom annotationProcessor
    }
    querydsl.extendsFrom compileClasspath
}
```

Add a QType removal action to the Querydsl-related plugin removal and clean actions to create a new QType on gradle task - build.
