### ISSUE TITLE
Query DSL + JPA Repository + Page mapping = Unable to find Querydsl root type for detected domain

### ISSUE THREAD

**Issue by ASaludo** [querydsl/querydsl#3642]
## Observed vs. expected behavior

I try to use Query DSL in a Kotlin App and intend to query a relationnal database. I want to minimize my controller response using a DTO transformation using
`<U> Page<U> map(Function<? super T, ? extends U> converter);`
to convert my Entity into a DTO but the QuerydslBindingsFactory want to use a predicate of my DTO instead of the entity.
I didn't succeed of using Fluent Query for projection so I tried with Page mapping and even with QuerydslPredicate It still search for a QDto class

My expectation : 
When I use QuerydslPredicateExecutor<Entity> as interface I expect that he try to use predicate from the entity and not the controller response

## Steps to reproduce

Controller
```
@RestController
@RequestMapping(value = ["/path"])
class MyController(val myService: MyService) {

    @GetMapping
    fun get(predicate: Predicate, pageable: Pageable) = myService.get(predicate, pageable)

}
```

Service
```
@Service
class MyService(val myRepository: MyRepository) {

    fun get(@QuerydslPredicate(root = Entity::class) predicate: Predicate, pageable: Pageable) : Page<Entity> = myRepository.findAll(predicate, pageable)

}
```

Repository
```
@Repository
interface MyRepository: JpaRepository<Entity, Float>, QuerydslPredicateExecutor<Entity>
```

## Environment

Querydsl version: 5.0.0

Querydsl module: 5.0.0

Database: MSSQL

JDK: 17

**Comment by H-Lo** [comment]
Good luck with that because this project is abandoned.

**Comment by Oodachi** [comment]
https://github.com/OpenFeign/querydsl
