### ISSUE TITLE
Spring 3 Code Generation don't work

### ISSUE THREAD

**Issue by lucasfrederico** [querydsl/querydsl#3647]
Guys, I'm trying to make this work, but it doesn't work for me. If I remove the maven-compiler-plugin, I get the message "Compilation failure
Bad service configuration file, or exception thrown while constructing Processor object: javax.annotation.processing.Processor: com.querydsl.apt.jpa.JPAAnnotationProcessor Unable to get public no-arg constructor".

Can anyone help me? My [my pom.xml](https://pastebin.com/0ZLp92Vy)

_Originally posted by @lucasfrederico in https://github.com/querydsl/querydsl/issues/3296#issuecomment-1859335307_

**Comment by angela-lopez-dev** [comment]
Why do you need to remove the maven-compiler-plugin ?

**Comment by lucasfrederico** [comment]
I already tried, the error remains the same. In this pom.xml that I sent previously, the maven-compiler-plugin configuration was already disabled, but it still had the plugin, so now I removed it completely, but the same result remains. https://pastebin.com/wiihC1Q8
![image](https://github.com/querydsl/querydsl/assets/55282018/3681432c-2e97-41a5-829b-1180cfe2916c)

**Comment by angela-lopez-dev** [comment]
From my understanding, you do need to remove references to the deprecated `com.mysema.maven.apt-maven-plugin`. However you also commented out the `maven-compiler-plugin` which is needed to generate QClasses. Could you try uncommenting the `<plugin>` node which contains the `maven-compiler-plugin` reference ? You may also need to remove the `<configuration>` node which references ` JPAAnnotationProcessor` inside the `maven-compile-plugin` node.

**Comment by lucasfrederico** [comment]
But all of this is commented... I don't understand what you mean by that.

**Comment by angela-lopez-dev** [comment]
I meant that you need to remove the comments around the `maven-compiler-plugin` node in your pom and only comment out the `configuration` portion of the plugin. Could you try this modified [pom](https://pastebin.com/ckCZJ0PG) ?

**Comment by lucasfrederico** [comment]
Same result.
https://pastebin.com/fiMY1DtG
![image](https://github.com/querydsl/querydsl/assets/55282018/c5a33e6a-1d3d-4dfe-ac03-a4a644446ac7)

**Comment by angela-lopez-dev** [comment]
Okay, my bad I looked around and it seems you might need to keep the maven-compiler-plugin and remove comments around the `configuration` node. Perhaps  [this](https://stackoverflow.com/questions/36248959/bad-service-configuration-file-or-exception-thrown-while-constructing-processor) will help you.

**Comment by angela-lopez-dev** [comment]
That's weird, I updated to spring 3 recently and using the method described in the initial thread worked. Probably has to do with your specific pom config indeed.
I'll give it a try tomorrow at work when I have the working config available.

**Comment by angela-lopez-dev** [comment]
I created a fake project and a dummy data class using your pom as a source and [this version works](https://pastebin.com/BztPiWVZ) both with intellij built-in maven tool and with `./mvnw ` commands. The commands I used are `./mvnw dependency:resolve` and `./mvnw clean install`. The Q-classes are then generated under the usual folder in `target/generated-sources/annotations`.   
Here is the full project -> [fixpom.zip](https://github.com/querydsl/querydsl/files/13719207/fixpom.zip)

**Comment by lucasfrederico** [comment]
> I created a fake project and a dummy data class using your pom as a source and [this version works](https://pastebin.com/BztPiWVZ) both with intellij built-in maven tool and with `./mvnw ` commands. The commands I used are `./mvnw dependency:resolve` and `./mvnw clean install`. The Q-classes are then generated under the usual folder in `target/generated-sources/annotations`. Here is the full project -> [fixpom.zip](https://github.com/querydsl/querydsl/files/13719207/fixpom.zip)

I tried to do mvn clean install on your project and I get the same problem. How does this work for you? Wtf

**Comment by angela-lopez-dev** [comment]
What is the exact command you type and where ? It's really weird that it doesn't work if you use the `mvnw` wrapper at the root of the project. If you use your host `mvn` command or your IDE maven interface instead, it might have to do with a specific configuration override in one or the other.

**Comment by lucasfrederico** [comment]
I use mvn clean install with maven from the IntelliJ IDE. The IDE uses Maven 3.

**Comment by lucasfrederico** [comment]
Try using ./mvn clean install and it doesn't work either.
https://pastebin.com/03Rv3p0H

**Comment by angela-lopez-dev** [comment]
Does `./mvnw clean install` work on the fake project ? If it does can you post the full debug log for your actual project using `./mvnw clean install -X` please ?

**Comment by lucasfrederico** [comment]
This is the [log file](https://github.com/querydsl/querydsl/files/13720267/log.txt) for the execution of your project, before I had tested it on your project too.

**Comment by angela-lopez-dev** [comment]
I'm at loss for what to do here honestly. Maven versions are the same, java version is the same. The only thing that might differ is the operating system and the `.m2` cache directory. Maybe you could try temporarily renaming your `.m2` directory to something like `.m2-bak` in order to force dependency resolving and then try re running the fake project? 
Sorry I couldn't help !

**Comment by lucasfrederico** [comment]
![image](https://github.com/querydsl/querydsl/assets/55282018/9ea8281e-577e-4149-86ab-7df75612a412)
![image](https://github.com/querydsl/querydsl/assets/55282018/0113bae7-94cb-4a81-9e39-87263d48e314)
I don't believe the problem was corrupted dependencies. I've had this problem before, but hadn't tested it this time. Thanks for all your help! This worked, thanks!

**Comment by qianyawjj** [comment]
最后怎么解决的？
