### ISSUE TITLE
QueryDSL-5.1.0 is not Java Runtime 8 compatible anymore?

### ISSUE THREAD

**Issue by FJGL** [querydsl/querydsl#3672]
Failed to execute goal com.mysema.maven:apt-maven-plugin:1.1.3:process...

java.lang.RuntimeException: java.lang.UnsupportedClassVersionError: com/querydsl/core/annotations/QueryEntities has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
 
java.lang.RuntimeException: java.lang.UnsupportedClassVersionError: com/querydsl/apt/jpa/JPAAnnotationProcessor has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0

Querydsl version: 5.1.0

JDK: 1.8

**Comment by liming1010** [comment]
update java version to 11

**Comment by FJGL** [comment]
Yes, I know that :) .  The problem is not how to fix it. It is that in the release notes of 5.0.0 the intention was very clear "This release of QueryDSL targets Java 8 minimally", but with no mention in the release notes of 5.1.0: https://github.com/querydsl/querydsl/releases/tag/QUERYDSL_5_1_0, this is an unplanned and unexpected situation. In many environments it is not so easy to change the Java version, old JEE application servers, enterprises policies, etc. as you know.
Thanks anyway.

**Comment by lzw-luozhiwei** [comment]
I have the same problem. How did you solve it？
