### ISSUE TITLE
Unable to use QueryDSL with my spring boot 3 project

### ISSUE THREAD

**Issue by Gaga-for-coding** [querydsl/querydsl#3693]
[## Observed vs. expected behavior
My IDE keeps giving this error java: Attempt to recreate a file for type com.guissisoftware.starter.model.QCourse
whenever I run mvn clean install

## Steps to reproduce

<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>3.1.5</version>
		<relativePath/> 
	</parent>
	<groupId>com.guissisoftware</groupId>
	<artifactId>starter</artifactId>
	<version>0.0.1-SNAPSHOT</version>
	<name>starter</name>
	<description>Journey to learning Spring boot with Musib</description>
	<properties>
		<java.version>17</java.version>
		<querydsl.version>5.1.0</querydsl.version>
	</properties>
	<dependencies>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-web</artifactId>
			<exclusions>
				<exclusion>
					<groupId>org.springframework.boot</groupId>
					<artifactId>spring-boot-starter-logging</artifactId>
				</exclusion>
			</exclusions>
		</dependency>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-data-jpa</artifactId>
		</dependency>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
		</dependency>

		<dependency>
			<groupId>com.querydsl</groupId>
			<artifactId>querydsl-apt</artifactId>
			<version>${querydsl.version}</version>
			<classifier>jakarta</classifier>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>com.querydsl</groupId>
			<artifactId>querydsl-jpa</artifactId>
			<classifier>jakarta</classifier>
			<version>${querydsl.version}</version>
		</dependency>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-jooq</artifactId>
		</dependency>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-log4j2</artifactId>
		</dependency>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-validation</artifactId>
		</dependency>
	</dependencies>

	<build>
		<plugins>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
			</plugin>
			
			<plugin>
				<groupId>com.mysema.maven</groupId>
				<artifactId>apt-maven-plugin</artifactId>
				<version>1.1.3</version>
				<executions>
					<execution>
						<goals>
							<goal>process</goal>
						</goals>
						<configuration>
							<outputDirectory>target/generated-sources/java</outputDirectory>
							<processor>com.querydsl.apt.jpa.JPAAnnotationProcessor</processor>
						</configuration>
					</execution>
				</executions>
				<dependencies>
					<dependency>
						<groupId>com.querydsl</groupId>
						<artifactId>querydsl-apt</artifactId>
						<version>${querydsl.version}</version>
					</dependency>
				</dependencies>
			</plugin>
		</plugins>
	</build>

</project>

## Environment

Windows 10, Intellij Idea 

Querydsl version: 5.1.0

Querydsl module:

Database:
Spring boot
JDK:
Java 17

## Additional details

](java: Attempt to recreate a file for type com.guissisoftware.starter.model.QCourse)

**Comment by billschen** [comment]
I use with  Gradle 8.5 and jdk 21.0.1 and spring boot 3.x,no problem.

**Comment by ivan-slavchev** [comment]
@Gaga-for-coding you can try to remove the querydsl-apt dependencies from </dependencies> and leave it only inside the <plugin>as dependency. Also might be necessary to add the jakarta classifier there. This is what worked for me at least.

**Comment by velo** [comment]
Try my fork
https://github.com/OpenFeign/querydsl

Its active, and people PRs are not ignored.

**Comment by spyro2000** [comment]
I would but using OpenFeign 6.12 in Spring Boot 3.5.4 for some reason is messing up my logging context `LogManager.getContext(false)` now returns L4j's LoggerRegistry instead of Log4js `LoggerContext`. This results in an exception when booting up and trying to register appenders.
