### ISSUE TITLE
Enhancing QueryDSL LIKE Searches with Wildcard Enum for Improved Flexibility

### ISSUE THREAD

**Issue by dukbong** [querydsl/querydsl#3756]
## Why the new feature should be added

Currently, when using the like method in QueryDSL, users are required to manually add % wildcards to the string. This means that every time a LIKE search is performed, the % symbols need to be inserted manually, which can lead to mistakes. To improve this, I propose introducing an Enum type, such as WildCard, that allows users to easily specify the desired LIKE search pattern. This approach will enhance code readability, reduce the chances of mistakes, and provide a better experience when using QueryDSL.

## How the new feature should work

Current Behavior
Currently, QueryDSL's like method requires users to manually include % wildcards in the string for performing a LIKE search. This leads to repetitive tasks and increases the potential for mistakes when specifying the wildcard placement.

Expected New Behavior
The new feature will introduce an Enum type, WildCard, that supports the following LIKE patterns:
```java
public enum WildCard {
    CONTAINS,      // Full inclusion search (%term%)
    STARTS_WITH,   // Search for values starting with the term (%term)
    ENDS_WITH,     // Search for values ending with the term (term%)
    NONE           // User-defined pattern without wildcards (text)

    public String transferPattern(String str) {
        if (this == WildCard.CONTAINS) {
            return "%" + str + "%";  // %term%
        } else if (this == WildCard.STARTS_WITH) {
            return "%" + str;       // %term
        } else if (this == WildCard.ENDS_WITH) {
            return str + "%";       // term%
        } else if (this == WildCard.NONE) {
            return str;             // text (user-defined pattern without wildcards)
        } else {
            return str;
        }
    }
}
```
Users will be able to easily use the desired LIKE pattern with the WildCard Enum, as shown in the following examples:
```text
like(text, WildCard.CONTAINS);      // like %text%;
like(text, WildCard.STARTS_WITH);   // like %text
like(text, WildCard.ENDS_WITH);     // like text%
like(text, WildCard.NONE);          // like text (user-defined pattern without wildcards)
```
The like method will be implemented as follows:
```java
public BooleanExpression like(String str, WildCard wildCard) {
    if (wildCard == null) {
        wildCard = WildCard.NONE; // Default to NONE if no WildCard is provided
    }
    return Expressions.booleanOperation(Ops.LIKE, new Expression[]{
        this, ConstantImpl.create(wildCard.transferPattern(str))
    });
}
```
This approach allows users to easily leverage different LIKE patterns without manually adding % each time. The new feature will make LIKE searches in QueryDSL more efficient and intuitive.

**Comment by giugallo** [comment]
In the class `com.querydsl.core.types.dsl.SimpleExpression`, in addition to the `like(...)` method, there are also `contains(...)`, `startsWith(...)` and `endsWith(...)` methods that should be sufficient to handle all cases.
