### ISSUE TITLE
Add javax.annotation.processing.Processor file in APT for Java 6 compatibility

### ISSUE THREAD

**Issue by sinuhepop** [querydsl/querydsl#437]
I usually have problems using APT processor with Eclipse Juno. When I don't use the Maven plugin, metamodel is not being generated. When I use it I get an error such as described here: https://github.com/mysema/querydsl/issues/6

In my opinion, these problems would be avoided if APT processor runs in "auto discovery" mode. That is, META-INF/services/javax.annotation.processing.Processor must be included in jar file, containing the name of the processors.

I've tried this only with JPA processor (com.mysema.query.apt.jpa.JPAAnnotationProcessor), and it works like a charm. IMHO, all processor could be executed this way with almost no performance penalisation.

Greetings.

**Comment by nealeu** [comment]
Oh my god!  This is what I've been missing all along.  That classifier.
