### ISSUE TITLE
QuerySyntaxException: unexpected AST node when selecting a constant

### ISSUE THREAD

**Issue by johnjaylward** [querydsl/querydsl#455]
Hibernate AST output:

select ?1
from T1 tli
  left join tli.t2 as vb
where tli.lft between ?2 and ?3
group by tli.t3
order by tli.t3.date desc

QueryDSL call is :
query.list(Expressions.constant("1")).size()
I don't really care what comes back in the list() call, but I assumed just having it return a "1" would be faster then having hibernate convert useless data into a model object. 

Instead QueryDSL is converting my constant expression into a parameter, and hibernate doesn't know what to do with it.

**Comment by syakovyn** [comment]
> This is a bug in Hibernate's query parser.
I don't quite understand why this is Hibernate's bug. I can see that '?' is appended by com.mysema.query.jpa.JPQLSerializer#visitConstant method. It serializes a direct literal into the parameter, and only allows for literals in case operations.
