### ISSUE TITLE
Feature: Add method for crossJoin

### ISSUE THREAD

**Issue by johnjaylward** [querydsl/querydsl#459]
Currently the only way to add cross joins is using the "from" method on Query and SubQuery objects, but this feels awkward when building dynamic queries.

```
q = new HibernateQuery(mySession).from(primaryEntityPath);
q.where(somePredicate);
if(someParameter == someExpectation){
q.from(secondaryEntityPath).where(someOtherPredicate);
}
```

The second "from" call there doesn't read well to me. Calling q.crossJoin would seem more accurate/readable.

 Also, the current "from" clause doesn't accept any alt-alias paths like the existing *join methods have. It'd be nice to have similar functions available for cross join that innerJoin, fullJoin etc have.

**Comment by kotlinistaAnkita** [comment]
Please add method for cross join function it will be of great help
