### ISSUE TITLE
Tune JDBC numeric mappings

### ISSUE THREAD

**Issue by timowest** [querydsl/querydsl#578]
Tune JDBC numeric mappings. The mapping for numeric(1,0) might need to be reconsidered.

Related:
http://stackoverflow.com/questions/20288414/querydsl-how-to-apply-type-mappings-via-the-querydsl-maven-plugin/20301986#20301986
https://github.com/mysema/querydsl/issues/535
https://github.com/mysema/querydsl/issues/513

**Comment by jjzazuet** [comment]
Um, naive question here but then, how can I use overrides to map `boolean` types to `NUMERIC(0-1,0)`? Any help or pointers appreciated. Thanks!
