### ISSUE TITLE
Use singleton MorphiaSerializer and provide Morphia as context attribute

### ISSUE THREAD

**Issue by timowest** [querydsl/querydsl#589]
Use singleton MorphiaSerializer and provide Morphia as context attribute

This change shouldn't be applied to the 3.* series since it breaks backwards compatibility

**Comment by timowest** [comment]
depends on https://github.com/querydsl/querydsl/issues/612

**Comment by timowest** [comment]
For consistency this might not be such a good idea, since this pattern hasn't been applied elsewhere in Querydsl and it might make also extension more complicated, since Spring Data Mongodb for example has multiple dependencies https://github.com/spring-projects/spring-data-mongodb/blob/master/spring-data-mongodb/src/main/java/org/springframework/data/mongodb/repository/support/SpringDataMongodbSerializer.java#L59

@Shredder121 I am considering to close it without implementation. What do you think?

**Comment by Shredder121** [comment]
I agree that suddenly applying that pattern would be strange.
I also think it would make extension difficult, not just for Spring Data Mongodb, but also means we have to ensure that we don't mess up with potentially future changes.
I think it's better to keep it this way, so closing it is fine with me.
