### ISSUE TITLE
Integrate with gradle

### ISSUE THREAD

**Issue by lstrzelecki** [querydsl/querydsl#599]
It would be nice to have gradle plugin for processing entities.

something like this in build.gradle file

```
apply plugin: 'querydsl'

jpaExport {
       packages 'com.example.domain'
}
```

**Comment by marceloverdijk** [comment]
I found https://github.com/ewerk/gradle-plugins/tree/master/querydsl-plugin by @holgerstolzenberg.
It's a fairly new library and I haven't used it myself yet.
Would it be an idea to add / merge this to the querydsl lib?

**Comment by holgerstolzenberg** [comment]
How would that merge/add be realised in detail?

One of the most important things for me is that it will be still available through Gradle Plugin Portal if you integrate it into your lib. This may need changes to your build (ecosystem), as all Gradle plugins are hosted on Bintray (http://plugins.gradle.org/submit). Using plugins we plugin portal is really more expressive and straightforward.

Another thing is that our plugin go a slightly different approach then yours  mentioned above. Once the plugin is registered, there is only one extension available for configuring the plugin. There you can switch on/off the different annotation processors. Excluding/including packages is not available, the processors are registered at the `compileJava` task, so all annotated sources will be taken into account.

**Comment by marceloverdijk** [comment]
OK maybe it's not a good idea then.
However I still think it would be very nice if querydsl would have an 'official' maintained gradle plugin, just like it has for maven.

**Comment by holgerstolzenberg** [comment]
Oh no,  please do not get me wrong. I also think that having an 'official' maintained plugin is a nice idea, for sure, I just wanted to say that we should discuss what could be an applicable way to do so.

**Comment by marceloverdijk** [comment]
Hope @timowest will join the discussion :-)

**Comment by timowest** [comment]
I am currently quite busy with doing the changes for the Querydsl 4.0
release. In general it would be good if the gradle plugin would provide the
same functionality as the querydsl maven plugin.

**Comment by johnjaylward** [comment]
it wasn't that hard to set up gradle to handle QueryDSL, here's my config if it helps make a standard plugin:

I use the propdeps-plugin to exclude the querydsl-apt jar from the final package. It shouldn't be needed for the plugin since plugin deps are not packaged.

```
buildscript {
    repositories {
        maven { url 'http://repo.spring.io/plugins-release' }
    }
    dependencies {
        classpath 'org.springframework.build.gradle:propdeps-plugin:0.0.6'
    }
}

sourceSets {
    main
    test
    // used by the QueryDSL apt pre-compile step for apt output
    generated
}

dependencies {
    // use the provided scope from propdeps-plugin so apt is not release in final JAR
    provided group: "com.mysema.querydsl", name: "querydsl-apt", version: "3.6.0"
    // ... project dependencies like Hibernate etc.
}

// Task modifications to generate code using apt
def generatedSrcDir = "src/generated/java"
task createGeneratedSrcDir << {
    file(generatedSrcDir).mkdirs()
}
compileJava.dependsOn createGeneratedSrcDir

compileJava {
    options.compilerArgs << "-processor" << "com.mysema.query.apt.jpa.JPAAnnotationProcessor" << "-s" << file(generatedSrcDir).absolutePath
}

clean {
    delete fileTree(dir:generatedSrcDir,exclude: ".gitignore")
}
```
Ideally, a plugin would not use a common "generated" source set like I did, but would have it's own and add it to the sourceSet collection so that other plugins like eclipse or intellij would be able to find the generated sources.

**Comment by marceloverdijk** [comment]
Wouldn't it be more logical to generate the code somewhere in /build instead of /src/generated/java?

**Comment by johnjaylward** [comment]
Yes. I was personally going for the least amount of configuration in gradle, but to keep it in line with the maven plugin, /build would be the place to go. I just used the defaults for the sourceSet.

**Comment by holgerstolzenberg** [comment]
The setup @johnjaylward mentioned is pretty much what the plugin does at the moment. The location to where the code is generated can be configured and defaults to `src/querydsl/java`.

**Comment by bozaro** [comment]
Why is the file querydsl/querydsl-apt/etc/META-INF/services/ javax.annotation.processing.Processor misses the querydsl-apt.jar file?
Its presence is automatically connected to the annotation processor during compilation using the javac (in maven, gradle, Idea and etc).

**Comment by bozaro** [comment]
I found out where the file META-INF/services/javax.annotation.processing.Processor: turns out there are several jar-files for com.mysema.querydsl:querydsl-apt:3.6.3.

In my case it was needed com.mysema.querydsl:querydsl-apt:3.6.3:hibernate

**Comment by persapiens** [comment]
+1

**Comment by ede-n** [comment]
+1

**Comment by bigalnz** [comment]
+1

**Comment by DineshShende** [comment]
+1

**Comment by vnobo** [comment]
It's been 5 years now

**Comment by Shredder121** [comment]
Gradle has javac support, can run ant tasks, can run arbitrary code (GenericExporter).
@vnobo the only thing we lack is documentation, thanks for the super comment btw

**Comment by niebaraka** [comment]
There is one issue described here: 
https://discuss.gradle.org/t/annotationprocessor-querydsl-java-lang-noclassdeffounderror/27107
If shortly, j`avax.persistence.*` annotations are not in the classpath of the annotation processor and therefore it fails.  Probably, it was not visible before, but since gradle 4.6, annotation processors are defined in a special scope named `annotationProcessor` and it is separate from `implementation` (`compile`). So in gradle we have to include `javax.persistence.*` and also `javax.annotation.Generated` in `annotationProcessor` in addition to `implementation`. Is it possible to include these dependencies as transitive?
