### ISSUE TITLE
Optimistic locking support in Querydsl SQL

### ISSUE THREAD

**Issue by timowest** [querydsl/querydsl#652]
Optimistic locking via version fields

Pseudocode

```
configuration.addVersionField(“EMPLOYEE”, “VERSION”);
QEmployee employee = QEmployee.employee;
update(employe).populate(...).execute();
// throws Exception for stale version 
```

**Comment by raymondBourges** [comment]
Did you plan to implement this feature?
If not, maybe have you a branch that initiates the work on which it would be possible to provide assistance...
