### ISSUE TITLE
JPA 2.1 capabilities

### ISSUE THREAD

**Issue by ldez** [querydsl/querydsl#658]
Add support for Hibernate 4.3.x.
Add also support of new JPA 2.1 capabilities, ex : `treat` for `.as(Class)` when entities are joined.

**Comment by virgo47** [comment]
Sorry for asking in the closed issue, but Google search for "Querydsl JPA 2.1 FUNCTION" lead me here. I see that TREAT is in Querydsl, but I don't understand what the status of FUNCTION is, and if it is in, how it should be used (search through Reference did not help).

**Comment by virgo47** [comment]
Seems I needed to ask (after a long search, mind you :-)), after the question I got it in a minute, as it is not strictly tied to JPA 2.1, but more to Querydsl templates:
http://stackoverflow.com/questions/22984343/how-to-call-mysql-function-using-querydsl

So we should just use `Expressions.xxxTemplate` depending on the type and write `function(real_function)` template ourselves.

**Comment by Shredder121** [comment]
Yes, that would be right.
Don't forget to also make your functions known to the JPA provider.
