### ISSUE TITLE
ConstructorExpression with joined boolean parameter causes IllegalArgumentException

### ISSUE THREAD

**Issue by wrungel** [querydsl/querydsl#679]
(Left-)Joining two entities with JPAQuery and using **boolean** property from the right joined entity causes _IllegalArgumentException_.

See test cases in https://github.com/wrungel/qdsl-bugs/tree/master/constructor-expression-boolean-bug
The following tests fails:
- constructor_expression_with_joined_boolean_parameter()
- nested_constructor_expression_with_joined_string_and_boolean_parameter()

Querydsl version: 3.3.1, 3.2.2
JPA Provider: Hibernate 4.2.8.Final, 4.1.5.Final
Database: h2, Oracle

**Comment by axelosorio** [comment]
I have similar problem when I was working in a Join with no values in the other table to join. The problem in hibernate is that it causes illegalArgumentException and tupleTransform problem in the join.
The thing was that in my constructor of the entity I have a type as double and it must be Double.
BAD CODE: 
```
public DetalleFacturaEmbarqueEB(Integer idDetalleFacturaEmbarque,
									Integer idFacturaEmbarque,
									double descuento
				  					){
```

GOOD CODE
```
public DetalleFacturaEmbarqueEB(Integer idDetalleFacturaEmbarque,
									Integer idFacturaEmbarque,
									Double descuento
				  					){

```

As you see "descuento" was as **double** and not as **Double**.
It works for me, I hope it helps someone else.
