### ISSUE TITLE
Support for Date Time API types in SQL module

### ISSUE THREAD

**Issue by timowest** [querydsl/querydsl#696]
Support for Date Time API types in SQL module

http://download.java.net/jdk8/docs/api/java/time/package-summary.html
http://docs.oracle.com/javase/tutorial/datetime/

Related issue https://github.com/mysema/querydsl/issues/680
- Instant - DATETIME
- LocalDate - DATE
- LocalDateTime - DATETIME
- LocalTime - TIME
- OffsetDateTime - DATETIME
- OffsetTime - TIME
- ZonedDateTime - DATETIME

**Comment by arturchyzy** [comment]
I pulled a request for it [https://github.com/querydsl/querydsl/pull/1209]. There is a problem with animal enforcer but if we resolve that it should work.

**Comment by Shredder121** [comment]
I can take it from there.

**Comment by gokhanoner** [comment]
Can we use Java 8 Date/Time types yet ? I'm using 3.6.2 but couldn't see those types ??

**Comment by Shredder121** [comment]
No, there are still some finicky Date/Time API methods I have to work around. (considering timezones, the way they model the objects, converting to/from, etc).
I will continue with the changes.

**Comment by Max1ds** [comment]
Do you plan release with Java 8 Date/Time types generation in near future?

**Comment by Shredder121** [comment]
Yes, in the near future we are releasing the JSR310 support.
Thanks for showing interest!

**Comment by Max1ds** [comment]
It's great news :). 
Can you specify near future? Is it days or weeks? :) Maybe at the end of this month?

**Comment by simonecarriero** [comment]
Hi, any news on this feature?

**Comment by gokhanoner** [comment]
Any new about JSR310 support ??

**Comment by timowest** [comment]
@simonecarriero @gokhanoner JSR 310 types are supported

**Comment by gokhanoner** [comment]
Thank you. Is there any doc/example shows how to use JSR 310 types during model creation?

**Comment by jwgmeligmeyling** [comment]
This was implemented in https://github.com/querydsl/querydsl/commit/faed3a7486d547d45c72273d6aa83eea55136131.
