### ISSUE TITLE
JPQL for Entities not correctly generated when using leftJoin

### ISSUE THREAD

**Issue by sendele** [querydsl/querydsl#726]
It seems that Querydsl does not include complete class descriptors in "LEFT JOIN" statements (e.g. "User" instead of "com.querydsl.example.jpa.model.User") when using JPAQuery.leftJoin() explicitly.

This can be reproduced with the JPA examply project on https://github.com/querydsl/querydsl-jpa-example by adding the following to the TweetRepository:

``` java
public List<Tweet> findByLeftJoin() {
    QUser user = QUser.user;
    return query()//
            .from(tweet)//
            .leftJoin(user)//
            .on(tweet.poster.eq(user))//
            // .where(user.username.eq("dr_frank")) // not necessary
            .list(tweet);
}
```

And small test for that in TweetRepositoryTest:

``` java
@Test
public void testFindByLeftJoin() throws Exception {
    repository.findByLeftJoin();
}
```

The following error is thrown:

``` log
java.lang.IllegalArgumentException: org.hibernate.hql.internal.ast.QuerySyntaxException: Path expected for join! [select tweet
from com.querydsl.example.jpa.model.Tweet tweet
  left join User user with tweet.poster = user]
    at org.hibernate.ejb.AbstractEntityManagerImpl.convert(AbstractEntityManagerImpl.java:1364)
    ...
```

I know that this can be expressed way more elegant by (the reason why I celebrate Querydsl)

``` java
query().from(tweet).where(tweet.poster.username.eq("dr_frank")).list(tweet);
```

But the upper implementation should work, shouldn't it?

**Comment by kehuaang** [comment]
Hello, look at the dialogue of the two, I still don't understand leftjoin...On how to use, can cite a simple example, thank you very much!

**Comment by hfcipriano** [comment]
> The problem is, we want to formulate a join on two entities, for which the relation is not modelled explicitly. Isn't that possible with Querydsl?
Querydsl JPQL is like a typesafe version of JPQL. So you will need to write it as from(a,b).where(a.propX.eq(b.propY));

> And what is the method JPAQueryBase.on(Predicate) there for then?
These are for further constraints on the joins.

> In a nutshell: joins in JPQL are for property path navigation, if you want to join unrelated entities you will need to use from and  where.   

Hello guys.

I would like to know is today is more efective way to use this soluction (way instead use from()).

I tried the follow:

`.leftJoin(entityA.entityB, subEntityB._super)
`

and got the exception
`Method threw 'java.lang.ArrayIndexOutOfBoundsException' exception.`


Someone can help me?
