### ISSUE TITLE
Support for querying against @MappedSuperclass 

### ISSUE THREAD

**Issue by PClaus** [querydsl/querydsl#75]
Hi Timo!

I've posted this on StackOverflow:

http://stackoverflow.com/questions/8702542/can-i-remove-the-discriminator-column-in-a-hibernate-single-table-inheritance

and you said to create a ticket here as this "is easily implemented" ;)

Basicly we'll need the @MappedSuperclass annotation to be treated as an @Entity annotation when generating querytypes.

Summary of our setup:

We are working with single table inheritance for all entities in our application but don't need or want a discriminator column in the database as it would be redundant and cost a lot of space and performance. Hibernate's alternative instead of using 

@Entity
@Inheritance(strategy = InheritanceType.SINGLE_TABLE)

(which is already supported by queryDSL) is to use 

@MappedSuperclass

so that no discriminator type is required to map the data from an extended entity back to its abstract parent object.

However: The Query DSL querytype generator does not generate an accessor for @MappedSuperclass.

Example:

@MappedSuperclass
@Inheritance(strategy = InheritanceType.SINGLE_TABLE)@Table(name = "client")
public abstract class Client extends AbstractPersistable<Long> {
    private String name;
    // getter, setter...
}

+

@Entity
public class ClientSimple extends Client {

should support a query like this:

query.where(QClient.client.name.equals("..."));

with the query.list ultimately returning a List of Client objects than can then be mapped to ClientSimple objects.

This behaviour is neccessairy, because another application instance of the same base application might extend the Client in a different way (ClientAdvanced) but still has to use most of the same querying methods to find objects of the Client type but then cast them to ClientAdvanced.

**Comment by jaumzera** [comment]
Nice. Also worked for me.
Thank you.
