### ISSUE TITLE
Spatial additions

### ISSUE THREAD

**Issue by timowest** [querydsl/querydsl#792]
ST_AsEWKT
ST_GeomFromText
ST_SetSRID
ST_XMin
ST_XMax
ST_YMin
ST_YMax
ST_DWithin
ST_Extent
ST_Collect
ST_Dump
ST_Translate

There are also some geometry construction functions:

ST_Point
ST_MakePoint
ST_MakeLine
ST_MakeBox2D

PostGIS also supports a type called Geography (http://postgis.refractions.net/docs/using_postgis_dbmanagement.html#PostGIS_Geography).

**Comment by kherrala** [comment]
Sorry for asking it here, but I fail to understand how the geometry constructor functions have been implemented in this change? I could not find ST_MakePoint() anywhere.
