### ISSUE TITLE
Improve mongodb reference handling

### ISSUE THREAD

**Issue by timowest** [querydsl/querydsl#803]
In eq and ne operations reference cases are not handled properly.

**Comment by simonered** [comment]
Seems not working anymore...

**Comment by timowest** [comment]
@simonered What failure do you get? Which version?

**Comment by simonered** [comment]
Latest version (3.7.1)...trying to use _eq_ on reference's $id, with no luck. 

This is my simplified code:

     public class Book {
         @DBRef
         private Library library;
     } 

    public class Library {
         @Id
         private String id;
     }

    [...]

    QBook book = QBook.book;
    BooleanExpression p = book.library.id.eq([some_id]);
    Predicate p = ExpressionUtils.and(null, p);

    List<Book> list = bookRepository.findAll(p);  // EMPTY

 Custom method in mongo repository `bookRepository.findByLibraryId(String id)` returns the items i'm expecting

**Comment by timowest** [comment]
is this with Spring Data?

**Comment by simonered** [comment]
Yes

**Comment by timowest** [comment]
then the related template methods might not have been overridden in the version you use.

**Comment by simonered** [comment]
Not sure I've understood what you mean...but the one i wrote is a simplified code, just to explain the issue...I'm trying to use QueryDsl for more complex and conditional query on the item, which I *can't* do with template methods...Whatever the reference handling seems not to work...

**Comment by simonered** [comment]
The case is the same as the original [StackOverflow question](http://stackoverflow.com/questions/24202259/spring-mongodb-querydsl-query-by-dbref-related-object)

**Comment by simonered** [comment]
What to you mean for "not been overridden"? What should I have to do?

**Comment by simonered** [comment]
So the issue is confirmed or should I have to do something else to make it work?

**Comment by timowest** [comment]
Sorry for the delay, which Spring Data version do you use?

Here isId seems to be not overridden https://github.com/spring-projects/spring-data-mongodb/blob/master/spring-data-mongodb/src/main/java/org/springframework/data/mongodb/repository/support/SpringDataMongodbSerializer.java

**Comment by simonered** [comment]
I'm using Spring Data MongoDB 1.8.1 (coming from spring boot 1.3.2)

**Comment by simonered** [comment]
Tried to update Spring Data to latest version 1.8.4, but the issue is still present.

**Comment by simonered** [comment]
I think the issue should be reopened.

**Comment by timowest** [comment]
The Spring Data Mongodb Querydsl bindings are maintained by Spring Data, not by us, it seems to be caused by their Querydsl bindings.
