### ISSUE TITLE
ClassPathUtils initialization doesn't work in wildfly

### ISSUE THREAD

**Issue by asm0dey** [querydsl/querydsl#832]
ClassPathUtils don't know how to work with vfs:

Caused by: java.lang.IllegalArgumentException: Illegal url : vfs:/C:/work/smev_admin_panel.git/ear/target/controller.ear/controller-1.6-SNAPSHOT.war/WEB-INF/lib/api-1.6-SNAPSHOT.jar/entity/

I think you could borrow principles of work with vfs from https://github.com/ronmamo/reflections
https://github.com/ronmamo/reflections/tree/master/src/main/java/org/reflections/vfs

This exception is being raised in method ClassPathUtils.scanPackage() (http://www.querydsl.com/static/querydsl/3.4.0/reference/html/ch04s02.html)

**Comment by DanielNoga** [comment]
Is that already fixed in Wildfly? https://issues.jboss.org/browse/ISPN-4667

**Comment by cnsgithub** [comment]
I don't know why it works now, but it seems to be fixed when using the following versions:

- WildFly 10.1.0.Final
- QueryDSL 4.1.4

Maybe the new  com.querydsl.codegen.ClassPathUtils  does it differently than the old mysema class.

**Comment by asm0dey** [comment]
OK, guys, I'm not on wildfly for almost 2 years as of now, so I don't know…

**Comment by jwgmeligmeyling** [comment]
ClassPathUtils was indeed changed to use `Reflections` instead, which solved this issue.
