### ISSUE TITLE
InstanceOf on super-class searches only by super-class discriminator

### ISSUE THREAD

**Issue by mirceade** [querydsl/querydsl#870]
Having:
- single-table inheritance on the three classes below

@MappedSuperclass
abstract class GateEvent extends DomainEvent
...
@Entity
class GateUpdatedEvent extends GateEvent
...
@Entity
class GateDeletedEvent extends GateEvent
...

Using:

query.from(domainEvent).
            where(domainEvent.instanceOf(GateEvent.class)).
            list(domainEvent.as(QGateEvent.class));

Expected result:
select domaineven0_.gateId as col_0_0_, domaineven0_.gateIpAddress as col_0_1_, domaineven0_.gateLocation 
as col_0_2_, domaineven0_.gateName as col_0_3_, domaineven0_.gatePort as col_0_4_ from DomainEvent 
domaineven0_ where 
domaineven0_.DTYPE='GateEvent'  or  
domaineven0_.DTYPE='GateUpdatedEvent' or 
domaineven0_.DTYPE='GateDeletedEvent'

Actual result:
select domaineven0_.gateId as col_0_0_, domaineven0_.gateIpAddress as col_0_1_, domaineven0_.gateLocation 
as col_0_2_, domaineven0_.gateName as col_0_3_, domaineven0_.gatePort as col_0_4_ from DomainEvent 
domaineven0_ where 
domaineven0_.DTYPE='GateEvent'

So it only uses the discriminator of the parent abstract class when generating the query!

**Comment by martinsefcik** [comment]
Workaround is to put all child class types to instaceOf method manually, but it a bit annoying.
