### ISSUE TITLE
list(new QueryProjectionImpl(...)) uses inner join and hides rows

### ISSUE THREAD

**Issue by KlausUnger** [querydsl/querydsl#875]
I have an entity *Fall* which has multiple ManyToOne relations to another entity called *User*, some of them mandatory, some optional.

When I do my query like 

```java
        QFall faelle = QFall.fall;

        return from(faelle)
            .where(faelle.location.eq(Location.TRESOR)
                .and(faelle.category.eq(Category.A))
                .and((faelle.status.eq(Status.A)).or(faelle.status.eq(Status.B))))
            .orderBy(faelle.key.asc())
            .list(faelle);
```

I receive the correct number of rows, but the object graph (with some unneeded fetches) will be materilaized.

The same query using a *QueryProjection* (which shouldn't - at least in my opinion - have an effect on the rows of the resultset) hides all rows, because one of the ManyToOne relations (the uploader) is null.

```java
     .list(new QFallReferenz(faelle.key, faelle.status, faelle.location, faelle.user, 
                             faelle.creator, faelle.modifier, faelle.uploader));
```

When the QueryProjection does the necessary joining, would it be possible to indicate somehow, that I would need an left-outer join? The used inner-join caused the empty result-set.

Any hints welcome and thanks for clarification.

**Comment by johnktims** [comment]
I'm closing this ticket due to lack of response. Feel free to comment if you're still having issues and we'll reopen it.
