### ISSUE TITLE
ANSI nested joins

### ISSUE THREAD

**Issue by robertandrewbain** [querydsl/querydsl#914]
As far as I can tell, querydsl doesn't support ANSI nested joins.

How would the following SQL be directly translated? (I'm aware a subquery can get the same results but it's not as clean IMO)

``` sql
-- Get data on all employees and details of their car, only if it's a BMW
SELECT *
FROM employee e 
LEFT JOIN (car c INNER JOIN manufacturer m ON c.manufacturer_id = m.id AND m.name = 'BMW') 
ON e.id = c.employee_id;
```

**Comment by bennesher** [comment]
Hi @timowest ! I have come up against this limitation as well, and will attempt to implement it as you proposed above. Hopefully I'll have a pull-request ready in a few days. Although I've got a decent idea how to make this work, any pointers are welcome!
