### ISSUE TITLE
Take @Table/@Column annotations into account in JPA native queries

### ISSUE THREAD

**Issue by johnktims** [querydsl/querydsl#926]
I'm generating Q classes from JPA entities using the maven JPAAnnotationProcessor. Normally, I use JPAQuery and everything works but I needed to UNION two queries so I tried to use JPASQLQuery.

Entities with names that map directly to its corresponding table work fine but if it's different then the "table is not found".

Example:

``` java
@Table(name="user")
class User
```

works fine but

``` java
@Table(name="other_user")
class User
```

will still try to generate SQL that refers to a table named `User` and fail.

**Comment by schragmanuel** [comment]
I'm seeing a problem related to this in Version 3.6.9:

My entity has a many to one relation to another entity:

	@javax.persistence.ManyToOne(targetEntity = ch.ims.suisdata.core.model.address.Address.class)
	@javax.persistence.JoinColumn(name = "NADR_ID", nullable = true, updatable = false, insertable = false)
	private Address address;

When i try to do a join, the *on* part is not mapped to the foreign key column:

    new JPASQLQuery(em, new OracleTemplates()).from(qEntity).leftJoin(qAddress).on(qEntity.address.eq(qAddress.));

This results in the query:

    select ... left join ADRESSEN address on errorView.address = address

but it should be

    select ... left join ADRESSEN address on errorView.NADR_ID = address.NID

I'm not sure if I do something wrong in the syntax of the query or if it's a QueryDsl issue.

**Comment by heapify00** [comment]
Same problem for JPQL queries in both v4.4.0 and v5.0.0. I'm using Q classes to construct a predicate on a property annotated with `@Column` and the value of the annotation is not taken into account.

Example:

With this property in my entity class
```
@Column(name = 'propertyname')
private boolean customPropertyName;
```

when I use `qEntity.customPropertyName.isTrue()` I get `entity.customPropertyName = true`
