### ISSUE TITLE
Update guava to latest version

### ISSUE THREAD

**Issue by SchulteDev** [querydsl/querydsl#931]
Please update guava to latest version. For time being, querydsl is using version 14.0;latest stable is 18.0[1].

There are known bugs meanwhile fixed in guava18.0. In special, 14.0 is not deployable to JavaEE7 containers[2].

[1] http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22com.google.guava%22%20AND%20a%3A%22guava%22
[2] https://code.google.com/p/guava-libraries/issues/detail?id=1433

**Comment by ratcashdev** [comment]
How strongly is querydsl (4.0) dependent on Guava? Would it be OK to exclude it completely for a JPA (Eclipselink) & j2EE7 (Glassfish) application?

**Comment by Shredder121** [comment]
We use quite a few features to make up for the Java 6 to 7 bridging(Objects), and for things that should exist in a sane way in the JDK by default (CharMatcher, Sets, Maps).
If you look for Querydsl without Guava I think building it yourself and removing it shouldn't be that much work (?)

**Comment by Shredder121** [comment]
Oh, just remembered, we use the Function interface, so unfortunately I think it requires quite some work.
