### ISSUE TITLE
NumberPath/SimplePath mixup on x64/x86

### ISSUE THREAD

**Issue by balizeiro** [querydsl/querydsl#955]
We are having this weird problem (or maybe we are missing some parameter configuration) that if we compile our project using a x86 JVM everything works OK, but if we use a x64 JVM we get this error during compilation:

    QT_LOG.java:66: incompatible types
    found   : com.mysema.query.types.path.NumberPath<java.lang.Long>
    required: com.mysema.query.types.path.SimplePath<java.lang.Long>
    public final SimplePath<Long> id = _super.id;

This behavior happens if we use ANT as described in here: http://www.querydsl.com/static/querydsl/3.4.3/reference/html/ch02.html#d0e147

    <javac includeantruntime="false" debug="true" debuglevel="source,lines,vars"        
    fork="yes" executable="...x86...or...x64...JAVAC" classpathref="My Project.classpath"
    source="1.6" target="1.6" encoding="iso-8859-1" >
    
        <compilerarg value="-proc:only"/>      
            <compilerarg value="-processor"/>
            <compilerarg value="com.mysema.query.apt.jpa.JPAAnnotationProcessor"/>
            <compilerarg value="-s"/>
            <compilerarg value="c:/myPath/"/>
    
            <src path="${mySourceFolder}" />
    </javac>

If we use Eclipse, we also get the different values (NumberPath/SimplePath) but we don't get any error.

What can we do to fix this?

Tested with QueryDSL 3.2.3 and 3.4.3.

**Comment by johnktims** [comment]
Closing due to lack of response and not having enough information to reproduce the issue. Feel free to comment if you're still having issues and we'll reopen the ticket.
